.pullapprove.yml
Add the pullapprove config file to ensure all PRs are approved before
landing.
Fixes #9.
=> CI: Enable pullapprove

CODE_OF_CONDUCT.md, CONTRIBUTING.md
Add the standard contributing and code of conduct documents.
Fixes #13.
=> docs: Add contributing and code of conduct docs

README.md
We use a packagecloud OSS account for package hosting.
As part of the arrangement with packagecloud we need to
credit them and add a link back to https://packagecloud.io
on our website and project README.
This repository's README is probably the closest we have to
a "project README", so let's add it here.
=> Credit packagecloud for package hosting

src/agent/src/config.rs, src/agent/src/main.rs
Create a config module and add more tests. Also enable setting the log level from the kernel command-line.
Fixes: #59, #63.
=> main: Split config code into separate module

.travis.yml, src/agent/README.md, src/agent/src/mount.rs
The get_key_value method is currently only avaiable in nightly rust.
As only this feature is required it worth to refactor and enable building
in the stable channel.
The method was removed by first getting the value from the CGROUPS hashmap,
then key is get by iterating over all the keys. The checks for an empty key and
key == "devices" were moved out of the hashmap block.
The README.md was updated as well to detail the instructions for stable rust.
=> agent: Remove `get_key_value` to enable building in stable rust.

src/agent/Makefile
Since build with --release produces corrupted binary in ci, we removed
--release. However, the make install target cannot find the binary,
set BUILDTYPE to debug
=> rust-agent: Set BUILDTYPE to debug.

src/agent/rustjail/src/container.rs, src/agent/src/random.rs
Fixes to allow the rust agent to be built using a gnu target. Specifically, remove assumptions about musl-specific types.
Fixes: #70.
=> build: Allow building with gnu target

src/agent/src/main.rs, src/agent/src/mount.rs, src/agent/src/test_utils.rs
The `skip_*` macros will be useful across the different tests so having
them in a separate module can help with code duplication. This change
creates a new module and exports the macros at crate level.
=> agent: Move test macros to a separate module to be commonly used.

src/agent/src/config.rs, src/agent/src/device.rs, src/agent/src/main.rs, src/agent/src/mount.rs
This adds an option to the agent to control the hotplug timeout of block devices.
Retains the previous behaviour of defaulting to 3 seconds if not specified.
Can be increased when block device hot plugging is taking longer than expected.
fixes #62
Signed-off-by: Alex Price <aprice@atlassian.com>
=> config: add hotplug timeout option

src/agent/src/netlink.rs
Invalid routes in update_routes request crash agent, fix it
Fixes: #73
=> netlink: Fix invalid route crashes agent

ci/static-checks.sh, src/agent/src/config.rs, src/agent/src/device.rs, src/agent/src/main.rs, src/agent/src/mount.rs
The CI was failing due to two problems.
1. The `ci/static-checks.sh` was run from an incorrect place.
2. `rustfmt` was failing as some code wasn't correctly formatted.
This patch address all the changed requested by rustfmt and the
`static-checks.sh` script was updated
Fixes: #83
=> agent: Fix CI and rustfmt issues

src/agent/src/main.rs
Support `--version` which dumps the announce message and exits.
Fixes: #80.
=> Add version option

src/agent/src/main.rs, src/agent/src/namespace.rs, src/agent/src/sandbox.rs
This patch adds a unit test for `namespace.rs`. The baseline for this
test comes from the Go agent tests. It turns out that the Go version of
this test creates a temp folder for `ipc` and `uts`, however these folders
doesn't has an effect in the tested code, therefore the implementation of
such temporal folders was removed.
Fixes: #50
=> agent: Add unit tests for `namespace.rs`

src/agent/oci/src/lib.rs, src/agent/oci/src/serialize.rs
Minor improvement to agent/oci crate:
1) clean up clippy warnings.
2) get rid of unnecessary & and mut.
3) normalize Error/Result.
=> Minor improvement to agent/oci crate

Makefile, ci/go-test.sh, ci/lib.sh
This adds a basic Makefile where we can use a central go test script
in order to run the tests for the CI.
Fixes #109
=> ci: Add minimal makefile to use central go test script

ci/lib.sh
This PR removes a function that is never used as the script that is
referring is also non existing at the test repository.
Fixes #113
=> ci: Remove run_rust_test functions as not being used

src/agent/.cargo/config, src/agent/src/linux_abi.rs
Hi, guys
I'm starting to work on running rust-agent on AArch64.
I'm already found a few bugs:
- **Like Kata Containers, for now, aarch64 is the only supported platform**
```
error[E0425]: cannot find value `PCI_ROOT_BUS_PATH` in this scope
--> src/uevent.rs:53:41
|
53 |             && self.devpath.starts_with(PCI_ROOT_BUS_PATH)
|                                         ^^^^^^^^^^^^^^^^^ not found in this scope
error[E0425]: cannot find value `PCI_ROOT_BUS_PATH` in this scope
--> src/uevent.rs:72:46
|
72 |                 let pci_p = format!("{}/{}", PCI_ROOT_BUS_PATH, *dev_addr);
|                                              ^^^^^^^^^^^^^^^^^ not found in this scope
```
- **Missing symbols on target `aarch64-unknown-linux-musl`**
```
= note: …
```
=> Running rust-agent on AArch64

src/agent/Cargo.toml, src/agent/src/grpc.rs, src/agent/src/main.rs
It should restore to it's previous cwd after it
create container in which it would change it's
cwd to container's bundle path.
Fixes: #126
=> fix the issue of missing restore process's cwd

src/agent/src/grpc.rs
To check is the oci spec passed in, other wise,
it would crash the agent unwrap it directly.
Fixes: #124
=> agent: fix the issue of crash agent without spec

src/agent/Cargo.toml, src/agent/logging/Cargo.toml, src/agent/logging/src/lib.rs, src/agent/src/main.rs
Since the codes in logging.rs is weakly related to the project,
separating it from the project will reduce coupling and make it reusable.
Fixes: #131
=> Agent: Separate logging into a single crate

src/agent/Makefile
This reverts commit a3e46a369f0bd51b146a7f618d50f53258890327.
There is still problem with static link, built binary will
segmentfault on clearlinux. So revert this patch for now.
Depends-on: github.com/kata-containers/tests#2293
Fixes: #69
=> Revert: "Makefile: Fix rust agent build using "--release"."

src/agent/rustjail/src/container.rs
For cases:
- `a`:  no value, will be omit
- `a=b=c`: key is `a`, value will be `b=c`
Fix #135 
Thanks @jodh-intel  for suggestion.
=> should ignore  invalid a key-value pair as an env

src/agent/Makefile, src/agent/kata-agent.service.in, src/agent/kata-containers.target, src/agent/rustjail/Cargo.toml
I add another sub-command `build-service` in Makefile to generate rust-agent-related systemd service files, which are necessary for building guest rootfs image.
The whole design is following the one in go-agent. 
And since I just copy the file [kata-conatiners.target](https://github.com/kata-containers/agent/blob/master/kata-containers.target) and [kata-agent.service](https://github.com/kata-containers/agent/blob/master/kata-agent.service.in) and paste them here, I don't change the copyright info in the header. Hope I'm doing the right thing???😜
=> systemd-service: build rust-agent systemd services

src/agent/oci/src/lib.rs, src/agent/rustjail/src/capabilities.rs, src/agent/rustjail/src/cgroups/fs/mod.rs, src/agent/rustjail/src/cgroups/mod.rs, src/agent/rustjail/src/container.rs, src/agent/rustjail/src/errors.rs, src/agent/rustjail/src/lib.rs, src/agent/rustjail/src/mount.rs, src/agent/rustjail/src/process.rs, src/agent/rustjail/src/specconv.rs, src/agent/rustjail/src/sync.rs, src/agent/rustjail/src/validator.rs, src/agent/src/device.rs, src/agent/src/grpc.rs, src/agent/src/main.rs, src/agent/src/sandbox.rs
In the previous implementation, create a container process
by forking the parent process as the container process,
and then at the forked child process do much more setting,
such as rootfs mounting, drop capabilities and so on, at
last exec the container entry cmd to switch into container
process.
But since the parent is a muti thread process, which would
cause a dead lock in the forked child. For example, if one
of the parent process's thread do some malloc operation, which
would take a mutex lock, and at the same time, the parent forked
a child process, since the mutex lock status would be inherited
by the child process but there's no chance to release the lock
in the child since the child process only has a single thread
which would meet a dead lock if it would do some malloc …
=> Refactor the way of creating container process

src/agent/rustjail/src/container.rs, src/agent/src/grpc.rs
Add the container id and exec id to start container's log
which would make it clearly to check the log.
Fixes: #173
=> unify the rustjail's log to contain container id and exec id

src/agent/src/grpc.rs, src/agent/src/namespace.rs, src/agent/src/sandbox.rs
When setup the persisten uts namespace, it's should
set the hostname for this ns.
Fixes: #175
=> sandbox: fix the issue of missing setting hostname

src/agent/rustjail/src/validator.rs
add license header to `src/agent/rustjail/src/validator.rs`
Fixes: #184.
Signed-off-by: Salvador Fuentes <salvador.fuentes@intel.com>
=> license: add license header

.github/workflows/main.yaml
the actions upload/download-artifact moved to a new version
and master now is not comptible.
Fixes: #211
Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>
=> backport: release: actions: pin artifact to v1

src/agent/Makefile
There maybe a bug in the 1.43.1 cargo, so we need install rust back
to 1.42.0 to avoid the failure when make the rust agent using the latest
rust.
also, I raise an issue in cargo community, see https://github.com/rust-lang/cargo/issues/8258 
Fixes: #202
@GabyCT @jodh-intel  @grahamwhaley
=> ci: install rust back to 1.42.0 to avoid ci failure.

Makefile, src/agent/Makefile, src/agent/protocols/hack/update-generated-proto.sh, src/agent/protocols/protos/agent.proto, src/agent/protocols/protos/github.com/kata-containers/agent/pkg/types/types.proto, src/agent/protocols/protos/health.proto, src/agent/protocols/protos/oci.proto
In Kata 1.x, agent interface is defined in agent repo and vendored by runtime. But in Kata 2.0, agent and runtime will use ttrpc as protocol, and agent is using rust language, so runtime can't vendor agent again, have to compile from agent's protobuf files.
This PR will hold proto files under src/agent, and compile it to rust/go sources for agent/runtime. Typing `make generate-protocols` under root of this repo or `src/agent` can see how to use it.
=> Agent: centrally manage proto files

src/agent/protocols/hack/update-generated-proto.sh
Got:
make PROTO_FILE=agent.proto generate-protocol
google/protobuf/descriptor.proto: Read access is denied for file: /usr/local/include/google/protobuf/descriptor.proto
This commit will fix this error.
=> agent: fix make generate-protocols errors

src/runtime/data/kata-collect-data.sh.in
Updated `kata-collect-data.sh` to gather basic podman details and containerd shim v2 logs.
Also fixed a minor legacy package bug, ksm throttler log collection issue and whitespace and ordering issues.
Fixes: #243.
=> runtime: Add podman and containerd shim v2 to data collection script

README.md, src/trace-forwarder/Cargo.toml, src/trace-forwarder/Makefile, src/trace-forwarder/README.md, src/trace-forwarder/src/handler.rs, src/trace-forwarder/src/main.rs, src/trace-forwarder/src/server.rs, src/trace-forwarder/src/tracer.rs
Add a new system component, used only when tracing is enabled. The component listens to the agent over VSOCK, forwarding trace spans created by the agent in the virtual machine onwards to an OpenTelemetry collector (such as Jaeger) running on the host.
Fixes: #224.
=> src: Add trace forwarder component

src/runtime/data/kata-collect-data.sh.in
Now that the Kata containerd shim v2 can display a version string, add those details to the data collection script.
Fixes: #309.
=> runtime: Add containerd shim v2 version to collect script

src/runtime/arch/ppc64le-options.mk, src/runtime/virtcontainers/qemu_ppc64le.go
This series brings the following ppc64le fixes to the 2.0 tree
- #2657 - Remove hard coding qemu-options to work with qemu-5.0
- #2738 - default qemu binary path to work with Fedora and Ubuntu distros
=> [Forward port] Bring ppc64le fixes to 2.0 dev tree

src/runtime/virtcontainers/qemu_ppc64le.go, src/runtime/virtcontainers/qemu_ppc64le_test.go
The Qemu version check in unit test case is no longer needed for
Power since we don't support Kata with Qemu version < 4.x.
Fixes: #315
Signed-off-by: bpradipt@in.ibm.com
=> qemu: Remove Qemu version check in ppc64le unit test

src/runtime/data/kata-collect-data.sh.in
Improve the output of the data collection script to use lots more folds.
This makes it easier to review the information when viewing the pasted output in a GitHub issue.
Fixes: #313.
=> runtime: Use more folds in collect script

src/agent/src/device.rs, src/agent/src/main.rs, src/agent/src/rpc.rs
device: Do not allow container access to the guest rootfs device
With this change, a container is not longer given access to
the underlying root partition.
This is done by explicitly adding the root partition
to the device cgroup of the container.
Fixes: #317
=> Port rootfs access fix to rust agent

src/agent/Cargo.lock, src/runtime/virtcontainers/agent.go, src/runtime/virtcontainers/api.go, src/runtime/virtcontainers/api_test.go, src/runtime/virtcontainers/clh.go, src/runtime/virtcontainers/container.go, src/runtime/virtcontainers/device/config/pmem.go, src/runtime/virtcontainers/kata_agent.go, src/runtime/virtcontainers/kata_agent_test.go, src/runtime/virtcontainers/mount.go, src/runtime/virtcontainers/mount_test.go, src/runtime/virtcontainers/noop_agent.go, src/runtime/virtcontainers/noop_agent_test.go, src/runtime/virtcontainers/qemu.go, src/runtime/virtcontainers/qemu_test.go, src/runtime/virtcontainers/virtcontainers_test.go, src/runtime/virtcontainers/vm.go
The PR ports following runtime commits up till 1.11.1 stable release 
shm: handle shm mount backed by empty-dir memory volumes
virtcontainers: Fix structured logging in device/config package
logging: Fix structured logging in store package
vc: make host shared path readonly
=> port runtime stable commits

src/runtime/virtcontainers/api.go, src/runtime/virtcontainers/pkg/cgroups/manager.go
Call the `pkg/cgroups` package `SetLogger()` function to ensure all its log
records contain all required structured logging fields.
Fixes: #2782
=> virtcontainers: Fix structured logging in cgroups package

src/runtime/cli/config/configuration-fc.toml.in, src/runtime/cli/config/configuration-qemu-virtiofs.toml.in, src/runtime/cli/config/configuration-qemu.toml.in, src/runtime/go.mod, src/runtime/go.sum, src/runtime/pkg/katautils/config-settings.go.in, src/runtime/pkg/katautils/config.go, src/runtime/vendor/github.com/intel/govmm/qemu/qemu.go, src/runtime/virtcontainers/hypervisor.go, src/runtime/virtcontainers/pkg/annotations/annotations.go, src/runtime/virtcontainers/pkg/oci/utils.go, src/runtime/virtcontainers/pkg/oci/utils_test.go, src/runtime/virtcontainers/qemu.go, src/runtime/virtcontainers/qemu_amd64.go, src/runtime/virtcontainers/qemu_amd64_test.go, src/runtime/virtcontainers/qemu_arch_base.go, src/runtime/virtcontainers/qemu_arch_base_test.go, src/runtime/virtcontainers/qemu_arm64.go, src/runtime/virtcontainers/qemu_ppc64le.go, src/runtime/virtcontainers/qemu_s390x.go
Add vIOMMU support to q35 machines
Use vIOMMU support added to govmm (link)
Add a configuration.toml switch and a Pod annotation
If enabled:
Add "kernel_irqchip=split" to machine options.
Add iommu device: "--device intel-iommu,intremap=on,device-iotlb=on,caching-mode=on"
Add iommu params to kernel command line
Fixes #2694
=> [foward port] Add vIOMMU support to qemu q35

src/runtime/virtcontainers/qemu_ppc64le.go, src/runtime/virtcontainers/qemu_ppc64le_test.go
qemu_ppc64le.go applies some qemu and kernel options which make no sense for ppc64, since they're x86 specific.
=> Don't use some x86 specific kernel and qemu options

src/runtime/cli/kata-env_test.go, src/runtime/containerd-shim-v2/create_test.go, src/runtime/containerd-shim-v2/service.go, src/runtime/pkg/katatestutils/utils.go, src/runtime/pkg/katautils/config_test.go, src/runtime/virtcontainers/acrn.go, src/runtime/virtcontainers/qemu.go, src/runtime/virtcontainers/sandbox.go
This series bring fixes for the following issues:
- #2727 - Ineffective error variable for deferred func in service#StartShim
- #2726 - the error return from GetAndSetSandboxBlockIndex() should be checked
- #2686 - katatestutils should use config.virtioFSDaemon
- #2682 - Runtime crash when virtiofsd is not executable
=> [forward port] Bring to the development branch fixes provided by Christophe De Dinechin and Ted Yu.

src/runtime/virtcontainers/qemu.go, src/runtime/virtcontainers/qemu_amd64.go, src/runtime/virtcontainers/qemu_amd64_test.go, src/runtime/virtcontainers/qemu_arch_base.go, src/runtime/virtcontainers/qemu_arch_base_test.go, src/runtime/virtcontainers/qemu_arm64.go, src/runtime/virtcontainers/qemu_arm64_test.go, src/runtime/virtcontainers/qemu_ppc64le.go, src/runtime/virtcontainers/qemu_ppc64le_test.go, src/runtime/virtcontainers/qemu_s390x.go, src/runtime/virtcontainers/qemu_s390x_test.go, src/runtime/virtcontainers/qemu_test.go
We have some tables in qemuArchBase where only one element is actually used.  Here are some simple cleanups to simplify those.
=> Clean up some unnecessary data structures

src/runtime/containerd-shim-v2/create.go, src/runtime/containerd-shim-v2/utils.go
Removing code that existed as a workaround for a bug in
how shared process namespaces were handled in the agent.
That has been long fixed in the agent.
With this, sharedPidNs will now work with shimv2.
=> shimv2 : Remove workaround for sharedPidNs

Makefile, src/agent/Makefile, utils.mk
Define a set of functions that support the standard rules (build, install, test, *etc*). Then simply add new components and tools to the appropriate variable to support all the standard build semantics.
Fixes #331.
=> build: Improve top-level Makefile

src/runtime/cli/config/configuration-fc.toml.in, src/runtime/cli/config/configuration-qemu-virtiofs.toml.in, src/runtime/cli/config/configuration-qemu.toml.in, src/runtime/virtcontainers/clh.go, src/runtime/virtcontainers/clh_test.go, src/runtime/virtcontainers/qemu_arm64.go, src/runtime/virtcontainers/qemu_arm64_test.go, src/trace-forwarder/Makefile, tools/agent-ctl/Makefile, versions.yaml
Port these runtime commits:
868f687 versions: Remove golangci-lint and gometalinter entries
ee985a6 qemu: arm64: Set defaultGICVersion to 3 to limit the max vCPU number
c4b5922 versions: Misc changes to descriptions
4d4a153 qemu: arm64: Don't detect gic version by /proc/interrupts
e36389e dax: enable dax on arm64
7e47046 vc: Version support check is ineffective in createSandbox
=> port runtime commits -- wave 1

versions.yaml
New features that can improve/impact in kata containers:
x86:
VMX features can be enabled/disabled via the "-cpu" flag.
When nested virtualization is enabled with an option like
"-cpu Haswell,+vmx", the set of VMX features will also be constrained to
what was available on the corresponding CPU model.
New "microvm" machine type that has virtio-mmio instead of PCI, and no ACPI
support (so no hotplug too). The new machine type is meant as a baseline
for performance optimizations of QEMU, firmware and guests. While inspired
by Firecracker it is not entirely compatible with it (for example it does
not have Firecracker's userspace IP stack and MicroVM Metadata Service).
Reduce memory footprint when booting uncompressed kernels.
ARM:
We now correctly support more than 256 CPUs when using KVM
The …
=> versions: update QEMU to 5.0.0

versions.yaml
We can only handle SEMVER-style versions in the script.
=> versions: specify rust version

src/agent/src/device.rs
When the "PCIAddr" (BDF information) is available, we allow to use the
predicted "VmPath" (from kata-runtime) to locate the block device in the
agent. This is a special code path for supporting block-device/volume
passthrough w/ cloud-hypervisor when the BDF information is not
available (as of clh v0.8.0).
This is mainly porting the changes from kata-agent PR https://github.com/kata-containers/agent/pull/790,
as the related changes from kata-runtime is ported to kata 2.0 earlier
this week (https://github.com/kata-containers/kata-containers/pull/362).
Note that the upstream clh recently added the support of returning BDF
information for hotplugged devices. We will consolidate/remove this
special code path for the next upgrade of clh version in kata.
Fixes: #248
Signed-off-by: Bo Chen …
=> agent: device: Allow "VmPath" to be used when adding block devices

tools/packaging/scripts/lib.sh, versions.yaml
This reverts commit 15af20b6dac6f427892405c3e4b064e0c8fe2cd6.
kubernetes test are failing randomly with QEMU 5.0.0, let's go back to
QEMU 4.1.1 and debug the failures with QEMU 5
Depends-on: github.com/kata-containers/tests#2701
fixes #379
=> versions: Revert "versions: update QEMU to 5.0.0"

src/runtime/containerd-shim-v2/errors_test.go, src/runtime/containerd-shim-v2/wait.go
For now, agent return status of NotFound when calling getOOMEvents, runtime should handle it correctly.
Fixes: #393
=> runtime: handle unimplemented RPC call by NotFound status code

src/runtime/pkg/katautils/config.go
Since the FC used the hybrid vsock, there's no need
to check whether the vhost vsock suported by host.
Fixes: #387
=> config: there is no need to check vhost-vosck for FC

src/runtime/cli/config/configuration-acrn.toml.in, src/runtime/cli/config/configuration-clh.toml.in, src/runtime/cli/config/configuration-fc.toml.in, src/runtime/cli/config/configuration-qemu-virtiofs.toml.in, src/runtime/cli/config/configuration-qemu.toml.in, src/runtime/cli/kata-monitor/main.go, src/runtime/containerd-shim-v2/create.go, src/runtime/containerd-shim-v2/shim_management.go, src/runtime/pkg/kata-monitor/metrics.go, src/runtime/pkg/kata-monitor/monitor.go, src/runtime/pkg/kata-monitor/pprof.go, src/runtime/pkg/kata-monitor/pprof_test.go, src/runtime/pkg/kata-monitor/sandbox_cache.go, src/runtime/pkg/katatestutils/utils.go, src/runtime/pkg/katautils/config.go, src/runtime/pkg/katautils/config_test.go, src/runtime/virtcontainers/pkg/annotations/annotations.go, src/runtime/virtcontainers/pkg/oci/utils.go
Add new http interfaces to support pprof:
- /sandboxes
- /debug/vars
- /debug/pprof/
- /debug/pprof/cmdline
- /debug/pprof/profile
- /debug/pprof/symbol
- /debug/pprof/trace
Fixes: #397
See #397 for details.
=> runtime: add pprof interface for shim

src/runtime/.gitignore
monitor_address may be committed to repo by accident
Fixes: #403
=> runtime: add monitor_address to .gitignore

docs/how-to/how-to-load-kernel-modules-with-kata.md
To pass annotations from CRI to Kata containers, user must configure containerd if containerd is used.
User may miss this configuration.
Related https://github.com/kata-containers/documentation/issues/683
=> docs: add link to CRI Configuration for pods

src/agent/rustjail/src/container.rs, src/agent/src/namespace.rs, src/agent/src/rpc.rs, src/agent/src/sandbox.rs
Add rust agent sandbox shared pid namespace.
this PR only support shared pid namespace by
sharing the infrastructure pause container's pid namespace
with other containers, instead of creating a new pid
namespace different from pause container.
=> add rust agent sandbox shared pid namespace support

src/runtime/virtcontainers/device/manager/utils.go, src/runtime/virtcontainers/device/manager/utils_test.go
When checking if a device is an emulated vhost-user-blk or
vhost-user-scsi one, we should not only check for their major number but
also their device node type. They must be block devices.
Fixes: #401
Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>
=> runtime: virtcontainers: vhost-user-blk/scsi are block device nodes

docs/how-to/how-to-set-sandbox-config-kata.md
Using pod annotations requires a minimum version of v1.3.0 of containerd
to pass annotations down to kata. This is already somewhat mentioned in
the corresponding how-to, however, it can be mis-read as the minimum
version of kata-containers instead of containerd. This can cause
extended and futile troubleshooting on older distributions such as
Ubuntu 16.04 which ship a version of 1.2.x of containerd. This patch
attempts to clarify this.
Fixes: #690
Signed-off-by: Georg Kunz <georg.kunz@est.tech>
=> docs: Clarifying minimum version of containerd for annotations

src/agent/rustjail/src/cgroups/fs/mod.rs
Fix the issue of applying/set to unsupported cgroups.
Fixes: #408
=> cgroup: fix the issue of crashed when meet unsupported cgroup

src/runtime/virtcontainers/types/bridges_test.go
Add function that creates new bridges to increase unit test coverage
for virtcontainers/types/bridges. Also adds test for address formats.
Fixes #422
=> virtcontainers: Add to bridges unit test

.github/workflows/PR-wip-checks.yaml, .github/workflows/dco-check.yaml
Since actions can access the github token, lets use a
particular version of sha rather than using master.
=> actions: Pin to a particular sha for actions

src/agent/src/device.rs
For docker in docker scenario, the nested container created
has entry "b *:* m" in the list of devices it is allowed to access
under /sys/fs/cgroup/devices/docker/{ctrid}/devices.list.
This entry was causing issues while starting a nested container
as we were denying "m" access to the rootfs block devices.
With this change we add back "m" access, the container would be
allowed to create a device node for the rootfs device but will
not have read-write access to the created device node.
This fixes the docker in docker use case while still making sure
the container is not allowed read/write access to the rootfs.
Note, this could also be fixed by simply skipping {"Type : "b"}
while creating the device cgroup with libcontainer.
But this seems to be undocumented behaviour at this point,
hence …
=> device: Ease device access for rootfs device to allow node creation

src/runtime/virtcontainers/sandbox.go
A container that is created and added to a sandbox can still fail
the final creation steps. In this case, the container must be stopped
and have its resources cleaned up to prevent leaking sandbox mounts.
This PR is a port of https://github.com/kata-containers/runtime/pull/2826
CC @fidencio 
Fixes #2816
Signed-off-by: Evan Foster <efoster@adobe.com>
=> sandbox: Stop and clean up containers that fail to create

ci/lib.sh
So that we use 2.0-dev branch for tests.
Fixes: kata-containers/tests#2732
=> ci: checkout TRAVIS_BRANCH

src/runtime/README.md
This PR fixes travis and go report carl url for the runtime README for kata
2.0
Fixes #432
=> docs: Update travis and go report card url

src/runtime/cli/kata-env.go, src/runtime/cli/kata-env_amd64_test.go, src/runtime/cli/kata-env_generic_test.go, src/runtime/cli/kata-env_test.go
Add host memory size(Total/Free/Avaiable) and CPU cores in host info
for `kata-runtime kata-env`.
Fixes: #405
Output:
```
[Host]
Kernel = "5.4.0-31-generic"
Architecture = "amd64"
VMContainerCapable = true
SupportVSocks = true
[Host.Distro]
Name = "Ubuntu"
Version = "20.04"
[Host.CPU]
Vendor = "GenuineIntel"
Model = "Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz"
CPUs = 2
[Host.Memory]
Total = 4030680
Free = 2914716
Available = 3612320
```
=> runtime: add CPU cores and memory basic info for `kata-env` sub-command

src/runtime/virtcontainers/types/capabilities_test.go
Add function that tests multiqueue functions in types/capabilities.go.
Fixes #428
=> virtcontainers: Add function to capabilities test

src/runtime/arch/arm64-options.mk
As cloud-hypervisor has enabled for arm64, add CLHCMD in
arm64-options.mk
Fixes: #468
@jodh-intel @devimc
=> Makefile: add CLHCMD in arm64-options.mk

src/runtime/virtcontainers/qemu_arch_base.go, src/runtime/virtcontainers/qemu_arm64.go
As the current qemu of arm64 is so old, the new multidev parameter
in fsdev is not supported on arm64, so disabled it temporarily.
Fixes:#466
@bergwolf @devimc @Pennyzct
=> qemu: remove multidev in fsdev parameter on arm64

src/runtime/go.mod, src/runtime/go.sum, src/runtime/vendor/github.com/intel/govmm/qemu/qemu.go, src/runtime/vendor/modules.txt, src/runtime/virtcontainers/qemu.go, src/runtime/virtcontainers/qemu_test.go
This is a port of the NoReboot changes [1] merged into 1.12.x
One change needed in qemu_test.go was dropping the last parameter in the call to createSandbox()
I also changed the govmm commit to use go modules. I'm not sure if I should have deleted the old govmm lines (167-168) in go.sum
[1] https://github.com/merwick/runtime/commit/77e3024cd0ab2e865953667ec49ebd742e2fed1b
=> Kata 2.0-dev port of #2867 (NoReboot Knob)

src/agent/rustjail/src/container.rs
=> Fix fd leakage in execute_hook

docs/Limitations.md
This PR updates the contributions sections for the limitations document
for kata 2.0 that instead using the previous runtime repository as example,
it will use the new one.
Fixes #476
=> docs: Update contributions section in limitations document kata 2.0

src/runtime/containerd-shim-v2/container.go, src/runtime/containerd-shim-v2/exec.go, src/runtime/containerd-shim-v2/service.go, src/runtime/containerd-shim-v2/start.go, src/runtime/containerd-shim-v2/stream.go
It should wait until the stdin io copy
termianted to close the process's io stream,
otherwise, it would miss forwarding some contents
to process stdin.
Fixes: #439
=> shimv2: fix the issue  of close IO stream

src/runtime/virtcontainers/types/container_test.go
Add unit tests for types/container.go. Tests were adapted from
sandbox_test.go since ContainerState is a sandbox state structure and
the transition tests are the same.
Fixes #451
=> virtcontainers: Add unit test for types/container.go

docs/Developer-Guide.md
This PR removes the installation of proxy in the Developer Guide as it
does not exist on kata 2.0
Fixes #502
=> docs: Remove installation of proxy

.github/workflows/commit-message-check.yaml
- Fixes #519 
- Fixes #520 
- Do not limit the length of single word in commit body
- Add commit-body-missing check
- Some minor updates
=> Fix commit-message-check and do some updates about github actions

src/runtime/virtcontainers/documentation/api/1.0/api.md
Some type declarations were changed. The example code here is outdated
according to the example_pod_run_test.go under virtcontainers directory.
And add the imports to make where the types from clear.
Fixes: #507 
Signed-off-by: Li Ning <lining_yewu@cmss.chinamobile.com>
=> virtcontainers: fix outdated example code in api document

tools/packaging/kernel/README.md, tools/packaging/kernel/build-kernel.sh
Add -a option in script usage function and README.
Fixes #534
Signed-off-by: Jason Zhang <zhanghj.lc@inspur.com>
=> packaging: add usage instructions for -a (arch_target) option

tools/osbuilder/rootfs-builder/rootfs.sh
For building rust agent on `ppc64le`, the rust toolchain is built using the `LIBC`
implementation - `gnu` instead of `musl`.
Fixes: #481
=> osbuilder : ppc64le support for rust agent based rootfs/initrd image

.github/workflows/commit-message-check.yaml
\h is not a valid metacharacter in javascript which is used in
github-action.
Use \s\t to replace it.
Fixes: #551
=> action: Fix subsystem check

src/agent/README.md
switched from grpc to ttrpc (a7041c27d)
fixs #558
Signed-off-by: Snir Sheriber <snir911@gmail.com>
=> docs: remove outdated dependencies from agent docs

src/runtime/go.mod, src/runtime/go.sum, src/runtime/vendor/github.com/intel/govmm/qemu/qemu.go, src/runtime/vendor/github.com/intel/govmm/qemu/qmp.go, src/runtime/vendor/modules.txt
This is a re-vendor of intel/govmm, with support for hot-plugging IBM Adjunct Processor (AP) devices over VFIO. This is necessary for enabling AP device pass-through in Kata (see #491).
/cc @alicefr
Fixes: #565
=> runtime: Re-vendor GoVMM for hotplugging IBM Adjunct Processor (AP) devices over VFIO

src/runtime/virtcontainers/sandbox.go
When a one-shot pod dies in CRI-O, the shimv2 process isn't killed until the pod is actually deleted, even though the VM is shut down. In this case, the shim appears to busyloop when attempting to talk to the (now dead) agent via VSOCK. To address this, we disconnect from the agent after the VM is shut down.
This is especially catastrophic for one-shot pods that may persist for hours or days, but it also applies to any shimv2 pod where Kata is configured to use VSOCK for communication.
Fixes kata-containers/runtime#2719
Signed-off-by: Evan Foster <efoster@adobe.com>
=> sandbox: Disconnect from agent after VM shutdown

src/runtime/virtcontainers/utils/utils_test.go
Expand unit tests for virtcontainers/utils/utils.go to include testing
CleanupFds, CPU calculations, ID string creation, and memory alignment
functions.
Fixes #490 
Signed-off-by: Chelsea Mafrica chelsea.e.mafrica@intel.com
Ported from 1.x [#2881](https://github.com/kata-containers/runtime/pull/2881)
=> virtcontainers: Add to utils unit tests

src/agent/Cargo.lock, src/agent/rustjail/src/container.rs, src/agent/src/rpc.rs, src/agent/src/sandbox.rs, tools/agent-ctl/Cargo.lock
The PR adds the missing rust agent capability of guest hooks:
1. create container bundle path in a tmpfs location
2. bind mount all rootfs and volumes to directories inside the bundle
3. write config.json in the bundle
=> agent: support guest hooks

src/agent/Cargo.lock, src/agent/src/main.rs
The logic for the debug console meant that if the debug console was _disabled_, the agent was guaranteed to crash on function exit due to the unsafe code block. Fixed by simplifying the code to use the standard `Option` idiom for optional values.
Fixes: #554.
---
Note: This PR includes a few other fixes which are part of #411. However, the tracing PR is still not ready and since these fixes are not actual trace changes, I'd like to land them before yet-more rebase hell caused by tracking the branch head :smile:
=> console: Fix crash if debug console disabled

tools/packaging/kernel/configs/fragments/s390/vfio-ap.conf
Add vfio-ap.conf to the s390 kernel config fragments, which includes the necessary flags for passing an IBM Adjunct Processor (AP) device over VFIO.
See also issue #491 on supporting VFIO-AP in Kata.
/cc @alicefr
Fixes: #567
=> packaging: Add VFIO-AP fragment for s390x

src/agent/rustjail/src/container.rs
Otherwise file owner in container may not read/write such devices.
Fixes: #570
Signed-off-by: Eryu Guan <eguan@linux.alibaba.com>
=> rustjail: default permission of device node should be 666

src/agent/Cargo.lock, src/agent/src/config.rs, src/agent/src/main.rs, src/agent/src/rpc.rs
Allow the default (VSOCK) ttRPC server address to be changed using a new `KATA_AGENT_SERVER_ADDR` environment variable (for testing and debugging).
Fixes: #552.
=> server: Allow address to be specified

src/agent/Makefile
Run `make optimize` will strip the binary.
Fixes: #626
=> agent: Add target optimize for Makefile

tools/agent-ctl/src/client.rs, tools/agent-ctl/src/main.rs, tools/agent-ctl/src/rpc.rs, tools/agent-ctl/src/types.rs, tools/agent-ctl/src/utils.rs
Rather than specifying the VSOCK address as two CLI options (`--vsock-cid` and `--vsock-port`), allow the agent's ttRPC server     address to be specified to the `agent-ctl` tool using a single URI `--server-address` CLI option. Since the ttrpc crate supports VSOCK and UNIX schemes, this allows the tool to be run inside the VM by specifying a UNIX address.
Fixes: #549.
=> tools: Add Unix socket support to agentl-ctl

versions.yaml
Upgrade Alpine version from unsupported 3.7 to supported 3.12
Fixes #610
Signed-off-by: Jan Schintag jan.schintag@de.ibm.com
=> initrd: Increase Alpine Version to 3.12

docs/how-to/how-to-use-virtio-fs-with-kata.md
Update this document to get rid of any nemu mentions.
Added comment to mention that number of containers that can be
launched may be limited by the size of `/dev/shm`.
Fixes #572
=> Foward-port :virtiofs: Update virtiofs docs

src/runtime/virtcontainers/clh.go
We kept observing instabilities from CLH CI jobs periodically (kata
1.x). To separate the random failures caused by `seccomp` from other
failures, this patch disables the 'seccomp' option from clh in kata for
now. We will bring this option back after completing the 'seccomp'
filter lists based on Kata's CI workload. Details are tracked in the
following two issues:
https://github.com/kata-containers/runtime/issues/2899 and
https://github.com/kata-containers/runtime/issues/2901
We are facing the similar challenge to stabilize CI jobs related to
cloud-hypervisor in Kata 2.0. We are disabling the `seccomp` option here
for the same reason. Related issue:
https://github.com/kata-containers/tests/issues/2813
Fixes: #614
=> clh: Disable the 'seccomp' option temporarily

src/agent/src/mount.rs, src/agent/src/sandbox.rs
fix the issue of epthemeral storage handler
For ephemeral storage handler, it should return an
empty string instead of the mount destination.
Fixes: #635
=> Fix epthemeral mount issue

pkg/logging/Cargo.toml, src/agent/Cargo.toml, src/agent/netlink/Cargo.toml, src/agent/oci/Cargo.toml, src/agent/protocols/Cargo.toml, src/agent/rustjail/Cargo.toml, src/trace-forwarder/Cargo.toml, tools/agent-ctl/Cargo.toml
Anyone can collaborate in the Kata Containers project, so instead of
adding her/his name and email to the Cargo.toml files, use
`The Kata Containers community` as name and
`kata-dev@lists.katacontainers.io` as email.
fixes #643
=> agent: update Cargo files authors

src/runtime/virtcontainers/qemu.go, src/runtime/virtcontainers/qemu_arch_base.go, src/runtime/virtcontainers/qemu_s390x.go, src/runtime/virtcontainers/utils/utils_linux.go, src/runtime/virtcontainers/utils/utils_linux_test.go
Recognise when a device to be hot-plugged is an IBM Adjunct Processor (AP) device and execute VFIO AP hot-plug accordingly. 
This enables running cryptographic workloads on an IBM CryptoCard inside a Kata container, since these cards use the AP bus on s390x (IBM Z mainframe).
I am momentarily calling this a WIP because I am not entirely sure about documentation.
To use this, one has to make an adapter and domain available for VFIO and assign them to a mediated device as per the [kernel documentation](https://www.kernel.org/doc/html/latest/s390/vfio-ap.html), determine the IOMMU group for this mediated device similar to [Kata's guide on doing this with an Intel i915 GPU](https://github.com/kata-containers/kata-containers/blob/2.0-dev/docs/use-cases/Intel-GPU-passthrough-and-Kata.md), and …
=> runtime: Add support for VFIO-AP pass-through

tools/packaging/kata-deploy/scripts/kata-deploy-docker.sh
Add an ACRN runtime ('kata-acrn') to the Docker configuration
('/etc/docker/daemon.json').
Fixes: #579
Signed-off-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>
=> kata-deploy: add ACRN runtime to Docker configuration

src/runtime/virtcontainers/device/config/config.go, src/runtime/virtcontainers/device/drivers/utils.go
Currently, isPCIeDevice() attempts to determine if a (host) device is
PCI-Express capable by looking up its link speed via the PCI slots
information in sysfs.  This is a) complicated and b) wrong.  PCI-e devices
don't have to have slots information, so this frequently fails.
Instead determine if devices are PCI-e by checking for the presence of
PCIe extended configuration space by looking at the size of the "config"
file in sysfs.
Forward ported from 6bf93b23 in the Kata 1.x runtime repository.
Fixes: #611
=> drivers: Correct isPCIeDevice logic

src/runtime/virtcontainers/qemu.go
"machineType" is misspelled as "machinneType".
=> runtime: Fix typo in hotplugVFIODevice()

src/runtime/Makefile
The linux kernel feature RANDOMIZE_BASE improved the security and at
the same time increased the memory footprint of a kata container,
this feature was enabled in kata-containers/packaging#1006.
In order to mitigate this increase in memory consumption, we can
boot container using the uncompressed kernel.
Reduce boot time by ~5%
Reduce KSM memory footprint by ~14%
Reduce noKSM memory footprint by ~27%
fixes #669
=> runtime: qemu: reduce boot time and memory footprint

tools/osbuilder/image-builder/image_builder.sh
Disable reflink when using DAX. Reflink is a xfs feature that cannot be
used together with DAX.
fixes kata-containers/osbuilder#456
=> [port] image-builder: disable reflink

src/agent/rustjail/src/capabilities.rs, src/agent/rustjail/src/container.rs, src/runtime/virtcontainers/network.go
I noticed the spelling mistake while reviewing another change and
doing a "grep" for "privilege" that turned up nothing.
Fixes: #671
=> trivial: Fix spelling of "privilege"

docs/how-to/how-to-set-prometheus-in-k8s.md
Update link address of yaml file refer to kata 2.0-dev branch.
Fixes: #676
=> docs: update yaml file link for prometheus deployment

src/runtime/virtcontainers/utils/compare_test.go
Add unit test for virtcontainers/utils/compare.go to increase overall
coverage.
Fixes #661
=> virtcontainers: Add unit test for utils/compare.go

tools/osbuilder/image-builder/image_builder.sh
Disable reflink when using DAX. Reflink is a xfs feature that cannot be
used together with DAX.
fixes #577
=> [fwport-2.0] osbuilder/image-builder: disable reflink

tools/osbuilder/image-builder/image_builder.sh, tools/osbuilder/rootfs-builder/rootfs.sh
This is a forward port of Kata 1.x PR
https://github.com/kata-containers/osbuilder/pull/480 .
Fixes #646
Signed-off-by: Pavel Mores <pmores@redhat.com>
=> rootfs-builder: fix unbootable dracut-based initramfs on Fedora

tools/osbuilder/rootfs-builder/rootfs.sh
The default toolchain used for building the rust agent would be different for ppc64le.
Fixes: #678
=> osbuilder: fix rootfs build on ppc64le

src/agent/src/rpc.rs, src/agent/src/sandbox.rs
Somte time runtime will fail in onlining CPU process,
because when the runtime calls to QMP
`device_add`, QEMU doesn't allocate all vCPUs inmediatelly.
Fixes: #665
**Attention:**
This PR only add retries for CPU resources, but not memory. In 1.x, there is no retries for memory resources.
=> agent: add retry between doing CPU hotplug and make it online.

tools/osbuilder/rootfs-builder/rootfs.sh
Update the default value of RUST_AGENT variable to 'yes' in
usage description.
fixes: #650
=> osbuilder: update usage of RUST_AGENT variable

src/agent/rustjail/src/cgroups/fs/mod.rs
The cgroup_parent path is expected to be absolute path,
if it was passed a relative path, change it to be an
absolute path.
Fixes: #336
=> rustjail: fix the issue of invalid cgroup_parent path

docs/design/kata-api-design.md
Sync the api from the runtime codes to the documentation. Remove and add
some apis in the kata-api-design.md doc. And new table for Sandbox
Monitor APIs.
Fixes: #701
=> docs: update sandbox apis doc for kata 2.0-dev

.travis.yml, src/agent/src/mount.rs
Running agent test now only support normal user,
under root user also needed.
Fixes: #708
=> ci: run agent test under root user

src/agent/src/network.rs, src/agent/src/rpc.rs
This PR is a porting of https://github.com/kata-containers/agent/pull/625
Fixes: #689
**Notes:**
This feature need new version `containerd`, at lease before 1.3.6 `contaienrd` dose not mount `/etc/resolv.conf`.
=> agent: setup DNS for guest

src/runtime/virtcontainers/virtiofsd_test.go
fix typo in virtiofsd_test.go
Fixes: #712
=> virtiofsd: fix typo in test code

src/agent/rustjail/src/process.rs, src/agent/src/rpc.rs, src/runtime/containerd-shim-v2/delete.go, src/runtime/containerd-shim-v2/service.go
* shimv2: do not kill a stopped exec process
* shimv2: trust cached status when deleting containers
* agent: allow multiple wait on the same process
Fixes: #716
=> fix issues with short life time container/exec processes

ci/lib.sh
Replace spaces by tabs as indent in file ci/lib.sh
Fixes: #743
=> ci: replace spaces by tabs as indent

src/runtime/data/kata-collect-data.sh.in
In show_container_mgr_details(), it used "cat /etc/crio/crio.conf"
instead of "crio config".
Fixes: #736
Signed-off-by: Qian Cai <cai@redhat.com>
=> runtime: Don't use hard-coded crio config

src/agent/Cargo.lock, src/agent/Cargo.toml, src/agent/rustjail/Cargo.toml, src/agent/rustjail/src/cgroups/fs/mod.rs, src/agent/rustjail/src/cgroups/mod.rs, src/agent/rustjail/src/cgroups/notifier.rs, src/agent/rustjail/src/container.rs, src/agent/rustjail/src/mount.rs, src/agent/src/config.rs, src/agent/src/main.rs, src/agent/src/mount.rs, src/agent/src/rpc.rs, src/agent/src/sandbox.rs, src/runtime/containerd-shim-v2/wait.go, src/runtime/virtcontainers/pkg/oci/utils.go, src/runtime/virtcontainers/pkg/oci/utils_test.go, src/runtime/virtcontainers/sandbox.go
This PR add basic cgroup v2 support for agent.
Fixes: #146, #357
=> agent: add cgroup v2 support

tools/packaging/release/runtime-release-notes.sh
It should only check kata-containers repository.
Fixes: #758
=> packaging: fix release notes scripts

tools/packaging/release/kata-deploy-binaries.sh, tools/packaging/static-build/cloud-hypervisor/build-static-clh.sh
We should just download the official static build binary instead of
trying to build on our own.
Fixes: #760
Ref:
* failure: https://github.com/kata-containers/kata-containers/actions/runs/260953909
* success: https://github.com/bergwolf/kata-containers/runs/1134462133?check_suite_focus=true
=> packaging: fix cloud-hypervisor build

versions.yaml
`kata-deploy` test failed on `v0.9.0` and succeeded on `v0.10.0`.
See
https://github.com/kata-containers/kata-containers/runs/1139077520?check_suite_focus=true
and
https://github.com/bergwolf/kata-containers/runs/1139304442?check_suite_focus=true
Fixes: #765
=> versions: update clh to v0.10.0

.gitignore, src/agent/src/main.rs
We should mount procfs before trying to parse kernel command lines.
Fixes: #771
=> fix guest panic when running agent as init

docs/Developer-Guide.md, docs/how-to/how-to-use-k8s-with-cri-containerd-and-kata.md
1. Until we restore docker/moby support, we should use crictl as
developer example.
2. Most of the hyperlinks should point to kata-containers repository.
3. There is no more standalone mode.
=> Fix developer guide

tools/packaging/cmd/kata-pkgsync/README.md
Fix the kata-pkgsync tool's docs, change the download path of the
packaging tool in 2.0 release.
Fixes: #773
=> docs: Fix the kata-pkgsync tool's docs script path

docs/how-to/containerd-kata.md
It should be set by default for Kata containers working with containerd.
Fixes: #775
=> how-to: add privileged_without_host_devices to containerd guide

src/runtime/Makefile, src/runtime/cli/config-generated.go.in, src/runtime/cli/kata-check.go, src/runtime/cli/release.go, src/runtime/cli/release_test.go
Update `kata-check` to see if there is a newer version available for download. Useful for users installing static packages (without a package manager).
Fixes: #734.
=> runtime: make kata-check check for newer release

tools/packaging/kata-deploy/README.md
Use the relative path of kata-deploy to replace the 1.x packaging url in
the kata-deploy/README.md file. Fixed the path issue, producted by
creating new branch.
Fixes: #777
=> docs: Update the reference path of kata-deploy in the packaging

src/agent/Cargo.lock, src/agent/Cargo.toml, src/agent/rustjail/Cargo.toml
Update cgroups crate to fix the building issue
on Aarch64.
Fixes: #770
=> agent: update cgroups crate

.travis.yml
This PR includes these changes:
- use Rust installed by Travis
- install x86_64-unknown-linux-musl
- install rustfmt
- use Travis cache
- delete ci/install_vc.sh
=> ci: use Travis cache to reduce build time

src/runtime/data/kata-collect-data.sh.in
Be more verbose about podman configuration in the output of data
collection script: get the system configuration as seen by podman and
dump the configuration files when present.
Fixes: #243
=> runtime: add podman configuration to data collection script

src/runtime/cli/release.go, src/runtime/cli/release_test.go
Fix the linter errors caught in the `runtime` repos `master` branch [1], but not in the `2.0-dev` branch [2]. See [3] for further details.
[1] - https://github.com/kata-containers/runtime/pull/2976
[2] - https://github.com/kata-containers/kata-containers/pull/735
[3] - https://github.com/kata-containers/tests/issues/2870
Fixes: #783.
=> runtime: Fix linter errors in release files

src/agent/oci/src/serialize.rs
We shouldn't use it, and we don't need to implement it.
fixes #791
=> agent/oci: Don't use deprecated Error::description() method

tools/osbuilder/scripts/lib.sh
Update rust to latest 1.46.0, and specify default toolchain in rust-init.
Fixes: #799
=> osbuilder: specify default toolchain verion in rust-init

src/runtime/containerd-shim-v2/create.go
In checkAndMount(), it is not clear why we check IsBlockDevice() and if
DisableBlockDeviceUse == false and then only return "false, nil" instead
of "false, err". Adding a comment to make it a bit more readable.
Fixes: 732
Signed-off-by: Qian Cai <cai@redhat.com>
=> shimv2: add a comment in checkAndMount()

src/runtime/virtcontainers/sandbox.go
Fixes:  #696
backport from https://github.com/kata-containers/runtime/pull/2920
Signed-off-by: Shukui Yang <keloyangsk@gmail.com>
=> runtime: Call s.newStore.Destroy if globalSandboxList.addSandbox

docs/Developer-Guide.md, src/agent/src/main.rs, src/runtime/cli/config-generated.go.in, src/runtime/cli/config/configuration-acrn.toml.in, src/runtime/cli/config/configuration-clh.toml.in, src/runtime/cli/config/configuration-fc.toml.in, src/runtime/cli/config/configuration-qemu-virtiofs.toml.in, src/runtime/cli/config/configuration-qemu.toml.in, src/runtime/cli/kata-exec.go, src/runtime/cli/kata-monitor/main.go, src/runtime/cli/main.go, src/runtime/containerd-shim-v2/shim_management.go, src/runtime/pkg/kata-monitor/metrics.go, src/runtime/pkg/kata-monitor/monitor.go, src/runtime/pkg/kata-monitor/pprof.go, src/runtime/pkg/kata-monitor/shim_client.go, src/runtime/pkg/katautils/config.go, src/runtime/pkg/katautils/config_test.go, src/runtime/virtcontainers/interfaces.go, src/runtime/virtcontainers/kata_agent.go, src/runtime/virtcontainers/pkg/agent/protocols/client/client.go, src/runtime/virtcontainers/pkg/annotations/annotations.go, src/runtime/virtcontainers/pkg/vcmock/sandbox.go, src/runtime/virtcontainers/pkg/vcmock/types.go, src/runtime/virtcontainers/sandbox.go, src/runtime/virtcontainers/vm_test.go
Add `kata-runtime exec` to enter guest OS through shell started by agent
This approach use `vsock` to connect shell running inside guest that started by agent. The good aspect is that we need not modify guest image or despite using what device that hypervisor support. Only `/bin/sh` or `/bin/bash` are necessary.
Fixes: #245
=> kata 2.0: add debug console service

src/agent/rustjail/src/mount.rs
This only allows some whitelists files bind mounted under proc
and prevent other malicious mount to procfs.
=> agent: Only allow proc mount if it is procfs

.gitignore, src/agent/Cargo.lock, src/agent/rustjail/Cargo.toml, src/agent/rustjail/src/lib.rs, src/agent/rustjail/src/mount.rs
Current working directory is a process level resource. We cannot call
chdir in parallel from multiple threads, which would cause cwd confusion
and result in UT failures.
The agent code itself is correct that chdir is only called from spawned
child init process. Well, there is one exception that it is also called
in do_create_container() but it is safe to assume that containers are
never created in parallel (at least for now).
Fixes: #782
=> agent: fix UT failures due to chdir

.travis.yml, CODEOWNERS, ci/go-no-os-exit.sh, ci/lib.sh, docs/CODE_OF_CONDUCT.md, docs/CONTRIBUTING.md, docs/Developer-Guide.md, docs/README.md, snap/README.md, src/agent/protocols/src/lib.rs, src/runtime/CONTRIBUTING.md, src/runtime/Makefile, src/runtime/cli/console_test.go, src/runtime/containerd-shim-v2/shim_metrics_test.go, src/runtime/virtcontainers/device/manager/utils_test.go, src/runtime/virtcontainers/documentation/Developers.md, src/runtime/virtcontainers/pkg/agent/protocols/client/client.go, src/runtime/virtcontainers/qemu_arch_base.go, src/runtime/virtcontainers/qemu_ppc64le.go, src/runtime/virtcontainers/qemu_s390x.go, tools/packaging/CODE_OF_CONDUCT.md, tools/packaging/CONTRIBUTING.md, tools/packaging/README.md
Somehow travis was not running static checkers and it silently reports success. It resulted in a lot of static check failures. Let's resurrect it and fix the static check errors.
=> ci: resurrect travis static checkers

docs/design/data/metrics.yaml, docs/design/kata-2-0-metrics.md, src/runtime/virtcontainers/fc.go, src/runtime/virtcontainers/fc_metrics.go
Firecracker expose metrics through fifo file and using a JSON format.
This PR will parse the Firecracker's metrics and convert to Prometheus metrics.
Fixes: #472
Old PR closed #473
=> fc: integrate Firecracker's metrics

ci/lib.sh
We should not checkout to 2.0-dev branch in the clone_tests_repo
function when running in Jenkins CI as it discards changes from
tests repo.
Fixes: #818.
Signed-off-by: Salvador Fuentes <salvador.fuentes@intel.com>
=> ci: fix clone_tests_repo function

src/agent/src/rpc.rs
It's should propagate the detail errors to users when
the rpc call failed.
Fixes: #824
=> agent: propagate the internal detail errors to users

src/agent/rustjail/src/container.rs
Indicates never return function and remove unreachable code.
Fixes #819
=> Indicates never return function and remove unreachable code

.github/workflows/commit-message-check.yaml
Overly long commit lines are annoying. But sometimes, we need to be able to force the use of long lines (for example to reference a URL).
Ironically, I can't refer to the URL that explains this because of ... the long line check! Hence:
```sh
$ cat <<EOT | tr -d '\n'; echo
See: https://github.com/kata-containers/tests/tree/master/
cmd/checkcommits#handling-long-lines
EOT
```
Fixes: #687.
=> action: Allow long lines if non-alphabetic

src/runtime/virtcontainers/device/manager/manager_test.go
Create "class" and "config" file in temporary device BDF dir,
and remove dir created  by ioutil.TempDir() when test finished.
fixes: #746
=> devices: fix go test warning in manager_test.go

src/agent/rustjail/src/cgroups/notifier.rs
The code used `match` as a switch with variable patterns `ev_fd` and
`cf_fd`, but the way Rust interprets the code is that the first
pattern matches all values. The code does not perform as expected.
This addresses the following warning:
warning: unreachable pattern
--> rustjail/src/cgroups/notifier.rs:114:21
|
107 |                     ev_fd => {
|                     ----- matches any value
...
114 |                     cg_fd => {
|                     ^^^^^ unreachable pattern
|
= note: `#[warn(unreachable_patterns)]` on by default
Fixes: #750
Fixes: #793
=> rust-agent: Replaces improper use of match for non-constant patterns

tools/packaging/release/runtime-release-notes.sh
2.0 Packaging runtime-release-notes.sh script is using 1.x Packaging
kernel urls. Fixed these urls to 2.0 branch Packaging urls.
Fixes: #829
=> Packaging: release notes script using error kernel path urls

src/agent/oci/src/lib.rs
Correct the typo which would break the Windows-specific OCI network shared container name feature.
See: https://github.com/opencontainers/runtime-spec/blob/master/config-windows.md#network
Fixes: #685.
=> agent: Fix OCI Windows network shared container name typo

tools/packaging/qemu/patches/5.1.x/0001-arm-enable-cold-plug-nvdimm-using-DT.patch, tools/packaging/scripts/configure-hypervisor.sh, versions.yaml
Now, the qemu version used in arm is so old. As some new features have merged
in current qemu, so it's time to upgrade it.
Fixes: #816
Signed-off-by: Edmond AK Dantes <edmond.dantes.ak47@outlook.com>
@jodh-intel  @devimc @jongwu
=> version: upgrade qemu version to v5.1.0 for arm64

src/agent/README.md
rust agent does not use grpc as submodule for a while, update README
to reflect the change.
This rebases #197 on top of latest master.
=> rust-agent: Update README

docs/design/architecture.md
Move CNM out of main doc since it is less commonly used. Add backround on the usage of tc-filter since it is the default and clarify why we use this instead of macvtap. Update state directory and tap device name.
Fixes #797 
This is a forward port of both https://github.com/kata-containers/documentation/pull/693 and https://github.com/kata-containers/documentation/pull/722.
=> docs: update networking description

src/runtime/virtcontainers/clh.go, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/MemoryConfig.md, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/VmAddDevice.md, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_memory_config.go, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_add_device.go, src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml, versions.yaml
Forward port PR kata-containers/runtime#2996 for issue kata-containers/runtime#2569.
This patch adds the support of VFIO device unplug when using
cloud-hypervisor.
Fixes: #860
Signed-off-by: Bo Chen chen.bo@intel.com
=> clh: Support VFIO device unplug

tools/packaging/guest-image/build_image.sh, tools/packaging/scripts/lib.sh
There were a couple of issues with the build-scripts discovered while
doing release:
- Relative paths are error prone. Fix error.
- short_commit_length is used to truncate sha for commits when
appending agent version to resulting files. Before this was
in pkglib.sh, which is otherwise an unused file from when we
supported OBS. Add this define to lib.sh, which is sourced by
the applicable packaging scripts.
There's plenty of room for improvement, but these fixes make the
existing scripts functional again.
Fixes: #871
=> packaging: fix image build script

snap/snapcraft.yaml
In order to avoid `unmet dependencies` error in the CI,
the python version must be specified in the yaml.
fixes #877
=> snap: specify python version

versions.yaml
plugins sections contains the details of plugins required for
the components or testing.
Add sriov-network-device-plugin url and version that are consumed
by the VFIO test in the tests repository.
fixes #879
=> versions: add plugins section

tools/osbuilder/rootfs-builder/rootfs.sh
When building with AGENT_SOURCE_BIN pointing to an already built
kata-agent binary, the target directory needs to be created in the
rootfs tree.
Fixes #873
Signed-off-by: Ralf Haferkamp <rhafer@suse.com>
=> osbuilder: Create target directory for agent

docs/Developer-Guide.md
The systemd method of adding a debug console is not really
user friendly. Since we have added a much more straightforward
method to enable agent debug console, update developer guide to
reflect this.
Fixes kata-containers/documentation#703
=> docs: Update docs for enabling agent debug console

src/runtime/Makefile
virtiofs DAX support is not stable today, there are
a few corner cases to make it default.
Fixes: #862
Fixes: #875
Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>
=> virtiofs: Disable DAX

tools/agent-ctl/Cargo.lock
Simply running `make` would generate some cargo lock updates for
agent-ctl. Let's include them so that we have fixed dependencies.
Fixes: #883
=> agent-ctl: include cargo lock updates

.github/workflows/snap.yaml
Run the snap CI on every PR is not needed. Don't run the snap CI
on PRs that don't change the source (*.go/*.rs) or yaml files.
fixes #896
=> ci: snap: add event filtering

docs/how-to/README.md, docs/how-to/data/crictl/busybox/container_config.json, docs/how-to/data/crictl/busybox/sandbox_config.json, docs/how-to/data/crictl/redis/redis_client_container_config.json, docs/how-to/data/crictl/redis/redis_client_sandbox_config.json, docs/how-to/data/crictl/redis/redis_server_container_config.json, docs/how-to/data/crictl/redis/redis_server_sandbox_config.json, docs/how-to/run-kata-with-crictl.md
Add basic sample pod/container config files to show
how to use `crictl` with Kata containers.
Fixes: #881
=> docs: Add crictl example json files

tools/packaging/release/kata-deploy-binaries.sh, tools/packaging/static-build/cloud-hypervisor/build-static-clh.sh
It is needed in order to build from source.
Fixes: #916
=> packaging: fix missing cloud_hypervisor_repo

src/agent/src/config.rs
In function parse_cmdline there are some similar codes, if we want
to add more commandline arguments, the code will grow too long.
Use macro can reduce some codes with the same logic/processing.
Fixes: #914
=> agent: use macro to simplify parse_cmdline function in config.rs

src/agent/src/rpc.rs
We were assuming base 10 string before, when the block size from sysfs
is actually a hex string. Let's fix that.
Fixes: #908
=> agent: fix errorneous parsing for guest block size

src/agent/src/device.rs
https://github.com/kata-containers/agent/issues/834 and https://github.com/kata-containers/agent/issues/835 covered possible misbehaviour of the agent due to conflicts between device major:minor numbers, either between guest and host or between block and character devices.
Here, forward port those fixes to address #703.
@bergwolf's PR #924 solves the same bugs.  This PR takes an approach that's closer to how they were solved in the Go agent, which will make dependent forward ports I'm working on easier.
=> Forward port device conflict fixes from Kata 1 / Go agent

src/runtime/go.sum, src/runtime/virtcontainers/container.go, src/runtime/virtcontainers/pkg/cgroups/manager.go, src/runtime/virtcontainers/pkg/cpuset/cpuset.go, src/runtime/virtcontainers/pkg/cpuset/cpuset_test.go, src/runtime/virtcontainers/sandbox.go, src/runtime/virtcontainers/sandbox_test.go
Without the following patchset, cpusets are buggy and do not work on 2.0
8bb1337d cpuset: don't set cpuset.mems in the guest
4d8dbad4 sandbox: consider cpusets if quota is not enforced
d25e83af cpuset: support setting mems for sandbox
75820e84 cpuset: add cpuset pkg
12cc0ee1 sandbox: don't constrain cpus, mem only cpuset, devices
b6cf68a9 cgroups: add ability to update CPUSet
b812d4f7 virtcontainers: add method for calculating cpuset for sandbox
=> cgroup and cpuset fixes from 1.x

tools/packaging/kernel/README.md
Update the build kata containers kernel document for 2.0 release. Fixed
the 1.x release project paths and urls, using the kata-containers
project file paths and urls.
Fixes: #929
=> docs: update the build kata containers kernel document

src/runtime/cli/containerd-shim-kata-v2/main.go, src/runtime/pkg/kata-monitor/containerd.go, src/runtime/pkg/kata-monitor/sandbox_cache.go, src/runtime/pkg/types/types.go, src/runtime/pkg/types/types_test.go
To support a few common configurations for Kata, including:
- `io.containerd.kata.v2`
- `io.containerd.kata-qemu.v2`
- `io.containerd.kata-clh.v2`
`kata-monintor` changes to use regexp instead of direct string comparison.
Fixes: #957
=> kata-monitor: use regexp to check if runtime is kata containers

src/agent/rustjail/src/validator.rs
This might be a copy miss, gid_mappings is checked twice, one should
be uid_mappings.
Fixes: #952
=> rustjail: add length check for uid_mappings in rootless euid mapping

src/agent/src/rpc.rs
Check the validity of the `AddARPNeighbors`, `UpdateInterface` and `UpdateRoutes`, APIs before using to avoid crashing the agent.
Fixes: #949, #950, #955.
=> agent: fix crashers if API requests empty

versions.yaml
Kubernetes: from 1.17.3 to 1.18.9
CRI-O: from 0eec454168e381e460b3d6de07bf50bfd9b0d082 (1.17) to 1.18.3
Containerd: from 3a4acfbc99aa976849f51a8edd4af20ead51d8d7 (1.3.3) to 1.3.7
cri-tools: from 1.17.0 to 1.18.0
Fixes: #960.
Signed-off-by: Salvador Fuentes <salvador.fuentes@intel.com>
=> versions: Update Kubernetes, containerd, cri-o and cri-tools

src/agent/rustjail/src/capabilities.rs, src/agent/rustjail/src/container.rs, src/agent/rustjail/src/mount.rs, src/agent/rustjail/src/sync.rs, src/agent/src/device.rs, src/agent/src/main.rs, src/agent/src/mount.rs, src/agent/src/namespace.rs, src/agent/src/rpc.rs, src/agent/src/sandbox.rs, src/agent/src/uevent.rs
- Remove `if let Err`
- Remove `check!` macro
- Remove unnecessary `match`
- Remove `unwrap` for `e.as_errno()`, avoid panic caused by error content
Fixes #934
=> agent: Optimize error handling

tools/agent-ctl/Cargo.lock, tools/agent-ctl/Cargo.toml, tools/agent-ctl/README.md, tools/agent-ctl/src/client.rs, tools/agent-ctl/src/main.rs, tools/agent-ctl/src/utils.rs
Added new `agent-ctl` commands to allow the following agent API calls to be made:
- `AddARPNeighborsRequest`
- `CloseStdinRequest`
- `CopyFileRequest`
- `GetMetricsRequest`
- `GetOOMEventRequest`
- `MemHotplugByProbeRequest`
- `OnlineCPUMemRequest`
- `ReadStreamRequest`
- `ReseedRandomDevRequest`
- `SetGuestDateTimeRequest`
- `TtyWinResizeRequest`
- `UpdateContainerRequest`
- `WriteStreamRequest`
Also did some tidy-up, and added more debug and better docs.
Fixes: #969.
=> tools: Make agent-ctl support more APIs

snap/snapcraft.yaml
To build qemu with virtio-fs support.
Fixes: #982
=> snap: install libseccomp-dev

src/runtime/virtcontainers/qemu_arch_base.go, src/runtime/virtcontainers/qemu_arch_base_test.go
Allow API consumers to change the maximum number of ports in the
virtio-serial devices, setting a lower number of ports can improve the
boot time and reduce the attack surface.
Before this patch on arm64:
[    0.028664] Serial: 8250/16550 driver, 4 ports, IRQ sharing disabled
[    0.055031] printk: console [hvc0] enabled
After this patch on arm64:
[    0.028484] Serial: 8250/16550 driver, 4 ports, IRQ sharing disabled
[    0.031370] printk: console [hvc0] enabled
Fixes: #2676
Signed-off-by: Jia He <justin.he@arm.com>
=> virtcontainers: Append max_ports to virtio-serial device

src/runtime/Makefile
In commit 966bd57 for PR #902, the makefile was changed to automate
the replacement of user variables. However, one variable was treated
specially in the original `sed` replacements, namely `RUNTIME_NAME`
which was replaced by `$(TARGET)`.
This commit adds the `RUNTIME_NAME` variable to the makefile in order
to ensure that the replacement works correctly.
Fixes: #993
=> Replace @RUNTIME_NAME@ with the target in generated files

.gitignore, .travis.yml, pkg/logging/src/lib.rs, src/agent/Makefile, src/agent/oci/src/serialize.rs, src/agent/protocols/src/lib.rs, src/agent/rustjail/src/capabilities.rs, src/agent/rustjail/src/cgroups/fs/mod.rs, src/agent/rustjail/src/cgroups/notifier.rs, src/agent/rustjail/src/container.rs, src/agent/rustjail/src/mount.rs, src/agent/rustjail/src/sync.rs, src/agent/rustjail/src/validator.rs, src/agent/src/config.rs, src/agent/src/device.rs, src/agent/src/main.rs, src/agent/src/metrics.rs, src/agent/src/mount.rs, src/agent/src/namespace.rs, src/agent/src/network.rs, src/agent/src/random.rs, src/agent/src/rpc.rs, src/agent/src/sandbox.rs, src/agent/src/test_utils.rs, versions.yaml
- add `cargo clippy` to Travis CI
- clear all clippy warnings for existing code to pass CI
Fixes: #951 
Not all lint are checked. Explicitly allowed lint includes:
```
warning: usage of `Box<&T>`
--> rustjail/src/cgroups/fs/mod.rs:48:30
|
48 | pub fn load_or_create<'a>(h: Box<&'a dyn cgroups::Hierarchy>, path: &str) -> Cgroup<'a> {
|                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `&'a dyn cgroups::Hierarchy`
|
= note: `#[warn(clippy::redundant_allocation)]` on by default
```
This only appears in `rustjail/src/cgroups/fs/mod.rs`, and I tried to resolve it, but it seems need more time.
Refer: https://rust-lang.github.io/rust-clippy/master/index.html#redundant_allocation
=> agent: clear clippy warnings

.github/workflows/snap-release.yaml, snap/snapcraft.yaml
Use Github actions to build and release the snap package automatically
when a new tag is pushed.
fixes #1006
=> snap: add GH actions jobs to release the snap package

docs/design/kata-api-design.md
Remove the build in shim and proxy desgin description from the
kata-api-design.md file.
Fixes: #912
=> docs: remove the 1.x version description about shim and proxy

src/agent/README.md
Fix the instructions explaining how to build the agent from source now that make needs to be run to auto-generate some source files.
Fixes: #889.
Signed-off-by: LiYa'nan <oliverliyn@gmail.com>
=> agent: Update build instructions

src/agent/rustjail/src/container.rs
It's should catch the failed error of spawning a new thread, otherwise,
it would cause the current thread panic.
Fixes: #1034
=> rustjail: fix the issue of create thread failed causing current thread panic

src/runtime/virtcontainers/clh.go
Cloud-hypervisor supports DAX, let's enable it to reduce its memory
footprint.
Before this patch:
**19.96M**
```
20448kB -- [/usr/share/kata-containers/kata.img]
```
With this patch:
**10.83M**
```
11100kB -- [/usr/share/kata-containers/kata.img]
```
fixes #1056
=> runtime: cloud-hypervisor: reduce memory footprint

versions.yaml
This PR updates the crio version from 1.18.3 to 1.18.4 in order to include
the fix https://github.com/cri-o/cri-o/pull/4284.
Fixes #1036
=> versions: Update crio version

.github/workflows/commit-message-check.yaml
Correct the link in the GitHub action commit message check showing users how to format all commits.
Fixes: #1053
=> CI: Fix incorrect URL

src/runtime/cli/config/configuration-qemu.toml.in
Correct the default configuration of [hypervisor.qemu] shared_fs in configuration-qemu.toml to virtio-fs in kata 2.0.
Fixes: #1054
=> docs: Fix incorrect docs in config file

src/runtime/virtcontainers/container.go, src/runtime/virtcontainers/kata_agent.go, src/runtime/virtcontainers/mount.go, src/runtime/virtcontainers/pkg/oci/utils.go, src/runtime/virtcontainers/sandbox_test.go, versions.yaml
So that even if the guest is compromised, we still ensure that readonly volumes cannot be modified.
=> runtime: readonly volume should be bind mounted readonly on the host

src/agent/Cargo.lock, src/agent/Cargo.toml, src/agent/src/config.rs, src/agent/src/main.rs
The `ttrpc` crate uses the `log` crate for logging. But the agent uses the `slog` crate. This means that currently, all `ttrpc` log messages are being discarded.
Use the `slog-stdlog` create to redirect `log` crate logging calls into `slog` so they are visible in the agents log output.
Also adds a new `KATA_AGENT_LOG_LEVEL` environment variable to make testing this easier, plus a bunch of new tests.
Fixes: #978.
=> agent: Log ttrpc messages

versions.yaml
This reverts commit ff13bde3c1bd03b5ed0c93e7ea315befd24a75b7, which
moved back CRI-O to v1.18.3.
This was, IMHO, a little bit premature.  We want to know exactly what are
the issues on v1.18.4, solve those, and be prepared for a v1.18.5 bump
(or even a bump to a specific commit, if needed).
Just for the sake of the completeness, v1.18.4 caused a regression on
"k8s-copy-file" tests, which is tracked on CRI-O side as
https://github.com/cri-o/cri-o/issues/4353.
Fixes: #1080
/cc @bergwolf
=> Revert "version: revert back to crio 1.8.3"

docs/how-to/what-is-vm-templating-and-how-do-I-use-it.md
Kata 2.0 uses virtio-fs as the shared_fs by default, bug VM templating cannot be used with virtio-fs.
Fixes: #1091
Signed-off-by: AIsland <yuchunyu01@inspur.com>
=> docs: Add instructions for enabling VM templating

docs/how-to/how-to-load-kernel-modules-with-kata.md, docs/how-to/how-to-set-sandbox-config-kata.md
Forward port annotation documentation fixes from
https://github.com/kata-containers/documentation/pull/755
https://github.com/kata-containers/documentation/pull/757
I also fixed a couple of minor inconsistencies between 2.0 and 1.x documentation, e.g. `cpu_features` was missing in 2.0. I did not do that in a very systematic way yet, though.
=> Forward port annotation doc

src/runtime/containerd-shim-v2/wait.go
In some cases, for example agent crashed and not marked dead yet, the GetOOMEvent
will return errors like `connection reset by peer` or `ttrpc: closed`. Do a sleep
with 1 second (agent check interval) and let agent health check to do the check.
Fixes: #991
=> runtime: sleep 1 second after GetOOMEvent failed

src/runtime/cli/release.go, src/runtime/cli/release_test.go
Fix `kata-runtime kata-check`'s network version check which was failing
when the user was running a release candidate build and the latest
release was a major one, two examples of the error being:
- `BUG: unhandled scenario: current version: 1.12.0-rc0, latest version: 1.12.0`
- `BUG: unhandled scenario: current version: 2.0.0-rc0, latest version: 2.0.0`
Fixes: #1104.
=> release: Fix release candidate to major version upgrade check

src/runtime/virtcontainers/clh.go, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/FsConfig.md, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_fs_config.go, src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml, versions.yaml
Guest consumes 120Mb more of memory when DAX is enabled and the default
FS cache size (8G) is used. Disable dax when it is not required
reducing guest's memory footprint.
Without this patch:
```
7fdea4000000-7fdee4000000 rw-s 18850589 /memfd:ch_ram (deleted)
Size:            1048576 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:              187876 kB
```
With this patch:
```
7fa970000000-7fa9b0000000 rw-s 612001  /memfd:ch_ram (deleted)
Size:            1048576 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:               57308 kB
Pss:               56722 kB
```
fixes #1100
-------
cc @likebreath
=> runtime: clh: disable virtiofs DAX when FS cache size is 0

versions.yaml
Let's update CRI-O version to the commit which introduced the fix for
the "k8s-copy-file" tests.
Fixes: #1080
=> versions: Use release-1.18 (commit ee9128444bec10)

src/runtime/cli/config/configuration-acrn.toml.in, src/runtime/cli/config/configuration-clh.toml.in, src/runtime/cli/config/configuration-fc.toml.in, src/runtime/cli/config/configuration-qemu.toml.in
Key name in configuration file is in snake case but not camel case.
And the key is processed as `enable_pprof` in code, the configuration
template file should replace `EnablePprof` it by `enable_pprof`
Fixes: #1109
=> runtime: change configuration key name from EnablePprof to enable_pprof

versions.yaml
This (unreleased) version of CRI-O brings in the possibility of enabling
the `k8s-oom.bats` test.
Depends-on: https://github.com/kata-containers/tests#3060
Fixes: #1116
=> versions: Use CRI-O v1.18.4-4-g6dee3891e

docs/design/virtualization.md
This is a PR with two fixes by Ariel Adam. It supersedes #855 which was failing due to the typo.
commit 8ec3cf08f3928d3e7ef03a5d9c67e837730d37ba (HEAD -> docs/855-hyperlinks, c3d/docs/855-hyperlinks)
Author: Ariel Adam <aadam@redhat.com>
Date:   Wed Aug 26 20:22:36 2020 +0300
docs: Adding hyperlink to virtio-net in kata documentation 2.0
Referring virtio-net mentioning in the kata virtualization
documentation to the virtio-networking blog series published
and explaining how it works.
Fixes #612
Signed-off-by: Ariel Adam <aadam@redhat.com>
commit b5b67db8d727c0003e2ec69bc40c7f938e69a8a5
Author: Ariel Adam <aadam@redhat.com>
Date:   Mon Oct 12 15:36:16 2020 +0300
docs: Fixing typo in virtualization.md file
Changing "implementor" to "implementer"
Fixes: #612
Signed-off-by: Ariel Adam …
=> Add hyperlink and fix typo

docs/design/virtualization.md, docs/hypervisors.md, src/runtime/README.md
Split some of the core hypervisor details out of the virtualisation
document and present in a simpler fashion for new users.
Fixes: #1063.
=> docs: Create hypervisor summary document

src/runtime/containerd-shim-v2/service.go, src/runtime/containerd-shim-v2/utils.go, src/runtime/virtcontainers/api.go, src/runtime/virtcontainers/api_test.go, src/runtime/virtcontainers/implementation.go, src/runtime/virtcontainers/interfaces.go, src/runtime/virtcontainers/persist.go, src/runtime/virtcontainers/pkg/vcmock/mock.go, src/runtime/virtcontainers/pkg/vcmock/mock_test.go, src/runtime/virtcontainers/pkg/vcmock/types.go, src/runtime/virtcontainers/sandbox.go, src/runtime/virtcontainers/sandbox_test.go
In PR 1079, CleanupContainer's parameter of sandboxID is changed to VCSandbox, but at cleanup,
there is no VCSandbox is constructed, we should load it from disk by loadSandboxConfig() in
persist.go. This commit reverts parts of #1079
Fixes: #1119
=> virtcontainers: revert CleanupContainer from PR 1079

src/agent/Cargo.toml
The lto setting controls the -C lto flag which controls LLVM's link time optimizations.
LTO can produce better optimized code, using whole-program analysis,
at the cost of longer linking time.
https://doc.rust-lang.org/cargo/reference/profiles.html#lto
Fixes: #1125
=> agent: enable lto flag for Cargo to get better optimized code

src/runtime/containerd-shim-v2/service.go
In first shim v2 startup(with `start` command-line option), it will start
the second shim v2 process running as ttrpc server, there is no needs to
wait the second process, because the current shim v2 process will exit immediately.
Fixes: #1127
=> runtime: don't wait the second shim process in shim start

snap/snapcraft.yaml
Add `kata-runtime` and `kata-collect-data.sh` commands to the apps
section, these two command will be accessible through the commands
`kata-containers.runtime` and `kata-containers.collect-data`
respectively.
Henceforth the snap command for `containerd-shim-kata-v2` will be
`kata-containers.shim`
fixes #1122
=> snap: update apps section

src/agent/rustjail/src/validator.rs
Since kata containers shared the network ns with
the guest system, thus there's no need to do the
network ns check.
Fixes: #1047
=> rustjail: remove the network ns validation against container

.github/workflows/snap-release.yaml, snap/snapcraft.yaml
Use Github actions to build and release the snap package automatically
when a new tag is pushed.
fixes #1006
=> [backport] snap: add GH actions jobs to release the snap package

README.md
The VMT process is well documented, but users would need to land on
community repo to find it. Let's make it easier to identify the correct
way to disclose vulnerabilities.
Fixes: 1136
=> docs: add link to VMT on top level README

src/agent/kata-agent.service.in
Under stress, the agent can be OOM-killed, which exists the sandbox.
One possible hard-to-diagnose manifestation is a virtiofsd crash.
Fixes: #1111
Reported-by: Qian Cai <caiqian@redhat.com>
=> agent: Adjust OOM Score to avoid agent being killed.

docs/Developer-Guide.md
fix the custom agent binary file path for creating an initrd image in
the Developer-Guide.md file.
Fixes: #919
=> docs: fix the custom agent binary file path for creating initrd image

src/agent/rustjail/src/cgroups/fs/mod.rs, src/agent/rustjail/src/cgroups/mock.rs, src/agent/src/sandbox.rs
This PR will fix #1156 , #1159 
```
Mem: 40364K used, 2526712K free, 8K shrd, 992K buff, 1848K cached
CPU:   1% usr  18% sys   0% nic  79% idle   0% io   0% irq   0% sirq
Load average: 3.25 1.14 0.41 5/89 8
PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
6     3 root     R     1528   0%   0   5% md5sum /dev/urandom
7     3 root     R     1528   0%   0   5% md5sum /dev/urandom
4     3 root     R     1528   0%   0   5% md5sum /dev/urandom
5     3 root     R     1528   0%   0   5% md5sum /dev/urandom
2     0 root     S     1532   0%   0   0% top
3     0 root     S     1532   0%   0   0% sh
8     3 root     R     1528   0%   0   0% top
1     0 root     S     1020   0%   0   0% /pause
```
```
top - 02:20:35 up 4 min,  0 users,  load average: 2.76, 0.84, 0.29
Tasks:  72 total,   5 running, …
```
=> handle vcpus properly utilized in the guest

src/agent/Cargo.lock, src/agent/rustjail/Cargo.toml, src/agent/rustjail/src/lib.rs, src/agent/rustjail/src/process.rs, src/agent/rustjail/src/reaper.rs, src/agent/src/main.rs, src/agent/src/rpc.rs
This is the Rust porting of https://github.com/kata-containers/agent/pull/371
`read_stdout`/`read_stderr` is blocking rpc calls, if exec process exited, these calls is on blocking state for reading on process's term master fd, and can't get a chance to break the wait.
In this PR, `read_stdout`/`read_stderr` will not read directly from a term master of a process, instead, it will first have to get an fd to read from newly added `epoller.poll()`. `epoller.poll()` may returns:
- the term master fd of exec process, if the process is running.
- a fd(piped fd) will return EOF when reading to indicate that th process is exited.
Fixes: #1160 
=> agent: exit from exec hangs if background process is present

docs/design/virtualization.md
The current description on the Cloud Hypervisor support in Kata
containers were introduced back to kata 1.10 and are out-dated.
Depends-on: github.com/kata-containers/tests#3106
Fixes: #1167
=> docs: Update the Cloud Hypervisor description in virtualization.md

docs/design/architecture.md
Correct the docs in docs/architecture.md,
use virtio-fs as the default config.
Fixes: #1193 
Signed-off-by: AIsland <yuchunyu01@inspur.com>
=> docs: Fix docs in docs/architecture.md

.github/workflows/snap-release.yaml
According to the new snap document
`docs/install/snap-installation-guide.md`, Kata Containers 2.x should
be available in the snapcraft `candidate` channel.
fixes #1174
=> snap: fix snap release channel

tools/osbuilder/rootfs-builder/ubuntu/rootfs_lib.sh
Improve Kata Containers memory footprint by reducing debian
image size.
Without this change:
Debian image -> 256MB
With this change:
Debian image -> 128MB
Note: this change *will not* impact ubuntu image.
fixes #1188
=> rootfs: reduce size of debian image

src/trace-forwarder/Makefile, tools/agent-ctl/Makefile
These simple patches allow us to do a `make install` from the top directory without any issue.
Fixes: #1149
=> Add void "install" targets for both "trace-forwarder" and "agent-ctl"

src/runtime/virtcontainers/kata_agent.go
Forward port of https://github.com/kata-containers/runtime/pull/3033
=> Fix error reporting in listInterfaces() and listRoutes()

src/agent/src/config.rs
get_bool_value() in src/agent/src/config.rs includes a Result::or_else()
call with a trivial closure which can be replaced by a Result::or.  This
removes a clippy warning.
=> agent: Simplify .or_else() to .or()

src/agent/Cargo.lock, src/agent/Cargo.toml, src/agent/rustjail/Cargo.toml, src/agent/rustjail/src/cgroups/fs/mod.rs
- upgrade crate cgroups to 0.2.0
- Avoid container stats panic caused by cgroup controller non-exist
=> agent: upgrade cgroups to 0.2.0

tools/packaging/static-build/qemu-virtiofs/Dockerfile, tools/packaging/static-build/qemu-virtiofs/build-static-qemu-virtiofs.sh, tools/packaging/static-build/qemu.blacklist, tools/packaging/static-build/qemu/Dockerfile, tools/packaging/static-build/qemu/build-static-qemu.sh, tools/packaging/static-build/scripts/qemu-build-post.sh
Currently QEMU is built inside the container, its tarball pulled to the host, files removed then it is packaged again.
Here I propose to run all those steps inside the container and the resulting tarball will be the final version. It can be refactored so that common code between qemu and qemu-virtiofs will be shared.
The commit https://github.com/kata-containers/kata-containers/commit/c94d9da0fc9a3b4d10e611ab439ea0b5fe337a12 is an unrelated improvement which I am pushing together.
Fixes #1168
=>  packaging/qemu: Build and package completely inside the container

src/runtime/virtcontainers/qemu.go
On pod delete, we were looking to read files that we had just deleted. In particular,
stopSandbox for QEMU was called (we cleanup up vmpath), and then QEMU's
save function was called, which immediately checks for the PID file.
Let's only update the persist store for QEMU if QEMU is actually
running. This'll avoid Error messages being displayed when we are
stopping and deleting a sandbox:
```
level=error msg="Could not read qemu pid file"
```
I reviewed CLH, and it looks like it is already taking appropriate
action, so no changes needed.
Ideally we won't spend much time saving state to persist.json unless
there's an actual error during stop/delete/shutdown path, as the persist will
also be removed after the pod is removed. We may want to optimize this,
as currently we are doing a persist …
=> qemu: no state to save if QEMU isn't running

src/agent/rustjail/src/sync.rs
It should check the read count and return an
error if read count didn't match the expected
number.
Fixes: #1233
=> rustjail: fix the issue of sync read

src/agent/rustjail/src/validator.rs
The network ns is shared with the guest, skip looking for it
in the spec
Fixes: #1228
=> rustjail: allow network sysctls

src/agent/src/namespace.rs, src/agent/src/sandbox.rs
The main goal of this PR is to fix #1220 . According to an annotation on code a pid namespace should not be persisted (I assume this information is true) so I added a checking for that condition.
Some minor improvements are sent alongside.
=> Agent: return error on trying to persist a pid namespace and minor improvements

src/runtime/containerd-shim-v2/delete.go
RemoveContainerRequest results in calling to deleteContainer, according
to spec calling to RemoveContainer is idempotent and "must not return
an error if the container has already been removed", hence, don't
return error if the error reports that the container is not found.
Fixes: #836
=> shimv2: Avoid double removing of container from sandbox

.github/workflows/snap-release.yaml
According to the new snap document
`docs/install/snap-installation-guide.md`, Kata Containers 2.x should
be available in the snapcraft `candidate` channel.
fixes #1174
=> [backport] snap: fix snap release channel

tools/osbuilder/rootfs-builder/rootfs.sh
Falling through the switch cases in docker_extra_args() looks like a
typo and causes issues when building with podman, as `--security-opt
apparmor=unconfinded" shouldn't be passed if Apparmor is no enable on
the system.
Fixes: #1241 
=> rootfs: Don't fallthrough in the docker_extra_args() switch

src/runtime/go.mod, src/runtime/go.sum, src/runtime/vendor/github.com/kata-containers/govmm/qemu/qemu.go, src/runtime/vendor/github.com/kata-containers/govmm/qemu/qmp.go, src/runtime/vendor/github.com/sirupsen/logrus/go.mod, src/runtime/vendor/modules.txt, src/runtime/virtcontainers/container.go, src/runtime/virtcontainers/device/config/config.go, src/runtime/virtcontainers/device/drivers/block.go, src/runtime/virtcontainers/kata_agent.go, src/runtime/virtcontainers/kata_agent_test.go, src/runtime/virtcontainers/qemu.go, src/runtime/virtcontainers/sandbox.go
If a volume is backed by a block device, let's make sure we take into account whether it should be hot plugged RO or not.
While updating this, I made some minor non-functional changes to correct comments, make storage handling a bit more clear.
=> storage: cleanup and support read only block dev hotplug

snap/snapcraft.yaml
The snap build pulls the latest release of `yq`, but `yq` version 4 changed the CLI syntax for reading a YAML file.
Update the snap config file to use the new `yq` v4 syntax.
Fixes: #1232.
=> snap: Fix yq error in build

snap/snapcraft.yaml
yq major releases are not backward compatible, install the same
major version used in the CI to avoid conflics building the kata
components.
We should update yq when the CI updates it, not before.
fixes #1232
=> Fix snap CI

snap/snapcraft.yaml
yq major releases are not backward compatible, install the same
major version used in the CI to avoid conflics building the kata
components.
We should update yq when the CI updates it, not before.
fixes #1232
=> [backport] snap: tag yq version

.github/workflows/main.yaml, .github/workflows/release.yaml, tools/packaging/release/tag_repos.sh, tools/packaging/release/update-repository-version.sh
GH Actions deprecated set-env, which was utilized for a couple of workflows (in particular release).  Let's update.
While at it, for 2.0 we weren't tagging/bumping the tests repo. Let's continue to do this.
=> Fix release scripts

.github/workflows/main.yaml, .github/workflows/release.yaml
Prior fix... didn't fix the workflow.
After forking and testing, I verified that the environment variable is now being passed between stages of each job.
=> Final fix probably 2.0 dev

.github/workflows/main.yaml
No need to dereference the environment variable. Doing so will result in
a true evaluation, which was causing NEMU to be tracked as built, when
it actually wasn't. This only impacts 1.x workflows, and is why it
wasn't caught with 2.x release process.
Fixes: #1273
=> actions: fix error with nemu build job

src/agent/rustjail/src/container.rs
In the container's destroy method, it should destroy
the container's cgroups.
Fixes: #1291
=> rustjail: fix the issue of missing destroy contaienr cgroups

src/agent/src/device.rs, src/agent/src/linux_abi.rs, src/agent/src/mount.rs, src/agent/src/uevent.rs
Support pmem-csi[1] k8s pluging, unlike SCSI and virtio devices,
NVDIMM/PMEM devices support DAX, improving IO Read and Write
operations.
fixes #1289
[1]: https://github.com/intel/pmem-csi
=> agent: implement NVDIMM/PMEM block driver

.github/workflows/static-checks.yaml
This PR updates the ubuntu version from 18.04 to 20.04 that will be
used for the github actions.
Fixes #1295
=> github: Update ubuntu version to 20.04

src/agent/src/device.rs, src/agent/src/mount.rs, src/agent/src/sandbox.rs
To make them follow the rust convention and easier to read.
Fixes: #1235
=> agent: Add underscore for constants

.github/workflows/snap-release.yaml
Stable and candidate snapcraft's channels are used to release Kata
Containers 1.x and 2.x respectively. Alpha and RC releases shouldn't
be pushed to the snap store because there are not enough channels
for all the releases of Kata Containers 1.x and 2.x.
fixes #1303
=> snap: Don't release Kata Alpha/RC in snap store

.github/workflows/kata-deploy-test.yaml, README.md, ci/lib.sh, docs/how-to/how-to-set-prometheus-in-k8s.md, docs/install/snap-installation-guide.md, tools/packaging/kernel/README.md, tools/packaging/release/tag_repos_test.sh, tools/packaging/scripts/gen_versions_txt.sh, utils/README.md
Change all mentioning of 2.0-dev to main so that we can rename the
default branch to main.
Fixes: #1310
=> branch: change 2.0-dev to main

tools/osbuilder/dracut/Dockerfile.in, tools/osbuilder/rootfs-builder/centos/Dockerfile.in, tools/osbuilder/rootfs-builder/clearlinux/Dockerfile.in, tools/osbuilder/rootfs-builder/debian/Dockerfile-aarch64.in, tools/osbuilder/rootfs-builder/debian/Dockerfile.in, tools/osbuilder/rootfs-builder/fedora/Dockerfile.in, tools/osbuilder/rootfs-builder/rootfs.sh, tools/osbuilder/rootfs-builder/suse/install-packages.sh, tools/osbuilder/rootfs-builder/ubuntu/Dockerfile-aarch64.in, tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in, tools/osbuilder/scripts/lib.sh, tools/osbuilder/tests/test_images.sh, versions.yaml
AFAICT cmake is referenced in the osbuilder scripts, but never actually invoked.
=> osbuilder: remove traces of cmake

src/agent/Cargo.lock, src/agent/Cargo.toml, src/agent/rustjail/src/cgroups/fs/mod.rs
We should create the container's cgroup under the system's
cgroup default path such as "/sys/fs/cgroup/<sub system>",
instead of under the kata-agnet's process's cgroup path,
which would under the systemd's cgroup such as
"/sys/fs/cgroup/systemd/system.slice/kata-agent.service"
Fixes: #1319
=> rustjail: fix the issue of container's cgroup root path

src/agent/protocols/build.rs, src/agent/rustjail/src/mount.rs
This patch fixed the security issue if the container images has
unsafe symlink to the container rootfs and hackers can be exploit
this symlink to hack the guest system. e.g. make directory or files
on guest.
CVE-2020-2026
Signed-off-by: Qingyuan Hou <qingyuan.hou@linux.alibaba.com>
=> agent: add secure_join to prevent softlink escape

src/runtime/containerd-shim-v2/delete.go, src/runtime/containerd-shim-v2/start.go
According to runtime-spec:
The poststop hooks MUST be invoked by the runtime. If any
poststop hook fails, the runtime MUST log a warning, but
the remaining hooks and lifecycle continue as if the hook
had succeeded.
Fixes: #1252
=> shimv2: log a warning and continue on post-stop hook failure

src/runtime/Makefile, tools/packaging/kata-monitor/Dockerfile
- add a reference Dockerfile to tools
- update kata-monitor build to:
1) utilize the kata buildflags, which were dropped before
2) disable CGO, so we have option for building in alpine
From root of the repository, example build:
$ docker build -f tools/packaging/kata-monitor/Dockerfile -t kata-monitor .
Fixes: #1135
=> kata-monitor: allow for building for alpine

src/runtime/Makefile
CGO_ENABLED=0 and -buildmode=pie are not compatible and may lead build failing in some OS.
Specify buildmode=exe to overwrite the value set in BUILDFLAGS
Fixes: #1343
=> kata-monitor: set buildmode to exe to avoid build failing

tools/osbuilder/rootfs-builder/rootfs.sh
To enforce LIBC=gnu to rootfs.sh for ppc64le, instead of error and exit if not set.
Fixes: #1339
Signed-off-by: Jing Wang <jing.wang4@ibm.com>
@bpradipt @Amulyam24 @clnperez @fidencio
Please review. Thanks!
See comment: https://github.com/kata-containers/kata-containers/pull/1314#issuecomment-770016030
=> osbuilder: Enforcing LIBC=gnu to rootfs build for ppc64le

src/agent/src/linux_abi.rs, src/runtime/cli/config/configuration-qemu.toml.in, src/runtime/pkg/katatestutils/utils.go, src/runtime/pkg/katautils/config.go, src/runtime/virtcontainers/hypervisor.go, src/runtime/virtcontainers/qemu.go, src/runtime/virtcontainers/qemu_arch_base.go, src/runtime/virtcontainers/qemu_arm64.go, tools/packaging/kernel/configs/fragments/arm64/acpi.conf, tools/packaging/kernel/configs/fragments/arm64/base.conf
acpi is enabled for kata 1.x, port and rebase code for 2.x
including:
runtime: enable pflash;
agent: add acpi support for pci bus path;
packaging: enable CONFIG_RTC_DRV_EFI;
Fixes: #1317
@bergwolf  @jodh-intel
=> arm64: enable acpi for qemu/virt.

src/agent/src/config.rs, src/agent/src/main.rs, src/agent/src/metrics.rs, src/agent/src/mount.rs, src/agent/src/namespace.rs, src/agent/src/netlink.rs, src/agent/src/network.rs, src/agent/src/rpc.rs, src/agent/src/sandbox.rs, src/agent/src/version.rs.in
Remove following attributes:
`#![allow(non_camel_case_types)]`
`#![allow(unused_parens)]`
`#![allow(unused_unsafe)]`
`#![allow(dead_code)]`
`#![allow(non_snake_case)`
=> Fix lints and remove allow attributes which silence these warnings

tools/packaging/qemu/patches/5.0.x/0004-virtiofsd-Add-o-allow_direct_io-no_allow_direct_io-o.patch, tools/packaging/qemu/patches/5.0.x/0005-virtiofsd-extract-lo_do_open-from-lo_open.patch, tools/packaging/qemu/patches/5.0.x/0006-virtiofsd-optionally-return-inode-pointer-from-lo_do.patch, tools/packaging/qemu/patches/5.0.x/0007-virtiofsd-prevent-opening-of-special-files-CVE-2020-.patch, tools/packaging/qemu/patches/5.0.x/0008-virtiofsd-Add-_llseek-to-the-seccomp-whitelist.patch, tools/packaging/qemu/patches/5.0.x/0009-virtiofsd-Add-restart_syscall-to-the-seccomp-whiteli.patch, tools/packaging/qemu/patches/5.1.x/0007-virtiofsd-Add-o-allow_direct_io-no_allow_direct_io-o.patch, tools/packaging/qemu/patches/5.1.x/0008-virtiofsd-extract-lo_do_open-from-lo_open.patch, tools/packaging/qemu/patches/5.1.x/0009-virtiofsd-optionally-return-inode-pointer-from-lo_do.patch, tools/packaging/qemu/patches/5.1.x/0010-virtiofsd-prevent-opening-of-special-files-CVE-2020-.patch, tools/packaging/qemu/patches/5.1.x/0011-virtiofsd-Add-_llseek-to-the-seccomp-whitelist.patch, tools/packaging/qemu/patches/5.1.x/0012-virtiofsd-Add-restart_syscall-to-the-seccomp-whiteli.patch
This series is based on
https://lists.gnu.org/archive/html/qemu-devel/2021-02/msg01787.html, and
was kindly brought up by David Gilbert.
Fixes: #1361 
@wainersm, @jcvenegas, I know you guys are working on getting 5.2.0 and I'd appreciate if you could adjust your patches to also include the fixes provided in the series pointed abve.
Last but not least, I do believe we need this backported to 1.x as well.
=> qemu: Add security fixes for CVE-2020-35517

src/agent/README.md
Add a bit to the agent README about installing protoc manually for Power (ppc64le)
Fixes: #1068
Signed-off-by: Christy Norman <christy@linux.vnet.ibm.com>
=> agent: README update to install protoc for ppc64le

src/agent/Cargo.lock, src/agent/rustjail/Cargo.toml, src/agent/rustjail/src/capabilities.rs, src/agent/rustjail/src/container.rs
The runtime determines the kernel capability set at run time.
In addition, this commit supports new capabilities: CAP_BPF, CAP_PERFMON and CAP_CHECKPOINT_RESTORE.
Fixes: #1370 
=> rustjail: get all capabilities dynamically

src/agent/Cargo.lock, src/agent/rustjail/Cargo.toml, src/agent/rustjail/src/container.rs
The current implementation of rustjail uses the specific _setrlimit_.
This patch uses rlimit crate for maintainability.
Fixes: #1372
=> rustjail: use rlimit crate

tools/packaging/kernel/build-kernel.sh
This directory has been automatically removed as there's no files inside
it, as part of d3c98620591f902fec9cc2abbe6f03f93122052d
Let's improve the logic in the scripts to avoid failing in case the
"experimental" dir is not present.
Fixes: #1328
=> kernel: Don't fail if "experimental" dir doesn't exist

ci/install_yq.sh
Since the resolution of https://github.com/mikefarah/yq/issues/502, the `yq` binary is no longer broken on s390x. This is an upgrade to the latest v3 version of yq (v4 has new syntax).
Fixes: #1260
Depends-on: https://github.com/kata-containers/tests/pull/3158
=> ci: Upgrade to yq 3.4.1

tools/packaging/kernel/build-kernel.sh
Installing the built uncompressed vmlinux kernel will not work on s390x, QEMU will complain:
```
Linux kernel boot failure: An attempt to boot a vmlinux ELF image failed.
This image does not contain all parts necessary for starting up.
Use bzImage or arch/s390/boot/compressed/vmlinux instead.
```
Hence, use that kernel image on s390x.
Fixes: #1264
=> packaging: Fix vmlinux kernel install on s390x

src/agent/Makefile, tools/osbuilder/rootfs-builder/rootfs.sh
Since there is no Rust target for musl on s390x, builds on s390x should use glibc.
This PR makes glibc the default on s390x as per the agent Makefile, removes the "Cannot build Rust agent on s390x" restriction in the osbuilder `rootfs.sh` and only installs musl in the build environment when it is required.
Fixes: #1262
=> Build for glibc on s390x

tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in, tools/osbuilder/scripts/lib.sh
For building the rootfs with `USE_DOCKER=true` on s390x,
- Install the required protobuf-compiler on Ubuntu (this might be a common code requirement)
- Install correct libc Rust target (glibc on s390x)
- Do not skip Rust installation on s390x
Fixes: #1266
No backport needed
=> osbuilder: Fix USE_DOCKER on s390x

docs/Developer-Guide.md
Change the installation directory of virtiofsd to kata-qemu.
Fixes: #1379
=> docs: Fix the installation directory of virtiofsd

.github/workflows/kata-deploy-test.yaml
We're currently running kata-deploy-test for every issue opened, for
every comment in the issue.  Issues, themselves, shouldn't be triggering
those as they can't cause any code change.
With this in mind, let's restrict ourselves to run those on
pull-requests only.
Fixes: #1341
=> github: Only run kata-deploy-test on pull-requests

docs/Documentation-Requirements.md, docs/design/architecture.md, docs/how-to/how-to-import-kata-logs-with-fluentd.md, docs/how-to/how-to-use-kata-containers-with-acrn.md, src/runtime/README.md, src/runtime/cli/config-generated.go.in, src/runtime/cli/main.go, src/runtime/cli/main_test.go, tools/packaging/release/kata-deploy-binaries.sh, tools/packaging/static-build/scripts/kata-configure-docker.sh
Change `--kata-config` and --kata-show-default-config-paths` to be prefixless, but keep the old option as alias.
=> cli: Add aliases for `kata-` options 

src/agent/src/netlink.rs
The unit test for list_interfaces() checks that the hardware address
returned for each interface has non-zero length.  However, that need not be
the case.  Point-to-point devices, such as ppp, or tun devices in certain
configurations may not have a hardware address, which is represented as
a zero length address here.
This happens on my machine with a tun0 device created by OpenVPN.
fixes #1377
=> agent: Remove bogus check from list_interfaces() unit test

src/runtime/virtcontainers/kata_agent.go
Today we only clear out the cpuset details when doing an update call on
existing container/pods. This works in the case of Kubernetes, but not
in the case where we are explicitly setting the cpuset details at boot
time. For example, if you are running a single container via docker ala:
docker run --cpuset-cpus 0-3 -it alpine sh
What would happen is the cpuset info would be passed in with the
container spec for create container request to the agent. At that point
in time, there'd only be the defualt number of CPUs available in the
guest (1), so you'd be left with cpusets set to 0. Next, we'd hotplug
the vCPUs, providing 0-4 CPUs in the guest, but the cpuset would never
be updated, leaving the application tied to CPU 0.
Ouch.
Until the day we support cpusets in the guest, let's make sure …
=> runtime: cpuset: when creating container, don't pass cpuset details

src/runtime/cli/config/configuration-acrn.toml.in, src/runtime/cli/config/configuration-clh.toml.in, src/runtime/cli/config/configuration-qemu.toml.in, src/runtime/pkg/katautils/config.go
Today hooks are only described in the QEMU toml. This shouldn't be VMM
specific -- let's make sure these are advertised for Cloud Hypervisor as
well.
Fixes: #1401
=> runtime: clh-config: add runtime hooks to the clh toml

docs/Licensing-strategy.md
This PR updates the licensing strategy document to use the proper
tests repository for kata 2.0
Fixes #1413
=> docs: Update licensing strategy to use kata 2.0 repository

tools/osbuilder/image-builder/image_builder.sh, tools/osbuilder/rootfs-builder/rootfs.sh
Give the user chance to specify their own registry in event the default
provided are not accessible, desirable.
Fixes: #1393
=> osbuilder: Allow image registry to be customizable

src/agent/oci/src/lib.rs, src/agent/rustjail/src/container.rs
This PR fixes wrong serialization of OCI state objects in some cases.
OCI hooks end up with a JSON string with double quotes in `state` field.
This happens because of confusion `Debug` and `Display` traits. Debug trait
returns string representation with double quotes.
Ideally we should not use Debug as a part of serialization process, so a bit
more safer fix would be to move container states to `oci` crate and simply
disallow wrong values in that field.
`ContainerState` in go spec: https://github.com/opencontainers/runtime-spec/blob/master/specs-go/state.go#L4
Fixes: #1404
=> Agent: OCI hooks return malformed json

docs/Developer-Guide.md, src/runtime/cli/kata-exec.go, src/runtime/pkg/kata-monitor/shim_client.go
Parse agent socket address by conversation to improve usability of
using guest debug console.
Fixes: #1329
=> runtime: connect guest debug console bypass kata-monitor

tools/packaging/kata-deploy/README.md, tools/packaging/kata-deploy/scripts/kata-deploy.sh, tools/packaging/release/kata-deploy-binaries.sh
This series ensures CRI-O uses shimv2 & the "vm" runtime type.  It also contains some preliminary patches doing some cleanups and re-using some bits from the containerd setup.
=> kata-deploy: Ensure CRI-O uses shimv2 & the "vm" runtime type

src/agent/rustjail/src/cgroups/notifier.rs, src/agent/src/sandbox.rs
If the container has exited, the sender in notifier watching OOM events
will be dropped after the loop exited, and recv() from the according
receiver will get None.
This will lead two problems for get_oom_event rpc all from agent:
- return an wrong OOM event.
- continuously return OOM events.
Fixes: #1369
=> agent: Stop receive message from Receiver if got None

src/agent/rustjail/src/container.rs
Agent sends -1 PID when invoking OCI hooks.
How to reproduce:
```
mount guest image
echo -e '#!/bin/sh\nread line\necho "$line" >> /var/run/kata-containers/shared/containers/repro-test/rootfs/home/log' >> ${GUEST_ROOTFS_PATH}/usr/share/oci/hooks/prestart/test.sh
chmod a+x ${GUEST_ROOTFS_PATH}/usr/share/oci/hooks/prestart/test.sh
sudo umount ~/mnt
sudo ctr run --rm --runtime io.containerd.kata-clh.v2  -t docker.io/library/busybox:latest repro-test sh -c "cat /home/log"
{"ociVersion":"1.0.2-dev","id":"repro-test","status":"created","pid":-1,"bundle":"/run/kata-containers/repro-test"}
```
OCI state struct is initialized before obtaining PID, so this PR moves `oci_state` call down, right after we get the id.
Fixes: #1458
=> agent: Agent invokes OCI hooks with wrong PID

src/agent/rustjail/src/cgroups/fs/mod.rs
BFQ weight controller is using the same BFQ weight scheme (i.e 1->1000).
Therefore, there is no need to do the conversion.
More details here: https://github.com/opencontainers/runc/pull/2786
Fixes: #1440
=> rustjail: fix blkio conversion

src/runtime/containerd-shim-v2/create.go
Looks like we inadvertantly removed the check on the loadRuntimeConfig
error return value. Adding back...
Fixes: #1474
=> runtime: check if error loading runtime config

src/runtime/containerd-shim-v2/create.go, src/runtime/containerd-shim-v2/service.go, src/runtime/virtcontainers/interfaces.go, src/runtime/virtcontainers/sandbox.go
Since the kata's hypervisor process is in the network namespace,
which is close to container's process, and some host metrics
such as cadvisor can use this pid to access the network namespace
to get some network metrics. Thus this commit replace the shim's
pid with the hypervisor's pid.
Fixes: #1451
=> shimv2: return the hypervisor's pid as the container pid

src/runtime/containerd-shim-v2/service.go
Each Kata Containers application should generate log records with a specified
structure. Currently on containerd-shim-v2's logs, the required 'name' field
is missing. This changed its logger to append the application name on each
and every emitted entries.
Fixes #1479
Related-to: github.com/kata-containers/tests/issues/3260
Suggested-by: James O. D. Hunt <james.o.hunt@intel.com>
=> runtime: Fix missing 'name' field on containerd-shim-v2 logs

ci/install_musl.sh, tools/osbuilder/scripts/lib.sh
Currently, musl toolchain installation on arm64 is just downloading from
a website. It's unsafe in case the website corrupts. So build musl
toolchain from source if it can't be downloaded.
Fixes: #1481
@GabyCT @jodh-intel
=> osbuilder/arm64: build musl toolchain from source code if needed

tools/osbuilder/scripts/lib.sh
In the last fix, the decompression ops is deleted by mistake and need
add it back.
Fixes: #1490
@lifupan @bergwolf
=> musl/arm64: decompression before use the tarball.

src/agent/rustjail/src/mount.rs
When do pass guest device files to container, the source
file wouldn't be a regular file, but we also need to create
a corresponding destination file to bind mount source file
to it. Thus it's better to check whether the source file
was a directory instead of regular file.
Fixes: #1477
=> rustjail: fix the issue of bind mount device file from guest

.github/workflows/static-checks.yaml, tools/agent-ctl/Cargo.lock, tools/agent-ctl/Cargo.toml, tools/agent-ctl/Makefile, tools/agent-ctl/src/client.rs
The recent switch to an async rust agent broke the `agent-ctl` tool.
However, we didn't notice because that isn't being built by the CI.
Fix the breakage by passing a ttRPC context to all ttRPC API calls and
also build the tool as part of the static checks CI.
Fixes: #1471.
=> agent-ctl: Unbreak build

tools/osbuilder/README.md, tools/osbuilder/dockerfiles/QAT/Dockerfile, tools/osbuilder/dockerfiles/QAT/README.md, tools/osbuilder/dockerfiles/QAT/qat.conf, tools/osbuilder/dockerfiles/QAT/run.sh
Update the Intel QAT Dockerfile to work with the 2.0 repos, fix some
bugs with building Debian/Ubuntu rootfs, and update the latest QAT
driver.
Fixes: 1419
Signed-off-by: Eric Adams eric.adams@intel.com
=> osbuilder: Port QAT Dockerfile to 2.0 repo

src/agent/rustjail/Cargo.toml, src/agent/rustjail/src/container.rs, src/agent/rustjail/src/lib.rs, src/agent/rustjail/src/utils.rs
Since the crate dirs::home_dir function depends on the
libc's api: getpwuid_r, but this api function wouldn't
be static linked on glibc, thus we'd better to figure
out an alternative way to get the home dir from /etc/passwd.
For much more info about this glibc's issue, please see:
https://sourceware.org/bugzilla/show_bug.cgi?id=19341.
This commit read and parse the "/etc/passwd" directly and
fetch the corresponding uid's home dir.
Fixes: #675
=> rustjail: fix the issue of home_dir function

src/runtime/containerd-shim-v2/exec.go
Extra groups were not being handled when exec'ing. Ensure
that these are handled.
Before this, running a pod with:
```
...snippet...
securityContext:
fsGroup: 266
runAsGroup: 51020
runAsUser: 264
```
And then exec'ing would not supply the fsGroup:
```
$ kubectl exec -it kata-bb  -- sh -c id
uid=264 gid=51020
```
Fixes: #1500
Signed-off-by: Eric Ernst  <eric.g.ernst@gmail.com>
=> exec: ensure sup groups are added to agent request

src/agent/.gitignore, src/agent/Makefile
Add target to run codecov report locally.
Useful to identify what are the missing lines
to be covered by unit test.
Fixes: #1487
=> agent: makefile: Add codecov target

src/runtime/containerd-shim-v2/utils.go
Other RPC calls return Pid of hypervisor, the TaskExit should
return the same Pid.
Fixes: #1497
=> runtime: return hypervisor Pid in TaskExit event

snap/snapcraft.yaml, tools/packaging/scripts/configure-hypervisor.sh
Recently I realized that snapcraft will not have virtiofsd included on snap once QEMU is updated to 5.2.0. Also @egernst reported to me a misbehave related with my changes to `configure-hypervisor.sh` script. Thus I made fixes for those issues and put together on this PR as a respin of https://github.com/kata-containers/kata-containers/pull/1349
=> Bump to QEMU 5.2.0 - respin

src/runtime/virtcontainers/pkg/cgroups/manager.go, src/runtime/virtcontainers/pkg/cgroups/manager_test.go, src/runtime/virtcontainers/pkg/cgroups/utils.go, src/runtime/virtcontainers/pkg/cgroups/utils_test.go
Systemd cgroup handling is broken as we never ported:
https://github.com/kata-containers/runtime/pull/2817
Fixes https://github.com/kata-containers/kata-containers/issues/599
=> [forwardport] Fixup systemd cgroup handling

src/agent/rustjail/src/utils.rs
This unneeded import was accidentally introduced by 81607e34.
fixes #1507
=> agent: Fix unused import warning in unit tests

tools/osbuilder/rootfs-builder/fedora/Dockerfile.in, tools/osbuilder/scripts/lib.sh
For building rootfs with docker, glibc based rust target should be installed on ppc64le.
Fixes: #1417
=> osbuiler: fixing USE_DOCKER for ppc64le

src/agent/Cargo.lock
Commit 81607e34 updated src/agent/rustjail/Cargo.toml, to remove an
unneeded dependency.  That causes cargo to update src/agent/Cargo.lock
on each build.  However, the change to Cargo.lock wasn't checked in
meaning anyone working on the agent code will get bogus diffs with every
build.  Check in the missing file to fix this.
fixes #1505
=> agent: Update Cargo.lock for earlier dependency change

docs/use-cases/using-Intel-QAT-and-kata.md
This fixes the guide to work with the Kata 2.0 repos and provide more
details on how to verify with ctr and kubernetes.
Fixes: #1362
Signed-off-by: Adams, Eric <eric.adams@intel.com>
=> docs: Update QAT instructions to work with Kata 2.0 repos

src/runtime/containerd-shim-v2/service.go
Each Kata Containers application should generate log records with a specified
structure. Currently on containerd-shim-v2's logs, the required 'name' field
is missing. This changed its logger to append the application name on each
and every emitted entries.
Fixes #1479
Related-to: github.com/kata-containers/tests/issues/3260
Suggested-by: James O. D. Hunt <james.o.hunt@intel.com>
=> [backport] runtime: Fix missing 'name' field on containerd-shim-v2 logs

src/runtime/containerd-shim-v2/create.go, src/runtime/containerd-shim-v2/service.go, src/runtime/containerd-shim-v2/utils.go, src/runtime/virtcontainers/interfaces.go, src/runtime/virtcontainers/pkg/vcmock/sandbox.go, src/runtime/virtcontainers/sandbox.go
Enable cAdvisor network stats in stable-2.0 branch:
backport https://github.com/kata-containers/kata-containers/pull/1452 and https://github.com/kata-containers/kata-containers/pull/1498
=> [backport] shimv2: return the hypervisor's pid as the container pid

src/agent/src/config.rs
To make debugging and testing easier, allow the ttRPC server address to
be specified via `/proc/cmdline` as `agent.server_addr=`.
Fixes: #1516.
=> agent: Allow server address to be specified on kernel command-line

src/agent/src/rpc.rs, src/runtime/cli/kata-exec.go, src/runtime/containerd-shim-v2/service.go, src/runtime/containerd-shim-v2/service_test.go, src/runtime/pkg/katatestutils/utils.go, src/runtime/pkg/katautils/utils.go, src/runtime/pkg/katautils/utils_test.go, src/runtime/virtcontainers/pkg/vcmock/sandbox.go
Validate CID for agent and runtime
Validate the container ID as we cannot / should not rely on the container manager to do this.
Fixes: #1520.
=> Verify container ID

tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
Let's tag the yet non existent 2.0.2 image, so whoever deploys kata
using kata-deploy from the release tarball is pointed to the correct
image.
Fixes: #1493
=> kata-deploy: Use the correct image for 2.0.2 release

tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
Let's ensure we use the appropriate tag for the release, even before it
was actually created.
Fixes: #1493
=> kata-deploy: Use the correct tag for 2.1-alpha1 release

src/runtime/virtcontainers/pkg/agent/protocols/client/client.go
On some setups, starting multiple kata pods (qemu) simultaneously on the same node
might cause kata VMs booting time to increase and the pods to fail with:
Failed to check if grpc server is working: rpc error: code = DeadlineExceeded desc = timed
out connecting to vsock 1358662990:1024: unknown
Increasing default dialing timeout to 30s should cover most cases.
Fixes: #1543
(backport https://github.com/kata-containers/kata-containers/pull/1544)
=> [backport] runtime: increase dial timeout

src/runtime/containerd-shim-v2/service.go, src/runtime/containerd-shim-v2/service_test.go, src/runtime/pkg/katatestutils/utils.go, src/runtime/virtcontainers/acrn.go, src/runtime/virtcontainers/api.go, src/runtime/virtcontainers/container.go, src/runtime/virtcontainers/factory/factory.go, src/runtime/virtcontainers/kata_agent.go, src/runtime/virtcontainers/mount.go, src/runtime/virtcontainers/network.go, src/runtime/virtcontainers/qemu.go, src/runtime/virtcontainers/sandbox.go
Return ctx in trace() functions to correct span ordering.
Fixes #1550
=> runtime: Fix trace span ordering and static checks

src/agent/src/device.rs, src/runtime/virtcontainers/README.md, src/runtime/virtcontainers/container.go, src/runtime/virtcontainers/documentation/api/1.0/api.md, src/runtime/virtcontainers/interfaces.go, src/runtime/virtcontainers/persist/api/config.go
Virtcontainers API documentation is outdated, update documentation from the latest
source.
Fixes: #1455
=> runtime: update virtcontainers API documentation

src/runtime/virtcontainers/container.go, src/runtime/virtcontainers/kata_agent.go, src/runtime/virtcontainers/mount.go
Right now we rely heavily on mount propagation to share host
files/directories to the guest. However, because virtiofsd
pivots and moves itself to a separate mount namespace, the remount
mount is not present in virtiofsd's mount. And it causes guest to be
able to write to the host RO volume.
To fix it, create a private RO mount and then move it to the host mounts
dir so that it will be present readonly in the host-guest shared dir.
=> runtime: fix virtiofsd RO volume sharing

pkg/logging/src/lib.rs, src/agent/Cargo.lock, src/agent/Cargo.toml, src/agent/src/config.rs, src/agent/src/main.rs, src/agent/src/signal.rs, src/agent/src/uevent.rs, src/agent/src/util.rs, src/trace-forwarder/src/main.rs, tools/agent-ctl/src/main.rs
The agent doesn't normally shutdown: it doesn't need to be as it is
killed *after* the workload has finished. However, a clean and ordered
shutdown sequence is required to support agent tracing, since all trace
spans need to be completed to ensure a valid trace transaction.
Enable a controlled shutdown by allowing the main threads (tasks) to be
stopped.
To allow this to happen, each thread is now passed a shutdown channel
which it must listen to asynchronously, and shut down the thread if
activity is detected on that channel.
Since some threads are created for I/O and since the standard `io::copy`
cannot be stopped, added a new `interruptable_io_copier()` function
which shares the same semantics as `io::copy()`, but which is also
passed a shutdown channel to allow asynchronous I/O …
=> agent: Enable clean shutdown

src/runtime/virtcontainers/qemu_arch_base.go
Use `on` and `off` to enable or disable features,
`no` prefix is deprecated
fixes #1545
=> runtime: add support for QEMU 6

src/runtime/virtcontainers/container.go
A wrong path was being used for container directory when
virtiofs is utilized. This resulted in a warning message in
logs when a container is killed, or completes:
level=warning msg="Could not remove container share dir"
Without proper removal, they'd later be cleaned up when the shared
path is removed as part of stopping the sandbox.
Fixes: #1559
Before, we would create a container directory at
/run/kata-containers/share/sandboxes/<sandboxid>/<container-id>
This is no longer the case with our slavemount setup. container path is now at:
/run/kata-containers/share/sandboxes/<sandbox-id>/mounts/<container-id>
=> container: on cleanup, rm container directory for mounts path

src/runtime/Makefile, src/runtime/pkg/katautils/hook_test.go, src/runtime/virtcontainers/pkg/mock/mock.go
`make test` depends mock hook in virtcontainers directory,
before test, install it first.
Fixes: #1554
=> test: install mock hook binary before test

src/runtime/Makefile
Allow enable DAX using env variable.
Fixes: #1547
=> runtime: makefile allow override DAX value

src/runtime/virtcontainers/qemu.go, src/runtime/virtcontainers/qemu_amd64.go, src/runtime/virtcontainers/qemu_amd64_test.go, src/runtime/virtcontainers/qemu_arch_base.go, src/runtime/virtcontainers/qemu_arch_base_test.go, src/runtime/virtcontainers/qemu_arm64.go, src/runtime/virtcontainers/qemu_arm64_test.go, src/runtime/virtcontainers/qemu_s390x.go, src/runtime/virtcontainers/qemu_s390x_test.go
#1389 has added a context for many signatures to improve trace spans.
Functions specific to s390x lack this. Add context where required. This
affects some common code signatures, since some functions that do not
require context on other architectures do require it on s390x.
Also remove an unnecessary import in test_qemu_s390x.go.
Fixes: #1562
/cc @cmaf 
no backport required
=> virtcontainers: Fix missing contexts in s390x

tools/packaging/kernel/patches/5.10.x/0001-NO-UPSTREAM-9P-always-use-cached-inode-to-fill-in-v9.patch, tools/packaging/kernel/patches/5.10.x/0002-arm64-mm-Define-arch_get_mappable_range.patch, versions.yaml
Linux 5.10.x is the new LTS branch, move
kata to a more recent kernel branch.
Fixes: #1288
Depends-on: github.com/kata-containers/tests#3363
=> versions: kernel 5.10.x

docs/install/README.md, docs/install/centos-installation-guide.md, docs/install/fedora-installation-guide.md
Current docs are outdated and have instructions for installing `kata-runtime`, which consists in packages built from 1.x repository.  Let's update the instructions and point to the `kata-containers`, which consist in the package built from the 2.x repository.
Fixes: #1582, #1583
=> Update install docs for Fedora and CentOS

docs/install/snap-installation-guide.md
As this repo is specific to the kata-containers 2.x, let's stop
mentioning / referring to the 1.x here, including how to setup and use
the snap package for 1.x.
Fixes: #1601
=> docs: Update snap install guide

src/runtime/containerd-shim-v2/create.go
Shimv2 protocol CreateTaskRequest.Options has a type of *google_protobuf.Any.
If the call is from Docker, to decode the request,
the proto types(github.com/containerd/containerd/runtime/v2/runc/options)
should be imported.
Fixes: #1576
=> runtime: import runtime/v2/runc/options to decode request from Docker

src/runtime/virtcontainers/agent.go, src/runtime/virtcontainers/kata_agent.go, src/runtime/virtcontainers/mock_agent.go
Kata Containers 2.0 only have one type of agent, so there is no
need to use interface as config's type
Fixes: #1610
=> runtime: use concrete KataAgentConfig instead of interface type

src/runtime/pkg/katautils/tracing.go, src/runtime/virtcontainers/kata_agent.go
There are some prints which are output very frequently when the workload is up and running. Let's move these ones from info/debug to trace.
If we are losing visibility, let's add debug prints to the request caller, rather than in the request handler, so we can view just the useful calls when debugging.
=> Dechat deruntime

tools/osbuilder/image-builder/Dockerfile, tools/osbuilder/rootfs-builder/alpine/Dockerfile.in, tools/osbuilder/rootfs-builder/centos/Dockerfile.in, tools/osbuilder/rootfs-builder/clearlinux/Dockerfile.in, tools/osbuilder/rootfs-builder/debian/Dockerfile-aarch64.in, tools/osbuilder/rootfs-builder/debian/Dockerfile.in, tools/osbuilder/rootfs-builder/fedora/Dockerfile.in, tools/osbuilder/rootfs-builder/gentoo/Dockerfile.in, tools/osbuilder/rootfs-builder/suse/Dockerfile.in, tools/osbuilder/rootfs-builder/template/Dockerfile.template, tools/osbuilder/rootfs-builder/ubuntu/Dockerfile-aarch64.in, tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in
While we introduced IMAGE_REGISTRY, we didn't actually update the
corresponding Dockerfiles to utilize it. Let's add
Fixes: #1622
=> osbuilder: update dockerfiles to utilize IMAGE_REGISTRY

tools/osbuilder/dockerfiles/QAT/Dockerfile, tools/osbuilder/dockerfiles/QAT/run.sh
This fixes the QAT driver version and provides a check early in the
building process to make sure the driver exists. It also provides
hints to users on how to fix themselves if the driver changes again.
Fixes: #1618
Signed-off-by: Eric Adams <eric.adams@intel.com>
=> osbuilder: Update QAT Dockerfile with new QAT driver version

src/agent/rustjail/src/mount.rs, src/agent/src/config.rs, src/agent/src/mount.rs, src/agent/src/rpc.rs
Rust 1.51 appears to have added a new warning in anticipation of Rust 2021,
which requires the format string for panic!()s (including via the various
assert!() macros) to be a string literal.  This triggers quite a few times
in the agent code.  This patch fixes them.
fixes #1626
=> agent: Remove many "panic message is not string literal" warnings

src/agent/src/mount.rs, src/runtime/virtcontainers/kata_agent.go, src/runtime/virtcontainers/kata_agent_test.go
fix the issue of missing pass/set fsGroup for emptyDir volumes
For k8s emptyDir volume, a specific fsGroup would
be set for it, thus runtime should pass this fsGroup
to guest and set it properly on the emptyDir volume
in guest.
Fixes: #1580
=> Fix fsgroup

src/agent/rustjail/src/pipestream.rs, src/agent/rustjail/src/sync_with_async.rs
The only right way to shutdown pipe is drop it
Otherwise PipeStream will conflict with its twins
Because they both have the same fd, and both registered.
=> Don't do anything in Pipestream::shutdown

src/agent/Cargo.lock, src/agent/Cargo.toml, src/agent/rustjail/Cargo.toml, src/agent/rustjail/src/mount.rs
- Update cgroups-rs to 0.2.5 to pull in the chain of https://github.com/rust-lang/libc/pull/1999, https://github.com/nix-rust/nix/pull/1372, and https://github.com/kata-containers/cgroups-rs/pull/38. This adds statfs constants on s390x. cgroups-rs 0.2.4 also contains this fix, but let's move to the latest 0.2.5 right away.
- Fix type for `PROC_SUPER_MAGIC` on s390x. statfs `f_type`s are `long` on most architectures, but not on s390x, where they are `uint`. Following the fix in rust-lang/libc at https://github.com/rust-lang/libc/pull/1999, the custom defined `PROC_SUPER_MAGIC` must be updated in a similar way.
Fixes: #1204
no backport required
=> agent: s390x statfs constants

src/runtime/virtcontainers/pkg/agent/protocols/client/client.go
On some setups, starting multiple kata pods (qemu) simultaneously on the same node
might cause kata VMs booting time to increase and the pods to fail with:
Failed to check if grpc server is working: rpc error: code = DeadlineExceeded desc = timed
out connecting to vsock 1358662990:1024: unknown
Increasing default dialing timeout to 30s should cover most cases.
Fixes: #1543
=> runtime: increase dial timeout

.github/workflows/kata-deploy-test.yaml
This partially reverts commit 1cce9300716035926cf8586f6b266a48f88674d0.
As mentioned in #1635, the malformed yaml wouldn't allow us to actually
test changes that were supposed to be test by this action.
So, this is now reverted and adapted accordingly.
Main differences from what we had before:
* As it tests kata-deploy itself, not the statically built binaries,
let's just use the binaries from 2.0.0 release;
* Adapt download and deploy location to the
`kata-containers/kata-containers` repo, as the original action was
based on 1.x repos;
Fixes: #1640
=> Revert "github: Remove kata-deploy-test action"

docs/how-to/how-to-set-sandbox-config-kata.md
Using "io.containerd.kata.v2" instead of deprecated "io.containerd.runc.v1".
Fixes: #1629
=> docs: update configuration for passing annotations in conatinerd

ci/lib.sh, ci/openshift-ci/images/Dockerfile.buildroot
This is required by " openshit-ci: build kata containers on CentOS 8" (https://github.com/kata-containers/tests/issues/3389).
The OpenShift CI imposes a restriction that the build root dockerfile should live on this repo instead of on tests. Well, when both repos are merged together it will save me some time.
I'm sending another commit together which replaces go with git to clone the tests repository. If this is not accepted I can work around it, but nevertheless it think it is a worth improvement (IMO we should stop cloning repositories with `go get -d`).
=> ci/openshift-ci: Prepare to build on CentOS 8

src/agent/rustjail/src/container.rs
first get the "HOME" env from "/etc/passwd", if
there's no corresponding uid entry in /etc/passwd,
then set "/" as the home env.
Fixes: #1643
=> rustjail: fix the issue of missing default home env

.github/workflows/kata-deploy-test.yaml
`/test-kata-deploy` command does **not** work, and the output returned
is:
```
Error: Comment didn't contain a valid slash command
```
So, why does this happen?
This is the regex used: `^\/([\w]+)\b *(.*)?$`, being the important part
of the command "\/([\w]+)\b", with the rest being arguments to it.
Okay, `\w` is the key here, as `\w` means: a-z, A-Z, 0-9, including the
_.
Our command is `/test-kata-deploy`, and `-` is not present as part of
`\w`.  Knowing this we need to update the command to something like:
`/test_kata_deploy`
Fixes: #1645
=> github: Fix slash-command-action usage

tools/packaging/kata-deploy/action/test-kata.sh, tools/packaging/release/Makefile, tools/packaging/release/kata-deploy-binaries.sh, tools/packaging/release/tag_repos.sh, tools/packaging/release/update-repository-version_test.sh
On commit 60f6315 we've started adding the specific version of the image
to be used, in order to ensure people using our content from a tarball
would be relying on the correct image.
However, later on, @bergwolf figured out it had some undesired side
effects, such as
https://github.com/kata-containers/kata-containers/runs/2235812941?check_suite_focus=true
What happens there is that the regular expression used to point the
image to a testing one doesn't take into consideration the $VERSION, and
that breaks the deployment.
Fixes: #1632
=> kata-deploy: Fix `test-kata.sh` and do some small cleanups / improvements in the kata-deploy script

tools/packaging/kernel/build-kernel.sh, versions.yaml
Relevant changes for experimental :
42d3e2d04 virtiofs: calculate number of scatter-gather elements accurately
413daa1a3 fuse: connection remove fix
bf109c640 fuse: implement crossmounts
1866d779d fuse: Allow fuse_fill_super_common() for submounts
fcee216be fuse: split fuse_mount off of fuse_conn
8f622e949 fuse: drop fuse_conn parameter where possible
24754db27 fuse: store fuse_conn in fuse_req
c6ff213fe fuse: add submount support to <uapi/linux/fuse.h>
d78092e49 fuse: fix page dereference after free
9a752d18c virtiofs: add logic to free up a memory range
d0cfb9dcb virtiofs: maintain a list of busy elements
6ae330cad virtiofs: serialize truncate/punch_hole and dax fault path
9483e7d58 virtiofs: define dax address space operations
2a9a609a0 virtiofs: add DAX mmap support
c2d0ad00d …
=> kernel: update experimental kernel to 5.10.x

src/agent/oci/src/lib.rs, src/agent/protocols/protos/oci.proto, src/agent/rustjail/src/lib.rs
Seccomp configuration should be updated to prepare for the future seccomp support based on the latest OCI specification.
Add:
- flags which is used with seccomp(2) in struct LinuxSeccomp
- errnoRet which is errno return code in struct LinuxSyscall
- some new seccomp actions and an architecture
Fixes: #1391
=> oci: Update seccomp configuration

tools/agent-ctl/Cargo.lock
While performing a `make` in the top directory of the project, I've
noticed that agent-ctl's Cargo.lock file was not up-to-date.
Fixes: #1655
=> tools/agent-ctl: Update Cargo.lock

src/agent/src/mount.rs
On commit 17e9a2cff5c8b it was introduced a guard for the case the mount point is already
mounted. Instead of log the mount tag ("kataShared") with this change it will print the
mount point path.
Fixes: #1398
=> agent: log the mount point if it is already mounted

tools/packaging/kata-deploy/action/test-kata.sh, tools/packaging/release/Makefile, tools/packaging/release/kata-deploy-binaries.sh, tools/packaging/release/tag_repos.sh, tools/packaging/release/update-repository-version_test.sh
On commit a649d33a4569cc968074ecde256deb602e9dcd01 we've started adding the specific version of the image
to be used, in order to ensure people using our content from a tarball
would be relying on the correct image.
However, later on, @bergwolf figured out it had some undesired side
effects, such as
https://github.com/kata-containers/kata-containers/runs/2235812941?check_suite_focus=true
What happens there is that the regular expression used to point the
image to a testing one doesn't take into consideration the $VERSION, and
that breaks the deployment.
Fixes: #1632
=> stable-2.0 | kata-deploy: Fix test-kata.sh and do some small cleanups / improvements in the kata-deploy script 

src/runtime/virtcontainers/api_test.go, src/runtime/virtcontainers/container_test.go, src/runtime/virtcontainers/kata_agent_test.go, src/runtime/virtcontainers/persist.go, src/runtime/virtcontainers/persist_test.go, src/runtime/virtcontainers/qemu_test.go, src/runtime/virtcontainers/sandbox.go, src/runtime/virtcontainers/sandbox_test.go
The property name make newcomers confused when reading code.
Since in Kata Containers 2.0 there will only be one type of store,
so it's safe to replace it by `store` simply.
Fixes: #1660
=> virtcontainers: replace newStore by store in Sandbox struct

ci/lib.sh
This PR fixes travis in stable-2.0 as is taking the branch
from the travis environment instead of using main.
Fixes #1663
=> ci: Fix travis for stable-2.0

src/agent/src/device.rs, src/agent/src/linux_abi.rs, src/agent/src/mount.rs
As described in #1628 the criteria we use to match uevents to specific devices are quite sloppy at times.  This series narrows those conditions based on each device type to make them more precise and correct.
This pull is based on #1492.
=> Refine uevent matching conditions

tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml, tools/packaging/release/update-repository-version.sh
Let's teach `update-repository-version.sh` to automatically bump the
version of the kata-deploy images to be used within that release, when
running against the `kata-containers` repo.
Fixes: #1665
=> release: automatically bump the version of the kata-deploy images

tools/packaging/kata-deploy/k8s-1.18/kata-runtimeClasses.yaml
The overhead values may not be perfect, but this is a start, and a good
reference.
Fixes: #580
=> kata-deploy: add runtimeclass that includes pod overhead

tools/packaging/release/update-repository-version.sh
I was, mistakenly, `git add`ing those files unconditionally.
Fixes: #1672
=> release: Do not git add kata-{deploy,cleanup}.yaml for the tests repo

docs/Release-Process.md
While working on the release of 2.1.0-alpha2 and 2.0.3 I've noticed that a few things that are part of https://github.com/kata-containers/kata-containers/blob/main/docs/Release-Process.md could be updated and that some of those things would have saved me some time.
The things that clearly need some updates are:
* The person managing the release doesn't need an OBS account, as we don't build packages as part of 2.x releases;
* The person should have hub setup to use app tokens rather than the user password
* This one hit me quite hard and made me spend a good amount of mine and @jcvenegas's time to understand the issue, thankfully @jcvenegas pointed me to the right direction!
* The release bump section could be simplified to only mention the script, rather than having different …
=> Update the information about the release process

src/runtime/cli/main_test.go
Change the "moo FAILURE" message shown in a couple of the unit tests to
"moo message".  This means that searching for unrelated failures in the
test output by looking for "FAIL" won't show these messages as false
positives any more.
=> runtime/tests: Change "moo FAILURE" message

src/runtime/cli/kata-env_s390x_test.go
`getExpectedHostDetails` did not offload any work to
`genericGetExpectedHostDetails` on s390x. By using that function, much
redundant code can be saved. This also resolves 2 issues with the
previous version:
- The number of CPUs was not calculated.
- vcUtils.SupportsVsocks() still used the Kata v1 signature.
Fixes: #1564
backport required
=> cli: Use genericGetExpectedHostDetails on s390x

src/agent/rustjail/src/cgroups/notifier.rs
register_memory_event_v2() includes a closure spawned as an async task
with tokio.  At the end of that closure, there's a test for a closed fd
exiting if so.  But this is right at the end of the closure when it was
about to exit anyway, so this does nothing.
This code was originally an explicit thread, converted to a tokio task
by 332fa4c "agent: switch to async runtime".  It looks like there was an
error during conversion, where this logic was accidentally moved out of the
while loop above, where it makes a lot more sense.
Put it back into the loop.
fixes #1702
=> agent/rustjail: Fix accidental damage from tokio conversion

src/runtime/virtcontainers/kata_agent.go
With tracing enabled, grpc health check generates a large number of
spans which creates too much data for tasks running longer than a few
minutes. To solve this, remove span creation from kata agent check() and
sendReq() where the majority of the spans come from. Leave contexts in
functions for subsequent calls that create spans.
Fixes #1395
=> runtime: Disable trace for healthcheck

src/agent/src/device.rs, src/runtime/virtcontainers/clh.go, src/runtime/virtcontainers/clh_test.go, src/runtime/virtcontainers/kata_agent.go, src/runtime/virtcontainers/kata_agent_test.go
Currently runtime and agent special case virtio-blk devices under clh, ostensibly because the PCI address information is not available in that case.  In fact, it *is* available from clh (with a little tweaking), since the VmAddDiskPut API returns a PciDeviceInfo.
So, remove this special case.
fixes #1431
The initial draft is based on unmerged #1430, hence the wip label for now.
=> block: Generate PCI path for virtio-blk devices on clh

src/runtime/go.mod, src/runtime/go.sum, src/runtime/vendor/github.com/kata-containers/govmm/qemu/qemu.go, src/runtime/vendor/modules.txt, src/runtime/virtcontainers/qemu.go, src/runtime/virtcontainers/qemu_arch_base.go, src/runtime/virtcontainers/qemu_arch_base_test.go, src/runtime/virtcontainers/qemu_s390x.go, src/runtime/virtcontainers/qemu_s390x_test.go
- Use updated GoVMM following the merge of https://github.com/kata-containers/govmm/pull/161 and allow `appendVhostUserDevice` on s390x.
- One thing I'm not so sure about is checking for virtio-fs support. It was only added to s390x in QEMU 5.2.0, which is officially to be used with Kata since the merge of #1349, but which generally hasn't landed in distro releases yet.
We could just assume that a recent enough QEMU is used because Kata's tests/CI use it. If we do this and try virtio-fs on a non-virtio-fs QEMU, the user would receive a message like:
```
ctr: failed to launch qemu: exit status 1, error messages from qemu log: qemu-system-s390x: -device vhost-user-fs-ccw,chardev=char-50b9c9fc5d2491f7,tag=kataShared: 'vhost-user-fs-ccw' is not a valid device model name
```
even though this …
=> Enable virtio-fs on s390x

src/runtime/virtcontainers/acrn.go, src/runtime/virtcontainers/clh.go, src/runtime/virtcontainers/fc.go, src/runtime/virtcontainers/hypervisor.go, src/runtime/virtcontainers/mock_hypervisor.go, src/runtime/virtcontainers/mock_hypervisor_test.go, src/runtime/virtcontainers/qemu.go, src/runtime/virtcontainers/sandbox.go, src/runtime/virtcontainers/utils/utils.go, src/runtime/virtcontainers/utils/utils_test.go, src/runtime/virtcontainers/vm.go
Fixed logic used to handle static agent tracing.
For a standard (untraced) hypervisor shutdown, the runtime kills the VM
process once the workload has finished. But if static agent tracing is
enabled, the agent running inside the VM is responsible for the
shutdown. The existing code handled this scenario but did not wait for
the hypervisor process to end. The outcome of this being that the
console watcher thread was killed too early.
Although not a problem for an untraced system, if static agent tracing
was enabled, the logs from the hypervisor would be truncated, missing the
crucial final stages of the agents shutdown sequence.
The fix necessitated adding a new parameter to the `stopSandbox()` API,
which if true requests the runtime hypervisor logic simply to wait for
the hypervisor …
=> Improve agent shutdown handling

src/agent/rustjail/src/container.rs, src/agent/rustjail/src/process.rs, src/agent/src/rpc.rs, src/agent/src/signal.rs
The situation is not a IPC scene, pipe(2) is too heavy.
We have `tokio::sync::watch::channel` after tokio has been introduced.
The channel has better performance and easy to use.
=> agent: use channel instead of pipe(2) to send exit signal of process

src/agent/oci/src/lib.rs, src/agent/rustjail/src/cgroups/fs/mod.rs, src/agent/rustjail/src/cgroups/notifier.rs, src/agent/rustjail/src/container.rs, src/agent/rustjail/src/lib.rs, src/agent/rustjail/src/validator.rs, src/agent/src/config.rs, src/agent/src/device.rs, src/agent/src/namespace.rs, src/agent/src/netlink.rs, src/agent/src/uevent.rs
It appears that a number of new lints have been added into recent clippy versions (I'm using 1.51) which trigger on the current Kata agent code.  For some reason these aren't showing up in the CI, possibly because it's using an older Rust snapshot.  The current clippy warnings thus make it difficult to locally check for new clippy warnings which *will* cause CI failures.
So, this patchset removes a number of those warnings.
=> Assorted clippy fixes for Rust agent

tools/packaging/qemu/patches/5.2.x/0009-monitor-Fix-assertion-failure-on-shutdown.patch
Occassional coredumps and OOMs observed on shutdown path due to improper
BH handling during aio cleanup in QEMU. Thankfully this has been fixed
in upstream already -- let's carry this patch.
Fixes: #1717
=> qemu: Fix assertion failure on shutdown

src/agent/src/mount.rs, src/runtime/virtcontainers/kata_agent.go, src/runtime/virtcontainers/kata_agent_test.go
For k8s emptyDir volume, a specific fsGroup would
be set for it, thus guest should get this fsGroup
from runtime and set it properly on the EphemeralStorage
volume in guest.
Fixes: #1580
=> fix the issue of missing set fsGroup for EphemeralStorage

src/runtime/containerd-shim-v2/stream.go
Do not close the tty as part of the stdout redirection routine.
The close is already happening a couple lines below, after all routines
have finished.
Fixes #1713
=> runtime: Fix stdout/stderr output from container being truncated

src/runtime/virtcontainers/pkg/oci/utils.go, src/runtime/virtcontainers/pkg/oci/utils_test.go
Users can specify extra arguments for virtiofsd in pod spec using the
io.katacontainers.config.hypervisor.virtio_fs_extra_args annontation.
However, this annotation was ignored so far by the runtime.  This commit
fixes the issue by processing the annotation value (if present) and
translating it to the corresponding hypervisor configuration item.
Fixes #1523
Signed-off-by: Pavel Mores <pmores@redhat.com>
=> add io.katacontainers.config.hypervisor.virtio_fs_extra_args handling

src/runtime/cli/kata-env_test.go, src/runtime/cli/main.go, src/runtime/containerd-shim-v2/create.go, src/runtime/pkg/katautils/config.go, src/runtime/pkg/katautils/config_test.go
Parametr builtIn is not used in function updateRuntimeConfigAgent,
delete it from updateRuntimeConfigAgent and LoadConfiguration
function signature.
Fixes: #1731
=> runtime: delete not used function parameter builtIn

src/runtime/virtcontainers/pkg/oci/utils.go, src/runtime/virtcontainers/pkg/oci/utils_test.go
This is a backport from main to stable-2.0 of PR #1739.  The original
commit message follows:
Users can specify extra arguments for virtiofsd in a pod spec using the
io.katacontainers.config.hypervisor.virtio_fs_extra_args annontation.
However, this annotation was ignored so far by the runtime.  This commit
fixes the issue by processing the annotation value (if present) and
translating it to the corresponding hypervisor configuration item.
Fixes #1523
Signed-off-by: Pavel Mores <pmores@redhat.com>
=> runtime: handle io.katacontainers.config.hypervisor.virtio_fs_extra_args

src/runtime/virtcontainers/qemu.go
"negotiate" was misspelled on qemu's qmp error message.
Fixes #1764
=> runtime/virtcontainers: Fix typo on qmp error msg

src/runtime/Makefile
In commit 966bd57 for PR #902, the makefile was changed to automate
the replacement of user variables. However, one variable was treated
specially in the original `sed` replacements, namely `RUNTIME_NAME`
which was replaced by `$(TARGET)`.
This commit adds the `RUNTIME_NAME` variable to the makefile in order
to ensure that the replacement works correctly.
Fixes: #993
Fixes: #1164
(cherry-picked from 96a4ed7d709d1eef31b2421f5a88d8f500583ea0)
=> Makefile: Replace @RUNTIME_NAME@ with the target in generated files

docs/Limitations.md
Subpaths are not supported at the moment. Document that fact.
Fixes: #1728
Signed-off-by: Christophe de Dinechin <christophe@dinechin.org>
=> docs: Document limitation regarding subpaths

src/runtime/virtcontainers/qemu.go
If the QEMU VMM fails to launch, we currently fail to kill virtiofsd,
resulting in leftover processes running on the host. Let's make sure we
kill these, and explicitly cleanup the virtiofs socket on the
filesystem.
Ideally we'll migrate QEMU to utilize the same virtiofsd interface that
CLH uses, but let's fix this bug as a first step.
Fixes: #1755
=> qemu: kill virtiofsd if failure to start VMM

src/runtime/virtcontainers/pkg/cloud-hypervisor/client/client.go
This fixes a dropped `err` variable in `runtime/virtcontainers/pkg/cloud-hypervisor/client` as reported in  https://github.com/kata-containers/community/issues/212
Signed-off-by: Lars Lehtonen <lars.lehtonen@gmail.com>
=> runtime: fix dropped error

src/runtime/virtcontainers/clh.go, src/runtime/virtcontainers/clh_test.go
If apiSocketPath failed, should return the error, but not nil
Fixes: #1724
=> clh: return error if apiSocketPath failed

src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/NetConfig.md, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_net_config.go, src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml, versions.yaml
Quotes from the cloud-hypervisor release v15.0:
This release is the first in a new version numbering scheme to represent that
we believe Cloud Hypervisor is maturing and entering a period of stability.
With this new release we are beginning our new stability guarantees.
Other highlights from the latest release include: 
1. Network device rate limiting; 
2. Support for runtime control of `virtio-net` guest offload;
3. `--api-socket` supports file descriptor parameter; 
4. Bug fixes on `virtio-pmem`, PCI BARs alignment, `virtio-net`, etc.; 
5. Deprecation of the "LinuxBoot" protocol for ELF and bzImage in the coming release.
Details can be found: https://github.com/cloud-hypervisor/cloud-hypervisor/releases/tag/v15.0 …
=> versions: Upgrade to cloud-hypervisor v15.0

src/runtime/go.mod, src/runtime/go.sum, src/runtime/vendor/github.com/kata-containers/govmm/qemu/qemu.go, src/runtime/vendor/github.com/kata-containers/govmm/qemu/qmp.go, src/runtime/vendor/modules.txt, src/runtime/virtcontainers/qemu.go, src/runtime/virtcontainers/qemu_arch_base.go, src/runtime/virtcontainers/qemu_arch_base_test.go, src/runtime/virtcontainers/qemu_s390x.go, src/runtime/virtcontainers/qemu_s390x_test.go
- Revert implementation from #1599 as it needs to be overhauled completely
- Give `vhost-user-fs-ccw` devices a CCW device number so it's possible to have devices after a `vhost-user-fs-ccw` device has been added
- Only allow `vhost-user-fs-ccw`, not `vhost-user-`{`blk`,`scsi`,`net`}`-ccw` like #1599 did 
Depends-on: https://github.com/kata-containers/govmm/pull/171. Do not merge as is! Needs update once that is merged.
Fixes: #1753
No backport required.
@fidencio ideally this would still make it into the release, since virtio-fs on s390x is a bit broken as is. However, I know that this comes very late, and would fully understand not putting it into release any more.
=> virtcontainers: Fix virtio-fs on s390x

tools/packaging/kernel/build-kernel.sh
Build kernel shell setup with -f, don't find patches directory path,
because patches_path is none, so fix this error.
Fixes: #1768
=> fix build kernel shell error when setup with `-f`

versions.yaml
In this PR we're updating the versions of the following components:
* kubernetes: 1.18.9-00 -> 1.21.0-00
* critools: 1.18.0 -> 1.21.0
* cri-o: v1.18.4-4-g6dee3891e -> v1.21.0
While touching th file, we're also remove the entries for:
* docker, not used since https://github.com/kata-containers/tests/pull/3272
* openshift, not used in 2.x at all, since kata-containers was added to the OpenShift CI (thanks, @wainersm!)
* And because of this, CRI-O meta dependencies can be dropped as well.
This PR is a WIP as we're still depending on:
* cri-o v1.21.0 to be released (we're pointing to v1.20.2, which is the latest release), which should happen Today / Tomorrow.
* a PR updating things on the `kata-containers/tests` side.
=> Update dependencies versions

tools/packaging/kata-deploy/scripts/kata-deploy.sh
By using drop-in file it simplifies the deployment and maintenance of
the CRI-O configurations by a lot, and all versions of CRI-O that should
be used together with the currently supported versions of kubenertes
support the drop-in configuration file.
While at here, let's also rely on CRI-O default's values for `manage_ns_lifecycle` (previously known as manage_network_ns_lifecycle), as it has its default value as
`true` for all CRI-O versions that should be used with the kubernetes versions that
are still supported / didn't reach their EOL.
Fixes #1781
=> Update kata-deploy to use CRI-O drop-in files

src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/NetConfig.md, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_net_config.go, src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml, versions.yaml
Quotes from the cloud-hypervisor release v15.0:
This release is the first in a new version numbering scheme to represent that
we believe Cloud Hypervisor is maturing and entering a period of stability.
With this new release we are beginning our new stability guarantees.
Other highlights from the latest release include: 1) Network device rate
limiting; 2) Support for runtime control of `virtio-net` guest offload;
3) `--api-socket` supports file descriptor parameter; 4) Bug fixes on
`virtio-pmem`, PCI BARs alignment, `virtio-net`, etc.; 5) Deprecation of
the "LinuxBoot" protocol for ELF and bzImage in the coming release.
Details can be found: https://github.com/cloud-hypervisor/cloud-hypervisor/releases/tag/v15.0
generated …
=> [backport] versions: Upgrade to cloud-hypervisor v15.0

src/runtime/containerd-shim-v2/start.go
This commint include two types of fixes for comments
in src/runtime/containerd-shim-v2/start.go.
- Out of date comment that is inconsistent with code.
- Comments without heading spaces.
Fixes: #1750
=> runtime: fix some comments

src/runtime/containerd-shim-v2/wait.go
s.ctx should be used for checking cancellation, and the
local ctx is used for tracing.
Fixes: #1804
=> runtime: use s.ctx instead ctx for checking cancellation

src/agent/kata-agent.service.in
Some applications may fail if NOFILE limit is set to unlimited.
Although in some environments this value is explicitly overridden,
lets set it to a more sane value in case it doesn't.
This value (2^20) has been chosen as it seems to be commonly used (e.g. crio daemon) and also:
https://stackoverflow.com/questions/1212925/on-linux-set-maximum-open-files-to-unlimited-possible/1213069#1213069
Fixes: https://github.com/kata-containers/kata-containers/issues/1715
=> Set fixed NOFILE limit value for kata-agent

src/runtime/virtcontainers/qemu.go
qemu.go: qemu: setupVirtioMem: let sizeMB be multiple of 2Mib to fix the issue.
qemu.go: qemu: resizeMemory: This commit change sizeByte from uint32 to uint64 to fix overflow issue.
Fixes: #1796
=> Fix issue of virtio-mem

docs/how-to/how-to-set-sandbox-config-kata.md, src/runtime/containerd-shim-v2/shim_management.go
Now enabling enable_pprof for individual pods is supported,
but not documented.
This commit will add per-Pod Kata configurations for `enable_pprof`
in file `docs/how-to/how-to-set-sandbox-config-kata.md`
Fixes: #1744
=> docs: add per-Pod Kata configurations for `enable_pprof`

src/runtime/virtcontainers/qemu.go
qemu.go: qemu: setupVirtioMem: let sizeMB be multiple of 2Mib to fix the issue.
qemu.go: qemu: resizeMemory: This commit change sizeByte from uint32 to uint64 to fix overflow issue.
Fixes: #1796
Porting from https://github.com/kata-containers/kata-containers/pull/1800
=> [2.1.0] Fix issue of virtio-mem

src/runtime/cli/kata-check.go, src/runtime/cli/kata-env.go, src/runtime/cli/kata-exec.go, src/runtime/cli/main.go, src/runtime/cli/version.go
There are no pod/container operations in kata-runtime binary,
tracing in this package is meaningless.
Fixes: #1748
=> cli: delete tracing code for kata-runtime binary

src/runtime/containerd-shim-v2/wait.go
s.ctx should be used for checking cancellation, and the
local ctx is used for tracing.
Fixes: #1804
Backport of https://github.com/kata-containers/kata-containers/pull/1805
=> [backport]runtime: use s.ctx instead ctx for checking cancellation

tools/osbuilder/rootfs-builder/alpine/Dockerfile.in, versions.yaml
We are using an older version of alpine, so upgrade to latest 3.13.5.
Fixes #1817
=> osbuilder: Upgrade alpine version to 3.13.5

ci/install_yq.sh, docs/how-to/how-to-set-sandbox-config-kata.md, src/agent/kata-agent.service.in, src/runtime/cli/kata-check.go, src/runtime/cli/kata-env.go, src/runtime/cli/kata-exec.go, src/runtime/cli/main.go, src/runtime/cli/version.go, src/runtime/containerd-shim-v2/shim_management.go, src/runtime/pkg/kata-monitor/metrics.go, src/runtime/pkg/kata-monitor/monitor.go, src/runtime/pkg/kata-monitor/shim_client.go
This PR contains the first round of backports we need for the stable-2.1 branch and that would be really beneficial to have those merged before the 2.1.0 release.
Those are:
https://github.com/kata-containers/kata-containers/pulls?q=is%3Apr+is%3Aclosed+label%3Amissing-backport-to-stable-2.1.0
Plus https://github.com/kata-containers/kata-containers/pull/1749, which was pulled in order to facilitate the backport of https://github.com/kata-containers/kata-containers/pull/1811/commits.
=> stable-2.1: First round of backports

src/runtime/cli/config/configuration-acrn.toml.in, src/runtime/cli/config/configuration-clh.toml.in, src/runtime/cli/config/configuration-fc.toml.in, src/runtime/cli/config/configuration-qemu.toml.in, src/runtime/pkg/katautils/config.go, src/runtime/virtcontainers/kata_agent.go, src/runtime/virtcontainers/pkg/agent/protocols/client/client.go
allow to set dialing timeout in configuration.toml
default is 30s
Fixes: #1789
=> runtime: make dialing timeout configurable

tools/packaging/kata-deploy/kata-cleanup/overlays/k3s/kustomization.yaml, tools/packaging/kata-deploy/kata-cleanup/overlays/k3s/mount_k3s_conf.yaml
kata-deploy cleanup expects to find containerd configuration
in /etc/containerd/config.toml. In case of k3s mount the k3s
containerd config as a volume.
Original PR #1802
Fixes #1801
Signed-off-by: Orestis Lagkas Nikolos <olagkasn@nubificus.co.uk>
=> packaging/kata-cleanup: add k3s containerd volume

docs/Limitations.md, tools/packaging/ccloudvm/README.md
There is a bug in the CI script checking spelling that causes it
to skip any text that follows a horizontal ruler.
(https://github.com/kata-containers/tests/issues/3448)
Solution: replace one horizontal ruler marker with another that
does not trip the spell-checking script.
Fixes: #1793
=> docs: Remove horizontal ruler markers that disable spell checks

docs/Release-Process.md
When we create a new stable branch, it is good practice to ensure that the test
repository points to that stable branch, to make sure that it is not impacted by
later changes to the CI made on the stable branch.
Fixes: #1823
Signed-off-by: Christophe de Dinechin <christophe@dinechin.org>
=> docs: Document test repository changes when creating a stable branch

src/agent/Cargo.toml, src/agent/rustjail/Cargo.toml
The tempfile is only used by tests.
Fixes: #1827
=> agent: move the dependency tempfile to the dev-dependencies section

src/agent/rustjail/src/container.rs, src/agent/src/signal.rs
=> agent: avoid reaping the exit signal of execute_hook in the reaper

tools/osbuilder/image-builder/image_builder.sh
There is inconformity between qemu and kernel of memory alignment
check in memory hotplug. Both of qemu and kernel will do the start
address alignment check check in memory hotplug. But it's 2M in qemu
while 128M in kernel. It leads to an issue when memory hotplug.
Currently, the kata image is a nvdimm device, which will plug into the VM as
a dimm. If another dimm is pluged, it will reside on top of that nvdimm.
So, the start address of the second dimm may not pass the alginment
check in kernel if the nvdimm size doesn't align with 128M.
There are 3 ways to address this issue I think:
1. fix the alignment size in kernel according to qemu. I think people
in linux kernel community will not accept it.
2. do alignment check in qemu and force the start address of hotplug
in alignment with …
=> image_build: align image size to 128M for arm64

src/agent/rustjail/src/container.rs, src/agent/src/signal.rs
=> stable-2.1 | agent: avoid reaping the exit signal of execute_hook in the reaper

tools/osbuilder/image-builder/image_builder.sh
There is an inconformity between qemu and kernel of memory alignment
check in memory hotplug. Both of qemu and kernel will do the start
address alignment check in memory hotplug. But it's 2M in qemu
while 128M in kernel. It leads to an issue when memory hotplug.
Currently, the kata image is a nvdimm device, which will plug into the VM as
a dimm. If another dimm is pluged, it will reside on top of that nvdimm.
So, the start address of the second dimm may not pass the alginment
check in kernel if the nvdimm size doesn't align with 128M.
There are 3 ways to address this issue I think:
1. fix the alignment size in kernel according to qemu. I think people
in linux kernel community will not accept it.
2. do alignment check in qemu and force the start address of hotplug
in alignment with 128M, …
=> back port: image_build: align image size to 128M for arm64

docs/Developer-Guide.md
Before 2.1-alpha1, user still need starting kata-monitor
to connect to debug console.
Fixes: #1842
=> docs: add note for connecting debug console for old versions

src/runtime/virtcontainers/sandbox.go
When reading the cleanup code path, we have several problems:
1. cgroups cleanup should ignore non-existing directories
2. sandbox delete should always succeeds after verifying sandbox states. otherwise we end up leaving orphan containers and inconsistent container states
=> runtime: improve sandbox cleanup logic

src/agent/rustjail/src/mount.rs
Since the propagation flags couldn't be combinted with the
standard mount flags, and they should be used with the remount,
thus it's better to split them from the standard mount flags.
Fixes: #1699
=> rustjail: separated the propagation flags from mount flags

docs/Limitations.md, src/agent/rustjail/src/mount.rs, src/runtime/virtcontainers/sandbox.go, tools/packaging/ccloudvm/README.md
Folks, this is the last round of backports before getting 2.1.0 out, and it includes:
* Two backports related to our spell checker, and I think it's better to backport then now than when we randomly hit some spell checker issue (as happened in the past).
42425456e7dd885360945ed4d508397d9a00d102 docs: Remove horizontal ruler markers that disable spell checks
5fdf617e7fe2cb81c1b274b8bc8f2ff96be3566c docs: Fix spell-check errors found after new text is discovered
* A sandbox cleanup issue, that avoids leaving behind orphan containers
35151f178684e799a1e9885dff71fbe28dce712c runtime: sandbox delete should succeed after verifying sandbox state
* An agent fix separating the propagation and mount flags on the rustjail code
e5fe572f51b8a9316c0c4a84ce90cbfc359f5db6 rustjail: separated the …
=> stable-2.1 | The last round of backports before releasing 2.1.0

.github/workflows/require-pr-porting-labels.yaml
This PR modifies that require porting labels only run at main.
Fixes #1857
=> github: Run require porting labels only at main

.github/workflows/require-pr-porting-labels.yaml
When we are creating a PR in stable-2.1 we do not need to run
the github action of porting labels as we are doing backports or
new releases in stable-2.1 and it is unnecessary to put labels
like no-backport-needed or no-forwardport-needed, etc.
Fixes #1847
=> github: Do not run require porting labels on stable-2.1

docs/how-to/README.md, docs/how-to/how-to-hotplug-memory-arm64.md
After some enablement work, memory hotplug can be used on arm64.
Here we offer a document to instruct user to enable it.
Fixes: #1854
@fidencio  @GabyCT
=> docs: Add document for memory hotplug on arm64

src/agent/Cargo.lock, src/agent/Cargo.toml, src/agent/rustjail/Cargo.toml, src/agent/rustjail/src/container.rs, src/agent/rustjail/src/lib.rs, src/agent/src/main.rs, src/agent/src/signal.rs, tools/agent-ctl/Cargo.lock
While evaluating the possibility of having kata-agent statically linked
to the GNU libc, we've ended upn facing some issues with prctl.
When debugging the issues, we figured out that the crate hasn't been
maintained since 2015 and that the capctl one is a good 1:1 replacement
for what we need.
And as we're already at it, let's also have all the dependencies updated.
=> agent: Stop relying in the unmaintained prctl crate

docs/Developer-Guide.md
Update the developer guide to correct the
command that adds a customer kata-agent to the rootfs image
putting it in /usr/bin/kata-agent rather than /bin/kata-agent
Fixes #1904
=> docs: Update add customer agent command

src/runtime/virtcontainers/kata_agent.go, src/runtime/virtcontainers/kata_agent_test.go, src/runtime/virtcontainers/persist.go, src/runtime/virtcontainers/persist/api/config.go
If for any reason there's an error when trying to setup the sandbox
bindmounts, make sure we roll back any mounts already created when
setting up the sandbox.
Without this, we'd leave a leftover shared directory mount and potentially
sandbox-bindmounts leftover.
Similarly, let's make sure we persist sandbox bindmounts, so we can appropriately cleanup as part of contained-shim-kata-v2 cleanup in the event that the shim dies.
=> Sandbox bindmount cleanup

.github/workflows/snap-release.yaml, docs/install/snap-installation-guide.md
kata 1.x has been deprecated, now kata 2.x can be released through
the stable channel
fixes #1909
=> workflows: release kata 2.x snap through the stable channel

.github/workflows/snap-release.yaml, docs/install/snap-installation-guide.md
kata 1.x has been deprecated, now kata 2.x can be released through
the stable channel
fixes #1909
=> [backport-2.1] workflows: release kata 2.x snap through the stable channel

tools/packaging/qemu/patches/5.1.x/0013-qemu-align-before-memory-hotplug-on-arm64.patch
When hotplug memory on arm64 in kata, kernel will shout:
[ 0.396551] Block size [0x40000000] unaligned hotplug range: start 0xc8000000, size 0x40000000
[ 0.396556] acpi PNP0C80:01: add_memory failed
[ 0.396834] acpi PNP0C80:01: acpi_memory_enable_device() error
[ 0.396948] acpi PNP0C80:01: Enumeration failure
It means that kernel will check if the memory range to be hotplugged
align with 1G before plug the memory. So we should twist the qemu to
make sure the memory range align with 1G to pass the kernel check.
Fixes: #1841
Signed-off-by: Yuanzhe Liu <yuanzheliu09@gmail.com>
=> qemu: align before memory hotplug on arm64

docs/Developer-Guide.md
Update the developer guide to add instructions of how to get the
correct version of the QEMU source and sets your_qemu_directory
variable, so that follow on steps are easier for a new joiner to the
community to understand
Fixed #1907
=> docs: Add instructions for getting QEMU source

src/agent/rustjail/src/container.rs, src/agent/src/main.rs, src/agent/src/random.rs, src/agent/src/rpc.rs
We should remove underscore(`_`) prefixed variables when `?` operator is used.
Fixes: #1903
=> agent: Remove unnecessary underscore(_) variables

src/agent/rustjail/src/container.rs
When starting a container and dropping all capabilities, the init child process has no permission to read the exec.fifo file because the parent set the file mode 0o622. So change the exec.fifo file mode to 0o644.
fixes #1913
Signed-off-by: quanweiZhou <quanweiZhou@linux.alibaba.com>
=> agent: fix start container failed when dropping all capabilities

docs/how-to/run-kata-with-k8s.md
The `--skip-preflight-checks` flag has been deprecated in the Kubernetes v1.9 and removed from Kubernetes v1.12.
We should use `--ignore-preflight-errors=all` flag instead of `--skip-preflight-checks`.
Fixes: #1919
=> docs: Use --ignore-preflight-errors=all flag

src/agent/rustjail/src/container.rs, src/runtime/virtcontainers/kata_agent.go, src/runtime/virtcontainers/kata_agent_test.go, src/runtime/virtcontainers/persist.go, src/runtime/virtcontainers/persist/api/config.go, tools/packaging/qemu/patches/5.1.x/0013-qemu-align-before-memory-hotplug-on-arm64.patch
This includes backports of the following PRs:
* https://github.com/kata-containers/kata-containers/pull/1897
* sandbox: Cleanup if failure to setup sandbox-bindmount occurs 089a7484e17c90bf0da7df190f58276e144548df
* sandbox-bindmount: persist mount information c51891fee791db97cef9f883238a2b246b08f300
* https://github.com/kata-containers/kata-containers/pull/1888
* qemu: align before memory hotplug on arm64 536634e909c1f9b31f042b569e2ca16fdfb803a6
* https://github.com/kata-containers/kata-containers/pull/1915
*  agent: fix start container failed when dropping all capabilities 7874ab33d499f86d8e7cacf3339f9715b4f84d13
=> Weekly stable 2.1 backports may 24th

src/runtime/cli/kata-check.go
In kata-runtime check sub-command, checks cgroups and SandboxCgroupOnly
to show message if the SandboxCgroupOnly is not set to true
and cgroup v2 is used.
Fixes: #1927
=> runtime: and cgroup and SandboxCgroupOnly check for check sub-command

src/runtime/virtcontainers/virtiofsd.go
This commit will fix two problems:
- Virtiofsd process ID returned to the caller will always be 0,
the pid var is never being assigned a value.
- Socket listen fd may leak in case of failure of starting virtiofsd process.
This is a port of https://github.com/kata-containers/kata-containers/commit/be9ca0d58b2b777beda02f59e443c1dc67d0b5f7
Fixes: #1931
=> virtiofsd: Fix file descriptors leak and return correct PID

src/runtime/cli/kata-check.go
This is a backport of #1934 
In kata-runtime check sub-command, checks cgroups and SandboxCgroupOnly
to show message if the SandboxCgroupOnly is not set to true
and cgroup v2 is used.
Fixes: #1927
=> [backport]runtime: and cgroup and SandboxCgroupOnly check for check sub-command

src/runtime/virtcontainers/clh.go, src/runtime/virtcontainers/qemu.go, src/runtime/virtcontainers/qemu_test.go, src/runtime/virtcontainers/virtiofsd.go, src/runtime/virtcontainers/virtiofsd_test.go
CloudHypervisor is using virtiofsd.go to manage virtiofsd process,
but qemu has its code in qemu.go. This commit let qemu to re-use
code in virtiofsd.go to reduce code and improve maintenanceability.
Fixes: #1933
=> virtiofsd: refactor qemu.go to use code in virtiofsd.go

src/runtime/containerd-shim-v2/service.go, src/runtime/pkg/katautils/create.go, src/runtime/pkg/katautils/hook.go, src/runtime/pkg/katautils/tracing.go, src/runtime/virtcontainers/acrn.go, src/runtime/virtcontainers/api.go, src/runtime/virtcontainers/clh.go, src/runtime/virtcontainers/container.go, src/runtime/virtcontainers/factory/factory.go, src/runtime/virtcontainers/fc.go, src/runtime/virtcontainers/kata_agent.go, src/runtime/virtcontainers/network.go, src/runtime/virtcontainers/qemu.go, src/runtime/virtcontainers/sandbox.go, src/runtime/virtcontainers/virtiofsd.go
Span attributes (tags) are not consistent in runtime tracing, so
designate and use core attributes such source, package, subsystem, and
type as span metadata for more understandable output.
Fixes #1852
=> tracing: Make runtime span attributes more consistent

src/runtime/virtcontainers/persist/api/sandbox.go, src/runtime/virtcontainers/qemu.go, src/runtime/virtcontainers/sandbox.go
Some of them are no longer valid. We can just remove them.
=> cleanup TODOs in runtime

src/agent/rustjail/src/cgroups/fs/mod.rs, src/agent/src/main.rs, src/runtime/virtcontainers/virtiofsd.go
This week we're backporting:
~727bfc4556451433468cb5ede72f8b2df196b3b8 runtime: and cgroup and SandboxCgroupOnly check for check sub-command (#1934)~ Please, see: #1940
009a200151c24af553577665484531fad2b65277 virtiofsd: Fix file descriptors leak and return correct PID (#1932)
ad7658e16ee99613612f8fc9dfc8c58708ba32fa agent: re-enable the standard SIGPIPE behavior (#1939)
26beb7a6a866aba6980be3db0a61fb12aad26520 cgroup: fix the issue of set mem.limit and mem.swap (#1918)
=> [stable-2.1] Weekly backports to stable-2.1 branch, May 31st 2021

src/agent/Cargo.lock, src/agent/Cargo.toml
Fixes: #1950
The further information: rust-vsock/vsock-rs#15
=> agent: Upgrade tokio-vsock to fix fd leak of vsock socket

versions.yaml
The reason for doing such is to (try to) avoid random crashes we've been
facing as part of our CI, such as the one reported as part of
https://github.com/kata-containers/tests/issues/3473
Fixes: #1850
=> versions: Update kubernetes to 1.21.1

src/runtime/virtcontainers/acrn.go, src/runtime/virtcontainers/clh.go, src/runtime/virtcontainers/fc.go, src/runtime/virtcontainers/hypervisor.go, src/runtime/virtcontainers/mock_hypervisor.go, src/runtime/virtcontainers/qemu.go, src/runtime/virtcontainers/sandbox_metrics.go
Export proc stats for virtiofsd.
This commit only adds for hypervisors that have support for it.
- qemu
- cloud-hypervisor
Fixes: #1926
=> metrics: Add virtiofsd exporter

src/agent/Cargo.lock, src/agent/Cargo.toml
See also: little-dude/netlink#165
Fixes: #1952
Because the author of netlink has no time to maintain the crate
(https://github.com/little-dude/netlink/issues/161), so we
need to switch the dependency to github temporarily.
=> agent: Fix fd leak caused by netlink

src/runtime/pkg/katautils/create.go, src/runtime/virtcontainers/acrn.go, src/runtime/virtcontainers/clh.go, src/runtime/virtcontainers/container.go, src/runtime/virtcontainers/fc.go, src/runtime/virtcontainers/network.go, src/runtime/virtcontainers/qemu.go, src/runtime/virtcontainers/sandbox.go
Add sandbox, container, and hypervisor IDs to trace spans. Note that some spans in sandbox.go are created with a trace() call from api.go. These spans have additional attributes set after span creation to overwrite the api attributes.
Add network model to spans. Trace spans erroneously set the network model to default in all cases. Add function to return network model string and use it to set attribute in spans.
Fixes #1878
=> Add sandbox and container ID to trace spans

docs/Release-Process.md
This PR updates the correct url for github actions as well as it
corrects a misspelling.
Fixes #1960
=> docs: Fix Release Process document

src/runtime/cli/main.go, src/runtime/virtcontainers/factory/template/template.go, src/runtime/virtcontainers/factory/template/template_test.go
backport for https://github.com/kata-containers/runtime/pull/2923
we can have the following case,
1. start kata container with factory feature, this need kata-runtime
config to enable factory and use initrd as base image.
2. start a kata container.
3. cd /root; cd /run/vc/vm/template dir, this will make
/run/vc/vm/template to be in used.
4. destroy vm template with kata-runtime factory destroy , and check
the template mountpoint.
we can see  the template mountpoints will add everytime we repeat the above steps .
[root@centos1 template]# mount |grep template
[root@centos1 template]# docker run -ti --rm  --runtime untrusted-runtime --net none busybox echo
[root@centos1 template]# cd /root; cd /run/vc/vm/template/
[root@centos1 template]# /kata/bin/kata-runtime factory destroy
vm factory …
=> factory: Use lazy unmount

versions.yaml
The reason for doing such is to (try to) avoid random crashes we've been
facing as part of our CI, such as the one reported as part of
https://github.com/kata-containers/tests/issues/3473
Fixes: #1850
(cherry picked from commit dbef2b29310eabef8d5d2ea6db7de78d08a6cdde)
Backport of #1851
=> stable-2.1 | versions: Update kubernetes to 1.21.1

tools/packaging/static-build/qemu/Dockerfile
In some distros (Ubuntu 18 and 20) it's not possible to clone meson
and QEMU dependencies from https://git.qemu.org due to problems with
its certificates, let's pull these dependencies from github before
building QEMU.
fixes #1965
=> tools/packaging: clone meson and dependencies before building QEMU

src/runtime/virtcontainers/bridgedmacvlan_endpoint.go, src/runtime/virtcontainers/ipvlan_endpoint.go, src/runtime/virtcontainers/kata_agent.go, src/runtime/virtcontainers/macvtap_endpoint.go, src/runtime/virtcontainers/network.go, src/runtime/virtcontainers/network_test.go, src/runtime/virtcontainers/physical_endpoint.go, src/runtime/virtcontainers/sandbox.go, src/runtime/virtcontainers/tap_endpoint.go, src/runtime/virtcontainers/tuntap_endpoint.go, src/runtime/virtcontainers/veth_endpoint.go, src/runtime/virtcontainers/vhostuser_endpoint.go
Add traces for all the endpoinnt types
and the main interface functions.
Record errors for some traces.
Fixes: #1956
=> runtime: add more traces for network

docs/Stable-Branch-Strategy.md
Last week I've proposed a new release cadence in our mailing list, and the email can be found [here](http://lists.katacontainers.io/pipermail/kata-dev/2021-May/001894.html).
As there was no push-back, now I'm trying to make it official by updated the related documents.
All in all, the only change in the proposal involves maintaining **only one** stable branch per active major release;
Please, @kata-containers/architecture-committee, I'd like to have an approval of each one of the active members before going ahead with this one.
Fixes: #1876 
EDITED: There was a light push back on having the releases out in a 8 weeks cadence rather than 12 weeks, so we can rediscuss this for the 2.3 release cycle, if needed. 2.2 release cycle will happen 12 weeks after 2.1 release cycle happened.
=> docs: Update the stable branch strategy to what was proposed in our ML

src/runtime/virtcontainers/hypervisor.go, src/runtime/virtcontainers/hypervisor_s390x.go, src/runtime/virtcontainers/hypervisor_s390x_test.go, src/runtime/virtcontainers/hypervisor_test.go, src/runtime/virtcontainers/qemu_amd64_test.go, src/runtime/virtcontainers/qemu_arch_base.go, src/runtime/virtcontainers/qemu_s390x.go, src/runtime/virtcontainers/qemu_s390x_test.go
Secure Execution is a confidential computing technology on s390x (IBM Z
& LinuxONE). Enable the correspondent virtualization technology in QEMU
(where it is referred to as "Protected Virtualization").
- Introduce enableProtection and appendProtectionDevice functions for
s390x.
- Introduce CheckCmdline to check for `prot_virt=1` being present on the
kernel command line.
- Introduce CPUFacilities for s390x to check for CPU support.
Also put consts in one block in `virtcontainers/qemu_s390x.go`.
Fixes: #1771
No backport required.
Depends-on: https://github.com/kata-containers/govmm/pull/173 and https://github.com/kata-containers/kata-containers/pull/1590 -- should be revendored/rebased accordingly, which would shrink this PR by those commits.
One question: This uses features that are …
=> virtcontainers: Add support for Secure Execution

src/runtime/virtcontainers/api.go
Remove the call to storeSandbox() at the end of createSandboxFromConfig(),
because this call chain createSandboxFromConfig -> s.createContainers has already calls storeSandbox().
This can improve the startup speed of the container, even just for a little. 
Fixes: #1980
Signed-off-by: Liang Zhou zhoul110@chinatelecom.cn
=> runtime: remove the call to storeSandbox at the end of createSandboxFromConfig 

tools/osbuilder/rootfs-builder/rootfs.sh, tools/osbuilder/scripts/lib.sh
- Merge codepath in lib.sh with ppc64le -- do not install CMake
- Like ppc64le, do not install musl rather than just not using it
Fixes: #1975
=> osbuilder: Streamline s390x CMake & musl handling

src/runtime/arch/s390x-options.mk, tools/osbuilder/rootfs-builder/rootfs.sh
For FFI to C in Go, `CC=gcc` is required on Fedora s390x (see https://github.com/kata-containers/osbuilder/issues/217).
- osbuilder: Remove CC=gcc for Fedora s390x (no longer required for Rust agent)
- runtime: Use CC=gcc on Fedora s390x (is still required and was never added for runtime)
Fixes: #1973
=> Update CC=gcc setting for Fedora s390x

tools/osbuilder/README.md
This PR removes the travis reference as we currently for kata 2.0,
travis is not being supported.
Fixes #1994
=> docs: Remove old travis reference

src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/client.go, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/NetConfig.md, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_net_config.go, src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml, versions.yaml
Highlights from the Cloud Hypervisor release v16.0: 
1. Improved live migration support;
2. Improved `vhost-user` support; 
3. ARM64 ACPI and UEFI support; 
4. Bug fixes.
Details can be found: https://github.com/cloud-hypervisor/cloud-hypervisor/releases/tag/v16.0
generated by `openapi-generator` [1-2]. As the API changes do not
impact usages in Kata, no additional changes in kata's runtime are
needed to work with the current version of cloud-hypervisor.
[1] https://github.com/OpenAPITools/openapi-generator
[2] https://github.com/kata-containers/kata-containers/blob/main/src/runtime/virtcontainers/pkg/cloud-hypervisor/README.md
Fixes: #1992
=> versions: Upgrade to cloud-hypervisor v16.0

src/runtime/containerd-shim-v2/stream_test.go
Following the fix for #1713, adding a unit test for ioCopy() that
verifies that data is properly copied from source to destination
whatever the order in which the pipes are closed.
Fixes #1831
=> test: Add a unit test for ioCopy()

src/runtime/README.md
This PR removes old links that were used in kata 1.x but not
longer valid for kata 2.x
Fixes #2019
=> docs: Update README for runtime documentation

docs/how-to/how-to-use-sysctls-with-kata.md
Currently in kata 2.x, we do not have docker support, this PR removes
the docker documentation with sysctls.
Fixes #2029
=> docs: Remove docker support with kata 2.x and sysctls

tools/packaging/kernel/README.md
This PR updates the proper url for breaking compatibility for
kata 2.x
Fixes #2031
=> docs: Update url for breaking compatibility

src/runtime/README.md
This PR removes old links that were used in kata 1.x but not
longer valid for kata 2.x
Fixes #2019
=> backport docs: Update README for runtime documentation

tools/osbuilder/rootfs-builder/rootfs.sh
Only show checkout faile message if AGENT_VERSION is set
and the checkout is failed.
Fixes: #1989
=> osbuilder: fix log message that is not error but seems like an error

src/agent/Cargo.lock
Fixes: #2035
Fixes: tokio-rs/tokio/#3809
=> Upgrade mio to v0.7.13 to fix epoll_fd leak problem

versions.yaml
This was fixed for tokio's version 
requirements for rust, see:
[supported-rust-versions](https://github.com/tokio-rs/tokio#supported-rust-versions)
Fixes: [#2008](https://github.com/kata-containers/kata-containers/issues/2008)
Signed-off-by: houfangdong <houfangdong@loongson.cn>
=> agent: Update rust version for tokio

src/runtime/containerd-shim-v2/stream_test.go
TestIoCopy unit test is failing randonly, skip it until we have a fix
fixes #2043
cc @littlejawa
=> containerd-shim-v2: Skip TestIoCopy unit test

src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/client.go, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/NetConfig.md, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_net_config.go, src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml, versions.yaml
Back-porting PR https://github.com/kata-containers/kata-containers/pull/1993.
Highlights from the Cloud Hypervisor release v16.0: 
1. Improved live migration support;
2. Improved `vhost-user` support; 
3. ARM64 ACPI and UEFI support; 
4. Bug fixes.
Details can be found: https://github.com/cloud-hypervisor/cloud-hypervisor/releases/tag/v16.0
generated by `openapi-generator` [1-2]. As the API changes do not
impact usages in Kata, no additional changes in kata's runtime are
needed to work with the current version of cloud-hypervisor.
[1] https://github.com/OpenAPITools/openapi-generator
[2] https://github.com/kata-containers/kata-containers/blob/main/src/runtime/virtcontainers/pkg/cloud-hypervisor/README.md
Fixes: #1992 …
=> [backport stable-2.1] versions: Upgrade to cloud-hypervisor v16.0

.github/workflows/snap-release.yaml, .github/workflows/snap.yaml
The snap/snapcraft.yaml set AGENT_VERSION to the current VERSION. The osbuilder script
will try to checkout the AGENT_VERSION tag. Let's ensure that all tags and branches
are fetched by the github's checkout action so the tag checkout does not fail.
=> ci: snap: Fetch history to all branches and tags

tools/packaging/qemu/patches/5.2.x/0010-Merge-remote-tracking-branch-remotes-ehabkost-gl-tag.patch
For QEMU 5.0.0 it is applied the patches/5.0.x/0002-memory-backend-file-nvdimm-support-read-only-files-a.patch
to fix an issue with the use of read-only files as backend memory of nvdimm devices. When Kata Containers bumped
to QEMU 5.2.0 that patch was left behind by mistake. In meanwhile a proper feature ("nvdimm: read-only file support")
was proposed and merged upstream (see https://mail.gnu.org/archive/html/qemu-devel/2021-01/msg00258.html).
This contain the backport of the commit 8360ebeb4f4a from QEMU master which should be applied on QEMU 5.2.0
so that feature is available to Kata Containers.
Fixes #2011
=> qemu: Add nvdimm read-only file support

src/runtime/virtcontainers/qemu_amd64.go
To print the correct value of kernel parameters, the log field
value should not be a function name. And for that qemuArchBase
doesn't contain debug flag, so the log contains debug/non-debug
parameters.
Fixes: #2048
=> runtime: using detail propertites instead of function name in log field

tools/packaging/qemu/patches/5.2.x/0010-Merge-remote-tracking-branch-remotes-ehabkost-gl-tag.patch
For QEMU 5.0.0 it is applied the patches/5.0.x/0002-memory-backend-file-nvdimm-support-read-only-files-a.patch
to fix an issue with the use of read-only files as backend memory of nvdimm devices. When Kata Containers bumped
to QEMU 5.2.0 that patch was left behind by mistake. In meanwhile a proper feature ("nvdimm: read-only file support")
was proposed and merged upstream (see https://mail.gnu.org/archive/html/qemu-devel/2021-01/msg00258.html).
This contain the backport of the commit 8360ebeb4f4a from QEMU master which should be applied on QEMU 5.2.0
so that feature is available to Kata Containers.
Fixes #2011
(cherry picked from commit 3f39df0d18ca93926190991689a6537e7bb67079)
=> stable-2.1 | qemu: Add nvdimm read-only file support

src/runtime/README.md
This PR updates the correct url for kata installation guides in kata 2.x
Fixes #2069
=> docs: Update url for installation guides

docs/install/minikube-installation-guide.md
This PR updates the proper url for kata-deploy scripts at the
minikube installation.
Fixes #2072
=> docs: Update kata-deploy urls for installation document

src/runtime/virtcontainers/sandbox.go
PMEM devices cannot be hot-removed from a running VM.
fixes #2018
=> runtime: do not hot-remove PMEM devices

docs/Developer-Guide.md
Fixed 3 errors which misused the bracket to substitute parameter for initrd-img creation at the developer guide.
Fixes: #2079
Signed-off-by: Sheng Zhao <zhaosheng.ste@bytedance.com>
=> docs: fix brackets usage error for developer guide

docs/Developer-Guide.md
- Adding missing `$` symbols to 3 references to `sandbox_id` variable
- Adding missing `'` symbol to QEMU-related `socat` command
Fixes #2075
Signed-off-by: Dave Hay <david_hay@uk.ibm.com>
=> docs: Fix typos in Developer Guide

src/runtime/containerd-shim-v2/service.go
Make sure we report the exit time for the container when we answer a "Status" request.
Fixes: #2096
=> runtime: report finish time in containers stats

docs/Developer-Guide.md
The Developer Guide instructs to install the agent from
`${ARCH}-unknown-linux-${LIBC}`, where `$LIBC` is set to `gnu` for
ppc64le (because Rust has no musl target there). The same is true for
s390x. Also set this for s390x.
Fixes: #2092
=> docs: Set LIBC=gnu for s390x too

src/runtime/containerd-shim-v2/service.go
Make sure we report the exit time for the container when we answer a "Status" request.
Fixes: #2098
=> stable-2.1 | runtime: report finish time in containers stats

tools/packaging/static-build/qemu/build-base-qemu.sh
Use Podman instead of Docker when $USE_PODMAN is set. This enables
running with Podman, e.g. to import images for CRI-O.
Fixes: #2067
=> packaging: Support Podman in QEMU build

tools/packaging/kernel/configs/fragments/s390/secure-execution.conf
Add `CONFIG_PROTECTED_VIRTUALIZATION_GUEST=y` to s390's guest kernel
config, which enables running with a secure image (as generated by
s390-tools' `genprotimg`).
Fixes: #2106
SEV uses the `-x` flag for enabling a confidential guest kernel build.
However, because enabling `CONFIG_PROTECTED_VIRTUALIZATION_GUEST` does not increase kernel size at all, and because it does no harm when used without Secure Execution, I think it's okay (and just easier) to add it for all.
/cc @sameo @magowan @jimcadden @fitzthum
=> kernel: Add Secure Execution guest

src/runtime/pkg/katautils/hook.go
The call to Trace() in runHooks() does not return a context; fix this so
that the subsequent calls to runHook() produces a properly ordered trace
span.
Fixes #2001
=> tracing: Make runHooks() span creation return context

src/runtime/virtcontainers/qemu.go, src/runtime/virtcontainers/sandbox.go
Architectures that do not support memory hotplugging will fail when
memory limits are set because that amount is hotplugged. Issue a warning
instead. The long-term solution is virtio-mem.
Fixes: #1412
=> virtcontainers: Don't fail memory hotplug

tools/agent-ctl/Cargo.lock
Two nix packages with the same version are specified from the lock file.
Fixes #2126
Signed-off-by: Samuel Ortiz <samuel.e.ortiz@protonmail.com>
=> tools: agent-ctl: Fix build failure

src/agent/rustjail/src/cgroups/notifier.rs, src/agent/rustjail/src/container.rs, src/agent/rustjail/src/lib.rs, src/agent/rustjail/src/mount.rs, src/agent/src/sandbox.rs, src/agent/src/test_utils.rs
These lint attributes can be deleted to keep clean code.
Fixes: #2059
=> agent: delete some lint attributes

src/agent/.gitignore, src/agent/Cargo.lock, src/agent/Cargo.toml
Update rtnetlink to use crate.io to make cargo vendor work.
Add vendor/ to .gitignore.
Fixes: #2111
=> agent: update netlink libraries

src/runtime/virtcontainers/pkg/oci/utils.go, src/runtime/virtcontainers/pkg/oci/utils_test.go
Use common functions wrapping logic of getting values
from annotations, parsing bool/uint32/uint64 and setting
to struct fields.
Fixes: #2082
=> runtime: refact virtcontainers/pkg/oci

tools/agent-ctl/README.md
Fix the incorrect regular expression to fetch the guest context ID.
In " [^,][^,]* ", [^,]* will match to the next ",", 
which is after "socket",  so finally got incorrect result.
It's better to match the contect ID by using " egrep -o "guest-cid=[0-9]*" ".
Fixes: #2124
Signed-off-by: Liang Zhou <zhoul110@chinatelecom.cn>
=> agent: fix wrong regular exp to fetch guest-cid

src/runtime/virtcontainers/clh.go, src/runtime/virtcontainers/clh_test.go
It looks like the version check for cloud hypervisor (clh) was added
initially when clh was actively evolving its API. We no longer need the
version check as clh API has been fairly stable for its recent releases.
Fixes: #1991
=> runtime: Remove the version check for cloud hypervisor

src/runtime/containerd-shim-v2/service.go
Since we only send an shutdown qmp command to qemu when do
stopSandbox, and didn't wait until qemu process's exit, thus
we'd better to make sure it had exited when shimv2 terminated.
Thus here to do the last cleanup of the hypervisor.
Fixes: #2198 
Fixes: https://github.com/kata-containers/tests/issues/3654
=> shimv2: fix the issue of leaking the hypervisor processes

src/trace-forwarder/src/handler.rs, src/trace-forwarder/src/main.rs, src/trace-forwarder/src/server.rs
Added a `--dump-only` option which disables forwarding of trace spans.
This essentially makes the forwarder a NOP but can be useful for testing
purposes.
Fixes: #2132.
=> forwarder: Add dump only option

src/agent/src/ccw.rs, src/agent/src/device.rs, src/agent/src/linux_abi.rs, src/agent/src/main.rs, src/agent/src/mount.rs, src/agent/src/uevent.rs, src/runtime/virtcontainers/hypervisor.go
The s390x architecture uses `virtio-blk-ccw` instead of `virtio-blk-pci`. It has been enabled in the runtime in the v1 days (https://github.com/kata-containers/runtime/pull/1965), and support in the Go agent was also added then (https://github.com/kata-containers/agent/pull/600). This is basically a forward port of the latter to the v2 Rust agent.
- agent/s390x: Enable `virtio-blk-ccw`, with tests. Includes a new CCW device structure and a respective uevent matcher and device handler.
- runtime/virtcontainers/s390x: The QEMU [`configuration.toml`](https://github.com/kata-containers/kata-containers/blob/main/src/runtime/cli/config/configuration-qemu.toml.in#L169) says
```
```
when it should be `virtio-blk-ccw` for s390x. I suggest to simply override the block driver to `virtio-blk-ccw` …
=> s390x: Enable virtio-blk-ccw

src/runtime/arch/s390x-options.mk
as both Fedora-likes and SUSE need this.
Fixes: #2167
=> runtime: Use CC=gcc on all RPM-based s390x

snap/snapcraft.yaml
- Ported from https://github.com/kata-containers/tests/pull/3612:
- Install protobuf-compiler for agent build on ppc64le & s390x
- Install libssl-dev for kernel build on s390x
- Fixes in image target for ppc64le & s390x
- Install image instead of initrd since it's preferred
- Use Ubuntu as base since Alpine requires a musl agent (cannot be
built on ppc64le & s390x because there is no such Rust target)
- Ported from
https://github.com/kata-containers/kata-containers/pull/1265:
Fix vmlinux install path
- Install libseccomp-dev on all architectures, not just x86_64
Fixes: #2192
=> snap: Miscellaneous s390x fixes

src/agent/rustjail/src/cgroups/fs/mod.rs
get_mounts() parses /proc/self/mountinfo in order to get the mountpoints
for various cgroup filesystems.  One of the entries in mountinfo is the
"device" for each filesystem, but for virtual filesystems like /proc, /sys
and cgroups, the device entry is arbitrary.  Depending on the exact rootfs
setup, it can end up being "-".
This breaks get_mounts() because it uses " - " as a separator.  There
really is a " - " separator in mountinfo, but in this case the device entry
shows up as a second one.  Fix this, by changing a split to a splitn, which
will effectively only consider the first " - " in the line.
While we're there, make the warning message more useful, by having it
actually show which line it wasn't able to parse.
fixes #2182
=> agent: Fix to parsing of /proc/self/mountinfo

tools/osbuilder/rootfs-builder/rootfs.sh
Check if the distro config directory exists before using the directory
Fixes: #2148
=> osbuilder: Fix the order of checking the distro config directory

src/runtime/containerd-shim-v2/create.go, src/runtime/containerd-shim-v2/service.go, src/runtime/pkg/katautils/config.go, src/runtime/pkg/katautils/create.go, src/runtime/pkg/katautils/hook.go, src/runtime/pkg/katautils/katatrace/tracing.go, src/runtime/virtcontainers/acrn.go, src/runtime/virtcontainers/api.go, src/runtime/virtcontainers/clh.go, src/runtime/virtcontainers/container.go, src/runtime/virtcontainers/factory/factory.go, src/runtime/virtcontainers/fc.go, src/runtime/virtcontainers/kata_agent.go, src/runtime/virtcontainers/mount.go, src/runtime/virtcontainers/network.go, src/runtime/virtcontainers/qemu.go, src/runtime/virtcontainers/sandbox.go, src/runtime/virtcontainers/virtiofsd.go
Removes custom trace functions defined across the repo and creates
a single trace function in a new katatrace package. Also moves
span tag management into this package and provides a function to
dynamically add a tag at runtime, such as a container id, etc.
Fixes #1162
Signed-off-by: Benjamin Porter <bporter816@gmail.com>
=> tracing: Consolidate tracing into a new katatrace package

src/runtime/virtcontainers/qemu.go
We'd better stop the virtiofsd specifically after stop qemu,
instead of depending on the qemu's termination to notify virtiofsd
to exit.
Fixes: #2211
=> qemu: stop the virtiofsd specifically

.github/workflows/static-checks.yaml
If a PR has the `force-skip-ci` label set, don't run the static tests.
Fixes: #2220.
=> CI: Honour force-skip-ci label

src/agent/Makefile, src/trace-forwarder/Makefile, utils.mk
Support rust-flags, target and build-type.
=> trace-forwarder: Add option rustflags, target, build-type for the make

snap/snapcraft.yaml
instead of image, does not require privileged containers since `losetup`
is not used and is thus more portable for various build environments.
Fixes: #2218
=> snap: Build initrd on ppc64le & s390x

src/runtime/virtcontainers/sandbox.go, src/runtime/virtcontainers/sandbox_test.go
Register defer function at early stage ensure that
it can be called if the startSandbox fails.
Fixes: #2230
=> runtime: Register defer function at early stage

tools/packaging/kata-deploy/action/Dockerfile
While doing the release we've faced the following issue:
```
Dockerfile for action: '/home/runner/work/kata-containers/kata-containers/./packaging/kata-deploy/action/Dockerfile'.
/usr/bin/docker build -t 8a33c1:c0625fe487ce5e4c8217747bef28861f -f "/home/runner/work/kata-containers/kata-containers/./packaging/kata-deploy/action/Dockerfile" "/home/runner/work/kata-containers/kata-containers/packaging/kata-deploy/action"
Sending build context to Docker daemon  15.87kB
Step 1/12 : FROM microsoft/azure-cli:latest
pull access denied for microsoft/azure-cli, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```
Carlos pointed out that the image has gone awry and that we could use
mcr.microsoft.com/azure-cli instead.
Fixes: #2240 …
=> kata-deploy: Use the correct image for kata-deploy

src/runtime/containerd-shim-v2/create.go
Seems that at least some versions of container, when using ConifgPath,
still rely on the runtime options and its APIs from the not in use
anymore github.com/containerd/cri-containerd/pkg/api/runtimeoptions/v1.
The fact backward compat breaks when moving from the old to the new
runtime options, which happened as part of f60641a6e6d, strongly feels
like a containerd bug.  Regardless, we can easily work this around on
our side without much hassle.
Just by importing old runtime options the unmarshalling doesn't break
anymore and we can easily check whether getting the options fails or not
and fallback to the old way if it does.
Fixes: #2258
=> shim-v2: Be compatible with the old runtime options

src/runtime/containerd-shim-v2/shim_management.go, src/runtime/pkg/kata-monitor/pprof.go, src/runtime/pkg/kata-monitor/shim_client.go
Commit 32c9ae1388385f10c75d9a76809f1d419e82b020 upgrade the
containerd vendor, which used the socket path to replace
the abstract socket address for socket listen and dial, and
there's an bug in containerd's abstract socket dialing.
Thus we should replace our monitor and exec socket server
with the socket path to fix this issue.
Fixes: #2238
=> shimv2: fix the issue of kata-runtime exec failed

src/agent/Cargo.lock, src/agent/Cargo.toml, src/agent/src/tracer.rs, src/agent/vsock-exporter/Cargo.toml, src/agent/vsock-exporter/src/lib.rs
- Make the vsock-exporter async totally using tokio runtime.
- Delay the timing of the connection to trace-forwarder so that it is easy to reconnect when the connection was broken.
=> vsock-exporter: switch to tokio runtime

tools/agent-ctl/Makefile
Update Makfile like other components, and remove the -v option of
cargo build commond.
Fixes: #2244
=> agent-ctl: Use a common Makefile style like other components

tools/osbuilder/rootfs-builder/centos/Dockerfile.in, tools/osbuilder/rootfs-builder/clearlinux/Dockerfile.in, tools/osbuilder/rootfs-builder/debian/Dockerfile-aarch64.in, tools/osbuilder/rootfs-builder/debian/Dockerfile.in, tools/osbuilder/rootfs-builder/fedora/Dockerfile.in, tools/osbuilder/rootfs-builder/gentoo/Dockerfile.in, tools/osbuilder/rootfs-builder/rootfs.sh, tools/osbuilder/rootfs-builder/suse/Dockerfile.in, tools/osbuilder/rootfs-builder/template/Dockerfile.template, tools/osbuilder/rootfs-builder/ubuntu/Dockerfile-aarch64.in, tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in, tools/osbuilder/scripts/lib.sh
Building rootfs does not depend on golang, delete intalling
golang may save build time.
And there is only rust agent now, the code for golang agent should
be deleted too.
Fixes: #2170
=> osbuilder: Skip installing golang for building rootfs

docs/install/container-manager/containerd/containerd-install.md
`containerd` has adopted a new configuration style. Update the example configuration to reflect the change.
Resolves https://github.com/kata-containers/kata-containers/issues/2180
=> docs: Update containerd configuration format

src/runtime/virtcontainers/virtiofsd.go
The virtiofsd's PID wan't assigned the right pid,
which will result skipping kill it.
Fixes: #2228
=> virtiofsd: fix the issue of missing stop virtiofsd

.github/workflows/static-checks.yaml, Makefile
In this pull request it is introduced the *static-checks* target (`make static-checks`) as the primary interface for developers to run the static checks locally (see #2206).
It would be nice to have a *pre-commit* target as suggested by @liubin which would run not just the static checks but all the checkers/tests executed as part of the github's static-checks workflow (see `.github/workflows/static-checks.yaml`). But I think deserves more thoughts, so I didn't go further than providing aforementioned *static-checks* target.
=> static-checks: Add a make target to run static-checks locally

ci/lib.sh
This avoids confusion e.g. when `$GOPATH` is unset.
Fixes: #2251
=> ci: set -o nounset

src/agent/Cargo.lock, src/agent/Cargo.toml, tools/agent-ctl/Cargo.lock
Update to latest tokio to address RUSTSEC-2021-0072:
Task dropped in wrong thread when aborting `LocalSet` task
Fixes: #2165
Updated by running "cargo update -p tokio" for both agent and agent-ctl
=> agent/agent-ctl: update tokio to 1.8.1

docs/install/minikube-installation-guide.md
the kata-deploy project scripts were changed, but minikube installation guide doc still use old yaml script. fix guide doc use the new yaml script of runtimeClasses.
Fixes: #2276
=> docs: fix minikube installation guide runtimeclasses error

snap/snapcraft.yaml
If you snap in an environment where you previously snapped,
`git clone`ing QEMU will fail. Remove the checkout directory.
Fixes: #2249
/cc @devimc
=> snap: Remove QEMU before clone

src/agent/src/mount.rs, src/agent/src/namespace.rs
'FLAGS' hash map has bool to indicate if the flag should be cleared or
not. But in parse_mount_flags_and_options() we set the flag even 'clear'
is true. This results in a 'rw' mount being mounted as 'MS_RDONLY'.
Fixes: #2262
Signed-off-by: Eryu Guan <eguan@linux.alibaba.com>
=> agent: clear MsFlags if the option has clear flag set

snap/snapcraft.yaml
fixed arm qemu patches dir in snap part. Clear the old `packaging/obs-packaging` path.
Fixes: #2279
=> snap: fixed snap aarch64 qemu patches dir in snapcraft.yaml file

ci/lib.sh
PR #2252 put `set -o nounset` in `ci/lib.sh`. It turns out that this
won't work when `$CI` is unset (it is always set in CI). Expand `$CI` to
nothing.
Fixes: #2283
=> ci: expand $CI to nothing

Glossary.md, README.md
This commit is a result of Assisted PR Process for PR #1515.  It
deviates from it in that the original commits were not retained as the
original commit structure was unnecessarily complex - the same commit
was added to two parallel branches which were then merged, producing the
same result in the end as any of the original two non-merge commits.
Also, a squash was requested by an original PR review.
The only other change to the original PR was to change capitalisation of
the word "Kubelet" in Glossary.md to placate spell checker.
The original commit message follows:
The terms added are: Kata Containers, container software, container
runtime interface, virtual machine software, container virtualization,
container security solutions, serverless containers, pod containers,
virtual machine …
=> docs: added a glossary to support SEO tactics

src/runtime/containerd-shim-v2/shim_management.go
Since the monitor socket used the unix socket path file,
which needed to be cleaned after the pod terminated,
thus put it into the sandbox data directory, and it
would be cleaned up once the sandbox termianted.
Fixes: #2269
=> monitor: mv the monitor socket into sbs directory

tools/osbuilder/rootfs-builder/centos/config_aarch64.sh
fix GPG_KEY_ARCH_URL config of centos's config_aarch64, update to "http://mirror.centos.org/altarch/7/os/aarch64/RPM-GPG-KEY-CentOS-7".
Fixes: #2181
=> osbuilder: update centos arm rootfs image config 'GPG_KEY_ARCH_URL'

tools/osbuilder/scripts/lib.sh
yq changed syntax in an incompatible way starting from version 4 and
above. Add support to all versions.
Fixes https://github.com/kata-containers/kata-containers/issues/2297
I think this should fix the snap building process in the CI
=> osbuilder/scripts: add support to yq version 4 and above

snap/snapcraft.yaml
This causes the repository to be checked out to a version tag, which is
inconsistent with how we build runtime, and reverts us to a buggy
`snap/snapcraft.yaml`.
Fixes: #2313
see https://github.com/kata-containers/kata-containers/issues/2190#issuecomment-886798117
=> snap: do not export agent version

src/runtime/virtcontainers/experimental/README.md
This PR updates the experimental documentation with the proper reference
to kata 2.x
Fixes #2317
=> docs: Update experimental documentation

docs/Developer-Guide.md
This PR updates the proper url for log parser for kata 2.x for
the Developer Guide document.
Fixes #2328
=> docs: Update url for log parser in Developer guide

snap/snapcraft.yaml
rather than removing the other line because configuration only contains
the image line ever more and this is how we already do it in tests.
Fixes: #2330
=> snap: Substitute image configuration with initrd

src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/BalloonConfig.md, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/NumaConfig.md, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/SgxEpcConfig.md, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_balloon_config.go, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_numa_config.go, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_sgx_epc_config.go, src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml, versions.yaml
Highlights from the Cloud Hypervisor release v17.0:
1. ARM64 NUMA support using ACPI; 
2. `Seccomp` support for MSHV backend;
3. Hotplug of macvtap devices; 
4. Improved SGX support;
5. Inflight tracking for `vhost-user` devices;
6. Bug fixes.
Details can be found: https://github.com/cloud-hypervisor/cloud-hypervisor/releases/tag/v17.0
generated by `openapi-generator` [1-2]. As the API changes do not
impact usages in Kata, no additional changes in kata's runtime are
needed to work with the current version of cloud-hypervisor.
[1] https://github.com/OpenAPITools/openapi-generator
[2] https://github.com/kata-containers/kata-containers/blob/main/src/runtime/virtcontainers/pkg/cloud-hypervisor/README.md
Fixes: #2333 …
=> versions: Upgrade to Cloud Hypervisor v17.0

.github/workflows/static-checks.yaml
Looking at the changes that could cause the static-checks to not run
when a PR is updated I think 7db8a85a1f3b4a2ccecd959c33fd88386e4a8691
could be the one that introduced such a regression.
Let's (try to) fix this by enforcing the workflow to run also when the
PR has been "edited" and "synchronized".
Fixes: #2343
=> ci: Run static checks when PRs are updated

docs/how-to/how-to-use-virtio-mem-with-kata.md
Remove undefined ${REPORT_DIR} in how-to-use-virtio-mem-with-kata.md.
Fixes: #2348
Signed-off-by: Hui Zhu <teawater@antfin.com>
=> how-to-use-virtio-mem-with-kata.md: Remove undefined ${REPORT_DIR}

tools/packaging/kata-deploy/README.md
fixed the url error, updated the path to kata 2.x release
(https://github.com/kata-containers/kata-containers/releases) from kata 1.x release
(https://github.com/kata-containers/runtime/releases) in the kata-deploy README.md file.
Fixes: #2355.
=> docs: update the kata release url in the kata deploy document

.github/workflows/static-checks.yaml
This is not the most beautiful solution, but when do the check on every single step we ensure the test at least started, and consequently will succeed.
Without this the tests wouldn't even start, making any PR using the `force-skip-ci` label not mergeable.
Fixes: #2362
=>  static-checks: Check for the `force-skip-ci` label on each step

src/runtime/virtcontainers/container.go, src/runtime/virtcontainers/sandbox.go
container start fail if io.katacontainers.container.resource.swap_in_bytes and memory_limit_in_bytes are not set.
```
$ pod_yaml=pod.yaml
$ container_yaml=container.yaml
$ image="quay.io/prometheus/busybox:latest"
$ cat << EOF > "${pod_yaml}"
metadata:
name: busybox-sandbox1
EOF
$ cat << EOF > "${container_yaml}"
metadata:
name: busybox-killed-vmm
annotations:
io.katacontainers.container.resource.swappiness: "60"
image:
image: "$image"
command:
- top
EOF
$ sudo crictl pull $image
$ podid=$(sudo crictl runp $pod_yaml)
$ cid=$(sudo crictl create $podid $container_yaml $pod_yaml)
$ sudo crictl start $cid
DEBU[0000] get runtime connection
DEBU[0000] connect using endpoint 'unix:///var/run/containerd/containerd.sock' with '10s' timeout
DEBU[0000] connected successfully using endpoint: …
```
=> Fix issue container start fail if io.katacontainers.container.resource.swap_in_bytes and memory_limit_in_bytes are not set

src/runtime/virtcontainers/qemu_arm64.go, src/runtime/virtcontainers/qemu_arm64_test.go
There is a new "ReadOnly" option added to nvdimm device in qemu
and now added to kata. However, qemu used for arm64 is a little
old and has no this feature. Here we remove this feature for arm.
this issue leads to the failure of arm ci.
Fixes: #2320
=> qemu/arm: remove nvdimm/"ReadOnly" option on arm64

src/runtime/virtcontainers/container.go
The swappiness is not right if just set
io.katacontainers.container.resource.swappiness:
```
$ pod_yaml=pod.yaml
$ container_yaml=container.yaml
$ image="quay.io/prometheus/busybox:latest"
$ cat << EOF > "${pod_yaml}"
metadata:
name: busybox-sandbox1
EOF
$ cat << EOF > "${container_yaml}"
metadata:
name: busybox-killed-vmm
annotations:
io.katacontainers.container.resource.swappiness: "100"
image:
image: "$image"
command:
- top
EOF
$ sudo crictl pull $image
$ podid=$(sudo crictl runp $pod_yaml)
$ cid=$(sudo crictl create $podid $container_yaml $pod_yaml)
$ sudo crictl start $cid
crictl exec $cid cat /sys/fs/cgroup/memory/memory.swappiness
60
```
The cause of this issue is there are two elements store the resources
infomation.  They are c.config.Resources for calculateSandboxMemory and …
=> Container: Add initConfigResourcesMemory and call it in newContainer

tools/packaging/kata-deploy/README.md
Kata deploy README document only contains Firecracker and Qemu. This PR adds
cloud-hypervisor test command to the README.md file.
Fixes: #2357
=> docs: update kata deploy README doc to add cloud-hypervisor test command

tools/osbuilder/rootfs-builder/rootfs.sh
With lines like
https://github.com/kata-containers/kata-containers/blob/0a2e2c6038ff9623610d62cad8db1d723dd500cb/tools/osbuilder/rootfs-builder/fedora/config.sh#L8
we imply that one can set another OS_VERSION and it will get picked up.
This is not the case when building inside Docker/Podman because the
variable is not passed to the container, which can lead to confusion.
Forward this env.
Fixes: #2378
/test
=> osbuilder: pass env OS_VERSION

tools/osbuilder/.gitignore, tools/osbuilder/Makefile, tools/osbuilder/dracut/add_libs.sh
When the guest is built using dracut and the agent uses glibc (esp.
ppc64le/s390x), libraries might be missing. In my case, it was
`libutil.so`, but more can be added easily. Add a script to configure
`install_items` for dracut w.r.t. `ldd` of the agent.
Fixes: #2384
=> osbuilder/dracut: Add missing libraries

.github/workflows/kata-deploy-test.yaml, .github/workflows/main.yaml, .github/workflows/release.yaml, docs/how-to/data/kata-monitor-daemonset.yml, tools/packaging/kata-deploy/action/test-kata.sh, tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml, tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml, tools/packaging/release/update-repository-version.sh
Now that the project owns https://quay.io/kata-containers, let's also push our images there and start making it our primary image repository.  Together with this change, let's also update all our scripts, pod definitions, and documentation that were pointing to `katadocker`.
Fixes: #2306
=> kata-deploy: Update our content to use / point to quay.io/kata-containers rather than katadocker

.github/workflows/kata-deploy-test.yaml, .github/workflows/main.yaml, .github/workflows/release.yaml
9fa1febfd9e6372fc1fd9ec3416082182c2f8c21 added the support to also push
the image to quay.io.  However, we didn't try explicitly pass quay.io as
the registry server, causing then to login to fail.
Fixes: #2306
=> workflows: Actually login to quay.io

tools/packaging/kata-deploy/Dockerfile
This PR consists in 3 small patches updating the base image we use for kata-deploy.  All in all, the differences are not big, as we keep using CentOS 7, but we ensure that we have it up-to-date and we also lower the delta of the packages that have to be updated during the process of building the image.
If you're curious why we keep using CentOS 7 though, the reason is because CentOS 8, and UBI images have a different systemd configuration that works quite well when mounting the image using podman, but systemd can't connect dbus when running on environments like AKS or even minikube.  So, in order to be as compatible as possible, let's keep
using the CentOS 7 image for now, at least till we find a suitable substitute for that.
Fixes: #2303
=> kata deploy: always update the base image

ci/run.sh
Run the agent shutdown test as part of CI testing code in this repo.
Fixes: #1808.
Depends-on:github.com/kata-containers/tests#3495
=> CI: Call agent shutdown test

src/runtime/virtcontainers/fc.go
When running a firecracker instance jailed, block devices
are not removed correctly, as the jailerRoot path is not
stripped from the PATCH command sent to the FC API.
This patch differentiates the jailed case from the non-jailed
one and allows the firecracker instance to be properly
terminated.
Fixes #2387 
Signed-off-by: Anastassios Nanos <ananos@nubificus.co.uk>
=> virtcontainers: fc: properly remove jailed block device

tools/packaging/static-build/cloud-hypervisor/build-static-clh.sh
Currently, there is cloud hypervisor binary released only for x86, thus
we must build from source code when install cloud hypervisor on non-x86.
Fixes: #2410
Sign-off-by: Jianyong Wu <jianyong.wu@arm.com>
@likebreath @bergwolf
=> clh: correct cloud-hypervisor installation on non-x86

src/runtime/virtcontainers/fc.go
When running a firecracker instance jailed, block devices
are not removed correctly, as the jailerRoot path is not
stripped from the PATCH command sent to the FC API.
This patch differentiates the jailed case from the non-jailed
one and allows the firecracker instance to be properly
terminated.
Fixes #2387
Signed-off-by: Anastassios Nanos <ananos@nubificus.co.uk>
(cherry picked from commit 64dd35b)
=> stable-2.1 | virtcontainers: fc: properly remove jailed block device

docs/use-cases/using-vpp-and-kata.md, src/runtime/virtcontainers/experimental/README.md
changed the document project url in the using-vpp-and-kata.md and
runtime experimental README.md files.
Fixes: #2418
=> docs: update the docs project url from kata 1.x to 2.x

tools/osbuilder/tests/test_config.sh, tools/osbuilder/tests/test_images.sh
With Kata 1.x EOL, the Go agent is no more.  So, remove support for it from the Kata tree.er scripts.  This removes the RUST_AGENT variable, treating it as always true.
=> osbuilder: Drop Go agent support

snap/snapcraft.yaml
snap build for arm64 fail for a long time, here we enable it.
the changes:
1. correct the variable of "branch"
2. add v5.1.0 under tag_patchs
Fixes: #2194
@jodh-intel @fidencio @devimc
=> enable snap build for arm64

src/runtime/virtcontainers/clh.go, src/runtime/virtcontainers/clh_test.go
It looks like the version check for cloud hypervisor (clh) was added
initially when clh was actively evolving its API. We no longer need the
version check as clh API has been fairly stable for its recent releases.
Fixes: #1991
(cherry picked from commit d08603bebb28eef8badf1aed8f0543991925a514)
=> [backport] runtime: Remove the version check for cloud hypervisor

tools/osbuilder/README.md
Alpine used to work as guest under 1.x, but because there is no musl
target for Rust on s390x, Alpine will not work for 2.x. Document this.
Fixes: #2436
=> osbuilder: Document no Alpine support on s390x

src/runtime/pkg/katautils/hook.go
This change was made earlier but inadvertently overwritten in another PR.
The call to Trace() in runHooks() should return a context so that
subsequent calls to runHook() produce properly ordered trace spans.
Fixes #2423
=> tracing: Return context in runHooks() span creation

docs/install/README.md
This change update general wording for the installation documentation.
Remove duplicated information, reduce text separation, rewrite notes to be more clear and concise.
Fixes: #2449
Signed-off-by: Joao Vanzuita <joaovanzuita@me.com>
=> docs: update general wording for installation documentation

.github/workflows/release.yaml
As quay.io is becoming our de-facto image registry, let's actually push
the kata-deploy release to it.  This commit should've been part of
9fa1febfd9e6372fc1fd9ec3416082182c2f8c21 but ended up slipping out.
Fixes: #2306
=> workflows: Actually push the release to quay.io

src/runtime/cli/config/configuration-fc.toml.in
Now that we have enabled CI tests for jailed firecracker and we have
fixed the  issue with removing the block storage device #2387, we
should leverage the full power of firecracker and enable jailer by
default.
Fixes: #2455
Signed-off-by: Jack Rieck <jack.rieck@sendgrid.com>
=> config: Enable jailer by default when using firecracker

.github/workflows/release.yaml
b789a935cf69f1aa4bd8eda2cd3ac0b721f056ba changed the artifact name from
"release-candidate" to "kata-static-tarball".  However, we didn't do the
same for the upload-static-tarball action, causing us the following
error during the release process:
https://github.com/kata-containers/kata-containers/runs/3383157459?check_suite_focus=true
Fixes: #2475
=> workflows: fix artifact name in the release yaml

docs/how-to/how-to-use-k8s-with-cri-containerd-and-kata.md
update cri plugin source path to containerd pkg in the
how-to-use-k8s-with-cri-containerd-and-kata.md file. The cri project was moved to containerd project pkg directory.
Fixes: #2490
=> docs: update containerd CRI plugin url

ci/openshift-ci/images/Dockerfile.buildroot
In order to avoid hit the pull requests limit of docker.io, this changed the
openshift-ci/images/Dockerfile.buildroot dockerfile to pull the centos image
from registry.centos.org.
Fixes #1636
=> ci/openshift-ci: Pull centos from registry.centos.org

docs/how-to/README.md
Remove the `Kata Containers with Firecracker` additional configuration steps.
From kata 2.x,  the config of `firecracker` is same to `qemu` and `cloud-hypervisor`.
Fixes: #2492
=> docs: update `how-to` README file for Firecracker config

src/runtime/virtcontainers/agent.go, src/runtime/virtcontainers/documentation/api/1.0/api.md
type: ProcessListOptions; ProcessList
const: SocketTypeVSOCK
Fixes: #2285
=> runtime: delete types or const that no longer needed

docs/how-to/what-is-vm-templating-and-how-do-I-use-it.md, src/runtime/cli/main_test.go, src/runtime/containerd-shim-v2/utils_test.go, src/runtime/pkg/katautils/config-settings.go.in, src/runtime/pkg/katautils/create_test.go, src/runtime/virtcontainers/qemu_amd64.go, src/runtime/virtcontainers/qemu_arch_base.go, src/runtime/virtcontainers/qemu_arch_base_test.go
qemu-lite project has not seen any activity for more than 5 years. We have not been testing against it for a very long time either. Let's just drop the related code.
=> drop qemu-lite support

tools/packaging/guest-image/build_image.sh
fix error soft link about initrd.img
Fixes #2503
backport PR: https://github.com/kata-containers/kata-containers/pull/2504
=> backport: build_image: Fix error soft link about initrd.img

src/runtime/containerd-shim-v2/service.go, src/runtime/virtcontainers/sandbox.go
shimv2: add logging to shimv2 api calls
and also fetch and log container id from the request
Fixes: #2527
=> shimv2: add logging to shimv2 api calls 

ci/run.sh
=> backport ci: Temporarily skip agent shutdown test on s390x

src/runtime/pkg/katautils/katatrace/tracing.go, src/runtime/virtcontainers/acrn.go, src/runtime/virtcontainers/clh.go, src/runtime/virtcontainers/container.go, src/runtime/virtcontainers/fc.go, src/runtime/virtcontainers/mount.go, src/runtime/virtcontainers/qemu.go, src/runtime/virtcontainers/sandbox.go
1. Tracing tags are stored inconsistently throughout the runtime. Change
all instances of tracing tags to variables.
2. Add function so that you can dynamically add more attributes when calling `katatrace.Trace()`
Fixes #2512
=> tracing: Change runtime tracing tags to vars

snap/snapcraft.yaml
In snapcraft.yaml we have a case statement on $(branch) - that is on the
output of executing a command "branch".  From the selections it appears
that what it actually wants is to simply select on the contents of the
$branch variable, which should be ${branch} instead.
fixes #2558
=> snap: Test variable instead of executing "branch"

tools/osbuilder/image-builder/image_builder.sh
This patch fixes inconsistent calculations of the rootfs size.
For `du` and `df`, `-B 1MB` is different from `-BM`. The former is the power of 1000, and the latter is the power of 1024. So comparing them doesn't make sense. The bug may result in a larger image than needed.
Fixes: #2560
Signed-off-by: Yujia Qiao <rapiz3142@gmail.com>
PTAL @devimc
=> osbuilder: fix inconsistent calculation of fs size

src/runtime/Makefile
Generate `config-generated.go` file under src/runtime/cli/containerd-shim-kata-v2 before excuting test or coverage.
Fixes #2479
=> makefile: Fix error exit status code

docs/how-to/README.md, docs/how-to/ccv0.sh, docs/how-to/how-to-build-and-test-ccv0.md, src/runtime/README.md
This commit add documentation and a script to help people to build, run,
test and demo the CCv0 changes around PullImage on guest.
It is currently limited to the Agent pullimage, but can be expanded
as more code is shared.
Also update LICENSE link in src/runtime/README.md that failed staticcheck
Fixes #2574
=> CCv0 | doc: Add doc and scripts for CCv0 agent PullImage

versions.yaml
Add a pr_id field to the cri-containerd config in versions.yaml
so the CI scripts can use this in the CCv0 builds as part of https://github.com/kata-containers/tests/pull/3888
Fixes #2576
=> CCv0 | version: Add support for using containerd PR

tools/osbuilder/rootfs-builder/centos/config.sh, tools/osbuilder/rootfs-builder/clearlinux/config.sh, tools/osbuilder/rootfs-builder/fedora/config.sh
zsh doesn't support "==" as equal comparison operator, so
replace "==" with "=" to make the script more portable
Fixes: #2584
=> osbuilder: Change to "=" operator to make script more portable

.github/workflows/kata-deploy-push.yaml, Makefile, tools/packaging/kata-deploy/local-build/Makefile
makefile: Include kata-deploy targets
>Use kata-deploy targets from toplevel. This will help if want to build and reinstall just one single kata component.
kata-deploy: Add tarball suffix to makefile targets
>Now that local-build kata-deploy makefile is inlucded in toplevel
makefile, lets use the suffix `-tarball` to avoid name collitions
and identify the tarball releted targets.
kata-deploy: Make verbose single builds
>If a binary tarball for a single component is done, the logs will be shown in stdout.
e.g.
`make kernel-tarball`
To build all a the same time still store logs in files.
`make kata-tarball`
actions: kata-deploy on PRs and use makefile
>- Run kata-deploy tarball generation action on every PR.
- Use kata-deploy makefile targets.
actions: test `make kata-tarball `
> make …
=> kata-tarball: Build and test fixes

snap/snapcraft.yaml
In snapcraft.yaml we have a case statement on $(branch) - that is on the
output of executing a command "branch".  From the selections it appears
that what it actually wants is to simply select on the contents of the
$branch variable, which should be ${branch} instead.
fixes #2558
=> [backport] snap: Test variable instead of executing "branch"

src/runtime/virtcontainers/fc.go
In getThreadIDs(), the cpuID variable is derived from a string that
already contains a whitespace. As a result, strings.SplitAfter returns
the cpuID with a leading space. This makes any go variant of string to int
fail (strconv.ParseInt() in our case). This patch makes sure that the
leading space character is removed so the string passed to
strconv.ParseInt() is "CPUID" and not " CPUID".
This has been caused by a change in the naming scheme of vcpu threads
for Firecracker after v0.19.1.
Fixes: #2592
Signed-off-by: Anastassios Nanos <ananos@nubificus.co.uk>
=> virtcontainers: fc: parse vcpuID correctly

src/runtime/README.md
The LICENSE file lives in the project's root.
Fixes #2612
=> runtime: Fix README link

src/runtime/README.md
The LICENSE file lives in the project's root.
Fixes #2612
=> [backport] runtime: Fix README link

src/runtime/virtcontainers/sandbox.go
adds the default devices for unix such as /dev/null, /dev/urandom to
the container's resource cgroup spec
Fixes: #2539
Backports: #2603
=> [backport]sandbox: Add device permissions such as /dev/null to cgroup

src/runtime/virtcontainers/clh.go, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/MemoryConfig.md, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/NetConfig.md, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_memory_config.go, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_net_config.go, src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml, versions.yaml
Highlights from the Cloud Hypervisor release v18.0:
1. Experimental User Device (`vfio-user`) support;
2. Migration support for `vhost-user` devices;
3. VHDX disk image support
4. Device pass through on MSHV hypervisor
5. AArch64 for support `virtio-mem`
6. Live migration on MSHV hypervisor
7. AArch64 CPU topology support
8. Power button support on AArch64
9. Various bug fixes on PTY, TTY, signal handling, and live-migration on AArch64
Details can be found: https://github.com/cloud-hypervisor/cloud-hypervisor/releases/tag/v18.0
Note: The client code of cloud-hypervisor's (CLH) OpenAPI is automatically
generated by openapi-generator [1-2]. Small changes has been made to
CLH's openapi spec file for fixing couple minor bugs [3], and hence small
changes are made from the Kata side.
[1] …
=> versions: Upgrade to Cloud Hypervisor v18.0

src/runtime/virtcontainers/clh.go, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/MemoryConfig.md, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/NetConfig.md, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_memory_config.go, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_net_config.go, src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml, versions.yaml
Highlights from the Cloud Hypervisor release v18.0:
1. Experimental User Device (`vfio-user`) support;
2. Migration support for `vhost-user` devices;
3. VHDX disk image support
4. Device pass through on MSHV hypervisor
5. AArch64 for support `virtio-mem`
6. Live migration on MSHV hypervisor
7. AArch64 CPU topology support
8. Power button support on AArch64
9. Various bug fixes on PTY, TTY, signal handling, and live-migration on AArch64
Details can be found: https://github.com/cloud-hypervisor/cloud-hypervisor/releases/tag/v18.0
Note: The client code of cloud-hypervisor's (CLH) OpenAPI is automatically
generated by openapi-generator [1-2]. Small changes has been made to
CLH's openapi spec file for fixing couple minor bugs [3], and hence small
changes are made from the Kata side.
[1] …
=> stable-2.2 | versions: Upgrade to Cloud Hypervisor v18.0

src/runtime/virtcontainers/qemu.go
We recently updated to using qemu-6.1 (from qemu 5.2).  Unfortunately one
breaking change in qemu 6.0 wasn't caught by the CI.
The query-cpus QMP command has been removed, replaced by query-cpus-fast
(which has been available since qemu 2.12).  govmm already had support for
query-cpus-fast, we just weren't using it, so the change is quite easy.
fixes #2643
=> runtime/qemu: Move from query-cpus to query-cpus-fast

.github/workflows/static-checks.yaml, src/agent/src/watcher.rs, src/agent/vsock-exporter/src/lib.rs, versions.yaml
Update `versions.yaml` to test with more recent Rust versions than the now fairly old 1.47.0.
=> versions: Allow newer Rust versions

src/agent/src/mount.rs, src/agent/src/namespace.rs, src/agent/src/rpc.rs, src/agent/src/sandbox.rs, src/agent/src/watcher.rs
mount_storage() first makes sure the mount point for the storage volume
exists.  It uses fs::create_dir_all() in the case of 9p or virtiofs volumes
otherwise ensure_destination_exists().  But.. ensure_destination_exists()
boils down to an fs::create_dir_all() in most cases anyway.  The only case
it doesn't is for a bind fstype, where it creates a file instead of a
directory.  But..
1) mount_storage() isn't used for bind mounts
2) That behaviour for bind mounts isn't correct anyway, because we would
need to create either a file or a directory depending on the source of
the bind mount, which ensure_destination_exists() doesn't know about.
Furthermore the 9p/virtiofs path checks if the mountpoint exists before
calling fs::create_dir_all(), which is unnecessary, because create_dir_all
has an …
=> agent: Simplify mount point creation

src/runtime/cli/config/configuration-clh.toml.in, src/runtime/virtcontainers/clh.go
This patch adds the configuration option that allows to use hugepages
with Cloud Hypervisor guests.
Fixes: #2648
=> runtime: clh: Enable hugepages support

docs/how-to/ccv0.sh, docs/how-to/how-to-build-and-test-ccv0.md, src/agent/src/rpc.rs
- Add a check in setup_bundle to see if the bundle already exists
and if it does then skip the setup.
- Add documentation and script for create_container agent test
Fixes: #2617
Co-authored-by: Dave Hay <david_hay@uk.ibm.com>
=> CCv0 | agent: Add CreateContainer support for pre-pulled bundle

src/runtime/virtcontainers/documentation/api/1.0/api.md
Sync the virtcontainers api.md document, add `ConfidentialGuest` `EntropySourceList` `GuestSwap` three
fields to the HypervisorConfig API.
Fixes #2625
=> virtcontainers: update VC HypervisorConfig API add three lost fields

src/runtime/virtcontainers/container_test.go
Due to #2332 being merged after running tests for #2604, and the latter
being merged now, a test for the now removed `storeContainer` was added.
Remove it.
Fixes: #2652
=> runtime: Remove outdated TestStoreContainer

src/runtime/virtcontainers/fc.go
In getThreadIDs(), the cpuID variable is derived from a string that
already contains a whitespace. As a result, strings.SplitAfter returns
the cpuID with a leading space. This makes any go variant of string to int
fail (strconv.ParseInt() in our case). This patch makes sure that the
leading space character is removed so the string passed to
strconv.ParseInt() is "CPUID" and not " CPUID".
This has been caused by a change in the naming scheme of vcpu threads
for Firecracker after v0.19.1.
Fixes: #2592
Signed-off-by: Anastassios Nanos <ananos@nubificus.co.uk>
=> stable-2.2 | virtcontainers: fc: parse vcpuID correctly

ci/run.sh
The agent shutdown test should only run on the CI JOB of CRI_CONTAINERD_K8S_MINIMAL
which is the only one where testing tracing is being enabled, however, this
test is being triggered in multiple CI jobs where it should not run. This PR
fixes that issue.
Fixes #2683
=> ci: Call agent shutdown test only in the correspondent CI_JOB

src/runtime/virtcontainers/pkg/cgroups/utils.go
An empty cgroup path shouldn't fail cgroup creation
Fixes #2674
=> runtime: fix empty cgroup path validation error

src/runtime/.gitignore
update .gitignore file, remove the follow configurations:
/virtcontainers/shim/mock/cc-shim/cc-shim
/virtcontainers/shim/mock/kata-shim/kata-shim
/virtcontainers/shim/mock/shim
Fixes: #2670
=> runtime: update .gitignore file cleare the vc shim config

src/runtime/config/configuration-qemu.toml.in, src/runtime/pkg/containerd-shim-v2/create.go, src/runtime/pkg/katautils/config-settings.go.in, src/runtime/pkg/katautils/config.go, src/runtime/pkg/utils/utils.go, src/runtime/pkg/utils/utils_test.go, src/runtime/virtcontainers/api_test.go, src/runtime/virtcontainers/hypervisor.go, src/runtime/virtcontainers/persist/fs/fs.go, src/runtime/virtcontainers/pkg/annotations/annotations.go, src/runtime/virtcontainers/pkg/oci/utils.go, src/runtime/virtcontainers/pkg/rootless/rootless.go, src/runtime/virtcontainers/qemu.go, src/runtime/virtcontainers/utils/utils.go, src/runtime/virtcontainers/utils/utils_test.go, src/runtime/virtcontainers/virtiofsd.go, src/runtime/virtcontainers/virtiofsd_test.go
The change is to enable running QEMU VMM process as a non-root user in Kata for better security. A new flag `rootless` is added to the hypervisor config. If the flag is set to true, when the kata shim v2 is creating a Pod sandbox, it creates a random user (e.g. qemu-1180) and uses it to launch the QEMU process. It also creates a file directory structure (`/run/user/[uid]/vc/...`) and use it to store the vmm files (such as qmp.sock, vhost-fs.sock, console.sock). The file directory is owned by the qemu user. This change also utilizes the [existing rootless code path](https://github.com/kata-containers/kata-containers/blob/main/src/runtime/virtcontainers/pkg/rootless/rootless.go).
Manually tested the change. I was able to manually build the kata-runtime and use it to launch pods and …
=> runtime: run the QEMU VMM process with a non-root user

.github/workflows/release.yaml
As part of the release, let's also upload a tarball with the vendored
cargo code.  By doing this we allow distros, which usually don't have
access to the internet while performing the builds, to just add the
vendored code as a second source, making the life of the downstream
maintainers slightly easier*.
Fixes: #1203
*: The current workflow requires the downstream maintainer to download
the tarball, unpack it, run `cargo vendor`, create the tarball, etc.
Although this doesn't look like a ridiculous amount of work, it's better
if we can have it in an automated fashion.
=> workflows,release: Upload the vendored cargo code

docs/how-to/ccv0.sh, docs/how-to/how-to-build-and-test-ccv0.md, src/agent/protocols/protos/agent.proto, src/agent/src/rpc.rs, tools/agent-ctl/src/client.rs
Add source credentials field to pull_image request
If field is not blank, send to skopeo in image pull command
Add source_creds to agentl-ctl pull command
Fixes: #2653
=> CCV0 | agent: Enable authenticated agent pull image

tools/packaging/qemu/patches/5.1.x/0014-gitmodules-use-GitLab-repos-instead-of-qemu.org.patch, tools/packaging/qemu/patches/5.2.x/0011-gitmodules-use-GitLab-repos-instead-of-qemu.org.patch
QEMU's submodule checkout from git.qemu.org can fail. On QEMU 6.x, this
is not a problem because they moved to GitLab. However, we use QEMU 5.2
on stable-2.2, which can be a problem when no cached QEMU is used.
Backport QEMU's switch.
Fixes: #2698
/cc @jongwu @fidencio @wainersm
=> packaging: Backport QEMU's switch to GitLab repos

ci/run.sh
The agent shutdown test should only run on the CI JOB of CRI_CONTAINERD_K8S_MINIMAL
which is the only one where testing tracing is being enabled, however, this
test is being triggered in multiple CI jobs where it should not run. This PR
fixes that issue.
Fixes #2683
=> backport: Call agent shutdown test only in the correspondent CI_JOB

tools/packaging/qemu/patches/5.1.x/0014-gitmodules-use-GitLab-repos-instead-of-qemu.org.patch
This brings #2699 to 5.1.x for ARM. Add a `no_patches` for 5.1.0 which
was missing apparently.
Fixes: #2701
/cc @gkurz @jongwu
I hope the attribution is correct this way, PTAL @wainersm
=> packaging: Backport QEMU's GitLab switch to 5.1.x

src/runtime/virtcontainers/documentation/api/1.0/api.md
sync the virtcontainers api.md document, add SandboxBindMounts field to the SandboxConfig API.
And update the order of the SandboxConfig API fields.
Fixes #2621
=> virtcontainers: update VC SandboxConfig API add SandboxBindMounts field

src/runtime/virtcontainers/container.go
Change logger in Trace call in newContainer from sandbox.Logger() to
nil. Passing nil will cause an error to be logged by kataTraceLogger
instead of the sandbox logger, which will avoid having the log message
report it as part of the sandbox subsystem when it is part of the
container subsystem.
The kataTraceLogger will not log it as related to the container
subsystem, but since the container logger has not been created at this
point, and we already use the kataTraceLogger in other instances where a
subsystem's logger has not been created yet, this PR makes the call
consistent with other code.
Fixes #2665
=> runtime: tracing: Fix logger passed in newContainer

.github/workflows/release.yaml, tools/packaging/kata-deploy/README.md, tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup-stable.yaml, tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml, tools/packaging/kata-deploy/kata-deploy/base/kata-deploy-stable.yaml, tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml, tools/packaging/kata-deploy/runtimeclasses/kata-runtimeClasses.yaml, tools/packaging/release/update-repository-version.sh
When releasing a tarball, let's **also** add the "stable" & "latest" tags to the kata-deploy image.  The "stable" tag refers to any **official** release, while the "latest" tag refers to any **pre-release** (alphas & rcs).
In order to do so, let's also change the content of both kata-deploy & kata-cleanup yaml and point to the `latest` (as this is something happening on the `main` branch).  By doing this already we can also go ahead and tweak the `update-repository-version.sh` script to change the tags accordingly to "stable" & "latest".
=> kata-deploy: Also provide "stable" & "latest" tags

docs/use-cases/Nvidia-GPU-passthrough-and-Kata.md, src/runtime/go.mod, src/runtime/go.sum, src/runtime/vendor/github.com/kata-containers/govmm/qemu/qemu.go, src/runtime/vendor/modules.txt, src/runtime/virtcontainers/qemu.go, src/runtime/virtcontainers/qemu_amd64.go, src/runtime/virtcontainers/qemu_amd64_test.go, src/runtime/virtcontainers/qemu_arch_base.go, src/runtime/virtcontainers/qemu_arch_base_test.go, src/runtime/virtcontainers/qemu_arm64.go, src/runtime/virtcontainers/qemu_arm64_test.go, src/runtime/virtcontainers/qemu_ppc64le.go, src/runtime/virtcontainers/qemu_s390x.go
SHPC hotplug requires a 5s delay which makes it unusable for Kata.  Furthermore although qemu was attempting to use SHPC, the guest kernel used in the CI was broken such that SHPC didn't work at all.  Instead we saw plugged VFIO devices because of an explicit rescan in the agent.  We actually relied on that behaviour because combining the manual rescan with an SHPC hotplug can cause devices to go into a broken state for the remained of the guest lifetime (see also https://github.com/kata-containers/kata-containers/issues/2288).
Getting ACPI PCI hotplug for the `q35` machine type means updating to the soon to be released qemu-6.1.
=> Replace SHPC with ACPI PCI hotplug for Kata guests

src/runtime/pkg/containerd-shim-v2/service.go
Call StopTracing with s.rootCtx, which is the root context for tracing,
instead of s.ctx, which is parent to a subset of trace spans.
Fixes #2661
=> runtime: tracing: Use root context to stop tracing

src/runtime/containerd-shim-v2/service.go
Call StopTracing with s.rootCtx, which is the root context for tracing,
instead of s.ctx, which is parent to a subset of trace spans.
Backport of #2662
Fixes #2663
=> stable-2.2 | runtime: tracing: Use root context to stop tracing

src/runtime/virtcontainers/container.go
Change logger in Trace call in newContainer from sandbox.Logger() to
nil. Passing nil will cause an error to be logged by kataTraceLogger
instead of the sandbox logger, which will avoid having the log message
report it as part of the sandbox subsystem when it is part of the
container subsystem.
The kataTraceLogger will not log it as related to the container
subsystem, but since the container logger has not been created at this
point, and we already use the kataTraceLogger in other instances where a
subsystem's logger has not been created yet, this PR makes the call
consistent with other code.
Backport of #2666
Fixes #2667
=> stable-2.2 | runtime: tracing: Fix logger passed in newContainer

.github/workflows/release.yaml, tools/packaging/kata-deploy/README.md, tools/packaging/kata-deploy/runtimeclasses/kata-runtimeClasses.yaml, tools/packaging/release/update-repository-version.sh
When releasing a tarball, let's also add the "stable" & "latest" tags to the kata-deploy image. The "stable" tag refers to any official release, while the "latest" tag refers to any pre-release (alphas & rcs).
In order to do so, let's also change the content of both kata-deploy & kata-cleanup yaml and point to the latest (as this is something happening on the main branch). By doing this already we can also go ahead and tweak the update-repository-version.sh script to change the tags accordingly to "stable" & "latest".
Partially backports: #2453
Fixes: #2302
I'm **NOT** backporting the following commits, as those only make sense on the `main` branch:
* https://github.com/kata-containers/kata-containers/pull/2453/commits/a86babe0d04c2cf5b382ed5806c0f40e2fbfb946
* …
=> stable-2.2 | kata-deploy: Also provide "stable" & "latest" tags

src/agent/src/watcher.rs
We would only create the target when updating files. We need to make
sure that we create the target if the source is a directory. Without
this, we'll fail to start a container that utilizes an empty configmap,
for example.
Add unit tests for this.
Fixes: #2638
=> watcher: ensure we create target mount point for storage

src/runtime/virtcontainers/kata_agent.go
A discussion on the Linux kernel mailing list [1] exposed that virtiofsd makes a
core assumption that the file systems being shared are not accessible by any
non-privileged user. We currently create the `shared` directory in the sandbox
with the default `0750` permissions, which gives read and directory traversal
access to the group. There is no real good reason for a non-root user to access
the shared directory, and this is potentially dangerous.
Fixes: #2589
[1]: https://lore.kernel.org/linux-fsdevel/YTI+k29AoeGdX13Q@redhat.com/
=> virtiofs: Create shared directory with 0700 mode, not 0750

src/runtime/virtcontainers/kata_agent.go
A discussion on the Linux kernel mailing list [1] exposed that virtiofsd makes a
core assumption that the file systems being shared are not accessible by any
non-privileged user. We currently create the `shared` directory in the sandbox
with the default `0750` permissions, which gives read and directory traversal
access to the group. There is no real good reason for a non-root user to access
the shared directory, and this is potentially dangerous.
Fixes: #2589
Backports: #2590
[1]: https://lore.kernel.org/linux-fsdevel/YTI+k29AoeGdX13Q@redhat.com/
=> stable-2.2 | virtiofs: Create shared directory with 0700 mode, not 0750

.github/workflows/release.yaml
While releasing kata-containers 2.3.0-alpha1 we've hit some issues as
the tags attribution is done incorrectly.  We want an array of tags to
iterate over, but the currently code is just lost is the parenthesis.
This issue was introduced in a156288c1f8251bdd3231ec765d324f95a3da33e.
Fixes: #2725
=> workflows: Fix tag attribution

.github/workflows/release.yaml
While releasing kata-containers 2.3.0-alpha1 we've hit some issues as
the tags attribution is done incorrectly.  We want an array of tags to
iterate over, but the currently code is just lost is the parenthesis.
This issue was introduced in a156288c1f8251bdd3231ec765d324f95a3da33e.
Backports: #2727
Fixes: #2725
(cherry picked from commit 39dcbaa67258b6363f897dd558e81cda34366157)
=> stable-2.2 | workflows: Fix tag attribution

.github/workflows/release.yaml
There's a typo in the file that should receive the output of `cargo
vendor`.  We should use forward the output to `.cargo/config` instead of
`.cargo/vendor`.
This was introduced by 21c8511630fefecfcdc4af350ba25139dfac8fde.
Fixes: #2729
=> workflows: Fix the config file path for using vendored sources

.github/workflows/release.yaml
There's a typo in the file that should receive the output of `cargo
vendor`.  We should use forward the output to `.cargo/config` instead of
`.cargo/vendor`.
This was introduced by 21c8511630fefecfcdc4af350ba25139dfac8fde.
Backports: #2730
Fixes: #2729
(cherry picked from commit a525991c2c27c5da88d02104a7a83831769ef2ba)
=> stable-2.2 | workflows: Fix the config file path for using vendored sources

src/runtime/virtcontainers/virtiofsd_test.go
Initialize ctx with context.Background() instead of nil value.
Fixes: #2718
=> virtiofs: fix error report in TestVirtiofsdStart when go test running

tools/packaging/kernel/patches/5.10.x/0001-arm64-sparsemem-reduce-SECTION_SIZE_BITS.patch, tools/packaging/scripts/configure-hypervisor.sh
there are 2 issue to upgrade qemu version to 6.1.0 for arm:
1. using the current qemu config will lead to compile error: 
qemu/build/../tests/plugin/bb.c:134: undefined reference to `qemu_plugin_register_vcpu_tb_trans_cb'
qemu/build/../tests/plugin/bb.c:135: undefined reference to `qemu_plugin_register_atexit_cb'
qemu/build/../tests/plugin/bb.c:131: undefined reference to `qemu_plugin_register_vcpu_idle_cb'
collect2: error: ld returned 1 exit status
that's why I disable plugin in the first patch.
2. when memory hotplug, kernel will check the alignment size of start hotplug size which is at the end of nvidmm memory size. The current nvdimm size align with 128M, however, in kernel it's 1G which will lead to error.
that's why I port the upstreamed patch to reduce the memory alignment size to …
=> qemu: prepare to upgrade qemu version to 6.1.0 for arm

src/runtime/virtcontainers/qemu.go
It seems the client (crio) can send multiple requests to stop the Kata VM,
resulting a nil reference if the uid has already been cleaned up by a different thread.
Fixes #2743
=> runtime: fix nil reference in cleanup rootless user

src/agent/src/device.rs, src/agent/src/linux_abi.rs, src/agent/src/mount.rs, src/agent/src/rpc.rs, src/agent/src/uevent.rs, src/runtime/virtcontainers/clh.go, src/runtime/virtcontainers/device/config/config.go, src/runtime/virtcontainers/hypervisor_s390x.go, src/runtime/virtcontainers/kata_agent.go, src/runtime/virtcontainers/qemu.go, src/runtime/virtcontainers/qemu_arm64.go
As described in #683, kata-containers/agent#781, the PCI rescan in the agent code causes a bunch of problems (up to and including making VFIO devices unusable until the next *host* reboot).
This series is intended to avoid this by instead using the agent's uevent watching mechanism to wait for PCI devices to be "naturally" ready.
This is a (loose) forward port of both https://github.com/kata-containers/agent/pull/850 and https://github.com/kata-containers/runtime/pull/2981
=> Remove forced PCI rescans from agent

src/runtime/Makefile
modify the make script of the check-go-static, changing the `./cli` path to `./cmd/kata-runtime`
Fixes: #2765
=> runtime: fix the make check-go-static command error

src/runtime/.gitignore
Run tests sometimes generate pkg/containerd-shim-v2/monitor_address,
and `git status` will treat it as a new file.
Package containerd-shim-v2 has moved to pkg/containerd-shim-v2,
the monitor_address in .gitignore should be updated too.
Fixes: #2762
=> runtime: update .gitignore to ignore monitor_address file

src/runtime/cmd/kata-runtime/kata-check_arm64_test.go, src/runtime/cmd/kata-runtime/kata-check_ppc64le_test.go, src/runtime/cmd/kata-runtime/kata-check_s390x_test.go
Rectify the values of `testModuleData` with the correct
types in `TestCCCheckCLiFunction` in kata-check_(!x86)_test.go
Fixes: #2735
=> cmd: Fix mismatched types in testModuleData

src/runtime/virtcontainers/clh.go
Fix guest userland logging for Cloud Hypervisor (CLH) by:
- Disabling CLH's serial console.
- Enabling CLH's console.
- Booting the kernel specifying a para-virtualised console device.
Previously, CLH's serial console was used, resulting in only
kernel boot output and CLH's own debug output being logged.
Switching to using the CLH console enables userland logging: systemd and
it's jobs, such as the Kata agent.
Fixes: #2726.
=> clh: Enable guest userland output

src/runtime/cmd/kata-runtime/kata-check_generic_test.go, src/runtime/cmd/kata-runtime/kata-check_ppc64le_test.go
Accept and assert the return value in testSetCPUTypeGeneric.
Fixes: #2779
=> cmd: get return value for setCPUtype

tools/osbuilder/rootfs-builder/centos/config_ppc64le.sh
#2676: fixing centos gpg key url for ppc64le
=> #2676: fixing centos gpg key url for ppc64le

src/runtime/cmd/kata-runtime/kata-check_s390x_test.go, src/runtime/virtcontainers/hypervisor_arm64.go, src/runtime/virtcontainers/hypervisor_arm64_test.go, src/runtime/virtcontainers/qemu_arch_base.go, src/runtime/virtcontainers/qemu_arm64.go, src/runtime/virtcontainers/qemu_arm64_test.go, src/runtime/virtcontainers/utils/utils_linux_ppc64le.go
Follow-up of #2237 for s390x -- field alignment isn't always minimal
Depends-on: github.com/kata-containers/tests#4047
Fixes: #2773
=> runtime: Fix !x86 static checks

src/agent/rustjail/src/container.rs
The CRI-O integration test suite has two tests that fail because they search for
"not found" in the error message, but we emit "is not exist".
Change the error message to match the expectations of the test suite.
Fixes: #2036
Reported-by: Julien Ropé <jrope@redhat.com>
=> agent: Make wording of error message match CRI-O test suite

versions.yaml
Let's test our `main` branch against the latest version of k8s.  In
order to do the bump, let's also update critools and CRI-O version
accordingly.
=> Update k8s, critools, and CRI-O to their 1.22 release

src/runtime/cmd/kata-runtime/kata-env.go, src/runtime/virtcontainers/qemu_arch_base.go
Show available guest protections in the `kata-runtime env` output. Also bump the `formatVersion`.
Fixes: #1982
Signed-off-by: Yujia Qiao <rapiz3142@gmail.com>
=> cli: Show available guest protection in env output

src/runtime/pkg/containerd-shim-v2/stream_test.go
When running the TestIoCopy test, on some occasions, the test
runs too quick, and closes the stdin pipe before the ioCopy()
routine start to read from it. This causes a SIGSEGV error.
To fix this issue, I am adding additional read/write tests before
closing the pipes. As the read operation waits for the writer to
be done, this actually synchronizes the threads and make sure
the final tests (with closed pipes) works as expected.
Fixes: #2042
=> test: Fix random failure for TestIoCopy

src/runtime/Makefile
Add `-failfast` option to let test exit on error, but the `-failfast` option
can't cross package, so there is a for loop used to test on all packages
in src/runtime, and the parallel number is set to 1, this may lead test
to be slow.
Fixes: #1997
=> runtime: add fast-test to let test exit on error

src/runtime/virtcontainers/container.go, src/runtime/virtcontainers/mount.go
Current handling of read-only mounts is a little tricky.
However, a clearer solution can be used here:
1. make a private ro bind mount at privateDest to the mount source
2. make a bind mount at mountDest to the mount created in step 1
3. umount the private bind mount created in step 1
One important aspect is that the mount in step 2 is duplicated from
the one we created in step 1. So the MS_RDONLY flag is properly
preserved in all mounts created in the propagtion.
Fixes: #2205
Signed-off-by: Yujia Qiao <rapiz3142@gmail.com>
=> virtcontainers: simplify read-only mount handling

ci/install_libseccomp.sh
This PR aims to primarily fix `ci/install_libseccomp` (see #2932) which fails if the environment has the `DESTDIR` variable set. While I am here I provided a small improvement too.
=> ci/install_libseccomp: Fix libseccomp build and misc improvement

src/trace-forwarder/README.md, tools/agent-ctl/Makefile, tools/agent-ctl/README.md, tools/agent-ctl/src/client.rs, tools/agent-ctl/src/main.rs, tools/agent-ctl/src/rpc.rs, tools/agent-ctl/src/types.rs
Allow the `agent-ctl` tool to connect to a Hybrid VSOCK hypervisor such
as Cloud Hypervisor or Firecracker.
Fixes: #2914.
=> agent-ctl: Update for Hybrid VSOCK

tools/osbuilder/image-builder/Dockerfile
Currently the image-builder image is built from `fedora:latest` and
this is error-prone as any update of the base image can lead to
breakage. Instead let's create the image from Fedora 34, which is the
last known version to build fine.
Fixes #2960
=> osbuilder: build image-builder image from Fedora 34

src/runtime/Makefile
There are some issues with Makefile for runtime:
- default target can't be used as a dependent of other targets.
- empty target `check`
And also add two targets for locally development/tests.
- lint: run golangci-lint
- pre-commit: run lint and test
Fixes: #2942
=> runtime: Enhancement for Makefile

src/agent/rustjail/Cargo.toml, src/agent/rustjail/src/container.rs, src/agent/rustjail/src/lib.rs, src/agent/rustjail/src/seccomp.rs
Re-enable seccomp feature on aarch64 because CI is ready
by https://github.com/kata-containers/tests/pull/4124.
This reverts commit 42add7f201cf082d0d06d676c5cf20e6088ac2fb.
Fixes: #2939
=> agent: "Revert agent: Disable seccomp feature on aarch64 temporarily"

pkg/logging/Cargo.toml, src/agent/Cargo.toml, src/agent/vsock-exporter/Cargo.toml, src/trace-forwarder/Cargo.toml
Raise the `slog` maximum log level feature for release code from `info`
to `debug` by changing the `slog` maximum level features in the shared
`logging` crate. This allows the consumers of the `logging` crate (the
agent, the `trace-forwarder` and the `agent-ctl` tool) to produce debug
output when their debug options are enabled. Currently, those options
will essentially be a NOP (unless using a debug version of the code).
Testing showed that setting the `slog` maximum level features in the
rust manifest files for the consumers of the `logging` crate has no
impact: those values are ignored, so they have been removed and replaced
with a comment stating the levels are set in the `logging` crate.
Fixes: #2966.
=> logging: Enable agent debug output for release builds

tools/osbuilder/image-builder/Dockerfile, versions.yaml
- Update CCv0 to use the new confidential containers fork of containerd
- Start using the current-CCv0 branch
Fixes: #2947
=> CCv0 | version: Update CCv0 fork of containerd used

src/runtime/pkg/katautils/create.go, src/runtime/pkg/katautils/hook.go, src/runtime/pkg/katautils/katatrace/tracing.go, src/runtime/virtcontainers/kata_agent.go, src/runtime/virtcontainers/network.go, src/runtime/virtcontainers/qemu.go, src/runtime/virtcontainers/sandbox.go
In later versions of OpenTelemetry label.Any() is deprecated. Change
AddTag() to accept only strings for values. Add AddTagMarshal() which
accepts an interface as a value and formats it for output.
Change names AddTag and AddTagMarshal to AddTags and AddTagsMarshal
respectively. Instead of taking a key and value as arguments, change
them to use a map of string keys and values, or in the case of
AddTagsMarshal, a map of string keys and interface values.
I chose a map to represent the tags for several reasons:
1. For consistency, since we already use a map of span tags for each
subsystem,
2. To keep these functions similar to how we accept tags when creating a
span, which uses maps,
3. To hopefully reduce possible errors by developers adding tags to
spans. For example, an alternative is a …
=> tracing: Accept multiple dynamic tags

src/runtime/pkg/containerd-shim-v2/service.go
We only added span.End() in the main process of the shim2 Shutdown method.
The "Shutdown" span would keep alive, when the containers number is not 0.
This PR make sure the "Shutdown" trace span have a correct end.
Fixes: #2930
=> runtime# make sure the "Shutdown" trace span have a correct end

tools/osbuilder/image-builder/Dockerfile
Currently the image-builder image is built from `fedora:latest` and
this is error-prone as any update of the base image can lead to
breakage. Instead let's create the image from Fedora 34, which is the
last known version to build fine.
Fixes #2960
(cherry picked from commit a239a38f457a15e96c5aa1e30a800227324671f6)
=> stable-2.2 | osbuilder: build image-builder image from Fedora 34

Makefile, pkg/logging/Makefile, pkg/logging/src/lib.rs, src/agent/Makefile, src/trace-forwarder/Makefile, tools/agent-ctl/Makefile, utils.mk
Ensure the tests in the local `logging` crate are run for all consumers
of it.
Additionally, add a new test which checks that output is generated by a
range of different log level `slog` macros. This is designed to ensure
debug level output is always available for the consumers of the
`logging` crate.
Fixes: #2969.
=> logging: Always run crate tests

src/agent/rustjail/src/container.rs
Got wrong created time of container after an exec
this commit will fix this problem.
Fixes: #2994
=> rustjail: Fix created time of container

docs/how-to/ccv0.sh, tools/osbuilder/rootfs-builder/rootfs.sh, tools/osbuilder/rootfs-builder/ubuntu/Dockerfile-aarch64.in, tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in, tools/osbuilder/rootfs-builder/ubuntu/config.sh, tools/osbuilder/scripts/lib.sh, versions.yaml
When the environment variable $AA_KBC is set, skopeo, umoci, and
attestation-agent (with that KBC) are built inside the guest build
container and installed to the guest rootfs. The respective build- and
runtime dependencies are added. This respects the (existing) $LIBC
variable (gnu/musl) and avoids issues with glibc mismatches. (musl
depends on https://github.com/containers/attestation-agent/pull/20)
At this time, only Ubuntu is supported, due to issues with building
Golang applications on Fedora/CentOS.
Fixes: #2907
/cc @sameo @fitzthum @davidhay1969 @bpradipt
=> osbuilder: Build attestation-agent and friends

src/runtime/virtcontainers/qemu_arch_base.go, src/runtime/virtcontainers/qemu_arm64_test.go
Protection types like tdxProtection or seProtection were marked nolint,
remove this. As a side effect, ARM needs dummy tests for these.
Fixes: #2801
obviously I couldn't test this just yet
=> virtcontainers: Lint protection types

.github/workflows/release.yaml
We need to explicitly call `${GOPATH}/bin/yq` that is installed by `ci/install_yq.sh`.
Fixes: #3014
=> release: Use ${GOPATH}/bin/yq for upload-libseccomp-tarball action

.github/workflows/static-checks.yaml, versions.yaml
According to https://endoflife.date/go golang 1.15 is not supported
anymore.  Let's remove it from out tests, add 1.17.x, and bump the
newest version known to work when building kata to 1.17.3.
Fixes: #3016
=> versions: bump golang to 1.17.x

.github/workflows/release.yaml
We need to explicitly call `${GOPATH}/bin/yq` that is installed by `ci/install_yq.sh`.
Backports: #3015 
Fixes: #3014
(cherry picked from commit 34307235942acd838f774c254c38af017b508d9b)
=> stable-2.3 | release: Use ${GOPATH}/bin/yq for upload-libseccomp-tarball action

src/runtime/virtcontainers/pkg/oci/utils.go, src/runtime/virtcontainers/pkg/oci/utils_test.go
Functions EnvVars and GetOCIConfig in runtime/virtcontainers/pkg/oci/utils.go
are not used anymore.
Fixes: #3029
=> runtime: delete not used codes

src/agent/src/namespace.rs
Improve unit test coverage for src/namespace.rs for Kata 2.0 agent
Fixes: #289
=> agent/src: improve unit test coverage for src/namespace.rs

.github/workflows/static-checks.yaml, versions.yaml
According to https://endoflife.date/go golang 1.15 is not supported
anymore.  Let's remove it from out tests, add 1.17.x, and bump the
newest version known to work when building kata to 1.17.3.
Fixes: #3016
(cherry picked from commit 395638c4bcc88532ba5ab8561095b2c7c8548e26)
=> stable-2.3 | versions: bump golang to 1.17.x

tools/agent-ctl/src/client.rs
Since the `utils::get_option` interface is modified,
PullImage needs to adapt to this modification in CCv0 branch.
=> CCv0|agent-ctl: fix compile error

docs/how-to/run-kata-with-k8s.md
CRI-O deployment documentation was quite outdated, giving info from the
`1.x` era.  Let's update this to reflect what we currently have.
Fixes: #2498
=> Update CRI-O documentation

src/runtime/virtcontainers/clh.go, src/runtime/virtcontainers/monitor.go
The thread monitor will check if the agent and the VMM are alive every
second in a blocking thread. The Cloud hypervisor API server is
single-threaded, if the monitor does a `check()`, while a slow request
is still in progress, the monitor check() method will timeout. The
monitor thread will stop all the shim-v2 execution.
This commit modifies the monitor thread to make it check the status of
the hypervisor after 5 seconds. Additionally, the `check()` method from
cloud-hypervisor will use the method `clh.isClhRunning(timeout)` with a
10 seconds timeout. The monitor function does no timeout, so even if
`hypervisor.check()` takes more 10 seconds, the isClhRunning method
handles errors doing a VmmPing and retry in case of errors until the
timeout is reached.
Reduce the time to the next check …
=> clh: Fix race condition that prevent start pods 

src/runtime/virtcontainers/endpoint.go, src/runtime/virtcontainers/endpoint_test.go, src/runtime/virtcontainers/macvlan_endpoint.go, src/runtime/virtcontainers/macvlan_endpoint_test.go, src/runtime/virtcontainers/network.go, src/runtime/virtcontainers/persist.go, src/runtime/virtcontainers/persist/api/network.go, src/runtime/virtcontainers/qemu_arch_base.go, src/runtime/virtcontainers/qemu_arch_base_test.go
The fact that we need to "bridge" the endpoint is a bit irrelevant. To
be consistent with the rest of the endpoints, let's just call this
"macvlan"
Note -- this doesn't introduce any functional changes.
Fixes: #3050
=> macvlan: drop bridged part of name

tools/packaging/scripts/configure-hypervisor.sh
While building snap, static qemu is considered. Disable libudev
as it doesn't have static libraries on ppc64le.
Fixes: #3002
=> qemu: fix snap build on ppc64le

src/runtime/virtcontainers/factory/template/template_test.go
d5a18173b98cabdaae082f42a4dc3f84b3821821 virtcontainers: fix failing template test on ppc64le
when #2921 gets merged
=> stable-2.3: virtcontainers: fix failing template test on ppc64le

tools/packaging/scripts/configure-hypervisor.sh
44e757a04b  qemu: fix snap build by disabling libudev
once #3003 is merged
=> stable-2.3: disable libudev when building static QEMU

src/agent/rustjail/src/container.rs
When the container didn't had a tty console, it would be in a same
process group with the kata-agent, which wasn't expected. Thus,
create a new session for the container process.
Fixes: #3063
=> agent: fix the issue of missing create a new session for container

tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup-stable.yaml, tools/packaging/kata-deploy/kata-deploy/base/kata-deploy-stable.yaml
stable-2.3 was the first time we branched the repo since
43a72d76e2520ae044335b9f1dbf54c12363f54b was merged.  One bit that I
didn't notice while working on this, regardless of being warned by
@amshinde (sorry!), was that the change would happen on `main` branch,
rather than on the branched `stable-2.3` one.
In my mind, the workflow was:
* we branch.
* we do the changes, including removing the files.
* we tag a release.
However, the workflow actually is:
* we do the changes, including removing the files.
* we branch.
* we tag a release.
A better way to deal with this has to be figured out before 2.4.0 is
out, but for now let's just re-add the files back.
Fixes: #3067
=> kata-deploy: Add back stable & latest tags

src/agent/src/device.rs, src/agent/src/pci.rs
The Kubernetes SR-IOV plugin communicates which virtual functions to use to container payloads via environment variables giving PCI addresses.  This works fine with traditional containers, however, with Kata the devices will probably have different PCI addresses within the VM.
Therefore we need to update the environment variables to match the guest rather than the host toplogy.
While we're working on this, make a number of cleanups to the adjustments we need to make to the OCI specification for host vs. guest differences.
=> Update k8s SR-IOV plugin environment variables to work properly with Kata

.github/workflows/kata-deploy-test.yaml
Is the past few releases we ended up hitting issues that could be easily
avoided if `/test_kata_deploy` would use HEAD instead of a specific
tarball.
By the end of the day, we want to ensure kata-deploy works, but before
we cut a release we also want to ensure that the binaries used in that
release are in a good shape.  If we don't do that we end up either
having to roll a release back, or to cut a second release in a really
short time (and that's time consuming).
Note: there's code duplication here that could and should be avoided,b
but I sincerely would prefer treating it in a different PR.
Fixes: #3001
=> kata-deploy: Ensure we test HEAD with `/test_kata_deploy`

.github/workflows/kata-deploy-test.yaml
Commit 3c9ae7f made /test_kata_deploy run
against HEAD, but it also mistakenly removed all the checks that ensure
/test_kata_deploy only runs when explicitly called.
Mea culpa on this, and let's add the tests back.
Fixes: #3101
=> workflows: Add back the checks for running test-kata-deploy

docs/install/README.md, tools/packaging/kata-deploy/README.md
This PR moves kata deploy installation instructions to docs/install
folder, update wording and document format, adds an index to general
installation documentat
Fixes: #2450
Signed-off-by: João Vanzuita <joao.vanzuita@de.bosch.com>
=> docs: make kata-deploy more visible

src/agent/Makefile
The unrecognized option: 'deny-warnings' args caused `make optimize` failed.
Fixed the Makefile of the agent project, make sure the `make optimize` command
execute correctly. This PR modify the rustc args from '--deny-warnings' to
'--deny warnings'.
Fixes: #3104
=> agent: fixed the `make optimize` bug

src/runtime/pkg/containerd-shim-v2/service.go
os.Exit() will terminate program immediately, the defer functions
won't be executed, so we add defer functions again before os.Exit().
Refer to https://pkg.go.dev/os#Exit
Fixes: #3059
=> shimv2/service: fix defer funtions never run with os.Exit()

src/agent/src/config.rs, src/agent/src/image_rpc.rs
Use the Attestation Agent as a keyprovider for Skopeo/ocicrypt when we pull the container from inside the guest. This requires starting the Attestation Agent, creating an ocicrypt config file, and amending the arguments of the skopeo copy command.
=> CCv0: Attestation Agent Integration

src/agent/src/device.rs, src/agent/src/main.rs, src/agent/src/metrics.rs, src/agent/src/mount.rs, src/agent/src/namespace.rs, src/agent/src/rpc.rs, src/agent/src/sandbox.rs, src/agent/src/util.rs, src/agent/src/watcher.rs, tools/agent-ctl/src/main.rs
Replace some `unwrap()` and `expect()` calls with code to return the
error to the caller.
Fixes: #3011.
=> agent: Remove some unwrap and expect calls

src/agent/rustjail/src/mount.rs
Function parameters in test config is not used. This
commit will add underscore before variable name
in test config.
Fixes: #3091
=> agent: clear cargo test warnings

tools/osbuilder/dockerfiles/QAT/Dockerfile
kernel compiled in fedora 35 (latest) is not working, following error
is reported:
```
qemu-system-x86_64: Error loading uncompressed kernel without PVH ELF
Note
```
Build QAT kernel in fedora 34 container to fix it
fixes #3135
cc @eadamsintel @GabyCT
=> tools/osbuilder: build QAT kernel in fedora 34

src/agent/src/sandbox.rs
Some tests in sandbox.rs need root user to run, because they need create
directories under /run/agent directories, actually this is a limit
that shouldn't be there. By using a temp directory for test containers
will not need run tests as root user.
Fixes: #3122
=> agent: use temp directory for test containers

.github/workflows/kata-deploy-test.yaml
Let's take advantage of the "is-organization-member" action and only
allow members who are part of the `kata-containers` organization to
trigger `/test_kata_deploy`.
One caveat with this approach is that for the user to be considered as
part of an organization, they **must** have their "Organization
Visibility" configured as Public (and I think the default is Private).
This was found out and suggested by @jcvenegas!
Fixes: #3130
=> workflows: only allow org members to run `/test_kata_deploy`

tools/osbuilder/rootfs-builder/centos/config.sh, tools/osbuilder/rootfs-builder/debian/config.sh, tools/osbuilder/rootfs-builder/fedora/config.sh, tools/osbuilder/rootfs-builder/gentoo/config.sh, tools/osbuilder/rootfs-builder/suse/config.sh, tools/osbuilder/rootfs-builder/ubuntu/config.sh
So that the debug console is more useful. In the meantime, remove
iptables as it is not used by kata-agent any more.
=> osbuilder: add coreutils to guest rootfs

tools/osbuilder/dockerfiles/QAT/Dockerfile
kernel compiled in fedora 35 (latest) is not working, following error
is reported:
```
qemu-system-x86_64: Error loading uncompressed kernel without PVH ELF
Note
```
Build QAT kernel in fedora 34 container to fix it
fixes #3135
(cherry picked from commit 857501d8dd7d6c8469c13920d5fad62a47be3219)
=> stable-2.3 | tools/osbuilder: build QAT kernel in fedora 34

.github/workflows/kata-deploy-test.yaml
Let's bring to the stable-2.3 branches the following fixes:
* kata-deploy: Ensure we test HEAD with `/test_kata_deploy (#3001)
* workflows: Add back the checks for running test-kata-deploy (#3101)
* workflows: only allow org members to run `/test_kata_deploy` (#3130)
=> stable-2.3 | backport kata-deploy fixes / improvements

tools/osbuilder/rootfs-builder/centos/config.sh, tools/osbuilder/rootfs-builder/debian/config.sh, tools/osbuilder/rootfs-builder/fedora/config.sh, tools/osbuilder/rootfs-builder/gentoo/config.sh, tools/osbuilder/rootfs-builder/suse/config.sh, tools/osbuilder/rootfs-builder/ubuntu/config.sh
So that the debug console is more useful. In the meantime, remove
iptables as it is not used by kata-agent any more.
=> stable-2.3 | osbuilder: add coreutils to guest rootfs

tools/osbuilder/image-builder/image_builder.sh, tools/osbuilder/initrd-builder/initrd_builder.sh, tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
1. install cpio package before building rootfs-initrd image
2. add `pipefail` check to the script
Fixes: #3144
=> osbuilder: fix missing cpio package when building rootfs-initrd image

tools/osbuilder/image-builder/image_builder.sh, tools/osbuilder/initrd-builder/initrd_builder.sh, tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
1. install cpio package before building rootfs-initrd image
2. add `pipefaili;errexit` check to the scripts
Fixes: #3144
(cherry picked from commit 8ee67aae4ff02526b65ba669a954fdf2b5eb1223)
=> stable-2.3 | osbuilder: fix missing cpio package when building rootfs-initrd image

tools/packaging/guest-image/build_image.sh, tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile, tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh, versions.yaml
This is still a draft, but it is supposed to shine a little light on how we might deploy CCv0 along with the [operator payload image config](https://github.com/confidential-containers/operator/tree/ccv0-demo/demo/payload-image).
The image would be built with something like `SKOPEO_UMOCI=yes AA_KBC=offline_fs_kbc INCLUDE_ETC="$(realpath aa-offline_fs_kbc-keys.json) $(realpath kata-config.toml)" make` (files must be in repo so they're included in the build container).
@sameo do you think this is the way to go at all?
/cc @bpradipt
=> ccv0: Support kata-deploy

src/agent/Cargo.lock, src/agent/Cargo.toml, src/agent/rustjail/Cargo.toml, src/agent/rustjail/src/cgroups/fs/mod.rs, src/agent/rustjail/src/container.rs, src/agent/rustjail/src/mount.rs, src/agent/rustjail/src/pipestream.rs, src/agent/rustjail/src/sync.rs, src/agent/rustjail/src/validator.rs, src/agent/src/console.rs, src/agent/src/device.rs, src/agent/src/netlink.rs, src/agent/src/rpc.rs, src/agent/src/uevent.rs, src/agent/vsock-exporter/Cargo.toml, src/trace-forwarder/Cargo.lock, tools/agent-ctl/Cargo.lock
Run `cargo update` to update to the latest crate dependency versions.
The agent is an application so this includes expanding the partially
specified semvers to full semver values for the following crates,
which makes those crates consistent with the other agent dependencies:
- `futures`
- `regex`
- `scan_fmt`
- `tokio`
Also includes:
- `cargo update` lockfiles updates for the `agent-ctl` tool and the `trace-forwarder`.
- An update to the latest `nix` crate version.
Fixes: #3124.
=> Update rust crate versions

src/runtime/config/configuration-acrn.toml.in, src/runtime/config/configuration-clh.toml.in, src/runtime/config/configuration-fc.toml.in, src/runtime/config/configuration-qemu.toml.in
This PR updates the comments in the configuration.toml to point to
the current kata containers repository instead of the kata 1.x.
Fixes #3163
=> runtime: Update comments for virtcontainers to use kata 2.0

.github/workflows/static-checks.yaml, src/agent/Cargo.lock, src/agent/Cargo.toml, src/agent/src/image_rpc.rs, src/agent/src/uevent.rs, tools/osbuilder/rootfs-builder/alpine/Dockerfile.in, tools/osbuilder/rootfs-builder/clearlinux/Dockerfile.in, versions.yaml
This PR try to use rust crate to download container image and decrypt with ocicrypt-rs crate.
We keep current skopeo solution with use_skopeo flag, but if upstream is agree, we can delete skopeo related code.
BTW this PR also depends on https://github.com/kata-containers/kata-containers/pull/2911 which will pass the `kbc_name` and `kbs_uri` to ocicrypt decrypt config
Private registry is supported with current rustified image download implementation, but we have one limitation is don't support container image manifiest lists and we will focuse on implementing new image-rs crate to address all gaps.
Fixes: #3041 
@sameo @fitzthum @stevenhorsman
=> CCv0: Rustify image download

src/agent/rustjail/src/mount.rs, src/agent/src/watcher.rs
In function `update_target`, if the updated source is a directory,
we should create the corresponding directory.
Fixes: #3140
=> agent: copy empty directories for watchable-bind mounts

docs/Limitations.md
This PR removes the information about docker swarm and docker compose
as currently for kata 2.0 we have not support for docker swarm and docker compose and the links and references that the document is referring are currently not part of kata 2.0
Fixes #3174
=> docs: Update limitation document regarding docker swarm

src/agent/rustjail/src/mount.rs, src/agent/src/network.rs
1.57 rust toolchain introduces additional lints, which highlight some unread fields in the agent.
Let's clean this up!
=> Cleanup some unused variables, definitions

tools/packaging/static-build/shim-v2/install_go.sh
add help info for force install, and remove unused '-p' option.
Fixes: #3168
=> packaging: add help information for '-f' option in install_go.sh

tools/osbuilder/rootfs-builder/rootfs.sh, tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in, tools/osbuilder/rootfs-builder/ubuntu/config.sh, tools/osbuilder/rootfs-builder/ubuntu/rootfs_lib.sh, tools/osbuilder/scripts/lib.sh
1.Integrate EAA KBC into CCv0 ubuntu rootfs image. 
2.And also fix the build failure if build rootfs image with "AA_KBC=eaa_kbc" option.
=> CCv0|osbuilder: integrate AA's EAA KBC into ubuntu rootfs image

src/runtime/virtcontainers/network.go
vhost-net is disabled in the rootless hypervisor. Because I reused the rootless code base for rootless kata runtime, which has been abandoned since kata 2.0. This change removes the disable logic under rootless flag. 
Fixes #3182
=> runtime: enable vhost-net for rootless hypervisor

docs/how-to/ccv0.sh, docs/how-to/how-to-build-and-test-ccv0.md, tools/osbuilder/rootfs-builder/README.md, tools/osbuilder/rootfs-builder/rootfs.sh, tools/osbuilder/rootfs-builder/ubuntu/config.sh, tools/osbuilder/scripts/lib.sh, tools/packaging/guest-image/build_image.sh, tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
With the new rust image pull service skopeo we can parameterise whether to build
and install skopeo and turn it off by default if we don't need
signature verification support
Fixes: #3170
=> Stop skopeo being installed by default 

tools/packaging/static-build/shim-v2/Dockerfile
add `git` package to the shim-v2 build image
Fixes: #3196
=> packaging: Fix missing commit message in building kata-runtime

src/runtime/virtcontainers/network.go
vhost-net is disabled in the rootless kata runtime feature, which has been abandoned since kata 2.0.
I reused the rootless flag for nonroot hypervisor and would like to enable vhost-net.
Fixes #3182
(cherry picked from commit b3bcb7b2516f05176985477f5af2bee2ddf6b7e7)
=> stable-2.3 | runtime: enable vhost-net for rootless hypervisor

tools/packaging/static-build/shim-v2/Dockerfile
add `git` package to the shim-v2 build image
Fixes: #3196
Backport PR: #3197
=> stable-2.3 | packaging: Fix missing commit message in building kata-runtime

versions.yaml
ppc64le & s390x have no (well supported) musl target for Rust,
therefore, the agent must use glibc and cannot use Alpine. Specify
Ubuntu as the distribution to be used for initrd.
Fixes: #3212
/cc @devimc @Amulyam24
=> versions: Use Ubuntu initrd for non-musl archs

snap/snapcraft.yaml
Build initrd or image rootfs using the distro name specified
in the versions.yaml
fixes #3208
cc @jodh-intel @Jakob-Naucke @jongwu
=> snap: read initrd and image distros from version.yaml

src/runtime/virtcontainers/qemu.go
If shared_fs is set to virtio-9p, the virtiofsd is not started,
so there is no need to stop it.
Fixes: #3219
=> runtime: only call stopVirtiofsd when shared_fs is virtio-fs

src/runtime/virtcontainers/kata_agent.go
Normally the span name should be the same as function
name, so chagne `StopVM` to `stopSandbox`.
Fixes: #3217
=> runtime: correct span name for stopSandbox function

versions.yaml
ppc64le & s390x have no (well supported) musl target for Rust,
therefore, the agent must use glibc and cannot use Alpine. Specify
Ubuntu as the distribution to be used for initrd.
Fixes: #3212
Backport of #3213
=> Backport versions: Use Ubuntu initrd for non-musl archs
