kata-containers/kata-containers

docs/code-pr-advice.md

Unit-Test-Advice.md was moved to kata-containers repo but URLs pointing
to that document were not updated. This patch updates these URLs.
fixes #3240

docs: fix check-markdown test

---

src/runtime/virtcontainers/factory/factory.go
src/runtime/virtcontainers/factory/template/template.go

Some new attributes are added to hypervisor config:
- VMStorePath
- RunStorePath
- SharedPath
These attributes should be handled in two places:
- reset when check the new hypervisor's config is suitable
to the base config.
- copy from new hypervisor's config when create new VM
Fixes: #3193

runtime/template: Handling new attributes for hypervisor config

---

tools/osbuilder/rootfs-builder/alpine/Dockerfile.in
tools/osbuilder/rootfs-builder/alpine/config.sh
tools/osbuilder/rootfs-builder/alpine/rootfs_lib.sh
versions.yaml

#2399 partially reverted #418, missing on returning to bootstrapping a
rootfs with `apk.static` instead of copying the entire root, which can
result in drastically larger (more than 10x) images.
Fixes: #3216

osbuilder: Revert to using apk.static for Alpine

---

tools/osbuilder/image-builder/image_builder.sh
tools/osbuilder/rootfs-builder/rootfs.sh

Use the same runtime used for docker/podman run also for
docker/podman build

osbuilder: be runtime consistent with podman build

---

tools/osbuilder/image-builder/image_builder.sh

The help information of '-f' option is missing, and same issue
with 'BLOCK_SIZE' env variables, fix it in usage() function.
Fixes: #3231

image_build: add help info for '-f' option and 'BLOCK_SIZE' env.

---

tools/osbuilder/rootfs-builder/alpine/Dockerfile.in
tools/osbuilder/rootfs-builder/alpine/config.sh
tools/osbuilder/rootfs-builder/alpine/rootfs_lib.sh
versions.yaml

Backport of #3222. For this, we're using the existing Alpine 3.13 rather than the upgrade to 3.15.
/cc @fidencio @skaegi

Backport osbuilder: Revert to using apk.static for Alpine

---

versions.yaml

This is a bug release from Cloud Hypervisor addressing the following issues:
1. Networking performance regression with virtio-net;
1. Limit file descriptors sent in vfio-user support;
1. Fully advertise PCI MMIO config regions in ACPI tables;
1. Set the TSS and KVM identity maps so they don't overlap with firmware RAM;
1. Correctly update the DeviceTree on restore.
Details can be found: https://github.com/cloud-hypervisor/cloud-hypervisor/releases/tag/v20.1
Fixes: #3262

Upgrade to Cloud Hypervisor v20.1

---

tools/osbuilder/image-builder/image_builder.sh
tools/osbuilder/rootfs-builder/rootfs.sh

Now if no options/arguments specified, the shell scripts will return an error:
ERROR: Invalid rootfs directory: ''
This commit will show usage if no options/arguments specified.
Fixes: #3256

osbuilder: show usage if no options/arguments specified

---

tools/packaging/kata-deploy/scripts/kata-deploy.sh

As containerd can properly run without having a existent
`/etc/containerd/config.toml` file (it'd run using the default
cobnfiguration), let's explicitly create the file in those cases.
This will avoid issues on ammending runtime classes to a non-existent
file.
Fixes: #3229
Tested-by: Jakob Naucke <jakob.naucke@ibm.com>

kata-deploy: Deal with empty containerd conf file

---

versions.yaml

This is a bug release from Cloud Hypervisor addressing the following
issues: 1) Networking performance regression with virtio-net; 2) Limit
file descriptors sent in vfio-user support; 3) Fully advertise PCI MMIO
config regions in ACPI tables; 4) Set the TSS and KVM identity maps so
they don't overlap with firmware RAM; 5) Correctly update the DeviceTree
on restore.
Details can be found: https://github.com/cloud-hypervisor/cloud-hypervisor/releases/tag/v20.1
Fixes: #3262
(cherry picked from commit bbfb10e16998f3ff3273083cf60875a7e9ce6fa2)

stable-2.3 | versions: Upgrade to Cloud Hypervisor v20.1

---

docs/code-pr-advice.md

Allow using `expect()` for `Mutex.lock()` because it is almost
unrecoverable if failed in the lock acquisition
Fixes: #3285
Signed-off-by: Zack <zmlcc@linux.alibaba.com>

docs: Update code PR advice document

---

src/runtime/pkg/katautils/katatrace/tracing.go

Add span name to logging error to help with debugging when the context
is not set before the span is created.
Fixes #3289

tracing: Add span name to logging error

---

docs/Stable-Branch-Strategy.md

On the last architecture committee meeting, the one held on December
14th 2021, we reached the agreement that minor releases will be cut once
every 16 weeks (instead of 12), and that patch releases will be cut
every 4 weeks (instead of 3)
Fixes: #3298

docs: Update the stable branch strategy

---

docs/README.md
docs/Upgrading.md
docs/design/README.md
docs/design/architecture/README.md
docs/design/architecture/background.md
docs/design/architecture/example-command.md
docs/design/architecture/guest-assets.md
docs/design/architecture/history.md
docs/design/architecture/kubernetes.md
docs/design/architecture/networking.md
docs/design/architecture/storage.md
docs/design/virtualization.md
snap/README.md
src/agent/README.md
src/runtime/README.md
src/runtime/virtcontainers/README.md

Move the architecture document to separate `docs/design/architecture/` directory and split some of the main sections into separate files to make the main file smaller and more manageable.
Fixes: #3246.

Split architecture doc into separate files

---

ci/install_libseccomp.sh

All CI jobs are failing as www.gnu.org is down, so switch to a mirror
for the time being.
Fixes: #3314.

CI: Switch to a mirror as gnu.org is down

---

tools/packaging/static-build/qemu/Dockerfile

This PR changes the method to clone the QEMU source tree in order to speed up its build. It is used the `--depth=1` argument of `git` to fetch just the needed objects.
While here I change the way that the submodules are cloned. 
Fixes #3291

packaging/qemu: partial git clone

---

.github/workflows/deploy-ccv0-demo.yaml
docs/how-to/data/confidential-agent-config.toml.in
tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
tools/packaging/kata-deploy/scripts/kata-deploy.sh

docs: Create sample config for confidential agent
Basic config, no debug endpoints, no exec/reseed. Uses the
`$AA_KBC_PARAMS` variable to be used with `envsubst`.
---
github: Add workflow for deploying a CCv0 demo
using the offline FS KBC [1] and keys from the SSH demo [2]. The
workflow is adapted from `main:kata-deploy-test.yaml`. The image
deployed here is _not_ for a trusted execution environment.
[1] - https://github.com/confidential-containers/attestation-agent/tree/main/src/kbc_modules/offline_fs_kbc
[2] - https://github.com/confidential-containers/documentation/tree/main/demos/ssh-demo
Fixes: #3198
---
Here is a diff to `kata-deploy-test.yaml` to make this PR a little more …

github: Add workflow for deploying a CCv0 demo

---

tools/osbuilder/rootfs-builder/alpine/Dockerfile.in

It seems the lack of protoc in the alpine containers is causing issues
with some of our CIs, such as the VFIO one.
Fixes: #3323

osbuilder: Add protoc to the alpine container

---

tools/packaging/scripts/configure-hypervisor.sh

Commit 112ea25859d6 disabled libudev for static builds because it was
breaking snap. It turns out that the only users of libudev in QEMU are
qemu-pr-helper and USB. Kata already disables USB and doesn't use
qemu-pr-helper. Disable libudev for all builds if QEMU supports it, i.e.
version 5.2 or newer.
Fixes #3078

qemu: Disable libudev for QEMU 5.2 and newer

---

tools/osbuilder/Makefile

Currently the versions.txt in rootfs-builder dir is already removed,
so avoid to copy it in list of helper files.
Fixes: #3267

osbuilder: avoid to copy versions.txt which already deprecated

---

utils/kata-manager.sh

In `utils/kata-manager.sh`, we download the first asset listed for the
release, which used to be the static x86_64 tarball. If that happened to
not match the system architecture, we would abort. Besides that logic
being invalid for !x86_64 (despite not distributing other tarballs at
the moment), the first asset listed is also not the static tarball any
more, it is the vendored source tarball. Retrieve all _static_ tarballs
and select the appropriate one depending on architecture.
Fixes: #3254

kata-manager: Retrieve static tarball

---

tools/packaging/kernel/configs/README.md

- `fragments` in backticks
- s/perfoms/performs/
Fixes: #3338

docs: Fix kernel configs README spelling errors

---

docs/design/host-cgroups.md
src/runtime/virtcontainers/README.md

renamed branch `master` to `main`
Fixes: #3336
Signed-off-by: Jakob Naucke jakob.naucke@ibm.com
---
Fix outdated link in virtcontainers readme

docs: Fix outdated links

---

src/agent/src/mount.rs

We already have a `mount_path` local Path variable which holds the mount
point (`mount.rs` line 438).
Use it instead of creating a new `mount_point` variable with identical
type and content.
Fixes: #3332
Signed-off-by: Dov Murik <dovmurik@linux.ibm.com>

agent: mount: Remove unneeded mount_point local variable

---

src/agent/rustjail/src/container.rs
src/agent/rustjail/src/seccomp.rs

If Kata agent cannot resolve the system calls given by seccomp profiles,
the agent ignores the system calls and continues to run without an error.
Fixes: #2957

agent: Ignore unknown seccomp system calls

---

tools/packaging/kernel/configs/README.md

- `fragments` in backticks
- s/perfoms/performs/
Fixes: #3338
Backport of #3339
/cc @jodh-intel

stable-2.3 | docs: Fix kernel configs README spelling errors

---

ci/go-test.sh
src/runtime/Makefile
src/runtime/pkg/containerd-shim-v2/stream.go

1. use ci/go-test.sh to replace the direct call to go test
2. fix data race test
Fixes #1494

Makefile: update `make go-test` call

---

.github/workflows/deploy-ccv0-demo.yaml

Push the demo image to `quay.io/confidential-containers/runtime-payload`
(which, as opposed to `.../kata-demo`, existed all along).
Fixes: #3345
/cc @bpradipt

CCv0 | actions: Push demo image to runtime-payload

---

ci/openshift-ci/images/Dockerfile.buildroot
tools/osbuilder/dockerfiles/QAT/Dockerfile
tools/osbuilder/dracut/Dockerfile.in
tools/osbuilder/image-builder/Dockerfile
tools/osbuilder/rootfs-builder/centos/Dockerfile.in
tools/osbuilder/rootfs-builder/clearlinux/Dockerfile.in
tools/osbuilder/rootfs-builder/fedora/Dockerfile.in
tools/osbuilder/rootfs-builder/gentoo/Dockerfile.in
tools/osbuilder/rootfs-builder/suse/Dockerfile.in
tools/osbuilder/rootfs-builder/ubuntu/Dockerfile-aarch64.in
tools/packaging/kata-deploy/Dockerfile
tools/packaging/kata-deploy/action/Dockerfile
tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
tools/packaging/kata-monitor/Dockerfile
tools/packaging/static-build/kernel/Dockerfile
tools/packaging/static-build/qemu/Dockerfile
tools/packaging/static-build/shim-v2/Dockerfile
tools/packaging/tests/Dockerfile/FedoraDockerfile.in

I'm sending this PR in preparation to enable a checker on `static-checks.sh` which aims to [run a linter on the dockerfiles](https://github.com/kata-containers/tests/issues/4149) of the project.
That new checker will be using the [hadolint tool](https://github.com/hadolint/hadolint) to inspect the dockerfiles.  So the changes here were made to silent the warnings/errors pointed out by hadolint 2.7.0.
Note that we have a bunch of dockerfile templates on the project which can't be parsed by the tool without some tricks.  See on https://github.com/kata-containers/tests/pull/4194 how I plan to handle templates, but even with the handling some files fail to get parsed and that explain why they will be ignored.
Below is how I run the hadolint on kata-containers repository. 
```
$ curl -sL …
```

Delint dockerfiles

---

src/runtime/data/kata-collect-data.sh.in

Fix a typo while to check if mountpoint exist.
Fixes: #3365

runtime: fix a typo in kata-collect-data.sh

---

src/runtime/pkg/katatestutils/constraints_test.go
tools/osbuilder/rootfs-builder/debian/Dockerfile-aarch64.in
tools/osbuilder/rootfs-builder/debian/Dockerfile.in
tools/osbuilder/rootfs-builder/debian/config.sh
tools/osbuilder/rootfs-builder/debian/rootfs_lib.sh
tools/osbuilder/rootfs-builder/rootfs.sh
tools/packaging/static-build/scripts/kata-configure-docker.sh
utils/kata-manager.sh

Restore Debian as a rootfs. Relate Issue #3372 
1. revert of #3154, but some change
2. update debian version to `10.11`
3. update  `libstdc++-6-dev` to `libstdc++-8-dev`
4.  changes discarded in QAT are not restored
Fixes: #3372
Signed-off-by: zhaojizhuang <571130360@qq.com>

osbuilder: Restore Debian as a rootfs

---

src/agent/Cargo.lock
src/agent/Cargo.toml
src/agent/src/main.rs

- Use clap to do command line parsing
Fixes: #3284
Co-authored-by: Samuel Ortiz <samuel.e.ortiz@protonmail.com>
Co-authored-by: stevenhorsman <steven@uk.ibm.com>

agent: Refactor command line parsing to use a framework

---

versions.yaml

This is a bug release from Cloud Hypervisor addressing the following issues:
1. Don't error out when setting up the SIGWINCH handler (for console resize) when this fails due to older kernel
1. Seccomp rules were refined to remove syscalls that are now unused
1. Fix reboot on older host kernels when SIGWINCH handler was not initialised
1. Fix virtio-vsock blocking issue
Details can be found: https://github.com/cloud-hypervisor/cloud-hypervisor/releases/tag/v20.2
Fixes: #3383

versions: Upgrade to Cloud Hypervisor v20.2

---

versions.yaml

This is a bug release from Cloud Hypervisor addressing the following
issues: 1) Don't error out when setting up the SIGWINCH handler (for
console resize) when this fails due to older kernel; 2) Seccomp rules
were refined to remove syscalls that are now unused; 3) Fix reboot on
older host kernels when SIGWINCH handler was not initialised; 4) Fix
virtio-vsock blocking issue.
Details can be found: https://github.com/cloud-hypervisor/cloud-hypervisor/releases/tag/v20.2
Fixes: #3383
(cherry picked from commit 1f581a04058ad0883bcc08b2f65168e8d0452f45)

stable-2.3 | versions: Upgrade to Cloud Hypervisor v20.2

---

src/runtime/config/configuration-acrn.toml.in
src/runtime/config/configuration-clh.toml.in
src/runtime/config/configuration-fc.toml.in
src/runtime/config/configuration-qemu.toml.in

This PR removes the reference of how to use disable_new_netns
configuration with docker as for kata 2.0 we are not supporting docker
and this information was used for kata 1.x
Fixes #3400

runtime: Remove docker comments for kata 2.0 configuration.tomls

---

ci/install_libseccomp.sh

This reverts commit 321995b7df787ee18e46d660ccf0d3862831d439.
Now that gnu.org is back online, we don't need to use a mirror.
Fixes: #3313.

CI: Revert "CI: Switch to a mirror as gnu.org is down"

---

src/runtime/virtcontainers/container.go

Return before closing span will cause invalid spans, so span should
be closed before function return.
Fixes: #3424

runtime: close span before return from function in case of error

---

src/libs/oci/.gitignore
src/libs/protocols/.gitignore

Generated protocols files should not be inclued in Git repo.
And also add Cargo.lock in oci/protocols directory to .gitignore.
Fixes: #3422

libs: add some generated files to .gitignore

---

tools/packaging/kata-deploy/scripts/kata-deploy.sh

As containerd doesn't exist at cleanup
Fixes: #3429

kata-deploy: validate conf file can be created

---

src/runtime/virtcontainers/kata_agent.go

The k.reqHandlers should be protected by locks when used
Fixes #3440
Signed-off-by: liangxianlong <liang.xianlong@zte.com.cn>

runtime: Provide protection for shared data

---

tools/packaging/README.md

This PR removes the ccloudvm reference at the README document as the
setup of scripts of ccloudvm were removed.
Fixes #3448

docs: Remove ccloudvm reference

---

docs/design/host-cgroups.md

Container1's cgroupsPath in pod2 should be /kubepods/pod2/container1.
Fixes: #3431

docs: fix a typo in host-cgroups.md doc

---

tools/packaging/kernel/configs/fragments/common/debug.conf

Provide the `/proc/config.gz` file in guest kernels that allow the guest
to determine the kernel configuration used to build the running kernel.
Note that since `gunzip` expects to rename the gzip'ed file it operates
on, to use this feature you need to run something like the following in
the container environment:
```bash
```
Fixes: #3445.

packaging: Make kernel config accessible to guest

---

.github/workflows/kata-deploy-test.yaml

The action used for testing kata-deploy is entirely based on the action
used to build the kata-deploy tarball, but while the latter is able to
use the correct branch, the former always uses `main`.
This happens as the `issue_comment`, from GitHub actions, passed the
"default branch" as the GITHUB_REF.
As we're not the first ones to face such a issue, I've decided to take
one of the approaches suggested at one of the checkout's issues,
https://github.com/actions/checkout/issues/331, and take advantage of a
new action provided by the community, which will get the PR where the
comment was made, give us that ref, and that then can be used with the
checkout action, resulting on what we originally wanted.
Fixes: #3443

workflows: Use the correct branch ref on test kata-deploy

---

src/runtime/Makefile

for linking. Required for basic KVM checks on some kernels (e.g. the
one RHEL is currently shipping), cf.
https://github.com/qemu/qemu/blob/6621441db50d5bae7e34dbd04bf3c57a27a71b32/target/s390x/kvm/meson.build#L15-L16.
Fixes: #3469
Related: https://github.com/kata-containers/tests/pull/4376

runtime: -Wl,--s390-pgste for s390x

---

versions.yaml

Current latest release is 1.23.1. Let's update to this version for our
integration testing.
Fixes: #3477

version: bump to kubernetes 1.23

---

tools/packaging/release/release-notes.sh

Escape (with backslash) backticks ( ` ) to prevent them from being evaluated by the shell.
Fixes: #3487

release: Escape backticks in Libseccomp Notices

---

.github/workflows/kata-deploy-push.yaml

A `:` was missed when d87ab14fa7c2244a631189083cceb6344ae9f306 was
introduced.
Fixes: #3485

workflows: Fix typo in kata-deploy-push action

---

.github/workflows/kata-deploy-test.yaml

Although I've done tests on my own fork using `head_ref` and those
worked, it seems those only worked as the PR was coming from exactly the
same repository as the target one.
Let's switch to base_ref, instead, which we for sure have as part of our
repo.
The downside of this is that we run the test with the last merged PR,
rather than with the "to-be-approved" PR, but that's a limitation we've
always had.
Fixes: #3482

workflows: Use base instead of head ref for kata-deploy-test

---

tools/packaging/Makefile
tools/packaging/README.md

Now that kata-pkgsync has been removed, this PR removes the reference
in the documentation.
Fixes #3513

docs: Remove kata-pkgsync reference

---

src/agent/src/namespace.rs

The tokio's spawn will only create an future async task
instead of a new real thread, thus executing unshare to
create a new namespace in tokio's async task would make
the agent process to join in the new created namespace,
which isn't expected.
Thus, we'd better to to the unshare in a real thread to
prevent moving the agent process into a new namespace.
Fixes: #3369

agent: fix the issue of creating new namespaces for agent

---

tools/osbuilder/rootfs-builder/alpine/Dockerfile.in
tools/osbuilder/rootfs-builder/clearlinux/Dockerfile.in

Remove the libseccomp package from Dockerfile of `alpine` and `clearlinux`
because the libseccomp library is installed by the `ci/install_libseccomp.sh`
script when building the kata-agent.
Fixes: #3508

osbuilder: Remove libseccomp from Dockerfile

---

src/runtime/Makefile

When no options are passed to `-ldflags`, it considers
the next string(in this case, `$BUILDFLAGS`) as its value.
Fix passing empty values by passing `$KATA_LDFLAGS`
in quotes.
Fixes: #3521

runtime: rectify passing empty options to -ldflags

---

Makefile
src/agent/Makefile
src/libs/Cargo.lock
src/libs/Cargo.toml
src/libs/Makefile
src/libs/README.md
src/libs/kata-types/Cargo.toml
src/libs/kata-types/README.md
src/libs/kata-types/src/annotations/cri_containerd.rs
src/libs/kata-types/src/annotations/crio.rs
src/libs/kata-types/src/annotations/dockershim.rs
src/libs/kata-types/src/annotations/mod.rs
src/libs/kata-types/src/container.rs
src/libs/kata-types/src/k8s.rs
src/libs/kata-types/src/lib.rs
src/libs/kata-types/src/mount.rs
src/libs/logging/src/file_rotate.rs
src/libs/logging/src/lib.rs
src/libs/logging/src/log_writer.rs
src/tools/agent-ctl/Makefile
src/tools/trace-forwarder/Makefile

Current src/libs are built as a sub-target of agent, tools/agent-ctl and tools/trace-forwarder. That's not well formed. Let's make src/libs a dedicated main target to simplify the dependency chain.
Also include the kata-type crate, which has been reviewed in #3306, so we could open following-on PRs based on it.

Refine build/makefile framework for src/libs

---

ci/lib.sh
ci/static-checks.sh

e.g. when called from the tests repo
Fixes: #3525
Creating on stable first because it is affected right now.

stable-2.3 | ci: Pass function arguments in static-checks.sh

---

utils/kata-manager.sh

In `utils/kata-manager.sh`, we download the first asset listed for the
release, which used to be the static x86_64 tarball. If that happened to
not match the system architecture, we would abort. Besides that logic
being invalid for !x86_64 (despite not distributing other tarballs at
the moment), the first asset listed is also not the static tarball any
more, it is the vendored source tarball. Retrieve all _static_ tarballs
and select the appropriate one depending on architecture.
Fixes: #3254
Backport of #3271

stable-2.3 | kata-manager: Retrieve static tarball

---

src/runtime/Makefile

for linking. Required for basic KVM checks on some kernels (e.g. the
one RHEL is currently shipping), cf.
https://github.com/qemu/qemu/blob/6621441db50d5bae7e34dbd04bf3c57a27a71b32/target/s390x/kvm/meson.build#L15-L16.
Fixes: #3469
Co-authored-by: Amulya Meka <amulmek1@in.ibm.com>
/cc @Amulyam24 
Backport of #3470 & #3522

stable-2.3 | runtime: -Wl,--s390-pgste for s390x

---

src/runtime/go.mod
src/runtime/go.sum
src/runtime/vendor/github.com/opencontainers/image-spec/specs-go/v1/annotations.go
src/runtime/vendor/github.com/opencontainers/image-spec/specs-go/v1/config.go
src/runtime/vendor/github.com/opencontainers/image-spec/specs-go/v1/mediatype.go
src/runtime/vendor/github.com/opencontainers/image-spec/specs-go/version.go
src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/cpu.go
src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs2/hugetlb.go
src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/common.go
src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/dbus.go
src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/v1.go
src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/v2.go
src/runtime/vendor/github.com/opencontainers/runc/libcontainer/configs/cgroup_linux.go
src/runtime/vendor/modules.txt

To address two depbot security warnings.
Fixes: #3475

runtime: update runc and image-spec dependencies

---

docs/Limitations.md

This PR removes the docker run and sysctl limitation reference
for kata 2.0 as currently for kata we are not supporting docker and
this reference belonged to kata 1.0
Fixes #3545

docs: Remove docker run and sysctl limitation

---

ci/lib.sh
ci/static-checks.sh

e.g. when called from the tests repo
Fixes: #3525
Forward-port of #3526

ci: Pass function arguments in static-checks.sh

---

src/runtime/virtcontainers/sandbox.go
src/runtime/virtcontainers/sandbox_test.go

The OCI container spec specifies a limit of -1 signifies
unlimited memory. Update the sandbox memory calculator
to reflect this part of the spec.
Fixes: #3512

runtime: fix handling container spec's memory limit

---

src/runtime/pkg/govmm/qemu/qemu.go
src/runtime/pkg/govmm/qemu/qemu_arch_base_test.go
src/runtime/pkg/govmm/qemu/qemu_s390x_test.go
src/runtime/pkg/govmm/qemu/qemu_test.go

govmm: Unite VirtioNet tests
govmm: readonly=on in s390x blkdev test
govmm: TestAppendPCIBridgeDevice et al. on !s390x
govmm: Remove unnecessary comma in iommu_platform
Revert "govmm: s390x: Skip broken tests"
Fixes: #3500

Fix and re-enable s390x GoVMM tests

---

src/runtime/pkg/kata-monitor/monitor.go

This is meant to address #3550 on the stable branch.
We are stable, so we probably don't want to backport #3553 here.
Since we use the sync with the container manager basically to just remove pods from the cache, we can wait some more time before syncing (and so reduce the chance to miss a kata pod just because it was not ready yet) without missing reporting any metric. The sync will just clean-up the sandbox cache from stale entries.
So, let's just raise the waiting time before starting the sync timer to an higher value: this will not fix the issue (if a pod has not completely started when the sync timer fires, we will miss its metrics till a new kata pod starts / is removed) but will make the issue to be much more unlikely to happen.

stable-2.3 | kata-monitor: increase delay before syncing with the container manager

---

tools/packaging/kata-deploy/action/test-kata.sh

When building a non-stable release, the tag is **always** "latest¨,
instead of the version. The same magic done for setting the correct
tags up should be done for replacing the tag on the kata-deploy and
kata-cleanup yaml files, as part of the kata-deploy test.
Fixes: #3559

kata-deploy: Fix the tag replacement logic

---

tools/packaging/kata-deploy/scripts/kata-deploy.sh

As containerd doesn't exist at cleanup
backport #3433

stable-2.3 - kata-deploy: validate conf file can be created 

---

docs/how-to/ccv0.sh
docs/how-to/how-to-build-and-test-ccv0.md

- Add scripts and documentation to build, configure and test
created a Kata CC unencrypted container using crictl
- Update documentation to better fit the kata documentation requirements
- Fixes: #3510

CCv0 | doc: Add crictl e2e cc doc

---

src/agent/rustjail/src/container.rs
src/agent/rustjail/src/mount.rs
src/agent/src/namespace.rs
src/agent/src/sandbox.rs
src/agent/src/watcher.rs
versions.yaml

Update Rust to 1.58.1 to fix CVE-2022-21658.
Fixes: #3570

versions: update Rust to 1.58.1

---

src/runtime/pkg/katautils/config.go
src/runtime/virtcontainers/clh.go
src/runtime/virtcontainers/clh_test.go
src/runtime/virtcontainers/virtcontainers_test.go

Since CH has supported booting with an initramfs since version 0.7.0
[1], allow an `initrd=` to be specified.
Fixes: #3566.
[1] - https://github.com/cloud-hypervisor/cloud-hypervisor/releases/tag/v0.7.0

virtcontainers: Enable initrd for Cloud Hypervisor

---

src/agent/rustjail/src/container.rs

When the container didn't had a tty console, it would be in a same
process group with the kata-agent, which wasn't expected. Thus,
create a new session for the container process.
Fixes: #3063

[backport from main] agent: fix the issue of missing create a new session for container

---

.github/workflows/PR-wip-checks.yaml
.github/workflows/commit-message-check.yaml
.github/workflows/kata-deploy-push.yaml
.github/workflows/kata-deploy-test.yaml
.github/workflows/move-issues-to-in-progress.yaml
.github/workflows/require-pr-porting-labels.yaml
.github/workflows/snap.yaml
src/runtime/virtcontainers/container.go
src/runtime/virtcontainers/kata_agent.go
tools/packaging/static-build/qemu/build-base-qemu.sh

99ed596a workflows: Fix typo in kata-deploy-push action
13b7d93b workflows: Ensure a label change re-triggers the actions
b8463224 workflows: Ensure force-skip-ci skips all actions
8c8571f4 workflows: Use the correct branch ref on test kata-deploy
620bb97e runtime: Provide protection for shared data
770d4acf tools: Fix groupname if it differs from username
cedb01d2 runtime: close span before return from function in case of error

stable-2.3-backports

---

.github/workflows/kata-deploy-test.yaml

Although I've done tests on my own fork using `head_ref` and those
worked, it seems those only worked as the PR was coming from exactly the
same repository as the target one.
Let's switch to base_ref, instead, which we for sure have as part of our
repo.
The downside of this is that we run the test with the last merged PR,
rather than with the "to-be-approved" PR, but that's a limitation we've
always had.
Fixes: #3482
(cherry picked from commit 3924470c8ff3cab4e1e628fc5559e83854f1b479)

stable-2.3 | workflows: Use base instead of head ref for kata-deploy-test

---

.github/workflows/commit-message-check.yaml

The commit message of a revert commit usually generated by
`git revert`, we should consider this as legal.
Consider the commit as the merge commit if the subject
starts with 'Reject "'
Follow the pr kata-containers/tests#3938, the suttle diffrence
is we skip all commit checks for revert commit including fixes checking
and subsystem checking. Because the commit was reverted must have passed
the check so the revert-commit should have the Fixes and Subsystem.
Fixes: #3568
Fixes: kata-containers/tests#3934

workflows: stop checking revert commit

---

src/agent/rustjail/src/container.rs

The hook.args[0] is the binary name which shouldn't be included
in the Command.args.
refer [posix-platform-hooks](https://github.com/opencontainers/runtime-spec/blob/main/config.md#posix-platform-hooks)
Fixes: #2610

agent: Fix execute_hook() args error

---

.github/workflows/kata-deploy-push.yaml
.github/workflows/kata-deploy-test.yaml

This pull request makes two changes to the kata-deploy worfklows.
1. For kata-deploy-test, let's make sure we are exercising changes that are introduced by the PR itself, rather than our base. With this, you can expect changes to our build scripts and/or kata-deploy scripts to be exercised. This doesn't change behavior, however, if changes to the kata-deploy-test workflow itself. Developers will need to continue using a fork to verify these (which is how this PR is tested - details below).
2. For kata-deploy-push:
*  let's make sure that we only run the workflow if the PR includes changes to ./tools/**. This way, we don't waste cycles for every single PR, and only exercise for use case that we care about (ensuring that ./tools/packaging and ./tools/osbuilder are still running correctly). …

kata-deploy: for testing, make sure we use the PR branch

---

src/runtime/virtcontainers/pkg/rootless/rootless.go
src/runtime/virtcontainers/pkg/rootless/rootless_linux.go

Move the netns specific bits into a Linux specific file.
Fixes: #3607

virtcontainers: Split the rootless package into OS specific parts

---

.github/workflows/commit-message-check.yaml
.github/workflows/kata-deploy-push.yaml
.github/workflows/move-issues-to-in-progress.yaml
.github/workflows/snap.yaml
.github/workflows/static-checks.yaml

This reverts commit 7a879164bd2fa1a7aad7954a2fda8374e8af9968, as it's
been proved that re-triggering the checks at every single change is more
painful than having to close / re-open a PR in case we ever use the
`force-skip-ci` label again.
Fixes: #2804

Revert "workflows: Ensure a label change re-triggers the actions"

---

docs/how-to/ccv0.sh
docs/how-to/how-to-build-and-test-ccv0.md

General doc enhancements including:
- Change `cd`s for `pushd` and `popd`s
- Remove hard coded architectures
- Tighten up the security where we `chmod 777`
- Add support for not running as source
- Updates so it doesn't do `ctr pull` if the image is on the
local system already
- Doc and Test running as non-root user (covered by #2879)
- Update doc to match image_rpc changes
Fixes: #3549
Fixes: #2879

CCv0 | doc: Improve ccv0.sh and CCv0 how-to document 

---

src/runtime/virtcontainers/hypervisor_amd64.go

Since linux 5.12, `kvm` module declares the `sev` parameters as a `boolean` (instead of an `int`) .
This PR fixes the verification of this parameter made by the runtime for linux 5.12 and above.
This was successfully tested against linux 5.15.
Edit:
Fixes #3273
Signed-off-by: Pierre Kohler <pierre.kohler@cysec.systems>

runtime: also check kvm module `sev` parameter as bool

---

ci/openshift-ci/images/Dockerfile.buildroot

The build root container is switched from CentOS 8 to Stream 8 as
the former reached EOL.
Fixes #3605

openshift-ci: switch to CentOS Stream

---

snap/snapcraft.yaml
versions.yaml

Update qemu version of snap for arm to 6.1.0 thus the arch specific qemu
version for arm needs clean up.
Fixes: #3627

snap: update qemu version to 6.1.0 for arm

---

src/agent/src/device.rs
src/agent/src/rpc.rs
src/agent/src/sandbox.rs

In commit `78dff468bf1` we introduced logic to rewrite `PCIDEVICE_` environment variables for the container so that they contain correct addresses for the Kata VM rather than for the host.  Unfortunately, we never actually invoked the function to do this.
It turns out we need to do this not only at container creation time, but also for environment variables supplied to processes exec-ed into the container after creation (e.g. with crictl exec).  Add calls to make both those updates.

device: Actually update PCIDEVICE_ environment variables for the guest

---

tools/packaging/kernel/build-kernel.sh
versions.yaml

Add support for building TDX kernel from github.com/intel/tdx
To build a guest kernel that supports Intel TDx run:
```
./build-kernel.sh -s -x tdx -d setup
./build-kernel.sh -s -x tdx -d install
```
fixes #3650

kernel: support TDx

---

docs/Release-Process.md
docs/Unit-Test-Advice.md
docs/code-pr-advice.md
docs/how-to/how-to-import-kata-logs-with-fluentd.md
docs/how-to/how-to-run-docker-with-kata.md
docs/how-to/how-to-use-virtio-fs-with-kata.md
docs/install/minikube-installation-guide.md
docs/install/snap-installation-guide.md
docs/tracing.md
docs/use-cases/using-Intel-QAT-and-kata.md
docs/use-cases/using-Intel-SGX-and-kata.md
src/runtime/README.md
tools/osbuilder/rootfs-builder/README.md

Relative links within this repository allow for easier navigation to
the corresponding file / directory in the current commit / for the
selected version.
Link text was slightly changed / fixed in
- docs/Unit-Test-Advice.md
- docs/how-to/how-to-run-docker-with-kata.md
Fixes #3045

docs: Fix relative links in Markdown

---

versions.yaml

As done for kubernetes, CRI-O should also be bumped to its 1.23 release
so those are in sync.
Fixes: #3481
And, while here, critools v1.23.0 has been released a few days ago.  As we're already
bumping kubernetes, and CRI-O, let's also update critools.

versions: bump CRI-O to its 1.23 release

---

tools/packaging/kernel/build-kernel.sh

check $build_type is not an empty string instead of equal to "true".
Fixes: #3635

scripts: fix a typo while to check build_type

---

src/runtime/pkg/katautils/network.go

The variables mountTypeFieldIdx := 8 and mntDestIdx := 4 are initialized multiple times in the for.
Moved mountTypeFieldIdx := 8 and mntDestIdx := 4 outside the for.
Fixes: #3646
Signed-off-by: yaoyinnan <yaoyinnan@foxmail.com>

runtime: The index variable is initialized multiple times in for

---

src/agent/rustjail/src/container.rs

Envs contain null-byte will cause running hooks to panic,
this commit will filter envs and only pass valid envs to hooks.
Fixes: #3667
agent: handle hook process result
The current hook process is handled by just calling
unwrap() on it, sometimes it will cause panic.
Handling all Result types and checking the error can
avoid panic.
Fixes: #3649

agent: fix hook execution issues

---

docs/Limitations.md

This PR removes the docker run and shared memory segment from the
limitations document as for kata 2.0 we do not support docker
and this is not longer valid.
Fixes #3676

docs: Remove docker run and shared memory from limitations

---

tools/packaging/static-build/cloud-hypervisor/build-static-clh.sh

This short series adds the possibility to force building Cloud Hypervisor from sources as not always the released binary, even if it matches the version we're trying to use / ship, has been built with the needed features enabled.  And talking about building something with the needed features, support for doing this is also added as part of this series.
Fixes: #3672 
Fixes: #3671

tools: clh: Allow to set when to build from sources and the build flags passed down to cargo

---

src/runtime/Makefile

German Maglione, one of the current virtio-fs developers, has brought to
our attention that using "announce-submounts" could help us to prevent
inode number collisions.
This feature was introduced a year ago or so by Hanna Reitz as part of
the 08dce386e77eb9ab044cb118e5391dc9ae11c5a8, and as we already mandate
QEMU >= 6.1.0, let's take advantage of that.
Fixes: #3507

virtiofsd: Use "-o announce_submounts"

---

tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh

Right now TDx support on Cloud Hypervisor is gated behind a "--features
tdx" flag.  However, having TDx support enabled should not and does not
impact on the general usability of cloud-hypervisor.
As sooner than later we'll need kata-deploy binaries to be tested on a
CI that's TDx capable, for the confidential containers effort, let's
take the bullet and already enable it by default.
By the way, touching kata-deploy-binaries.sh as it's ensure the change
will be used in the following workflows:
* kata-deploy-push
* kata-deploy-test
* release
Fixes: #3688
Together with this one, in a separate commit, there's also a small cleanup.

tools: Build cloud-hypervisor with "--features tdx"

---

README.md
src/runtime/README.md

Various improvements to the top-level README file:
- Moved the following sections from the runtime's README to the
top-level README:
- License
- Platform support / Hardware requirements
- Added the following sections to the top-level README:
- Configuration
- Hypervisors
- Improved formatting of the Documentation section in the top-level
README.
- Removed some unused named links from the top-level README.
Fixes: #3557.

docs: Improve top-level README

---

src/agent/Makefile
src/tools/agent-ctl/Makefile
src/tools/agent-ctl/src/client.rs
src/tools/agent-ctl/src/main.rs
src/tools/agent-ctl/src/utils.rs
src/tools/trace-forwarder/Makefile
src/tools/trace-forwarder/src/handler.rs
utils.mk

Add make check to run cargo fmt/clippy
for Rust projects.
Fixes: #3656

trace-forwarder/agent-ctl: run cargo fmt/clippy in make check

---

utils/README.md
utils/kata-manager.sh

Fix installation of both Kata and containerd for the `kata-manager.sh` script and update the docs.
Fixes: #3674.

Kata manager fix install

---

.github/workflows/move-issues-to-in-progress.yaml
src/libs/Cargo.lock
src/libs/kata-types/Cargo.toml
src/libs/kata-types/src/annotations/dockershim.rs
src/libs/kata-types/src/annotations/mod.rs
src/libs/kata-types/src/annotations/thirdparty.rs
src/libs/kata-types/src/config/agent.rs
src/libs/kata-types/src/config/agent_vendor.rs
src/libs/kata-types/src/config/default.rs
src/libs/kata-types/src/config/hypervisor/dragonball.rs
src/libs/kata-types/src/config/hypervisor/mod.rs
src/libs/kata-types/src/config/hypervisor/qemu.rs
src/libs/kata-types/src/config/hypervisor/vendor.rs
src/libs/kata-types/src/config/mod.rs
src/libs/kata-types/src/config/runtime.rs
src/libs/kata-types/src/config/runtime_vendor.rs
src/libs/kata-types/src/lib.rs
src/libs/kata-types/tests/test-config.rs
src/libs/kata-types/tests/test_config.rs
src/libs/kata-types/tests/texture/configuration-anno-0.toml
src/libs/kata-types/tests/texture/configuration-anno-1.toml
src/libs/kata-types/tests/texture/configuration-qemu.toml

Redefined the data structure for kata config and be able to update kata config securely by annotation
Fixes: #3523

Runtime-rs: load, parse, access kata configuration and optionally modify them by annotations

---

docs/Limitations.md

This PR updates the limitations document by removing the docker
references belonged to kata 1.x and add as a limitation the
docker and podman support for kata 2.0
Fixes #3709

docs: Update limitations document

---

src/runtime/virtcontainers/utils/utils_test.go

Remove duplicated strings in assert.Errorf() and assert.NoErrorf().
Fixes: #3714

virtcontainers: Remove duplicated assert messages in utils test code

---

tools/packaging/scripts/apply_patches.sh
tools/packaging/static-build/kernel/Dockerfile
tools/packaging/static-build/qemu/Dockerfile

`tools/packaging/scripts/apply_patches.sh` uses `git apply $patch`, but
this will not apply to subdirectories. If one wanted to apply with
`git apply`, they'd have to run it with `--directory=...`
_relative to the Git tree's root_ (absolute will not work!). I suggest
we just use `patch`, which will do what we expected `git apply` would
do.
`patch` is also added to build containers that require it.
Fixes: #3690
Backport of #3691

stable-2.3 | packaging: Use `patch` for applying patches

---

src/runtime/pkg/kata-monitor/cri.go
src/runtime/pkg/kata-monitor/metrics.go
src/runtime/pkg/kata-monitor/metrics_test.go
src/runtime/pkg/kata-monitor/monitor.go
src/runtime/pkg/kata-monitor/sandbox_cache.go
src/runtime/pkg/kata-monitor/sandbox_cache_test.go
src/runtime/pkg/kata-monitor/shim_client.go

Currently, kata-monitor detects started and terminated kata pods by monitoring the vc/sbs fs (this makes sense since we will have to access that path to access the sockets there to get the metrics from the shim).
While kata-monitor updates its sandbox cache based on the sbs fs events, it will schedule also a sync with the container manager via the CRI in order to sync the list of sandboxes there.
The container manager will be the ultimate source of truth, so we will stick with the response from the container manager, removing the sandboxes not reported from the container manager.
May happen anyway that when we check the container manager, the new kata pod is not reported yet, and we will remove it from the kata-monitor pod cache. If we don't get any new kata pod added or removed, we will …

kata-monitor: simplify sandbox cache management and attach kubernetes POD metadata to metrics

---

tools/packaging/kata-deploy/scripts/kata-deploy.sh

When using kata-deploy, no `containerd-shim-kata-v2` binary is deployed,
but we do deploy a `kata` runtime class, which seems very much
incosistent.
As the default configuration for kata-containers points to QEMU, let's
also use kata with QEMU as the default shim-v2 binary.
Fixes: #3228, #3734

kata-deploy: Use (kata with) qemu as the default shim-v2 binary

---

CONTRIBUTING.md

This PR updates the contributing documentation link to the
one that is using kata 2.0
Fixes #3740

docs: Update contributing link

---

src/runtime/pkg/containerd-shim-v2/event_forwarder.go
src/runtime/pkg/containerd-shim-v2/event_forwarder_test.go
src/runtime/pkg/containerd-shim-v2/service.go
src/runtime/virtcontainers/container.go

CRI-O start shim process without setting TTRPC_ADDRESS,
that the forwarding events goroutine will get errors.
For CRI-O runtime, we can log the events to log file.
Fixes: #3733

shim: log events for CRI-O

---

src/runtime/pkg/containerd-shim-v2/event_forwarder.go
src/runtime/pkg/containerd-shim-v2/event_forwarder_test.go
src/runtime/pkg/containerd-shim-v2/service.go
src/runtime/virtcontainers/container.go

CRI-O start shim process without setting TTRPC_ADDRESS,
that the forwarding events goroutine will get errors.
For CRI-O runtime, we can log the events to log file.
Fixes: #3733
Backport of #3736

stable-2.3 | shim: log events for CRI-O

---

tools/packaging/kata-deploy/scripts/kata-deploy.sh

When using kata-deploy, no `containerd-shim-kata-v2` binary is deployed,
but we do deploy a `kata` runtime class, which seems very much
incosistent.
As the default configuration for kata-containers points to QEMU, let's
also use kata with QEMU as the default shim-v2 binary.
Fixes: #3228, #3734
Backports: #3735
(cherry picked from commit 11220f052f3a7e7c2efd9db188d5aaf26b152ab7)

stable-2.3 | kata-deploy: Use (kata with) qemu as the default shim-v2 binary

---

src/runtime/pkg/katautils/create.go
src/runtime/pkg/katautils/create_test.go
src/runtime/pkg/katautils/hook.go
src/runtime/pkg/katautils/hook_test.go

The kata runtime does not properly work with `nerdctl` [1], and this is partly due to the fact that it does not support the `createRuntime` hooks and also because it can not tell `nerdctl` which networking namespace to use when calling the CNI plugins.
This PR:
1. Add support for the `createRuntime` hooks
2. Run both the (deprecated) `preStart` and `createRuntime` hooks in the runtime networking namespace
3. Pass the spec annotations back to the called hooks
4. Add a `nerdctl` specific annotation for indicating which networking namespace to use when calling the CNI plugins.
For a fully working `nerdctl`, this PR depends on https://github.com/containerd/nerdctl/pull/817
[1] https://github.com/containerd/nerdctl/issues/787

Support nerdctl OCI hooks

---

tools/packaging/kata-deploy/Dockerfile

The kata-deploy Dockerfile is based on CentOS 7, which has no s390x
support. Add an `IMAGE` argument to specify the registry, which still
defaults to CentOS, but e.g. ClefOS can be selected instead.
Other x86_64 assumptions are also removed. Other general simplicifations
are made.
This does not address the more general issue of #3723 -- what we're
doing here does not seem to be working with systemd >= something between
235-237.
Fixes: #3722
/cc @bpradipt since you were asking -- this is a co-requirement for s390x CC operator support.

kata-deploy: Simplify Dockerfile and support s390x

---

src/runtime/pkg/govmm/vmm_ppc64le.go

Incorrect package name causes build to fail. Fix it
in `vm_ppc64le.go`
Fixes: #3761

runtime: fix package declaration for ppc64le

---

src/runtime/cmd/kata-monitor/main.go
src/runtime/pkg/kata-monitor/cri.go
src/runtime/pkg/kata-monitor/metrics.go
src/runtime/pkg/kata-monitor/metrics_test.go
src/runtime/pkg/kata-monitor/monitor.go
src/runtime/pkg/kata-monitor/sandbox_cache.go
src/runtime/pkg/kata-monitor/sandbox_cache_test.go

This PR targets to:
1) fix #3705
2) rename symbols and labels containing "Kube" to "CRI": the collection of CRI metadata we just added belong to CRI spec, not kubernetes. Any CRI consumer will get those labels (renamed to cri_name, cri_namespace and cri_uid).
3) bump kata-monitor version: we don't stick to the kata shim version, as kata-monitor should usually work with older and newer shim releases. We want anyway have a new version in kata-monitor binary we release as from commit #7516a8c51b40e5b84b46f1888b2337c50e1acce5  we now totally rely on FS events. May be useful for debugging.
What is still missing is giving-up when trying to retrieve CRI metadata: if the sandbox has not been created through CRI (e.g., containerd 'ctr run') we will keep polling containerd CRI interface. While I …

kata-monitor: fix collecting metrics for sandboxes not started through CRI

---

src/runtime/virtcontainers/qemu.go

On s390x, skip adding a virtio-rng device. The on-chip CPACF provides
entropy instead. For Confidential Containers, when using Secure
Execution, entropy attacks on virtio-rng are mitigated.
Fixes: #3598
/cc @stevenhorsman -- might be good to have in CCv0 soonish. But I'm creating this upon main because it is a general issue.

virtcontainers: Do not add a virtio-rng-ccw device

---

src/runtime/virtcontainers/clh.go
tools/packaging/static-build/cloud-hypervisor/build-static-clh.sh

This is a follow-up of #3771, and we're fixing here an issue found by an unrelated PR, where the ARM CI poinnted out about the unbound variable, and also a typo pointed out by @egernst.
Fixes: #3775

Fix unbound variable / typo on error mesage

---

src/runtime/Makefile
src/runtime/config/configuration-acrn.toml.in
src/runtime/config/configuration-clh.toml.in
src/runtime/config/configuration-fc.toml.in
src/runtime/config/configuration-qemu.toml.in
src/runtime/pkg/katautils/config.go
src/runtime/virtcontainers/clh.go
src/runtime/virtcontainers/fc.go
src/runtime/virtcontainers/hypervisor.go
src/runtime/virtcontainers/qemu.go

- runtime, config: make selinux configurable
- removes --tags selinux handling in the makefile (part of it introduced here: https://github.com/kata-containers/kata-containers/commit/d78ffd653d051948218e8b8ba21a551ad15c2b45) 
Fixes: #3631
Signed-off-by: Tanweer Noor <tanweer.noor@gmail.com>

runtime, config: make selinux configurable

---

src/agent/rustjail/src/cgroups/fs/mod.rs

The content about systemd in "/proc/self/cgroup" is as:
1:name=systemd:/kubepods/pod1815643d-3789-4e4e-aaf4-00de024912e1/0e15a65bd5f7b30a0b818d90706212354d8b3f0998a1495473c3be9a24706ccf
and in "/prol/self/mountinfo" is as:
30 29 0:26 / /sys/fs/cgroup/systemd rw,nosuid,nodev,noexec,relatime shared:6 - cgroup cgroup rw,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd
The keys extracted from the two files are the same as "name=systemd". So no need to rename the key to "systemd".
Fixes: https://github.com/kata-containers/kata-containers/issues/3385

kata-agent: Fix mismatching error of cgroup and mountinfo.

---

docs/Developer-Guide.md

The Developer-Guide.md build a custom kata agent with `x86_64-unknown-linux-musl`.
The `musl` should be changed by the system arch. The system arch is aarch64,
ppc64le and s390x, the musl should be changed. When the arch is ppc64le or s390x,
the musl should be replaced by the gnu.
Fixes: #3731

docs: Developer-Guide build a custom Kata agent with musl

---

docs/README.md

This PR updates the README document by using the proper link for
the contributing guide as well as a misspelling.
Fixes #3791

docs: Update Readme document

---

src/runtime/config/configuration-clh.toml.in
src/runtime/config/configuration-qemu.toml.in

Let's clarify that an error will be reported in case confidential_guest
is enabled, but the hardware where Kata Containers is running doesn't
provide the required feature set.
Fixes: #3787
And while at this, let's also make it clear that when using Cloud Hypervisor we only support Intel TDX.

Update `confidential_guest` comments

---

src/runtime/Makefile
src/runtime/config/configuration-acrn.toml.in
src/runtime/config/configuration-clh.toml.in
src/runtime/config/configuration-fc.toml.in
src/runtime/config/configuration-qemu.toml.in
src/runtime/pkg/katautils/config.go
src/runtime/virtcontainers/clh.go
src/runtime/virtcontainers/fc.go
src/runtime/virtcontainers/hypervisor.go
src/runtime/virtcontainers/qemu.go

removes --tags selinux handling in the makefile (part of it introduced here: d78ffd6)
and makes selinux configurable via configuration.toml
Fixes: #3631
Signed-off-by: Tanweer Noor <tnoor@apple.com>

back port:: runtime: make selinux configurable

---

snap/snapcraft.yaml
versions.yaml

The current snap build for clh is broken as it's not aware of how to
build the binary from sources.
Instead of fixing it here, let's take advantage of the kata-deploy
script, which is capable of building from sources, and re-use it here.
Fixes: #3693

snap: clh: Re-use kata-deploy script here

---

src/runtime/Makefile
src/runtime/cmd/kata-monitor/main.go

monitor: Listen to localhost only by default
Change `kata-monitor` to listen to port `8090` on the local interface
only by default.
> **Note:**
>
> This is a breaking change as previously it listened on all interfaces.
Fixes: #3795.

Fix monitor listen address

---

src/runtime/virtcontainers/api_test.go
src/runtime/virtcontainers/factory/factory_test.go
src/runtime/virtcontainers/factory/template/template_test.go
src/runtime/virtcontainers/kata_agent_test.go
src/runtime/virtcontainers/pkg/mock/mock.go

remove temp dir generated by mock.GenerateKataMockHybridVSock().
Fixes: #3186

virtcontainers: remove temp dir created for vsock in test code

---

snap/snapcraft.yaml

snapcraft build is failing due to:
```
utils.mk:130: "WARNING: powerpc64le-unknown-linux-musl target is unavailable"
```
It seems to happen as powerpc64-unknown-linux-musl is a target that
although there's support for it, it's not exactly built or
automatically tested, at least according to:
https://doc.rust-lang.org/rustc/platform-support.html
Fixes: #3803

snap: Don't build cloud-hypevisor on ppc64le

---

snap/snapcraft.yaml

Use `git clone --depth 1 ...` for QEMU and its dependencies
to speed up checkouts.
Fixes: #3799.

snap: Use git clone depth 1 for QEMU and dependencies

---

src/runtime/Makefile

Enable stack protector and fortify source for golang builds.
Fixes: #3817.

runtime: Build golang components with extra security options

---

src/runtime/config/configuration-clh.toml.in
src/runtime/config/configuration-qemu.toml.in
src/runtime/virtcontainers/clh.go
src/runtime/virtcontainers/qemu_amd64.go
src/runtime/virtcontainers/qemu_arch_base.go
src/runtime/virtcontainers/qemu_ppc64le.go

clh: Don't use sharedFS with Confidential Guests
kata-containers/pulls#3771 added TDX support for Cloud Hypervisor, but
two big things got overlooked while doing that.
1. virtio-fs, as of now, cannot be part of the trust boundary, so the
Confidential Guest will not be using it.
2. virtio-block hotplug should be enabled in order to use virtio-block
for the rootfs (used with the devmapper plugin).
When trying to use cloud-hypervisor with TDX using virtio-fs, we're
facing the following error on the guest kernel:
```
virtiofs virtio2: device must provide VIRTIO_F_ACCESS_PLATFORM
```
After checking and double-checking with virtiofs and cloud-hypervisor
developers, it happens as confidential containers might put some
limitations on the device, so it can't access all of the guests' memory
and …

clh: tdx: Don't use sharedFS with Confidential Guests

---

src/runtime/virtcontainers/clh.go

If, for some reason, we're able to launch cloud hypervisor but not able
to boot the VM up, the virtiofsd process would be left behind.
Let's ensure, via defer, that we stop virtiofsd in case of errors.
Fixes: #3819

clh: stop virtofsd if clh fails to boot up the vm

---

src/runtime/config/configuration-fc.toml.in
src/runtime/config/configuration-qemu.toml.in
src/runtime/pkg/katautils/config.go

config: fc: Don't expose disable_block_device_use
Relying on virtio-block is the *only* way to use Firecracker with Kata
Containers, as shared FS (virtio-{fs,fs-nydus,9p}) is not supported by
Firecracker.
As configuration doesn't make sense to be exposed, we hardcode the
`false` value in the Firecracker configuration structure.
---
config: qemu: Fix disable_block_device_use comments
virtio-fs, instead of virtio-9p, is the default shared file system type
in case virtio-blk is not used.
---
Fixes: #3813

Minor fixes for the `disable_block_device_use` comments

---

src/runtime/pkg/katatestutils/README.md
src/runtime/pkg/katatestutils/constraints.go
src/runtime/pkg/katatestutils/constraints_api.go
src/runtime/pkg/katatestutils/constraints_test.go

The distro constraint parses os release files, which may not contain
distro version(VERSION_ID field), for example rolling release distributions
like Debian testing, archlinux.
These distro constraints are not used anyway, so removing them instead
of fixing the complex version detection.
Fixes: #1864
Signed-off-by: Shengjing Zhu <zhsj@debian.org>

katatestutils: remove distro constraints

---

versions.yaml

Highlights from the Cloud Hypervisor release v22.0:
1. GDB Debug Stub Support;
2. `virtio-iommu` Backed Segments (to facilitate hotplug devices that require being behind an IOMMU, e.g. QAT) ;
3. Before Boot Configuration Changes;
4. `virtio-balloon` Free Page Reporting;
5. Support for Direct Kernel Booting with TDX;
6. PMU Support for AArch64;
7. Documentation Under CC-BY-4.0 License;
8. Deprecation of "Classic" virtiofsd (rust-based virtiofsd now is recommended);
9. Bug fixes on `virtio-balloon`, `virtio-net` with multiple TAP fd support, REST APIs, seccomp filters, migration with `vhost-user`, etc;
Details can be found: https://github.com/cloud-hypervisor/cloud-hypervisor/releases/tag/v22.0
Fixes: #3825

versions: Upgrade to Cloud Hypervisor v22.0

---

src/agent/rustjail/src/container.rs
src/agent/src/sandbox.rs
src/runtime/pkg/resourcecontrol/controller.go
src/runtime/pkg/resourcecontrol/utils_linux.go

- rustjail: delete function signal in BaseContainer
> Function signal in BaseContainer is not used anymore.
- agent: delete meaningless FIXME comment
> The test has passed, the FIX comment should
be deleted.
- runtime: fix invalid comments for pkg/resourcecontrol
> Some comments are copied and not adjusted to the
pkg/resourcecontrol package.

Enhancement: fix comments/logs and delete not used function

---

tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup-stable.yaml
tools/packaging/kata-deploy/kata-deploy/base/kata-deploy-stable.yaml

As 2.4.0-rc0 has been released, let's switch the kata-deploy / kata-cleanup
tags back to "latest", and re-add the kata-deploy-stable and the
kata-cleanup-stable files.
Only merge this commit after 2.4.0-rc0 release is successfully tagged!

release: Revert kata-deploy changes after 2.4.0-rc0 release

---

.github/workflows/add-pr-sizing-label.yaml

Created a new GitHub Action workflow file that adds a sizing label to
each PR.
Fixes: #3841.

CI: Create GHA to add PR sizing label

---

src/agent/src/mount.rs

This series contains some small fixes and debugging improvements for bug #3752 and #3743.  It is *not* a fix for either of those problems, but may show the problems more clearly.

Improve error checking of hugepage allocation

---

src/agent/src/image_rpc.rs

1.Update AA's launch command according to latest implementation
2.Enable get_resource port which will be used by signature verification
Fixes: #3827
Signed-off-by: zhouliang121 <liang.a.zhou@linux.alibaba.com>

CCv0: Update AA's launch command

---

src/agent/src/rpc.rs

Add test coverage for get_memory_info function in src/rpc.rs
Fixes #3837

agent: add tests for get_memory_info function

---

utils/kata-manager.sh

Add new CLI options to the `kata-manager` script:
```
-d           : Enable debug for all components.
-t           : Disable self test (don't try to create a container after install).
-T           : Only run self test (do not install anything).
```
- Added a `-d` option to `kata-manager` to enable Kata Containers and containerd debug.
These are useful for system debugging.
- Added self test options to allow the self test to be disabled, or to only run the self test.
These features allow changes to be made to the installed system before the self test is run.
Fixes: #3851.

Add debug and self-test control options to Kata Manager

---

versions.yaml

This is a bug fix release. The following issues have been addressed:
1. VFIO ioctl reordering to fix MSI on AMD platforms; 
2.  Fix virtio-net control queue.
Details can be found: https://github.com/cloud-hypervisor/cloud-hypervisor/releases/tag/v22.1
Fixes: #3872

versions: Upgrade to Cloud Hypervisor v22.1

---

tools/packaging/kata-deploy/README.md

Corrects a filename typo in cleanup cluster part of kata-deploy README.md
Fixes: #3869

doc: fix kata-deploy README typo

---

src/agent/rustjail/src/utils.rs

Optimized several writelns by merging them into one in src/utils.rs
Fixes #3772 
Signed-off-by: Jack Hance <jack.hance@ndsu.edu>

rustjail: optimization, merged several writelns into one

---

src/runtime/virtcontainers/container.go
src/runtime/virtcontainers/utils/utils.go

Currently kata shim v2 doesn't translate ESRCH signal, causing container
fail to stop and shim leak.
Fixes: #3874
Signed-off-by: <feng.wang@databricks.com>

runtime: properly handle ESRCH error when signaling container

---

versions.yaml

This is a bug fix release. The following issues have been addressed:
1. VFIO ioctl reordering to fix MSI on AMD platforms; 
2. Fix virtio-net control queue.
Details can be found: https://github.com/cloud-hypervisor/cloud-hypervisor/releases/tag/v22.1
Fixes: #3872
(cherry picked from commit 7a18e32fa7b4724994fb06c74b7d27ba5b91ec89)

stable-2.4 | versions: Upgrade to Cloud Hypervisor v22.1

---

versions.yaml

This is a bug fix release. The following issues have been addressed:
1. VFIO ioctl reordering to fix MSI on AMD platforms; 
2. Fix virtio-net control queue.
Details can be found: https://github.com/cloud-hypervisor/cloud-hypervisor/releases/tag/v22.1
Note: client code of Cloud Hypervisor is not updated given this is a
backport change.
Fixes: #3872
(cherry picked from commit 7a18e32fa7b4724994fb06c74b7d27ba5b91ec89)

stable-2.3 | versions: Upgrade to Cloud Hypervisor v22.1

---

src/agent/Cargo.lock
src/agent/Cargo.toml
src/agent/rustjail/src/cgroups/fs/mod.rs
src/agent/rustjail/src/lib.rs
src/agent/src/device.rs
src/agent/src/image_rpc.rs
src/libs/oci/src/lib.rs
src/tools/agent-ctl/src/utils.rs

Image-rs crate image pull/decrypt/decompression/unpack/mount
features are ready now.
With image-rs pull_image API, the downloaded container image layers
will store at IMAGE_RS_WORK_DIR, and generated bundle dir with rootfs
and config.json will be saved under CONTAINER_BASE/cid directory.
Fixes: #3860
Signed-off-by: Arron Wang <arron.wang@intel.com>

image: Enable image-rs crate to pull image inside guest

---

tools/packaging/qemu/patches/6.2.x/Revert-target-ppc-Move-SPR_DSISR-setting-to-powerpc_excp.patch
tools/packaging/scripts/configure-hypervisor.sh
versions.yaml

bring Intel SGX support
Changes tha may impact in Kata Containers
Arm:
The 'virt' machine now supports an emulated ITS
The 'virt' machine now supports more than 123 CPUs in TCG emulation mode
The pl031 real-time clock device now supports sending RTC_CHANGE QMP events
PowerPC:
Improved POWER10 support for the 'powernv' machine
Initial support for POWER10 DD2.0 CPU added
Added support for FORM2 PAPR NUMA descriptions in the "pseries" machine
type
s390x:
Improved storage key emulation (e.g. fixed address handling, lazy
storage key enablement for TCG, ...)
New gen16 CPU features are now enabled automatically in the latest
machine type
KVM:
Support for SGX in the virtual machine, using the /dev/sgx_vepc device
on the host and the "memory-backend-epc" backend in QEMU.
New "hv-apicv" CPU …

tools: update QEMU to 6.2

---

docs/use-cases/using-Intel-SGX-and-kata.md

Installation section is not longer needed because of the latest
default kata kernel supports Intel SGX.
Include QEMU to the list of supported hypervisors.
fixes #3911

doc: update Intel SGX use cases document

---

src/runtime/virtcontainers/container_test.go
src/runtime/virtcontainers/device/config/config.go
src/runtime/virtcontainers/device/config/pmem.go
src/runtime/virtcontainers/device/drivers/block.go
src/runtime/virtcontainers/device/drivers/vhost_user_blk.go
src/runtime/virtcontainers/device/manager/manager.go
src/runtime/virtcontainers/device/manager/manager_linux_test.go
src/runtime/virtcontainers/device/manager/manager_test.go
src/runtime/virtcontainers/documentation/api/1.0/api.md
src/runtime/virtcontainers/kata_agent_test.go
src/runtime/virtcontainers/persist/api/device.go
src/runtime/virtcontainers/persist_test.go
src/runtime/virtcontainers/sandbox_test.go

Currently, the block driver option is specifed by hard coding, maybe it
is better to use const string variables instead of hard coded strings.
Fixes: #3321

device: using const strings for block-driver option instead of hard coding

---

docs/use-cases/using-Intel-SGX-and-kata.md
tools/packaging/qemu/patches/6.2.x/Revert-target-ppc-Move-SPR_DSISR-setting-to-powerpc_excp.patch
tools/packaging/scripts/configure-hypervisor.sh
versions.yaml

This is a controversial one as we passed "-rc0" already, but would be very nice if we could bump QEMU to 6.2.0 (currently using 6.1.0) as part of 2.4.0 release.
SGX code has already been on Kata Containers for a while and it's supported when using Cloud Hypervisor and QEMU as VMMs. The Cloud Hypervisor version used already supports SGX, and so does the Kernel.  The only missing piece is QEMU, which slipped off the "-rc0".
I'd like to ask the @kata-containers/architecture-committee, @Amulyam24 (as the power maintainer), @Jakob-Naucke (as the still s390x maintainer), and @jongwu (as the ARM maintainer) on whether this would be okay to bring in, and what are your concerns from the multi arch point of view.

stable-2.4: Bump QEMU to 6.2 (bringing then SGX support in)

---

src/agent/rustjail/src/cgroups/notifier.rs
src/agent/rustjail/src/lib.rs
src/agent/src/main.rs
src/agent/src/mount.rs
src/agent/src/signal.rs
src/agent/src/util.rs
src/agent/vsock-exporter/src/lib.rs

Clippy v1.58 added needless_late_init.
This breaks agent `make check`.
Fixes #3933

Agent: fix unneeded late initialization lint

---

docs/design/vcpu-handling.md

This PR updates the vcpu handling document by removing docker information
which is not longer being used in kata 2.x and leaving only k8s information.
Fixes #3950

docs: Update vcpu handling document

---

tools/osbuilder/dockerfiles/QAT/Dockerfile

move away from ubuntu, since now it's easier to build using
CentOS as base OS

osbuilder/qat: use centos as base OS

---

.github/workflows/deploy-ccv0-demo.yaml
tools/packaging/kata-deploy/scripts/kata-deploy.sh

for config, as per suggestion from @jodh-intel in #3243.
- Uses the pre-established `kata-containers` folder which we can also
use for more
- Makes it clear the agent is used
Also, use curl instead of wget for uniformity.
Fixes: #3920

CCv0 | github: Use `/etc/kata-containers/agent.toml`

---

docs/how-to/how-to-run-docker-with-kata.md

Some links in how-to-run-docker-with-kata.md is not correct,
and some typos.
Fixes: #3929

docs: fix markdown issues in how-to-run-docker-with-kata.md

---

src/agent/src/rpc.rs
src/runtime/pkg/containerd-shim-v2/service.go
src/runtime/pkg/containerd-shim-v2/start.go
src/runtime/pkg/containerd-shim-v2/stream.go
src/runtime/pkg/containerd-shim-v2/stream_test.go
src/runtime/pkg/containerd-shim-v2/wait.go

This PR addresses #3913.
As described in #3913, the current container termination is insufficient for use cases where a pid namespace is shared among multiple containers. I updated the kata agent container termination logic to follow the [runc](https://github.com/opencontainers/runc/blob/485e6c84e7ef783c126c392af072a974c9fb88ce/libcontainer/init_linux.go#L528) implementation that kills all the processes in the same cgroup, as it's safe to assume each container has its own cgroup. The other change is to set `KillRequest.All` as `true` when the `ExecID` is empty. This separates the container termination versus container exec signaling. 
It's also worth calling out, I didn't change the kata shim v2 service to follow the [runc v2 logic](https://github.com/fengwang666/containerd/blob/e48bbe8394 …

agent: Signal the whole process group

---

tools/packaging/release/update-repository-version.sh

During the release of 2.4.0-rc0 @egernst noticed an incositency in the
way we handle release tags, as release candidates are being taken as
"stable" releases, while both the kata-deploy tests and the release
action consider this as "latest".
Ideally we should have our own tag for "release candidate", but that's
something that could and should be discussed more extensively outside of
the scope of this quick fix.
For now, let's align the code generating the PR for bumping the release
with what we already do as part of the release action and kata-deploy
test, and tag "-rc"  as latest, regardless of which branch it's coming
from.
Fixes: #3847
(cherry picked from commit 4adf93ef2c7ebf75ad6c662a98726c286dd3f87e)

stable-2.4 | tools: release: Do not consider release candidates as stable releases

---

docs/design/VSocks.md

This PR removes the kata-proxy references in VSocks documentation,
as this is not a component in kata 2.0 and all the examples that
were used belonged to kata 1.x.
Fixes #3980

docs: Remove kata-proxy references in documentation

---

src/runtime/virtcontainers/qemu.go

Modify the 2Mib in the comment to 4Mib.
VirtioMem is set by configuration file or annotation. And setupVirtioMem is called only when VirtioMem is true.
Fixes: #3750
Signed-off-by: yaoyinnan <yaoyinnan@foxmail.com>

runtime: Remove the explicit VirtioMem set and fix the comment

---

.github/workflows/release.yaml
tools/packaging/release/generate_vendor.sh

workflows,release: Ship *all* the rust vendored code
Instead of only vendoring the code needed by the agent, let's ensure we
vendor all the needed rust code, and let's do it using the newly
introduced enerate_vendor.sh script.
Fixes: #3973
---
tools: Add a generate_vendor.sh script
This script is responsible for generating a tarball with all the rust
vendored code that is needed for fully building kata-containers on a
disconnected environment.
---
How to verify:
* From the top dir of the project, do:
```
bash -c "tools/packaging/release/generate_vendor.sh kata-containers-vendor.tar.gz"
```
* Do a downstream build using the vendored source, instead of the one currently used.
@etrunko, please, verify if it works on Fedora and let us know ASAP.

release: Include all the rust vendored code into the vendored tarball

---

.github/workflows/release.yaml
tools/packaging/release/generate_vendor.sh

workflows,release: Ship all the rust vendored code
Instead of only vendoring the code needed by the agent, let's ensure we
vendor all the needed rust code, and let's do it using the newly
introduced enerate_vendor.sh script.
Fixes: https://github.com/kata-containers/kata-containers/issues/3973
(cherry picked from commit 3606923ac80aab82f425f158547a0ccc3aa0f9a7)
---
tools: Add a generate_vendor.sh script
This script is responsible for generating a tarball with all the rust
vendored code that is needed for fully building kata-containers on a
disconnected environment.
(cherry picked from commit 2eb07455d0e7d98b7b64b861dde58fb548d89ced)

stable-2.4: release: Include all the rust vendored code into the vendored tarball

---

tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh

`make kata-tarball` relies on `kata-deploy-binaries.sh -s` which silently ignores errors, and you may end up with an incomplete tarball without noticing it because `make`'s exit status is 0. This is due to a non-obvious behaviour of `bash` when mixing the 'errexit' option and calling functions from conditional pipelines.
While here, document `-s` in the script's usage.
Fixes #3757

tools/packaging: Fix error path in `kata-deploy-binaries.sh -s`

---

docs/how-to/ccv0.sh
docs/how-to/how-to-build-and-test-ccv0.md

- We've updated the CC logging scripts to log to the journal
rather than a socket, so remove socat scripts and instructions
to reflect this
Depends-on: github.com/kata-containers/tests#4610
Fixes: #3928

docs: Update to reflect logging changes

---

src/runtime/pkg/containerd-shim-v2/wait.go
src/runtime/virtcontainers/monitor.go

Stop getting OOM events from agent for "ttrpc closed" error
Backport of #3989

stable-2.4 | runtime: Stop getting OOM events from agent for "ttrpc closed" error

---

src/runtime/cmd/kata-monitor/main.go

(default: "/run/containerd/containerd.sock") is duplicated when
printing kata-monitor usage:
[root@kubernetes ~]# kata-monitor --help
Usage of kata-monitor:
-listen-address string
The address to listen on for HTTP requests. (default ":8090")
-log-level string
Log level of logrus(trace/debug/info/warn/error/fatal/panic). (default "info")
-runtime-endpoint string
Endpoint of CRI container runtime service. (default: "/run/containerd/containerd.sock") (default "/run/containerd/containerd.sock")
the golang flag package takes care of adding the defaults when printing
usage. Remove the explicit print of the value so that it would not be
printed on screen twice.
Fixes: #3998
Backport of #3999

stable-2.4 | kata-monitor: fix duplicated output when printing usage

---

docs/how-to/how-to-use-kata-containers-with-acrn.md

This PR removes the kata-proxy reference from this document as it is
not longer a component in kata 2.0
Fixes #4013

docs: Remove kata-proxy reference

---

tools/packaging/kata-deploy/README.md

The idea is to pass this README file to kata-doc-to-script.sh script and
then execute the result.
Added comments with a file name on top of each YAML snippet.
This helps in assigning a file name when we cat the YAML to a file.
Fixes: #3943
Signed-off-by: David Esparza <david.esparza.borquez@intel.com>

doc: Improve kata-deploy README.md by changing sh blocks to bash blocks

---

src/agent/rustjail/src/process.rs
src/agent/src/rpc.rs

The nix::sys::signal::Signal package api cannot deal with SIGRTMIN+3,
directly use libc function to send the signal.
Fixes: #3990
Signed-off-by: Wang Xingxing <stellarwxx@163.com>

agent: fix container stop error with signal SIGRTMIN+3

---

docs/how-to/ccv0.sh
docs/how-to/how-to-build-and-test-ccv0.md

Refactor image verification documentation to be more user
focussed, using crictl rather than agent-ctl and re-using the
integration test config files
Fixes: #3958

CCv0: Refactor image verification doc and tests

---

versions.yaml

This release changes Docker images repository from DockerHub to Amazon
ECR. This resolves the `You have reached your pull rate limit` error
when building the firecracker tarball.
Fixes #4001

versions: Bump firecracker to v0.23.4

---

src/agent/Cargo.lock
src/agent/Cargo.toml
src/agent/src/config.rs
src/agent/src/image_rpc.rs

Containerd can support set a proxy when downloading images with a environment variable.
For CC stack, image download is offload to the kata agent, we need support similar feature.
Fixes #3956
Signed-off-by: Arron Wang <arron.wang@intel.com>

CCv0: agent: Support https_proxy config for image download in guest

---

src/runtime/config/configuration-clh.toml.in

This configuration option is valid for all the hypervisor that are going
to be used with the confidential containers effort, thus exposing the
configuration option for Cloud Hypervisor as well.
Fixes: #4022

clh: Expose service offload configuration

---

src/runtime/pkg/katautils/config.go
src/runtime/virtcontainers/hypervisor.go
src/runtime/virtcontainers/hypervisor_test.go
src/runtime/virtcontainers/qemu.go

Previously, it was not permitted to have neither an initrd nor an image.
However, this is the exact config to use for Secure Execution, where the
initrd is part of the image to be specified as `-kernel`. Require the
configuration of no initrd for Secure Execution.
Also
- remove redundant code for image/initrd checking -- no need to check in
`newQemuHypervisorConfig` (calling) when it is also checked in
`getInitrdAndImage` (called)
- use `QemuCCWVirtio` constant when possible
Fixes: #3922
and an extra fix

runtime: Allow and require no initrd for SE

---

src/runtime/virtcontainers/kata_agent.go
src/runtime/virtcontainers/kata_agent_test.go

fix the issue I have mentioned in #3695 kata-runtime doesn't pass the hugepages params to kata-agent.

kata-runtime enable hugepage support

---

docs/how-to/ccv0.sh
docs/how-to/how-to-build-and-test-ccv0.md

ccv0: Don't use the QEMU process to get the sandbox ID
Instead, rely on the conntainerd-shim-kata-v2 process, as this makes
this script VMM agnostic.
---
ccv0.sh: Expand to also using Cloud Hypervisor
Right now the script only support QEMU, but there's not a reason to do
that, mainly considering we already have the tests parity in the CIs
between QEMU and Clouud Hypervisor.
With this in mind, let's expand this script to also using Cloud
Hypervisor.
Whether this script should use QEMU or Cloud Hypervisor is defined
according to the KATA_HYPERVISOR environment variable.
Fixes: #4038
---
@stevenhorsman, please, take a look at the changes and let me know if you want something done differently.

CCv0 | ccv0.sh: Expand to also using Cloud Hypervisor

---

src/libs/protocols/.gitignore

After running make in src/agent, the git working area will be changed:
Untracked files:
(use "git add <file>..." to include in what will be committed)
src/libs/protocols/src/csi.rs
The generated file by `build.rs` should be ignored in git.
Fixes: #3959

protocols: add src/csi.rs to .gitignore

---

src/agent/Makefile

This allows the kata-agent to be rebuilt when Cargo "features" is
changed. The Makefile for the agent do not need to specify the
sources for prerequisites by having Cargo check for the sources
changes.
Fixes: #4052

agent: Allow the agent to be rebuilt with the change of Cargo features

---

src/agent/rustjail/src/lib.rs

Add test coverage for the process_grpc_to_oci function in src/rustjail/lib.rs
Fixes #4058

rustjail: add test coverage for process_grpc_to_oci function

---

src/runtime/config/configuration-clh.toml.in
src/runtime/config/configuration-qemu.toml.in
src/runtime/virtcontainers/clh.go
src/runtime/virtcontainers/qemu.go
src/runtime/virtcontainers/virtiofsd.go
src/runtime/virtcontainers/virtiofsd_test.go

virtiofsd's debug will be enabled if hypervisor's debug has been
enabled, this will generate too many noisy logs from virtiofsd.
Unbind the relationship of log level between virtiofsd and
hypervisor, if users want to see debug log of virtiofsd,
can set it by:
virtio_fs_extra_args = ["-o", "log_level=debug"]
Fixes: #3303

runtime: delete debug option in virtiofsd

---

src/agent/src/rpc.rs
src/agent/src/sandbox.rs

Add test coverage for do_write_stream function of AgentService
in src/rpc.rs. Includes minor refactoring to make function more
easily testable.
Fixes #3984

agent: add tests for do_write_stream function

---

src/agent/src/mount.rs

Add test coverage for the parse_mount_flags_and_options function
in src/mount.rs.
Fixes #4056

agent: add test coverage for parse_mount_flags_and_options function

---

src/agent/src/mount.rs

Add test coverage for mount_storage function in src/mount.rs.
Fixes: #4068

agent: add tests for mount_storage

---

docs/Limitations.md

This PR updates the url link to the contributions guide
at the Limitations document.
Fixes #4070

docs: Update link to contributions guide

---

src/agent/rustjail/src/cgroups/fs/mod.rs

This was seen in an issue report, where we'd try to unwrap a None value,
leading to a panic.
Fixes: #4077
Related: #4043
Full backtrace:
```
"thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', rustjail/src/cgroups/fs/mod.rs:593:31"
"stack backtrace:"
"   0:     0x7f0390edcc3a - std::backtrace_rs::backtrace::libunwind::trace::hd5eff4de16dbdd15"
"                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5"
"   1:     0x7f0390edcc3a - std::backtrace_rs::backtrace::trace_unsynchronized::h04a775b4c6ab90d6"
"                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5"
"   2:     0x7f0390edcc3a …
```

agent: Avoid agent panic when reading empty stats

---

src/runtime/cmd/kata-monitor/main.go
src/runtime/pkg/kata-monitor/metrics.go
src/runtime/pkg/kata-monitor/monitor.go
src/runtime/pkg/kata-monitor/pprof.go

Add some links to rendered webpages for better user experience,
let users can jump to pages only by clicking links in browsers.
Fixes: #4061

kata-monitor: add some links when generating pages for browsers

---

src/runtime/virtcontainers/virtiofsd.go

The scanner readis nothing from viriofsd stderr pipe, because param
'--syslog' rediercts stderr to syslog. So there is no need to write
scanner.Text() to kata log.
Fixes: #4063
Signed-off-by: tiezhuoyu <tiezhuoyu@outlook.com>

runtime: no need to write virtiofsd error to log

---

src/agent/rustjail/src/cgroups/fs/mod.rs

This was seen in an issue report, where we'd try to unwrap a None value,
leading to a panic.
Fixes: #4077
Related: #4043
Full backtrace:
```
"thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', rustjail/src/cgroups/fs/mod.rs:593:31"
"stack backtrace:"
"   0:     0x7f0390edcc3a - std::backtrace_rs::backtrace::libunwind::trace::hd5eff4de16dbdd15"
"                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5"
"   1:     0x7f0390edcc3a - std::backtrace_rs::backtrace::trace_unsynchronized::h04a775b4c6ab90d6"
"                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5"
"   2:     0x7f0390edcc3a …
```

stable-2.4 | agent: Avoid agent panic when reading empty stats

---

src/runtime/pkg/kata-monitor/pprof.go
src/runtime/pkg/kata-monitor/pprof_test.go

kata-monitor allows to get data profiles from the kata shim
instances running on the same node by acting as a proxy
(e.g., http://$NODE_ADDRESS:8090/debug/pprof/?sandbox=$MYSANDBOXID).
In order to proxy the requests and the responses to the right shim,
kata-monitor requires to pass the sandbox id via a query string in the
url.
The profiling index page proxied by kata-monitor contains the link to all
the data profiles available. All the links anyway do not contain the
sandbox id included in the request: the links result then broken when
accessed through kata-monitor.
This happens because the profiling index page comes from the kata shim,
which will not include the query string provided in the http request.
Let's add on-the-fly the sandbox id in each one of the href tags returned
by the …

kata-monitor: update the hrefs in the debug/pprof index page

---

docs/design/kata-2-0-metrics.md
src/runtime/README.md
src/runtime/cmd/kata-monitor/README.md

The documentation we already had was in the metrics 2.0 design document.
Added the kata-monitor README, trying to not duplicate info (or at least not too much) and linking back the the metrics 2.0 design document.
Fixes: #3704

kata-monitor: add the README file

---

src/runtime/cmd/kata-runtime/kata-check_s390x_test.go

This PR is to fix a test failure for the `kata-containers-2.0-ubuntu-20.04-s390x-main-baseline` jenkins job. (See the log http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-20.04-s390x-main-baseline/196/console)
Fixes: #4088 

test: Fix golangci-lint error for s390x

---

src/agent/src/sandbox.rs

During container exit, the agent tries to remove all the mount point directories,
which can fail if it's a readonly filesytem (e.g. device mapper). This commit ignores
the removal failure and logs a warning message.
Fixes: #4043

agent: best-effort removing mount point

---

src/agent/src/rpc.rs

Add test coverage for is_signal_handled function in rpc.rs. Includes
refactors to make the function testable and handle additional cases.
Fixes #3939

agent: add tests for is_signal_handled function

---

src/agent/rustjail/src/lib.rs

Add test coverage for root_grpc_to_oci in rustjail/src/lib.rs
Fixes: #4095

rustjail: Add tests for root_grpc_to_oci

---

src/agent/src/config.rs
src/agent/src/rpc.rs
src/agent/src/test_utils.rs

Move the assert_result macro to the shared test_utils file
so that it is not duplicated in individual files.
Fixes: #4093

agent: move assert_result macro to test_utils file

---

src/runtime/cmd/kata-runtime/kata-volume.go
src/runtime/pkg/direct-volume/utils.go
src/runtime/pkg/direct-volume/utils_test.go
src/runtime/virtcontainers/kata_agent.go

This is to avoid accidentally deleting multiple volumes.
Fixes #4020
(cherry picked from commit 354cd3b9b6e62c35be902b926fb900c32c6bb604)

stable-2.4 | runtime: Base64 encode the direct volume mountInfo path

---

src/agent/rustjail/src/cgroups/fs/mod.rs
src/agent/rustjail/src/lib.rs
src/libs/oci/src/lib.rs
src/tools/agent-ctl/src/utils.rs

The type of MemorySwappiness in runtime is uint64, and the type of swappiness in agent is int64,
if we set max uint64 in runtime and pass it to agent, the value will be equal to -1. We should
modify the type of swappiness to u64
Fixes: https://github.com/kata-containers/kata-containers/issues/4123
Signed-off-by: yangfeiyu <yangfeiyu20102011@163.com>

agent: modify the type of swappiness to u64

---

src/agent/rustjail/src/lib.rs

Add test coverage for hooks_grpc_to_oci in rustjail/src/lib.rs
Fixes: #4142

rustjail: Add tests for hooks_grpc_to_oci

---

src/runtime/pkg/containerd-shim-v2/create_test.go
src/runtime/pkg/containerd-shim-v2/delete_test.go
src/runtime/pkg/containerd-shim-v2/service_test.go
src/runtime/pkg/katatestutils/utils.go
src/runtime/pkg/katautils/create_test.go
src/runtime/pkg/katautils/hook_test.go
src/runtime/virtcontainers/factory/cache/cache_test.go
src/runtime/virtcontainers/factory/direct/direct_test.go
src/runtime/virtcontainers/factory/factory_test.go
src/runtime/virtcontainers/factory/template/template_test.go
src/runtime/virtcontainers/fc.go
src/runtime/virtcontainers/kata_agent_test.go
src/runtime/virtcontainers/mount_test.go
src/runtime/virtcontainers/persist/fs/fs.go
src/runtime/virtcontainers/persist/fs/fs_test.go
src/runtime/virtcontainers/persist/fs/mockfs.go
src/runtime/virtcontainers/persist/fs/mockfs_test.go
src/runtime/virtcontainers/persist/manager.go
src/runtime/virtcontainers/persist/manager_test.go
src/runtime/virtcontainers/virtcontainers_test.go

A number of the Go unit tests leave things behind in `/tmp`.  As described in #4140, this isn't ideal.  Fix them to clean up after themselves.

Fix Go unit tests to clean up /tmp after themselves

---

tools/packaging/static-build/cloud-hypervisor/build-static-clh.sh

A recent change introduced a typo that could cause `pull_clh_released_binary()` to fail. This in turn revealed a flaw in `build_clh_from_source()` that would simply terminate the build.
This never did visible harm because kata-deploy force-builds clh from source for TDX. Fix these two anyway.
Fixes: #4151

packaging: Fix broken path in `build-static-clh.sh`

---

src/agent/rustjail/src/lib.rs

Add test coverage for mount_grpc_to_oci in rustjail/src/lib.rs
Fixes: #4106

rustjail: Add tests for mount_grpc_to_oci

---

docs/design/virtualization.md

Currently the 'pc' machine type is no longer supported in kata configuration,
so remove it in the design docs.
Fixes: #4155
Signed-off-by: Jason Zhang <zhanghj.lc@inspur.com>

docs: remove pc machine type supports

---

docs/install/container-manager/containerd/containerd-install.md

This PR updates the containerd url link for the installation guide
Fixes #4162

docs: Update containerd link to installation guide

---

tools/packaging/kata-deploy/README.md
tools/packaging/kata-deploy/kata-cleanup/overlays/rke2/kustomization.yaml
tools/packaging/kata-deploy/kata-cleanup/overlays/rke2/mount_rke2_conf.yaml
tools/packaging/kata-deploy/kata-deploy/overlays/rke2/kustomization.yaml
tools/packaging/kata-deploy/kata-deploy/overlays/rke2/mount_rke2_conf.yaml
tools/packaging/kata-deploy/scripts/kata-deploy.sh

"RKE2 - Rancher's Next Generation Kuberentes Distribution" can easily be
supported by kata-deploy with some simple adjustments to what we've been
relying on for "k3s".
The main differences between k3s and RKE2 are, basically:
1. The location where the containerd configuration is stored
- k3s: /var/lib/rancher/k3s/agent/etc/containerd/
- rke2: /var/lib/rancher/rke2/agent/etc/containerd/
2. The name of the systemd services used:
- k3s: k3s.service or k3s-agent.service
- rke2: rke2-server.service or rke2-agent.service
Knowing this, let's add a new overlay for RKE2, adapt the kata-deploy
and the kata-cleanup scripts, and that's it.
Fixes: #4160

kata-deploy: Add support to RKE2

---

src/tools/agent-ctl/README.md
src/tools/agent-ctl/src/client.rs

Unbreak the `agent-ctl` tool connecting to the agent with a Unix domain
socket.
It appears that [1] changed the behaviour of connecting to the agent
using a local Unix socket (which is not used by Kata under normal
operation).
The change can be seen by reverting to commit
72b8144b569f1d0fef3001642f244bf79b17ddc6 (the one before [1]) and
running the agent manually as:
```bash
$ sudo KATA_AGENT_SERVER_ADDR=unix:///tmp/foo.socket target/x86_64-unknown-linux-musl/release/kata-agent
```
Before [1], in another terminal we see this:
```bash
$ sudo lsof -U 2>/dev/null |grep foo|awk '{print $9}'
@/tmp/foo.socket@
```
But now, we see the following:
```bash
$ sudo lsof -U 2>/dev/null |grep foo|awk '{print $9}'
@/tmp/foo.socket
```
Note the last byte which represents a nul (`\0`) value.
The …

agent-ctl: Fix abstract socket connections

---

src/tools/runk/README.md

The default runtime for io.containerd.runc.v2 is runc,
to use runk, the containerd configuration should set the
default runtime to runk or add BinaryName options for the
runtime.
Fixes: #4177

runk: set BinaryName for runk for containerd

---

src/agent/src/main.rs
src/agent/src/mount.rs
src/agent/src/test_utils.rs

Add tests for create_logger_task function in src/main.rs.
Fixes: #4113
I am interested in feedback on ideas for being able to test more with this function. One particular problem I ran into when trying to add more tests was getting the `util::get_vsock_stream` future used in `create_logger_task` to complete execution.

agent: add tests for create_logger_task function

---

src/runtime/virtcontainers/clh.go
src/runtime/virtcontainers/clh_test.go

We're currently hitting a race condition on the Cloud Hypervisor's
driver code when quickly removing and adding a block device.
This happens because the device removal is an asynchronous operation,
and we currently do *not* monitor events coming from Cloud Hypervisor to
know when the device was actually removed.  Together with this, the
sandbox code doesn't know about that and when a new device is attached
it'll quickly assign what may be the very same ID to the new device,
leading to the Cloud Hypervisor's driver trying to hotplug a device with
the very same ID of the device that was not yet removed.
This is, in a nutshell, why the tests with Cloud Hypervisor and
devmapper have been failing every now and then.
The workaround taken to solve the issue is basically *not* passing down
the …

clh: Rely on Cloud Hypervisor for generating the device ID

---

src/agent/rustjail/src/lib.rs

Add test coverage for hook_grpc_to_oci in rustjail/src/lib.rs
Fixes: #4125
I'm opening this one on behalf of @garrettmahin

rustjail: Add tests for hook_grpc_to_oci

---

src/agent/src/sandbox.rs

Add test coverage for the functions `find_process` and `online_resources` in `src/sandbox.rs`.
This pull request supersedes #4084 
Fixes #4085
Fixes #4136
Signed-off-by: Jack Hance <jack.hance@ndsu.edu>

agent: add test coverage for functions find_process and online_resources

---

src/tools/runk/src/commands/kill.rs
src/tools/runk/src/main.rs

runk uses liboci-cli crate to parse command line options,
but liboci-cli does not support --all option for kill command,
though this is the runtime spec behavior.
But crictl will issue kill --all command when stopping containers,
as a workaround, we use a custom kill command instead of the one
provided by liboci-cli.
Fixes: #4182
PTAL @ManaSugi

runk: use custom Kill command to support --all option

---

src/agent/src/mount.rs
src/agent/src/test_utils.rs

Add a macro to skip a loop easier without using a
if {} else {} condition check.
Fixes: #4185

agent: Add a macro to skip a loop easier

---

versions.yaml

The following issues have been addressed from the latest bug fix release v23.1 of Cloud Hypervisor:
1. Add some missing seccomp rules;
2. Remove virtio-fs filesystem entries from config on removal;
3. Do not delete API socket on API server start;
4. Reject virtio-mem resize if the guest doesn't activate the device;
5. Fix OpenAPI naming of I/O throttling knobs;
Fixes: #4222

versions: Upgrade to Cloud Hypervisor v23.1

---

.github/workflows/kata-deploy-push.yaml
.github/workflows/kata-deploy-test.yaml
.github/workflows/release.yaml
tools/packaging/kata-deploy/local-build/Makefile
tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
tools/packaging/static-build/virtiofsd/build-static-virtiofsd.sh
versions.yaml

This PR is the x86_64 kata-containers part of switching to the rust virtiofsd.  I still need to work on the tests counterpart of this PR, but we need to start from somewhere. :-)
For now we're only adding support for shipping the rust virtiofsd binary, **without** removing the C one.
The removal will be done once the tests counterpart is raised and merged.

Build and distribute the rust version of virtiofsd

---

docs/how-to/privileged.md

As we are using a containerd version > 1.4 we need to update
the runc containerd runtime.
Fixes #4263

docs: Update runc containerd runtime

---

tools/packaging/qemu/patches/6.2.x/0001-numa-Enable-numa-for-SGX-EPC-sections.patch
tools/packaging/qemu/patches/6.2.x/0002-numa-Support-SGX-numa-in-the-monitor-and-Libvirt-int.patch
tools/packaging/qemu/patches/6.2.x/0003-doc-Add-the-SGX-numa-description.patch

There are a few patches for SGX numa support in QEMU added after the
6.2.0 release. Add them for SGX support in Kata.
Fixes #4254

tools: Add QEMU patches for SGX numa support

---

tools/packaging/qemu/patches/6.2.x/0001-numa-Enable-numa-for-SGX-EPC-sections.patch
tools/packaging/qemu/patches/6.2.x/0002-numa-Support-SGX-numa-in-the-monitor-and-Libvirt-int.patch
tools/packaging/qemu/patches/6.2.x/0003-doc-Add-the-SGX-numa-description.patch

There are a few patches for SGX numa support in QEMU added after the
6.2.0 release. Add them for SGX support in Kata.
Fixes #4254
(cherry picked from commit b4b9068cb7136172614a231649f50dae09dd1027)

stable-2.4 | tools: Add QEMU patches for SGX numa support

---

.github/workflows/docs-url-alive-check.yaml

This workflow is a scheduled job that runs at 23:00
every Sunday, it should only run the main repo
but not the forked ones.
Fixes: #4219
**NOTE:** This is review-able but I added a DNM label for verification.
/cc @Bevisy @jodh-intel

ci: Don't run Docs URL Alive Check workflow on forks

---

src/agent/src/rpc.rs

In the is_signal_handled function, when parsing the hex string returned
from `/proc/<pid>/status` the space/tab character after the colon
is not removed.
This patch trims the result of SigCgt so that
all whitespace characters are removed. It also extends the existing
test cases to check for this scenario.
Fixes: #4250
Signed-off-by: Champ-Goblem <cameron@northflank.com>

agent: Fix is_signal_handled failing parsing str to u64

---

tools/packaging/scripts/gen_versions_txt.sh
tools/packaging/static-build/cloud-hypervisor/build-static-clh.sh
tools/packaging/static-build/firecracker/build-static-firecracker.sh

The param was deleted by a09e58fa80ae81c0d336d9a782da4f38f9492da1, so
update the callers not to use it.
Fixes #4245
Signed-off-by: Rafael Fonseca <r4f4rfs@gmail.com>

tools: delete unused param from get_from_kata_deps callers

---

src/runtime/virtcontainers/sandbox.go

The documentation of the bufio package explicitly says
"Err returns the first non-EOF error that was encountered by the
Scanner."
When io.EOF happens, `Err()` will return `nil` and `Scan()` will return
`false`.
Fixes #4079
Signed-off-by: Rafael Fonseca <r4f4rfs@gmail.com>

runtime: do not check for EOF error in console watcher

---

tools/osbuilder/rootfs-builder/README.md

This PR removes the clear containers reference as this is not longer
being used and is deprecated at the rootfs builder README.
Fixes #4278

docs: Remove clear containers reference in README

---

docs/how-to/how-to-set-sandbox-config-kata.md
src/runtime/config/configuration-qemu.toml.in
src/runtime/pkg/katautils/config-settings.go.in
src/runtime/pkg/katautils/config.go
src/runtime/pkg/oci/utils.go
src/runtime/pkg/oci/utils_test.go
src/runtime/virtcontainers/hypervisor.go
src/runtime/virtcontainers/pkg/annotations/annotations.go
src/runtime/virtcontainers/qemu.go
src/runtime/virtcontainers/qemu_amd64.go
src/runtime/virtcontainers/qemu_arch_base.go
src/runtime/virtcontainers/qemu_arch_base_test.go
src/runtime/virtcontainers/qemu_arm64.go
src/runtime/virtcontainers/qemu_ppc64le.go
src/runtime/virtcontainers/qemu_s390x.go

This allows to get guest early boot logs which are usually
missed when virtconsole is used.
- It utilizes previous work on the govmm side:
kata-containers/govmm#203
- unit test added
Fixes: kata-containers#4237

qemu: allow using legacy serial device for the console

---

src/runtime/virtcontainers/acrn.go
src/runtime/virtcontainers/clh.go
src/runtime/virtcontainers/fc.go
src/runtime/virtcontainers/qemu.go

The functions were renamed but their docstrings were not.
Fixes #4006
Signed-off-by: Rafael Fonseca <r4f4rfs@gmail.com>

runtime: sync docstrings with function names

---

src/runtime/virtcontainers/device/drivers/utils.go
src/runtime/virtcontainers/device/drivers/vfio.go
src/runtime/virtcontainers/device/drivers/vfio_test.go

runtime: Adding the correct detection of mediated PCIe devices

---

docs/how-to/ccv0.sh

- Add call to install_virtiofsd.sh
- Remove the qemu build in the cloud_hypervisor path
Fixes: #4286

CCv0: Fix ccv0.sh to install virtiofsd

---

src/runtime/cmd/kata-runtime/kata-volume.go

The action function expects a function that returns error
but the current direct-volume stats Action returns
(string, error) which is invalid.
This change fixes the format and print out the stats from
the command instead.
Fixes: #4293
Signed-off-by: Yibo Zhuang <yibzhuang@gmail.com>

runtime: fix incorrect Action function for direct-volume stats

---

src/agent/src/rpc.rs
src/runtime/cmd/kata-runtime/kata-volume.go
src/runtime/pkg/containerd-shim-v2/shim_management.go

This PR contains the changes needed to make direct-assigned volume stats work as expected.
NOTE: The agent code is derived from @egernst's original PR #1792
1. direct-volume stats update to use GET parameter.
The go default http mux AFAIK doesn’t support pattern
routing so right now client is padding the url
for direct-volume stats with a subpath of the volume
path and this will always result in 404 not found returned
by the shim. This change will update the shim to take the volume
path as a GET query parameter instead of a subpath.
If the parameter is missing or empty, then return
400 BadRequest to the client.
2. direct-volume stats use correct name.
Today the shim does a translation when doing
direct-volume stats where it takes the source and
returns the mount path within the guest.
The …

Fix issues with direct-volume stats feature

---

snap/snapcraft.yaml

Update the snap config file to build the rust version of `virtiofsd` for
x86_64, but build QEMU's C version for other platforms.
Fixes: #4261.

snap: Build and package rust version of virtiofsd

---

src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/PlatformConfig.md
src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_platform_config.go
src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
versions.yaml

This release has been tracked through the v24.0 project.
virtio-iommu specification describes how a device can be attached by default
to a bypass domain. This feature is particularly helpful for booting a VM with
guest software which doesn't support virtio-iommu but still need to access
the device. Now that Cloud Hypervisor supports this feature, it can boot a VM
with Rust Hypervisor Firmware or OVMF even if the virtio-block device exposing
the disk image is placed behind a virtual IOMMU.
Multiple checks have been added to the code to prevent devices with identical
identifiers from being created, and therefore avoid unexpected behaviors at boot
or whenever a device was hot plugged into the VM.
Sparse mmap support has been added to both VFIO and vfio-user devices. This
allows the device …

stable-2.4 | clh: Update to the v24.0 release

---

src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/PlatformConfig.md
src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_platform_config.go
src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
versions.yaml

This release has been tracked through the v24.0 project.
virtio-iommu specification describes how a device can be attached by default
to a bypass domain. This feature is particularly helpful for booting a VM with
guest software which doesn't support virtio-iommu but still need to access
the device. Now that Cloud Hypervisor supports this feature, it can boot a VM
with Rust Hypervisor Firmware or OVMF even if the virtio-block device exposing
the disk image is placed behind a virtual IOMMU.
Multiple checks have been added to the code to prevent devices with identical
identifiers from being created, and therefore avoid unexpected behaviors at boot
or whenever a device was hot plugged into the VM.
Sparse mmap support has been added to both VFIO and vfio-user devices. This
allows the device …

clh: Update to v24.0

---

src/runtime/virtcontainers/device/drivers/utils.go
src/runtime/virtcontainers/device/drivers/vfio.go
src/runtime/virtcontainers/device/drivers/vfio_test.go

Fixes #4212
Backport-of: https://github.com/kata-containers/kata-containers/pull/4213

stable-2.4: runtime: Adding the correct detection of mediated PCIe devices

---

src/agent/rustjail/src/console.rs
src/tools/runk/Makefile

First commit: 
agent: Remove unused import in console test                
Remove some unused imports in console test module
used by runk's test.                                          
Second commit:
runk: Enable test for the agent built with standard-oci-runtime feature 
This enables tests for the kata-agent for runk that is built            
with standard-oci-runtime feature in CI.                                
Fixes: #4351                                                            

agent, runk: Enable test for the agent built with standard-oci-runtime feature 

---

src/tools/runk/README.md

runk can launch containers using Podman, so add the guide
in README.
Fixes: #4338

runk: Add Podman guide in README

---

tools/osbuilder/rootfs-builder/alpine/config.sh
tools/osbuilder/rootfs-builder/centos/config.sh
tools/osbuilder/rootfs-builder/clearlinux/config.sh
tools/osbuilder/rootfs-builder/debian/config.sh
tools/osbuilder/rootfs-builder/ubuntu/config.sh

Since we are introducing an agent API for interacting with guest
iptables, let's ensure that our example rootfs' have iptables-save/restore
installed.
Fixes: #4356

osbuilder: add iptables package

---

docs/use-cases/using-Intel-QAT-and-kata.md

This PR updates some Intel QAT documentation url links.
Fixes #4374

docs: Update Intel QAT documentation links

---

src/agent/src/mount.rs

Include mount file content in error message when parsing
mountinfo failed for debug.
Fixes: #4246, #4103

agent: return mount file content if parse mountinfo failed

---

README.md
snap/local/README.md
snap/local/snap-common.sh
snap/snapcraft.yaml
tools/packaging/Makefile
tools/packaging/README.md

Move the common shell code to a helper script that is sourced by all
parts.
Add extra quoting to some variables in the snap config file
and simplify.
Fixes: #4304.

snap: Use helper script and cleanup

---

.github/workflows/kata-deploy-test.yaml
docs/Release-Process.md

This will allow to trigger the test-kata-deploy workflow manually from
any branch instead of using always the one that is defined on main
While here, let's also update the doc how to use it and with some github_token instructions
See: https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
Depends-on: github.com/kata-containers/tests#4823 (to fix static checks)
Fixes: #4349

workflows: add workflow_dispatch triggering to test-kata-deploy

---

src/agent/rustjail/src/container.rs
src/runtime/pkg/containerd-shim-v2/wait.go

Kata agent can return ESRCH to the agent.stopContainer call,
which causes shim leak.
Fixes: #4359

runtime: ignore ESRCH error from stop container

---

src/agent/rustjail/src/container.rs
src/runtime/pkg/containerd-shim-v2/wait.go

See https://github.com/kata-containers/kata-containers/issues/4359

My 2.4 pr backport -- fix shim leak caused by ESRCH in agent destroy

---

src/tools/runk/Cargo.lock
src/tools/runk/Cargo.toml
src/tools/runk/src/commands/list.rs
src/tools/runk/src/commands/mod.rs
src/tools/runk/src/main.rs

Support list sub-command. It will traverse the root directory, parse status file and print basic information of containers. Behavior and print format consistent with runc. To handle race with runk delete or system user modify, the loop will continue to traverse when errors are encountered.
Fixes: #4362
Signed-off-by: Chen Yiyang <cyyzero@qq.com>

runk: Support `list` sub-command

---

src/tools/agent-ctl/README.md

Add a new `Examples` section to the `agent-ctl` docs giving some
examples of how to use the tool with QEMU and stand-alone.
Fixes: #4414.

docs: Add agent-ctl examples section

---

src/tools/agent-ctl/src/main.rs
src/tools/trace-forwarder/src/main.rs

The `agent-ctl` and `trace-forwarder` tools make use of
`anyhow::Context` to provide additional call site information on error.
However, previously neither tool was using the "alternate debug" format
to display the error, meaning full error output was not displayed.
Fixes: #4411.

tools: Enable extra detail on error

---

docs/how-to/containerd-kata.md
src/tools/runk/README.md

Kubernetes-incubator was previously deprecated in favor of
kubernetes-sigs.
Fixes #4377

docs: Update source for cri-tools

---

docs/design/architecture/storage.md

Updated the architecture document to explain that if you wish to
constrain the amount of disk space a container uses, you need to use an
existing facility such as `quota(1)`s or device mapper limits.
Fixes: #4430.

docs: Add storage limits to arch doc

---

versions.yaml

Changes since v1.2.0:
!123  Update rust-vmm dependencies                           (main) ← (update-deps)
!121  implement std::error::Error trait                      (main) ← (fix-impl-error)
!120  Show the nofile hard limit value in the warning me...  (main) ← (fix-rlimit-warn)
!119  Do not create tmpdir and bind mount /proc/self/fd ...  (main) ← (remove-tmp-dir-for-proc)
!116  Disable killpriv_v2 by default                         (main) ← (no-killpriv-default)
The one that affected Kata Containers the most was !119, as virtiofsd
would get denied when SELinux was set to run on enforcing mode.
Fixes: #4433

versions: Bump virtiofsd to v1.3.0

---

src/runtime/cmd/kata-monitor/README.md

Add more detail to the `kata-monitor` doc to allow an admin to make a
more informed decision about where and how to run the daemon.
Fixes: #4416.

docs: Add more kata monitor details

---

src/runtime/pkg/containerd-shim-v2/wait.go

GetOOMEvent is a blocking call that will fail if
the container exit, in this case, it's not an error or warning.
Changing the log level for logs in case of GetOOMEvent call fails
will reduce log noise in a large cluster that has pods
creating/deleting frequently.
Fixes: #4376

shim: change the log level for GetOOMEvent call failures

---

snap/snapcraft.yaml
src/runtime/Makefile
tools/packaging/scripts/configure-hypervisor.sh
tools/packaging/static-build/virtiofsd/build-static-virtiofsd.sh

So far this has been done for x86_64.  Now that the support for building
and testing has been added for all arches, let's do the full switch.
Fixes: #4258, #4259, #4260

runtime: Switch to using the rust version of virtiofsd (all arches but powerpc)

---

src/libs/safe-path/src/pinned_path_buf.rs
src/libs/safe-path/src/scoped_dir_builder.rs

fix clippy warnings in safe-path lib to make clippy happy.
fixes: #4443 

safe-path: fix clippy warning

---

src/agent/src/mount.rs

In the original code, reads mountstats file and return
the content in the error, but at this time the file maybe
changed, we should return the file content that parsed
line by line to check why there is not a fstype option.
Fixes: #4246

agent: refactor reading file timing for debugging

---

docs/Developer-Guide.md

This PR updates the containerd url link in the Developer Guide.
Fixes #4451

docs: Update containerd url link

---

src/runtime/virtcontainers/clh.go
src/runtime/virtcontainers/clh_test.go
src/runtime/virtcontainers/fc.go
src/runtime/virtcontainers/network_linux.go

Cloud Hypervisor, currently, cannot run under the `container_kvm_t` label, as it opens the tuntap device using device's name, causing the following SELinux AVC:
```
type=PROCTITLE msg=audit(1653421182.755:146064): proctitle=2F6F70742F6B6174612F62696E2F636C6F75642D68797065727669736F72002D2D6170692D736F636B6574002F72756E2F76632F766D2F366331626530336235653437396639666637363265313566633937306266663932303337663562376334353562663639656237323630663838343964373632382F636C682D6170692E
type=SYSCALL msg=audit(1653421182.755:146064): arch=c000003e syscall=2 success=yes exit=54 a0=7f964538e51b a1=80802 a2=0 a3=0 items=0 ppid=344244 pid=344254 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="vmm" exe="/opt/kata/bin/cloud-hypervisor" …
```

Allow Cloud Hypervisor to run under the `container_kvm_t`

---

src/runtime/pkg/oci/utils.go
src/runtime/pkg/oci/utils_test.go

Changed bitsize for parsing functions to 64-bit in order to avoid
parsing errors.
Fixes #4435

runtime: fix error when trying to parse sandbox sizing annotations

---

docs/how-to/how-to-build-and-test-ccv0.md
tools/osbuilder/rootfs-builder/rootfs.sh

Fix of the attestation-agent build and install issue in rootfs.sh after the crate structure changed
Update the doc to clarify the skopeo requirement
Fixes: #4465

osbuilder: Fix attestation-agent build

---

src/runtime/pkg/containerd-shim-v2/create.go

Remove space from root span name to follow camel casing of other tracing
span names in the runtime and to make parsing easier in testing.
Fixes #4483

tracing: Remove whitespace from root span

---

tools/osbuilder/rootfs-builder/rootfs.sh

In at least kata versions 2.3.3 and 2.4.0 it was noticed that the guest operating system's clock would drift out of sync slowly over time whilst the pod was running.
This had previously been raised and fixed in the old reposity via [1] . In essence kvm_ptp and chrony were paired together in order to keep the system clock up to date with the host.
In the recent versions of kata metioned above, the chronyd.service fails upon boot with status `266/NAMESPACE` which seems to be due to the fact that the `/var/lib/chrony` directory no longer exists.
This change sets the `/var/lib/chrony` directory for the `ReadWritePaths` to be ignored when the directory does not exist, as per [2].
[1] https://github.com/kata-containers/runtime/issues/1279
[2] …

rootfs: Fix chronyd.service failing on boot

---

src/runtime/Makefile
src/runtime/config/configuration-qemu.toml.in
src/runtime/pkg/govmm/qemu/qemu.go
src/runtime/pkg/katautils/config.go
src/runtime/virtcontainers/hypervisor.go
src/runtime/virtcontainers/persist.go
src/runtime/virtcontainers/persist/api/config.go
src/runtime/virtcontainers/qemu.go

Enable "-sandbox on" in qemu can introduce another protect layer
on the host, to make the secure container more secure.
The default option is disable because this feature may introduce some
performance cost, even though user can enable
/proc/sys/net/core/bpf_jit_enable to reduce the impact.
Fixes: #2266

runtime: enable sandbox feature on qemu

---

src/runtime/go.mod
src/runtime/go.sum
src/runtime/vendor/gitlab.com/nvidia/cloud-native/go-nvlib/LICENSE
src/runtime/vendor/gitlab.com/nvidia/cloud-native/go-nvlib/pkg/nvpci/bytes/bytes.go
src/runtime/vendor/gitlab.com/nvidia/cloud-native/go-nvlib/pkg/nvpci/bytes/native.go
src/runtime/vendor/gitlab.com/nvidia/cloud-native/go-nvlib/pkg/nvpci/bytes/swapbo.go
src/runtime/vendor/gitlab.com/nvidia/cloud-native/go-nvlib/pkg/nvpci/config.go
src/runtime/vendor/gitlab.com/nvidia/cloud-native/go-nvlib/pkg/nvpci/mmio/mmio.go
src/runtime/vendor/gitlab.com/nvidia/cloud-native/go-nvlib/pkg/nvpci/mmio/mock.go
src/runtime/vendor/gitlab.com/nvidia/cloud-native/go-nvlib/pkg/nvpci/mock.go
src/runtime/vendor/gitlab.com/nvidia/cloud-native/go-nvlib/pkg/nvpci/nvpci.go
src/runtime/vendor/gitlab.com/nvidia/cloud-native/go-nvlib/pkg/nvpci/resources.go
src/runtime/vendor/modules.txt
src/runtime/virtcontainers/qemu.go
src/runtime/virtcontainers/qemu_arch_base.go

Add heuristic to get the right values for mem-reserve and pref-64-reserve. 
Fixes: #2938

runtime: Add heuristic to get the right value(s) for mem-reserve

---

.github/workflows/snap-release.yaml
.github/workflows/snap.yaml
tools/osbuilder/rootfs-builder/rootfs.sh

In at least kata versions 2.3.3 and 2.4.0 it was noticed that the guest
operating system's clock would drift out of sync slowly over time
whilst the pod was running.
This had previously been raised and fixed in the old reposity via [1].
In essence kvm_ptp and chrony were paired together in order to
keep the system clock up to date with the host.
In the recent versions of kata metioned above,
the chronyd.service fails upon boot with status `266/NAMESPACE`
which seems to be due to the fact that the `/var/lib/chrony`
directory no longer exists.
This change sets the `/var/lib/chrony` directory for the `ReadWritePaths`
to be ignored when the directory does not exist, as per [2].
[1] https://github.com/kata-containers/runtime/issues/1279
[2] https://www.freedesktop.org/software/systemd …

stable-2.4 | rootfs: Fix chronyd.service failing on boot

---

src/runtime/virtcontainers/clh.go
src/runtime/virtcontainers/qemu.go

Similar to network, we can use multiple queues for virtio-block
devices. This can help improve storage performance.
This commit changes the number of queues for block devices to
the number of cpus for cloud-hypervisor and qemu.
Today the default number of cpus a VM starts with is 1.
Hence the queues used will be 1. This change will help
improve performance when the default cold-plugged cpus is greater
than one by changing this in the config file. This may also help
when we use the sandboxing feature with k8s that passes down
the sum of the resources required down to Kata.
Fixes #4502

block: Leverage multiqueue for virtio-block

---

docs/how-to/ccv0.sh
docs/how-to/how-to-setup-swap-devices-in-guest-kernel.md
docs/how-to/how-to-use-virtio-fs-nydus-with-kata.md
docs/how-to/how-to-use-virtio-mem-with-kata.md

- Ensure that our documented crictl pod config file contents have
uid  and namespace fields for compatibility with crictl 1.24+
Fixes: https://github.com/kata-containers/kata-containers/issues/4513

doc: Update crictl pod-config

---

src/agent/Cargo.lock
src/agent/src/netlink.rs
src/agent/src/random.rs

Some agent warnings were caught by an update of dependencies in the CCv0 branch, and I've decided to fix those here first, and also run a `cargo update` before the release.
Please, take a look at the commits for more details.
Fixes: #4523 #4525

Fix clippy warnings and update agent's vendored code

---

docs/how-to/ccv0.sh

export PS1, so it is bound
Fixes: #4531

CCv0: Fix PS1 unbound error

---

src/agent/Cargo.lock
src/agent/Cargo.toml
src/agent/src/image_rpc.rs
src/agent/src/netlink.rs
src/agent/src/random.rs

Let's pin a specific version of image-rs, one that pins a specific
version of ocicrypt-rs on their side, and ensure we don't fall into
issues by consuming the content from `main` on those repos, and also
helping to ensure reproducible builds from our side.
Fixes: #4517 
---
Note: with this we also update the vendored dependencies.

CCv0 | agent: Pin a specific version of image-rs

---

src/runtime/pkg/containerd-shim-v2/service.go
src/runtime/pkg/containerd-shim-v2/shim_io_binary.go
src/runtime/pkg/containerd-shim-v2/shim_io_file.go
src/runtime/pkg/containerd-shim-v2/shim_io_pipe.go
src/runtime/pkg/containerd-shim-v2/start.go
src/runtime/pkg/containerd-shim-v2/stream.go
src/runtime/pkg/containerd-shim-v2/stream_test.go
src/runtime/vendor/github.com/containerd/containerd/pkg/ioutil/read_closer.go
src/runtime/vendor/github.com/containerd/containerd/pkg/ioutil/write_closer.go
src/runtime/vendor/github.com/containerd/containerd/pkg/ioutil/writer_group.go
src/runtime/vendor/modules.txt

Now kata shim only supports stdout/stderr of fifo from
containerd/CRI-O, but shim v2 supports logging plugins,
and nerdctl default will use the binary schema for logs.
This commit will add the others type of log plugins:
- file
- binary
In case of binary, kata shim will receive a stdout/stderr like:
binary:///nerdctl?_NERDCTL_INTERNAL_LOGGING=/var/lib/nerdctl/1935db59
That means the nerdctl process will handle the logs(stdout/stderr)
Fixes: #4420

shim: support shim v2 logging plugin

---

docs/how-to/run-kata-with-k8s.md

This commit updates the "Run Kata Containers with Kubernetes" to include
cgroupDriver configuration via "KubeletConfiguration". Without this
setting kubeadm defaults to systemd cgroupDriver. Containerd with Kata
cannot spawn conntainers with systemd cgroup driver.

kata-with-k8s: Add cgroupDriver for containerd

---

versions.yaml

As we're still depending on components that are only being tested on
Ubuntu, let's make sure the VM image distributed is exactly the same
we've been testing.
Fixes: #4551

CC | versions: Always use ubuntu as rootfs for CC

---

src/runtime/pkg/containerd-shim-v2/wait.go
src/runtime/virtcontainers/sandbox.go

Return code is an int32 type, so if an error occurred, the default value
may be zero, this value will be created as a normal exit code.
Set return code to 255 will let the caller(for example Kubernetes) know
that there are some problems with the pod/container.
Fixes: #4419

shim: set a non-zero return code if the wait process call failed.

---

tools/packaging/guest-image/build_image.sh
tools/packaging/kata-deploy/local-build/Makefile
tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh

Let's add a new build target for our local-build scripts,
cc-rootfs-image-tarball, and use it to build an image that has skopeo
and umoci embedded in, and that using the offline_fs_kbc as the
attenstation agent KBC.
Fixes: #4557

CC | Build the rootfs image with skopeo, umoci, and using an offline_fs_kbc

---

src/runtime/cmd/kata-runtime/factory_test.go
src/runtime/cmd/kata-runtime/main_test.go
src/runtime/pkg/containerd-shim-v2/create.go
src/runtime/pkg/containerd-shim-v2/create_test.go
src/runtime/pkg/containerd-shim-v2/utils_test.go
src/runtime/pkg/katautils/create.go
src/runtime/pkg/katautils/create_test.go
src/runtime/pkg/oci/utils.go
src/runtime/pkg/oci/utils_test.go
src/runtime/virtcontainers/types/sandbox.go

There is much code related to this property, but it is not used anymore.
Fixes: #4553

runtime: delete Console from Cmd type

---

ci/lib.sh

Set `safe.directory` against `kata-containers/tests` repository
before checkout because the user in the docker container is root,
but the `tests` repository on the host machine is usually owned
by the normal user.
This works when we already have the `tests` repository which is
not owned by root on the host machine and try to create a rootfs
using Docker (`USE_DOCKER=true`).
Fixes: #4561

Set safe.directory against tests repository

---

src/runtime/pkg/containerd-shim-v2/wait.go
src/runtime/virtcontainers/sandbox.go

Return code is an int32 type, so if an error occurred, the default value
may be zero, this value will be created as a normal exit code.
Set return code to 255 will let the caller(for example Kubernetes) know
that there are some problems with the pod/container.
Fixes: #4419
(cherry picked from commit ab5f1c9564fcdf4d5797db9b3f59333061ec6df2)

stable-2.4 | shim: set a non-zero return code if the wait process call failed.

---

tools/packaging/kata-deploy/local-build/Makefile
tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
tools/packaging/static-build/qemu/build-static-qemu-cc.sh

For the very first milestone towards a release, we're targeting something working with the Operator in a **non**-TEE CI.
For that, we need to have Cloud Hypervisor, QEMU, Kernel, and virtiofsd (as we're not using devmapper in our CI yet) built using a destdir that matches with the modified components ("/opt/confidential-containers/....").
Here, in this series, we're adding all the missing pieces.
Fixes: #4566, #4567, #4568. #4569

CC | packaging: Add a build target for all the "unmodified" components

---

.github/workflows/commit-message-check.yaml

Recently added check-commit-message to the tests repository. Minor
changes were also made to action. For consistency's sake, copied changes
over to here as well.
tests - https://github.com/kata-containers/tests/pull/4878
Minor Changes:
1. Body length check is now 75 and consistent with guidelines
2. Lines without spaces are not counted in body length check
Fixes #4559
Signed-off-by: Derek Lee <derlee@redhat.com>

ci/cd: update check-commit-message

---

tools/packaging/static-build/shim-v2/build.sh

While doing a docker build for shim-v2, we see this:
```
fatal: unsafe repository
('/home/${user}/go/src/github.com/kata-containers/kata-containers' is
owned by someone else)
To add an exception for this directory, call:
git config --global --add safe.directory
/home/${user}/go/src/github.com/kata-containers/kata-containers
```
This is because the docker container build is run as root while the
runtime repo is checked out as normal user.
Unlike this error causing the rootfs build to error out, the error here
does not really cause `make shim-v2-tarball` to fail.
However its good to get rid of this error message showing during the
make process.
Fixes: #4572

build: Set safe.directory for runtime repo

---

src/runtime/pkg/oci/utils.go
src/runtime/pkg/oci/utils_test.go

Some clients like nerdctl may pass mount type of none for volumes/bind mounts,
this will lead to container start fails.
Referring to runc, it overwrites the mount type to bind and ignores the input value.
Fixes: #4548

runtime: overwrite mount type to bind for bind mounts

---

src/agent/rustjail/src/container.rs
src/agent/src/main.rs

Replace `libc::setgroups()`, `libc::fchown()`, and `libc::sethostname()`
functions with nix crate ones for safety and maintainability.
Fixes: #4579

agent: Replace some libc functions with nix ones

---

src/agent/rustjail/src/container.rs
src/agent/src/rpc.rs

Run the OCI `poststart` hooks must be called after the
user-specified process is executed but before the `start`
operation returns in accordance with OCI runtime spec.
Fixes: #4575

agent: Run OCI poststart hooks after a container is launched

---

src/libs/oci/src/lib.rs

There is an extra space on the serde serialization condition.
Fixes: #4578 
Signed-off-by: haining.cao <haining.cao@daocloud.io>

oci: fix serde skip serializing condition

---

src/dragonball/Cargo.toml
src/dragonball/src/vcpu/aarch64.rs
src/dragonball/src/vcpu/vcpu_impl.rs

This pull request adds Vcpu::configure() function for aarch64.
Fixes: #4445

runtime-rs: Dragonball sandbox - add Vcpu::configure() function for aarch64

---

src/runtime/README.md
src/runtime/pkg/katautils/config.go
src/runtime/pkg/katautils/config_test.go

This PR adds support for drop-in configuration files stored in a `config.d` directory at the same path where the main `configuration.toml` file is located.
The PR is meant to be backwards-compatible - if no drop-in directory is found or if it's empty, the current behaviour is preserved.  Drop-ins will only override the specific settings that they contain, there should be no collateral damage to other settings loaded from the main `configuration.toml` anywhere in the configuration.  Drop-in files handling aims to follow existing conventions - the files are evaluated in alphabetical order and the last one to modify a specific setting wins.
Individual commits in this series are ordered bottom-up so that earlier commits build up foundations that later commits then use until the new …

Drop in cfg files support

---

.github/workflows/commit-message-check.yaml

So that we can add move info there and few people use such small
terminals nowadays.
Fixes: #4596

action: revert commit message limit to 150 bytes

---

docs/Developer-Guide.md
docs/use-cases/using-Intel-QAT-and-kata.md
snap/snapcraft.yaml
tools/osbuilder/dockerfiles/QAT/run.sh
tools/packaging/kata-deploy/local-build/Makefile
tools/packaging/kernel/build-kernel.sh
tools/packaging/static-build/qemu/Dockerfile

Replaces calls of nproc	with nproc with
nproc ${CI:+--ignore 1}
to run nproc with one less processing unit than the maximum to prevent
DOS-ing the local machine.
If process is being run in a container (determined via whether $CI is
null), all processing units avaliable will be used.
Fixes #3967
Signed-off-by: Derek Lee <derlee@redhat.com>

tools/snap: simplify nproc

---

docs/how-to/containerd-kata.md

This PR updates some url links related with containerd documentation.
Fixes #4615

docs: Update URL links for containerd documentation

---

src/runtime/config/configuration-acrn.toml.in
src/runtime/config/configuration-clh.toml.in
src/runtime/config/configuration-fc.toml.in
src/runtime/config/configuration-qemu.toml.in
src/runtime/pkg/katautils/config.go

Enable Kata runtime to handle `disable_selinux` flag properly in order
to be able to change the status by the runtime configuration whether the
runtime applies the SELinux label to VMM process.
Fixes: #4599

runtime: Fix DisableSelinux config

---

tools/packaging/kata-deploy-cc/Dockerfile
tools/packaging/kata-deploy-cc/scripts/kata-deploy.sh
tools/packaging/kata-deploy/scripts/kata-deploy.sh

Although I don't like the duplication introduced here, it's (at least
for now) way cleaner to have a specific daemonset for the Confidential
Containers effort.
As soon as we have all the bits and pieces upstreamed (kernel, QEMU, and
specific dependencies for each one of the TEEs), we'll be easily able to
get rid of this one.  However, for now, focusing on this different set
of files will make our lives easier.
This new daemonset includes the configurations needed for containerd in
order to use the `cc` specific `cri_handler`, which is not and will not
be upstream on the containerd side.
Note, CRI-O is **not** supported for now.

CC | Introduce kata-deploy-cc

---

src/dragonball/Cargo.toml
src/dragonball/docs/api.md
src/dragonball/src/address_space_manager.rs
src/dragonball/src/api/v1/boot_source.rs
src/dragonball/src/api/v1/instance_info.rs
src/dragonball/src/api/v1/machine_config.rs
src/dragonball/src/api/v1/mod.rs
src/dragonball/src/api/v1/vmm_action.rs
src/dragonball/src/config_manager.rs
src/dragonball/src/device_manager/blk_dev_mgr.rs
src/dragonball/src/device_manager/console_manager.rs
src/dragonball/src/device_manager/fs_dev_mgr.rs
src/dragonball/src/device_manager/memory_region_handler.rs
src/dragonball/src/device_manager/mod.rs
src/dragonball/src/device_manager/virtio_net_dev_mgr.rs
src/dragonball/src/device_manager/vsock_dev_mgr.rs
src/dragonball/src/error.rs
src/dragonball/src/event_manager.rs
src/dragonball/src/lib.rs
src/dragonball/src/vcpu/aarch64.rs
src/dragonball/src/vcpu/mod.rs
src/dragonball/src/vcpu/vcpu_impl.rs
src/dragonball/src/vcpu/vcpu_manager.rs
src/dragonball/src/vm/aarch64.rs
src/dragonball/src/vm/kernel_config.rs
src/dragonball/src/vm/mod.rs
src/dragonball/src/vm/x86_64.rs
src/dragonball/src/vmm.rs

In this PR, we introduce the abstractions for the virtio-blk, virtio-fs, virtio-net manager, and VMM API support for the runtime to communicate with VMM in one process.

runtime-rs: built-in Dragonball sandbox part III - virtio-blk, virtio-fs, virtio-net and VMM API support

---

tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
tools/packaging/static-build/cloud-hypervisor/build-static-clh.sh

While running make as non-privileged user, the make errors out with
the following message:
"INFO: Build cloud-hypervisor enabling the following features: tdx
Got permission denied while trying to connect to the Docker daemon
socket at unix:///var/run/docker.sock: Post
"http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/create?fromImage=cloudhypervisor%2Fdev&tag=20220524-0":
dial unix /var/run/docker.sock: connect: permission denied"
Even though the user may be part of docker group, the clh build from
source does a docker in docker build. It is necessary for the user of
the nested container to be part of docker build for the build to
succeed.
Fixes #4594

Fix clh tarball build

---

.github/workflows/docs-url-alive-check.yaml

repository_owner check in docs-url-alive-check.yaml now is specified for each step, it can be in job level to save lines.
Fixes: #4611
Signed-off-by: Yuan-Zhuo <yuanzhuo0118@outlook.com>

build: save lines for repository_owner check

---

tools/packaging/kata-deploy/scripts/kata-deploy.sh

Both CRI-O and containerd expose the option for the admin to set the
configuration path that should be used by a specific runtime.
All the versions of CRI-O and containerd supported have that option, and
switching to using this option makes our code cleaner.
Fixes: #4608

packaging: Simplify config path handling

---

src/dragonball/src/device_manager/legacy.rs
src/dragonball/src/device_manager/mod.rs
src/dragonball/src/error.rs
src/dragonball/src/vm/aarch64.rs
src/dragonball/src/vm/mod.rs

In this PR, we introduce two virtio device features for aarch64.
First, we implement generate_virtio_device_info() and get_virtio_mmio_device_info() funtions to support the mmio_device_info member, which is used by FDT.
Second, we add the implementation of legacy device on aarch64 platform.

runtime-rs: Dragonball-sandbox - add virtio device feature support for aarch64

---

tools/packaging/kata-deploy/local-build/Makefile
tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
tools/packaging/kernel/build-kernel.sh

We're adding a new target for building a TDX capable kernel for CC.
This commit, differently than c4cc16efcd946f225c6b010e5dd916f7fc86a326,
introduces support for building the artefacts that are TEE specific.
Fixes: #4622
---
**NOTE**: This PR has a hard dependency on https://github.com/kata-containers/kata-containers/pull/4628.
For now I'm adding a `do-not-merge` label as we need that PR reviewed and merged before acting on this one.

CC | packaging: Allow building a TDX capable kernel

---

tools/packaging/kata-deploy/local-build/Makefile
tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
tools/packaging/static-build/qemu/Dockerfile
tools/packaging/static-build/qemu/build-static-qemu-cc.sh
tools/packaging/static-build/qemu/build-static-qemu-experimental.sh
tools/packaging/static-build/scripts/qemu-build-post.sh

We're adding a new target for building a TDX capable QEMU for CC.
This commit, differently than b307531c29d951c18f993c41ff344721f6e42b89,
introduces support for building the artefacts that are TEE specific.
Fixes: #4623
---
Note, this PR depends on https://github.com/kata-containers/kata-containers/pull/4639

cc | packaging: Allow building a TDX capable QEMU

---

src/runtime/virtcontainers/clh.go

`ctr` doesn't setup a network device when creating the sandbox, which
leads to Cloud Hypervisor's driver crashing, see the log below:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x55641c23b248]
goroutine 32 [running]:
github.com/kata-containers/kata-containers/src/runtime/virtcontainers.glob..func1(0xc000397900)
/home/ubuntu/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/clh.go:163 +0x128
github.com/kata-containers/kata-containers/src/runtime/virtcontainers.(*cloudHypervisor).vmAddNetPut(...)
/home/ubuntu/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/clh.go:1348
github.com/kata-containers/kata-containers/src/runtime/virtcontainers.(*cloud …
```

clh: Don't crash if no network device is set by the upper layer

---

src/agent/rustjail/src/container.rs
src/tools/runk/Cargo.lock
src/tools/runk/Cargo.toml
src/tools/runk/libcontainer/Cargo.toml
src/tools/runk/libcontainer/src/builder.rs
src/tools/runk/libcontainer/src/container.rs
src/tools/runk/libcontainer/src/utils.rs
src/tools/runk/src/commands/create.rs
src/tools/runk/src/commands/exec.rs
src/tools/runk/src/commands/mod.rs
src/tools/runk/src/commands/run.rs
src/tools/runk/src/main.rs

`exec` will execute a command inside a container which exists and is not
frozon or stopped. *Inside* means that the new process share namespaces
and cgroup with the container init process. Command can be specified by
`--process` parameter to read from a file, or from other parameters such
as arg, env, etc.
Fixes #4363
Signed-off-by: Chen Yiyang <cyyzero@qq.com>

runk: Support `exec` sub-command

---

tools/packaging/kata-deploy/local-build/Makefile
tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh

We're adding a new target for building a TDX capable Cloud Hypervisor
for CC.
As the current version of Cloud Hypervisor is already built with TDX
support, we just rely on calling the same `install_cc_clh()` function,
as done for the non-tee `cc` target.
Fixes: #4659

CC | packaging: Build and ship Cloud Hypervisor

---

src/dragonball/src/vm/aarch64.rs
src/runtime-rs/Cargo.lock
src/runtime-rs/Cargo.toml
src/runtime-rs/arch/aarch64-options.mk
src/runtime-rs/crates/hypervisor/src/device/vfio.rs

This PR fixes some bugs when use "make" in runtime-rs directory. 
1. fix a vcpu_manager warning in dragonball
2. fix a module use warning in runtime-rs
3. add compile option file for aarch64
4. update dbs-xxx dependencies in runtime-rs/Cargo.toml

runtime-rs: fix some bugs to make runtime-rs on aarch64

---

src/runtime-rs/crates/resource/src/cgroups/utils.rs

When run with configuration `sandbox_cgroup_only=false`, we will call
`gen_overhead_path()` as the overhead path. The `cgroup-rs` will push
the path with the subsystem prefix by `PathBuf::push()`. When the path
has prefix “/” it will act as root path, such as
```
let mut path = PathBuf::from("/tmp");
path.push("/etc");
assert_eq!(path, PathBuf::from("/etc"));
```
So we shoud not set overhead path with prefix "/".
Fixes: #4687

runtime-rs: fix sandbox_cgroup_only=false panic

---

docs/how-to/how-to-build-and-test-ccv0.md

We don't need skopeo to get the encrypted container image
scenario working, so remove that instruction from the doc
Fixes: #4587

doc: Remove skopeo requirement from doc

---

versions.yaml

This PR updates the firecracker version that is being
used in kata CI.
Fixes #4717

versions: Update firecracker version

---

src/agent/rustjail/src/cgroups/fs/mod.rs

Change get_mounts to get paths from a borrowed argument rather than
calling get_paths a second time.
Fixes #3768
Signed-off-by: Derek Lee <derlee@redhat.com>

cgroups: remove unnecessary get_paths()

---

versions.yaml

Upgrade nydus/nydus-snapshotter to the latest version.
Nydus 2.0.0 can't work correctly, so use v2.1.0-alpha.4 instead.
Later will upgrade to a stable version.
The tests side: https://github.com/kata-containers/tests/pull/4952

upgrade nydus version

---

src/libs/Cargo.lock
src/runtime-rs/crates/resource/src/network/endpoint/endpoints_test.rs
src/runtime-rs/crates/resource/src/network/endpoint/macvlan_endpoint.rs
src/runtime-rs/crates/resource/src/network/endpoint/mod.rs
src/runtime-rs/crates/resource/src/network/endpoint/vlan_endpoint.rs
src/runtime-rs/crates/resource/src/network/network_with_netns.rs
src/runtime-rs/crates/resource/src/network/utils/link/manager.rs

Add macvlan and vlan support to runtime-rs code and corresponding unit
tests.
Fixes: #4701

runtime-rs: add functionalities support for macvlan and vlan endpoints

---

src/agent/src/rpc.rs

The fd will closed on struct Process's dropping, so don't
close it again manually.
Fixes: #4598

agent: fix fd-double-close problem in ut test_do_write_stream

---

src/libs/kata-types/src/config/hypervisor/dragonball.rs

when the default_vcpus is greater than the default_maxvcpus, the default
vcpu number should be set equal to the default_maxvcpus.
Fixes: #4712

runtime-rs: handle default_vcpus greator than default_maxvcpu

---

src/runtime-rs/crates/resource/src/network/network_info/network_info_from_link.rs
src/runtime-rs/crates/resource/src/network/network_model/tc_filter_model.rs

Fix bug using tc filter and protocol needs to use network byte order.
Fixes: #4726
Update route destination with prefix.
Fixes: #4726

fix network failed for kata ci

---

src/agent/rustjail/src/container.rs

When a container terminated, we should make sure there's no processes
left after destroying the container.
Before this commit, kata-agent depended on the kernel's pidns
to destroy all of the process in a container after the 1 process
exit in a container. This is true for those container using a
separated pidns, but for the case of shared pidns within the
sandbox, the container exit wouldn't trigger the pidns terminated,
and there would be some daemon process left in this container, this
wasn't expected.
Fixes: #4663

container: kill all of the processes in a container when it terminated

---

src/agent/rustjail/src/process.rs

The fd would be closed on Pipestream's dropping and we should
not close it agian.
Fixes: #4752

agent: Fix stream fd's double close

---

tools/packaging/static-build/qemu/Dockerfile

io_uring is a Linux API for asynchronous I/O introduced in qemu 5.0.
It is designed to better performance than older `aio` API.
We could leverage this in order to get better storage performance.
Add liburing-dev to qemu build so that we can make use of it.
Fixes: #4645

qemu: Add liburing to qemu build

---

versions.yaml

This PR updates the runc version to v1.1.0.
Fixes #4757

versions: Update runc version

---

src/agent/src/tracer.rs

We can log all RPC calls to the agent for debugging purposes
to check which RPC is called, which can help us to understand
the container lifespan.
Fixes: #4738

agent: log RPC calls for debugging

---

tools/packaging/static-build/td-shim/Dockerfile
tools/packaging/static-build/td-shim/build-td-shim.sh
tools/packaging/static-build/td-shim/build.sh
versions.yaml

TD-shim is a simplified TDX virtual firmware, used by Cloud Hypervisor,
in order to create a TDX capable VM.
TD-shim is heavily under development, and is hosted as part of the
Confidential Containers project:
https://github.com/confidential-containers/td-shim
The version chosen for this commit, is a version that's being tested
inside Intel, but we, most likely, will need to change it before we have
it officially packaged as part of an official release.
Fixes: #4779

versions: Track and add support for building TD-shim

---

tools/packaging/static-build/ovmf/Dockerfile
tools/packaging/static-build/ovmf/build-ovmf.sh
tools/packaging/static-build/ovmf/build.sh
versions.yaml

TDVF is the firmware used by QEMU to start TDX capable VMs.  Let's start
tracking it as it'll become part of the Confidential Containers sooner
or later.
TDVF lives in the public https://github.com/tianocore/edk2-staging repo
and we're using as its version tags that are consumed internally at
Intel.
Fixes: #4624

packaging: Add support for building TDVF

---

tools/packaging/static-build/ovmf/build-ovmf.sh
tools/packaging/static-build/td-shim/build-td-shim.sh

Let's create the OVMF / td-shim tarball in the directory where the script was
called from, instead of doing it in the $DESTDIR.
This aligns with the logic being used for creating / extracting the
tarball content, which is already in use by the kata-deploy local build
scripts.
Fixes: #4808, #4809

OVMF / td-shim: Adjust final tarball location

---

tools/packaging/kata-deploy/local-build/Makefile
tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
tools/packaging/static-build/ovmf/build-ovmf.sh
tools/packaging/static-build/td-shim/build-td-shim.sh

We're adding a new target for building a TDVF and TD-shim, firmwares used with QEMU and Cloud Hypervisor, respectively,
to start TDX capable VMs for CC.
NOTE: This PR backports two patches that are about to be merged on the `main` branch - https://github.com/kata-containers/kata-containers/pull/4810
Fixes: #4625, #4780

CC | packaging: Build and ship TDVF and TD-shim

---

src/agent/Cargo.lock
src/agent/Cargo.toml
src/agent/src/netlink.rs

Bump rtnetlink version from 0.8.0 to 0.11.0. Use rtnetlinks's API to
add neighbors and fix issues to adapt new verson of rtnetlink.
Fixes: #4607
Signed-off-by: Xuewei Niu <justxuewei@apache.org>

agent: Use rtnetlink's neighbours API to add neighbors

---

docs/use-cases/using-Intel-SGX-and-kata.md

Update documentation with details regarding
intel-device-plugins-for-kubernetes setup and dependencies.
Fixes #4819

docs: Improve SGX documentation

---

src/runtime-rs/Makefile
src/runtime-rs/arch/s390x-options.mk

Depends-on: github.com/kata-containers/tests#4986. To avoid returning an error when running the ci, we just skip the build
process if the arch is s390x
Fixes: #4816

runtime-rs:skip the build process when the arch is s390x

---

src/tools/runk/libcontainer/src/builder.rs
src/tools/runk/libcontainer/src/container.rs
src/tools/runk/src/commands/kill.rs
src/tools/runk/src/commands/mod.rs
src/tools/runk/src/commands/ps.rs
src/tools/runk/src/main.rs

ps command supprot two formats, `json` and `table`. `json` format just
outputs pids in the container. `table` format will use `ps` utilty in
the host, search and output all processes in the container. Add a struct
`container` to represent a spawned container. Move the `kill`
implemention from kill.rs as a method of `container`.
Fixes: #4361
Signed-off-by: Chen Yiyang <cyyzero@qq.com>

runk: add ps sub-command

---

docs/Limitations.md

Kata Containers doesn't support host network namespace,
it's a common issue for new users. The limitation
is deleted, this commit will add them back.
Also, Docker has support to run containers using
Kata Containers, delete Docker from not support list.
This commit reverts parts of #3710
Fixes: #4794

docs: add back host network limitation

---

src/runtime/virtcontainers/kata_agent.go

Unlock is required before return, so there need to add unlock
Fixes: #4827
Signed-off-by: chmod100 <letfu@outlook.com>

runtime: add unlock before return in sendReq

---

src/runtime/virtcontainers/qemu.go

In qemu.StopVM(), if debug is enabled, the shim will dump logs
from qemu.log, but users don't know which logs are from qemu.log
and shim itself. Adding some additional messages will
help users to distinguish these logs.
Fixes: #4745

runtime: explicitly mark the source of the log is from qemu.log

---

src/tools/agent-ctl/Cargo.toml

"An empty [workspace] can be used with a package to conveniently create a
workspace with the package and all of its path dependencies", according
to the https://doc.rust-lang.org/cargo/reference/workspaces.html
This is also matches with the suggestion provided by the Cargo itself,
due to the errors faced with the Cloud Hypervisor CI:
```
10:46:23 this may be fixable by adding `go/src/github.com/kata-containers/kata-containers/src/tools/agent-ctl` to the `workspace.members` array of the manifest located at: /tmp/jenkins/workspace/kata-containers-2-clh-PR/Cargo.toml
10:46:23 Alternatively, to keep it out of the workspace, add the package to the `workspace.exclude` array, or add an empty `[workspace]` table to the package's manifest.
```
Fixes: #4843
Signed-off-by: Fabiano Fidêncio …

agent-ctl: Add an empty [workspace]

---

versions.yaml

"We need a newer nightly 1.62 rust to deal with the change
rust-lang/libc@576f778 on crate libc which breaks the compilation."
This comes from the a pull-request raised on TD-shim repo,
https://github.com/confidential-containers/td-shim/pull/354, which fixes
the issues with the commit being used with Kata Containers.
Let's bump to a newer commit of TD-shim and to a newer version of the
nightly toolchain as part of our versions file.
Fixes: #4840

versions: Update TD-shim due to build breakage

---

src/runtime/virtcontainers/nydusd.go
src/runtime/virtcontainers/nydusd_test.go

If the API server is not ready, the mount call will fail, so before
mounting share fs, we should wait the nydusd is started and
the API server is ready.
Fixes: #4710

nydus: wait nydusd API server ready before mounting share fs

---

versions.yaml

This PR updates the libseccomp version at the versions.yaml that is
being used in the kata CI.
Fixes #4858

versions: Update libseccomp version

---

src/agent/Cargo.lock
src/agent/Cargo.toml

Pick up a new verison of image-rs as the pinned version depended on a
version of ocicrypt-rs that doesn't build anymore
Fixes: #4867

agent: Update pinned verison of image-rs

---

.github/workflows/commit-message-check.yaml
.github/workflows/move-issues-to-in-progress.yaml

These two commits changed some workflow jobs in runtime-rs branch, now this branch has been merged into main, so these custom configurations should be reset.
This PR includes two reverts of these two commits:
https://github.com/kata-containers/kata-containers/commit/97d8c6c0fa2f537340c8587dee6467a26f2bb583
https://github.com/kata-containers/kata-containers/commit/575df4dc4d76ad142206ef18dbcc7a47858f2dfc

Fix some GitHub actions workflow issues

---

docs/install/kata-containers-3.0-rust-runtime-installation-guide.md

use curl as default downloader for runtime-rs @jodh-intel 
Fixes: #4879

docs: use curl as default downloader for runtime-rs

---

docs/how-to/containerd-kata.md

This PR updates the url that we have in our kata containerd
documentation.
Fixes #4915

docs: Update url in containerd documentation

---

tools/osbuilder/rootfs-builder/rootfs.sh
tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in
versions.yaml

For CoCo stack, the pause image is managed by host side,
then it may configure a malicious pause image, we need package
a pause image inside the rootfs and don't the pause image from host.
The reasons we don't pull the pause image inside the guest, one is performance, another is the trusted storage for CoCo is not ready when launch the pause container https://github.com/confidential-containers/documentation/issues/39
Fixes: #4768
Signed-off-by: Wang, Arron <arron.wang@intel.com>

CC | Integrate pause image inside rootfs

---

.github/workflows/release.yaml
.github/workflows/snap-release.yaml

So that we can push 3.x artifacts to the release page.
Fixes: #4919

workflow: trigger release for 3.x releases

---

docs/install/minikube-installation-guide.md

In file docs/install/minikube-installation-guide.md, updated the link target of CRI-O to https://minikube.sigs.k8s.io/docs/handbook/config/#runtime-configuration
Fixes https://github.com/kata-containers/kata-containers/issues/4767
Signed-off-by: Prajwal Borkar <prajwalborkar5075@gmail.com>

Updated the link target of CRI-O 

---

ci/install_libseccomp.sh

Updates the libseccomp version that is being used in the Kata CI.
Fixes: #4858, #4939

ci: Update libseccomp version

---

src/runtime/pkg/containerd-shim-v2/create.go
src/runtime/pkg/containerd-shim-v2/service.go

The root span should exist the duration of the trace. Defer ending span
until the end of the trace instead of end of function. Add the span to
the service struct to do so.
Fixes #4902
The output of the rest of the trace is not affected since the rest of the spans are ultimately derived from a context saved in the service struct, but this is technically a bug and should be backported.

runtime: tracing: End root span at end of trace

---

src/agent/src/config.rs
src/agent/src/image_rpc.rs
src/agent/src/rpc.rs
tools/osbuilder/rootfs-builder/init_trusted_storage.sh
tools/osbuilder/rootfs-builder/rootfs.sh

After these two PR: Add cryptsetup support in Guest kernel and rootfs: https://github.com/kata-containers/kata-containers/pull/4762 and Integrate pause image inside rootfs https://github.com/kata-containers/kata-containers/pull/4769
We can implement the trusted storage for CoCo as describe in: https://github.com/confidential-containers/documentation/issues/39
Frist we will guest provided pause image and use pause sidecar container to host the block volume
Next we will use an shell script with cryptsetup tools to initialize the trust storage.
Since data integrity protection will have huge performance drop, we will enable it by default but introduce an config to allow the user to disable it if they have performance concerns.
Fixed https://github.com/kata-containers/kata-containers/issues/488 …

CC | Implement trusted storage for CoCo

---

src/runtime/virtcontainers/network_linux.go

Error out with the correct interface name and hardware address instead.
Signed-off-by: Hengqi Chen <chenhengqi@outlook.com>

network: Fix error message for setting hardware address on TAP interface

---

src/agent/src/rpc.rs

In some cases do_create_container may return an error, mostly due to
`container.start(process)` call. This commit will do some rollback
works if this function failed.
Fixes: #4749

agent: do some rollback works if case of do_create_container failed

---

src/libs/Cargo.lock
src/libs/kata-types/Cargo.toml
src/libs/kata-types/src/config/drop_in.rs
src/libs/kata-types/src/config/mod.rs

This PR adds handling of drop-in config file fragments to runtime-rs to match the same feature already implemented in golang runtime.  Behaviour of this Rust port should be the same as the Golang version so no additional documentation should be necessary.
The change is fairly non-intrusive, mostly adding new code, but the final commit does involve some refactoring of the existing code.  Admittedly there were multiple ways to achieve the goal of creating a single point that drop-in handling needs to be added to.  Being not entirely clear about the intended usage of `load_raw_from_file()` (a public function, however it doesn't seem to be called from anywhere currently) and `load()` (public as well but only called internally AFAICT) I just went for what seemed to be the simplest and least …

Drop-in cfg files support in runtime-rs

---

tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh

The local-build script should honor the value of SKOPEO exported in the
environment so that it will be able to build the image without skopeo
inside. This remove the hard-coded "SKOPEO=yes".
Fixes #4959

CCv0 | kata-deploy: allow to build the image without skopeo

---

src/agent/Cargo.toml
src/agent/rustjail/Cargo.toml
src/libs/kata-types/Cargo.toml
src/runtime-rs/Cargo.lock
src/runtime-rs/crates/runtimes/virt_container/Cargo.toml
src/tools/agent-ctl/Cargo.lock
src/tools/runk/Cargo.lock
src/tools/trace-forwarder/Cargo.lock

Including thread_local, regex and async-std. We should bump their versions.

Fix depbot reported rust crates dependency security issues

---

src/runtime/config/configuration-clh.toml.in
src/runtime/virtcontainers/clh.go
src/runtime/virtcontainers/qemu_amd64.go

clh: Lift the sharedFS restriction used with TDX
When booting the TDX kernel with `tdx_disable_filter`, as it's been done
for QEMU, VirtioFS can work without any issues.
Whether this will be part of the upstream kernel or not is a different
story, but it easily could make it there as Cloud Hypervisor relies on
the VIRTIO_F_IOMMU_PLATFORM feature, which forces the guest to use the
DMA API, making these devices compatible with TDX.
See Sebastien Boeuf's explanation of this in the
3c973fa7ce208e7113f69424b7574b83f584885d commit:
"""
By using DMA API, the guest triggers the TDX codepath to share some of
the guest memory, in particular the virtqueues and associated buffers so
that the VMM and vhost-user backends/processes can access this memory.
"""
Fixes: #4977
---
clh: Increase API and …

TDX: Get TDX working again with Cloud Hypervisor + a minor change on QEMU's code

---

src/agent/Cargo.lock
src/agent/Cargo.toml
src/agent/src/config.rs
src/libs/kata-types/src/config/agent.rs
src/libs/kata-types/src/config/default.rs
src/runtime-rs/crates/agent/src/kata/agent.rs
src/runtime-rs/crates/agent/src/kata/mod.rs
src/runtime-rs/crates/agent/src/lib.rs
src/runtime-rs/crates/agent/src/types.rs
src/runtime-rs/crates/runtimes/virt_container/src/lib.rs
src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
src/tools/agent-ctl/src/utils.rs

Users can specify the kernel module to be loaded through the agent
configuration in kata configuration file or in pod anotation file.
And information of those modules will be sent to kata agent when
sandbox is created.
Fixes: #4894 
Signed-off-by: Yushuo <y-shuo@linux.alibaba.com>

runtime-rs: support loading kernel modules in guest vm

---

src/runtime/config/configuration-clh.toml.in
src/runtime/virtcontainers/clh.go
src/runtime/virtcontainers/qemu_amd64.go

This PR backports https://github.com/kata-containers/kata-containers/pull/4982, as it'll help us to speed up the process for bringing a CI up, rather than waiting for a week till the next rebase.

CC | Backport fixes for Cloud Hypervisor + TDX

---

src/runtime/Makefile

The `force_tdx_guest` kernel parameter was only needed in the early
development stages of the TDX kernel driver.  We can safely drop it with
the kernel version we've been currently using.
Fixes: #4985

CC | config: Drop `force_tdx_guest` unneeded parameter

---

src/agent/rustjail/src/cgroups/fs/mod.rs
src/agent/rustjail/src/container.rs
src/agent/rustjail/src/mount.rs
src/agent/rustjail/src/validator.rs
src/agent/src/netlink.rs
src/agent/src/rpc.rs

Replaces instances of anyhow!(nix::Error::EINVAL) with other messages to
make it easier to debug.
Fixes #954
Signed-off-by: Derek Lee <derlee@redhat.com>

logging: Replace nix::Error::EINVAL with more descriptive msgs

---

src/agent/src/mount.rs

Somewhere is lack of log info, add more details about
the storage and log when error will help understand
what happened.
Fixes: #4962

agent: add some logs for mount operation

---

src/tools/runk/src/main.rs

Add cli message for init command to tell the user
not to run this command directly.
Fixes: #4367

runk: Add cli message for init command

---

ci/install_libseccomp.sh
tools/osbuilder/rootfs-builder/rootfs.sh
tools/osbuilder/scripts/lib.sh

It would be nice to use `versions.yaml` for the maintainability.
Previously, we have been specified the `libseccomp` and the `gperf` version
directly in this script without using the `versions.yaml` because the current
snap workflow is incomplete and fails.
This is because snap CI environment does not have kata-cotnainers repository
under ${GOPATH}. To avoid the failure, the `rootfs.sh` extracts the libseccomp
version and url in advance and pass them to the `install_libseccomp.sh` as
environment variables.
Fixes: #4941

ci: Use versions.yaml for the libseccomp

---

src/runtime-rs/crates/shim/src/core_sched.rs
src/runtime-rs/crates/shim/src/lib.rs
src/runtime-rs/crates/shim/src/shim_run.rs

Linux 5.14 supports core scheduling to have better security control
for SMT siblings. This PR supports that for Rust runtime when containerd enables SCHED_SCORE in its configuration.
Fixes: #4429

runtime-rs: add support for core scheduling

---

.github/workflows/add-backport-label.yaml
.github/workflows/auto-backport.yaml

A work-in-progress implementation of semi-automating the backporting
process.
This implementation has two steps:
1. Checking whether any associated issues are marked as bugs
If they do, mark with `auto-backport` label
2. On a successful merge, if there is a `auto-backport` label  and there
are any tags of `backport-to-BRANCHNAME`, it calls an action that
cherry-picks the commits in the PR and automatically creates a PR to
those branches.
This action uses https://github.com/sqren/backport-github-action
Currently, I copied and modified the hub-util.sh script from
kata-containers/.github.scripts/hub-util.sh to include a function to
output the labels JSON associated with an issue to find the labels.
If this approach looks good, I will remove that script from here and
make a separate PR to …

github-actions: Auto-backporting

---

tools/packaging/kata-deploy/local-build/.gitignore
tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh

It is needed to pass the `CI` variable down to the kata-deploy build container so that scripts behave as expected. As for example, the `clone_tests_repo()` in `ci/lib.sh` relies on that variable in order to checkout (or not) the tests repository.
This fix can be tested with:
* have at least one file in tests repo in stage
* run `make CI=yes rootfs-image-tarball`
Fixes #4949

Fix kata-deploy to work on CI context

---

tools/osbuilder/rootfs-builder/rootfs.sh

osbuilder: fix ubuntu initrd /dev/ttyS0 hang
osbuilder: add systemd symlinks for kata-agent
Fixes: [#4932](https://github.com/kata-containers/kata-containers/issues/4932)
Signed-Off-By: Ryan Savino <ryan.savino@amd.com>

Initrd fixes for ubuntu systemd

---

docs/how-to/data/confidential-agent-config.toml.in

The agent configuration file, which is part of the docs, is used by the
confidential containers CIs and, right now, cannot be run behind a
firewall, which is exactly how the TDX CIs are reunning, as https_proxy
is not set there.
Fixes: #5020

CC | docs: Add https_proxy to confidential agent config

---

src/runtime-rs/crates/runtimes/virt_container/src/health_check.rs
src/runtime-rs/crates/shim/src/args.rs
src/runtime-rs/crates/shim/src/bin/main.rs
src/runtime-rs/crates/shim/src/shim.rs
src/runtime-rs/crates/shim/src/shim_start.rs

The socket is not used to specify the socket address, but
an ENV variable is used for runtime-rs.
Fixes: #4995

runtime-rs: delete socket from shim command-line options

---

tools/packaging/kernel/build-kernel.sh
versions.yaml

00aadfe20abdcc81b39e7b284efde58f087ae547 introduced a regression on
`make cc-tdx-kernel-tarball` as we stopped passing all the needed
information to the `build-kernel.sh` script, leading to requiring `yq`
installed in the container used to build the kernel.
This commit partially reverts the faulty one, rewritting it in a way the
old behaviour is brought back, without changing the behaviour that was
added by the faulty commit.
Fixes: #5043

kernel: Re-work get_tee_kernel()

---

tools/osbuilder/image-builder/Dockerfile
tools/osbuilder/image-builder/image_builder.sh

One task for issue: https://github.com/confidential-containers/documentation/issues/40
Generate rootfs hash data during creating the kata rootfs,
current kata image only have one partition, we add another
partition as hash device to save hash data of rootfs data blocks.
Fixes: #4966
Signed-off-by: Wang, Arron <arron.wang@intel.com>

CC | image-build: generate root hash as an separate partition for rootfs

---

src/tools/agent-ctl/src/utils.rs
versions.yaml

CI for 2.5 branch is failing with the issue:
"package `time v0.3.14` cannot be built because it requires rustc 1.59.0
or newer, while the currently active rustc version is 1.58.1"
Fixes: #1000

versions: Upgrade rust supported version to 1.59.0 for 2.5 branch

---

src/agent/Cargo.lock
src/agent/Cargo.toml
src/agent/rustjail/Cargo.toml
src/agent/rustjail/src/seccomp.rs
src/tools/agent-ctl/Cargo.lock
src/tools/runk/Cargo.lock
src/tools/trace-forwarder/Cargo.lock

Taken from https://github.com/kata-containers/kata-containers/pull/4930 and https://github.com/kata-containers/kata-containers/pull/4969
69505695b agent-ctl/trace-forwarder: udpate thread_local dependency
48a94f36a agent/runk: update regex dependency
1a396a178 dep: update nix dependency

[stable-2.5] backport security related dependency commits

---

docs/Unit-Test-Advice.md

Specify language for code block in docs/Unit-Test-Advice.md
for syntax highlight.
Fixes: #5064

docs: Specify language in markdown for syntax highlight

---

src/runtime/virtcontainers/acrn.go
src/runtime/virtcontainers/clh.go
src/runtime/virtcontainers/fc.go
src/runtime/virtcontainers/hypervisor.go
src/runtime/virtcontainers/mock_hypervisor.go
src/runtime/virtcontainers/mock_hypervisor_test.go
src/runtime/virtcontainers/qemu.go
src/runtime/virtcontainers/sandbox.go
src/runtime/virtcontainers/sandbox_test.go

If we're using ACPI hotplug for memory, there's a limitation on the
amount of memory which can be hotplugged at a single time.
During hotplug, we'll allocate memory for the memmap for each page,
resulting in a 64 byte per 4KiB page allocation. As an example, hotplugging 12GiB
of memory requires ~192 MiB of *free* memory, which is about the limit
we should expect for an idle 256 MiB guest (conservative heuristic of 75%
of provided memory).
From experimentation, at pod creation time we can reliably add 48 times
what is provided to the guest. (a factor of 48 results in using 75% of
provided memory for hotplug). Using prior example of a guest with 256Mi
RAM, 256 Mi * 48 = 12 Gi; 12GiB is upper end of what we should expect
can be hotplugged successfully into the guest.
Note: It isn't expected …

Address Memory hotplug limitation

---

tools/packaging/static-build/qemu/Dockerfile
tools/packaging/static-build/qemu/build-base-qemu.sh

Dockerfile cannot decipher multiple conditional statements in the main RUN call.
Cannot segregate statements in Dockerfile with '{}' braces without wrapping entire statement in 'bash -c' statement.
Dockerfile does not support setting variables by bash command.
Must set HYPERVISOR_NAME and PKGVERSION from parent script: build-base-qemu.sh
Fixes: #5078
Signed-Off-By: Ryan Savino <ryan.savino@amd.com>

qemu: fix tdx qemu tarball directories

---

tools/packaging/static-build/qemu/Dockerfile
tools/packaging/static-build/qemu/build-base-qemu.sh

In the commit 54d6d01754b689a32da852cfd85a69d2c4730baa we ended up
removing the BUILD_SUFFIX argument passed to QEMU as it only seemed to
be used to generate the HYPERVISOR_NAME and PKGVERSION, which were added
as arguments to the dockerfile.
However, it turns out BUILD_SUFFIX is used by the `qemu-build-post.sh`
script, so it can rename the QEMU binary accordingly.
Let's just bring it back.
Fixes: #5078

qemu: Keep passing BUILD_SUFFIX

---

.github/cargo-deny-composite-action/cargo-deny-generator.sh
.github/cargo-deny-composite-action/cargo-deny-skeleton.yaml.in
.github/workflows/cargo-deny-runner.yaml
ci/lib.sh
deny.toml
src/agent/Cargo.lock
src/agent/Cargo.toml
src/agent/rustjail/Cargo.toml
src/agent/vsock-exporter/Cargo.toml
src/libs/Cargo.lock
src/libs/Cargo.toml
src/libs/logging/Cargo.toml
src/libs/oci/Cargo.toml
src/libs/protocols/Cargo.toml
src/runtime-rs/Cargo.lock
src/runtime-rs/crates/agent/Cargo.toml
src/runtime-rs/crates/hypervisor/Cargo.toml
src/runtime-rs/crates/persist/Cargo.toml
src/runtime-rs/crates/resource/Cargo.toml
src/runtime-rs/crates/runtimes/Cargo.toml
src/runtime-rs/crates/runtimes/common/Cargo.toml
src/runtime-rs/crates/runtimes/virt_container/Cargo.toml
src/runtime-rs/crates/service/Cargo.toml
src/runtime-rs/tests/utils/Cargo.toml
src/tools/agent-ctl/Cargo.lock
src/tools/agent-ctl/Cargo.toml
src/tools/trace-forwarder/Cargo.lock
src/tools/trace-forwarder/Cargo.toml

Adds cargo-deny to scan for vulnerabilities and license issues regarding
rust crates.
Some modifications were required for the repo to pass the tests:
~~Updates ttrpc to avoid using nix 0.16.0
https://rustsec.org/advisories/RUSTSEC-2021-0119~~ (This got fixed in a different PR while this was pending)
~~Updates slog-json to avoid MLP license (copyleft)~~(I ended up allowing copy-left licenses)
Updates crossbeam-channel because 0.52.0 was a yanked package
Ignores https://rustsec.org/advisories/RUSTSEC-2020-0071
because chrono is dependent on that version of time.
chronotope/chrono#578
Allow multiple versions of the same package
(package dependencies require this)
Adds "oci" to src/libs workplace
Adds Apache-2.0 license to workplace modules that did not have them
because cargo-deny complains …

github-actions: Add cargo-deny

---

src/tools/agent-ctl/README.md

Following the instructions in guidance doc will result in the ECONNREFUSED, thus we need to keep the unix socket address in the two commands consistent.
Fixes: #5085
Signed-off-by: Yuan-Zhuo <yuanzhuo0118@outlook.com>

docs: fix unix socket address in agent-ctl doc

---

tools/packaging/kata-deploy-cc/scripts/kata-deploy.sh

For Confidential Containers the file is present at
`/opt/confidential-containers` instead of `/opt/kata`.
Fixes: #5119

kata-deploy: Fix `containerd-shim-kata-v2` location

---

src/libs/kata-types/src/annotations/mod.rs
src/libs/kata-types/src/config/agent.rs
src/libs/kata-types/src/config/default.rs
src/libs/kata-types/src/config/mod.rs
src/libs/kata-types/src/config/runtime.rs

Kata 3.0 introduced 3 new configurations under runtime section:
name="virt_container"
hypervisor_name="dragonball"
agent_name="kata"
Blank values will lead to starting to fail.
Adding default values will make user easy to migrate to kata 3.0.
Fixes: #5098

runtime-rs: add default agent/runtime/hypervisor for configuration

---

src/agent/Cargo.lock
src/agent/Cargo.toml
src/agent/src/netlink.rs
tools/packaging/kata-deploy/action/test-kata.sh

This reverts PR: https://github.com/kata-containers/kata-containers/pull/4770
Using  rtnetlink's neighbours API to add neighbors is causing issues in AKS while adding neighbours. Hence reverting the change for now till we resolve the issue.

Revert arp neighbour api

---

versions.yaml

gperf download fails intermittently.
Changing to mirror site will hopefully increase download reliability.
Fixes: #5057
Signed-Off-By: Ryan Savino <ryan.savino@amd.com>

gperf: point URL to mirror site

---

src/libs/kata-types/src/annotations/mod.rs

Replace tabs by spaces in the comments of file
libs/kata-types/src/annotations/mod.rs.
Fixes: #5115

libs/kata-types: replace tabs by spaces in comments

---

tools/packaging/kata-deploy-cc/scripts/kata-deploy.sh

Let's remove the whole content from:
* /opt/confidential-containers/libexec
* /opt/confidential-containers/share
And then manually remove the binaries under bin directory` as the pre-install hook will drop binaries there.
Finally, let's call a `rmdir -p /opt/confidential-containers/bin` which should take care of the cleanup in case no pre-install hook is used, and let's make sure we pass `--ignore-fail-on-non-empty` so we don't fail when using a pre-install hook.
Fixes: #5128

kata-deploy-cc: Simplify cleanup

---

tools/packaging/kernel/build-kernel.sh

'linux-' prefix needed for tarball name in SEV case.
Fixes: #5094
Signed-Off-By: Ryan Savino <ryan.savino@amd.com>

kernel: fix kernel tarball name for SEV

---

tools/packaging/kernel/build-kernel.sh

Commit cherry picked from #5095. This is for CCv0.
'linux-' prefix needed for tarball name in SEV case.
Fixes: #5094
Signed-Off-By: Ryan Savino [ryan.savino@amd.com](mailto:ryan.savino@amd.com)

kernel: fix kernel tarball name for SEV for CCv0

---

src/runtime-rs/config/configuration-dragonball.toml.in

"inline-virtio-fs" is newly supported by kata 3.0 as a "shared_fs" type,
it should be described in configuration file.
Fixes: #5102

config: add "inline-virtio-fs" as a "shared_fs" type

---

src/tools/runk/Cargo.lock
src/tools/runk/Cargo.toml
src/tools/runk/Makefile
src/tools/runk/README.md

Enable seccomp support in `runk` by default.
The user can disable seccomp by `make SECCOMP=no`
Fixes: #4896

runk: Enable seccomp support by default

---

src/runtime-rs/crates/resource/src/volume/share_fs_volume.rs

The comment for `generate_mount_path` function is a copy miss and should be deleted.
Fixes: #5150

runtime-rs: remove meaningless comment

---

src/runtime-rs/crates/resource/src/volume/share_fs_volume.rs

Host devices should start with `/dev/` but not `/dev`.
Fixes: #5145
Signed-off-by: bin liu <liubin0329@gmail.com>

runtime-rs: fix host device check pattern

---

src/libs/kata-types/src/annotations/mod.rs
src/runtime-rs/crates/runtimes/src/static_resource.rs

period should have a type of u64, and quota should be i64, the
function of getting CPU period and quota from annotations should
use the same data type as function return type.
Fixes: #5100

kata-types: change return type of getting CPU period/quota function

---

src/libs/kata-types/src/config/hypervisor/mod.rs

If the shared_fs is set to "inline-virtio-fs", the "virtio_fs_daemon"
should be ignored.
Fixes: #5104

kata-types: don't check virtio_fs_daemon for inline-virtio-fs

---

tools/packaging/kata-deploy/local-build/Makefile
tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh

Currently leaving the cc-sev-ovmf-tarball target out of the cc payload.
I was not sure where discussion had landed on the number of payload bundles.
e.g. could be included in a cc bundle along with tdx support or create an SEV bundle.
Fixes: kata-containers#5025

CC| packaging: Add AmdSev OVMF target for use in payload images

---

tools/packaging/guest-image/build_image.sh
tools/packaging/kata-deploy/local-build/Makefile
tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
tools/packaging/kernel/build-kernel.sh
tools/packaging/scripts/lib.sh

Adds a make target for an sev initrd.
Changes the kata-deploy-binaries functions to be more generic.
Adds efi_secret kernel module to the sev initrd. 
Moved kernel config version checking function from kernel builder to lib script.
First question: should this get added to the cc target?

CC, packaging: add sev-initrd target, and add efi_secret module to sev's initrd 

---

tools/packaging/kata-deploy-cc/scripts/kata-deploy.sh

Adds to the configuration of containerd so the correct config is selected.
Fixes: #4851
Signed-Off-By: Alex Carter <alex.carter@ibm.com>

CC, kata-deploy: add kata-qemu-sev runtimeclass

---

src/runtime-rs/crates/resource/src/rootfs/mod.rs
src/runtime-rs/crates/shim/src/config.rs.in

Some #![allow(dead_code)]s and code are not needed indeed.
Fixes: #5164

runtime-rs: delete some allow(dead_code) attributes

---

tools/osbuilder/rootfs-builder/agent-config.toml.in
tools/osbuilder/rootfs-builder/rootfs.sh
tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in

Adds default config file.
Adds case in rootfs.sh to copy config.
Fixes kata-containers#5023
Signed-Off-By: Alex Carter <alex.carter@ibm.com>

CC | rootfs builder: add agent config file to rootfs for offline_sev_kbc

---

tools/packaging/kata-deploy/local-build/Makefile
tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
tools/packaging/static-build/kernel/Dockerfile

Adds a new make target for an sev kernel which can be built and put into payload bundles for the operator.
Currently not including this sev kernel target in the cc payload bundle.
Unfortunately having to breakflow from using the generic cc_tee_kernel functions in either the kata-deploy-binaries or build-kernel.
Largely based on using an upstreamed kernel release, meaning the url is the defaul cdn, and e.g. we use version rather than tag.
The upside of this is that we can use the sha sum checking functionality from the generic get_kernel function.
Fixes: #5037

CC | packaging: Build SEV capable kernel + efi_secret module

---

tools/osbuilder/rootfs-builder/rootfs.sh
tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in
tools/osbuilder/rootfs-builder/ubuntu/config.sh

This adds depmod to the rootfs builder to get the dependencies for kernel modules, namely for the efi_secret module needed for sev.
In order to maintain compatibility with the local build docker environment, a few dependencies are needed.

CC use depmod in rootfs builder for kernel modules with docker support

---

src/runtime-rs/Cargo.lock
src/runtime-rs/crates/agent/src/kata/agent.rs
src/runtime-rs/crates/agent/src/kata/mod.rs
src/runtime-rs/crates/agent/src/lib.rs
src/runtime-rs/crates/runtimes/Cargo.toml
src/runtime-rs/crates/runtimes/common/src/sandbox.rs
src/runtime-rs/crates/runtimes/src/lib.rs
src/runtime-rs/crates/runtimes/src/manager.rs
src/runtime-rs/crates/runtimes/src/shim_mgmt/client.rs
src/runtime-rs/crates/runtimes/src/shim_mgmt/handlers.rs
src/runtime-rs/crates/runtimes/src/shim_mgmt/mod.rs
src/runtime-rs/crates/runtimes/src/shim_mgmt/server.rs
src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs

This PR consists of two parts.
1. An **http server running on a uds** (/run/kata/sid/shim-monitor.sock), registered with several uri (currently only /agent-url for checking agent socket path). When a http client connect to this socket and send a http request, corresponding handler function will be invoked.
- This server is running on a lightweight tokio thread when the sandbox is started
- For each request, the lightweight tokio thread starts another lightweight tokio thread. This supports concurrent request on the server with lower overhead.
2. **Client side utilities** including a `struct MgmtClient` which can connected to shim mgmt server and establish **PUT, GET, POST** requests. The client side utilities support **timeout**.
This functionality will make further development of …

feat(Shimmgmt): Shim management server and client

---

tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh

The sev initrd target had been changed to "cc-sev-rootfs-initrd". This was good discussion as part of #5120.
I failed to rename it from "cc-sev-initrd-image" in kata-deploy-binaries. The script will fail for a bad build target.
Fixes: #5166
Signed-Off-By: Alex Carter <alex.carter@ibm.com>

kata-deploy: rename make target for sev initrd

---

docs/design/virtualization.md

This PR updates the url for the cloud hypervisor in the virtualization document.
Fixes #5203

docs: Update url in virtualization document

---

tools/packaging/kernel/configs/fragments/s390/crypto.conf

This config update supports new crypto algorithms for s390.
Fixes: kata-containers#5158

kernel: Add crypto kernel config for s390

---

src/libs/kata-types/src/config/hypervisor/mod.rs

Some comments for types are incorrect in file
src/libs/kata-types/src/config/hypervisor/mod.rs
Fixes: #5187

runtime-rs: fix incorrect comments

---

src/runtime-rs/crates/resource/src/network/utils/link/manager.rs

Some device types have the same definition, they can be implemented by macro to reduce code.
And this commit also deleted the `peer_name` field of the structs that is never been used.
Fixes: #5170

runtime-rs/resource: use macro to reduce duplicated code

---

src/runtime-rs/Cargo.lock
src/runtime-rs/crates/resource/Cargo.toml
src/runtime-rs/crates/resource/src/network/endpoint/endpoints_test.rs
src/runtime-rs/crates/resource/src/network/network_pair.rs
src/runtime-rs/crates/resource/src/network/utils/address.rs
src/runtime-rs/crates/resource/src/network/utils/link/create.rs
src/runtime-rs/crates/resource/src/network/utils/link/mod.rs
src/runtime-rs/crates/resource/src/network/utils/mod.rs
src/runtime-rs/crates/resource/src/network/utils/netns.rs

Add UTs for network resource.
Currently we are lacking UTs for runtime-rs, we should add UTs gradually.
Fixes: #4923

runtime-rs: add unit tests for network resource

---

tools/osbuilder/rootfs-builder/rootfs.sh

To avoid the random failures when we are building the rootfs as it seems that it does not find the value for the libseccomp and gperf directory, this PR export these variables.
Fixes #5232

osbuilder: Export directory variables for libseccomp

---

src/runtime-rs/crates/runtimes/src/shim_mgmt/server.rs

Use KATA_PATH instead of "run/kata"
Fixes: #5229

runtime-rs: remove hardcoded string

---

src/runtime-rs/crates/runtimes/src/static_resource.rs

Add test case for StaticResource, the old test is not covering the StaticResource struct.
Fixes: #5162

runtime-rs: add test for StaticResource

---

tools/osbuilder/rootfs-builder/rootfs.sh

Umoci is not longer required if we have the attestation-agent, so don't override the user input
Fixes: #5237

osbuilder: don't pull in umoci with attestation

---

tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup-stable.yaml
tools/packaging/kata-deploy/kata-deploy/base/kata-deploy-stable.yaml

As 3.0.0-rc0 has been released, let's switch the kata-deploy / kata-cleanup
tags back to "latest", and re-add the kata-deploy-stable and the
kata-cleanup-stable files.
Only merge this commit after 3.0.0-rc0 release is successfully tagged!

release: Revert kata-deploy changes after 3.0.0-rc0 release

---

tools/packaging/scripts/configure-hypervisor.sh

`powwer` is a typo of `power`, and many spaces should be replaced by tabs for indent.
Fixes: #5160

packaging: fix typo in configure-hypervisor.sh

---

src/runtime-rs/crates/hypervisor/src/device/vfio.rs

In src/runtime-rs/crates/hypervisor/src/device/vfio.rs, the path of new_id is defined as a const, but unbind is used as a local variable, they should be unified to const.
Fixes: #5189

runtime-rs: define VFIO unbind path as a const

---

src/libs/kata-types/src/config/default.rs
src/libs/kata-types/src/config/hypervisor/mod.rs
src/libs/kata-types/src/config/mod.rs
src/runtime-rs/crates/hypervisor/src/dragonball/inner.rs
src/runtime-rs/crates/hypervisor/src/kernel_param.rs
src/runtime-rs/crates/runtimes/Cargo.toml
src/runtime-rs/crates/runtimes/src/manager.rs

Read debug console configuration in kernel params. The debug console is opened when the configuration is set, and to be consistent with kata 2.x, the port is default to be 1026 in runtime. A console can log into the pod's shell by connecting to vport 1026.
Fixes: #5068
Signed-Off-By: Ji-Xinyou <jerryji0414@outlook.com>

runtime-rs: debug console support in runtime

---

src/agent/Cargo.lock

Looks like cargo vendor searches for all needed dependencies and we have left over nix 0.24.2
Fixes: #5261

stable-2.5: fix cargo vendor

---

.github/workflows/kata-deploy-test.yaml
docs/Release-Process.md

This with those changes **test-kata-deploy** is triggered in 3 ways:
1. **pull_request** events that changes VERSION, essentially, a release PR
2. **workflow_dispatch** event - manually triggered from Github's Actions web UI and required to mention the branch to run against
3. **comment_issue** event - triggered by commenting on PR with `/test_kata_deploy`, works only against main branch
All three methods validates it is triggered by a kata-containers member
Fixes: #4349
**NOTE** This contains essential fixes for https://github.com/kata-containers/kata-containers/pull/4350

workflow: trigger test-kata-deploy with pull_request and fix workflow_dispatch

---

src/runtime/pkg/containerd-shim-v2/create.go
src/runtime/virtcontainers/hypervisor.go
src/runtime/virtcontainers/qemu.go

These are the remaining backports for 2.5.2 :
https://github.com/kata-containers/kata-containers/pull/5156 :
- 17dfa43691a3d232d324f3232fc42839f43a979c runtime: add more debug logs for non-root user operation
- 6c6701b136636e74d5926de92a38051a56fbcbaf runtime: make StopVM thread-safe
- 266f08c3be7b85e2004354a0268fd84e4c897c13 runtime: store the user name in hypervisor config

Last backport for 2.5.2

---

src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container_inner.rs
src/runtime-rs/crates/runtimes/virt_container/src/container_manager/process.rs
src/runtime-rs/crates/service/src/task_service.rs

Add close_io to shim and call agent's close_stdin in close_io.
Fixes: #4729

runtime-rs: fix shim close_io call to support kubectl cp

---

src/runtime-rs/crates/agent/src/kata/mod.rs

Use RwLock for Agent in runtime, for better concurrency.
Fixes: #5199

refactor(runtime-rs): Use RwLock in runtime-agent

---

src/runtime-rs/Cargo.lock

src/dragonball/Cargo.toml is updated and the Cargo.lock is not commited into repo.
Fixes: #5280

runtime-rs: update Cargo.lock

---

tools/packaging/release/update-repository-version.sh

Shell expands `*"rc"*` to the top-level `src` directory. This results in comparing a version with a directory name. This doesn't make sense and causes the script to choose the wrong branch of the `if`.
The intent of the check is actually to detect `rc` in the version.
Fixes: #5283

tools: release: fix bogus version check

---

src/dragonball/src/vm/aarch64.rs

Cmdline struct update in the latest linux-loader lib and its as_str method is changed to as_cstring, thus we need fix it according whereas the old as_str method is used.
Fixes: #5287

dragonball: fix no "as_str" error on Arm

---

versions.yaml

This PR updates the oci version that we are using in kata containers.
Fixes #5291

versions: Update oci version

---

versions.yaml

This PR updates the gperf url to avoid random failures when installing
libseccomp as it seems that the mirrror url produces network random
failures in multiple CIs.
Fixes #5294

versions: Update gperf url to avoid libseccomp random failures

---

src/dragonball/src/vm/kernel_config.rs

Since linux loader is updated in the Dragonball and the api for Cmdline has been changed ( as_str() changed to as_cstring() ), we need to update unit test in Dragonball.
fixes: #5277

dragonball: update ut for kernel config

---

src/runtime/virtcontainers/qemu_amd64.go

Closes #1984 and #4386
With microvm machine types, `kernel_irqchip=split` option is necessary (see related issues for more debug info).

microvm: Remove kernel_irqchip=on option

---

tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh

In order to ensure that the proxy configuration is passed to the 2nd layer container, let's ensure the $HOME/.docker/config.json file is exposed inside the 1st layer container.
For some reason which I still don't fully understand exporting https_proxy / http_proxy / no_proxy was not enough to get those variables exported to the 2nd layer container.
In this commit we're creating a "$HOME/.docker" directory, and removing it after the build, in case it doesn't exist yet.  The reason we do this is to avoid docker not running in case "$HOME/.docker" doesn't exist.
This was not tested with podman, but if there's an issue with podman, the issue was already there beforehand and should be treated as a different problem than the one addressed in this commit.
Fixes: #5077
Signed-off-by: Fabiano …

packaging: Mount $HOME/.docker in the 1st layer container

---

tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh

In order to ensure that the proxy configuration is passed to the 2nd layer container, let's ensure the $HOME/.docker/config.json file is exposed inside the 1st layer container.
For some reason which I still don't fully understand exporting https_proxy / http_proxy / no_proxy was not enough to get those variables exported to the 2nd layer container.
In this commit we're creating a "$HOME/.docker" directory, and removing it after the build, in case it doesn't exist yet.  The reason we do this is to avoid docker not running in case "$HOME/.docker" doesn't exist.
This was not tested with podman, but if there's an issue with podman, the issue was already there beforehand and should be treated as a different problem than the one addressed in this commit.
Fixes: #5077
Signed-off-by: Fabiano …

CC | packaging: Mount $HOME/.docker in the 1st layer container

---

src/libs/protocols/.gitignore

This patch adds `image_ttrpc_async.rs` to `.gitignore`, since the file is a generated one.
Fixes: #5318

CCv0: Add image_ttrpc_async.rs to .gitignore

---

src/libs/kata-sys-util/src/spec.rs
versions.yaml

* kata-sys-util: fix typo `unknow`
* versions: Update gperf url to avoid libseccomp random failures

backport fix for 3.0.0 release

---

src/libs/kata-sys-util/src/fs.rs

get_bundle_path has already defined in spec.rs,
delete it from fs.rs.
Fixes: #5299

kata-sys-util: delete duplicated get_bundle_path

---

src/agent/Cargo.lock
src/agent/rustjail/Cargo.toml
src/agent/rustjail/src/console.rs
src/agent/src/rpc.rs

ESRCH usually means the process has exited. In this case, the execution should continue to kill remaining container processes.
Fixes: #5366

agent: don't exit early if signal fails due to ESRCH

---

src/runtime-rs/crates/resource/src/share_fs/share_virtio_fs.rs
src/runtime-rs/crates/resource/src/share_fs/share_virtio_fs_inline.rs

The const PASSTHROUGH_FS_DIR defined twice, delte one.
Fixes: #5301

runtime-rs: delete duplicated PASSTHROUGH_FS_DIR const

---

src/agent/Cargo.lock
src/agent/rustjail/Cargo.toml
src/agent/rustjail/src/console.rs
src/agent/src/mount.rs
src/agent/src/rpc.rs

* agent: reduce reference count for failed mount
* agent: don't exit early if signal fails due to ESRCH

stable-3.0: backport agent fixes

---

src/runtime/virtcontainers/qemu.go

The qmp command of hotplug cpu failed error was hidden. It didn't friendly for the user tracing the hotplug cpu error. The PR help us to improve the hotplug cpu error log. Add real qemu command error log for `failed to hot add vCPUs`. Through the error message, we can get the reason of the failed qmp command
for hotplug cpu operation.
Fixes: #5234

virtcontainers: add warn log record for qmp hotplug cpu error

---

src/runtime/virtcontainers/types/capabilities.go

The comment for SetFsSharingSupport is not suitable, correct the function name.
Fixes: #5285

runtime: fix incorrect comment for SetFsSharingSupport function

---

README.md
src/runtime-rs/README.md

There are two duplicated mentioning of the rust libraries in README.md. Let's just remove them all as the section is intended to list out core Kata components rather than general libraries.
Fixes: #5275

readme: remove libraries mentioning

---

docs/install/kata-containers-3.0-rust-runtime-installation-guide.md

Fixes: #5392
Signed-off-by: chmod100 <letfu@outlook.com>

docs: fix a typo in rust-runtime-installation-guide

---

src/libs/kata-sys-util/src/k8s.rs
src/libs/kata-types/src/mount.rs
src/runtime-rs/crates/resource/src/share_fs/mod.rs
src/runtime-rs/crates/resource/src/share_fs/virtio_fs_share_mount.rs
src/runtime-rs/crates/resource/src/volume/share_fs_volume.rs
src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs

Add support for ephemeral storage and k8s emptydir.
Depends-on:github.com/https://github.com/kata-containers/tests/pull/5161
Fixes: #4730

runtime-rs: support ephemeral storage for emptydir

---

src/dragonball/src/device_manager/blk_dev_mgr.rs

delete redundent derive part for BlockDeviceMgr.
fixes: #5396

Dragonball: delete redundant comments in blk_dev_mgr

---

.github/workflows/static-checks.yaml
src/dragonball/Makefile
src/dragonball/src/device_manager/mod.rs
src/dragonball/src/vcpu/aarch64.rs
src/dragonball/src/vcpu/vcpu_impl.rs
src/dragonball/src/vcpu/vcpu_manager.rs
src/dragonball/src/vm/aarch64.rs
utils.mk

Currently, Dragonball only supports x86_64 and aarch64 platforms.
Fixes: #4381

ci: skip s390x for dragonball.

---

versions.yaml

The previously used repo has been removed by Intel.  As this happened, the TDX team worked on providing the patches that were hosted atop of the v5.15 kernel as a tarball present in the
https://github.com/intel/tdx-tools repos, see
https://github.com/intel/tdx-tools/pull/161.
On the Kata Containers side, in order to simplify the process and to avoid adding ~1400 kernel patches to our repo, we've revived the https://github.com/kata-containers/linux repo, and created a branch and a tag with those ~1400 patches atop of the v5.15.  The branch is called v5.15-plus-TDX, and the tag is called 5.15-plus-TDX (in order to avoid having to change how the kernel builder script deals with versioning).
Knowing the whole background, let's switch the repo we're getting the TDX kernel from.
Fixes: #5326 …

versions: Update TDX kernel

---

src/runtime-rs/crates/resource/src/share_fs/share_virtio_fs_standalone.rs
src/runtime-rs/crates/service/src/manager.rs
src/runtime-rs/crates/shim/src/shim_delete.rs

In some case the call of cleanup from shim to service manager will fail,
and the shim process will continue to running, that will make process leak.
This commit will force shutdown the shim process in case of any errors in
service crate.
Fixes: #5087

runtime-rs: force shutdown shim process in it can't exit

---

src/tools/kata-ctl/src/args.rs

This change improves consistency on strings in the kata-ctl tool's command descriptions, and can avoid certain confusions.
Fixes #5411 
Signed-off-by: Tingzhou Yuan <tzyuan15@bu.edu>

kata-ctl: improve command descriptions for consistency

---

src/libs/kata-sys-util/src/spec.rs
src/runtime-rs/crates/shim/src/shim_delete.rs

Change get_contaier_type to get_container_type
Fixes: #5415

runtime-rs: fix typo get_contaier_type to get_container_type

---

src/agent/src/image_rpc.rs

This also slightly improves readability by decluttering the function declaration and call site.
Signed-off-by: Wedson Almeida Filho <walmeida@microsoft.com>

image_rpc: avoid double and triple indirections

---

src/dragonball/src/event_manager.rs

handle_events for EventManager doesn't take max_events as arguments, so we need to update the comments for it.
p.s. max_events is defined when initializing the EventManager.
fixes: #5382

Dragonball: remove redundant comments in event manager

---

versions.yaml

versions: Update TDX kernel
The previously used repo has been removed by Intel.  As this happened,
the TDX team worked on providing the patches that were hosted atop of
the v5.15 kernel as a tarball present in the
https://github.com/intel/tdx-tools repos, see
https://github.com/intel/tdx-tools/pull/161.
On the Kata Containers side, in order to simplify the process and to
avoid adding ~1400 kernel patches to our repo, we've revived the
https://github.com/kata-containers/linux repo, and created a branch and
a tag with those ~1400 patches atop of the v5.15.  The branch is called
v5.15-plus-TDX, and the tag is called 5.15-plus-TDX (in order to avoid
having to change how the kernel builder script deals with versioning).
Knowing the whole background, let's switch the repo we're getting the
TDX …

CC | backport TDX kernel and qemu repo updates

---

snap/snapcraft.yaml
tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
tools/packaging/static-build/virtiofsd/build-static-virtiofsd.sh
tools/packaging/static-build/virtiofsd/build.sh
tools/packaging/static-build/virtiofsd/gnu/Dockerfile
tools/packaging/static-build/virtiofsd/musl/Dockerfile

When moving to building the CI artefacts using the kata-deploy scripts, we've noticed that the build would fail on any machine where the tarball wasn't officially provided.
This happens as rust is missing from the 1st layer container.  However, it's a very common practice to leave the 1st layer container with the minimum possible dependencies and install whatever is needed for building a specific component in a 2nd layer container, which virtiofsd never had.
In this commit we introduce the second layer containers (yes, comtainers), one for building virtiofsd using musl, and one for building virtiofsd using glibc.  The reason for taking this approach was to actually simplify the scripts and avoid building the dependencies (libseccomp, libcap-ng) using musl libc.
Fixes: #5425
Signed-off-by: …

virtiofsd: Build inside a container

---

src/tools/kata-ctl/Cargo.toml
src/tools/kata-ctl/src/arch/mod.rs
src/tools/kata-ctl/src/check.rs
src/tools/kata-ctl/src/ops/check_ops.rs

s390x apparently does not support rust-tls, which is required by the
network check (due to the `reqwest` crate dependency).
Disable the network check on s390x until we can find a solution to the
problem.
> **Note:**
>
> This fix is assumed to be a temporary one until we find a solution.
> Hence, I have not moved the network check code (which should be entirely
> generic) into an architecture specific module.
Fixes: #5435.
-----
Also fixes:
kata-ctl: arch: Improve check call
Rework the architecture-specific `check()` call by moving all the
conditional logic out of the function.
Fixes: #5402.

kata-ctl: Disable network check on s390x

---

snap/snapcraft.yaml
tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
tools/packaging/static-build/virtiofsd/build-static-virtiofsd.sh
tools/packaging/static-build/virtiofsd/build.sh
tools/packaging/static-build/virtiofsd/gnu/Dockerfile
tools/packaging/static-build/virtiofsd/musl/Dockerfile

When moving to building the CI artefacts using the kata-deploy scripts, we've noticed that the build would fail on any machine where the tarball wasn't officially provided.
This happens as rust is missing from the 1st layer container. However, it's a very common practice to leave the 1st layer container with the minimum possible dependencies and install whatever is needed for building a specific component in a 2nd layer container, which virtiofsd never had.
In this commit we introduce the second layer containers (yes, comtainers), one for building virtiofsd using musl, and one for building virtiofsd using glibc. The reason for taking this approach was to actually simplify the scripts and avoid building the dependencies (libseccomp, libcap-ng) using musl libc.
Fixes: …

CC | backport | virtiofsd: Build inside a container

---

src/runtime-rs/Makefile

regulate the comment style for the runtime-rs comments.
In runtime-rs makefile, we use
```
```
to let make help print out help information for variables and targets, but later commits forgot this rule.
So we need to follow the previous rule and change the current comments.
fixes:#5413

runtime-rs: regulate the comment in runtime-rs makefile

---

.github/workflows/cc-payload-after-push.yaml
tools/packaging/kata-deploy/local-build/kata-deploy-build-and-upload-payload.sh

Let's have a GitHub action to publish the Kata Containers payload, after
every push to the CCv0 branch, to the Confidential Containers
`runtime-payload-ci` registry.
The intention of this action is to allow developers to test new
features, and easily bisect breakages that could've happened during the
development process.  Ideally we'd have a CI/CD pipeline where every
single change would be tested with the operator, but we're not yet
there.  In any case, this work would still be needed. :-)
It's very important to mention that this should be carefully considered
on whether it should or should not be merged back to `main`, as the flow
of PRs there is way higher than what we currently have as part of the
CCv0 branch.
Fixes: #5460

CC | actions: Publish a payload on every CCv0 push

---

.github/workflows/cc-payload.yaml

Let's create a GitHub action to automate the Kata Containers payload generation for the Confidential Containers project.
This GitHub action builds the artefacts (in parallel), merges them into a single tarball, generates the payload with the resulting tarball, and uploads the payload to the Confidential Containers quay.io.
It expects the tags to be used to be in the `CC-x.y.z` format, with x, y, and z being numbers.
Fixes: #5330

CC | action: Automate CC payload release

---

src/runtime-rs/crates/agent/src/kata/mod.rs
src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs

Let /agent-url request returns with default server port (1024), this is to align the behavior in go runtime.

Modify agent-url return value in runtime-rs

---

.github/workflows/cc-payload-after-push.yaml

There was a typo in the registry name, which should be quay.io/confidential-containers/runtime-payload-ci instead of quay.io/repository/confidential-containers/runtime-payload-ci
Fixes: #5469

CC | actions: Fix runtime-payload-ci registry address

---

tools/packaging/static-build/qemu/Dockerfile
tools/packaging/static-build/qemu/build-base-qemu.sh
tools/packaging/static-build/qemu/build-qemu.sh

Differently than every single other bit that's part of our repo, QEMU has been using a single Dockerfile that prepares an environment where the project can be built, but *also* building the project as part of that very same Dockerfile.
This is a problem, for several different reasons, including:
* It's very hard to have a reproducible build if you don't have an archived image of the builder
* One cannot cache / ipload the image of the builder, as that contains already a specific version of QEMU
* Every single CI run we end up building the builder image, which includes building dependencies (such as liburing)
Let's split the logic into a new build script, and pass the build script to be executed inside the builder image, which will be only responsible for providing an environment where …

qemu: Re-work static-build Dockerfile

---

src/runtime-rs/Makefile

There is a typo in runtime-rs makefile.
_dragonball should be _DB
fixes: #5452

Makefile: fix an typo in runtime-rs makefile

---

tools/osbuilder/rootfs-builder/init_trusted_storage.sh

Based on https://gitlab.com/cryptsetup/cryptsetup/-/issues/525
With this PR, 1 TiB ephemeral disk can be setup in ~9 seconds.
1. When --no-wipe is used, the device will have invalid checksums
2. mkfs.ext4 would fail on an un-wiped device due to reads of pages with invalid checksums
3. To make mkfs.ext4 work
- Perform a dry run to figure out which sectors (pages) mkfs.ext4 will write to.
- Perform direct writes to these pages to ensure that they will have valid checksums
- Invoke mkfs.ext4 again to perform initialization 
4. Use lazy_journal_init option with mkfs.ext4 to lazily initialize the journal.
According to the man pages,
"This speeds up file system initialization  noticeably, but carries some small
risk if the system crashes before the  journal  has  been overwritten  entirely
one …

CCv0: Optimize integrity device creation by avoiding a full device clear

---

tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
tools/packaging/static-build/shim-v2/build.sh
tools/packaging/static-build/shim-v2/install_go_rust.sh

As the CCv0 effort is not using the runtime-rs, let's add a mechanism to avoid building it.
The easiest way to do so, is to simply *not* build the runtime-rs if the RUST_VERSION is not provided, and then not providing the RUST_VERSION as part of the cc-shim-v2-tarball target.
Fixes: #5462

CC | packaging: Don't build runtime-rs if no RUST_VERSION is provided

---

src/agent/src/netlink.rs

Sometimes we will face EEXIST error when adding arp neighbour.
Using NLM_F_REPLACE replace NLM_F_EXCL will avoid fail if the
entry exists.
See https://man7.org/linux/man-pages/man7/netlink.7.html
Fixes: #4895

agent: use NLM_F_REPLACE replace NLM_F_EXCL in rtnetlink

---

src/tools/kata-ctl/Cargo.toml
src/tools/kata-ctl/src/arch/s390x/mod.rs
src/tools/kata-ctl/src/check.rs
src/tools/kata-ctl/src/ops/check_ops.rs

Re-enable network tests on s390x. On s390x, `reqwest` uses `native-tls` instead of `rustls-tls` and its `ring` dependencies that is not available on s390x. Further, `workspace.resolver` was necessary to allow `cfg` checks in `Cargo.toml`.
To let the tests running on s390x, further annotations where required. With that PR, test results look like:
````
git/kata-containers/kata-containers/src/tools/kata-ctl# make test
../../../utils.mk:153: "WARNING: s390x-unknown-linux-musl target is unavailable"
Finished release [optimized] target(s) in 0.05s
Running unittests (target/s390x-unknown-linux-gnu/release/deps/kata_ctl-7ef55a9a87c85ded)
running 7 tests
test check::tests::check_version_by_empty_url ... ok
test check::tests::check_version_by_garbage_url ... ok
test …
```

kata-ctl: Re-enable network tests on s390x (fixes 5438)

---

src/runtime/pkg/containerd-shim-v2/metrics.go

The containerd stats method and metrics API are broken with Kata 2.5.x, the stats fail to load and the metrics API responds with status code 500
This seems to be down to the conversion from the stats reported by the agent RPC `StatsContainer` where the field `Pagesize` is not completed by the `setHugetlbStats` method. In the case where multiple sized tables stats are reported, this causes containerd to register two metrics with the same label set, rather than each being partitioned by the `page` label.
Fixes: #5316

shim: Ensure pagesize is set when reporting hugetlb stats

---

src/agent/src/sandbox.rs

Remove redundant checks for executable files.
FIXes: #3730
Signed-off-by: Rouzip <1226015390@qq.com>

agent: remove redundant checks

---

src/runtime-rs/Makefile

when using mock to package rpm, we cannot have sudo permission
Fixes: #5473

makefile: remove sudo when create symbolic link

---

src/agent/Cargo.lock
src/agent/rustjail/Cargo.toml

The libseccomp crate v0.3.0 has been released, so use it in the agent.
Fixes: #5487

rustjail: Upgrade libseccomp crate to v0.3.0

---

docs/install/kata-containers-3.0-rust-runtime-installation-guide.md
tools/packaging/kata-deploy/README.md

As kata-deploy support rust runtime, we need to update the installation docs
Fixes:#5500

docs: update rust runtime installation guide

---

.github/workflows/cc-payload-after-push.yaml
tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
tools/packaging/scripts/lib.sh
tools/packaging/static-build/initramfs/build.sh
tools/packaging/static-build/kernel/build.sh
tools/packaging/static-build/ovmf/build.sh
tools/packaging/static-build/qemu/Dockerfile
tools/packaging/static-build/qemu/build-base-qemu.sh
tools/packaging/static-build/qemu/build-qemu.sh
tools/packaging/static-build/shim-v2/build.sh
tools/packaging/static-build/td-shim/build.sh
tools/packaging/static-build/virtiofsd/build.sh
tools/packaging/static-build/virtiofsd/gnu/Dockerfile
tools/packaging/static-build/virtiofsd/musl/Dockerfile
versions.yaml

This PR covers a work done for avoiding building, on every pull-request, containers used to build the artefacts we produce.
This basically covers the following builders:
* kata-deploy (the container that will spawn the other containers)
* #5475 
* kernel
* #5476
* ovmf / tdvf
* #5477
* shim-v2
* #5478
* td-shim
* #5479
* virtiofsd
* #5480
* QEMU
* #5476 
This work doesn't cover:
* rootfs builders
* initrd builders
* agent builder
The image upload is done to the https://quay.io/kata-containers/cc-builders registry on every change done to the Dockerfile used to build the artefacts.
For now we have no expiration policy set, but that's a consideration for a different issue / PR.

CC | Avoid rebuilding the containers used for building the artefacts

---

tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
tools/packaging/scripts/lib.sh
tools/packaging/static-build/initramfs/Dockerfile
tools/packaging/static-build/initramfs/build-initramfs.sh
tools/packaging/static-build/initramfs/build.sh
tools/packaging/static-build/kernel/build.sh
tools/packaging/static-build/ovmf/build.sh
tools/packaging/static-build/qemu/build-base-qemu.sh
tools/packaging/static-build/shim-v2/build.sh
tools/packaging/static-build/td-shim/build.sh
tools/packaging/static-build/virtiofsd/build.sh

lib.sh: Fix get_last_modification()
The ${file} path is an absolute path, as /home/fidencio/..., while the
result of the `git status --porcelain` is a path relative to the
${repo_root_dir}.  Because of this, the logic to adding `-dirty` to the
image name would never work.
Let's fix this by removing the ${repo_root_dir} from the ${file} when
grepping for it.
---
Revert "packaging: Add infra to push the kata-deploy builder image"
This reverts commit fe8b246ae4f3945fc5816cefcee5cf67bf233a59.
The reason this has to be reverted is because we cannot cache an image
that has a specific user, uid, gid, docker_host_id, and expect that to
work equally on different machines.  Unfortunately, this is one of the
images that cannot be cached at all.
---
Revert "packaging: Use existing image for the …

CC | Fix up issues with cached images

---

docs/use-cases/using-Intel-SGX-and-kata.md

The /dev/sgx is not mounted and the enclave is not available, causing the demo job to report an error in the logs. Add volumeMounts to container in order to have the device available in the container.
Fixes: #5514

docs: Fix volumeMounts in SGX usage example

---

versions.yaml

There is little point to maintain backward compatibility for golangci-lint. Let's just use a unified version of it.

versions: bump golangci-lint version

---

tools/packaging/static-build/virtiofsd/build-static-virtiofsd.sh

The compile option `link-self-contained=yes` asks rustc to use C library startup object files that come with the compiler, which are not available on the target `s390x-unknown-linux-gnu`. A build does not contain any startup files leading to a broken executable entry point (causing segmentation fault). This PR is to make the compile option able to be skipped for `s390x`. 
Fixes: #5522

virtiofsd: Not use "link-self-contained=yes" on s390x

---

src/runtime/pkg/katautils/network_linux.go
src/runtime/virtcontainers/network_linux.go

Add a `EnterNetNS` in `virtcontainers` to remove same code in `katautils`
Fixes #5394
Signed-off-by: Rouzip <1226015390@qq.com>

add EnterNetNS in virtcontainers

---

tools/packaging/scripts/lib.sh
tools/packaging/static-build/cache_components.sh
tools/packaging/static-build/qemu/build-static-qemu-cc.sh

This PR implements the use of a cached cc qemu tarball to speed up the CI and avoid building the cc qemu tarball when it is not necessary.
Fixes #5363

CCv0: Use cached cc qemu tarball

---

src/agent/src/config.rs

As we discussed in #5178, user need set aa_kbc_params config without modify kata guest image, since kernel params is also measured in TEE boot flow, we make aa_kbc_params can be parsed through kernel cmdline.
Fixes: #5178
Signed-off-by: Wang, Arron <arron.wang@intel.com>

CC | config: Export aa_kbc_params to be set in guest kernel command line

---

tools/osbuilder/rootfs-builder/ubuntu/config.sh
tools/osbuilder/rootfs-builder/ubuntu/rootfs_lib.sh

Inclavare released a rats-tls-tdx package, which we depend on for using
verdictd.
Let's install it when using EAA_KBC, as already done for the rats-tls
package.
Fixes: #5543

CC | osbuilder: Install rats-tls-tdx

---

src/agent/Cargo.lock
src/agent/Cargo.toml
src/agent/src/signal.rs

Fix build warning in signal.rs:
error: unused `tokio::sync::MutexGuard` that must be used
--> src/signal.rs:27:9
|
27 |         rustjail::container::WAIT_PID_LOCKER.lock().await;
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: `-D unused-must-use` implied by `-D warnings`
= note: if unused the Mutex will immediately unlock
Fixes: #5541
Signed-off-by: Wang, Arron <arron.wang@intel.com>

CC | agent: Bump pinned version of image-rs to support cosign signature verification

---

tools/osbuilder/rootfs-builder/rootfs.sh
versions.yaml

Add tag entry to the attestation agent entry of the versions file. Checkout tag commit after cloning AA in rootfs builder.
Fixes: #5373
Fixes: kata-containers#5373
Signed-Off-By: Alex Carter <alex.carter@ibm.com>

osbuilder: specify Attestation Agent tag for rootfs build

---

src/runtime/virtcontainers/clh.go

Launching a pod with measured boot enabled seems to be taking longer than expected with Cloud Hypervisor, which leads to hitting a timeout limit.
Let's double those timeout limits for now.

CC | clh: Increase the timeouts when using Conf Guests

---

snap/snapcraft.yaml

It appears that _either_ the GitHub workflow runners have changed their
environment, or the Ubuntu archive has changed package dependencies,
resulting in the following error when building the snap:
```
Installing build dependencies: bc bison build-essential cpio curl docker.io flex gcc git git-extras gnupg2 iptables libattr1-dev libblkid-dev libcap-dev libcap-ng-dev l  ibcapstone-dev libelf-dev libfdt-dev libffi-dev libglib2.0-dev libltdl-dev libmount-dev libnuma-dev libpixman-1-dev libseccomp-dev libselinux1-dev make ninja-build python3   software-properties-common uidmap zlib1g-dev
:
The following packages have unmet dependencies:
docker.io : Depends: containerd (>= 1.2.6-0ubuntu1~)
E: Unable to correct problems, you have held broken packages.
```
This PR uses the simplest solution: …

snap: Unbreak docker install

---

src/tools/runk/Cargo.lock

The libseccomp crate was upgraded to v0.3.0 by 4696ead, but `Cargo.lock` of runk wasn't updated by mistake. So, this commit updates `Cargo.lock` of runk to the latest dependencies.
Fixes: #5487

runk: Upgrade libseccomp crate to v0.3.0 in Cargo.lock

---

src/tools/runk/libcontainer/src/container.rs
src/tools/runk/libcontainer/src/status.rs

Ignore an error handling that is triggered when the kill command is called
with `--all option` to the stopped container.
High-level container runtimes such as containerd call the kill command with
`--all` option in order to terminate all processes inside the container
even if the container already is stopped. Hence, a low-level runtime
should allow `kill --all` regardless of the container state like runc.
This commit reverts to the previous behavior.
Fixes: https://github.com/kata-containers/kata-containers/issues/5555

runk: Ignore an error when calling kill cmd with --all option

---

src/runtime/virtcontainers/qemu_amd64.go

This commit adds the `kernel-hashes=on` flag to the QEMU command line for all SEV guests (previously, this was only enabled for SEV guests with `guest_pre_attestation=on`. This change allows the AmdSev firmware to be used for both encrypted and non-encrypted container images.
**Note:** 
This change makes the AmdSev OVMF build a requirement for all SEV guests. The standard host OVMF package will no longer work.
Fixes #5307 
Signed-off-by: Jim Cadden <jcadden@ibm.com>

CC | runtime: Enable kernel hashes for all SEV guests

---

src/runtime-rs/crates/resource/src/volume/share_fs_volume.rs

Fix the issue where share volumes always have readwrite permission even if
readonly permission is enough.
Fixes: kata-containers#5549
Signed-off-by: Xuewei Niu <justxuewei@apache.org>

runtime-rs: fix shared volume permission issue

---

.github/workflows/static-checks.yaml

Although introducing an awful amount of code duplication, let's
parallelise the static checks in order to reduce its time and the space
used in the VMs running those.
While I understand there may be ways to make the whole setup less
repetitive and error prone, I'm taking the approach of:
* Make it work
* Make it right
* Make it fast
So, it's clear that I'm only attempting to make it work, and I'd
appreciate community help in order to improve the situation here.  But,
for now, this is a stopgap solution.
JFYI, the time needed for run the tests on the `main` branch went down
from ~110 minutes to ~60 minutes.  Plus, we're not running those on a
single VM anymore, which decreases the chance to hit the space limit.
Reference: https://github.com/kata-containers/kata-containers/actions/runs/33934 …

github: Parallelise static checks

---

.github/workflows/static-checks.yaml
snap/snapcraft.yaml

Although introducing an awful amount of code duplication, let's parallelise the static checks in order to reduce its time and the space used in the VMs running those.
While I understand there may be ways to make the whole setup less repetitive and error prone, I'm taking the approach of:
* Make it work
* Make it right
* Make it fast
So, it's clear that I'm only attempting to make it work, and I'd appreciate community help in order to improve the situation here.  But, for now, this is a stopgap solution.
JFYI, the time needed for run the tests on the `main` branch went down from ~110 minutes to ~60 minutes.  Plus, we're not running those on a single VM anymore, which decreases the change to hit the space limit.
Reference: https://github.com/kata-containers/kata-containers/actions/runs/33934 …

CC | github: Parallelise static checks

---

src/agent/Cargo.lock
src/libs/Cargo.lock
src/libs/kata-types/Cargo.toml
src/libs/kata-types/src/capabilities.rs
src/libs/kata-types/src/lib.rs
src/runtime-rs/Cargo.lock
src/runtime-rs/crates/hypervisor/src/dragonball/inner.rs
src/runtime-rs/crates/hypervisor/src/dragonball/inner_hypervisor.rs
src/runtime-rs/crates/hypervisor/src/dragonball/mod.rs
src/runtime-rs/crates/hypervisor/src/lib.rs
src/runtime-rs/crates/resource/src/manager_inner.rs

add hypervisor interface capabilities
1. be able to check does hypervisor support use block device, block
device hotplug, multi-queue, and share file
2. be able to set the hypervisor capability of using block device, block
device hotplug, multi-queue, and share file
Fixes: #5569

runtime-rs:add hypervisor interface capabilities

---

src/dragonball/src/vm/mod.rs

In the current Dragonball code, mem_file_path config is not used when hugetlbfs is enabled.
In this commit we add mem_file_path into hugetlbfs enable process.
fixes: #5566

Dragonball: enable mem_file_path config into hugetlbfs process

---

src/agent/Makefile

This is just to keep the support for s390x without the cosign verification while looking for a solution for #5582.
Fixes: #5599

CC: Make agent build differently for image-rs on s390x

---

src/dragonball/Cargo.toml
src/runtime-rs/Cargo.toml
src/runtime-rs/crates/hypervisor/Cargo.toml

The cargo patch in the cargo.toml seems to cause the whole runtime-rs building time longer and also makes it harder to build runtime-rs in an environment without the network
We should delete all patches from the cargo.toml file and publish all the crates that was once patched.
fixes: #5614 #5527 #5526 #5449

runtime-rs: delete all cargo patches

---

src/dragonball/Cargo.toml
src/runtime-rs/Cargo.lock
src/runtime-rs/crates/hypervisor/Cargo.toml

Since the upstream of vmm-sys-utils upgraded to 0.11.0, some crates automatically upgrade to v0.11.0, and some stay at v0.10.0 ( depending on how they write version dependency in Cargo toml`） which causes the compile error in runtime-rs.
In order to fix this problem, we need to upgrade all vmm-sys-util dependencies in runtime-rs to v0.11.0.
fixes: #5636

versions: update vmm-sys-util and related crates to v0.11.0

---

src/runtime-rs/crates/shim/src/lib.rs

The name shim has multiple potential sources of import, this patch now gives it a clear source.
Fixes: #5535
Signed-off-by: Chen TaoTao <chentt10@chinatelecom.cn>

runtime-rs : fix the shim source in the documentation test is ambiguous

---

docs/how-to/how-to-use-kata-containers-with-firecracker.md

On install you generate a configuration-fc.toml file when building the kata-runtime and copy it to either /etc/kata-containers/configuration-fc.toml or /usr/share/defaults/kata-containers/configuration-fc.toml. To reflect that the path must be one of the above, we can fix the path in doc.

docs: Fix configuration path

---

src/runtime/virtcontainers/clh.go
src/runtime/virtcontainers/qemu.go

clh: don't try to stop clh multiple times
clh: fast exit from isClhRunning if the process was stopped
clh: return faster with dead Cloud Hypervisor process from isClhRunning
qemu: set stopped only if StopVM is successful
qemu: early exit from Check if the process was stopped
Avoid executing StopVM concurrently when virtiofs dies as a result of clh being stopped in StopVM.
Proactively check if Cloud Hypervisor process is dead in isClhRunning
Set stopped to 1 in clh and qemu only if StopVM returns without an error.
Fast exit from Check for both clh and qemu if the process was stopped, uses atomic operations instead of acquiring a mutex.
This stops isClhRunning from generating a deadlock by trying to reacquire an already-acquired lock when called via StopVM->terminate.
Fixes #5622, #5623, …

clh: avoid race condition when stopping clh

---

docs/how-to/how-to-setup-swap-devices-in-guest-kernel.md

`crictl runp` command needs `--runtime kata` option to start a Kata Containers pod.
Fixes: #5678

docs: update doc "Setup swap device in guest kernel"

---

src/agent/Cargo.lock
src/libs/kata-types/Cargo.toml
src/libs/kata-types/src/mount.rs
src/runtime-rs/crates/hypervisor/src/dragonball/inner_device.rs
src/runtime-rs/crates/resource/Cargo.toml
src/runtime-rs/crates/resource/src/manager_inner.rs
src/runtime-rs/crates/resource/src/rootfs/mod.rs
src/runtime-rs/crates/resource/src/rootfs/nydus_rootfs.rs
src/runtime-rs/crates/resource/src/rootfs/share_fs_rootfs.rs
src/runtime-rs/crates/resource/src/share_fs/mod.rs
src/runtime-rs/crates/resource/src/share_fs/share_virtio_fs.rs
src/runtime-rs/crates/resource/src/share_fs/share_virtio_fs_inline.rs
src/runtime-rs/crates/resource/src/share_fs/utils.rs
src/runtime-rs/crates/resource/src/share_fs/virtio_fs_share_mount.rs
src/runtime-rs/crates/resource/src/volume/share_fs_volume.rs
src/runtime-rs/crates/runtimes/src/shim_mgmt/handlers.rs
src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs

support nydus v5 for container rootfs
Fixes:#5142

runtime-rs: support nydus v5 and v6 rootfs

---

src/tools/kata-ctl/Cargo.lock
src/tools/kata-ctl/Cargo.toml
src/tools/kata-ctl/src/utils.rs

Add functionality to get kernel version and related unit tests. This is intended to be used in the kata-env command going forward.
Fixes: #5688

utils: Add utility function to fetch the kernel version.

---

docs/use-cases/NVIDIA-GPU-passthrough-and-Kata.md

We should make sure the hook shell `nvidia-container-toolkit.sh` is executable.
Fixes: https://github.com/kata-containers/kata-containers/issues/5594
Signed-off-by: Matt Wang <kinder_yj@hotmail.com>

docs: update doc "NVIDIA GPU passthrough"

---

src/runtime/go.mod
src/runtime/go.sum
src/runtime/vendor/github.com/Microsoft/hcsshim/internal/jobobject/iocp.go
src/runtime/vendor/github.com/Microsoft/hcsshim/internal/jobobject/jobobject.go
src/runtime/vendor/github.com/Microsoft/hcsshim/internal/jobobject/limits.go
src/runtime/vendor/github.com/Microsoft/hcsshim/internal/queue/mq.go
src/runtime/vendor/github.com/Microsoft/hcsshim/internal/winapi/jobobject.go
src/runtime/vendor/github.com/Microsoft/hcsshim/internal/winapi/process.go
src/runtime/vendor/github.com/Microsoft/hcsshim/internal/winapi/system.go
src/runtime/vendor/github.com/Microsoft/hcsshim/internal/winapi/zsyscall_windows.go
src/runtime/vendor/github.com/containerd/containerd/version/version.go
src/runtime/vendor/modules.txt

Let's follow the binary bump used in the CI and also bump the vendored version of containerd to v1.6.8.
Fixes: #5722

runtime: Use containerd v1.6.8

---

src/runtime/go.mod
src/runtime/go.sum
src/runtime/vendor/github.com/Microsoft/hcsshim/internal/jobobject/iocp.go
src/runtime/vendor/github.com/Microsoft/hcsshim/internal/jobobject/jobobject.go
src/runtime/vendor/github.com/Microsoft/hcsshim/internal/jobobject/limits.go
src/runtime/vendor/github.com/Microsoft/hcsshim/internal/queue/mq.go
src/runtime/vendor/github.com/Microsoft/hcsshim/internal/winapi/jobobject.go
src/runtime/vendor/github.com/Microsoft/hcsshim/internal/winapi/process.go
src/runtime/vendor/github.com/Microsoft/hcsshim/internal/winapi/system.go
src/runtime/vendor/github.com/Microsoft/hcsshim/internal/winapi/zsyscall_windows.go
src/runtime/vendor/github.com/containerd/containerd/version/version.go
src/runtime/vendor/modules.txt

As we bumped containerd dependency to v1.6.8, let's also do the re-vendor of its code on the runtime side.
Fixes: #5745

CC | runtime: Revendor containerd to v1.6.8

---

src/runtime-rs/crates/resource/src/manager_inner.rs

As the increase of the I/O intensive tasks, two issues could be caused:
1. When the future is blocked, the current thread (which is in the network namespace) might be taken over by other tasks. After the future is finished, the thread taking over the current task might not be in the pod netns. But the current task still need to run in pod netns.
2. When finish setting up the network, the current thread will be set back to the host namsapce. But the task which is taken over would still stay in the pod network namespace
To avoid that, we need to block the future on the current thread.
Fixes:#5728

runtime-rs: block on the current thread when setup the network to avoid be take over by other task

---

src/runtime/virtcontainers/utils/utils.go

In case a folder is created by another process continue without generating an error.
Fixes #5713

runtime: don't fail mkdir if the folder is already created by another process

---

tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
tools/packaging/static-build/kernel/build.sh

Now that we're caching the kernel, we're relying on the kernel version
being exported.  This is already done for the CC kernel, but not for the
TEE specific ones.
Fixes: #5770

CC | build: export kernel_version to be used with its build script

---

src/runtime-rs/README.md

When using source code to compile runtime-rs,make the documentation point out the detailed environment build and compilation methods to avoid errors caused by related dependent packages.
Fixes:#5757
Signed-off-by: Chen Taotao <chentt10@chinatelecom.cn>

doc: update runtime-rs "Build and Install"

---

.github/workflows/cargo-deny-runner.yaml
.github/workflows/darwin-tests.yaml
.github/workflows/snap.yaml

If only docs/images are changed, some jobs should not run.
Fixes: #5759

actions: skip some jobs using "paths-ignore" filter

---

Makefile
src/agent/Makefile
src/dragonball/Makefile
src/libs/Makefile
src/runtime-rs/Makefile
src/runtime/Makefile
src/tools/agent-ctl/Makefile
src/tools/kata-ctl/Makefile
src/tools/log-parser/Makefile
src/tools/runk/Makefile
src/tools/trace-forwarder/Makefile
utils.mk

Since the static-checks only need some config/version files to be generated, we can add a new target/rule to create the code required to let static-checks pass.
Fixes: #5777

ci: let static checks don't depend on build

---

tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh

This PR removes extra tab spaces from the kata deploy binaries script.
Fixes #5747

tools: Remove extra tab spaces from kata deploy binaries script

---

src/runtime-rs/crates/resource/src/cgroups/mod.rs

when overhead controller exists, just contrain vCPU threads
in sandbox controller
Fixes:#5760
Signed-off-by: gaohuatao <gaohuatao@bytedance.com>

runtime-rs: moving only vCPU threads into sandbox controller

---

src/agent/src/rpc.rs

Some rootfs put iptables-save and iptables-restore under /usr/sbin instead of /sbin. This pr checks both and returns the one exist.
Fixes: #5608

fix(agent): fix iptables binary path in guest

---

.github/workflows/snap-release.yaml
.github/workflows/snap.yaml

Setup the snapcraft environment manually as the action we had been using for this does not appear to be actively maintained currently.
Related to this, switch to specifying the snapcraft store credentials using the `SNAPCRAFT_STORE_CREDENTIALS` secret. This unbreaks `snapcraft upload`, which Canonical appear to have broken by removing the previous facility.
Fixes: #5772.

snap: Fix snapcraft setup (unbreak snap releases)

---

src/tools/runk/libcontainer/src/activated_builder.rs
src/tools/runk/libcontainer/src/container.rs
src/tools/runk/libcontainer/src/created_builder.rs
src/tools/runk/libcontainer/src/lib.rs
src/tools/runk/src/commands/start.rs
src/tools/runk/src/main.rs

This commit re-implements `start` operation by leveraging the agent codes. Currently, `runk` has own `start` mechanism even if the agent already has the feature to handle starting a container. This worsen the maintainability and `runk` cannot keep up with the changes on the agent side easily. Hence, `runk` replaces own implementations with agent's ones.
Fixes: #5648

runk: Re-implement start operation using the agent codes

---

src/agent/Cargo.lock
src/agent/Cargo.toml
src/agent/src/image_rpc.rs

agent: Add auth reg support
If the attestation-agent is used then enable image_client_auth
to enable the attempt to get registry credentials for the pull
Fixes: #5652

CC | agent: Add auth reg support to the agent

---

src/runtime-rs/Makefile
src/runtime-rs/crates/shim/src/bin/main.rs
src/runtime-rs/crates/shim/src/config.rs.in

The displayed commit message and version message are partially duplicated. Remove the version number from the commit display message.
Fixes:#5735
Signed-off-by: Chen Taotao <chentt10@chinatelecom.cn>

runtime-rs: remove the version number from the commit display message

---

tools/packaging/guest-image/build_image.sh
tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
tools/packaging/scripts/lib.sh
tools/packaging/static-build/cache_components.sh
tools/packaging/static-build/cloud-hypervisor/build-static-clh.sh
tools/packaging/static-build/initramfs/build.sh
tools/packaging/static-build/kernel/build.sh
tools/packaging/static-build/ovmf/build.sh
tools/packaging/static-build/qemu/build-base-qemu.sh
tools/packaging/static-build/qemu/build-static-qemu-cc.sh
tools/packaging/static-build/shim-v2/build.sh
tools/packaging/static-build/td-shim/build.sh
tools/packaging/static-build/virtiofsd/build.sh

This is a huge set of changes that basically re-work how we're caching the components for our CI.
Previously to this work, we've been caching specific binaries and having to implement a specific logic for each component cached.  With this work we're trying to have a more generic solution where we're just caching the final tarball generated by `make cc-${component}` and re-using them whenever possible.
The critereas for using a cached tarball are:
* The base container image used to build the tarball did **not** change
* The version of the component did **not** change
* For components that we carry patches over, we do a check on their folder to see whether something has changed there or not.

Re-work the way we cache components for the CCv0 branch

---

.github/workflows/static-checks-dragonball.yaml

Call cargo in root's HOME may lead to permission error, should call cargo installed in user's HOME/PATH.
Fixes: #5813

workflow: call cargo in user's $PATH

---

.github/workflows/cargo-deny-runner.yaml

There is a syntax error in .github/workflows/cargo-deny-runner.yaml
Fixes: #5808

workflow: fix cargo-deny-runner.yaml syntax error

---

src/agent/Cargo.lock
src/agent/Cargo.toml
src/agent/Makefile

Exclude the image-rs cosign feature when the build target is the s390x architecture.
Change Cargo to use workspace resolver 2 so that conditional include for the image-rs crate is resolved correctly for different targets.
Fixes: kata-containers#5582
Signed-off-by: Matthew Arnold <mattarno@uk.ibm.com>

agent: Fix s390x agent build

---

tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
tools/packaging/static-build/cache_components.sh

This PR allow us to use the virtiofsd cache tarball instead of building it from source.
Fixes #5356

CCv0: use virtiofsd cache

---

src/tools/kata-ctl/Cargo.lock
src/tools/kata-ctl/Cargo.toml

This change added crate `runtime-rs/crates/runtimes` as dependency as it's immediately depended upon by the `direct-volume` feature, see issue [5341](https://github.com/kata-containers/kata-containers/issues/5341) and PR [5467](https://github.com/kata-containers/kata-containers/pull/5467), which introduced the dependency version conflict problem, addressed here by manually sorting out the required versions of crates including `vmm-memory` and `kvm-bindings`. The new versions of the crates are picked directly from the runtime-rs's Cargo.lock.
Fixes #5810
Signed-off-by: Tingzhou Yuan <tzyuan15@bu.edu>

kata-ctl: fix dependency version conflict

---

src/tools/kata-ctl/src/arch/aarch64/mod.rs

For now, we can check if host support running kata by check if "/dev/kvm" exist on aarch64.
Fixes: #5768

kata-ctl: add host check for aarch64

---

tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh

As already done for install_cc_kernel(), let's ensure we export
KATA_BUILD_CC=yes as part of the install_cc_tee_kernel.
This is used to generate the hash of the devices in the initramfs.
Fixes: #5845

kernel: Export KATA_BUILD_CC in install_cc_tee_kernel()

---

docs/install/kata-containers-3.0-rust-runtime-installation-guide.md

Rust version in the installation documentation does not match the requirements. Just fix it.
Fixes: #5841
Signed-off-by: Chen Yiyang <cyyzero@qq.com>

docs: Update the rust version in the installation documentation

---

.gitignore
src/libs/kata-sys-util/src/mount.rs
src/runtime-rs/Cargo.lock
src/runtime-rs/crates/resource/src/share_fs/mod.rs
src/runtime-rs/crates/resource/src/share_fs/share_virtio_fs_inline.rs
src/runtime-rs/crates/resource/src/share_fs/share_virtio_fs_standalone.rs
src/runtime-rs/crates/resource/src/share_fs/utils.rs
src/runtime-rs/crates/resource/src/share_fs/virtio_fs_share_mount.rs
src/runtime-rs/crates/resource/src/volume/block_volume.rs
src/runtime-rs/crates/resource/src/volume/default_volume.rs
src/runtime-rs/crates/resource/src/volume/mod.rs
src/runtime-rs/crates/resource/src/volume/share_fs_volume.rs
src/runtime-rs/crates/resource/src/volume/shm_volume.rs
src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs
src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container_inner.rs

This PR fixes the issue mentioned in #5588. In this pull request all shared volumes, except for rootfs, are bind mounted in sandbox level. That is all volumes referred to the same source on the host are bind mounted only once until no container references to it.
It supports dynamic permission controls as well. For example, when a volume mounted with readonly permission and a new coming container needs readwrite permission, the volume should be upgraded to readwrite permission. At the same time, if readwrite permission is no longer needed, then the volume should be downgraded.
Fixes: #5588 
Signed-off-by: Xuewei Niu <justxuewei@apache.org>

runtime-rs: bind mount volumes in sandbox level

---

src/runtime-rs/crates/runtimes/virt_container/src/container_manager/io/shim_io.rs
src/runtime-rs/crates/runtimes/virt_container/src/container_manager/process.rs

Fixed the issue when using nonblocking, the `tokio::io::copy()` needing to handle EAGAIN, resulting in high CPU usage.
Fixes: #5740

runtime-rs: fix high cpu

---

src/runtime/virtcontainers/utils/utils.go
src/runtime/virtcontainers/utils/utils_darwin.go
src/runtime/virtcontainers/utils/utils_linux.go

runtime: prevent waiting 50 ms minimum for a process exit
Use pidfd_open and poll on newer versions of Linux to wait for the process to exit. For older versions fall back to polling every 50 ms.
Fixes #5617 

runtime: prevent waiting 50 ms minimum for a process exit

---

docs/install/kata-containers-3.0-rust-runtime-installation-guide.md
src/agent/src/rpc.rs
src/runtime-rs/crates/runtimes/src/manager.rs
src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs
src/runtime-rs/crates/runtimes/virt_container/src/container_manager/manager.rs
src/runtime-rs/crates/service/src/manager.rs
src/runtime-rs/crates/service/src/task_service.rs
src/tools/kata-ctl/Cargo.lock
src/tools/kata-ctl/Cargo.toml
src/tools/kata-ctl/src/arch/aarch64/mod.rs

Merge remote-tracking branch 'upstream/main' into CCv0
Fixes: #5854
Signed-off-by: Megan Wright <megan.wright@ibm.com>

CC: Merge main into CCv0 branch

---

.github/workflows/cc-payload-after-push-s390x.yaml

The following issues are identified after #5783 is merged:
1. The same artifact name between 2 architectures → could result in a workflow for s390x fetching artifacts from those of amd64.
2. Lack of virtiofsd for s390x → failed to install ccruntime
This PR is to differentiate an artifact name between amd64 and s390x and add a virtiofsd target for s390x.
Fixes: #5851

CC: Fix issues on cc-payload-ci workflow for s390x

---

tools/packaging/static-build/ovmf/build-ovmf.sh

This PR fixes the indentation for the ovmf script for packaging.
Fixes #5864

tools: Fix indentation for ovmf script

---

tools/packaging/kata-deploy/scripts/kata-deploy.sh

kata-deploy:  Fix after the node restarts, the pod of kata depoy starts to report an error
If a pod of type kata is deployed on a machine, after the machine restarts, the pod status corresponding to kata-deploy will be CrashLoopBackOff. The reason is that kata-deploy will update the installation files in the /opt/kata/ directory. At this time, the pod of the kata type is started, and some files in this directory are occupied and are not allowed to be updated. The -u parameter of the cp command is just suitable for solving it.
The following is the error message before modification, and it has been resolved after modification.
$ kubectl logs -f kata-deploy-hjtc6 -n kube-system
copying kata artifacts onto host
cp: cannot create regular file '/opt/kata/bin/qemu-system-x86_64': Text file busy …

fix kata deploy error after node reboot.

---

.github/workflows/cc-payload-after-push-amd64.yaml
.github/workflows/cc-payload-after-push-s390x.yaml

e1f075dc60794dbcf680e6e9bd424781126b7f5c reworked the action so the shim-v2 was split out of the matrix build.  With that done I ended up not realising I'd need to log into the quay.io as one step of the build-asset-cc-shim-v2 job.
Fixes: #5885

actions: Fix pushing the shim-v2 build image to quay.io

---

src/agent/rustjail/src/container.rs
src/agent/src/rpc.rs
src/agent/src/sandbox.rs
src/tools/runk/libcontainer/src/container.rs

Cgroup manager for a container will always be created.
Thus, dropping the option for LinuxContainer.cgroup_manager is feasible and could simplify the code.
Fixes: #5778

agent: Drop the Option for LinuxContainer.cgroup_manager

---

src/libs/Cargo.lock
src/libs/kata-sys-util/src/mount.rs

Strings in Rust don't have \0 at the end, but C does, which leads to `umount2`
in the libc can't get the correct path. Besides, calling `nix::mount::umount2`
to avoid using an unsafe block is a robust solution.
Fixes: https://github.com/kata-containers/kata-containers/issues/5871
Signed-off-by: Xuewei Niu <niuxuewei.nxw@antgroup.com>

kata-sys-util: fix issues where umount2 couldn't get the correct path

---

src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs

* runtime-rs: clear OCI spec namespace path
* runtime-rs: reset rdma cgroup
* runtime-rs: CreateContainerRequest has Default
* runtime-rs: fix is_pid_namespace_enabled check

runtime-rs: fix sandbox_pidns calculation and oci spec amending 

---

src/libs/kata-types/src/config/default.rs
src/libs/kata-types/src/config/hypervisor/mod.rs
src/runtime-rs/crates/resource/src/share_fs/share_virtio_fs_standalone.rs

Standalone share fs should add virtiofs device in setup_device_before_start_vm
and return the storages to mount the directory in guest. And it uses
hypervisor's jailer root directly instead of jail config.
Besides, we tweaked the parameter, so it adapts to rust version virtiofsd
now. And its cache policy which forbids caching is "never" now,  instead of
"none". Hence, we change the default cache mode.
Fixes: https://github.com/kata-containers/kata-containers/issues/5655
Signed-off-by: Yipeng Yin <yinyipeng@bytedance.com>

runtime-rs: fix standalone share fs

---

tools/packaging/kernel/build-kernel.sh

This PR fixes the indentation on the build kernel script.
Fixes #5883

tools: Fix indentation on build kernel script

---

src/runtime-rs/Cargo.lock
src/runtime-rs/Cargo.toml
src/runtime-rs/README.md
src/runtime-rs/crates/hypervisor/src/lib.rs
src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
src/runtime-rs/crates/hypervisor/src/qemu/mod.rs
src/runtime-rs/crates/runtimes/virt_container/src/lib.rs
src/runtime-rs/crates/shim-ctl/Cargo.toml
src/runtime-rs/crates/shim-ctl/README.md
src/runtime-rs/crates/shim-ctl/src/main.rs

This PR adds basic boilerplate for QEMU driver in runtime-rs. It's obviously far from a full QEMU support but it does enable runtime-rs to start a very basic QEMU process (along with its supporting virtiofsd instance). It also includes (an embryo of) an alternative shim binary that drops containerd dependency and thus makes it fast and easy to execute shim proper, greatly enhancing dev cycle.
The main purpose of this WIP PR is to publish progress so far and give a common base to enable cooperation on QEMU support.
Fixes: #5817

basic framework for QEMU support in runtime-rs

---

src/tools/kata-ctl/Cargo.lock
src/tools/kata-ctl/Cargo.toml
src/tools/kata-ctl/src/args.rs
src/tools/kata-ctl/src/check.rs
src/tools/kata-ctl/src/ops/check_ops.rs

This pull request adds kata-ctl check **only-list-releases** and **include-all-releases**
Fixes: [#5345](https://github.com/kata-containers/kata-containers/issues/5345)
Signed-off-by: Alex Lee [alee23@bu.edu](mailto:alee23@bu.edu)

kata-ctl: check: only-list-releases and include-all-releases options

---

src/libs/Cargo.lock
src/libs/Cargo.toml
src/libs/shim-interface/Cargo.toml
src/libs/shim-interface/src/lib.rs
src/libs/shim-interface/src/shim_mgmt/client.rs
src/libs/shim-interface/src/shim_mgmt/mod.rs
src/runtime-rs/crates/hypervisor/Cargo.toml
src/runtime-rs/crates/hypervisor/src/dragonball/inner.rs
src/runtime-rs/crates/hypervisor/src/dragonball/inner_hypervisor.rs
src/runtime-rs/crates/persist/Cargo.toml
src/runtime-rs/crates/persist/src/lib.rs
src/runtime-rs/crates/runtimes/Cargo.toml
src/runtime-rs/crates/runtimes/src/lib.rs
src/runtime-rs/crates/runtimes/src/manager.rs
src/runtime-rs/crates/runtimes/src/shim_mgmt/handlers.rs
src/runtime-rs/crates/runtimes/src/shim_mgmt/mod.rs
src/runtime-rs/crates/runtimes/src/shim_mgmt/server.rs
src/runtime-rs/crates/service/Cargo.toml
src/runtime-rs/crates/service/src/manager.rs

The client side is moved to libs. This is to solve the problem that including clients will bring about messy dependencies.
Fixes: #5874

refactor(shim-mgmt): move client side to libs

---

.github/workflows/cc-payload-amd64.yaml
.github/workflows/cc-payload-s390x.yaml
.github/workflows/cc-payload.yaml

This is to enable `quay.io/confidential-containers/runtime-payload` for s390x on top of amd64.
The workflow is tested: https://github.com/BbolroC/kata-containers/actions/runs/3688419109
Fixes: #5894

CC: Enable multi-arch build for runtime-payload image

---

src/runtime/pkg/sev/ovmf.go
src/runtime/pkg/sev/sev.go
src/runtime/pkg/sev/sev_test.go
src/runtime/pkg/sev/vcpu_sigs.go
src/runtime/pkg/sev/vmsa.go

This includes constructing VMSA pages, parsing OVMF footer table to fetch the AP reset EIP address, and allowing different vcpu types.
Fixes: #5471
Signed-off-by: Dov Murik <dovmurik@linux.ibm.com>
----
Note that this PR allows calculating expected SEV-ES launch digests, but not yet ties this in into `virtcontainers/qemu_amd64.go` to actually launch SEV-ES guests. This will be done in a subsequent PR.
FYI @jimcadden @fitzthum

CCv0: runtime: pkg/sev: Support SEV-ES launch digest calculation

---

tools/packaging/static-build/ovmf/Dockerfile
tools/packaging/static-build/ovmf/build-ovmf.sh
tools/packaging/static-build/ovmf/build.sh
versions.yaml

Switching sev build of ovmf to the cc fork until patches are upstreamed.
Adding build for dependencies
Fixes: kata-containers#5892
@dubek @fitzthum

CC: static build switching sev ovmf to CC fork

---

docs/how-to/containerd-kata.md
src/runtime-rs/crates/resource/src/manager.rs
src/runtime-rs/crates/resource/src/manager_inner.rs
src/runtime-rs/crates/resource/src/rootfs/mod.rs
src/runtime-rs/crates/resource/src/rootfs/share_fs_rootfs.rs
src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs

enable start container from bundle in this way
$ ls ./bundle
config.json  rootfs
$ sudo ctr run -d --runtime io.containerd.kata.v2 --config bundle/config.json test_kata
Fixes:#5872

runtime-rs: enable start container from bundle

---

src/dragonball/src/api/v1/vmm_action.rs
src/dragonball/src/device_manager/mod.rs

If the serial path is given, legacy_manager should create socket console based on that path. Or the console should be created based on stdio.
Fixes: #5914
Signed-off-by: Yushuo <y-shuo@linux.alibaba.com>

dragonball: refactor legacy device initialization

---

docs/Developer-Guide.md

Script to execute to build virtiofsd has been changed in #5426 but not in the doc. This commit update the developer guide.
Fixes: #5860
Signed-off-by: Mathias Flagey <mathiasflagey1201@gmail.com>

docs: Update virtiofsd build script in the developer guide

---

src/tools/kata-ctl/src/arch/aarch64/mod.rs
src/tools/kata-ctl/src/arch/powerpc64le/mod.rs
src/tools/kata-ctl/src/arch/s390x/mod.rs
src/tools/kata-ctl/src/arch/x86_64/mod.rs
src/tools/kata-ctl/src/ops/check_ops.rs

https://github.com/kata-containers/kata-containers/pull/5735 break CI for non-x86 arches. Fix it here.

kata-ctl: fix checkcpu bug in non-x86 arches

---

src/runtime-rs/Cargo.lock
src/runtime-rs/crates/resource/src/rootfs/mod.rs
src/runtime-rs/crates/resource/src/rootfs/nydus_rootfs.rs
src/runtime-rs/crates/resource/src/rootfs/share_fs_rootfs.rs
src/runtime-rs/crates/resource/src/share_fs/mod.rs
src/runtime-rs/crates/resource/src/share_fs/virtio_fs_share_mount.rs
src/runtime-rs/crates/resource/src/volume/block_volume.rs
src/runtime-rs/crates/resource/src/volume/default_volume.rs
src/runtime-rs/crates/resource/src/volume/share_fs_volume.rs
src/runtime-rs/crates/resource/src/volume/shm_volume.rs
src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container_inner.rs

1. Fixed issues where shared volumes couldn't umount correctly. 
2. The rootfs of each container is cleaned up after the container is killed, except
for `NydusRootfs`. `ShareFsRootfs::cleanup()` calls
`VirtiofsShareMount::umount_rootfs()` to umount mount points shared to the
guest, and umounts the bundle rootfs. 
Fixes: #5898
Signed-off-by: Xuewei Niu <niuxuewei.nxw@antgroup.com>

runtime-rs: Clean up mount points shared to guest

---

src/runtime/pkg/katautils/config.go

Add the SELinux setting to ensure it is passed through to the remote hypervisor
Fixes: #5936

runtime: Update the remote hypervisor config

---

src/libs/Cargo.lock
src/libs/kata-sys-util/src/mount.rs
src/runtime-rs/Cargo.lock
src/runtime-rs/config/configuration-dragonball.toml.in
src/runtime-rs/crates/hypervisor/src/dragonball/inner.rs
src/runtime-rs/crates/hypervisor/src/dragonball/vmm_instance.rs
src/runtime-rs/crates/hypervisor/src/lib.rs
src/runtime-rs/crates/persist/src/lib.rs
src/runtime-rs/crates/resource/Cargo.toml
src/runtime-rs/crates/resource/src/manager.rs
src/runtime-rs/crates/resource/src/manager_inner.rs
src/runtime-rs/crates/resource/src/share_fs/mod.rs
src/runtime-rs/crates/resource/src/share_fs/virtio_fs_share_mount.rs
src/runtime-rs/crates/resource/src/volume/hugepage.rs
src/runtime-rs/crates/resource/src/volume/mod.rs
src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs

enable the functionality of using hugepages in container
Fixes: #5560

runtime-rs: enable hugepage

---

utils.mk

When `HOST_ARCH` != `ARCH` unset `CC`
Fixes: #5890
Signed-off-by: James Tumber <james.tumber@ibm.com>

agent: unset `CC` for cross-build

---

tools/packaging/guest-image/build_image.sh

the switch to cases lets AA_KBC to be parsed correctly.
There will be an addition to the offline_sev_kbc case to do the same for online_sev_kbc
There will also be an addition for SNP
Fixes: #5909

osbuilder: fix kernel module copy logic in rootfs builder

---

src/tools/kata-ctl/Cargo.lock
src/tools/kata-ctl/src/check.rs

This commit will call `error_for_status` after `send`, this call
will generate errors if status code between 400-499 and 500-599.
And sometime access github.com will fail, in this case we can
skip the test to prevent the CI failing.
Fixes: #5948

kata-ctl: skip test if access GitHub.com fail

---

tools/packaging/static-build/kernel/Dockerfile

adding kmod to kernel building docker env to remove warning
Fixes: kata-containers#5866

kernel: adding kmod to do docker env

---

tools/packaging/kernel/build-kernel.sh

In the function get_kernel, the indents are two tabs, which should be 1 tab.
Fixes: #5944

packaging: fix indents in build-kernel.sh

---

docs/install/minikube-installation-guide.md

Some instructions are old, delete them to prevent misleading.
Fixes: #5942

docs: remove old and misleading instructions for minikube

---

ci/install_yq.sh
src/runtime/Makefile

Substitution in the yq install script doesn't like zsh, and additionally
the version of yq we're using doesn't have a darwin/arm64 build so grab
the amd64 version and let rosetta work its magic.
This also swaps to abspath from readlink -m for the printing of what binaries
to install, as the -m flag doesn't exist on the BSD variant, and this
should be the same behavior.
Fixes: https://github.com/kata-containers/kata-containers/issues/5970

runtime/Makefile: Get some bits happy on darwin

---

src/runtime/pkg/sev/vcpu_sigs.go
src/runtime/pkg/sev/vcpu_sigs_test.go
src/runtime/virtcontainers/qemu_amd64.go

The `sev_guest_policy` configuration field distinguishes between SEV and SEV-ES guests (according to standard AMD SEV policy values).
Modify the kata runtime to detect SEV-ES guests and calculate calculate the expected launch digest taking into account the number of VCPUs and their CPU signature (model/family/stepping).
Fixes: #5471
Signed-off-by: Dov Murik <dovmurik@linux.ibm.com>
----
Note that the default SEV policy will remain `3` for now (see #5665), which is SEV mode.
I think that after this successfully lands in CCv0, we can add a CI test which starts an SEV-ES pod. No corresponding change is needed in simple-kbs. It will be easier to choose between SEV and SEV-ES pods after we have the annotations override for `sev_guest_policy` (= `io.katacontainers.config.sev.policy`) in PR …

CCv0: runtime: Support launching SEV-ES guests

---

utils.mk

When `HOST_ARCH` != `ARCH` unset `CC`
Specifying a foreign CC is incompatible with building libgit2. Thus after the RUSTFLAGS linker has been set we can safely unset CC to avoid passing this value through the build.
Fixes: #5890
Signed-off-by: James Tumber <james.tumber@ibm.com>
Cherry-picked: 087515a

CC | agent: unset `CC` for cross-build

---

versions.yaml

Cloud Hypervisor published a bug fix release v28.1 with the following issues being addressed:
* Update dependencies including a version of `linux-loader` that addresses an infinite loop issue ([details](https://github.com/rust-vmm/linux-loader/security/advisories/GHSA-52h2-m2cf-9jh6))
* Fix bugs related to `virtio-net` including an integer overflow issue
* Use host `cpuid` information for L2 cache for older KVM on x86 
* Improve README and documentation
Details can be found here: https://github.com/cloud-hypervisor/cloud-hypervisor/releases/tag/v28.1
Fixes: #5973

versions: Upgrade to Cloud Hypervisor v28.1

---

src/runtime/pkg/containerd-shim-v2/shim_management.go

add rust runtime path for kata-runtime exec
Fixes:#5963

kata-runtime: add rust runtime path for kata-runtime exec

---

src/runtime/virtcontainers/vm.go

Was about to change `urandomdev` to a constant when I realized it's intentionally mutable so it can be mocked in tests. There's other comments to the same effect so clarify here as well.
Fixes: https://github.com/kata-containers/kata-containers/issues/5965

Runtime: Clarify mutability of global var

---

src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs

Cleanup the run dir of hypervisor when shut down.
Fixes: #5825
Signed-off-by: yaoyinnan <yaoyinnan@foxmail.com>

runtime-rs: cleanup the run dir of hypervisor when shut down

---

src/runtime/pkg/utils/schedcore.go
src/runtime/pkg/utils/schedcore_linux.go
src/runtime/pkg/utils/schedcore_other.go

Fixes: #5983
sched-core only makes sense on Linux hosts. Let's add stub/error for other platforms.

schedcore: Make buildable on !linux

---

src/agent/Cargo.lock
src/agent/rustjail/Cargo.toml
src/agent/rustjail/src/container.rs
src/libs/Cargo.lock
src/libs/kata-sys-util/src/hooks.rs
src/libs/kata-sys-util/src/validate.rs
src/tools/runk/Cargo.lock
src/tools/runk/libcontainer/Cargo.toml
src/tools/runk/libcontainer/src/container.rs

We have to execute some hooks both in host and guest. And in /libs/kata-sys-util/src/hooks.rs, the coomon operations are implemented.
In this commit, we are going to refactor the code of guest hooks using code in /libs/kata-sys-util/src/hooks.rs.
Fixes:#5857
Signed-off-by: Yushuo <y-shuo@linux.alibaba.com>

agent: refactor guest hooks

---

src/runtime/virtcontainers/clh.go

Docker / Moby 23.0.0-rc1 has added support to other containerd runtimes (see https://github.com/moby/moby/commit/547da0d575519a197fbf4e0543555d508d176084), and it means that Kata Containers will be supported again.  @bergwolf worked on the bits missing as part of https://github.com/kata-containers/kata-containers/pull/5972, which got QEMU working, but not Cloud Hypervisor.
Now we're adding the needed bits to have Cloud Hypervisor working with Docker.
Before this PR:
```
docker: Error response from daemon: failed to create shim task: cannot hotplug device: unsupported device type '2': unknown.
```
With this PR:
```
5.19.2
PING www.google.com (142.251.36.100): 56 data bytes
64 bytes from 142.251.36.100: seq=0 ttl=114 time=13.217 ms
64 bytes from 142.251.36.100: seq=1 ttl=114 time=15.918 ms …
```

clh: Ensure it works with Docker / Moby

---

src/runtime/virtcontainers/nydusd.go
src/runtime/virtcontainers/nydusd_linux.go
src/runtime/virtcontainers/nydusd_other.go

Fixes: #5985
With nydus not being its own pkg, it is challenging to implement cleanly in a virtcontainers package that isn't necesarily Linux-only. The existing code utilizes network namespace code in order to ensure nydus is launched in the host netns. This is very Linux specific - so let's make sure we only carry this out in a linux specific file.
In the Darwin case, to allow for compilation at least, let's add a stub for doNetNS. Ideally the nydus and vc code can be refactored / decoupled.

nydus: net-ns handling needs to be only executed on Linux hosts

---

src/runtime/pkg/signals/signals.go
src/runtime/pkg/signals/signals_darwin.go
src/runtime/pkg/signals/signals_linux.go

Fixes: #5990
Some signals may not be defined on non Linux host OSes, like SIGSTKFLT for example. It's also not defined on certain architectures, but irrelevant for this.
/cc @egernst

runtime: Define Darwin handled signals list

---

src/tools/kata-ctl/src/arch/s390x/mod.rs
src/tools/kata-ctl/src/check.rs
src/tools/kata-ctl/src/ops/check_ops.rs

Some type is not imported in s390x's mod file.
Fixes: #5987

kata-ctl: fix build error on s390x

---

src/tools/kata-ctl/Makefile
src/tools/kata-ctl/src/check.rs

In `src/tools/kata-ctl/src/check.rs`, there is a function `get_kata_version_by_url` in the tests mod,
indeed we can use the `get_kata_all_releases_by_url` in the main mod to replace it.
Fixes: #5981

kata-ctl: remove get_kata_version_by_url function

---

src/runtime/virtcontainers/fs_share_darwin.go

Fixes: #6002
As a first pass for testing, let's add a skeleton for filesystem sharing support on Darwin.

virtcontainers: fs_share: Add Darwin skeleton

---

tools/packaging/guest-image/build_image.sh

Bug fix for #5651. Faulty bash syntax let a initrd build complete, but not copy the kernel module. This change fixes the if logic to work as an 'or' as intended.
Fixes: #6024

osbuilder: copy efi_secret module for online_sev_kbc

---

docs/how-to/how-to-set-sandbox-config-kata.md
src/libs/kata-types/src/annotations/mod.rs
src/libs/kata-types/src/config/hypervisor/mod.rs
src/runtime-rs/crates/resource/src/share_fs/share_virtio_fs_standalone.rs
src/runtime/config/configuration-clh.toml.in
src/runtime/config/configuration-qemu.toml.in
src/runtime/pkg/katautils/config_test.go
src/runtime/pkg/oci/utils_test.go
src/runtime/virtcontainers/documentation/api/1.0/api.md
src/runtime/virtcontainers/hypervisor.go
src/runtime/virtcontainers/kata_agent.go
src/runtime/virtcontainers/persist/api/config.go
src/runtime/virtcontainers/pkg/annotations/annotations.go
src/runtime/virtcontainers/virtiofsd.go
src/runtime/virtcontainers/virtiofsd_test.go

New Rust virtiofsd's `cache` mode doesn't support `none` mode,
we should use `never` to replace it.         
Fixes: #6018

Change cache mode from none to never

---

src/libs/kata-sys-util/src/spec.rs
src/libs/kata-types/src/container.rs
src/libs/kata-types/src/k8s.rs
src/runtime-rs/crates/shim/src/shim_start.rs

For now, only pod_sandbox and pod_container are supported. It doesn't cover the case that container started by ctr which is a single_container defined in kata 2.0. Port the single_container kata type from kata 2.0 to kata 3.0.

runtime-rs: add Single Container support

---

src/tools/agent-ctl/Cargo.lock
src/tools/agent-ctl/Makefile
src/tools/kata-ctl/Makefile

There is a broken release of cgroup-rs, but cargo install will not use the version in Cargo.lock, so add the `--locked` option to use the version specified in the Cargo.toml
Fixes: #5376

tools: add --locked option for cargo install

---

tools/packaging/kata-deploy/local-build/Makefile

This is to adjust dependencies for a target `cc-payload` based on architecture. It follows a build order found in the GHA workflow (kernel &rightarrow; qemu &rightarrow; rootfs &rightarrow; virtiofsd &rightarrow; shim-v2)
Fixes: #6028

CC: Support s390x for target cc-payload in Makefile

---

tools/packaging/scripts/lib.sh

As the toolchain is installed in the image itself, we *must* take the toolchain into consideration when deciding whether to use a cached image or building a new one.
Fixes: #6033

CC | packaging: Take toolchain version when using the td-shim builder image

---

src/runtime/virtcontainers/sandbox.go

With `disable_netns=true`, we should never scan the sandbox netns which is the host netns in such case.
Fixes: #6021

runtime: fix up disable_netns handling

---

src/runtime/.gitignore

Add test generated file to .gitignore to avoid making the working directory dirty.
Fixes: #6031

runtime: add test generated file to .gitignore

---

src/agent/Cargo.lock
src/agent/Cargo.toml
versions.yaml

---
versions: Update TD-Shim version to v0.3.0
TD-Shim has released its v0.3.0 release earlier Today, following the
Confidential Containers v0.3.0 release.
Let's update it here.  We need to also bump the toolchain to using the
nightly-2022-11-15
---
build: Update image-rs to v0.3.0
image-rs has released its v0.3.0 release earlier Today, following the
v0.3.0 Confidential Containers release process.
The v0.3.0 is based on exactly the same commit we've been using already,
so no changes are expected for us.
---
versions: Bump attestation-agent to v0.3.0
The attestation-agent had its v0.3.0 release earlier Today, following
the Confidential Containers v0.3.0 release process.
Let's bump it on our side, as we've already tested the version that
became this release.
---

CC | Update dependencies for the v0.3.0 release

---

src/runtime/virtcontainers/clh.go

This PR fixes a misspelling in the error message when it tries to run a system without Confidential computing support.
Fixes #6042

virtcontainers: Fix misspelling in error message

---

src/runtime/Makefile

The .git-commit can be a multiple line file, potentially confusing the Darwin linker for example.
Fixes: #6046

runtime: Use git rev-parse for the kata-monitor tag

---

src/runtime/virtcontainers/kata_agent_linux_test.go

In TestHandleHugepages it will do a mount operation with different pagesizes, but some systems only support 2M pagesize, test for a 1g pagesize will fail.
This commit try to fix by only mount pagesizes under `/sys/kernel/mm/hugepages`, which are supported to mount by the OS.
Fixes: #6029

runtime: use system pagesize for hugepage test

---

src/tools/runk/Cargo.lock
src/tools/runk/Cargo.toml
src/tools/runk/src/commands/kill.rs
src/tools/runk/src/main.rs

We can remove the custom kill command.
Fix: https://github.com/kata-containers/kata-containers/issues/6083

runk: Upgrade liboci-cli to v0.0.4

---

src/runtime/pkg/containerd-shim-v2/wait.go

When the vmm process exits abnormally, a goroutine sets s.monitor
to null in the 'watchSandbox' function without getting service.mu,
This will cause another goroutine to block when sending a message
to s.monitor, and it holds service.mu, which leads to a deadlock.
For example, the wait function in the file
.../pkg/containerd-shim-v2/wait.go will send a message to s.monitor
after obtaining service.mu, but s.monitor may be null at this time
Fixes: #6059
Signed-off-by: ls <335814617@qq.com>

 runtime:all APIs are hang in the service.mu

---

tools/packaging/scripts/configure-hypervisor.sh
versions.yaml

As QEMU released its v7.2.0 version in December last year, last do the bump on our side.
A few configuration options have been removed between the v6.2.0 (the vcersion we currently use) and v7.2.0, so those have also been dropped from our configure-hypervison.sh script (for this specific version).
Fixes: #6102

versions: Bump QEMU to v7.2.0

---

src/runtime/cmd/kata-runtime/kata-check_amd64.go

Fixes: #6095
We're already importing the virtcontainers package so might as well use the constants for the hypervisor types we're checking against instead of typing the names out in the switch cases.

runtime: Use consts in `kata-runtime check`

---

versions.yaml

v29.0. The following user visible changes have been made:
On `x86-64` the binary included in releases supports both the KVM and MSHV
hypervisor with runtime detection to identify the correct hypervisor to use.
Improvements have been made to the data structures used for both live migration
and snapshot/restore. Unfortunately this has broken compatibility with older
versions (support for migrating between major versions is not yet officially
supported but has worked for some versions.)
Improvements have been made to the volume of heap allocations when running with
`virtio-block` devices along with a reduction in the peak heap size.
Support for "pinging" the VMM and …

versions: Upgrade to Cloud Hypervisor v29.0

---

versions.yaml

Use cni plugins v1.2.0 to get latest fixes.
Fixes: #6110

versions: update cni plugins version

---

docs/use-cases/using-Intel-QAT-and-kata.md

This PR updates the url link in QAT documentation.
Fixes #6130

docs: Update url link in QAT documentation

---

tools/packaging/static-build/cache_components.sh

These changed will be consumed by SEV firmware caching job in the CI. This will help in reducing the CI runtime.
Fixes: #6119 
Signed-off-by: Unmesh Deodhar <udeodhar@amd.com>

Adding caching capability for SEV ovmf

---

src/runtime/pkg/govmm/qemu/examples_test.go
src/runtime/pkg/govmm/qemu/qemu.go
src/runtime/pkg/govmm/qemu/qemu_test.go
src/runtime/pkg/govmm/qemu/qmp.go
src/runtime/pkg/govmm/qemu/qmp_test.go
src/runtime/virtcontainers/qemu.go

The goal of this PR is to collect error messages emitted by QEMU. This requires to not put `-daemonize` on the QEMU command line otherwise it won't produce any output. This has several impacts:
- no guarantees that QEMU is functional when LaunchQemu() returns
- QEMU becomes a direct child that should be reaped when terminated
The QMP connection is now pre-established. The listening socket is then passed to QEMU : the shim just has to wait for the QMP greeting or a disconnect, similarly as what we get with the current code.
QEMU is now started with [Cmd.Start](https://pkg.go.dev/os/exec#Cmd.Start) instead of [Cmd.Run](https://pkg.go.dev/os/exec#Cmd.Run). The Cmd structure is kept around until QEMU is terminated and waited for with [Cmd.Wait](https://pkg.go.dev/os/exec#Cmd.Wait).
Some logic …

runtime: Start QEMU undaemonized and get logs

---

docs/how-to/how-to-hotplug-memory-arm64.md

The key steps in how-to-hotplug-memory-arm64.md are missing, resulting in the kata qemu pod not being created successfully.
Fixes: #6105
Signed-off-by: SinghWang <wangxin_0611@126.com>

docs: Fix missing critical steps in how-to-hotplug-memory-arm64.md

---

.github/workflows/kata-deploy-push.yaml
.github/workflows/kata-deploy-test.yaml
.github/workflows/release.yaml
tools/packaging/kata-deploy/local-build/Makefile
tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh

kata-deploy: Add kernel-dragonball-experimental target
As Chao Wu added the support for building the dragonball kernel as a new
experimental kernel, let's make sure we reflect that as part of the
kata-deploy build scripts.
---
release: Add the dragonball-experimental kernel
Let's add the dragonball specific kernel, which takes advantage of
upcall, as part of the release tarball, so it can be used from the
release tarball / kata-deploy.
---
kata-deploy-test: Ensure we build dragonball specific kernel
As the dragonball specific kernel is now part of the release, let's make
sure we build it as part of the kata-deploy-test action.
Fixes: #5859
Signed-off-by: Fabiano …

Add kernel-dragonball-experimental to kata-deploy, kata-deploy-test, and the release

---

docs/Developer-Guide.md

The default for the agent today is building with seccomp support. However, additional steps need to be taken for building against musl such as installing the static seccomp library for musl. Add documentation to explain this.
Fixes #6136

docs: Add documentation for building agent with seccomp support.

---

versions.yaml

A new release was made for the cni plugins. Use the new version for the CI.
Fixes: #6169

cni: Update cni plugins version to 1.2.0

---

src/runtime/pkg/containerd-shim-v2/shim_management.go

os.Stat("unix:///run/vc/sbs/sid/shim-monitor.sock") will fail, should be os.Stat("/run/vc/sbs/sid/shim-monitor.sock")
Fixes:#6148

runtime:fix stat uds path

---

tools/packaging/static-build/virtiofsd/build-static-virtiofsd.sh

`link-self-contained` is not supported on ppc64le rust target.
Hence, do not pass it while building virtiofsd.
Fixes: #6195

virtiofsd: fix the build on ppc64le

---

tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile

This is to make a docker version to v20.10 in docker upstream image ubuntu:20.04 for s390x|ppc64le.
Fixes: #6211

CI: Make docker version stick to v20.10 in ubuntu:20.04 for s390x|ppc64le

---

src/agent/src/watcher.rs
src/runtime/pkg/containerd-shim-v2/stream_test.go
src/tools/kata-ctl/Cargo.toml
src/tools/kata-ctl/src/ops/volume_ops.rs
src/tools/kata-ctl/src/utils.rs

There are lots of unit test failure on arm64. fix or skip them to unblock the CI.

arm64/CI: fix unit test failure on arm64

---

tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
tools/packaging/static-build/virtiofsd/build-static-virtiofsd.sh

This backports #6212 and #5523 to stable-3.0 :
f49b89b632e6 ("CI: Set docker version to v20.10 in ubuntu:20.04 for s390x|ppc64le")
43fcb8fd0906 ("virtiofsd: Not use "link-self-contained=yes" on s390x")
Fixes: #6211 for stable-3.0
Fixes: #5522 for stable-3.0

Backport CI fixes for s390x and ppc64le to stable-3.0

---

src/dragonball/src/api/v1/vmm_action.rs
src/dragonball/src/error.rs
src/dragonball/src/vcpu/mod.rs
src/dragonball/src/vcpu/vcpu_impl.rs
src/dragonball/src/vcpu/vcpu_manager.rs
src/dragonball/src/vm/mod.rs
src/runtime-rs/crates/hypervisor/src/dragonball/vmm_instance.rs

Add cpu resize ability upon upcall communication channel. Runtime could use ResizeVcpu VmmAction and pass the desired vCPU number to the Dragonball hypervisor.
Dragonball will trigger the device manager service in guest kernel's upcall server to do cpu resize.
fixes: kata-containers#6008

Dragonball: add cpu resize ability

---

src/runtime/virtcontainers/fs_share_linux.go

Normally, the span name should be the same as the function name, and the log subsystem should not contain spaces.
Fixes #6153
Signed-off-by: joannejchen <chenjjoanne@gmail.com>

improvement: Fix naming conventions for span name and log subsystem

---

src/runtime/pkg/govmm/qemu/examples_test.go
src/runtime/pkg/govmm/qemu/qemu.go
src/runtime/pkg/govmm/qemu/qemu_test.go
src/runtime/pkg/govmm/qemu/qmp.go
src/runtime/pkg/govmm/qemu/qmp_test.go
src/runtime/virtcontainers/qemu.go

This backports recent work on QEMU logs:
- don't daemonize QEMU
- collect QEMU logs from stderr
- drop QEMU log file support (unsafe, can fill up host storage)
Fixes #5780 for stable-3.0
Fixes #6173 for stable-3.0

Qemu logs for stable 3.0

---

tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile

This is to make a docker version to v20.10 in docker upstream image ubuntu:20.04 for s390x and ppc64le.
Fixes: #6211
Cherry-picked: f49b89b

CI: Set docker version to v20.10 in ubuntu:20.04 for s390x|ppc64le

---

tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
tools/packaging/static-build/cache_components.sh
tools/packaging/static-build/shim-v2/build.sh
tools/packaging/static-build/shim-v2/install_go_rust.sh

We've disabled building shim-v2 as part of https://github.com/kata-containers/kata-containers/commit/299829aec09a1f237b85bc6cebd49980766ef33f. However, now TDX support will be implemented there and we must start considering it for building and caching the shim-v2 tarball.

CC | Take runtime-rs into consideration when building and caching the shim-v2 tarball

---

src/runtime/pkg/containerd-shim-v2/create_test.go
src/runtime/pkg/katatestutils/utils.go

ShimPath and ShimDebug are not needed anymore.
Fixes: #6147
Signed-off-by: d3c3mber <tangbo_gl_2022@163.com>

runtime: remove not used shim configurations

---

src/runtime/virtcontainers/clh.go

launchClh already has a timeout of 10seconds for launching clh, e.g. if launchClh or setupVirtiofsDaemon takes a few seconds the context's deadline will already be expired by the time it reaches bootVM

clh: Enforce API timeout only for vm.boot request

---

.github/workflows/static-checks.yaml
tools/packaging/kernel/README.md

github-action: Add step to verify kernel config version id updated
The version mentioned in the `kata_config_version` needs to be
updated for any kernel config change or changed to the patches applied.
Without this, CI would not test with the latest kernel changes.
We use to enforce this earlier as part of CI when `packaging` was
a standalone repo.
Add back this check as part of a github action so that the check is
performed early on instead of a CI job.
Fixes: kata-containers/tests#5419

Action check kernel config version

---

docs/how-to/how-to-hotplug-memory-arm64.md

The key steps in how-to-hotplug-memory-arm64.md are missing, resulting in the kata qemu pod not being created successfully.
Fixes: #6105

main | docs: Fix missing critical steps in how-to-hotplug-memory-arm64.md

---

src/runtime/config/configuration-qemu.toml.in
src/runtime/pkg/govmm/qemu/qemu.go
src/runtime/pkg/katautils/config-settings.go.in
src/runtime/pkg/katautils/config.go
src/runtime/pkg/katautils/config_test.go
src/runtime/virtcontainers/hypervisor.go
src/runtime/virtcontainers/qemu_amd64.go

Removed the qemu paramter 'policy' (and also dh-cert-file, session-file, kernel-hashes=on) for SNP container.
Fixes: #5795
Signed-off-by: Niteesh Dubey <niteesh@linux.ibm.com>

CCv0: Enable 'policy' for SNP container

---

tools/osbuilder/rootfs-builder/rootfs.sh

Already being passed 10 lines above the removed one.
Fixes: #6237

osbuilder: remove duplicate KATA_BUILD_CC entry

---

src/runtime/pkg/govmm/qemu/qemu.go

The cmd.ExtraFiles feature that is used to implement appendFDs takes an array of arbitray file descriptors and internally renumbers them to be consecutive starting from 3, using dup2().
This isn't especially obvious : document it for the sake of clarity.
Fixes #6199

runtime: Improve documentation of appendFDs

---

docs/how-to/how-to-hotplug-memory-arm64.md

The key steps in how-to-hotplug-memory-arm64.md are missing, resulting in the kata qemu pod not being created successfully.
Fixes: #6105
Signed-off-by: SinghWang <wangxin_0611@126.com>

stable-3.0 | docs: Fix missing critical steps in how-to-hotplug-memory-arm64.md

---

tools/packaging/static-build/shim-v2/Dockerfile

This is to explicitly install a binary `protoc`, which is missing for s390x, in shim-v2 Dockerfile.
Fixes: #6244

CCv0: install protobuf-compiler explicitly in shim-v2 Dockerfile

---

src/runtime-rs/Makefile

Right now only x86_64 and ARM are supported.
Fixes: #6142

shim-v2/build.sh: Only build runtime-rs for the supported arches

---

src/runtime/virtcontainers/qemu_amd64.go
src/runtime/virtcontainers/qemu_amd64_test.go

Updating this field, as `cpuid` provides host level data, which is not
what a guest would expect for Reduced Phsycial Bits. In almost all
cases, we should be using `1` for the value here.
Fixes: #5006
Signed-off-by: Larry Dewey <larry.dewey@amd.com>

SEV: Update ReducedPhysBits

---

src/runtime-rs/Makefile

ATM, CI jobs for s390x and ppc64le are failing due to lack of support for runtime-rs. This is to stop building runtime-rs for the architectures.
Fixes: #6142
(cherry picked from commit 4139d68d516c2272c76cc042d4b885a22621e526)
(cherry picked from commit c0713553597660be7d999446a815a05cf831c0f3)
(cherry picked from commit 4e2db96ef76d48de3bd8cff119d27b64a478f75d)

CCv0: shim-v2: Only build runtime-rs for the supported arches

---

src/dragonball/src/api/v1/instance_info.rs
src/dragonball/src/api/v1/mod.rs
src/dragonball/src/error.rs
src/dragonball/src/kvm_context.rs
src/dragonball/src/vm/mod.rs

add confidential_vm_type to let Dragonball create a TDX VM.
Signed-off-by: fengshifang <fengshifang@linux.alibaba.com>

CC |  Dragonball: add confidential_vm_type for TDX

---

src/runtime/virtcontainers/clh.go

Normally we return the context when creating a trace span so that the ordering of spans w.r.t. calls is maintained in tracing output. Add missing context for StartVM() for Cloud Hypervisor.
Fixes #6271

runtime: tracing: Fix missing ctx return

---

.github/workflows/cc-payload-after-push-s390x.yaml

It is just to place a missing stage for permission adjustment in the cc-payload-after-push-s390x workflow.
Fixes #6278

CC|action: Place permission adjustment for s390x kata-payload

---

tools/packaging/static-build/shim-v2/Dockerfile

This is to install a missing binary protoc in shim-v2 Dockerfile.
Fixes: #6244
(cherry picked from commit 10603e3deff8d4f9907ade320d727ef343970a2f)

kata-deploy: Install protobuf-compiler explicitly in shim-v2 Dockerfile

---

docs/how-to/how-to-use-kata-containers-with-firecracker.md

Removed the `` around containerd, because when you execute this as a script it runs the containerd command within the script, which it should not do.
Fixes #4217
Original PR is https://github.com/kata-containers/kata-containers/pull/4216

Assisted PR | docs: Update how-to-use-kata-containers-with-firecracker.md

---

src/libs/kata-types/src/config/default.rs
src/libs/kata-types/src/config/hypervisor/ch.rs
src/libs/kata-types/src/config/hypervisor/mod.rs
src/libs/kata-types/src/config/mod.rs
src/runtime-rs/Cargo.lock
src/runtime-rs/crates/hypervisor/Cargo.toml
src/runtime-rs/crates/hypervisor/README.md
src/runtime-rs/crates/hypervisor/ch-config/Cargo.toml
src/runtime-rs/crates/hypervisor/ch-config/src/ch_api.rs
src/runtime-rs/crates/hypervisor/ch-config/src/lib.rs
src/runtime-rs/crates/hypervisor/ch-config/src/net_util.rs
src/runtime-rs/crates/hypervisor/ch-config/src/virtio_devices.rs
src/runtime-rs/crates/hypervisor/src/ch/inner.rs
src/runtime-rs/crates/hypervisor/src/ch/inner_device.rs
src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
src/runtime-rs/crates/hypervisor/src/ch/mod.rs
src/runtime-rs/crates/hypervisor/src/ch/utils.rs
src/runtime-rs/crates/hypervisor/src/hypervisor_persist.rs
src/runtime-rs/crates/hypervisor/src/lib.rs
src/runtime-rs/crates/runtimes/virt_container/Cargo.toml
src/runtime-rs/crates/runtimes/virt_container/src/lib.rs

Add a basic runtime-rs `Hypervisor` trait implementation for Cloud Hypervisor (CH).
> **Note:**
>
> This only supports a default Kata configuration for CH currently.
Fixes: #5242.

runtime-rs: Add basic CH implementation

---

src/dragonball/src/api/v1/instance_info.rs
src/dragonball/src/vm/mod.rs

In order to disable or enable some features when running tdx vms, we need to add is_tdx_enabled() function to identify whether the VM confidiential type is TDX.
fixes: #6276
Signed-off-by: fengshifang <fengshifang@linux.alibaba.com>

CC | Dragonball TDX: add is_tdx_enabled to identify tdx VM type

---

tools/packaging/static-build/shim-v2/build.sh

Let's not try to sed a file that doesn't exist, which may be the case depending on the architecture we're building the shim-v2 for.
This is a partial-forward port of
f24c47ea47e39bdc28bb740d5281eba21fa5727d.
Fixes: #6293

packaging/shim-v2: Only change the config if the file exists

---

src/agent/src/network.rs
src/libs/kata-types/src/config/default.rs
src/runtime-rs/crates/runtimes/common/src/sandbox.rs
src/runtime-rs/crates/runtimes/src/manager.rs
src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs

The rust agent had supported to set the guest dns
server in start sandbox request, thus add the dns
in the runtime side.
Fixes:#6286

sandbox: set the dns for the sandbox

---

src/runtime-rs/crates/resource/src/volume/mod.rs
src/runtime-rs/crates/resource/src/volume/share_fs_volume.rs

For some cases, users will mount system directories as bind volume. We should not bind mount these kind of directories in the host as it does not make sense.
Fixes: #6299

runtime-rs: handle sys_dir bind volume

---

src/runtime-rs/arch/powerpc64le-options.mk
tools/packaging/static-build/shim-v2/install_go_rust.sh

---
packaging/shim-v2: Install the target depending on the arch/libc
In the `install_go_rust.sh` file we're adding a
x86_64-unknown-linux-musl target unconditionally.  That should be,
instead, based in the ARCH of the host and the appropriate LIBC to be
used with that host.
---
runtime-rs: Add a generic powerpc64le-options.mk
There's a check in the runtime-rs Makefile that basically checks whether
the `arch/$arch-options.mk` exists or not and, if it doesn't, the build
is just aborted.
With this in mind, let's create a generic powerpc64le-options.mk file
and not bail when building for this architecture.
Fixes: #6142
---

runtime-rs: Don't build on Power, don't break on Power.

---

src/runtime-rs/crates/hypervisor/src/dragonball/inner.rs
src/runtime-rs/crates/hypervisor/src/dragonball/mod.rs
src/runtime-rs/crates/runtimes/linux_container/src/lib.rs
src/runtime-rs/crates/runtimes/src/manager.rs
src/runtime-rs/crates/runtimes/virt_container/src/container_manager/manager.rs
src/runtime-rs/crates/runtimes/virt_container/src/lib.rs
src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
src/runtime-rs/crates/runtimes/wasm_container/src/lib.rs

Send and Sync are automatically derived traits,
if a type is composed entirely of Send or Sync types, then it is Send or Sync. Almost all primitives are Send and Sync,
so we don't need to implement them manually most of the time.
Fixes: #6307

runtime-rs: remove unnecessary Send/Sync trait implement

---

docs/Release-Process.md

When a new stable branch is created, it is necessary to change the references in the tests repo from main to the new stable branch.
However this step needs to be performed after the repos have been tagged as the `tags_repos.sh` script is the one that creates the new branch. Clarify this in the documentation and move the step to change branch references in test repo after repos have been tagged.
Fixes: #1824

docs: Change the order of release step

---

.github/workflows/add-backport-label.yaml
.github/workflows/kata-deploy-test.yaml
.github/workflows/release.yaml

Signed-off-by: jongwooo <jongwooo.han@gmail.com>
Resolve  #6266 
Update workflows to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow files that use `set-output` command through the following command:
```bash
$ find .github/workflows -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```

github-action: Replace deprecated command with environment file

---

versions.yaml

Currently ubuntu is already the default distro for all the architectures but x86_64, which uses clearlinux.  However, our CI does *not* test the clearlinux image we ship.
Taking a look at our CI code [0], we've been using ubuntu as base for the tests for a few years already, if not forever.
The minimum we can do is to switch to distributing ubuntu, as the tested rootfs-image, and then decide later on whether we should switch back to clearlinux (once we switch our CI to using that, and make sure all tests will be green), or if we move to slimmer distro, such as alpine.
[0]: https://github.com/kata-containers/tests/blob/0a39dd1a01dc135e76f874b9475a33c5f54afcca/.ci/install_kata_image.sh#L44
Fixes: #6303

versions: Use ubuntu as the default distro for the rootfs-image

---

utils/kata-manager.sh

Every dependency in check_deps is used inside the script (apart from git, which may be a historical artifact), and therefore should be checked even when the -f option is passed to the script. Simply changed at what point check_deps is called in order to always run it.
Fixes #6302.

utils: always check some dependencies.

---

tools/packaging/static-build/shim-v2/Dockerfile

Let's bump the base container image to use the 22.04 version of Ubuntu, as it does bring up-to-date package dependencies that we need to statically build the runtime-rs on aarch64.
Fixes: #6320

shim-v2: Bump Ubuntu container image  to 22.04

---

tools/packaging/static-build/firecracker/build-static-firecracker.sh

kata-deploy: Fix kata static firecracker arm64 package build error
When building the kata static arm64 package, the stages of firecracker report errors.
Fixes: #6318

kata-deploy: Fix building the kata static firecracker arm64 package occurred an error

---

.github/workflows/kata-deploy-push.yaml

This reverts commit b835c40bbdc126e97256c0342d10aa0b09ac14e4.
Right now I'm reverting this one as this should only run *after* commits get pushed to our repo, not on very PR.

Revert "workflows: Push the builder image to quay.io"

---

src/dragonball/src/config_manager.rs

DeviceConfigInfo contains config and device, so when we want to do update we could simply update config part of the info, and device would not be changed during update.
Fixes: #6324

dragonball: config_manager: preserve device when update

---

tools/packaging/static-build/shim-v2/Dockerfile
tools/packaging/static-build/shim-v2/install_go_rust.sh

---
Revert "kata-deploy: Fix kata static firecracker arm64 package build error"
This reverts commit 697ec8e578f32c238adf7c14262f6bf1437eadd7.
Golang binaries are built statically by default, unless linking against
CGO, which we do.  In this case we dynamically link against glibc,
causing us troubles when running a binary built with Ubuntu 22.04 on
Ubuntu 20.04 (which will still be supported for the next few years ...)
---
kata-deploy: Fix kata static shim-v2 arm64 package build error
When building the kata static arm64 package, the stages of shim-v2 report errors.
Fixes: #6320
Signed-off-by: SinghWang <wangxin_0611@126.com>
---

kata-deploy: Ensure go binaries can run on Ubuntu 20.04

---

docs/Developer-Guide.md

New developers are often confused by some of our requirements, notably porting labels. While our CONTRIBUTING.md file points to the solution, the developer's guide does not. Add a link there.
Fixes: #6329

devguide: Add link to the contribution guidelines

---

tools/osbuilder/Makefile

The .dracut_rootfs.done file is accidentally being picked up as the default target, regardless of BUILD_METHOD. Move the 'all' target definition up, so that it's the default (=first) target in the makefile. Additionally make the .dracut_rootfs.done target conditional on the right BUILD_METHOD being selected, as building it doesn't make sense with BUILD_METHOD=distro.
Fixes: #6235
Signed-off-by: Jeremi Piotrowski <jpiotrowski@microsoft.com>

osbuilder: fix default build target in makefile

---

src/runtime-rs/crates/resource/src/manager.rs
src/runtime-rs/crates/resource/src/manager_inner.rs
src/runtime-rs/crates/resource/src/share_fs/mod.rs
src/runtime-rs/crates/resource/src/share_fs/utils.rs
src/runtime-rs/crates/resource/src/share_fs/virtio_fs_share_mount.rs
src/runtime-rs/crates/runtimes/common/src/sandbox.rs
src/runtime-rs/crates/runtimes/src/manager.rs
src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs

cleanup the /run/kata-containers/shared/sandboxes/pid path
Fixes:#5975

runtime-rs: cleanup kata host share path

---

src/runtime/Makefile

Currently the symbolic link for virtiofsd which is used as a valid path is not updated on every CI run. Fix it by using the actual path of installation.
Fixes: #6311

virtiofsd: update to a valid path on ppc64le

---

src/libs/kata-types/src/config/default.rs
src/runtime-rs/Cargo.lock
src/runtime-rs/crates/hypervisor/ch-config/Cargo.toml
src/runtime-rs/crates/hypervisor/ch-config/src/ch_api.rs
src/runtime-rs/crates/hypervisor/ch-config/src/convert.rs
src/runtime-rs/crates/hypervisor/ch-config/src/lib.rs
src/runtime-rs/crates/hypervisor/src/ch/inner_device.rs
src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs

Replace `cloud_hypervisor_vm_create_cfg()` with a set of `TryFrom` trait implementations in the new CH specific `convert.rs` to allow the generic `Hypervisor` configuration to be converted into the CH specific `VmConfig` type.
Note that device configuration is not currently handled in `convert.rs` (it's handled in `inner_device.rs`).
This change removes the old hard-coded CH specific configuration.
Fixes: #6203.

runtime-rs: Improve Cloud Hypervisor config handling

---

src/tools/kata-ctl/Cargo.lock
src/tools/kata-ctl/Cargo.toml
src/tools/kata-ctl/src/args.rs
src/tools/kata-ctl/src/check.rs
src/tools/kata-ctl/src/main.rs
src/tools/kata-ctl/src/ops.rs
src/tools/kata-ctl/src/ops/check_ops.rs
src/tools/kata-ctl/src/ops/exec_ops.rs

The patchset will help users to easily enter guest VM by debug console sock.
In order to enter guest VM smoothly, users needs to do some
configuration, options as below:
(1) Set `debug_console_enabled = true` with default vport 1026.
(2) Or add `agent.debug_console agent.debug_console_vport=<PORT>`
into `kernel_params`. But the enter VM port is <PORT>.
The detail of usage:
$ kata-ctl exec -h
kata-ctl-exec
Enter into guest VM by debug console
USAGE:
kata-ctl exec [OPTIONS] <SANDBOX_ID>
ARGS:
<SANDBOX_ID>    pod sandbox ID
Fixes: #5340

kata-ctl/exec: add new command exec to enter guest VM.

---

tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in
tools/osbuilder/rootfs-builder/ubuntu/rootfs_lib.sh

When starting an initrd the kernel expects to find /dev/console in the initrd, so that it can connect it as stdin/stdout/stderr to the /init process. If the device node is missing the kernel will complain that it was unable to open an initial console. If kata-agent is the initrd init process, it will also result in log messages not being logged to console and thus not forwarded to host syslog.
Add a set of standard device nodes for completeness, so that console logging works.
Fixes: #6261
Signed-off-by: Jeremi Piotrowski <jpiotrowski@microsoft.com>

osbuilder: Include minimal set of device nodes in ubuntu initrd

---

src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/CpuAffinity.md
src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_cpu_affinity.go
src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
versions.yaml

v30.0. The following user visible changes have been made:
Command Line Changes for Reduced Binary Size
--------------------------------------------
The `clap` crate was replaced by the `argh` crate to create our command
line, which reduced our release binary size from 3.6MB to 3.3MB. There
were several syntax changes:
* All `--option=value` commands now are `--option value`.
* The `--disk DISK1 DISK2` command now is `--disk DISK1 --disk DISK2`.
* The  `-vvv` command now is `-v -v -v`
Basic vfio-user Server Support
------------------------------
Our `vfio-user` crate is extended to provide basic server side support
with an example of gpio vfio-user device. This crate now …

Upgrade to Cloud Hypervisor v30.0

---

src/runtime/virtcontainers/mount.go
src/runtime/virtcontainers/mount_linux_test.go
src/runtime/virtcontainers/mount_test.go

Fix path check bypassed issuse introduced by #6082, use filepath.Clean() to clean path before check
Fixes: #6082
Signed-off-by: XDTG <click1799@163.com>

runtime: use filepath.Clean() to clean the mount path

---

.github/workflows/deploy-ccv0-demo.yaml
.github/workflows/kata-deploy-push.yaml
.github/workflows/kata-deploy-test.yaml
.github/workflows/release.yaml

The latest ubuntu runners already have docker installed and trying to install it manually will cause the following issue:
```
Run curl -fsSL https://test.docker.com/ -o test-docker.sh
Warning: the "docker" command appears to already exist on this system.
If you already have Docker installed, this script can cause trouble, which is
why we're displaying this warning and provide the opportunity to cancel the
installation.
If you installed the current Docker package using this script and are using it
again to update Docker, you can safely ignore this message.
You may press Ctrl+C now to abort this script.
+ sleep 20
+ sudo -E sh -c apt-get update -qq >/dev/null
E: The repository 'https://packages.microsoft.com/ubuntu/22.04/prod jammy Release' is no longer signed.
```
Fixes: #6390

CC | workflows: Do not install docker

---

tools/packaging/kata-deploy-cc/scripts/kata-deploy.sh

/opt/confidential-containers/runtime-rs needs to be cleaned up, otherwise containerd post-uninstall script fails due to weird logic in `rmdir --ignore-fail-on-non-empty`.
Fixes: #6396

kata-deploy-cc: Cleanup runtime-rs

---

src/agent/Cargo.lock
src/agent/Cargo.toml
versions.yaml

This covers td-shim, attestation-agent and image-rs.
Fixes: #6366

CCv0: set dependencies to v0.4.0 tag

---

.github/workflows/static-checks.yaml

Use `git-diff` instead of legacy `git-whatchanged` to get differences in the packaging/kernel directory. This also fixes a bug by grepping for the kernel directory in the output of the git command.
Fixes: #6210

actions: Use `git-diff` to get changes in kernel dir

---

src/runtime-rs/crates/resource/src/cgroups/mod.rs

Fixed the typo in comment in the delete method located in mod.rs file.
Fixes: #6256.
Signed-off-by: Christopher Robinson <christopher.cadiz.robinson@gmail.com>

src: Fixed typo mod.rs

---

.github/workflows/payload-after-push-amd64.yaml
.github/workflows/payload-after-push-arm64.yaml
.github/workflows/payload-after-push-s390x.yaml
.github/workflows/payload-after-push.yaml
tools/packaging/kata-deploy/local-build/kata-deploy-build-and-upload-payload.sh

For the architectures we know that `make kata-tarball` works as expected, let's start publishing the kata-deploy payload after each merge.
This will help to:
* Easily test the content of current `main` or `stable-*` branch
* Easily bisect issues
* Start providing some sort of CI/CD content pipeline for those who need that
This is a forward-port work from the `CCv0` and groups together patches that I've worked on, with the work that Choi did in order to support different architectures.
Fixes: #6343

workflows: Publish kata-deploy payload after a merge

---

.github/workflows/kata-deploy-push.yaml
.github/workflows/kata-deploy-test.yaml
.github/workflows/release.yaml

The latest ubuntu runners already have docker installed and trying to install it manually will cause the following issue:
```
Run curl -fsSL https://test.docker.com/ -o test-docker.sh
Warning: the "docker" command appears to already exist on this system.
If you already have Docker installed, this script can cause trouble, which is
why we're displaying this warning and provide the opportunity to cancel the
installation.
If you installed the current Docker package using this script and are using it
again to update Docker, you can safely ignore this message.
You may press Ctrl+C now to abort this script.
+ sleep 20
+ sudo -E sh -c apt-get update -qq >/dev/null
E: The repository 'https://packages.microsoft.com/ubuntu/22.04/prod jammy Release' is no longer signed.
```
Fixes: #6390

workflows: Do not install docker

---

src/dragonball/Cargo.lock
src/dragonball/Cargo.toml
src/dragonball/src/device_manager/mod.rs
src/dragonball/src/vcpu/vcpu_impl.rs
src/dragonball/src/vcpu/vcpu_manager.rs
src/dragonball/src/vm/aarch64.rs
src/dragonball/src/vm/mod.rs
src/runtime-rs/Cargo.lock

Since rust-vmm and dragonball-sandbox has introduced several updates such as vPMU support for aarch64, we also need to update Dragonball dependencies to include those changes.
Update:
virtio-queue to v0.6.0
kvm-ioctls to v0.12.0
dbs-upcall to v0.2.0
dbs-virtio-devices to v0.2.0
kvm-bindings to v0.6.0
Also, several aarch64 features are updated because of dependencies
changes:
1. update vcpu hotplug API.
2. update vpmu related API.
3. adjust unit test cases for aarch64 Dragonball.
fixes: #6268

Dragonball: update dependencies

---

utils/kata-manager.sh

Removed the part in the `kata-manager.sh` script that checks if the host system only runs cgroups v2.
Fixes: #6259.
Signed-off-by: Alec Pemberton <pembek1901@gmail.com>

utils: Remove kata-manager.sh cgroups v2 check

---

docs/design/README.md
docs/design/hooks-handling.md
src/agent/rustjail/src/container.rs
src/agent/rustjail/src/lib.rs
src/dragonball/src/api/v1/instance_info.rs
src/libs/oci/src/lib.rs
src/libs/protocols/protos/oci.proto
src/libs/protocols/src/trans.rs
src/runtime-rs/Cargo.lock
src/runtime-rs/crates/agent/src/types.rs
src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
src/runtime-rs/crates/hypervisor/src/ch/mod.rs
src/runtime-rs/crates/hypervisor/src/dragonball/inner_hypervisor.rs
src/runtime-rs/crates/hypervisor/src/dragonball/mod.rs
src/runtime-rs/crates/hypervisor/src/dragonball/vmm_instance.rs
src/runtime-rs/crates/hypervisor/src/lib.rs
src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
src/runtime-rs/crates/hypervisor/src/qemu/mod.rs
src/runtime-rs/crates/resource/src/network/mod.rs
src/runtime-rs/crates/resource/src/network/utils/netns.rs
src/runtime-rs/crates/runtimes/Cargo.toml
src/runtime-rs/crates/runtimes/common/Cargo.toml
src/runtime-rs/crates/runtimes/common/src/sandbox.rs
src/runtime-rs/crates/runtimes/src/manager.rs
src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs
src/runtime-rs/crates/runtimes/virt_container/src/container_manager/manager.rs
src/runtime-rs/crates/runtimes/virt_container/src/lib.rs
src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs

In this pr, we are going to support OCI Hooks in runtime-rs. Besides `prestart` / `poststart` / `poststop` / `create_runtime hooks`, which are supported in runtime-go, we also support `create_container` / `start_container` hooks in this pr.
Description of  OCI hooks in OCI spec: https://github.com/opencontainers/runtime-spec/blob/main/runtime.md#lifecycle
Fixes: #5787
Signed-off-by: Yushuo <y-shuo@linux.alibaba.com>

runtime-rs: add oci hook support

---

src/runtime-rs/crates/runtimes/common/src/types/mod.rs
src/runtime-rs/crates/runtimes/common/src/types/trans_into_shim.rs
src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container_inner.rs
src/runtime-rs/crates/runtimes/virt_container/src/container_manager/process.rs

Set process status to exited at end of io wait, which indicate process
exited only, but stop process has not been finished. Otherwise, the
cleanup_container will be skipped.

fix(runtime-rs): add exited state to ensure cleanup

---

src/runtime/pkg/containerd-shim-v2/shim_management.go

fix wrong notes for func GetSandboxesStoragePathRust()

fix wrong notes for func GetSandboxesStoragePathRust()

---

src/runtime/Makefile

```
$ make install
make: *** No rule to make target 'containerd-shim-kata-v2', needed by 'install-containerd-shim-v2'.  Stop.
```
Spotted when building kata-runtime with a different name for SHIMV2_OUTPUT. For instance, trying to keep different runtime binaries installed at the same time, one from master and another from lets say, the CCv0 branch, with the following small change applied.
```
diff --git a/src/runtime/Makefile b/src/runtime/Makefile index 95efaff78..2bab9eb75 100644
--- a/src/runtime/Makefile
+++ b/src/runtime/Makefile
@@ -231,7 +231,7 @@ SED = sed
CLI_DIR = cmd
SHIMV2 = containerd-shim-kata-v2
-SHIMV2_OUTPUT = $(bCURDIR)/$(SHIMV2)
+SHIMV2_OUTPUT = $(CURDIR)/$(SHIMV2)-ccv0
SHIMV2_DIR = $(CLI_DIR)/$(SHIMV2)
MONITOR = kata-monitor
```

runtime/Makefile: Fix install-containerd-shim-v2 dependency

---

src/agent/rustjail/src/cgroups/fs/mod.rs
src/agent/rustjail/src/cgroups/mock.rs
src/agent/rustjail/src/cgroups/mod.rs
src/agent/rustjail/src/cgroups/systemd/manager.rs
src/agent/rustjail/src/container.rs
src/agent/src/main.rs
src/agent/src/rpc.rs

Rustjail panics when host uses systemd cgroups but guest does not have systemd. To fix this tell rustjail whether kata-agent is running as init process or not. If we are running as init process, then we use cgroupfs as the cgroup manager, regardless of what the host uses.
This should allow all guest/host combinations to work:
host cgroup | agent_init | guest cgroup
-|-|-
systemd | yes | cgroupfs
cgroupfs | yes | cgroupfs
systemd | no | systemd
cgroupfs | no | cgroupfs
Fixes: #5779

rustjail: fix cgroup handling in agent-init mode

---

tools/packaging/kata-deploy/Dockerfile
tools/packaging/kata-deploy/local-build/kata-deploy-build-and-upload-payload.sh

---
kata-deploy: Allow passing IMG_NAME and IMG_TAG
Let's break the IMAGE build parameter into IMG_NAME and IMG_TAG, as it
makes it easier to replace the default CentOS image by something else.
Spoiler alert, the default CentOS image is **not** multi-arch, and we do
want to support at least aarch64 and s390x in the near term future.
---
kata-deploy: Use different images for s390x and aarch64
As the image provided as part of registry.centos.org is not a multi-arch
one, at least not for CentOS 7, we need to expand the script used to
build the image to pass images that are known to work for s390x (ClefOS)
and aarch64 (CentOS, but coming from dockerhub).
---
kata-deploy: …

workflows: Yet more fixes for publishing the kata-deploy payload after every PR merged

---

.github/workflows/payload-after-push-amd64.yaml
.github/workflows/payload-after-push-arm64.yaml
tools/packaging/kata-deploy/Dockerfile
tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml
tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
tools/packaging/kata-deploy/local-build/kata-deploy-build-and-upload-payload.sh

kata-deploy: Fix kata deploy image build error
When building the kata deploy arm64 image, using default base image report errors.
Fixes: #6358

main | kata-deploy: Fix kata deploy arm64 image build error

---

src/agent/rustjail/src/cgroups/fs/mod.rs
src/agent/rustjail/src/cgroups/mock.rs
src/agent/rustjail/src/cgroups/mod.rs
src/agent/rustjail/src/cgroups/systemd/manager.rs
src/agent/rustjail/src/container.rs
src/agent/src/main.rs
src/agent/src/rpc.rs

This is a backport of #6331 to kata-3.1.
cc @fidencio

backport rustjail systemd cgroup fix #6331 to 3.1

---

src/dragonball/src/error.rs
src/dragonball/src/vcpu/aarch64.rs
src/dragonball/src/vcpu/mod.rs
src/dragonball/src/vcpu/vcpu_impl.rs
src/dragonball/src/vcpu/vcpu_manager.rs
src/dragonball/src/vm/aarch64.rs
src/dragonball/src/vm/mod.rs

This commit adds support for pmu virtualization on aarch64. The initialization of pmu is in the following order:
1. Receive pmu parameter(vpmu_feature) from runtime-rs to determine the VpmuFeatureLevel.
2. Judge whether to initialize pmu devices and add pmu device node into fdt on aarch64, according to VpmuFeatureLevel.
Fixes: #6168

dragonball: support pmu on aarch64

---

utils/kata-manager.sh

Updated the `kata-manager.sh` script to make it run all the checks on the host system before attempting to create a container. If any checks fail, they will indicate to the user what the problem is in a clearer manner than those reported by the container manager.
Fixes: #6281.

utils: Make kata-manager.sh runs checks

---

tools/packaging/guest-image/build_image.sh
tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
tools/packaging/scripts/lib.sh
tools/packaging/static-build/kernel/build.sh
tools/packaging/static-build/ovmf/build.sh
tools/packaging/static-build/qemu/build-base-qemu.sh
tools/packaging/static-build/shim-v2/build.sh
tools/packaging/static-build/td-shim/build.sh
tools/packaging/static-build/virtiofsd/build.sh

---
packaging: Move repo_root_dir to lib.sh
This is used in several parts of the code, and can have a single
declaration as part of the `lib.sh` file, which is already imported by
all the places where it's used.
---
packaging: Simplify get_last_modification()
There's no need to pass repo_root_dir to get_last_modification() as the
variable used everywhere is exported from that very same file.
Fixes: #6431
---

packaging: Simplify get_last_modification()

---

tools/packaging/kata-deploy/local-build/Makefile
tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh

Remove duplicate SEV kernel builds.
Fixes: #6415
Create a directory where kernel modules tarball will be extracted.
Fixes: #6418

packaging: fix sev kernel build

---

src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
src/runtime-rs/crates/hypervisor/src/ch/mod.rs
src/runtime-rs/crates/hypervisor/src/dragonball/inner_hypervisor.rs
src/runtime-rs/crates/hypervisor/src/dragonball/mod.rs
src/runtime-rs/crates/hypervisor/src/dragonball/vmm_instance.rs
src/runtime-rs/crates/hypervisor/src/lib.rs
src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
src/runtime-rs/crates/hypervisor/src/qemu/mod.rs
src/runtime-rs/crates/runtimes/virt_container/src/container_manager/manager.rs

For external hypervisors(qemu, cloud-hypervisor, ...), the ns they launch vm in is different from internal hypervisor(dragonball). And when we doing CreateContainer hook, we will rely on the netns path. So we add a get_ns_path API.
Fixes: #6442
/cc @jodh-intel @pmores @amshinde

bugfix: add get_ns_path API for Hypervisor

---

src/libs/shim-interface/src/shim_mgmt/client.rs
src/runtime-rs/Cargo.lock
src/runtime-rs/crates/agent/src/kata/agent.rs
src/runtime-rs/crates/agent/src/kata/trans.rs
src/runtime-rs/crates/agent/src/lib.rs
src/runtime-rs/crates/agent/src/types.rs
src/runtime-rs/crates/runtimes/Cargo.toml
src/runtime-rs/crates/runtimes/common/src/sandbox.rs
src/runtime-rs/crates/runtimes/src/shim_mgmt/handlers.rs
src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs

This change adds handlers for the requests made by the `direct-volume` subcommand from kata-ctl in runtime-rs/crates/runtimes. This includes `direct-volume stats` and `direct-volume resize`. Corresponding traits & types are defined in runtimes-rs/crates/agent.
Note that the actual agent-side RPC handler for the resize request is currently not
implemented, please refer to issue #3694.
Fixes #5369 
Signed-off-by: Tingzhou Yuan <tzyuan15@bu.edu>

Implement direct-volume commands handler for shim-mgmt

---

src/runtime-rs/Makefile

---
build: Use the correct kernel name
When calling `MAKE_KERNEL_NAME` we're considering the default kernel
name will be `vmlinux.container` or `vmlinuz.container`, which is not
the case as the runtime-rs, when used with dragonball, relies on the
`vmlinu[zx]-dragonball-experimental.container` kernel.
Other hypervisors will have to introduce a similar
`MAKE_KERNEL_NAME_${HYPERVISOR}` to adapt this to the kernel they want
to use, similarly to what's already done for the go runtime.
By doing this we also ensure that no changes in the configuration file
will be required to run runtime-rs, with dragonball, as part of our CI
or as part of kata-deploy.
Fixes: #6290
---
kata-types/config: Add more default config paths
This is not ideal, but this is what it is right now, as the
configurations end …

runtime-rs: fix default kernel location and add more default config paths

---

tools/packaging/kata-deploy-cc/Dockerfile
tools/packaging/kata-deploy/local-build/kata-deploy-build-and-upload-payload.sh

kata-deploy-cc: Switch to using Ubuntu image
This will help us in several ways:
* The first one is not using an image that's close to be EOLed, and
which doesn't officially provide multi-arch images.
* The second is getting closer to what's been already done on main.
* The third is simplifying the logic to build the payload image.
Fixes: #6446

kata-deploy-cc: Switch to using an ubuntu image

---

src/runtime-rs/crates/runtimes/src/manager.rs

Since shimv2 create task option is already implemented, we need to update the corresponding comments.
Also, the ordering is also updated to fit with the code.
fixes: #3961

runtime-rs: update load_config comment

---

src/runtime/pkg/resourcecontrol/cgroups.go

This adds `/dev/mshv` to the list of sandbox devices so that VMMs can create Hyper-V VMs.
In our testing, this also doesn't error out in case `/dev/mshv` isn't present.
Fixes #6454.

runtime: add support for Hyper-V

---

tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
tools/packaging/static-build/cache_components.sh

We need to ensure `kata_config_version` is taken into account when:
* consuming a cached kernel, otherwise we may introduce changes to a kernel that will never be validated as part of the PR
* caching the kernel, otherwise we won't update the artefacts if just a config is changed
Fixes: #6485

CC | kernel: Ensure `kata_config_version` is taken into account

---

src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs

Setting hostname according to the spec.
The wrong username is because special systemd process is used as init process.
Fixes: #6247

bugfix: set hostname in CreateSandboxRequest

---

.github/workflows/kata-deploy-push.yaml
tools/packaging/kata-deploy/local-build/kata-deploy-merge-builds.sh

Remove some tools from runner and some temp files during build so that we (hopefully) don't run out of disk space so often.

CC | kata-deploy-push more space
