kata-containers/kata-containers

- src/agent/Cargo.lock
- src/agent/Cargo.toml
- src/agent/src/ap.rs
- src/agent/src/device.rs
- src/agent/src/linux_abi.rs
- src/agent/src/main.rs
- src/runtime/pkg/device/config/config.go
- src/runtime/pkg/device/drivers/utils.go
- src/runtime/pkg/device/drivers/vfio.go
- src/runtime/pkg/device/drivers/vfio_test.go
- src/runtime/virtcontainers/clh.go
- src/runtime/virtcontainers/clh_test.go
- src/runtime/virtcontainers/kata_agent.go
- src/runtime/virtcontainers/qemu.go
- src/runtime/virtcontainers/qemu_arch_base.go
- src/runtime/virtcontainers/qemu_arch_base_test.go
- src/runtime/virtcontainers/sandbox.go
- src/runtime/virtcontainers/utils/utils_linux.go
- src/runtime/virtcontainers/utils/utils_linux_test.go
This PR is a continuing work for (#3679).
This generalizes the previous VFIO device handling which only
focuses on PCI to include AP (Adjunct Processor, IBM Z specific).
Fixes: #3678
> agent: Bring in VFIO-AP device handling again 

- .github/workflows/static-checks.yaml
- tools/osbuilder/tests/test_images.sh
- remove all TRAVIS_XXX variables (except TRAVIS because it is still used in kata-containers/tests)
- free some disk space to prevent the sudo test job from running out of space (affects mostly CCv0 branch)
- simplify setting GOPATH
Since these apply to main, I'm submitting against main but would be nice to have them flow into CCv0 soon.
> static checks workflow improvements

- src/runtime/pkg/katautils/config.go
- src/runtime/pkg/katautils/config_test.go
For now, image nvdimm on qemu/arm64 depends on UEFI/ACPI, so if there
is no firmware offered, it should be disabled.
> qemu/arm64: disable image nvdimm once no firmware offered

- utils/kata-manager.sh
barebones fix for #6385, simply passes through only_kata to pre_check and adds an additional conditional before aborting the install due to pre-existing containerd.
However, should we be aborting on pre-existing containerd, or should only_kata be set based on whether containerd is already installed? (so that containerd install would be skipped if it was detected to already be installed.)
> make only_kata work without -f

- tools/osbuilder/rootfs-builder/ubuntu/config.sh
- tools/osbuilder/rootfs-builder/ubuntu/rootfs_lib.sh
DCAP has upgraded to 1.16, which is not compatible with the host OS used as part of our CI (2022ww44).  Let's ensure DCAP 1.15 is used instead.
Fixes: #6529
> rootfs: Ensure we use a compatible version of dcap with rats-tls

- snap/snapcraft.yaml
Our CI and release process are currently taking advantage of the
kata-deploy local build scripts to build the artefacts.
Having snap doing the same is the next logical step, and it will also
help to reduce, by a lot, the CI time as we only build the components
that a PR is touching (otherwise we just pull the cached component).
Fixes: #6514
> snap: Build the artefacts using kata-deploy

- tools/packaging/kata-deploy-cc/scripts/kata-deploy.sh
This is to add a new element `qemu-se` to the shims for a new runtime class `kata-qemu-se`.
Fixes: #6549
> CC|kata-deploy: Add kata-qemu-se runtimeclass

- src/runtime/virtcontainers/container.go
- src/runtime/virtcontainers/fs_share.go
- src/runtime/virtcontainers/fs_share_darwin.go
- src/runtime/virtcontainers/fs_share_linux.go
- src/runtime/virtcontainers/kata_agent.go
- src/runtime/virtcontainers/sandbox.go
For remote hypervisor, the configmap, secrets, downward-api or project-volumes are copied from host to guest. This patch watches for changes to the host files and copies the changes to the guest.
Note that configmap updates takes significantly longer than updates via downward-api. This is similar across runc and Kata runtimes.
Fixes: #6341
> runtime: propagate configmap, secrets, downward-api etc changes for remote-hyp

- .github/workflows/cc-payload-after-push-amd64.yaml
- tools/packaging/kata-deploy/local-build/Makefile
- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
- tools/packaging/static-build/ovmf/build-ovmf.sh
SNP needs two builds of ovmf: the AmdSev build and the normal x86_64 build.
Adds target for vanilla ovmf build for snp
Adding another make target / kata-deploy function, and fixing the ovmf builder so these builds dont overlap.
Fixes: kata-containers#5849
> CC: kata-deploy add x86 ovmf build for SNP

- docs/design/architecture/networking.md
This PR updates the url for the Container Network Model in the network document.
Fixes #6563
> docs: Update CNM url in networking document

- src/runtime/cmd/kata-monitor/README.md
- src/runtime/pkg/kata-monitor/metrics.go
- src/runtime/pkg/kata-monitor/shim_client.go
The kata monitor metrics API returns a huge size response, if containers or sandboxs are a large number,
focus on what we need will be harder.
#6500
> runtime: add filter metrics with specific names

- src/agent/rustjail/src/cgroups/systemd/dbus_client.rs
- src/agent/rustjail/src/cgroups/systemd/manager.rs
There can be an error while connecting to the cgroups managager, for
example a `ENOENT` if a file is not found. Make sure that this is
reported through the proper channels instead of causing a `panic()`
that does not provide much information.
Fixes: #6561 
Reported-by: Greg Kurz <gkurz@redhat.com>
While I'm at it, rename `unit_exist` to `unit_exits` to match English grammar.
> rustjail: Fix panic when cgroup manager fails

- .github/workflows/create-aks.yaml
It's been pointed out that D4s_v5 instances are more powerful than the D4s_v3 ones, and have the very same price.  With this in mind, let's switch to the newer machines.
Fixes: #6606
> gha: aks: Use D4s_v5 instance

- .github/workflows/build-kata-static-tarball-amd64.yaml
- .github/workflows/build-kata-static-tarball-arm64.yaml
- .github/workflows/build-kata-static-tarball-s390x.yaml
- .github/workflows/ci-on-push.yaml
- .github/workflows/payload-after-push.yaml
- .github/workflows/publish-kata-deploy-payload-amd64.yaml
- .github/workflows/publish-kata-deploy-payload-arm64.yaml
- .github/workflows/publish-kata-deploy-payload-s390x.yaml
- .github/workflows/run-k8s-tests-on-aks.yaml
- tools/packaging/kata-deploy/local-build/kata-deploy-build-and-upload-payload.sh
56331bd7bcfbc6aabd8a732a10c544ba3df84622 oversaw the fact that we mistakenly tried to push the build containers to the registry for a PR, rather than doing so only when the code is merged.
As the workflow is now shared between different actions, let's introduce an input variable to specify which are the cases we actually need to perform a push to the registry.
Fixes: #6592
> gha: Only push images to registry after merging a PR

- .github/workflows/run-k8s-tests-on-aks.yaml
- tests/integration/kubernetes/run_kubernetes_tests.sh
As already done for Cloud Hypervisor and QEMU, let's make sure we can run the AKS tests using dragonball.
Fixes: #6583
> gha: Also run k8s tests on AKS with dragonball

- .github/workflows/cc-payload-after-push-s390x.yaml
This is to add an artifact named `cc-rootfs-initrd` to a payload image because it is identified that the artifact is required to run a cc-operator e2e test.
Fixes: #6544
> CC: Add cc-rootfs-initrd to payload image for s390x

- .github/workflows/run-k8s-tests-on-aks.yaml
This was missed from the last series, as GHA will use the "target branch" yaml file to start the workflow.
Basically we changed the name of the cluster created to stop relying on the PR number, as that's not easily accessible on `workflow_run`.
Fixes: #6611
> gha: k8s-on-aks: Fix cluster name

- src/agent/Cargo.lock
- src/agent/Cargo.toml
- src/agent/src/image_rpc.rs
- tools/osbuilder/rootfs-builder/rootfs.sh
- versions.yaml
Using ttrpc instead grpc feature of image-rs for kata-agent
Close https://github.com/kata-containers/kata-containers/issues/6219
cc @arronwy @jiangliu
> agent: add support for ttrpc

- .github/workflows/cc-payload-after-push-amd64.yaml
- .github/workflows/cc-payload-amd64.yaml
Last SNP component needed in the x86 payload is Qemu. I missed adding an entry in #6062.
Fixes: #6600
> CC | gha: add SNP components to amdx86_64 payload workflows

- .github/workflows/build-kata-static-tarball-amd64.yaml
- .github/workflows/build-kata-static-tarball-arm64.yaml
- .github/workflows/build-kata-static-tarball-s390x.yaml
- .github/workflows/ci-on-push.yaml
- .github/workflows/publish-kata-deploy-payload-amd64.yaml
- .github/workflows/publish-kata-deploy-payload-arm64.yaml
- .github/workflows/publish-kata-deploy-payload-s390x.yaml
- .github/workflows/run-k8s-tests-on-aks.yaml
We've been currently using {create,delete}_aks as jobs.  However, it means that if the tests fail we'll end up deleting the AKS cluster (as expected), but not having a way to recreate the cluster without re-running all jobs, which is a waste of resources.
Fixes: #6628
> gha: k8s-on-aks: Set {create,delete}_aks as steps

- docs/how-to/how-to-run-rootless-vmm.md
- src/runtime/config/configuration-clh.toml.in
- src/runtime/pkg/katautils/config.go
- src/runtime/virtcontainers/clh.go
- src/runtime/virtcontainers/qemu.go
This change enables to run cloud-hypervisor VMM using a non-root user when rootless flag is set true in the configuration
Fixes: #2567
Signed-off-by: Feng Wang <fwang@confluent.io>
I tested this change locally and verified that cloud-hypervisor processes are running using a nonroot user.
```
[root@ip-10-10-1-227 bin]# ps aux | grep cloud-hypervisor
kata-15+ 73449 14.1  1.1 10648792 2331536 ?    Sl   18:09   1:59 /opt/kata/bin/cloud-hypervisor --api-socket /run/user/1127/run/vc/vm/81ca7e3197d266259589e60aeb57f6aff98647d221ee13ad9796a5808ad58e21/clh-api.sock -v
kata-50+ 73627 14.2  1.2 10648792 2483084 ?    Sl   18:09   2:00 /opt/kata/bin/cloud-hypervisor --api-socket /run/user/1128/run/vc/vm/aa0f117bfe03336e34b60c30e66ef17d07c3dfa407bccb2a39e74d3e20ddc703/clh-api.sock -v
kata-24+ 88123 …
```
> runtime: support non-root for clh

- src/runtime-rs/crates/hypervisor/src/dragonball/inner_device.rs
Add support for virtiofsd when virtio_fs_extra_args with "-o cache auto, ..." users specified.
Fixes: #6615
> runtime-rs/virtio-fs: add support extra handler for cache mode.

- src/runtime/config/configuration-remote.toml.in
This PR updates the template configuration file for the remote hypervisor to set `static_sandbox_resource_mgmt` to be true.  The remote hypervisor uses the peer pod config to determine the sandbox size, so requires this to be set to true by default.
This change fixes the issue reported at https://github.com/confidential-containers/cloud-api-adaptor/issues/745
Fixes: #6616
> CCv0: runtime: Use static_sandbox_resource_mgmt by default in remote hypervisor

- src/agent/rustjail/src/cgroups/systemd/dbus_client.rs
- src/agent/rustjail/src/cgroups/systemd/manager.rs
- src/agent/rustjail/src/cgroups/systemd/subsystem/cpu.rs
Backport #6562 and #6637. This is needed to use cgroups v2 with systemd in the guest.
> Backport cgroup fixes to 3.1

- src/libs/kata-types/src/annotations/mod.rs
- src/libs/kata-types/src/config/hypervisor/mod.rs
- src/runtime-rs/crates/resource/src/rootfs/nydus_rootfs.rs
nydus_rootfs/prefetch_files: add prefetch_files for RAFS
A sandbox annotation used to specify prefetch_files.list path the container image being used, and runtime will pass
it to Hypervisor to search for corresponding prefetch file. format looks like:
"io.katacontainers.config.hypervisor.prefetch_files.list" = /path/to/<uid>/xyz.com/fedora:36/prefetch_file.list
Fixes: #6582
> nydus_rootfs/prefetch_files: add prefetch_files for RAFS

- tools/osbuilder/dracut/dracut.conf.d/05-base.conf
- tools/osbuilder/rootfs-builder/rootfs.sh
The agent now offloads cgroup configuration to systemd when possible. This requires to enable D-Bus in order to communicate with systemd.
Fixes #6657
> osbuilder: Enable dbus in the dracut case

- src/agent/Cargo.lock
- src/agent/Cargo.toml
- versions.yaml
Updated the following dependencies:
* td-shim to commit [10568bab569bc40034cc973f26fbb0a768dcc3e3](https://github.com/confidential-containers/td-shim/commit/10568bab569bc40034cc973f26fbb0a768dcc3e3)
* attestation-agent to commit [c939d211fe5ac497715008e36161aff20cabb6e6](https://github.com/confidential-containers/attestation-agent/commit/c939d211fe5ac497715008e36161aff20cabb6e6)
* image-rs to commit [b28eaae46bcea69ac28d079381b7aa1ef6851ad9](https://github.com/confidential-containers/image-rs/commit/b28eaae46bcea69ac28d079381b7aa1ef6851ad9)
> CCv0: update dependencies for CoCo release 0.5.0

- tools/osbuilder/dracut/dracut.conf.d/05-base.conf
- tools/osbuilder/rootfs-builder/rootfs.sh
The agent now offloads cgroup configuration to systemd when possible. This requires to enable D-Bus in order to communicate with systemd.
Fixes #6657
(cherry picked from commit eb1762e813c52d5b593bacb04932d6fbf0ca3a19)
> osbuilder: Enable dbus in the dracut case (backport for 3.1)

- src/agent/Cargo.lock
- src/agent/Cargo.toml
- versions.yaml
image-rs, attestation-agent, and td-shim were bumped to v0.5.0 release.
> Update deps for the v0.5.0 release of Confidential Containers

- versions.yaml
Details of this release can be found in our new roadmap project as iteration v31.0: https://github.com/orgs/cloud-hypervisor/projects/6.
v31.0. The following user visible changes have been made:
Adapted to the latest [acpi_tables](https://github.com/rust-vmm/acpi_tables). There has been significant API changes in
the crate.
Updated the recommended guest kernel version from 6.1.6 to 6.2.
A separate thread had been created to capture the `SIGWINCH` signal and resize
the guest console. Now the thread is skipped if the console is not resizable.
Two completely different code paths existed for handling console resizing, one
for `tty` and the other for `pty`. That makes the …
> versions: Upgrade to Cloud Hypervisor v31.0

- .github/workflows/run-k8s-tests-on-tdx.yaml
- src/runtime-rs/config/configuration-dragonball.toml.in
- src/runtime/config/configuration-acrn.toml.in
- src/runtime/config/configuration-clh.toml.in
- src/runtime/config/configuration-fc.toml.in
- src/runtime/config/configuration-qemu-tdx.toml.in
- src/runtime/config/configuration-qemu.toml.in
- src/runtime/virtcontainers/clh.go
- tests/integration/kubernetes/k8s-cpu-ns.bats
- tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml
- tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
- tools/packaging/kata-deploy/runtimeclasses/kata-runtimeClasses.yaml
- tools/packaging/kata-deploy/scripts/kata-deploy.sh
We must ensure that no kata-deploy is left behind after the tests
finish, otherwise it may interfere with the next run.
Fixes: #6647
> gha: tdx: Ensure kata-deploy is removed after the tests run

- .github/workflows/run-k8s-tests-on-tdx.yaml
- tools/packaging/static-build/cache_components_main.sh
---
cached-components: Fix TDX QEMU caching
TDX QEMU caching is not working as expected, as we're checking for its
version looking at "assets.hypervisor.${QEMU_FLAVOUR}.version", which is
correct for standard QEMU. However, for TDX QEMU we should be checking
for "assets.hypervisor.${QEMU_FLAVOUR}.tag"
---
cache-components: Fix TDVF caching
TDVF caching is not working as the tarball name is incorrect. The result
expected is kata-static-tdvf.tar.xz, but it's looking for
kata-static-tdx.tar.xz.
This happens as a logic to convert tdx -> tdvf has been added as part of
the building scripts, but I missed doing this as part of the caching
scripts.
---
> cache-components: Fix caching of TDVF and QEMU for TDX

- src/agent/src/main.rs
Never ever try to close the same fd double times, even in a unit test.
A file descriptor is a number which will be reused, so when you close the same number twice you may close another file descriptor in the second time and then there will be an error 'Bad file descriptor (os error 9)' while the wrongly closed fd is being used.
Fixes: #6679
> agent: Fix ut issue caused by fd double closed

- utils/kata-manager.sh
Newer containerd releases have an additional static package published. Because of this,  download_url contains two urls causing curl to fail. To resolve this, pick the first url from the containerd releases to download containerd.
Fixes: #6695
> kata-manager: Fix containerd download

- snap/snapcraft.yaml
In Arm baseline CI, docker starts fail with error: "no sockets found via socket activation: make sure the service was started by systemd". I find a solusion in [1] to fix it.
[1] https://forums.docker.com/t/failed-to-load-listeners-no-sockets-found-via-socket-activation-make-sure-the-service-was-started-by-systemd/62505
Fixes: #6619
> snap: fix docker start fail issue

- src/tools/kata-ctl/src/arch/aarch64/mod.rs
- src/tools/kata-ctl/src/arch/s390x/mod.rs
- src/tools/kata-ctl/src/arch/x86_64/mod.rs
- src/tools/kata-ctl/src/check.rs
- src/tools/kata-ctl/src/ops/check_ops.rs
- src/tools/kata-ctl/src/types.rs
Ensure that kvm and kvm_intel modules are loaded
Fixes #5332
> kata-ctl: checks for kvm, kvm_intel modules loaded

- tools/osbuilder/rootfs-builder/rootfs.sh
- D-Bus enabling now occurs only in `setup_rootfs` (instead of `prepare_overlay` and `setup_rootfs`)
- Adjust permissions of `/` so `dbus-broker` will be able to traverse FS
These changes enables `kata-agent` to successfully communicate with D-Bus.
Fixes #6677
(cherry picked from commit 3e7b902265c6f5d1c4eece2ea778eb2cc3d6faa5)
> osbuilder: Fix D-Bus enabling in the dracut case (backport for 3.1)

- src/agent/rustjail/src/cgroups/systemd/subsystem/cpu.rs
The CPU shares property belongs to CgroupsV1. CgroupsV2 uses CPU weight instead. The correct value is computed in the latter case but it is passed to systemd using the legacy property. Systemd rejects the request and the agent exists with the following error :
Value specified in CPUShares is out of range: unknown
Replace the "shares" wording with "weight" in the CgroupsV2 code to avoid confusions. Use the "CPUWeight" property since this is what systemd expects in this case.
Fixes #6636
References:
https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html#CPUWeight=weight https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html#systemd%20252 https://github.com/containers/crun/blob/main/crun.1.md#cpu-controller
Signed-off-by: Greg Kurz …
> rustjail: Use CPUWeight with systemd and CgroupsV2

- src/libs/kata-types/src/config/runtime.rs
- src/runtime-rs/config/configuration-dragonball.toml.in
- src/runtime-rs/crates/runtimes/src/manager.rs
- src/runtime-rs/crates/runtimes/virt_container/src/health_check.rs
- src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
This patch adds keep_abnormal in runtime config. If keep_abnormal = true, it means that 1) if the runtime exits abnormally, the cleanup process will be skipped, and 2) the runtime will not exit even if the health check fails.
This option is typically used to retain abnormal information for debugging and should NOT be enabled by default.
Fixes: #6717
> runtime-rs: support keep_abnormal in toml config

- .github/workflows/run-k8s-tests-on-sev.yaml
kubectl commands need a '-f' instead of a '-k'
Fixes: #6758
> gha: sev: fix for kata-deploy error

- src/runtime/virtcontainers/factory/factory_test.go
Expanded tests on factory_test.go to cover more lines of code. Coverage went from 34% to 41.5% in the case of user-mode run tests, and from 77.7% to 84% in the case of priviledge-mode run tests.
Fixes: #260
> virtcontainers/factory: Improved test coverage

- src/tools/kata-ctl/Cross.toml
- src/tools/kata-ctl/README.md
`cross` is an open source tool that provides zero-setup cross compile for rust binaries. Add documentation on this tool for compiling kata-ctl tool and Cross.toml file that provides required configuration for installing dependencies for various targets.
This is pretty useful for a developer to make sure code compiles and passes checks for various architectures.
Fixes: #1000
> cross-compile: Include documentation and configuration for cross-compile

- src/tools/kata-ctl/src/arch/x86_64/mod.rs
- src/tools/kata-ctl/src/check.rs
- src/tools/kata-ctl/src/ops/check_ops.rs
- src/tools/kata-ctl/src/types.rs
Add kvm check using ioctl macro to create a syscall that checks the kvmapi version and if creation of a vm is successful.
Check in a unit test that kvm test fails when run as non-root and when device specified is not /dev/kvm.
Fixes #5338
> kata-ctl: add generic kvm check & unit test

- docs/install/README.md
- docs/install/snap-installation-guide.md
The snap package is no longer being maintained so update the docs to warn readers.
We'll remove the snap installation docs in a few weeks.
See: #6769.
Fixes: #6793.
> docs: Mark snap installation method as unmaintained

- .github/workflows/build-kata-static-tarball-amd64.yaml
- tools/packaging/kata-deploy/local-build/Makefile
- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
- tools/packaging/static-build/cache_components_main.sh
We need to make sure that, when caching a `-nvidia-gpu` kernel, we still
look at the version of the base kernel used to build the nvidia-gpu
drivers, as the ${vendor}-gpu kernels are based on already existing
entries in the versions.yaml file and do not require a new entry to be
added.
Fixes: #6777
> cache: Update the KERNEL_FLAVOUR list to include nvidia-gpu

- tools/packaging/static-build/cache_components_main.sh
c9bf7808b6345c7902c46ad11204fc076fb7b894 introduced the logic to properly get the version of nvidia-gpu kernels, but one important part was dropped during the rebase into main, which is actually getting the correct version of the kernel.
Fixing this now, and using the old issue as reference.
Fixes: #6777
> cache: Fix nvidia-gpu version

- .github/workflows/snap-release.yaml
- .github/workflows/snap.yaml
Fix recurring issues of failing to install dependencies due to stale apt cache. Uprev actions/checkout to v3 to resolve issue "Node.js 12 actions are deprecated."
Fixes: #5659
> gha: Fix snap creation workflow

- .github/workflows/commit-message-check.yaml
Change the Body Line Length workflow to not trigger when the commit message contains only a message without a body. Other workflows will flag the missing body sections, and it was confusing to have an error message that said 'Body line too long (max 150)' when this was not actually the case.
Fixes: #5561
---
This basically just adds a match for a single line without a new line, OR'd with the existing logic. 
We created a few test cases to try this out here - https://regexr.com/7cq1d
> gha: Fix Body Line Length action flagging empty body commit messages

- src/agent/Makefile
- src/runtime-rs/Makefile
- src/tools/agent-ctl/Makefile
- src/tools/runk/Makefile
- src/tools/trace-forwarder/Makefile
- utils.mk
Currently, `ARCH` value is being set to `powerpc64le` by default. `powerpc64le` is only right in the context of rust and any operation which might use this variable for a different purpose might fail on `ppc64le`.
Fixes: #6741
> runtime: remove overriding ARCH value by default for ppc64le

- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
- tools/packaging/static-build/cache_components_main.sh
---
cache: Fix nvidia-gpu-tdx-experimental cache URL
We were passing "kernel-nvidia-gpu-tdx", missing the "-experimental"
part, leading to a non-valid URL.
---
cache: Fix nvidia-snp caching version
All the kernel-foo instances, such as "kernel-sev" or "kernel-snp",
should be transformed into "kernel.foo" when looking at the
versions.yaml file.
This was already done for SEV, but missed on the SNP case.
Fixes: #6777 
---
> cache: More fixes to nvidia-gpu kernels caching

- .github/workflows/cc-payload-after-push.yaml
- .github/workflows/cc-payload.yaml
- Create multi-arch manifests for the ci and release runtime-payload that are tagged with the commit, for use in the operator
Fixes: #6814
> actions:  multi-arch runtime-payload

- .github/workflows/release-amd64.yaml
- .github/workflows/release-arm64.yaml
- .github/workflows/release-s390x.yaml
- .github/workflows/release.yaml
release: Fix multi-arch publishing is not supported
When release is published, kata-deploy image and kata-static package can support multi-arch publishing.
Fixes: #6449
> main | release: Fix multi-arch publishing is not supported

- src/runtime/virtcontainers/fc_test.go
Expanded tests on fc_test.go to cover more lines of code. Coverage went from 4.6% to 18.5%.
Fixes: #266
> virtcontainers: Improved test coverage for fc.go from 4.6% to 18.5%

- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
- tools/packaging/static-build/cloud-hypervisor/build-static-clh.sh
- tools/packaging/static-build/firecracker/build-static-firecracker.sh
Let's start downloading, instead of building, the binaries for Cloud Hypervisor (aarch64) and Firecracker.
As we're here, we've also fixed the nydus package download for aarch64.
Fixes: #6770
> kata-deploy: Build improvements

- tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
Add http_proxy and https_proxy as part of the docker build arguments in order to build properly when we are behind a proxy.
Fixes #6834
> kata-deploy: Add http_proxy as part of the docker build

- src/tools/kata-ctl/Makefile
- src/tools/kata-ctl/README.md
Fixes #5403 
The Makefile was updated to use an INSTALL_PATH variable to track where the kata-ctl binary should be installed.  If the user doesn't specify anything, then it uses the default path that cargo uses.  Otherwise, it will install it in the directory that the user specified.  The README.md file was also updated to show how to use the new option.
This work was done by pair programming by the following contributors: Cesar Tamayo
Kevin Mora Jimenez
Narendra Patel
Ray Karrenbauer
Srinath Duraisamy
Fixes #5403
> kata-ctl:  Add the option to install kata-ctl to a user specified directory

- utils/kata-manager.sh
Fix the syntax and logic error that is only displayed if the user runs the script with `-o`. This option requests that "only" Kata Containers is installed and stops containerd from being installed.
Fixes: #6822.
> kata-manager: Fix '-o' syntax and logic error

- tools/packaging/kata-deploy/local-build/kata-deploy-build-and-upload-payload.sh
`uname -m` produces `x86_64`, but container image convention is to use `amd64`, so update this in the tag
Fixes: #6820
(cherry picked from commit 2856d3f23dfb7b844244e006c270fe244c80e81e)
> deploy: Fix arch in image tag

- tools/osbuilder/rootfs-builder/rootfs.sh
This PR replaces single spaces to tabs in order to fix the indentation of the rootfs script.
Fixes #6848
> osbuilder: Fix indentation in rootfs.sh

- src/runtime/Makefile
- tools/packaging/scripts/configure-hypervisor.sh
- versions.yaml
We have been using the C version of virtiofsd on ppc64le. Now that the issues with rust virtiofsd have been fixed, let's switch to it.
Fixes: #4259
> ppc64le: switch virtiofsd from C to rust version

- .github/workflows/run-k8s-tests-on-tdx.yaml
As the TDX CI runs on k3s, we must ensure the cleanup, as already done for the deploy, used the k3s overlay.
Fixes: #6857
> gha: tdx: Use the k3s overlay for kata-cleanup

- .github/workflows/run-k8s-tests-on-aks.yaml
- .github/workflows/run-k8s-tests-on-sev.yaml
- .github/workflows/run-k8s-tests-on-snp.yaml
- .github/workflows/run-k8s-tests-on-tdx.yaml
We like it or not, every now and then we'll have to deal with flaky tests, and our tests using GHA are not exempt from that fact.
With this simple commit, we're trying to improve the reliability of the tests in a few different fronts:
* Giving enough time for the script used by kata-deploy to be executed
* We've hit issues as the kata-deploy pod is considered "Ready" at the moment it starts running, not when it finishes the needed setup. We should also be looking on how to solve this on the kata-deploy side but, for now, let's ensure our tests do not break with the current kata-deploy behavior.
* Merging the "Deploy kata-deploy" and "Run tests" steps
* We've hit issues re-running tests and seeing even more failures than the ones we're trying to debug, as a step will simply be taken as …
> gha: k8s: Make the tests more reliable

- src/runtime/pkg/oci/utils.go
Set the default value of runtime's EnableVCPUsPinning to value read from .toml.
Fixes: #6836
> runtime: use enable_vcpus_pinning from toml

- src/runtime/pkg/resourcecontrol/utils_linux.go
With this fix the vCPU pinning feature chooses the correct physical cores to pin the vCPU threads on rather than always using core 0.
Fixes #6831
> resource-control: fix setting CPU affinities on Linux

- tools/packaging/kata-deploy/local-build/kata-deploy-build-and-upload-payload.sh
- Remove local introduced by bad copy-paste
Fixes: #6814
(cherry picked from commit 1a3f8fc1a23297230b4a9fe532232a753ae2701a)
> deploy: fix shell script error

- src/agent/Cargo.lock
- src/agent/Cargo.toml
- src/agent/rustjail/Cargo.toml
- src/agent/src/signal.rs
- src/agent/vsock-exporter/Cargo.toml
- src/runtime-rs/Cargo.lock
- src/runtime-rs/crates/agent/Cargo.toml
- src/runtime-rs/crates/hypervisor/Cargo.toml
- src/runtime-rs/crates/hypervisor/ch-config/Cargo.toml
- src/runtime-rs/crates/resource/Cargo.toml
- src/runtime-rs/crates/runtimes/Cargo.toml
- src/runtime-rs/crates/runtimes/common/Cargo.toml
- src/runtime-rs/crates/runtimes/linux_container/Cargo.toml
- src/runtime-rs/crates/runtimes/virt_container/Cargo.toml
- src/runtime-rs/crates/runtimes/wasm_container/Cargo.toml
- src/runtime-rs/crates/service/Cargo.toml
- src/runtime-rs/crates/shim-ctl/Cargo.toml
- src/runtime-rs/crates/shim/Cargo.toml
- src/tools/kata-ctl/Cargo.lock
- src/tools/kata-ctl/Cargo.toml
- src/tools/runk/Cargo.lock
- src/tools/runk/Cargo.toml
There are quite a few tokio-related bugs. Let's update tokio to the latest 1.28.1 to bring in the fixes.
> update tokio dependency

- src/agent/Cargo.lock
- src/agent/Cargo.toml
- src/agent/rustjail/Cargo.toml
- src/agent/src/signal.rs
- src/agent/vsock-exporter/Cargo.toml
- src/runtime-rs/Cargo.lock
- src/runtime-rs/crates/agent/Cargo.toml
- src/runtime-rs/crates/hypervisor/Cargo.toml
- src/runtime-rs/crates/resource/Cargo.toml
- src/runtime-rs/crates/runtimes/Cargo.toml
- src/runtime-rs/crates/runtimes/common/Cargo.toml
- src/runtime-rs/crates/runtimes/linux_container/Cargo.toml
- src/runtime-rs/crates/runtimes/virt_container/Cargo.toml
- src/runtime-rs/crates/runtimes/wasm_container/Cargo.toml
- src/runtime-rs/crates/service/Cargo.toml
- src/runtime-rs/crates/shim-ctl/Cargo.toml
- src/runtime-rs/crates/shim/Cargo.toml
- src/tools/runk/Cargo.lock
- src/tools/runk/Cargo.toml
There are quite a few tokio-related bugs. Let's update tokio to the latest 1.28.1 to bring in the fixes.
This is a backport of https://github.com/kata-containers/kata-containers/pull/6882
> stable-3.1 | update tokio dependency

- tools/packaging/static-build/firecracker/build-static-firecracker.sh
Fix mismatched case of `arch`
Fixes: #6895
> tools: Fix arch bug

- .github/workflows/build-kata-static-tarball-amd64.yaml
- .github/workflows/build-kata-static-tarball-arm64.yaml
- .github/workflows/build-kata-static-tarball-s390x.yaml
- .github/workflows/payload-after-push.yaml
The "build-assets-${arch}" jobs need to have access to the secrets in order to log into the container registry in the cases where "push-to-registry", which is used to push the builder containers to quay.io, is set to "yes".
Now that "build-assets-${arch}" pass the secrets down, we need to log into the container registry in the "build-kata-static-tarball-${arch}" files, in case "push-to-registry" is set to "yes".
Fixes: #6899
> gha: payload-after-push: Pass secrets down

- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
I cannot easily pin-point which commit dropped it, but my gut feeling is that it's the result of an erroneous conflict resolution when merging content from main to the CCv0 branch.
Regardless of when / why it happened, as the root_hash logic ended up being dropped, workflows that depend on that are now failing.
With everything said in mind, let's bring the logic back.
Fixes: #6901
> CC | local-build: Bring back root_hash logic

- tools/packaging/static-build/cache_components_main.sh
OVMF has been cached, but it's not been used from cache as the `version` set in the cached builds has always been empty.
The reason for that is because we've been trying to look for `externals.ovmf.ovmf.version`, while we should be actually looking for `externals.ovmf.x86_64.version`.
Setting `x86_64` as the OVMF_FLAVOUR would cause another bug, as the expected tarball name would then be `kata-static-x86_64.tar.xz`, instead of `kata-static-ovmf-x86_64.tar.xz`.
With everything said, let's simplify the OVMF_FLAVOUR usage, by using it as it's passed, and only adapting the tarball name for the TDVF case, which is the abnormal one.
Fixes: #6897
> cache: Fix OVMF caching

- .github/workflows/run-k8s-tests-on-aks.yaml
fa832f4709f6213946c11601ccd895ab01ee8bab increased the timeout, which helped a lot, mainly in the TEE machines.  However, we're still seeing some failures here and there with the AKS tests.
Let's bump it yet again and, hopefully, those errors to start the tests will go away.
Fixes: #6905
> gha: aks: Wait a little bit more before run the tests

- tools/packaging/kata-deploy/Dockerfile
- tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
- tools/packaging/kata-deploy/local-build/kata-deploy-build-and-upload-payload.sh
- tools/packaging/kata-deploy/local-build/kata-deploy-copy-yq-installer.sh
- tools/packaging/kata-deploy/local-build/kata-deploy-merge-builds.sh
We've a discrepancy on what's set along the scripts used to build the Kata Cotainers artefacts locally.
Some of those were missing a way to easily debug them in case of a failure happens, but one specific one (build-and-upload-payload.sh) could actually silently fail.
All of those have been changed as part of this commut.
Fixes: #6908
> local-build: Standardise what's set for the local build scripts

- tools/osbuilder/dockerfiles/QAT/Dockerfile
- tools/osbuilder/image-builder/Dockerfile
- Swap out an EoL fedora image for the latest
Fixes: #6923
> osbuilder: Bump fedora image version

- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
- tools/packaging/static-build/cache_components_main.sh
---
cache: Use "initrd" as `initrd_type` to build rootfs-initrd
We've been defaulting to "", which would lead to a mismatch with the
latest version from the cache, causing a miss, and finally having to
build the rootfs-initrd as part of the tests, every single time.
Fixes: #6917
---
cache: Fix OVMF tarball name for different flavours
75330ab3f96f644fff48312e2954ecb1c2fa4081 tried to fix OVMF caching, but
didn't consider that the "vanilla" OVMF tarball name is not
"kata-static-ovmf-x86_64.tar.xz", but rather "kata-static-ovmf.tar.xz".
The fact we missed that, led to the cache builds of OVMF failing, and
the need to build the component on every single PR.
Fixes: #6917 (hopefully for good this time).
---
> Fix cache for OVMF and rootfs-initrd (both x86_64)

- src/runtime/arch/amd64-options.mk
This commit should've been part of the series that reverted a bunch of TDX changes that are not compatible with the TDX stack we're using in the Jenkins CI machine.
The change made here is in order to match what's been undone here: c29e5036a68f67c556750356e43f7bf88b0fe313
Fixes: #6884
> runtime: Fix QEMU cmdline for TDX

- .github/workflows/release-amd64.yaml
- .github/workflows/release-arm64.yaml
- .github/workflows/release-s390x.yaml
- .github/workflows/release.yaml
`docker/login-action@v3` does *not* exist and `docker/login-action@v2` should be used instead.
Fixes: #6934
> release: Fix `docker/login-action` version

- versions.yaml
This PR updates the nydus version to 2.2.1. This change includes: 
nydus-image: fix a underflow issue in get_compressed_size()
backport fix/feature to stable 2.2
[backport] contrib: upgrade runc to v1.1.5
service: add README for nydus-service
nydus: fix a possible panic caused by SubCmdArgs::is_present Backports two bugfixes from master into stable/v2.2
[backport stable/v2.2] action: upgrade golangci-lint to v1.51.2 
[backport] action: fix smoke test for branch pattern
Fixes #6938
> versions: Update nydus version to 2.2.1

- .github/workflows/release-amd64.yaml
- .github/workflows/release-arm64.yaml
- .github/workflows/release-s390x.yaml
- .github/workflows/release.yaml
For some bizarre reason, the login-action will simply fail to authenticate to docker.io in it's specified as a registry.  The way to proceed, instead, is to *not* specify any registry as it'd be used by default.
Fixes: #6943
> gha: release: login-action: Don't specify docker.io registry

- .github/workflows/release-amd64.yaml
- .github/workflows/release-arm64.yaml
- .github/workflows/release-s390x.yaml
We previously were doing:
* Create a new image on kata-deploy-ci using the commit hash of the latest tag
* This was used to test on AKS, which is no longer needed as we test on AKS on every PR
* Create a new image on kata-deploy using the release tag and "latest" or "stable", by tagging the kata-deploy-ci image accordingly
As part of cfe63527c5328611cac647d0c10916bef6cf0408, we broke the workflow described above, as in the first step we would save the PKG_SHA to be used in the second step, but that part ended up being removed.
Anyways, this back and forth is not needed anymore and we can simplify the process by doing:
* Create a new image on kata-deploy, using:
- The tag received as ref from the event that triggered this worklow
- "latest" or "stable" tag, depending on whether it's a …
> gha: release: Simplify the process for tagging the payload

- src/runtime/Makefile
- src/runtime/config/configuration-qemu-tdx.toml.in
The rebase from `main` to `CCv0` ended up overwriting the image path that should be used for QEMU, in the CCv0 branch.
Fixes: #6932
> CC | runtime: config: Fix image path for QEMU TDX

- tools/packaging/kata-deploy/local-build/kata-deploy-merge-builds.sh
This PR fixes the indentation on the kata deploy merge script that instead of single spaces uses a tap.
Fixes #6925
> kata-deploy: Fix indentation on kata deploy merge script

- tools/packaging/kata-deploy/README.md
- tools/packaging/kernel/README.md
Fix bad migrations from `go get` to `git clone` and update the cloned directory path
Fixes: #6951
> doc: Update git commands

- src/dragonball/src/config_manager.rs
- src/dragonball/src/device_manager/mod.rs
- src/dragonball/src/device_manager/virtio_net_dev_mgr.rs
- src/dragonball/src/device_manager/vsock_dev_mgr.rs
This MR implements removing virtio-net and virtio-vsock devices gracefully when shutting down VMM.
Fixes: #6684
> dragonball: Remove virtio-net and vsock devices gracefully

- src/dragonball/src/api/v1/vmm_action.rs
- src/dragonball/src/device_manager/blk_dev_mgr.rs
- src/dragonball/src/device_manager/virtio_net_dev_mgr.rs
VsockDeviceMgr::insert_device is a method. BlockDeviceMgr::insert_device and VirtioNetDeviceMgr::insert_device can convert to method too. Make the code more readable through this.
Fixes: #6880
> dragonball: convert BlockDeviceMgr and VirtioNetDeviceMgr functions to methods

- src/runtime/virtcontainers/qemu.go
There is a race condition when virtiofsd is killed without finishing all the clients. Because of that, when a pod is stopped, QEMU detects virtiofsd is gone, which is legitimate.
Sending a SIGTERM first before killing could introduce some latency during the shutdown.
One alternative is to just kill QEMU during this phase.
Fixes #6757.
> runtime: sending SIGKILL to qemu

- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
This PR removes unwanted white spaces in order to fix the format of the kata-deploy-binaries script.
Fixes: #6962
> kata-deploy: Remove trailing and leading white spaces in kata-deploy-binaries.sh

- .github/workflows/run-k8s-tests-on-aks.yaml
- tests/integration/kubernetes/run_kubernetes_tests.sh
- tests/integration/kubernetes/setup.sh
This PR kickstarts the onboarding of Mariner onto the CI.
The current testing setup only supports running Kata on top of an Ubuntu host. This adds Mariner to the matrix of testable hosts for k8s tests, with Cloud Hypervisor as a VMM.
As preparation for the upcoming PR (#6839) that will change the actual test code (rather than workflow YAMLs), this also introduces a new file `setup.sh` that will be used to set host-specific parameters at test time.
Fixes: #6961
> gha: Create Mariner host as part of k8s tests

- src/agent/Cargo.lock
- src/libs/Cargo.lock
- src/libs/kata-types/Cargo.toml
- src/libs/kata-types/src/mount.rs
- src/runtime-rs/Cargo.lock
- src/tools/kata-ctl/Cargo.lock
- src/tools/kata-ctl/src/ops/volume_ops.rs
Move the get_volume_mount_info to kata-types/src/mount.rs. If so, it becomes a common method of DirectVolumeMountInfo and reduces duplicated code.
Fixes: #6701
> runtime-rs/kata-ctl: Enhancement of DirectVolumeMount.

- src/libs/kata-types/src/annotations/mod.rs
- src/libs/kata-types/src/config/runtime.rs
- src/libs/kata-types/src/mount.rs
- src/runtime-rs/config/configuration-dragonball.toml.in
- src/runtime-rs/crates/resource/src/manager_inner.rs
- src/runtime-rs/crates/resource/src/share_fs/mod.rs
- src/runtime-rs/crates/resource/src/share_fs/sandbox_bind_mounts.rs
- src/runtime-rs/crates/resource/src/share_fs/utils.rs
- src/runtime-rs/crates/resource/src/share_fs/virtio_fs_share_mount.rs
sandbox_bind_mounts supports kinds of mount patterns, for example:
(1) "/path/to",     default readonly mode.
(2) "/path/to:ro",   same as (1).
(3) "/path/to:rw",   readwrite mode.
Both support configuration and annotation:
(1)[runtime]
sandbox_bind_mounts = ["/path/to", "/path/to:rw", "/mnt/to:ro"]
(2) annotation will be supported too, restricted as below: io.katacontainers.config.runtime.sandbox_bind_mounts
= "/path/to /path/to:rw /mnt/to:ro"
Fixes: #6597
> runtime-rs/sandbox_bindmounts: add support for sandbox bindmounts

- .github/workflows/run-k8s-tests-on-aks.yaml
This fixes the regression introduced by https://github.com/kata-containers/kata-containers/pull/6686 by properly injecting the `--os-sku mariner --workload-runtime KataMshvVmIsolation` flags.
Error reference:
https://github.com/kata-containers/kata-containers/actions/runs/5111460297/jobs/9188819103
Fixes: https://github.com/kata-containers/kata-containers/issues/6982
> gha: Unbreak CI and fix cluster creation step

- src/runtime/virtcontainers/qemu.go
There is a race condition when virtiofsd is killed without finishing all the clients. Because of that, when a pod is stopped, QEMU detects virtiofsd is gone, which is legitimate.
Sending a SIGTERM first before killing could introduce some latency during the shutdown.
Backport of #6959.
> runtime: sending SIGKILL to qemu (backport to 3.1)

- .github/workflows/run-k8s-tests-on-aks.yaml
While the Mariner Kata host is in preview, we need the `aks-preview` extension to enable the `--workload-runtime KataMshvVmIsolation` flag.
Fixes: #6994
> gha: Fix Mariner cluster creation

- .github/workflows/run-k8s-tests-on-aks.yaml
We need to do so, otherwise we'll create two clusters for testing Cloud Hypervisor with exactly the same name, one using Ubuntu, and one using Mariner.
Fixes: #6999
> gha: aks: Add the host_os as part of the aks cluster's name

- tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
- tools/packaging/scripts/lib.sh
This PR is to make an environment variable `BUILDER_REGISTRY` configurable so that those who want to use their own registry for build can set up the registry.
Fixes: #6988
> packaging: make BUILDER_REGISTRY configurable

- .github/workflows/release.yaml
release: Standardize kata static file name
The string representing the architecture aarch64 and x86_64 need to be changed to arm64 and amd64 for the release.
Fixes: #6986
> main | release: Standardize kata static file name

- .github/workflows/run-k8s-tests-on-aks.yaml
We added that to create the cluster name, but I forgot to add that to the part we get the k8s config file, or to the part where we delete the AKS cluster.
Fixes: #6999
> gha: aks: Ensure host_os is used everywhere needed

- tools/packaging/kata-deploy/Dockerfile
The current method has been failing every now and then, and was reported on https://github.com/kubernetes/release/issues/2862.
Ding poked me and suggested to do this change here, so here we go. :-)
Fixes: #7006
> kata-deploy: Change how we get the Ubuntu k8s key

- README.md
---
readme: Add status badge for the "Publish Artefacts" job
Let's start adding the status of our jobs as part of our main page, so
folks monitoring those can easily check whether they're okay, or if
someone has to be pinged about those.
Fixes: #7008 
---
readme: Update Kata Containers logo
Let's use the horizontal logo, as it occupies better the space the we
have.
The logo comes from:
https://openinfra.dev/brand/logos
---
> README: Display badge for the "Publish Artefacts" job and update the Kata Containers logo

- .github/workflows/run-k8s-tests-on-aks.yaml
Full SHA is 40 characters, while AKS cluster name has a limit of 63. Trim the SHA to 12 characters, which is widely considered to be unique enough and is short enough to be used in the cluster name
Fixes: #7010
> gha: aks: Use short SHA in cluster name

- src/runtime-rs/Cargo.lock
When dragonball update dbs-boot crate in commit
64c764c1475fc9230b4836f5e02c81fc6e1410a7, the Cargo.lock in runtime-rs should also be updated.
Fixes: #6969
> runtime-rs: bugfix: update Cargo.lock

- src/agent/rustjail/src/process.rs
- src/agent/src/rpc.rs
When run a exec process in backgroud without tty, the
exec will hang and didn't terminated.
For example:
crictl -i <container id> sh -c 'nohup tail -f /dev/null &'
Fixes: #4747
> agent: fix the issue of exec hang with a backgroud process

- src/agent/Cargo.lock
- src/libs/Cargo.lock
- src/libs/kata-sys-util/Cargo.toml
- src/runtime-rs/Cargo.lock
- src/tools/agent-ctl/Cargo.lock
- src/tools/kata-ctl/Cargo.lock
- src/tools/runk/Cargo.lock
When the version of `libc` is upgraded to 0.2.145, `getrandom` could not adapt to new API, and this will make `agent-ctl` fail to compile.
We upgrade the version of `rand`, so the low version of `getrandom` will no longer need.
Fixes: #7032
> agent-ctl: fix the compile error

- src/runtime-rs/crates/resource/src/manager_inner.rs
- src/runtime-rs/crates/resource/src/volume/mod.rs
- src/runtime-rs/crates/resource/src/volume/share_fs_volume.rs
- versions.yaml
In hypervisors that do not support virtiofs we have to copy files in the VM sandbox to properly setup the network (resolv.conf, hosts, and hostname).
To do that, we construct the volume as before, with the addition of an extra variable that designates the path where the file will reside in the sandbox.
In this case, we issue a `copy_file` agent request *and* we patch the spec to account for this change.
Fixes: #6978
> runtime-rs: handle copy files when share_fs is not available

- .github/workflows/run-k8s-tests-on-aks.yaml
- .github/workflows/run-k8s-tests-on-sev.yaml
- .github/workflows/run-k8s-tests-on-snp.yaml
- .github/workflows/run-k8s-tests-on-tdx.yaml
- tests/integration/gha-run.sh
Github Actions reads and runs workflow files from the main branch, rather than from the PR branch. This means that PRs that modify workflow files aren't being tested with the updated workflows coming from the PR, but rather with the old workflows from the main branch. AFAIK, this behavior isn't avoidable for workflow files (but is for other scripts).
This makes it very hard to reliably test workflow changes before they're actually merged into main and leads to issues that we have to hotifx (see #6983, #6995).
This PR aims to mitigate that by extracting the commands used in workflows to a separate script file. The way our CI is set up, those script files are read from the PR branch and thus changes would be reflected in the CI checks.
Fixes: #6971
> gha: aks: Extract `run` commands to a script

- src/agent/Cargo.lock
- src/agent/Cargo.toml
- versions.yaml
This updates image-rs, attestation-agent, and td-shim to v0.6.0 for the upcoming release.
> CCv0: Update dependencies to v0.6.0 for release

- src/tools/log-parser-rs/README.md
This PR updates the link to the correspondent Developer Guide at the enabling full containerd debug that we have for kata 2.0 documentation.
Fixes #7034
> log-parser: Update log parser link at README

- src/agent/Cargo.lock
- src/libs/logging/Cargo.toml
- src/libs/logging/src/lib.rs
- src/tools/kata-ctl/Cargo.lock
- src/tools/kata-ctl/Cargo.toml
- src/tools/kata-ctl/src/arch/aarch64/mod.rs
- src/tools/kata-ctl/src/arch/s390x/mod.rs
- src/tools/kata-ctl/src/arch/x86_64/mod.rs
- src/tools/kata-ctl/src/args.rs
- src/tools/kata-ctl/src/check.rs
- src/tools/kata-ctl/src/main.rs
- src/tools/kata-ctl/src/ops/check_ops.rs
- src/tools/kata-ctl/src/ops/exec_ops.rs
- src/tools/kata-ctl/src/ops/volume_ops.rs
Fixes: #5401, #6654
- Switch kata-ctl from eprintln!()/println!() to structured logging via the logging library which uses slog.
- Adds a new create_term_logger() library call which enables printing log messages to the terminal via a less verbose / more human readable terminal format with colors.
- Adds --log-level argument to select the minimum log level of printed messages.
- Adds --json-logging argument to switch to logging in JSON format.
> kata-ctl: Switch to slog logging; add --log-level and --json-logging arguments

- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Qemu entry for SNP was changed in the versions.yaml resulting into the incorrect qemu build for SNP.
Fixes: #7059
Signed-Off-By: Unmesh Deodhar <udeodhar@amd.com>
> local-build: Fix qemu build for SNP

- docs/how-to/README.md
- docs/how-to/how-to-run-kata-containers-with-kinds-of-Block-Volumes.md
- src/runtime-rs/Cargo.lock
- src/runtime-rs/crates/hypervisor/src/device/device_manager.rs
- src/runtime-rs/crates/hypervisor/src/device/driver/vfio.rs
- src/runtime-rs/crates/hypervisor/src/device/driver/vhost_user.rs
- src/runtime-rs/crates/hypervisor/src/device/driver/virtio_blk.rs
- src/runtime-rs/crates/hypervisor/src/device/mod.rs
- src/runtime-rs/crates/resource/src/manager_inner.rs
- src/runtime-rs/crates/resource/src/rootfs/block_rootfs.rs
- src/runtime-rs/crates/resource/src/volume/block_volume.rs
- src/runtime-rs/crates/resource/src/volume/mod.rs
- src/runtime-rs/crates/resource/src/volume/utils.rs
usage:
```bash
#direct volume 
$ sudo ctr run --runtime "io.containerd.kata.v2" --rm -t \
--mount type=directvol,src=/tmp/directv01,dst=/data2,options=rbind:rw "$image" \
test-kata2 /bin/bash
$ sudo ctr run --runtime "io.containerd.kata.v2" --rm -t \
--mount type=directvol,src=/tmp/directv01,dst=/dev/vdc,options=rbind:rw "$image" \
test-kata2 /bin/bash
```
device manager: refactor device manager implementation
the main aspects of the DM implementation refactoring as below:
1. reduce duplicated code
Many scenarios have similar steps when adding devices. so to reduce duplicated code,
we should create a common method abstracted and use it in various scenarios.
do_handle_device:
(1) new_device with DeviceConfig and return device_id;
(2) try_add_device with device_id and do really add device; …
> add support direct volume and refactor device manager

- src/dragonball/Cargo.lock
- src/dragonball/Cargo.toml
- src/dragonball/src/api/v1/vmm_action.rs
- src/dragonball/src/device_manager/balloon_dev_mgr.rs
- src/dragonball/src/device_manager/blk_dev_mgr.rs
- src/dragonball/src/device_manager/mem_dev_mgr.rs
- src/dragonball/src/device_manager/memory_region_handler.rs
- src/dragonball/src/device_manager/mod.rs
- src/dragonball/src/error.rs
- src/dragonball/src/vm/mod.rs
we introduce two virtio devices to support resizing memory:
1. virtio-balloon device. virtio-balloon device could reclaim memory from guest to host.
2. virtio-mem device.  virtio-mem device could hot-plug more memory blocks to guest and could also hot-unplug them from guest.
These patches support ability of Dragonball resizing memory, and expose interface to runtime-rs.
> Dragonball: support resize memory

- tools/packaging/kata-deploy-cc/scripts/kata-deploy.sh
Pod annotations (io.katacontainers.*) are not meaningful for the remote hypervisor.
https://github.com/kata-containers/kata-containers/blob/main/docs/how-to/how-to-set-sandbox-config-kata.md
This patch disables pod annotations in the kata-remote settings of the containerd configuration.
Fixes #6345
`config.toml` of containerd will look like this.
```
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata]
cri_handler = "cc"
runtime_type = "io.containerd.kata.v2"
privileged_without_host_devices = true
pod_annotations = ["io.katacontainers.*"]
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata.options]
ConfigPath = "/opt/confidential-containers/share/defaults/kata-containers/configuration.toml"
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-remote] …
```
> CCv0: kata-deploy-cc: Ignore pod annotations in kata-remote

- .github/workflows/build-kata-static-tarball-amd64.yaml
This defines `stage` as a list instead of a literal to fix the GHA CI.
Fixes: #7086
> gha: Fix `stage` definition in matrix

- tools/packaging/kata-deploy/local-build/Makefile
- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
This fixes the builds of `cloud-hypervisor-glibc` and `rootfs-initrd-mariner` to properly create the `build/` directory.
Fixes: #7098
> tools: Fix no-op builds

- versions.yaml
This PR updates the firecracker version to 1.3.3 which includes the following changes
Fixed passing through cache information from host in CPUID leaf 0x80000006. A race condition that has been identified between the API thread and the VMM thread due to a misconfiguration of the api_event_fd.
Fixes #7089
> versions: Update firecracker version to 1.3.3

- src/runtime-rs/crates/hypervisor/src/device/driver/virtio_fs.rs
- src/runtime-rs/crates/hypervisor/src/dragonball/inner_device.rs
- src/runtime-rs/crates/resource/src/share_fs/share_virtio_fs.rs
runtime-rs: Enhance flexibility of virtio-fs config
support more and flexible options for inline virtiofs.
Fixes: #7091
> runtime-rs: Enhance flexibility of virtio-fs config

- .github/workflows/run-launchtimes-metrics.yaml
The run-launchtimes-metrics workflow needs to get the commit ID for the last commit to the head branch of the PR.
Fixes: #7116
> gha: Add base branch on SHA on pull requst

- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
This is to set a default value for `AA_KBC` for the make target `cc_rootfs_initrd_tarball`.
Fixes: #7121
> CC: Set default value for AA_KBC for cc_rootfs_initrd_tarball

- src/runtime/Makefile
- src/runtime/config/configuration-clh.toml.in
- src/runtime/config/configuration-qemu.toml.in
- src/runtime/virtcontainers/virtiofsd.go
- src/runtime/virtcontainers/virtiofsd_test.go
This series fixes some deprecated arguments being passed to `virtiofsd`,
either by dropping them when they aren't needed anymore or by
converting them to the replacement arguments expected by the rust
virtiofsd.
Fixes #7111
> Fix deprecated virtiofsd args (go shim only)

- .github/workflows/run-launchtimes-metrics.yaml
This PR fixes the format for the run launchtimes metrics yaml which is causing to the workflow to fail.
Fixes #7130
> gha: Fix format for run launchtimes metrics yaml

- versions.yaml
Currently ubuntu is already the default distro for all the architectures but x86_64, which uses clearlinux.  However, our CI does *not* test the clearlinux image we ship.
Taking a look at our CI code [0], we've been using ubuntu as base for the tests for a few years already, if not forever.
The minimum we can do is to switch to distributing ubuntu, as the tested rootfs-image, and then decide later on whether we should switch back to clearlinux (once we switch our CI to using that, and make sure all tests will be green), or if we move to slimmer distro, such as alpine.
[0]: https://github.com/kata-containers/tests/blob/0a39dd1a01dc135e76f874b9475a33c5f54afcca/.ci/install_kata_image.sh#L44
Fixes: #7123
> [stable-3.1] backport: versions: Use ubuntu as the default distro for the rootfs-image

- tests/metrics/lib/json.bash
This PR adds the json script which allow us to save the metrics results into a json file which will be used in the kata containers metrics.
Fixes #7128
> tests: Add json script for metrics tests

- tools/packaging/static-build/initramfs/init.sh
This PR replaces single spaces for tabs in order to fix the indentation in the init.sh script.
Fixes #7147
> packaging: Fix indentation in init.sh script

- src/tools/kata-ctl/src/arch/aarch64/mod.rs
- src/tools/kata-ctl/src/arch/powerpc64le/mod.rs
- src/tools/kata-ctl/src/arch/s390x/mod.rs
- src/tools/kata-ctl/src/arch/x86_64/mod.rs
- src/tools/kata-ctl/src/check.rs
- src/tools/kata-ctl/src/ops/env_ops.rs
- src/tools/kata-ctl/src/types.rs
Implement functionality to add to the env output if the host is capable
of running a VM.
Fixes: #6727
Adding vhost and vhost-net to the kernel modules. These do not require
any kernel module parameters to be checked. Currently, kernel params is
a required field. Make this as optional. Could make this as <Option>,
but making this a slice instead, as a module could have multiple kernel
params. Refactor the function that checks are for kernel modules into
two with one specifically checking if the module is loaded and other
checking for module parameters.
> kata-ctl: Check for vm capability

- src/runtime/Makefile
- src/runtime/config/configuration-clh.toml.in
- src/runtime/config/configuration-qemu.toml.in
- src/runtime/virtcontainers/virtiofsd.go
- src/runtime/virtcontainers/virtiofsd_test.go
This backports #7112 to branch stable-3.1.
> [stable-3.1] Fix deprecated virtiofsd args (go shim only)

- .github/workflows/ci-on-push.yaml
We have GH configured so that manual approval is required for CI runs triggered by outside contributors. However, because CI is triggered by the `pull_request_target` event, this setting isn't being honored (see [1]).
This change aims to mititgate this issue by preventing PRs from triggering CI unless the `ok-to-test` label is set.
Note: For further context, we use the `pull_request_target` event and manually check out the PR branch because it is the only way to both access secrets and test incoming code changes.
Fixes: https://github.com/kata-containers/kata-containers/issues/7163
[1]: https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks
> gha: Don't automatically trigger CI

- docs/how-to/how-to-run-kata-containers-with-kinds-of-Block-Volumes.md
- src/runtime-rs/Cargo.lock
- src/runtime-rs/crates/hypervisor/Cargo.toml
- src/runtime-rs/crates/hypervisor/src/device/device_manager.rs
- src/runtime-rs/crates/hypervisor/src/device/driver/mod.rs
- src/runtime-rs/crates/hypervisor/src/device/driver/vfio.rs
- src/runtime-rs/crates/hypervisor/src/device/util.rs
- src/runtime-rs/crates/hypervisor/src/dragonball/inner_device.rs
- src/runtime-rs/crates/resource/src/manager_inner.rs
- src/runtime-rs/crates/resource/src/network/endpoint/physical_endpoint.rs
- src/runtime-rs/crates/resource/src/volume/mod.rs
- src/runtime-rs/crates/resource/src/volume/vfio_volume.rs
1. runtime-rs: add support vfio device manager
Limitations:
As no ready rust vmm's vfio manager is ready, it only supports
part of vfio in runtime-rs. And the left part is to call vmm
interfaces related to vfio add/remove.
So when vmm/vfio manager ready, a new PR will be pushed to
narrow the gap.
2. runtime-rs: add support vfio device based volume
A new choice of using vfio devic based volume for kata-containers.
With the help of kata-ctl direct-volume, users are able to add a
specified device which is BDF or IOMMU group ID.
To help users to use it smoothly, A doc about howto added in
docs/how-to/how-to-run-kata-containers-with-kinds-of-Block-Volumes.
Fixes: https://github.com/kata-containers/kata-containers/issues/6525
> add support vfio device manager 

- README.md
- tests/metrics/README.md
This PR adds a general metrics introduction documentation for the kata CI.
Fixes #7157
> docs: Add general metrics documentation

- tools/packaging/static-build/initramfs/build.sh
- tools/packaging/static-build/ovmf/build.sh
- tools/packaging/static-build/td-shim/build.sh
- Remove the unnecessary kata-version passed as a second parameter
Fixes: #7096
> static-build: Remove kata-version parameter

- docs/how-to/how-to-run-kata-containers-with-kinds-of-Block-Volumes.md
- src/dragonball/src/device_manager/blk_dev_mgr.rs
- src/runtime-rs/crates/hypervisor/src/device/device_manager.rs
- src/runtime-rs/crates/hypervisor/src/device/driver/mod.rs
- src/runtime-rs/crates/hypervisor/src/device/driver/vhost_user.rs
- src/runtime-rs/crates/hypervisor/src/device/driver/vhost_user_blk.rs
- src/runtime-rs/crates/hypervisor/src/device/mod.rs
- src/runtime-rs/crates/hypervisor/src/dragonball/inner_device.rs
- src/runtime-rs/crates/resource/src/manager.rs
- src/runtime-rs/crates/resource/src/manager_inner.rs
- src/runtime-rs/crates/resource/src/volume/mod.rs
- src/runtime-rs/crates/resource/src/volume/spdk_volume.rs
- src/runtime-rs/crates/resource/src/volume/utils.rs
- src/runtime-rs/crates/runtimes/virt_container/src/lib.rs
Unlike the previous usage which requires creating
/dev/xxx by mknod on the host, the new approach will fully utilize the DirectVolume-related usage method, and pass the spdk controller to vmm.
And a user guide about using the spdk volume when run a kata-containers. it can be found in docs/how-to.
Fixes: #6526
> runtime-rs: add support spdk/vhost-user based volume.

- tests/metrics/README.md
- tests/metrics/time/README.md
This PR adds boot time metrics documentation for kata metrics tests.
Fixes #7170
> docs: Add boot time metrics documentation

- tests/metrics/README.md
- tests/metrics/cmd/checkmetrics/Makefile
- tests/metrics/cmd/checkmetrics/README.md
This PR adds checkmetrics documentation and makefile which is used to process the metrics json results files.
Fixes #7172
> checkmetrics: Add checkmetrics makefile and documentation

- tests/common.bash
This PR makes use of sudo to retrieve the hypervisor version.
Fixes: #7178
> metrics: Fix retrieving hypervisor version on metrics

- src/runtime-rs/crates/resource/src/volume/block_volume.rs
- src/runtime-rs/crates/resource/src/volume/utils.rs
The failure mainly caused by the encoded volume path and the mount/src. As the src will be validated with stat,but it's not a full path and encoded, which causes the stat mount source failed.
Fixes: #7186
> runtime-rs: bugfix for direct volume path's validation.

- tools/packaging/kata-deploy/Dockerfile
- tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml
- tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
- tools/packaging/kata-deploy/scripts/kata-deploy.sh
CentOS registry has been decomissioned between our last stable release and this one (see https://www.spinics.net/lists/centos-devel/msg22160.html, thanks @gkurz for pointing this out), which breaks our usage of CentOS as the base image.
As we've switched to using Ubuntu as the base image some time ago for the `main` branch, let's simply backport the needed patches here, instead of keep using CentOS.
> stable-3.1: A bunch of kata-deploy fixes and a switch to using ubuntu as the base image

- tests/metrics/gha-run.sh
This PR adds the word function before the function names in order to have uniformity across the script as some are using this and some are not.
Fixes #7196
> metrics: Uniformity across function names in gha-run.sh

- src/runtime/config/configuration-clh.toml.in
- src/runtime/config/configuration-qemu-nvidia-gpu.toml.in
- src/runtime/config/configuration-qemu-sev.toml.in
- src/runtime/config/configuration-qemu-snp.toml.in
- src/runtime/config/configuration-qemu-tdx.toml.in
- src/runtime/config/configuration-qemu.toml.in
- src/runtime/pkg/device/config/config.go
- src/runtime/pkg/katautils/config.go
- src/runtime/virtcontainers/acrn.go
- src/runtime/virtcontainers/acrn_arch_base.go
- src/runtime/virtcontainers/acrn_arch_base_test.go
- src/runtime/virtcontainers/clh.go
- src/runtime/virtcontainers/clh_test.go
- src/runtime/virtcontainers/qemu.go
- src/runtime/virtcontainers/qemu_amd64.go
- src/runtime/virtcontainers/qemu_amd64_test.go
- src/runtime/virtcontainers/qemu_arch_base.go
- src/runtime/virtcontainers/qemu_arch_base_test.go
- src/runtime/virtcontainers/qemu_ppc64le.go
Currently, even when using devmapper, if the VMM supports virtio-fs /
virtio-9p, that's used to share a few files between the host and the
guest.
This needed, as we need to share with the guest contents like secrets,
certificates, and configurations, via Kubernetes objects like configMaps
or secrets, and those are rotated and must be updated into the guest
whenever the rotation happens.
However, there are still use-cases users can live with just copying
those files into the guest at the pod creation time, and for those
there's absolutely no need to have a shared filesystem process running
with no extra obvious benefit, consuming memory and even increasing the
attack surface used by Kata Containers.
For the case mentioned above, we should allow users, making it very
clear which limitations …
> runtime: Add "none" as a shared_fs option

- docs/design/README.md
- docs/design/kata-vra.md
Adding detailed information about the virtualization reference architecture. 
Fixes: #4041
DependsOn: https://github.com/kata-containers/tests/pull/5703
> doc: Add documentation for the virtualization reference architecture

- tools/packaging/static-build/ovmf/build.sh
This PR fixes the indentation of build.sh script at ovmf.
Fixes #7208
> packaging: Fix indentation of build.sh script at ovmf

- tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
- tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-cloud-hypervisor-kata-metric8.toml
- tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
- tests/metrics/gha-run.sh
This PR adds checkmetrics installation for gha-run.sh in order to compare results limits as part of the metrics CI.
Fixes #7198
> metrics: Add checkmetrics to gha-run.sh for metrics CI

- .github/workflows/release.yaml
ideally we should never ever use hub again, and switch to a supported / release tool instead.  However, in order to get v3.1.3 released, let's just stick to the last released version of hub, as trying to get its release is leading to:
```
curl -s "https://api.github.com/repos/github/hub/releases/latest"
{
"message": "Moved Permanently",
"url": "https://api.github.com/repositories/401025/releases/latest",
"documentation_url": "https://docs.github.com/v3/#http-redirects"
}
```
And that breaks the release process. :-/
Fixes: #7223
> gha: release: Use a specific release of hub

- .github/workflows/release.yaml
ideally we should never ever use hub again, and switch to a supported / release tool instead.  However, in order to get v3.1.3 released, let's just stick to the last released version of hub, as trying to get its release is leading to:
```
curl -s "https://api.github.com/repos/github/hub/releases/latest"
{
"message": "Moved Permanently",
"url": "https://api.github.com/repositories/401025/releases/latest",
"documentation_url": "https://docs.github.com/v3/#http-redirects"
}
```
And that breaks the release process. :-/
Fixes: #7223
Backport of: #7224
> stable-3.1 | gha: release: Use a specific release of hub

- src/agent/rustjail/src/cgroups/fs/mod.rs
- src/agent/rustjail/src/cgroups/notifier.rs
- src/agent/rustjail/src/container.rs
- src/agent/src/device.rs
- src/agent/src/main.rs
- src/agent/src/metrics.rs
- src/agent/src/rpc.rs
- src/agent/src/tracer.rs
- src/agent/src/uevent.rs
This fixes https://github.com/kata-containers/kata-containers/issues/7201. 
As part of converting `is_allowed`, we also fix https://github.com/kata-containers/kata-containers/issues/5409 because it allows us to avoid having to `.await` all calls.
> Convert `is_allowed`, `ttrpc_error` and `sl` to functions

- versions.yaml
v33.0. The following user visible changes have been made:
A D-Bus based API has been added as an alternative to the existing REST
API. This feature is gated by the `dbus_api` feature. Details can be
found in the [API documentation](docs/api.md).
Now the CPU cache information on the host is properly exposed to the
guest on AArch64.
* Report errors explicitly to users when VM failed to boot
* Fix VFIO on platforms with non-4k page size
* Fix TDX initialization
* Ensure all guest memory regions are page-size aligned
* Fix seccomp filter lists related to virtio-console, serial and pty
* Populate APIC ID properly
* Ignore and warn TAP FDs in more situations
Details can be …
> versions: Upgrade to Cloud Hypervisor v33.0

- .github/workflows/static-checks-dragonball.yaml
cargo/rust is installed in one step, we need to write the PATH update to GITHUBENV so that it becomes visible in the next steps.
Fixes: #7221
> gha: dragonball: Correctly propagate PATH update

- tools/packaging/kata-deploy-cc/scripts/kata-deploy.sh
SNP's QEMU has changed its name some time ago and, due to that, we have been leaving the new binary behind during the uninstall process, which lead to the Operator hanging when uninstalling.
Fixes: #7233
> cc: kata-deploy: Adapt the SNP's QEMU name

- .github/workflows/cc-payload-after-push-amd64.yaml
- .github/workflows/cc-payload-after-push-s390x.yaml
- .github/workflows/cc-payload-amd64.yaml
- .github/workflows/cc-payload-s390x.yaml
Since the measured rootfs work has been merged to main, and then brought in to the CCv0 via the weekly merge, we have introduced a few regressions related to how we build it / use it.
This PR attempts to make sure the artefacts are properly built, using GitHub Actions, so the feature can be used with the operator.
Fixes: #7235
> cc: gha: Pass MEASURED_ROOTFS to the artefacts build

- .github/workflows/cc-payload-after-push-amd64.yaml
- .github/workflows/cc-payload-after-push-s390x.yaml
- .github/workflows/cc-payload-amd64.yaml
- .github/workflows/cc-payload-s390x.yaml
- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
We need to export MEASURED_ROOTFS=yes for the rootfs-image builds, as shown here[0], otherwise the root_hash.txt file won't be generated.
A huge thanks to Choi for quickly finding this out.
Fixes: #7235
[0]:
https://github.com/kata-containers/kata-containers/blob/CCv0/tools/osbuilder/image-builder/image_builder.sh#L507,
> cc: gha: Export MEASURE_ROOTFS=yes for rootfs-image builds

- .github/workflows/cc-payload-after-push-amd64.yaml
- .github/workflows/cc-payload-after-push-s390x.yaml
- .github/workflows/cc-payload-amd64.yaml
- .github/workflows/cc-payload-s390x.yaml
Those components are being built twice, one as part of the normal matrix assets, and the second one as part of the include.
Fixes: #7235
> cc: gha: Avoid building twice the components set as "include"

- tests/integration/gha-run.sh
- tests/integration/kubernetes/k8s-pod-quota.bats
- tests/integration/kubernetes/runtimeclass_workloads/pod-custom-dns.yaml
- tests/integration/kubernetes/runtimeclass_workloads/pod-oom.yaml
- tests/integration/kubernetes/runtimeclass_workloads/pod-quota-deployment.yaml
- tests/integration/kubernetes/runtimeclass_workloads/resource-quota.yaml
- tests/integration/kubernetes/runtimeclass_workloads/tests-namespace.yaml
Let's make sure we run our tests in a specific namespace, as in case of
any kind of issue, we will just get rid of the namespace itself, which
will take care of cleaning up any leftover from failing tests.
One important thing to mention is why we can get rid of the `namespace:
${namespace}` on the tests that are already using it, and let's do it in
parts:
* namespace: default
We can easily get rid of this as that's the default namespace where
pods are created, so it was a no-op so far.
* namespace: test-quota-ns
My understanding is that we'd need this in order to get a clean
namespace where we'd be setting a quota for.  Doing this in the
namespace that's only used for tests should **not** cause any
side-effect on the tests, as we're running those in serial and there's
no other pods …
> gha: k8s: Ensure tests are running on a specific namespace

- .github/workflows/build-kata-static-tarball-amd64.yaml
- .github/workflows/build-kata-static-tarball-arm64.yaml
- .github/workflows/build-kata-static-tarball-s390x.yaml
- .github/workflows/ci-nightly.yaml
- .github/workflows/ci-on-push.yaml
- .github/workflows/ci.yaml
- .github/workflows/payload-after-push.yaml
- .github/workflows/publish-kata-deploy-payload-amd64.yaml
- .github/workflows/publish-kata-deploy-payload-arm64.yaml
- .github/workflows/publish-kata-deploy-payload-s390x.yaml
- .github/workflows/run-k8s-tests-on-aks.yaml
- .github/workflows/run-k8s-tests-on-sev.yaml
- .github/workflows/run-k8s-tests-on-snp.yaml
- .github/workflows/run-k8s-tests-on-tdx.yaml
- .github/workflows/run-metrics.yaml
The idea of this PR is to add nightly jobs for the bits we care, and ensure we have something similar to the "Green CI" effort, but as part of GitHub.
This is a draft PR, the idea is to gather feedback from the interested parts.
One thing to mention, how do we track it?  My idea was to add a badge on our `kata-containers/kata-containers/README.md`, and from there folks can monitor the state of the CI.
> gha: Add nightly jobs

- .github/workflows/ci-nightly.yaml
- .github/workflows/ci-on-push.yaml
- .github/workflows/payload-after-push.yaml
de83cd9de79226b15519e07871dcdee635d501c6 tried to solve an issue, but it clearly seems that I'm using env wrongly, as what ended up being passed as input was "$VAR", instead of the content of the VAR variable.
As we can simply avoid using those here, let's do it and save us a headache.
Fixes: #7247
> gha: ci: Avoid using env unless it's really needed

- src/runtime/config/configuration-remote.toml.in
- Add annotation enablement for machine_type, default_memory and default_vcpus
- Remove note that says that cpu and memory settings are ignored.
Fixes: #7256
> config:  Update remote hypervisor config

- .github/workflows/build-kata-static-tarball-amd64.yaml
- tests/integration/gha-run.sh
- tests/integration/kubernetes/run_kubernetes_tests.sh
- tests/integration/kubernetes/setup.sh
- tools/packaging/guest-image/build_image.sh
- tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
- tools/packaging/kata-deploy/scripts/kata-deploy.sh
- tools/packaging/static-build/cloud-hypervisor/build-static-clh.sh
- versions.yaml
Depends on: ~#6686~ ~#7027~
This PR adapts the test code so that we can actually run k8s tests on Mariner. The change is essentially summarized as below:
1) We allow building the Mariner rootfs initrd as part of CI, and we specify it at test time using an annotation.
2) Again using an annotation, we specify the custom bleeding-edge kernel used by Mariner. This is enabled by setting the `enable_annotations` config in `kata-deploy.sh`.
3) Build Cloud Hypervisor with glibc and the `mshv` feature for Mariner.
Fixes #6840.
> tests: Enable running k8s tests on Mariner

- tests/integration/gha-run.sh
The cluster cleanup step will sometimes fail to run, meaning the next run would fail in the cluster creation step. This PR addresses that.
Example: https://github.com/kata-containers/kata-containers/actions/runs/5349582743/jobs/9867845852
Fixes: #7242
> gha: k8s: Ensure cluster doesn't exist before creating it

- .github/workflows/ci-nightly.yaml
- .github/workflows/payload-after-push.yaml
The latter workflow is breaking as it doesn't recognise ${GITHUB_REF}, the former would most likely break as well, but it didn't get triggered yet.
The error we're facing is:
```
Determining the checkout info
/usr/bin/git branch --list --remote origin/${GITHUB_REF}
/usr/bin/git tag --list ${GITHUB_REF}
Error: A branch or tag with the name '${GITHUB_REF}' could not be found
```
Fixes: #7247
> gha: ci: Avoid using env also in the ci-nightly and payload-after-push

- tools/packaging/kata-deploy-cc/scripts/kata-deploy.sh
Remove the logic that made the kata-remote containerd config not support io.katacontainers annotations
Fixes: #7265
> kata-deploy: Remove remote annotation logic

- .github/workflows/ci-on-push.yaml
On cc3993d860339f4fcf669429a9e5948755dfaa75 we introduced a regression, where we started passing inputs.commit-hash, instead of github.event.pull_request.head.sha. However, we have been setting commit-hash to github.event.pull_request.sha, meaning that we're mssing a `.head.` there.
github.event.pull_request.sha is empty for the pull_request_target event, leading the CI to pull the content from `main` instead of the content from the PR.
Fixes: #7247
> gha: ci: Fix refernce passed to checkout@v3

- src/agent/rustjail/src/process.rs
- src/agent/src/rpc.rs
- src/runtime-rs/crates/hypervisor/src/dragonball/inner.rs
- tests/integration/kubernetes/k8s-number-cpus.bats
- tests/integration/kubernetes/k8s-oom.bats
Let's take the same approach of the go runtime, instead, and allocate
the maximum allowed number of vcpus instead.
Fixes: #7270
> dragonball: Don't fail if a request asks for more CPUs than allowed

- .github/workflows/ci-nightly.yaml
- .github/workflows/payload-after-push.yaml
As we need to pass down the commit sha to the jobs that will be
triggered from the `push` / 'schedule' events, we must be careful
on what exactly we're using there.
At first we were using ${{ github.ref }}, but this turns out to be the
**branch name**, rather than the commit hash.  In order to actually get
the commit hash, Let's use ${{ github.sha }} instead.
Fixes: #7247
> gha: ci: Use github.sha to get the last commit reference

- README.md
This will help folks to monitor the history of the failing tests, as we've done in Jenkins with the "Green Effort CI".
Fixes: #7279
> README: Add badge for our Nightly CI

- .github/workflows/ci-nightly.yaml
---
gha: nightly: Fix name size limit for AKS
Passing the commit hash as the "pr-number" has shown problematic as it
would make the AKS cluster name longer than what's accepted by AKS.
One easy way to solve this is just passing "nightly" as the PR number,
as that's only used to create the cluster.
Fixes: #7247
---
gha: nightly: Also use `workflow_dispatch` to trigger it
This is a very nice suggestion from Steve Horsman, as with that we can
manually trigger the workflow anytime we need to test it, instead of
waiting for a full day for it to be retriggered via the `schedule`
event.
---
> gha: nightly: Fix long name of AKS clusters issue and make the CI easier to test

- .github/workflows/PR-wip-checks.yaml
- .github/workflows/add-backport-label.yaml
- .github/workflows/add-issues-to-project.yaml
- .github/workflows/add-pr-sizing-label.yaml
- .github/workflows/auto-backport.yaml
- .github/workflows/cargo-deny-runner.yaml
- .github/workflows/ci-nightly.yaml
- .github/workflows/ci-on-push.yaml
- .github/workflows/commit-message-check.yaml
- .github/workflows/darwin-tests.yaml
- .github/workflows/payload-after-push.yaml
- .github/workflows/release.yaml
- .github/workflows/require-pr-porting-labels.yaml
- .github/workflows/static-checks-dragonball.yaml
- .github/workflows/static-checks.yaml
Let's make sure we cancel previous runs, mainly as we have some of those that take a lot of time to run, whenever the PR is updated.
This is based on the following stack overflow suggestion: https://stackoverflow.com/questions/66335225/how-to-cancel-previous-runs-in-the-pr-when-you-push-new-commitsupdate-the-curre
Fixes: #7298
> gha: Cancel previous jobs if a PR is updated

- tests/metrics/density/memory_usage.sh
This PR updates memory usage script by applying the clean_env_ctr at the main in order to avoid failures of leaving certain processes not removed.
Fixes #7302
> metrics: Update memory usage script

- .github/workflows/ci.yaml
TDX tests need to be temporarily disabled as the current machine allocated for this will be off for some time, and a new machine only will be added next week.
Fixes: #7307
> gha: k8s: tdx: Temporarily disable TDX tests

- src/runtime-rs/crates/resource/src/network/network_with_netns.rs
Skip to scan network from netns if the network model is specified to "none".
Fixes: #7305
> runtime-rs: Do not scan network if network model is "none"

- tests/integration/kubernetes/setup.sh
- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
- versions.yaml
Currently a mixture of cbl-mariner and mariner is used when creating the mariner initrd. The kata-static tarball has mariner in the name, but the jenkins url uses cbl-mariner. This breaks cache usage.
Use mariner as the target name throughout the build, so that caching works.
Fixes: #7292
> tools: Use a consistent target name when building mariner initrd

- src/agent/Cargo.lock
- src/agent/Cargo.toml
- versions.yaml
Update Attestation-Agent and  image-rs version. They are needed to fix the CI error. Refer to https://github.com/confidential-containers/kbs/issues/124
Fixes: #7285
> CCv0 | Update guest components dependency version

- tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
- tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
- tests/metrics/density/memory_usage_inside_container.sh
- tests/metrics/gha-run.sh
This PR will enable the memory inside container metrics for the Kata CI.
Fixes #7254
> metrics: Enable memory inside container metrics

- .github/workflows/ci.yaml
- .github/workflows/run-cri-containerd-tests.yaml
- tests/common.bash
- tests/integration/cri-containerd/gha-run.sh
- tests/metrics/gha-run.sh
---
tests: Add `function` before each function
Let's just keep this standardised.
---
tests: common: Move a few utility functions to common.bash
Those functions were originally introduced as part of the
`metrics/gha-run.sh` file, but those will be very hand at the time we
start adding more tests.
---
gha: ci: Add cri-containerd tests skeleton
This PR builds the foundation for us to start migrating the
cri-containerd tests from Jenkins to GitHub Actions.
Right now the test does nothing and should always finish successfully.
The coming PRs will actually introduce logic to the `gha-run.sh` script
where we'll be able to run the tests and make sure those pass before
having them actually merged.
Fixes: #6543 
---
> tests: gha: ci: Add cri-containerd tests skeleton

- .github/workflows/run-cri-containerd-tests.yaml
- tests/integration/cri-containerd/gha-run.sh
- versions.yaml
---
ci: cri-containerd: Ensure deps are installed
Let's make sure we install the needed dependencies for running the
`cri-containerd` tests.
---
ci: cri-containerd: Export GOPATH
Let's make sure this is exported, as it'll be needed in order to install
`yq`, which will be used to get the versions of the dependencies to be
installed.
---
ci: cri-containerd: Add LTS / Active versions for containerd
As we'll be testing against the LTS and the Active versions of
containers, let's add those entries to the versions.yaml file and make
sure we export what we want to use for the tests as an env var.
The approach taken should not break the current way of getting the
containerd version.
LTS and Active versions of containerd can be found at:
https://containerd.io/releases/#support-horizon
Fixes: #6543 …
> gha: ci: Add cri-containerd tests skeleton -- follow up 1

- tests/metrics/README.md
- tests/metrics/storage/README.md
This PR adds the metrics storage documentation related with the blogbench performance test as well as a link to the general metrics README.
> tests: Add metrics storage documentation

- tests/metrics/lib/common.bash
This PR adds function before the function name in common.bash script in order to have uniformity across all the script.
Fixes #7327
> tests: Add function before function name in common.bash for metrics

- src/agent/Cargo.lock
- src/libs/Cargo.lock
- src/libs/kata-sys-util/Cargo.toml
- src/libs/kata-sys-util/src/cpu.rs
- src/libs/kata-sys-util/src/lib.rs
- src/libs/kata-sys-util/src/protection.rs
- src/tools/kata-ctl/Cargo.lock
- src/tools/kata-ctl/Cargo.toml
- src/tools/kata-ctl/src/arch/aarch64/mod.rs
- src/tools/kata-ctl/src/arch/powerpc64le/mod.rs
- src/tools/kata-ctl/src/arch/s390x/mod.rs
- src/tools/kata-ctl/src/arch/x86_64/mod.rs
- src/tools/kata-ctl/src/check.rs
- src/tools/kata-ctl/src/ops/env_ops.rs
- src/tools/kata-ctl/src/utils.rs
Move the GuestProtection code in kata-ctl to the src/libs/kata-sys-util crate to allow it to be consumed by other components.
Fixes: #7144
This is wip as it depends on https://github.com/kata-containers/kata-containers/pull/6726. This PR includes a commit from PR 6726 to make this work in order to make use of cpu utilities from kata-sys-util.
> kata-ctl: Move GuestProtection code to kata-sys-util

- src/libs/kata-sys-util/src/mount.rs
- src/runtime-rs/crates/hypervisor/src/dragonball/inner.rs
- src/runtime-rs/crates/resource/src/share_fs/sandbox_bind_mounts.rs
- src/runtime-rs/crates/resource/src/share_fs/share_virtio_fs.rs
- src/runtime-rs/crates/resource/src/share_fs/utils.rs
Add an extra parameter in `bind_mount_unchecked` to specify the propagation type: "shared" or "slave".
Fixes: #7017
> runtime-rs: add parameter for propagation of (u)mount events

- tests/integration/gha-run.sh
- tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml
- tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
- tools/packaging/kata-deploy/scripts/kata-deploy.sh
---
kata-deploy: Give users the ability to run it on DEBUG mode
The DEBUG env var introduced to the kata-deploy / kata-cleanup yaml file
will be responsible for:
* Setting up the CRI Engine to run with the debug log level set to debug
* The default is usually info
* Setting up Kata Containers to enable:
* debug logs
* debug console
* agent logs
This will help a lot folks trying to debug Kata Containers while using
kata-deploy, and also help us to always run with DEBUG=yes as part of
our CI.
Fixes: #7342
---
ci: k8s: Enable debug when running the tests
This will help us to gather more information about Kata Containers in
case of failure.
Fixes: #7343
---
> kata-deploy: Add a debug option to kata-deploy (and also use it as part of our CI)

- tests/common.bash
In order to run kata metrics we need to check that the containerd config file is properly set. When this is not the case, we need to remove that file, and generate a valid one.
This PR runs rm -f in order to ignore errors in case the file to delete does not exist.
Fixes: #7336
> metrics: use rm -f to remove the oldest continerd config file.

- tests/metrics/density/memory_usage.sh
- tests/metrics/lib/common.bash
- tests/metrics/lib/json.bash
This PR makes kata-env is called only after some metrics have completed his workload. This fixes a bug that occurs when kata-env was being called before kata is already installed on the testing platform.
Fixes: #7348
> metrics: Stop running kata-env before kata is properly installed.

- src/runtime-rs/crates/resource/src/network/network_info/network_info_from_link.rs
- src/runtime-rs/crates/resource/src/network/network_with_netns.rs
Ignore unconfigured network interfaces like tunl0 when create endpoints.
Fixes: #7020
> runtime-rs: ignore unconfigured network interfaces

- src/runtime-rs/Cargo.lock
- src/runtime-rs/crates/agent/Cargo.toml
- src/runtime-rs/crates/agent/src/kata/agent.rs
- src/runtime-rs/crates/agent/src/kata/mod.rs
- src/runtime-rs/crates/hypervisor/Cargo.toml
- src/runtime-rs/crates/hypervisor/src/dragonball/mod.rs
- src/runtime-rs/crates/resource/Cargo.toml
- src/runtime-rs/crates/resource/src/manager.rs
- src/runtime-rs/crates/runtimes/Cargo.toml
- src/runtime-rs/crates/runtimes/common/src/sandbox.rs
- src/runtime-rs/crates/runtimes/src/lib.rs
- src/runtime-rs/crates/runtimes/src/manager.rs
- src/runtime-rs/crates/runtimes/src/tracer.rs
- src/runtime-rs/crates/runtimes/virt_container/Cargo.toml
- src/runtime-rs/crates/runtimes/virt_container/src/container_manager/manager.rs
- src/runtime-rs/crates/runtimes/virt_container/src/lib.rs
- src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
- src/runtime-rs/crates/service/Cargo.toml
- src/runtime-rs/crates/service/src/manager.rs
- src/runtime-rs/crates/shim/Cargo.toml
- src/runtime-rs/crates/shim/src/bin/main.rs
- src/runtime-rs/crates/shim/src/shim.rs
1. Instrumenting currently only on major booting process, i.e. before sandbox creation to container creation finished
* all instrumenting spans are child spans of a long running rootspan
* tracer.rs supports spans without guard entering and exiting at any place, this supports the long running rootspan
2. Add some debug trait implementation (maybe not complete) since #[instrument] needs this, and skip instrumenting the parameters is not a good choice.
3. there is one thing `TODO`, some crates, `e.g. hyper`, uses tracing and send traces to jaeger, we may offer an option to filter the traces from other crates
> feat(Tracing): tracing in Rust runtime

- src/libs/Cargo.lock
- src/runtime-rs/crates/hypervisor/src/device/device_manager.rs
- src/runtime-rs/crates/hypervisor/src/device/driver/virtio_net.rs
- src/runtime-rs/crates/hypervisor/src/dragonball/inner_device.rs
- src/runtime-rs/crates/resource/src/manager_inner.rs
- src/runtime-rs/crates/resource/src/network/endpoint/endpoints_test.rs
- src/runtime-rs/crates/resource/src/network/endpoint/ipvlan_endpoint.rs
- src/runtime-rs/crates/resource/src/network/endpoint/macvlan_endpoint.rs
- src/runtime-rs/crates/resource/src/network/endpoint/mod.rs
- src/runtime-rs/crates/resource/src/network/endpoint/physical_endpoint.rs
- src/runtime-rs/crates/resource/src/network/endpoint/veth_endpoint.rs
- src/runtime-rs/crates/resource/src/network/endpoint/vlan_endpoint.rs
- src/runtime-rs/crates/resource/src/network/mod.rs
- src/runtime-rs/crates/resource/src/network/network_pair.rs
- src/runtime-rs/crates/resource/src/network/network_with_netns.rs
Currently the network endpoints are alone out of device manager, we should include them into the device manager for management.
If so, refactoring network endpoints' implementation is needed.
First, restruct NetworkConfig and NetworkDevice structures; Second, do implementation for virtio-net driver and add Network device into Device Manager;
Third, unified the entry with do_handle_device for each endpoint;
Fixes: #7215
> runtime-rs: enhancement of Device Manager for network endpoints.

- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
DEFSERVICEOFFLOAD controls whether images are pulled inside the guest. This should always be set for CoCo, not just when we use MEASURED_ROOTFS.
Fixes: #7350
> local-build: always use DEFSERVICEOFFLOAD for CoCo

- tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
- tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
This PR uses squared brackets in a jq expression to access key values corresponding to metric results in json format.
The values are the data inputs into the checkmetrics tool.
Fixes: #7319
> metrics: replace backslashes used to escape double quoted jq key expr.

- .github/workflows/ci.yaml
Now that we have a new TDX machine plugged into our CI, let's re-enable the TDX tests.
Fixes: #7368
> ci: k8s: Bring TDX tests back

- src/agent/Cargo.lock
- src/agent/Cargo.toml
- src/agent/src/mount.rs
Using an initrd and setting KATA_INIT=yes meaning we're using the kata-agent as the init process we need to make sure that the agent is not segfaulting if mounts  already happened.
Some workloads need to configure several things in the initrd before the kata-agent starts which involves having /proc or /sys already mounted.
Add functionality to ignore already mounted devs/fs/pseudo-fs.
Fixes: #6992
> agent: Ignore already mounted dev/fs/pseudo-fs

- src/agent/rustjail/src/process.rs
- src/agent/src/rpc.rs
Issue #4747 and pull request #4748 fix exec hang issues where the exec command hangs when a process's stdout is not closed. However, the PR might cause the exec command not to work as expected, leading to CI failure. The PR was reverted in #7042. This PR resolves the exec hang issues and has undergone 1000 rounds of testing to verify that it would not cause any CI failures.
Fixes: #4747
Signed-off-by: Xuewei Niu <niuxuewei.nxw@antgroup.com>
> agent: Fix exec hang issues with a backgroud process

- tests/common.bash
- tests/metrics/lib/common.bash
- tests/metrics/storage/blogbench.sh
This PR kills the hypervisor and the kata shim in the init_env stage prior to launch any metric test.
Additionally this PR adds info messages in the main blocks of the blogbench test to help in debugging.
> metrics: stop hypervirsor and shim at init_env stage

- versions.yaml
https://gitlab.com/virtio-fs/virtiofsd/-/releases/v1.7.0 was released Today.
Fixes: #7371
> versions: Bump virtiofsd to v1.7.0

- tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
- tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
This reverts commit 468f017e2183c45b7cec44c14ff4b7ad2f4a4c6d.
Fixes: #7385
> Revert "metrics: Replace backslashes used to escape double quoted key in jq expr"

- tests/metrics/density/memory_usage_inside_container.sh
This PR adds function before function of the variables at the memory inside container script in order to have uniformity across the script.
Fixes #7386
> metrics: Add function to memory inside container script

- .github/workflows/cc-payload-after-push.yaml
Allow triggering this action manually, since we noticed it being skipped on push exactly when we needed it the most.
> gha: ci: cc-payload-after-push: Add workflow_dispatch trigger

- .github/workflows/run-metrics.yaml
- tests/metrics/gha-run.sh
This PR adds the function and option to run TensorFlow benchmark on the gha for the kata metrics CI.
> metrics: enable TensorFlow benchmark to be run on gha

- .github/workflows/build-kata-static-tarball-amd64.yaml
- .github/workflows/build-kata-static-tarball-arm64.yaml
- .github/workflows/build-kata-static-tarball-s390x.yaml
- .github/workflows/release.yaml
- tools/packaging/kata-deploy/local-build/Makefile
- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
- tools/packaging/kata-deploy/local-build/kata-deploy-merge-builds.sh
- versions.yaml
Let's make things simpler to figure out which version of Kata
Containers has been deployed, and also which artefacts come with it.
This will help us immensely in the future, for the TEEs use case, so we
can easily know whether we can deploy a specific guest kernel for a
specific host kernel.
> kata-deploy: Add VERSION and versions.yaml to the final tarball

- tools/packaging/kata-deploy/local-build/kata-deploy-merge-builds.sh
We need to correctly get the full path of the versions.yaml file as part of the merge-builds.sh script, as we do a `pushd` there and that leads to a fail merging the artefacts as the `versions.yaml` file does not exists in that path.
Fixes: #7405
> kata-deploy: Properly get the path of the versions.yaml file

- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
- tools/packaging/static-build/cache_components_main.sh
Any change in the script used to build the kernel should invalidate the cache.
Fixes: #7403
> cache: kernel: Consider changes in tools/packaging/kernel

- Makefile
- README.md
- tests/integration/kubernetes/gha-run.sh
- tools/packaging/kata-debug/Dockerfile
- tools/packaging/kata-debug/README.md
- tools/packaging/kata-debug/debug.sh
- tools/packaging/kata-debug/kata-debug-build-and-upload-payload.sh
kata-debug is a tool that is used as part of the Kata Containers CI to gather
information from the node, in order to help debugging issues with Kata
Containers.
As one can imagine, this can be expanded and used outside of the CI context,
and any contribution back to the script is very much welcome.
The resulting container is stored at the [Kata Containers quay.io
space](https://quay.io/repository/kata-containers/kata-debug) and can
be used as shown below:
```sh
kubectl debug $NODE_NAME -it --image=quay.io/kata-containers/kata-debug:latest
```
> packaging/tools: Add kata-debug and use it as part of our CI

- .github/workflows/cc-payload-s390x.yaml
The measured_boot matrix parameter should be a list.
Fixes ##7400
> workflows: fix malformed CC payload s390x yaml

- .github/workflows/ci.yaml
- .github/workflows/run-nydus-tests.yaml
- tests/integration/nydus/gha-run.sh
- tests/integration/nydus/nydus-container.yaml
- tests/integration/nydus/nydus-sandbox.yaml
- tests/integration/nydus/nydus_tests.sh
- tests/integration/nydus/nydusd-config.json
Let's move all the nydus content from the `tests`  repo to our GHA, and create a no-op test for those.
The tests right now are being triggered but not being executed, and a different PR doing clean-ups and enabling the tests will be raised, as this one is basically a placeholder that must get in first.
There's no need to add the `ok-to-test` label as changes in the yaml file for the ci related workflows won't be triggered.
> gha: ci: Add no-op nydus tests to our CI

- tests/integration/nydus/gha-run.sh
We should source from `nydus_dir`, instead of `cri_containerd_dir`, and that was a leftover from fb4f7a002cf40d073868278eb59ba92a7f9514e0.
Fixes: #6543
> ci: nydus: Fix typo in "source"

- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
`module_dir` has been passed to the function but was never assigned to a var, leading to errors when trying to use it.
Fixes: #7416
> kata-deploy-binaries: kernel_cache: Take module_dir into account

- tools/packaging/release/release-notes.sh
This is a small step towards build reproducibility.
Fixes: #7412
> release: Mention the container images used to build the project

- tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml
- tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
- tools/packaging/kata-deploy/scripts/kata-deploy.sh
Instead of hardcoding shims as part of the script, let's ensure we can allow them to be created based on environment variables passed to the daemonset.
This change brings no functionality change as the default values in the daemonset are exactly what has been used as part of the scripts.
Fixes: #7407
> kata-deploy: Allow shim creation based on what's passed to the daemonset

- src/tools/runk/README.md
`runk` can launch containers using Docker, so add the guide to it's README.
```sh
$ sudo dockerd --experimental --add-runtime="runk=/usr/local/bin/runk"
$ sudo docker run -it --rm --runtime runk busybox echo hello runk
hello runk
```
Fixes: #7431
> runk: Add Docker guide to README

- tools/packaging/static-build/cache_components_main.sh
Kernel caching got broken for various configs by mismatched commits in the version string. SEV had additional breakage because the two cache assets used different version strings altogether. Fix both issues.
> cache: kernel: Fix kernel caching

- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
As CCv0 and main branches have the different versions of the TDX components, we need to adjust the URL where we're getting the cached artefacts from.
> CC | Adjust cache URL for TDX components

- src/agent/src/mount.rs
currently when fsGroup is used with direct-assign, kata agent recursively changes ownership and permission for each file including symlinks. However the problem with symlinks is, the permission of the symlink itself may not be same as the underlying file. So while doing recursive ownership and permission changes we should skip symlinks.
Fixes: #7364
> agent: exclude symlinks from recursive ownership change

- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
We're re-enabling a bunch of other cached targets, mostly related to the rootfs, as those have been re-built using the correct `/opt/kata` prefix.
> CC| cc: cache: Enable more cached components back and ensure shim-v2 can be properly cached

- tools/packaging/guest-image/build_se_image.sh
This is to change a prefix from `confidential-containers` to `kata` for IBM SE image build.
Fixes: #7444
> CCv0: fix a prefix to kata for IBM SE image build

- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Now that the shim-v2 for CCv0 has been rebuilt with the correct path, let's re-enable the cache.
Fixes: #7422
> cc: cache: shim-v2: Re-enable cached artefact

- src/runtime-rs/crates/resource/src/cpu_mem/initial_size.rs
- src/runtime-rs/crates/resource/src/volume/spdk_volume.rs
- src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs
These unneeded 'mut' keywords blocks built by rust 1.71.0. Remove them.
Fixes: #7424
> runtime-rs: remove unneeded 'mut' keywords

- src/agent/src/signal.rs
- src/libs/kata-types/src/annotations/mod.rs
Remove unused `mut` because the agent compilation fails when the rust compiler is >= 1.71. This is related to #7425
Fixes: #7438
> agent,libs: Remove unused 'mut' keywords

- .github/workflows/run-k8s-tests-on-aks.yaml
- tests/integration/kubernetes/gha-run.sh
**tests: k8s: Clean up node debuggers after running**
This deletes node debugger pods after execution since their presence may
affect tests that assume only test workloads pods are present.
For example, in `k8s-job` we wait for *any* pod to be in the `Succeeded`
state before proceeding, which causes failures.
Fixes: https://github.com/kata-containers/kata-containers/issues/7452
---
**tests: gha: Add timeout to cluster creation**
This has been intermittently taking a while lately so let's add a
timeout.
> tests: Fix `k8s-job` test

- .github/workflows/static-checks-dragonball.yaml
Static checks for dragonball are landing on any of the self-hosted runners, and the reason for that is because "self-hosted" was the label selector used.
Let's use "dragonball" instead, as the machine has that label as well.
Fixes: #7464
> gha: dragonball: Run only on the dragonball labeled machine

- tools/packaging/kata-deploy/scripts/kata-deploy.sh
This is another piece that got dropped as part of
6f552b010c51eb9e6dbcbb21cfa122f5c8d6ad36 and is causing regressions on the operator tests.
Fixes: #7422
This doesn't require the tests to run, as this script is only tested as part of the Operator CI.
> CC | kata-deploy: Add the runtime-classes that are not yet on main

- tools/packaging/kata-deploy/scripts/kata-deploy.sh
On main we will not have this problem as we can easily configure which
shims will be installed according to an environment variable passed to
the kata-deploy.yaml file.
However, on CCV0, at least for now, we better keep the list of shims
separated by architecture, as we've found out that s390x CoCo Operator
CI is breaking because we try to install a shim that's not even built
for that architecture (dragonball).
> CC | kata-deploy: Use different shim arrays for different arches

- tools/packaging/kata-deploy/scripts/kata-deploy.sh
We were doing "if - else  if - else", while bash expects "if - elif - else", and that should never have happened in the first place, but it happend as part of b8b73939ea98086e1359f5cb4d5a71d940e960dc
Fixes: #7422
Again, no tests are needed to run as it will only be tested on the operator side.
> kata-deploy: Fix if-elif-else-statement

- tools/packaging/kata-deploy/scripts/kata-deploy.sh
In order to do so, we need the `()` around the `shim_{arch}`.
Fixes: #7422
> kata-deploy: We need shim to an array, not a string

- tests/integration/kubernetes/k8s-file-volume.bats
- tests/integration/kubernetes/k8s-volume.bats
- tests/integration/kubernetes/run_kubernetes_tests.sh
- tests/integration/kubernetes/runtimeclass_workloads/pv-pod.yaml
- tests/integration/kubernetes/runtimeclass_workloads/pv-volume.yaml
- tests/integration/kubernetes/runtimeclass_workloads/volume-claim.yaml
- tests/integration/kubernetes/tests_common.sh
This imports the following tests from the tests repo and modifies them slightly to set up volumes on the AKS host to make volume tests work with our GitHub Actions CI.
* `k8s-volume`
* `k8s-file-volume`
The flow of each test is preserved and the bats file were only slightly edited to allow running commands on the host (grep for `exec_host`).
See draft PRs for the remaining tests (issues to debug): https://github.com/kata-containers/kata-containers/pull/7476 https://github.com/kata-containers/kata-containers/pull/7165
Fixes: #6566
> tests: Add `k8s-volume` and `k8s-file-volume` tests to GHA CI

- .github/workflows/build-kata-static-tarball-amd64.yaml
- .github/workflows/release-amd64.yaml
- .github/workflows/release-arm64.yaml
- .github/workflows/release-s390x.yaml
Otherwise we'll face the following error as part of our GHA:
```
The workflow is not valid.
kata-containers/kata-containers/.github/workflows/release-$foo.yaml
(Line: 13, Col: 14): Invalid input, stage is not defined in the
referenced workflow.
```
Fixes: #7497
NOTE: I'm adding the `force-skip-ci` label as the changes here are only touching the yaml file used for the release, and it can only be tested after being merged.  Running the tests here would be a waste of resource, and they would **NOT** test anything related to this PR.
> gha: release: `stage` must be a string

- .github/workflows/run-k8s-tests-on-aks.yaml
- .github/workflows/run-k8s-tests-on-sev.yaml
- .github/workflows/run-k8s-tests-on-snp.yaml
- .github/workflows/run-k8s-tests-on-tdx.yaml
Let's make sure we can rely on the tests passing down whether they want to be tested using Node Feataure Discovery or not.
Right now, only the TDX job has this option set to "true", all the other jobs have this option set to "false".
We can and have to merge this one before merging the NFD related patches as:
1) It causes no harm in exporting this environment variable, but not
having it used
2) It will allow us to test the NFD after this one is merged, as changes
in the yaml file, in the case of the pull_request_target event,  are
not taken into consideration before they're merged
Fixes: #7495
> k8s: Rely on the USING_NFD environment variable passed by the jobs

- docs/design/architecture/kubernetes.md
The links for pods and kubelets no longer work so update to new links with relevant info.
Fixes #7487
> docs: Update links for pods and kubelet

- .github/workflows/build-kata-static-tarball-amd64.yaml
- .github/workflows/build-kata-static-tarball-arm64.yaml
- .github/workflows/build-kata-static-tarball-s390x.yaml
- .github/workflows/release-amd64.yaml
- .github/workflows/release-arm64.yaml
- .github/workflows/release-s390x.yaml
`stage`  has been added, but only hooked up to the amd64 logic, leaving
arm64 and s390x behind.
Let's fix this right now, and make sure no error occurs when passing
this down to the yaml files.
Fixes: #7497
> gha: release: `stage` must be defined for arm64 / s390x yamls

- tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
- tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
- tests/metrics/gha-run.sh
- tests/metrics/machine_learning/tensorflow.sh
This PR enables the Tensorflow benchmark metrics for kata CI.
Fixes #7395
> metrics: Enable Tensorflow metrics for kata CI

- .github/workflows/release.yaml
This requires the GITHUB_UPLOAD_TOKEN.  While we're here, let's also fix the name of the action and remove the "-tarball" suffix, as it's not really a tarball.
Fixes: #7497
> release: Fix upload-versions-yaml

- tools/packaging/release/release-notes.sh
diferent -> different
And also let's make sure we escape the backticks around the kata-deploy
environment variables, otherwise bash will try to interpret those.
Fixes: #7497
> release: release-note.sh: Fix typos and reference to images

- src/tools/kata-ctl/Cargo.lock
- src/tools/kata-ctl/Cargo.toml
- src/tools/kata-ctl/src/args.rs
- src/tools/kata-ctl/src/main.rs
- src/tools/kata-ctl/src/monitor/http_server.rs
- src/tools/kata-ctl/src/monitor/metrics.rs
- src/tools/kata-ctl/src/monitor/mod.rs
- src/tools/kata-ctl/src/ops/check_ops.rs
- src/tools/kata-ctl/src/ops/exec_ops.rs
- src/tools/kata-ctl/src/ops/volume_ops.rs
- src/tools/kata-ctl/src/utils.rs
The previous kata-monitor in golang could not communicate with runtime-rs to gather metrics due to different sandbox addresses as we discussed in https://github.com/kata-containers/kata-containers/pull/5643. This PR adds the subcommand monitor in kata-ctl to gather metrics from runtime-rs and monitor itself.
Fixes: #5017
Note: This PR and https://github.com/kata-containers/kata-containers/pull/5797 jointly completed the function of obtaining the metrics of runtime-rs or Kata 3.0, where this PR is responsible for establishing an http server to handle requests, and https://github.com/kata-containers/kata-containers/pull/5797 is responsible for collecting within runtime-rs.
> kata-ctl: add monitor subcommand for runtime-rs

- tests/integration/kubernetes/gha-run.sh
Otherwise the VM deletion may not delete, leaving us with several machines behind.
Fixes: #7509
> ci: k8s: Do not fail when gathering info on AKS nodes

- .github/workflows/ci-on-push.yaml
As we only support one stable branch, it'll be used as part of the stable-3.2 and onwards.
Fixes: #7518
> ci-on-push: Make the CI also run for the stable-* branches

- src/runtime/virtcontainers/container.go
- src/runtime/virtcontainers/sandbox.go
If modeVFIO is enabled we need 1st to attach the VFIO control group device `/dev/vfio/vfio` an 2nd the actuall device(s) afterwards. Sort the devices starting with device #1 being the VFIO control group device and the next the actuall device(s)
`/dev/vfio/<group>`
Fixes: #7493
> vfio: Fix vfio device ordering

- tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup-stable.yaml
- tools/packaging/kata-deploy/kata-deploy/base/kata-deploy-stable.yaml
As 3.2.0-rc0 has been released, let's switch the kata-deploy / kata-cleanup
tags back to "latest", and re-add the kata-deploy-stable and the
kata-cleanup-stable files.
Only merge this commit after 3.2.0-rc0 release is successfully tagged!
> release: Revert kata-deploy changes after 3.2.0-rc0 release

- tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml
- tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
- tools/packaging/kata-deploy/scripts/kata-deploy.sh
when interacting with systemd. We have occasionally faced issues with compatibility between the systemctl version used inside the kata-deploy container and the systemd version on the host. Instead of using a containerized systemctl with bind mounted sockets, nsenter the host and run systemctl from there. This provides less coupling between the kata-deploy container and the host.
Fixes: #7511
> kata-deploy: Use host's systemctl

- src/dragonball/Cargo.toml
Version 0.10.5, which was just released, breaks `nydus-storage`.
This is a workaround to fix the CI which is blocking other PRs.
Fixes: #7541
> Use version 0.10.4 of `fuse-backend-rs`

- src/agent/src/mount.rs
- src/agent/src/rpc.rs
- src/runtime/pkg/containerd-shim-v2/create.go
- src/runtime/pkg/device/config/config.go
- src/runtime/pkg/device/manager/manager.go
- src/runtime/pkg/govmm/qemu/qmp.go
- src/runtime/virtcontainers/container.go
- src/runtime/virtcontainers/fs_share_linux.go
- src/runtime/virtcontainers/kata_agent.go
- src/runtime/virtcontainers/mount.go
- src/runtime/virtcontainers/pkg/annotations/annotations.go
These are the changes in the kata runtime and agent that enable pulling images on the host and exposing layers as block devices to the VM, which are then mounted and overlayed to produce the final image. This layering allows sharing by containers with common layers, which is a desirable to reduce the memory footprint (and similar to what the overlay snapshotter does on the host). There is no dependency on image-rs.
The changes here are independent of which file system is used. Everything is driven by mount options, which can be used with any file system and snapshotter. (I believe this preferred over hard-coding file system names and functions in generic kata code.)
We have a reference snapshotter (tardev) that uses tarfs as the file system -- both are available here: …
> Image pulling on the host

- src/agent/src/mount.rs
- src/agent/src/rpc.rs
These calls cause two extra atomic instructions each time they're used, one to increment and another one to decrement the refcount.
Since we don't need them because the referred value is guaranteed to outlive the function, remove the calls.
Fixes: #7190
> agent: avoid unnecessary calls to `Arc::clone`

- docs/design/architecture/kubernetes.md
- docs/how-to/how-to-use-k8s-with-containerd-and-kata.md
- docs/how-to/run-kata-with-k8s.md
- docs/install/minikube-installation-guide.md
Replace `master` with `control-plane` in the context of K8s because `master` is a legacy term and haven't been used any more.
Ref. https://github.com/kubernetes/enhancements/tree/master/keps/sig-cluster-lifecycle/kubeadm/2067-rename-master-label-taint
Fixes: #7466
> docs: Use control-plane term instead of master

- tools/packaging/kata-deploy/runtimeclasses/kata-clh-tdx.yaml
- tools/packaging/kata-deploy/runtimeclasses/kata-qemu-se.yaml
- tools/packaging/kata-deploy/runtimeclasses/kata-remote.yaml
- tools/packaging/kata-deploy/runtimeclasses/kata-runtimeClasses.yaml
As the operator will be delegating the runtimeclass creation to the kata-deploy daemonset, let's add here the missing runtime classes that are not yet on main:
* kata-clh-tdx
* kata-qemu-se
* kata-remote
> CC | Add missing runtime classes

- src/dragonball/Cargo.toml
> 3.2 backport | dragonball: use version 0.10.4 of `fuse-backend-rs`

- src/libs/kata-types/src/config/runtime.rs
- src/runtime-rs/Makefile
- src/runtime-rs/config/configuration-dragonball.toml.in
- src/runtime-rs/crates/hypervisor/src/device/driver/virtio_net.rs
- src/runtime-rs/crates/hypervisor/src/dragonball/inner_device.rs
- src/runtime-rs/crates/resource/src/network/dan.rs
- src/runtime-rs/crates/resource/src/network/endpoint/endpoint_persist.rs
- src/runtime-rs/crates/resource/src/network/endpoint/mod.rs
- src/runtime-rs/crates/resource/src/network/endpoint/tap_endpoint.rs
- src/runtime-rs/crates/resource/src/network/mod.rs
- src/runtime-rs/crates/resource/src/network/network_info/mod.rs
- src/runtime-rs/crates/resource/src/network/network_info/network_info_from_dan.rs
- src/runtime-rs/crates/resource/src/network/utils/address.rs
- src/runtime-rs/crates/resource/src/network/utils/mod.rs
- src/runtime-rs/crates/runtimes/src/manager.rs
- src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
Kata containers as VM-based containers are allowed to run in the host netns. That is, the network is able to isolate in the L2. The network performance will benefit from this architecture, which eliminates as many hops as possible. We called it a Directly Attachable Network (DAN for short).
The network devices are placed at the host netns by the CNI plugins. The configs are saved at {dan_conf}/{sandbox_id}.json in the format of JSON, including device name, type, and network info. At the very beginning stage, the DAN only supports host tap devices. More devices, like the DPDK, will be supported in later versions.
The format of file looks like as below:
```json
{
"netns": "/path/to/netns",
"devices": [{
"name": "eth0",
"guest_mac": "xx:xx:xx:xx:xx",
"device": {
"type": "vhost-user",
"path": …
```
> runtime-rs: Introduce directly attachable network

- src/dragonball/Cargo.toml
- src/dragonball/src/api/v1/vmm_action.rs
- src/dragonball/src/dbs_address_space/Cargo.toml
- src/dragonball/src/dbs_arch/Cargo.toml
- src/dragonball/src/dbs_boot/Cargo.toml
- src/dragonball/src/dbs_virtio_devices/Cargo.toml
- src/dragonball/src/device_manager/mod.rs
- src/dragonball/src/test_utils.rs
- src/dragonball/src/vm/kernel_config.rs
- src/dragonball/src/vm/mod.rs
- src/runtime-rs/Cargo.lock
This pull request is mainly for updating vm-memory and vmm-sys-util.
The affacted crates include:
- vm-memory: from 0.9.0 to 0.10.0
- vmm-sys-util: from 0.10.0 to 0.11.0
- virtio-queue: from 0.6.0 to 0.7.0
- fuse-backend-rs: from 0.10.4 to 0.10.5
- linux-loader: from 0.6.0 to 0.8.0
- nydus-api: from 0.3.0 to 0.3.1
- nydus-rafs: from 0.3.1 to 0.3.2
- nydus-storage: from 0.6.3 to 0.6.4
Fixes: #0000
> deps: Bump dependent crate versions

- tests/integration/kubernetes/gha-run.sh
Instead of using package manager to install bats, building this from source. This gives us the updated version of bats which supports functions such as setup_file and
teardown_file.
We can use these functions into our current tests.
Fixes: #7597
> tests: upgrade bats version

- tests/integration/kubernetes/gha-run.sh
- tests/integration/kubernetes/kata-deploy-ensure-runtimec-classes-created.bats
- tests/integration/kubernetes/run_kubernetes_tests.sh
- tests/integration/kubernetes/setup.sh
---
k8s: tests: Take advantage of `SHIMS` and `DEFAULT_SHIM` env vars
We don't have to do any sed to replace the runtimeclass being used by
the moment we start taking advantage of the `DEFAULT_SHIM` environment
variable exposed merged in the previous commits.
---
tests: k8s: Ensure the runtime classes are properly created
With these 2 simple checks we can ensure that we do not regress on the
behaviour of allowing the runtime classes / default runtime class to be
created by the kata-deploy payload.
---
> kata-deploy: Ensure we cover SHIMS / DEFAULT_SHIM as part of our tests

- .github/workflows/ci.yaml
Following the example on https://github.com/docker/build-push-action, it's clear that the actions to "Set up QEMU" and "Set up Docker Buildx" are missing.
Let's add them, and also take the advantage to bump the build-push-action to its v4, which, by the way, had a typo on its name (build-and-push-action does **NOT** exist, build-push-action does).
Fixes: #7595
> ci: create-confidential-image: Add dependent actions

- .github/workflows/ci.yaml
- tests/integration/kubernetes/runtimeclass_workloads/confidential/unencrypted/Dockerfile
The build context should be the folder where the Dockerfile is present,
otherwise the files copied into the image won't be found.
Fixes: #7595
> ci: unencrypted-image: Fix build context

- .github/workflows/run-metrics.yaml
- tests/common.bash
- tests/metrics/gha-run.sh
This PR changes the metrics workflow in order to just install kata once, and run the checks for multiple hypervisor variations.
In this way we save time avoiding installing kata for each hypervisor to be tested.
Fixes: #7578
> metrics: install kata once and run multiple checks

- tests/metrics/network/README.md
- tests/metrics/network/nginx_kubernetes/nginx-network.sh
- tests/metrics/network/nginx_kubernetes/runtimeclass_workloads/nginx-networking.yaml
This PR adds the network nginx benchmark for kata metrics.
Fixes #7605
> metrics: Add network nginx benchmark

- src/dragonball/Cargo.toml
- src/dragonball/src/api/v1/vmm_action.rs
- src/dragonball/src/dbs_address_space/Cargo.toml
- src/dragonball/src/dbs_arch/Cargo.toml
- src/dragonball/src/dbs_boot/Cargo.toml
- src/dragonball/src/dbs_virtio_devices/Cargo.toml
- src/dragonball/src/device_manager/mod.rs
- src/dragonball/src/test_utils.rs
- src/dragonball/src/vm/kernel_config.rs
- src/dragonball/src/vm/mod.rs
- src/runtime-rs/Cargo.lock
- src/runtime/virtcontainers/sandbox.go
- Add support for setting the sandbox name and namespace in the hypervisor config, which is needed in the remote hypervisor implementation to get the pod name and namespace for the remote pod create request
- Also cherry-pick in the nydus version bump to attempt to stop the dragonball errors
Fixes: #7588
> Re-added hypervisor annotations

- src/agent/src/mount.rs
- src/agent/src/network.rs
- src/agent/src/rpc.rs
There are many places where the code currently creates new `Vec` instances when it's not really needed. The result is a perf hit because it allocates memory, copies all elements, then frees the memory; in some cases, copying elements also involves extra allocations (e.g., when elements are strings, or structs containing strings).
This patch addresses a number of these cases.
Fixes: #7203
> agent: avoid creating new `Vec` instances when easily avoidable

- src/agent/src/device.rs
Allow `clippy::redundant_clone` in the agent's unit tests because rustc>=1.70 shows the errors as false-negatives. These `clone()` are required because the following codes refer to the variable, but the clippy analyzes them by mistake, using the conservative and limited approach.
Ref. https://rust-lang.github.io/rust-clippy/master/index.html#/redundant_clone
Fixes: #7534
> agent: Allow clippy::redundant_clone in the unit tests

- .github/workflows/static-checks.yaml
The GHA runners are not exactly powerful, which makes the static-checks take way too long (almost an hour).
Let's give a try and move those to the same size of Azure instances used as part of our CI, and probably have this time reduced.
Fixes: #7446
> gha: static-checks: Move to the Azure instances

- tools/packaging/kata-deploy/README.md
- tools/packaging/kata-deploy/kata-deploy/overlays/k0s/kustomization.yaml
- tools/packaging/kata-deploy/kata-deploy/overlays/k0s/mount_k0s_conf.yaml
- tools/packaging/kata-deploy/scripts/kata-deploy.sh
This patch adds k0s deployment support, ~~but this isn't tested yet. I will be running this on my own cluster soon.~~ On my own homelab, this runs pretty well, but I don't have the managed containerd auto config and instead I merged the keys on my own.
This feature requires k0s 1.27.1 or above due to a new mechanism:
> k0s managed dynamic runtime configuration[#](https://docs.k0sproject.io/v1.27.1+k0s.0/runtime/#k0s-managed-dynamic-runtime-configuration)
>
> From 1.27.1 onwards k0s enables dynamic configuration on containerd CRI runtimes. This works by k0s creating a special directory in /etc/k0s/containerd.d/ where user can drop-in partial containerd configuration snippets.
> 
> **k0s will automatically pick up these files and adds these in containerd configuration imports list**. If k0s …
> kata-deploy: Preliminary k0s support

- src/runtime/virtcontainers/documentation/Developers.md
Remove the installation step in the virtcontainers doc because the virtcontainers install/uninstall targets have been removed by 86723b51ae131364e4efaa4d8818a6bac26a9dac and they are not used anymore.
Fixes: #7637
> docs: Remove installation step in virtcontainers doc

- tests/common.bash
This PR fixed the loop that stops the kata-shim and the hypervisors used in metrics checks.
Fixes: #7628
> metrics: fix the loop used to stop kata components

- .github/workflows/run-kata-deploy-tests-on-aks.yaml
- .github/workflows/run-kata-deploy-tests-on-tdx.yaml
- tests/functional/kata-deploy/gha-run.sh
- tests/gha-run-k8s-common.sh
- tests/integration/kubernetes/gha-run.sh
This first part does:
* Splits gha-run.sh from the `integration/kubernetes`  dir, so it can be reused for the `functional/kata-deploy`  tests that will come in the future
* Add the aks / tdx tests, as those are the ones I will be touching
* sev / snp tests are also welcome but I'll leave this to AMD to play with
* Add a basic placeholder for the gha-run.sh, which will be used by the `functional/kata-deploy` tests.
> gha: tests: Add kata-deploy functional tests -- Part 1

- tests/integration/cri-containerd/gha-run.sh
- tests/integration/cri-containerd/integration-tests.sh
As the cri-containerd tests have been fully migrated to GHA, let's make sure we get them running.
Fixes: #6543
> gha: cri-containerd: Enable tests

- src/tools/runk/Cargo.lock
- src/tools/runk/libcontainer/src/container.rs
The error message when the kill command is executed with the container's 
state == Stopped should be "container not running" because the containerd
tests expect that OCI runtimes return the error message and compare it.  
If the error message is different from the expected one, the tests fail. 
Fixes: #7650                                                             
> runk: Modify kill command's error message for containerd tests

- .github/workflows/ci.yaml
Let's add the tests as part of the ci.yaml, so they an be triggered as part of each PR.
For this PR those tests won't be triggered, courtesy to the `pull_request_target` event we rely on.
> gha: ci: Start running kata-deploy tests

- tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
- tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
- tests/metrics/gha-run.sh
This PR fixes the check results for tensorflow benchmark now that we change the name of the test.
Fixes #7684
> metrics: Fix check results for tensorflow benchmark

- tests/common.bash
- tests/integration/kubernetes/kata-deploy-ensure-runtimec-classes-created.bats
- tests/integration/kubernetes/setup.sh
- tools/packaging/kata-deploy/scripts/kata-deploy.sh
The default `kata` runtime class would get created with the `kata`
handler instead of `kata-$KATA_HYPERVISOR`. This made Kata use the wrong
hypervisor and broke CI.
Fixes: https://github.com/kata-containers/kata-containers/issues/7681
Backport of #7654
> CC | kata-deploy: Properly create default runtime class

- src/agent/src/main.rs
- src/agent/src/policy.rs
- tools/osbuilder/rootfs-builder/rootfs.sh
When building with AGENT_POLICY=yes and AGENT_INIT=yes:
1. Include OPA and the Policy settings in rootfs.
2. Start OPA from the kata agent.
Before these changes, building with both AGENT_POLICY=yes and AGENT_INIT=yes was unsupported.
Starting OPA from systemd (when AGENT_INIT=no) was already supported.
Fixes: #7615
> rootfs: agent: Policy support with AGENT_INIT=yes

- src/agent/src/image_rpc.rs
- src/agent/src/rpc.rs
- src/agent/src/sandbox.rs
Move image service related code into image-rpc.rs, and also introduce a singleton instance of image service for coming refactor.
> CC | move image service related code into image-rpc.rs

- tests/metrics/machine_learning/tensorflow_mobilenet_v1_bfloat16_fp32.sh
This PR removes unused variable in tensorflow mobilenet script.
Fixes #7679
> metrics: Remove unused variable in tensorflow mobilenet script

- tests/metrics/machine_learning/README.md
This PR fixes the pytorch reference in the README file.
Fixes #7689
> metrics: Fix README for pytorch

- tests/metrics/gha-run.sh
- tests/metrics/storage/fio-k8s/Makefile
- tests/metrics/storage/fio-k8s/cmd/fiotest/Makefile
- tests/metrics/storage/fio-k8s/configs/example-config/kata-clh.yaml
- tests/metrics/storage/fio-k8s/configs/example-config/kata-qemu.yaml
- tests/metrics/storage/fio-k8s/fio-test-ci.sh
This PR configures the corresponding kata runtime in K8s based on the tested hypervisor.
This PR also enables FIO metrics test in the kata metrics-ci.
Fixes: #7665
> metrics: Enable kata runtime in K8s for FIO test.

- tests/integration/kubernetes/gha-run.sh
10 lines can be insufficient for diagnostics.
Fixes: #7707
> gha: capture additional kata-deploy output

- tests/metrics/README.md
This PR adds disk link to README documentation for kata metrics.
Fixes #7721
> metrics: Add disk link to README

- tools/packaging/kata-deploy/scripts/kata-deploy.sh
We can simply use `rm -f` all over the place and avoid the container returning any error.
Fixes: #7733
> kata-deploy: Avoid failing on content removal

- tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
docker install now creates a group with gid 999 which happens to match what we need to get docker-in-docker to work. Remove the group first as we don't need it.
Fixes: #7726
> local-build: Remove GID before creating group

- src/libs/kata-types/tests/texture/configuration-anno-1.toml
Change `pdisable_guest_seccomp` to `disable_guest_seccomp`
Fixes: #7727
> libs,tests: fix typo disable_guest_seccomp in configuration-anno-1.toml

- tools/packaging/kata-deploy/scripts/kata-deploy.sh
We can simply use `rm -f` all over the place and avoid the container returning any error.
Fixes: #7733
(cherry picked from commit 5cba38c1750f24fc946cfe72f5f1fc971b58d90b)
> CC | backport | kata-deploy: Avoid failing on content removal

- src/agent/rustjail/src/lib.rs
When the FileMode field for the device is unset (0), use a default value instead to allow the use of the device from the container.
This behaviour is seen from cri-o typically.
Fixes: #7717
> kata-agent: use default filemode for block device when it is set to 0

- .github/workflows/run-vfio-tests.yaml
Move the test to run on Ubuntu 23.04, which already ships kernel v6.2. We need this to get L3 virtualization to work.
To be merged before #7704 so that the other PR can make use of it (thanks GHA...).
> gha: vfio: Run on Ubuntu 23.04 runner

- tools/packaging/kata-deploy/scripts/kata-deploy.sh
The directory is a host path mount and cannot be removed from within the container.  What we actually want to remove is whatever is inside that directory.
This may raise errors like:
```
rm: cannot remove '/opt/kata/': Device or resource busy
```
Fixes: #7746
> CC | backport | kata-deploy: Don't try to remove /opt/kata

- tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
docker install now creates a group with gid 999 which happens to match what we need to get docker-in-docker to work. Remove the group first as we don't need it.
Fixes: #7726
Signed-off-by: Jeremi Piotrowski <jpiotrowski@microsoft.com>
(cherry picked from commit 3b881fbc0edbe3c0979bff0d6f12bbce7215e3bb)
Another one that can simply bypass the CI
> CC | Backport | local-build: Remove GID before creating group

- tools/packaging/kata-deploy/scripts/kata-deploy.sh
The directory is a host path mount and cannot be removed from within the container.  What we actually want to remove is whatever is inside that directory.
This may raise errors like:
```
rm: cannot remove '/opt/kata/': Device or resource busy
```
Fixes: #7746
> kata-deploy: Don't try to remove /opt/kata

- tests/metrics/machine_learning/tensorflow_nhwc.sh
This PR removes unused variable in tensorflow nhwc script.
Fixes #7750
> metrics: Remove unused variable in tensorflow nhwc script

- .github/workflows/run-cri-containerd-tests.yaml
- .github/workflows/run-metrics.yaml
- .github/workflows/run-nydus-tests.yaml
- .github/workflows/static-checks.yaml
Otherwise we'll have to re-run all the tests due to a flaky behaviour in one of the parts.
Fixes: #7757
> gha: Avoid "fail-fast" in tests that are known to be flaky

- src/runtime-rs/crates/agent/src/log_forwarder.rs
The log_forwarder task does not check if the peer has closed, causing a meaningless loop during the period of “kata vm exit”, when the peer closed, and “ShutdownContainer RPC received” that aborts the log forwarder.
This patch fixes the problem.
Fixed: #7741
> runtime-rs: check peer close in log_forwarder

- tests/integration/kubernetes/k8s-kill-all-process-in-container.bats
k8s-pid-ns.bats was already using the test name from k8s-kill-all-process-in-container.bats - probably a copy/paste bug.
Fixes: #7753
> tests: use unique test name

- tests/integration/kubernetes/k8s-pod-quota.bats
At the end of k8s-kill-all-process-in-container.bats, delete the deployment it created.
Fixes: #7752
> tests: delete k8s deployment at the test's end

- src/agent/src/mount.rs
Cherry-pick #7602 from main branch. There's only a minor conflict in src/agent/src/rpc.rs, which should be pretty safe.
> CC | cherry-pick #7602 from main branch

- tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
- tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
This PR fixes the memory inside limit for clh for kata metrics due to the recent changes that we had in the script which impacted in the performance measurement.
> metrics: Fix memory inside limits for kata metrics

- src/agent/Cargo.lock
- src/agent/Cargo.toml
- versions.yaml
Bump image-rs and attestation-agent to use the latest guest-components with the rust clap version fix
Fixes: #7580
> versions: Bump guest-components

- tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
- tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
- tests/metrics/gha-run.sh
This PR enables the FIO limits for kata metrics.
Fixes #7771
> metrics: Enable FIO limits for kata metrics

- tests/metrics/report/grabdata.sh
This PR adds the grabdata script so it can be used for the metrics report for kata metrics.
Fixes #7812
> metrics: Add grabdata script for metrics report

- versions.yaml
3.15 will be out of life in 2 months from now.
Fixes: #7816
> versions: Update alpine to its 3.18 version

- .github/workflows/add-issues-to-project.yaml
- .github/workflows/add-pr-sizing-label.yaml
- .github/workflows/ci-on-push.yaml
- .github/workflows/darwin-tests.yaml
- .github/workflows/docs-url-alive-check.yaml
- .github/workflows/move-issues-to-in-progress.yaml
- .github/workflows/require-pr-porting-labels.yaml
This follows the same workflow which was performed when using the
jenkins tests, and it avoids asking for a contributor to do a rebase in
the most part of the cases.
The only cases where the contributor's rebase would still be needed is
when the action itself has been changed.
Fixes: #7414
> gha: Rebase PR atop of the target branch before testing

- src/agent/src/sandbox.rs
- src/agent/src/storage/mod.rs
When a storage device is used by more than one container, the second and forth instances will cause storage device reference count leakage, thus cause storage device leakage. The reason is:
add_storages() will increase reference count of existing storage device, but forget to add the device to the `mount_list` array, thus leak the reference count.
Fixes: #7820
> agent: avoid possible leakage of storage device

- src/agent/src/sandbox.rs
- src/agent/src/storage/mod.rs
- src/libs/kata-types/src/mount.rs
Currently there's no way to return error when cleaning up storage devices for sandbox. So add a way to return error and refine the logic to clean up resources.
> Improve the way to clean up storage devices for sandbox

- tools/osbuilder/image-builder/image_builder.sh
Remove the `chcon` operation which adds `container_runtime_exec_t` label to the `kata-agent` binary because the container-selinux package including the https://github.com/containers/container-selinux/commit/39f83cc74d50bd10ab6be4d0bdd98bc04857469f commit has been released officially.
Ref. https://centos.pkgs.org/9-stream/centos-appstream-x86_64/container-selinux-2.221.0-1.el9.noarch.rpm.html
The container-selinux package is installed in a guest rootfs when we create it with `SELinux = yes`, and `restorecon` sets `container_runtime_exec_t` to the `kata-agent`.
Fixes: #7807
> osbuilder: Remove chcon operation for guest SELinux

- .github/workflows/static-checks-dragonball.yaml
Previously, static-checks-dragonball is using machines from Alibaba Cloud to run all the CI jobs.
Currently, we are going through an internal process to apply for the new machines for Dragonball CI. Before the internal process is over, we will temporarily use Azure VM to run static-checks-dragonball jobs.
fixes: #7838
> CI: switch static-checks-dragonball CI machines to Azure

- tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
- tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
- tests/metrics/gha-run.sh
- tests/metrics/network/iperf3_kubernetes/k8s-network-metrics-iperf3.sh
This PR enables the iperf benchmark to run on the gha for kata metrics.
Fixes #7575
> metrics: Enable iperf benchmark on gha for kata metrics

- src/runtime-rs/crates/runtimes/common/src/types/mod.rs
- src/runtime-rs/crates/runtimes/common/src/types/trans_into_shim.rs
- src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs
- src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container_inner.rs
- src/runtime-rs/crates/runtimes/virt_container/src/container_manager/manager.rs
- src/runtime-rs/crates/runtimes/virt_container/src/container_manager/process.rs
There are several processes for container exit:
- Non-detach mode: `Wait` request is sent by containerd, then
`stop_process()` will be called eventually.
- Detach mode: `Wait` request is not sent, the `wait_process()` won’t be
called.
- Killed by ctr: For example, a container runs `tail -f /dev/null`, and
is killed by `sudo ctr t kill -a -s SIGTERM <CID>`. Kill request is
sent, then `kill_process()` will be called. User executes `sudo ctr c
rm <CID>`, `Delete` request is sent, then `delete_process()` will be
called.
- Exited on its own: For example, a container runs `sleep 1s`. The
container’s state goes to `Stopped` after 1 second. User executes
the delete command as below.
Where do we do container cleanup things?
- `wait_process()`: No, because it won’t be called in detach mode.
- …
> runtime-rs: Fix volumes and rootfs cleanup issues

- tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
This PR is to skip installing docker-compose-plugin while buiding a `build-kata-deploy` image for s390x|ppc64le. It is a temporary solution to fix current CI failures for s390x regarding `hash sum mismatch`.
Fixes: #7848
(cherry picked from commit 2efda20c778940bf0ac096dcc435da74583378c6)
> CCv0: packaging: do not install docker-compose-plugin for s390x|ppc64le

- src/runtime/Makefile
Some use cases may just require passing extra arguments to virtiofsd, and having this disabled by default makes it impossible to set when using kata-deploy, as changes in the configuration file would be overwritten by the daemon-set.
With this in mind, let's allow users to pass whatever thet need (and here I'm specifically looking at `--xattr`) as a virtio_fs_extra_arg.
Fixes: #7853
> runtime: Allow virtio_fs_extra_args annotation

- tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
- tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
This PR adds the write 95 percentile FIO value for checkmetrics for kata metrics.
Fixes #7842
> metrics: Add write 95 percentile FIO value

- src/runtime/virtcontainers/acrn_arch_base.go
- src/runtime/virtcontainers/acrn_arch_base_test.go
- src/runtime/virtcontainers/acrn_test.go
- src/runtime/virtcontainers/clh.go
- src/runtime/virtcontainers/clh_test.go
- src/runtime/virtcontainers/qemu_amd64.go
- src/runtime/virtcontainers/qemu_amd64_test.go
- src/runtime/virtcontainers/qemu_arch_base.go
- src/runtime/virtcontainers/qemu_arch_base_test.go
- src/runtime/virtcontainers/qemu_ppc64le.go
- src/runtime/virtcontainers/qemu_test.go
- src/runtime/virtcontainers/sandbox.go
- src/runtime/virtcontainers/types/capabilities.go
- src/runtime/virtcontainers/utils/utils.go
- src/runtime/virtcontainers/utils/utils_test.go
Add a new hypervisor capability to tell if it supports device hotplug. If not, we should run prestart hooks before starting new VMs as nerdctl is using the prestart hooks to set up netns. To make nerdctl + FC to work, we need to run the prestart hooks before starting new VMs.
Fixes: #6384
> runtime: run prestart hooks before starting VM for FC

- tools/packaging/kata-deploy/local-build/kata-deploy-merge-builds.sh
Pass --owner and --group to the tar invokation to prevent gihtub runner user from leaking into release artifacts.
Fixes: #7832
> kata-deploy: Create kata-static.tar with correct ownership

- .github/workflows/ci.yaml
- .github/workflows/run-k8s-tests-on-garm.yaml
- tests/integration/kubernetes/gha-run.sh
Let's enable the devmapper kubernetes tests to match exactly what's been
tested as part of the Jenkins CI.
Fixes: #6542
>  ci: k8s: Add k8s devmapper tests (part 0)

- src/dragonball/src/api/v1/vmm_action.rs
- src/dragonball/src/vm/mod.rs
Currently, the dbs-upcall features have 2 problems that are needed to be fixed :
There are redundant dbs-upcall features that are needed to be removed. Some place should be controlled by dbs-upcall but not being implemented.
This commit will fix those two problems.
fixes: #6878
> Dragonball: optimize the placement of dbs-upcall features

- tests/metrics/density/memory_usage.sh
This PR re-enables the initialization step disabled on 538c965c2b79053f0b4d8fe2855196307b72932b.
Fixes: #7804
> metrics: re-enable memory-usage initialization step

- tests/metrics/storage/fio-k8s/fio-test-ci.sh
This PR changes the order in which the FIO test first cleans the environment and then checks if the environment is indeed clean.
Fixes: #7869
> metrics: fix FIO test initialization

- tests/metrics/machine_learning/resnet50_fp32_dockerfile/Dockerfile
- tests/metrics/machine_learning/resnet50_int8_dockerfile/Dockerfile
This PR replaces the ubuntu image for one which has TensorFlow optimized for kata metrics.
Fixes #7866
> metrics: Use TensorFlow optimized image

- tools/packaging/kata-deploy/Dockerfile
This will make our image smaller, and still ensure it's multi-arch support.
Fixes: #7861
> kata-deploy: Switch to an alpine image

- src/runtime/virtcontainers/qemu.go
- src/runtime/virtcontainers/virtiofsd.go
- src/runtime/virtcontainers/virtiofsd_test.go
Update some more virtiofsd arguments from the legacy syntax of the C implementation to the new syntax used by the rust implementation.
> runtime: Fix more virtiofs args

- tools/packaging/kata-deploy/Dockerfile
Similarly to what's been done for x86_64 -> amd64, we need to do a
aarch64 -> arm64 change in order to be able to download the kubectl
binary.
> kata-deploy: Fix aarch64 image build

- .github/workflows/add-pr-sizing-label.yaml
- .github/workflows/build-kata-static-tarball-amd64.yaml
- .github/workflows/build-kata-static-tarball-arm64.yaml
- .github/workflows/build-kata-static-tarball-s390x.yaml
- .github/workflows/ci-on-push.yaml
- .github/workflows/ci.yaml
- .github/workflows/move-issues-to-in-progress.yaml
- .github/workflows/require-pr-porting-labels.yaml
- .github/workflows/run-cri-containerd-tests.yaml
- .github/workflows/run-k8s-tests-on-aks.yaml
- .github/workflows/run-k8s-tests-on-garm.yaml
- .github/workflows/run-k8s-tests-on-sev.yaml
- .github/workflows/run-k8s-tests-on-snp.yaml
- .github/workflows/run-k8s-tests-on-tdx.yaml
- .github/workflows/run-kata-deploy-tests-on-aks.yaml
- .github/workflows/run-kata-deploy-tests-on-tdx.yaml
- .github/workflows/run-metrics.yaml
- .github/workflows/run-nydus-tests.yaml
- .github/workflows/run-vfio-tests.yaml
- tests/git-helper.sh
We're changing what's been done as part of ac939c458cde, as we've notcied issues using `github.event.pull_request.merge_commit_sha`.
Basically, whenever a force-push would happen, the reference of merge_commit_sha wouldn't be updated, leading us to test PRs with the old code. :-/
In order to get the rebase properly working, we need to ensure we pull the hash of the commit as part of checkout action, and ensure fetch-depth is set to 0.
Fixes: #7414
> gha: Manually rebase PR atop of the target branch before testing

- .github/workflows/ci-nightly.yaml
- .github/workflows/payload-after-push.yaml
- .github/workflows/publish-kata-deploy-payload-amd64.yaml
- .github/workflows/publish-kata-deploy-payload-arm64.yaml
- .github/workflows/publish-kata-deploy-payload-s390x.yaml
The ones for the payload-after-push.yamland ci-nightly.yaml are not that much important right now, but they're needed for when we start running those on stable branches as well.
The other ones were missed during
bd24afcf737f94481992e2d88b27e66cfae64df8.
Fixes: #7414
> ci: Add more target-branch related fixes

- .github/workflows/ci-nightly.yaml
- .github/workflows/payload-after-push.yaml
As, regardless of what's mentioned in the documentation, it seems that $GITHUB_REF_NAME is passed down as a literal string.
Fixes: #7414
> ci: use github.ref_name instead of $GITHUB_REF_NAME

- src/libs/Cargo.lock
- src/libs/kata-types/src/config/mod.rs
- src/libs/shim-interface/Cargo.toml
- src/libs/shim-interface/src/lib.rs
- src/runtime-rs/Cargo.lock
- src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
- src/runtime-rs/crates/hypervisor/src/ch/utils.rs
- src/runtime-rs/crates/hypervisor/src/device/device_manager.rs
- src/runtime-rs/crates/hypervisor/src/device/driver/mod.rs
- src/runtime-rs/crates/hypervisor/src/device/driver/virtio_vsock.rs
- src/runtime-rs/crates/hypervisor/src/dragonball/inner.rs
- src/runtime-rs/crates/hypervisor/src/dragonball/inner_device.rs
- src/runtime-rs/crates/hypervisor/src/dragonball/inner_hypervisor.rs
- src/runtime-rs/crates/hypervisor/src/lib.rs
- src/runtime-rs/crates/hypervisor/src/utils.rs
- src/runtime-rs/crates/persist/src/lib.rs
- src/runtime-rs/crates/resource/src/lib.rs
- src/runtime-rs/crates/resource/src/manager_inner.rs
- src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
- src/runtime-rs/crates/service/Cargo.toml
- src/runtime-rs/crates/service/src/manager.rs
Currently, virtio_vsock are still outside of the device manager. 
This causes some management issues,such as the inability to unify PCI address management.
Just do some work for hybrid vsock.
Fixes: #7655
> runtime-rs: bring hybrid vsock devices in manager.

- tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
- tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
- tests/metrics/gha-run.sh
FIO test is showing ongoing issues when running in k8s. Working on running FIO on the ctr client which has been shown to be stable.
Fixes: #7920
> metrics: this PR skips the FIO test temprarily to fix issues

- tests/metrics/lib/common.bash
This PR ensures that docker is running as part of the init_env function in kata metrics to avoid failures like docker is not running and making the kata metrics CI to fail.
Fixes #7898
> metrics: Ensure docker is running in init_env

- tools/osbuilder/image-builder/image_builder.sh
Incorporate the `DM_VERITY` parameter when building the image with docker.
Fixes #7879
> image-builder: fix udev error when using docker to build image

- tools/osbuilder/rootfs-builder/rootfs.sh
We should configure the Rust environment when AGENT_SOURCE_BIN is empty or AA_KBC is not empty before building agent and AA.
Fixes #7877
> CC | osbuilder: check rust enviornment before building agent and AA

- tests/metrics/README.md
Now that the metrics migration from the tests to kata containers has been completed, this PR removes the warning from the main metrics documentation.
Fixes #7894
> metrics: Remove warning from metrics documentation

- src/agent/Cargo.lock
- src/agent/Cargo.toml
- src/agent/src/storage/block_handler.rs
- src/agent/src/storage/dm_verity.rs
- src/agent/src/storage/fs_handler.rs
- src/agent/src/storage/mod.rs
- src/libs/kata-sys-util/src/mount.rs
- src/libs/kata-types/src/lib.rs
- src/libs/kata-types/src/volume.rs
- src/runtime/pkg/katautils/create.go
- src/runtime/virtcontainers/container.go
- src/runtime/virtcontainers/fs_share.go
- src/runtime/virtcontainers/fs_share_linux.go
- src/runtime/virtcontainers/kata_agent.go
- src/runtime/virtcontainers/types/virtual_volume.go
- src/runtime/virtcontainers/types/virtual_volume_test.go
This PR is the feature of https://github.com/confidential-containers/confidential-containers/issues/142 , to support to pull images on the host by nydus-snapshotter and share the image block devices to the guest. 
The following are operations and results to share image on the host with dm-verity: 
- snapshotter:  pass the raw disk image to kata through mount options with prefix `extraoption=`:
```
"extraoption=eyJ2b2x1bWVfdHlwZSI6ImltYWdlX3Jhd19ibG9jayIsInNvdXJjZSI6Ii92YXIvbGliL2NvbnRhaW5lcmQtbnlkdXMvc25hcHNob3RzLzEvZnMvaW1hZ2VzL2ZiYTVlNDhiMmU0NjlkNTRmZjdiZGM0MzViNWUyOTM5YmQyMWJhNjgzMWU1OGQ5NjQ3ZjU2ZWRlZWIyODAxMWQuZGlzayIsImZzX3R5cGUiOiJlcm9mcyIsImRtX3Zlcml0eSI6eyJoYXNodHlwZSI6InNoYTI1NiIsImhhc2giOiJkODYxMDRlZWU3MTVhMWI1OWI2MjE0ODY0MWY0Y2E3M2VkZjFiZTMwMDZjNGQ0ODFmMDNmNTVhYzA1NjQwNTcwIiwiYm …
```
> CC | support dm-verity tarfs disk image in CoCo

- tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
- tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
This PR adds the iperf bandwidth value for kata metrics.
Fixes #7924
> metrics: Add iperf bandwidth value for kata metrics

- tests/integration/kubernetes/run_kubernetes_tests.sh
- tests/integration/kubernetes/setup.sh
Fix kernel and initrd annotations in the k8s tests on Mariner. These annotations must be applied to the spec.template for Deployment, Job and ReplicationController resources.
Fixes: #7764
> tests: fix kernel and initrd annotations

- .github/workflows/build-kata-static-tarball-amd64.yaml
- .github/workflows/build-kata-static-tarball-arm64.yaml
- .github/workflows/build-kata-static-tarball-s390x.yaml
We do the build of our artefacts inside a container image, and we need to expose some env vars to the container so ORAS can be used there to push the artefacts we want to cache to ghcr.io.
The env vars we're exposing are:
* ARTEFACT_REGISTRY: The registry where we're going to save the artefacts.
* ARTEFACT_REGISTRY_USERNAME: The username to log in to the registry, as ORAS does not use the same json file used by docker.
* ARTEFACT_REGISTRY_PASSWORD: The pasword to log in to the the registry, as the ORAS does not use the same json file used by docker.
* TARGET_BRANCH: The target branch, which will be part of the tag of the artefact, as we may end up caching the artefacts for both main and stable branches.
I'm opening this PR as "part 0" of the full work that can be seen in the following …
> ci: cache: Export env vars needed to use ORAS

- tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
- tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
This PR adds the iperf value for cpu utilization for kata metrics.
Fixes #7936
> metrics: Add iperf value for cpu utilization

- tests/gha-run-k8s-common.sh
- tests/integration/kubernetes/run_kubernetes_tests.sh
- tests/integration/kubernetes/runtimeclass_workloads/inotify-configmap-pod.yaml
We do **not** need a very powerful machine for our tests, as we're not building anything there.
The instance we switched to (Standard_D2s_v5) still has nested virt available, as shown here[0], but has half of the amount of vCPUs / Memory, which should be fine only for running the tests, costing us basically half of the price[1].
[0]:
https://learn.microsoft.com/en-us/azure/virtual-machines/dv5-dsv5-series [1]:
https://azure.microsoft.com/en-us/pricing/details/virtual-machines/linux/#pricing
Fixes: #7955
> ci: Reduce the size of the AKS VMs

- .github/workflows/run-cri-containerd-tests.yaml
- .github/workflows/run-docker-tests-on-garm.yaml
- .github/workflows/run-k8s-tests-on-garm.yaml
- .github/workflows/run-nerdctl-tests-on-garm.yaml
- .github/workflows/run-nydus-tests.yaml
With the idea of reducing the costs, let's make sure we run the following jobs in smaller instances:
* docker
* nerdctl
* cri-containerd
* nydus
* k8s - devmapper
> ci: Run some of the GARM tests in smaller instances

- tools/packaging/guest-image/build_image.sh
This PR is to prevent rootfs.sh from running twice for a target `make cc-rootfs-initrd` by fixing the typo `initrd-image`.
Fixes: #7980
> cc|osbuilder: Correct a typo in the initrd-image

- .github/workflows/cc-payload-after-push-s390x.yaml
This PR is to remove the build redundancy of `kernel` and `cc-rootfs-initrd` by making `cc-se-image` built based on them at the second build stage.
Fixes: #7949
> cc|gha: remove build redundancy of kernel and cc-rootfs-initrd for s390x

- src/runtime/config/configuration-qemu-nvidia-gpu.toml.in
- src/runtime/config/configuration-qemu.toml.in
- src/runtime/pkg/govmm/qemu/qemu.go
- src/runtime/pkg/govmm/qemu/qemu_test.go
- src/runtime/pkg/katautils/config-settings.go.in
- src/runtime/pkg/katautils/config.go
- src/runtime/virtcontainers/hypervisor.go
- src/runtime/virtcontainers/qemu.go
PR #6146 added the possibility to control QEMU with an extra HMP socket as an aid for debugging. This is great for development or bug chasing but this raises some concerns in production.
The HMP monitor allows to temper with the VM state in a variety of ways. This could be intentionally or mistakenly used to inject subtle bugs in the VM that would be extremely hard if not even impossible to debug. We definitely don't want that to be enabled by default.
The feature is currently wired to the `enable_debug` setting in the `[hypervisor.qemu]` section of the configuration file. This setting has historically been used to control "debug output" and it is used as such by some downstream users (e.g. Openshift). Forcing people to have the extra HMP backdoor at the same time is abusive and …
> runtime/qemu: Rework QMP/HMP support

- tests/common.bash
- tests/integration/nydus/gha-run.sh
- tests/integration/nydus/nydus-container.yaml
- tests/integration/nydus/nydus-sandbox.yaml
- tests/integration/nydus/nydus_tests.sh
- tests/integration/nydus/nydusd-config.json
- tests/integration/nydus/snapshotter-config.toml
- tools/packaging/static-build/nydus/build.sh
- versions.yaml
Bump nydus and nydus-snapshotter to its latest release and update the nydus tests in the same way as demonstrated in https://github.com/kata-containers/tests/pull/5769
This PR is rebased from https://github.com/kata-containers/kata-containers/pull/7659
> Bump nydus versions and update nydus tests

- versions.yaml
https://gitlab.com/virtio-fs/virtiofsd/-/releases/v1.8.0 was released two weeks ago. We have fully tested and are using this version.
Fixes: #7960
Signed-off-by: Simon Kaegi <simon.kaegi@gmail.com>
> versions: Bump virtiofsd to v1.8.0

- tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
- tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
This PR enables the parallel bandwidth iperf limit for kata metrics.
Fixes #7989
> metrics: Enable parallel bandwidth iperf limit

- .github/workflows/run-kata-deploy-tests-on-garm.yaml
It should be garm-ubuntu-2004-smaller instead of garm-ubuntu-2004-small.
Fixes: #7890
> ci: kata-deploy: Fix runner name

- src/agent/Cargo.lock
- src/agent/Cargo.toml
- tools/osbuilder/rootfs-builder/rootfs.sh
- versions.yaml
- Switch api-server-rest to use the Makefile rather than directly calling cargo for multi-platform support and decoupling
Fixes: #7947
> osbuilder: Update api-server-rest

- versions.yaml
As we'll need to test with both the vanilla and the forked versions of containerd, let's make sure we'll specify both entries as part of our versions.yaml file, and we can read whatever we need accordingly as part of our tests jobs.
NOTE: This will never make into the `main` branch, but we need this right now in order to have our tests properly setup.
> CC | version: Specify forked / vanilla entries of containerd

- tools/osbuilder/rootfs-builder/rootfs.sh
Guest rootfs will aligned to 128M, we may exceed the rootfs with several megabytes but the rootfs will add 128M.
Fixes: #8009
> CC | osbuild: Reduce guest components binary size with strip

- tools/packaging/static-build/cache_components.sh
The name of the tarballs changed on main, but we didn't follow up changing this on the CCv0 branch. :-/
> CC | cache: Fix rootfs-image-tdx and rootfs-initrd-sev cached artefacts

- src/agent/src/image_rpc.rs
- src/agent/src/storage/image_pull_handler.rs
- src/agent/src/storage/mod.rs
- src/runtime/virtcontainers/container.go
- src/runtime/virtcontainers/fs_share_linux.go
- src/runtime/virtcontainers/kata_agent.go
- tools/osbuilder/scripts/lib.sh
- tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
- tools/packaging/static-build/nydus/build.sh
- tools/packaging/static-build/shim-v2/build.sh
- tools/packaging/static-build/shim-v2/install_go_rust.sh
This PR is to achieve `image pulling in the guest without forked containerd`. 
Without forked containerd, the image name will be passed from remote snapshotter to kata-agent through mount slice.
The following are operations and results with image pulling in the guest:
- snapshotter:  pass the image url to kata through mount options with prefix `io.kata-containers.volume=`:
```
"io.kata-containers.volume=eyJ2b2x1bWVfdHlwZSI6ImltYWdlX2d1ZXN0X3B1bGwiLCJzb3VyY2UiOiJxdWF5LmlvL2thdGEtY29udGFpbmVycy9jb25maWRlbnRpYWwtY29udGFpbmVyczp1bnNpZ25lZCIsImZzX3R5cGUiOiJvdmVybGF5ZnMiLCJpbWFnZV9wdWxsIjp7Im1ldGFkYXRhIjp7fX19"
``` 
the decoded json: 
```
{"volume_type":"image_guest_pull","source":"quay.io/kata-containers/confidential-containers:unsigned","fs_type":"overlayfs","image_pull":{"metadata":{}}}
``` …
> CC | image pulling in the guest without forked containerd

- .github/workflows/ci.yaml
The test has been added to the repo, but we have to also add it to the
list of jobs to be executed.
Fixes: #8005
> ci: Actually enable the CRI-O tests

- .github/workflows/static-checks.yaml
Seems like the static checks are failing due the missing of the hunspell package this PR fixes that.
Fixes #8019
> gha: Install hunspell for static checks

- src/runtime/config/configuration-clh.toml.in
- src/runtime/config/configuration-fc.toml.in
- src/runtime/pkg/katautils/config.go
- src/runtime/virtcontainers/clh.go
- src/runtime/virtcontainers/fc.go
Cloud hypervisor has support for direct i/o, this patch adds support for enabling it in kata. It doesn't know about noflush, removed it from the list of valid options for clh.
Firecracker supports noflush semantic via Unsafe cache type.
There is no support for direct i/o in firecracker, I removed it from config file.
Fixes: #7798 #7823
> clh: Direct IO support for block devices 

- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Fixes: #8027
This PR and [PR 8029](https://github.com/kata-containers/kata-containers/pull/8029) are two different attempts to solve the current CI failure. Example failure [here](https://github.com/kata-containers/kata-containers/actions/runs/6257676526/job/16990382096).
> ci: rootfs-image build-asset is failing

- .github/workflows/static-checks.yaml
To avoid the failure of not finding pandoc command this PR adds that package as a dependency for static checks.
Fixes #8041
> gha: Add pandoc as a dependency for static checks

- tools/osbuilder/rootfs-builder/rootfs.sh
opa_linux_amd64_static 38M => 27M
kata-agent 30M => 23M
ls -alh opa_linux_amd64_static
-rw-rw-r-- 1 arron arron 38M Jul 28 01:59 opa_linux_amd64_static ➜ kata-containers git:(main) ✗ strip opa_linux_amd64_static ➜ kata-containers git:(main) ✗ ls -alh opa_linux_amd64_static -rw-rw-r-- 1 arron arron 27M Sep 20 16:12 opa_linux_amd64_static
ls -alh ./usr/bin/kata-agent
-rwxr-xr-x. 1 root root 30M Jul 30 23:41 ./usr/bin/kata-agent ls -alh ./usr/bin/kata-agent
-rwxr-xr-x. 1 root root 23M Sep 20 16:13 ./usr/bin/kata-agent
Fixes: #8011
> osbuild: Reduce guest components binary size with strip

- src/runtime-rs/crates/hypervisor/ch-config/src/convert.rs
- src/runtime-rs/crates/hypervisor/ch-config/src/lib.rs
- src/runtime-rs/crates/hypervisor/src/ch/inner.rs
- src/runtime-rs/crates/hypervisor/src/ch/inner_device.rs
- src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
This PR adds support for adding a network device before starting the cloud-hypervisor VM.
Support for adding and removing network devices is not really added to the resource manager, so supporting this for cloud-hypervisor is not scoped in this PR.
This also changes "pending_devices" for clh implementation from an Option of vector to simply a vector. This simplifies the structure a bit as we can simple iterate over the pending devices instead of having to check for a "Some" value as this is not really required.
Fixes: #6333
> runtime-rs: Add network support for cloud-hypervisor

- tools/packaging/kata-deploy/local-build/kata-deploy-build-and-upload-payload.sh
The permissions on .docker/buildx/activity/default are regularly broken by us passing docker.sock + $HOME/.docker to a container running as root and then using buildx inside. Fixup ownership before executing docker commands.
Fixes: #8027
> local-build: Fix .docker ownership before build-payload

- .github/workflows/run-metrics.yaml
- tests/metrics/gha-run.sh
This PR enables the latency test for gha run script for kata metrics.
Fixes #8037
> metrics: Enable latency test in gha run script

- tests/gha-run-k8s-common.sh
- tests/integration/kubernetes/tests_common.sh
- tools/packaging/kata-deploy/scripts/kata-deploy.sh
This is the last set of patches needed to get the CRI-O CI working as part of GHA.
> ci: k8s: crio: Follow up patches to have CRI-O also working as part of our CI

- tools/packaging/kata-deploy/scripts/kata-deploy.sh
This is a patch that should **NOT** be forward ported to main, as there we want to take a cleaner approach on configuring specific snapshotters for specific runtime handlers.
However, for CC, for the v0.8.0 release of CC, this is good enough as it is, and it'll allow us to set one snapshotter for all the deployments done with the CoCo Operator.
This is the Kata Containers counterpart of the work, and there's still work to be done on the Confidential Containers in order to make it work as expected, as:
* Confidential Containers Operator has to expose to the users which snapshotter will be configured
* Confidential Containers Opereator, specifically the pre-install hook, will have to take care of actually installing and configuring the snapshotter, so it can be used.
> CC: kata-deploy: Set the snapshotter in the containerd runtime config

- src/agent/src/image_rpc.rs
Fix setting the image service policy path when there is a policy path in the agent config.
Fixes https://github.com/kata-containers/kata-containers/issues/8049
Signed-off-by: Matthew Arnold <mattarno@uk.ibm.com>
> CC | policy: fix setting the policy path from agent config

- src/libs/Cargo.lock
- src/libs/kata-sys-util/src/protection.rs
- src/libs/kata-types/src/config/hypervisor/ch.rs
- src/libs/kata-types/src/config/hypervisor/mod.rs
- src/runtime-rs/Cargo.lock
- src/runtime-rs/crates/hypervisor/Cargo.toml
- src/runtime-rs/crates/hypervisor/ch-config/Cargo.toml
- src/runtime-rs/crates/hypervisor/ch-config/src/convert.rs
- src/runtime-rs/crates/hypervisor/ch-config/src/errors.rs
- src/runtime-rs/crates/hypervisor/ch-config/src/lib.rs
- src/runtime-rs/crates/hypervisor/src/ch/inner.rs
- src/runtime-rs/crates/hypervisor/src/ch/inner_device.rs
- src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
Allow Cloud Hypervisor to create a confidential guest (a TD or "Trust Domain") rather than a VM (Virtual Machine) on Intel systems that provide TDX functionality.
> **Note:**
>
> At least currently, when built with the `tdx` feature, Cloud Hypervisor
> cannot create a standard VM on a TDX capable system: it can only create
> a TD. This implies that on TDX capable systems, the Kata Configuration
> option `confidential_guest=` must be set to `true`. If it is not, Kata
> will detect this and display the following error:
>
> ```
> TDX guest protection available and must be used with Cloud Hypervisor (set 'confidential_guest=true')
> ```
Fixes: #6448.
> runtime-rs: ch: Enable Intel TDX

- src/runtime/virtcontainers/kata_agent.go
merge metadata and annotation in `imagepullvolume`.
> CC | runtime: merge metadata and annotation in imagepullvolume

- .github/workflows/ci.yaml
- .github/workflows/run-kata-monitor-tests.yaml
- tests/common.bash
- tests/functional/kata-monitor/gha-run.sh
- tests/functional/kata-monitor/kata-monitor-tests.sh
- tests/gha-run-k8s-common.sh
This PR brings in the kata-monitor tests.
The tests I've performed locally can be seen here:
* containerd:
* history: https://gist.github.com/fidencio/c641730a3458d755543de4972a318e76
* logs: https://gist.github.com/fidencio/f526f44b4ccfd36fd2c1e2ce50afbcf4
* cri-o:
* history:  https://gist.github.com/fidencio/662899805eaec19f07711d06c04cff13
* logs: https://gist.github.com/fidencio/dae3d4ab1fde008b855857f09b34ad15
I've performed the tests on an ubuntu 22.04 VM, matching the "smaller" garm VM, and I've used the kata-static tarball generated from Yesterday's nightly run.
> ci: Port kata-monitor tests from Jenkins to GHA

- src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
- src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/DiskConfig.md
- src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_disk_config.go
- src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
- versions.yaml
A new device has been added that can communicate when the guest kernel has panicked and share those details with the VMM. This is controlled with a new `--pvpanic` command line option and JSON API change equivalent. 
Requesting to dump the guest memory as core dump will now transparently pause the VM if required; returning to the original state after. 
The support for QCOW2 files has been enhanced to include support for using backing files. 
The minimum supported host kernel is now 5.13 in order to incorporate a bug fix for `KVM_FEATURE_ASYNC_PF_INT` functionality. 
* The x86 emulator is only compiled in if MSHV is compiled in (the kernel carries out this job with KVM)
* A regression has been fixed in VFIO support for devices that use MSI rather  than MSI-X
* When triggering a VM shutdown …
> Upgrade to Cloud Hypervisor v35.0

- src/runtime/virtcontainers/sandbox.go
The cgroup stats come from `resourcecontrol` package in the form of pointers to structs. The sandbox `Stat()` method incorrectly was expecting structs. This caused the cpu and memory stats to always be 0, which in turn caused incorrect pod overhead metrics.
Fixes #8035
> runtime: fix reading cgroup stats of sandboxes

- tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
- tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
- tests/metrics/gha-run.sh
This PR adds latency value limits for kata CI.
Fixes #8067
> metrics: Add latency value limits for kata CI

- .github/workflows/build-kata-static-tarball-amd64.yaml
- tools/packaging/kata-deploy/local-build/Makefile
- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
- tools/packaging/scripts/lib.sh
- tools/packaging/static-build/tools/Dockerfile
- tools/packaging/static-build/tools/build-static-tools.sh
- tools/packaging/static-build/tools/build.sh
We need those in order to start easily testing "tracing" and "runk".
This is focusing on "x86_64", and improvements for other arches are very much welcome **as follow-up PRs**.
Last but not least, to test this, run:
* make agent-ctl-tarball
* make kata-ctl-tarball
* make log-parser-rs-tarball
* make runk-tarball
* make trace-forwarder-tarball
Please, test it locally before approving!
> kata-deploy: build & ship the rust components from src/tools/

- tests/gha-run-k8s-common.sh
The tests are failing when setting up k0s, and that happens because we download a kubectl binary matching the kubernetes version k0s is using, and we do that by:
```
sudo k0s kubectl version --short 2>/dev/null | ...
```
With kubectl 1.28, which is now the default on k0s, `kubectl version --short` has been removed, leading us to an empty stringm causing then the error in the CI.
Fixes: #8105
> gha: Fix k0s deployment

- tests/integration/kubernetes/tests_common.sh
- tools/packaging/kata-deploy/examples/test-deploy-kata-clh.yaml
- tools/packaging/kata-deploy/examples/test-deploy-kata-dragonball.yaml
- tools/packaging/kata-deploy/examples/test-deploy-kata-fc.yaml
- tools/packaging/kata-deploy/examples/test-deploy-kata-qemu.yaml
- tools/packaging/kata-deploy/examples/test-deploy-runc.yaml
The k8s.gcr.io is deprecated for a while now and has been redirected to registry.k8s.io. However on some bare-metal machines in our testing pools that redirection is not working, so let's just replace the registries.
Fixes #6461
(cherry picked from commit b2c3bca558c38deff2117d5909d9071c23c05590)
> versions: migrate out of k8s.gcr.io

- .github/workflows/build-kata-static-tarball-arm64.yaml
- .github/workflows/publish-kata-deploy-payload-arm64.yaml
- .github/workflows/release-arm64.yaml
Otherwise we'll use any arm64 machine that's added as a runner, and whenever new machines are added those may end up being only used for running some specific set of the tests.
Fixes: #8109
> gha: arm64: Ensure the builder is arm64-builder

- .github/workflows/ci.yaml
- .github/workflows/run-tracing-tests.yaml
- tests/common.bash
- tests/functional/tracing/configure_tracing_for_kata.sh
- tests/functional/tracing/gha-run.sh
- tests/functional/tracing/test-agent-shutdown.sh
- tests/functional/tracing/tracing-test.sh
- tests/integration/docker/gha-run.sh
This PR is porting the tracing tests over from the tests repo to this one.
The idea of this PR is **NOT** to improve the tests, but rather bring them as they are.
Here you can find logs of the tests running on my local VMs:
* clh | history: https://gist.github.com/fidencio/4385230d22b3066753daf49845df7dd5
* clh | running: https://gist.github.com/fidencio/2dfc51df0a2c0692ac5e9a65598f9c1f
* qemu | history: https://gist.github.com/fidencio/6fc07d297a556be0e9eec0215e030b23
* qemu | running: https://gist.github.com/fidencio/06601c79f335b2364b9c4fcd1c56466a
The kata-static.tar.xz used as part of my tests is the one coming from https://github.com/kata-containers/kata-containers/actions/runs/6404410066
> ci: gha: Port tracing tests over

- .github/workflows/ci.yaml
- .github/workflows/run-runk-tests.yaml
- tests/integration/runk/gha-run.sh
- tests/integration/runk/runk-tests.sh
This PR is porting the runk tests from the tests repo to the kata-containers one.
No major modifications have been done to the tests, and I'm keeping the `SoB` of all contributors to those tests.
Here you can find info of my tests on my local VM.
* runk | history: https://gist.github.com/fidencio/93e82efcd150528825481483af56f74e
* runk | running: https://gist.github.com/fidencio/76cff60c508afd40c95c50204f8b8748
> gha: ci: Port runk tests over

- src/runtime-rs/crates/hypervisor/README.md
- src/runtime-rs/crates/runtimes/virt_container/Cargo.toml
Enable the Cloud Hypervisor driver (the `cloud-hypervisor` build feature) for the rust runtime.
Fixes: #6264.
> runtime-rs: ch: Enable feature

- .github/workflows/cc-payload-after-push-amd64.yaml
- .github/workflows/cc-payload-after-push-s390x.yaml
We're facing errors in the operator CI, which are related to the measured rootfs.
For now, let's skip the cache builds (as those were dropped anyways for this branch) and ensure we do a clean build, and then check if the problem persists.
> CC | payload-after-push: Bypass cache

- versions.yaml
We're doing so in order to avoid errors like the ones from here: https://github.com/kata-containers/kata-containers/actions/runs/6468115049/job/17559485246
I was able to locally build it, but as we're not testing CLH + TDX lately, running CI on this will be useless.
> versions: bump td-shim version

- tests/gha-run-k8s-common.sh
- tests/integration/kubernetes/gha-run.sh
- tests/integration/kubernetes/k8s-file-volume.bats
- tests/integration/kubernetes/k8s-volume.bats
- tests/integration/kubernetes/runtimeclass_workloads/pod-file-volume.yaml
- tests/integration/kubernetes/runtimeclass_workloads/pv-pod.yaml
- tests/integration/kubernetes/tests_common.sh
- tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml
- tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
My first version of https://github.com/kata-containers/kata-containers/pull/7600 I simply didn't test locally, instead I let the CI run. Unfortunately CI failed and it took a good amount of time to give me a feedback. Other than that, I don't need the kata-deploy payload rebuilt as I am just changing tests files. Ok, so I decided to look if I could make `gha-run.sh` (which basically implements the CI workflow) to run locally, and here is this PR. I hope it helps to speed up the process to migrate testing code from CCv0 -> main.
I chose to deploy and managed a k8s locally with kcli (https://github.com/karmab/kcli) because it is a tool that I use almost everyday (so I know it quite well). I know that @fidencio used to use it, and I suspect others on the community use too.
kcli will be …
> ci: k8s: adapt gha-run.sh to run locally

- src/dragonball/src/hypervisor_metrics.rs
- src/dragonball/src/metric.rs
- src/dragonball/src/signal_handler.rs
- src/dragonball/src/vcpu/aarch64.rs
- src/dragonball/src/vcpu/vcpu_impl.rs
- src/dragonball/src/vcpu/vcpu_manager.rs
- src/dragonball/src/vcpu/x86_64.rs
In this PR, the vcpu metrics in Dragonball will be changed to record per-vcpu.
Fixes: #7248
Signed-off-by: lisongqian <mail@lisongqian.cn>
> dragonball: vcpu metrics change to be recorded per vcpu

- src/libs/kata-types/src/mount.rs
- src/tools/kata-ctl/src/ops/volume_ops.rs
Direct-volume needs to use the same base64 character set as kata-runtime/direct-volume does.
Fixes: #8175
> runitme-rs: use the same base64 as kata-runtime/direct-volume does

- src/libs/Cargo.lock
- src/libs/kata-sys-util/Cargo.toml
- src/libs/kata-sys-util/src/protection.rs
- src/runtime-rs/Cargo.lock
- src/runtime-rs/crates/hypervisor/ch-config/src/convert.rs
- src/runtime-rs/crates/hypervisor/ch-config/src/lib.rs
- src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
Improve the `GuestProtection` handling to detect the version of Intel TDX available.
The TDX version is now logged by the Cloud Hypervisor driver.
Fixes: #8147.
> runtime-rs: ch: Detect Intel TDX version

- tests/metrics/storage/README.md
This PR removes the reference in the documentation to the DAX subtest of the FIO benchmark, because this metric is currently WIP.
Fixes: # 8159
> metrics: removal of reference in the documentation to the fio dax subtest.

- src/runtime/virtcontainers/fs_share_linux.go
kata-shim CCv0 does not propagate dynamically updated k8s secret values due to incorrect file name matching. This 
patch fixes the the wrong file name matching for k8s secret volume paths.
Note that this problem has already fixed in the main branch.
https://github.com/kata-containers/kata-containers/blob/538131ab449f85bc9533bb04ab8b2788e4d4e830/src/runtime/virtcontainers/fs_share_linux.go#L311
Fixes: #8208
> CCv0: runtime: fix k8s secret issue with remote hypervisor

- src/dragonball/Cargo.lock
- src/dragonball/Cargo.toml
- src/dragonball/src/dbs_virtio_devices/src/fs/device.rs
- src/runtime-rs/Cargo.lock
- src/runtime-rs/crates/resource/src/rootfs/nydus_rootfs.rs
- tests/integration/nydus/nydus_tests.sh
```
Since Nydus snapshotter has been updated in previous commits, there is a problem that the config passthrough to Dragonball during mount_rafs is RafsConfig instead of ConfigV2, but Dragonball could only serde ConfigV2 so it will panic.
We need to add the support for RafsConfig
fixes:# 8013
```
```
1. enable virtio-fs-pro in Dragonball to have the ability to process nydus backend registry
2. change passthrough for rw layer's readonly config to false to have the accurate read write ability.
Fixes:https://github.com/kata-containers/kata-containers/issues/8013
```
> runtime-rs : fix Nydus support for runtime-rs + Dragonball

- tests/metrics/lib/common.bash
This PR corrects the init env() helper function, to make that systemctl always returns true when enumerating masked services, and preventing the test from failing
Fixes: #8242
> metrics: fixes common.sh function to always return true

- src/runtime/pkg/katautils/config.go
- src/runtime/pkg/katautils/config_test.go
Previously, if you accidentally modified the name of the hypervisor section in the config file, the default golang runtime gives a cryptic error message ("`VM memory cannot be zero`"). This can be demonstrated using the `kata-runtime` utility program which uses the same golang config package as the actual runtime (`containerd-shim-kata-v2`):
```bash
$ kata-runtime env >/dev/null; echo $?
0
$ sudo sed -i 's!^\[hypervisor\.qemu\]!\[hypervisor\.foo\]!g' /etc/kata-containers/configuration.toml
$ kata-runtime env >/dev/null; echo $?
VM memory cannot be zero
1
```
The hypervisor name is now validated so that the behaviour becomes:
```bash
$ kata-runtime env >/dev/null; echo $?
0
$ sudo sed -i 's!^\[hypervisor\.qemu\]!\[hypervisor\.foo\]!g' /etc/kata-containers/configuration.toml
$ …
```
> runtime: Validate hypervisor section name in config file

- src/runtime-rs/crates/hypervisor/src/ch/inner.rs
- src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
If you attempt to create a container (a TD) on a TDX system using a
custom build of Cloud Hypervisor (CH) that was not built with the `tdx`
CH feature, Kata will report the following, somewhat cryptic, CH error:
```
ApiError(VmBoot(InvalidPayload))
```
Newer versions of CH now report their build-time features in the ping
API response message so we now use that, if available, to detect this
scenario and generate a user-friendly error message instead.
Also adds a commit to check for TDX as this is the only expected guest
protection for CH for now.
Fixes: #8152.
> runtime-rs: ch: Add TDX CH features check

- docs/how-to/how-to-run-kata-containers-with-SNP-VMs.md
This PR fixes the correct path to setup, build and install properly the kernel for snp.
Fixes #8156
> docs: Fix paths to build kernel in SNP VMs documentation

- tests/integration/kubernetes/k8s-credentials-secrets.bats
Skip this check with firecracker as expected.
Fixes #8259
> ci: k8s: Fix bogus firecracker check in k8s-credentials-secrets.bat

- src/libs/kata-sys-util/src/protection.rs
Add the missing closing bracket to the output of the TDX details, so rather than:
```bash
$ sudo kata-ctl env 2>/dev/null | grep available_guest_protection
available_guest_protection = "tdx (major_version: 1, minor_version: 0"
:                                                                    ^
:                                                           Missing ')' !
```
... we now have:
```bash
$ sudo kata-ctl env 2>/dev/null | grep available_guest_protection
available_guest_protection = "tdx (major_version: 1, minor_version: 0)"
:                                                                    ^
:                                                                   Aha!
```
Added a unit test for this scenario.
Fixes: #8257.
> libs: protection: Fix typo in TDX output

- tools/packaging/release/update-repository-version.sh
This is needed in order to properly run the CIs in branches that are not the main one, as the kata-deploy.yaml file on those branches do not have the `latest` tag, but rather the latest stable release.
Fixes: #8274
> release: Adapt the CIs using the kata-deploy image

- .github/workflows/release.yaml
hub is now deprecated, which has been causing issues with our release process.
Let's move to the GH cli (https://cli.github.com/manual), and unblock this release.
**NOTE**: This commit is purposefully not touching anywhere else hub is used, as that would require more time and investigation to do the switch, and right now we just want to unblock the release.
Fixes: #8286
> actions: release: Use GH cli instead of hub

- src/runtime/virtcontainers/network.go
- src/runtime/virtcontainers/network_darwin.go
- src/runtime/virtcontainers/network_linux.go
- src/runtime/virtcontainers/qemu.go
Currently, ACPI PCI device hotplug is not supported on Qemu/Virt and SHPC is disabled in kata. The only way to hotplug pci device is pcie native way.
This patch set will create enough pcie root port for the nacessary devices, like network device, virtio-mem and vhostUserBlk. Then adjust the code for hotplugging network dev and virtio-mem to let them hot add dev to pcie root port.
Fixes: #7646
> AArch64: runtime: use pcie root port to do pci/pcie device hotplug

- src/dragonball/src/dbs_virtio_devices/src/balloon.rs
- src/dragonball/src/device_manager/balloon_dev_mgr.rs
- src/dragonball/src/metric.rs
This PR adds metrics support for balloon device and outputs the metrics to runtime.
Fixes: #7248
Signed-off-by: lisongqian <mail@lisongqian.cn>
> dragonball: add metrics support for balloon device

- utils/kata-manager.sh
kata-manager currently adds default config which currently is qemu. Add config for clh as well to containerd configuration.
Fixes: #8280
> kata-manager: Add clh config to containerd config file

- .github/workflows/static-checks.yaml
In the migration from the tests repo to the kata containers repo we missed two huspell dictionaries for static checks; add them.
Fixes #8315
> gha: add dependencies for spell checker

- src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
- src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/DiskConfig.md
- src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_disk_config.go
- src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
- versions.yaml
This patch is backporting #8058 to the Stable-3.2 branch mainly due to the recent security advisory published from the `vm-memory` crate (https://github.com/advisories/GHSA-49hh-fprx-m68g).
See: https://github.com/kata-containers/kata-containers/issues/8057#issuecomment-1764962600
> Stable-3.2 | Upgrade to Cloud Hypervisor v35.0

- tests/git-helper.sh
In bare-metal machines the git tree might get on unstable state with the previous rebase left halfway. So let's attempt to abort any rebase before.
Fixes #8318
> tests/git-helper: cancel any previous rebase left halfway

- src/agent/Cargo.lock
- src/agent/rustjail/src/container.rs
- src/agent/rustjail/src/specconv.rs
- src/agent/rustjail/src/validator.rs
- src/agent/src/rpc.rs
- src/agent/src/sandbox.rs
- src/libs/kata-types/src/annotations/cri_containerd.rs
- src/libs/kata-types/src/annotations/crio.rs
- src/libs/kata-types/src/annotations/mod.rs
- src/libs/kata-types/src/config/runtime.rs
- src/libs/kata-types/src/config/shared_mount.rs
- src/libs/kata-types/src/k8s.rs
- src/libs/protocols/protos/agent.proto
- src/runtime-rs/crates/agent/src/kata/trans.rs
- src/runtime-rs/crates/agent/src/types.rs
- src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs
- src/tools/runk/Cargo.lock
- src/tools/runk/libcontainer/src/init_builder.rs
- src/tools/runk/libcontainer/src/utils.rs
Some workloads need a sidecar to mount some storage and share it with the application container. This feature supports sharing mount objects directly between containers through annotations. Thus, the application container can access the storage mounted by the sidecar.
The advantage of using a sidecar to mount devices is that the sidecar can act as a FUSE daemon, which can work with the user namespace to achieve non-privileged mounting.
To enable this feature, simply declare it within the annotations like this. This is a JSON-formatted list containing some shared mount declarations. Each declaration must include the following fields:
- `name` to uniquely identify a pair of mount points.
- `src_ctr` specifying the source container's name.
- `src_path` indicating the source container's mount …
> agent: use open_tree()/move_mount() to set up bind mounts between containers directly.

- src/dragonball/src/dbs_legacy_devices/src/i8042.rs
- src/dragonball/src/dbs_legacy_devices/src/rtc_pl031.rs
- src/dragonball/src/dbs_legacy_devices/src/serial.rs
- src/dragonball/src/device_manager/legacy.rs
- src/dragonball/src/device_manager/mod.rs
- src/dragonball/src/metric.rs
This PR unifies the legacy device metrics interface and outputs the metrics to runtime.
Fixes: #7248
Signed-off-by: lisongqian <mail@lisongqian.cn>
> dragonball: add metrics support for legacy device

- src/runtime/cmd/kata-runtime/kata-env.go
- src/tools/kata-ctl/Cargo.lock
- src/tools/kata-ctl/src/ops/env_ops.rs
Add the hypervisor security details to the output of the `kata-runtime env` and `kata-ctl env` commands so the user can see, amongst other things, the value of `confidential_guest`.
Fixes: #8313.
> kata-runtime/kata-ctl: Add security details to output

- src/dragonball/Cargo.lock
- src/dragonball/Cargo.toml
- src/dragonball/src/api/v1/vmm_action.rs
- src/dragonball/src/event_manager.rs
- src/dragonball/src/lib.rs
- src/dragonball/src/tracer.rs
- src/dragonball/src/vmm.rs
This PR add tracing feature for dragonball.
Fixes: #7249
Signed-off-by: lisongqian <mail@lisongqian.cn>
> dragonball: add tracing feature for dragonball

- utils/kata-manager.sh
The archive names for x86_64 [Kata releases](https://github.com/kata-containers/kata-containers/releases) used to include the tag `x86_64`, but that has now been changed to `amd64`, which unfortunately broke `kata-manager.sh`:
```
kata-static-3.1.3-x86_64.tar.xz
~~~~~~
expected
kata-static-3.2.0-alpha3-x86_64.tar.xz
~~~~~~
expected
kata-static-3.2.0-alpha4-amd64.tar.xz
~~~~~
changed
```
PR also includes lint fixes and a follow-on fix for installing containerd.
Fixes: #8321.
> utils: kata manager: Fix version checks

- tests/common.bash
- tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
- tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
- tests/metrics/cmd/checkmetrics/json.go
- tests/metrics/gha-run.sh
- tests/metrics/lib/common.bash
- tests/metrics/storage/fio-dockerfile/workload/fio_bench.sh
- tests/metrics/storage/fio_test.sh
This PR enables the new FIO test based on the containerd client
which is used to track the I/O metrics in the kata-ci environment.
Fixes: #8199
> Enable fio checkmetrics

- src/agent/src/watcher.rs
This is to skip a flaky test `create_tmpfs()` on s390x until a root cause is identified and fixed.
It would be great to get this backported onto `CCv0` to prevent the hiccup.
Fixes: #4248
> agent: Skip flaky create_tmpfs on s390x

- .github/workflows/static-checks.yaml
- src/agent/src/watcher.rs
- src/runtime/virtcontainers/ipvlan_endpoint.go
- src/runtime/virtcontainers/macvlan_endpoint.go
- tests/common.bash
- tests/git-helper.sh
- tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
- tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
- tests/metrics/cmd/checkmetrics/json.go
- tests/metrics/gha-run.sh
- tests/metrics/lib/common.bash
- tests/metrics/network/iperf3_kubernetes/k8s-network-metrics-iperf3-udp.sh
- tests/metrics/storage/fio-dockerfile/workload/fio_bench.sh
- tests/metrics/storage/fio_test.sh
- utils/kata-manager.sh
This is a list of backports, most of the patches are related to tests, but there are also 2 that are not.
The 2 that are not related to tests are:
* kata-manager fixes, for those who'll deploy kata-containers using that script
* ipvlan / macvlan fixes for nerdctl use case.
> stable-3.2 | Backport everything needed after the release till Oct 31st 2023

- src/agent/Cargo.lock
The Cargo.lock for agent needs to be updated to include "safe-path" dependency.
Fixes: #8350
> cargo: Agent cargo.lock updated

- .github/workflows/release.yaml
- tools/packaging/release/README.md
- tools/packaging/release/tag_repos.sh
- tools/packaging/release/update-repository-version.sh
- tools/packaging/scripts/lib.sh
The hub tool is deprecated. Convert the release scripts to use the official GitHub CLI gh instead.
Fixes #8303
EDIT: this also fixes this old issue
Fixes #3083
Same digits being used in both issue numbers is pure coincidence :smile:
> release: Fully migrate from hub to gh

- .github/workflows/stale.yaml
Our goal. as discussed in the Architecture Committee meeting held on October 31st, 2023, is to take a more aggressive action on issues and PRs that have been opened for a long time.
This commit is the very first step, and it's **only** targetting **PRs**.  What this action will do is:
* Mark all the PRs that have no activity for more than 180 days, starting from May 1st, 2023, as stale.
* A message will be added, letting the contributor know that they can simply comment on the PR in order to make it "not stale".
* If there's no activity on the PR for 7 days, the PR will be automatically closed.
Fixes: #8347
> gha: Add workflow to close stale PRs

- docs/hypervisors.md
The Dragonball link in the docs currently points to the archived repo, the PR updates to to point to the current repo
Fixes #8324
> Docs: Fix Dragonball link

- utils/kata-manager.sh
kata-manager is a very nice tool, but we shouldn't be trying to take
care of "everything" in "all possible scenarios", and we should focus on
installing Kata Containers dependencies that are supported.
With this in mind, let's limit a little bit the scope of which versions
of containerd can be installed, limitting to "active" and "lts", which
will then install the latest version of those "flavours".  The default
value will always be "lts" as that's supposed to be the stable one.
Fixes: #8356
While here, we're also adding a commit to ensure that `apt-get update` runs before `apt-get install`.
> kata-manager: Accept only "lts" or "active" as containerd versions

- src/runtime-rs/crates/hypervisor/ch-config/src/ch_api.rs
- src/runtime-rs/crates/hypervisor/src/ch/inner_device.rs
- src/runtime-rs/crates/hypervisor/src/ch/mod.rs
- src/runtime-rs/crates/hypervisor/src/device/driver/vfio.rs
- src/runtime-rs/crates/hypervisor/src/device/driver/virtio_blk.rs
- src/runtime-rs/crates/hypervisor/src/device/mod.rs
- src/runtime-rs/crates/hypervisor/src/dragonball/inner_device.rs
- src/runtime-rs/crates/hypervisor/src/dragonball/mod.rs
- src/runtime-rs/crates/hypervisor/src/lib.rs
- src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
- src/runtime-rs/crates/hypervisor/src/qemu/mod.rs
- src/runtime-rs/crates/resource/src/manager_inner.rs
- src/runtime-rs/crates/resource/src/share_fs/share_virtio_fs.rs
runtime-rs: change hypervisor add_device trait to return device copy
Block(virtio-blk) and vfio devices are currently not handled correctly
by the agent as the agent is not provided with correct PCI paths for
these devices.
The PCI paths for these devices can be inferred from the PCI information
provided by the hypervisor when the device is added.
Hence changing the add_device trait function to return a device copy
with PCI info potentially provided by the hypervisor. This can then be
provided to the agent to correctly detect devices within the VM.
This commit includes implementation for PCI info update for
cloud-hupervisor for virtio-blk devices with stubs provided for other
hypervisors.
This PR fixes virtio-block device addition bug. The following works now:
```
$ sudo ctr run --runtime …
```
> runtime-rs: update device pci info for vfio and virtio-blk devices

- src/agent/Cargo.lock
- src/agent/Cargo.toml
- versions.yaml
Update toml and yaml files for v0.8.0 of image-rs, AA, and td-shim.
Fixes: [#8352](https://github.com/kata-containers/kata-containers/issues/8352)
> CCv0: Set v0.8.0 tag for image-rs, AA and td-shim

- tests/integration/cri-containerd/integration-tests.sh
After running cri-containerd/integration-tests twice we receive permission denied during containerd clean.
Fixes: #8216
> tests: fixes permission denied when running test

- src/runtime-rs/crates/hypervisor/ch-config/src/convert.rs
- src/runtime-rs/crates/hypervisor/ch-config/src/errors.rs
Remove the redundant `VmConfigError::EmptyVsockSocketPath` error from
the Cloud Hypervisor config crate since this scenario is already handled
by the `VsockConfigError::NoVsockSocketPath` error.
Also removes an unused function.
Fixes: #8385.
> runtime-rs: ch: Simplify VSOCK error handling

- src/runtime/virtcontainers/qemu.go
- tests/integration/nerdctl/gha-run.sh
network: Fix network hotplug for ipvlan and macvlan endpoints.
Since moving from network coldplug to hotplug, the only case verified
was veth endpoints. Support for network hotplug for ipvlan and macvlan was
broken/not added. Fix it.
Fixes: https://github.com/kata-containers/kata-containers/issues/8391
Add test to verify kata supports ipvlan networks.
This test can be bit tricky as it requires knowledge about host interfaces to be used as a master for the ipvlan network.
However, with github actions, we can assume interface called eth0 to be present on the host(VM) and functioning.
Fixes: #8366
> network: Fix network hotplug for ipvlan and macvlan endpoints for qemu and add tests

- src/runtime/cmd/kata-runtime/kata-check_amd64_test.go
`TestCheckHostIsVMContainerCapable` removes `sysModuleDir` to simulate a
case that the kernel modules are not loaded. However,
`checkKernelModules()` executes `modprobe <module>` if a module not
found in that directory. Loading those modules is required to be denied
temporarily.
Fixes: #8390
Signed-off-by: Xuewei Niu <niuxuewei.nxw@antgroup.com>
> runtime: Fix TestCheckHostIsVMContainerCapable unstablity issue

- src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
- src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/ConsoleConfig.md
- src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/NumaConfig.md
- src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/VmmPingResponse.md
- src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_console_config.go
- src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_numa_config.go
- src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vmm_ping_response.go
- src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
- versions.yaml
v36.0. The following user visible changes have been made:
We switched back to use the `clap` crate to create our command line,
since the `argh` crate is barely maintained. There were several syntax
changes:
* All `--option value` commands now are `--option=value`.
* The `--disk DISK1 --disk DISK2` command now is `--disk DISK1 DISK2`.
* The `-v -v -v`command now is `-vvv`.
Note: the released binary size increased around 0.3M due to this change.
Now the enabled (Cargo) features of the running Cloud Hypervisor
instance can be queried via API endpoint (`/vmm.ping`) and CLI
(`--version -v`).
The `--numa` command is augmented with a new option `pci_segment=`, so
that users …
> Upgrade to Cloud Hypervisor v36.0

- tests/gha-run-k8s-common.sh
It seems that with the new k3s release, they've bumped their kubectl version from x.y.z+k3s1 to x.y.z+k3s2.
Let's ensure our regexp is more generic and future proof for such changes.
Fixes: #8410
> gha: Fix regex used to get kubectl version from the k3s version

- src/runtime/virtcontainers/qemu.go
- tests/integration/nerdctl/gha-run.sh
The PR includes backports related to bug fix for qemu related to ipvlan+macvlan and related nerdctl tests that verify macvlan and ipvlan with nerdctl for all hypervisors:
97845c93d network: Fix network hotplug for ipvlan and macvlan endpoints.
4667b837c tests: Add test with nerdctl to verify ipvlan support
08152dd46 tests: Add test with nerdctl to verify macvlan support
> network: Backports for Ipvlan qemu fix and related tests

- .github/workflows/cc-payload-amd64.yaml
We fixed this as part of the after-push PR, but we forgot to have this one fixed.
> cc: gha: kernel-snp-experimental is not a valid tag

- tests/integration/kubernetes/gha-run.sh
- tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
- tools/packaging/kata-deploy/scripts/kata-deploy.sh
Currently the only way one can specify allowed hypervisor annotations is
during build time, which is a big issue for users grabbing kata-deploy
as we provide.
Fixes: #8403
---
Although a formal test for this is not provided, we're testing this as part of all the deployments / tests using CBL mariner, as we're set the extra "initrd" and "kernel" to the allowed list of hypervisor annotations.
@sprt, I'd appreciate a lot a review and tests from your side to make sure this is working as expected with CBL mariner.
> kata-deploy: Allow users to set hypervisor annotations

- src/agent/src/metrics.rs
Update AGENT_THREADS values when the metrics of agent are requested.
Fixes: #8369
> agent: update AGENT_THREADS metrics value

- src/runtime-rs/crates/resource/src/volume/mod.rs
- src/runtime-rs/crates/resource/src/volume/shm_volume.rs
is_shim_volume should be is_shm_volume in shm_volume mod.
fixes: #8168
> runtime-rs: fix a typo in shm

- utils/kata-manager.sh
Add support for also installing the Docker CLI, giving users the chance
to try Kata Containers with docker in the same way we provide users the
chance to try Kata Containers with `ctr`.
Fixes: https://github.com/kata-containers/kata-containers/issues/8357
> kata-manager: Add support for Docker CLI installation

- docs/Release-Process.md
Reflect latest changes in the documentation :
- No longer run kata-deploy test when releasing
- Release now uses the official GitHub CLI
- No longer release the test repository
Fixes #8302
> Update release process documentation

- utils/kata-manager.sh
Add an extra sanity check to ensure that only a single download URL is
found for the specified release version.
Fixes: #8364.
> utils: kata-manager: Ensure only one download URL

- src/runtime-rs/Cargo.lock
- src/runtime-rs/crates/hypervisor/Cargo.toml
- src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
PR #8311 inadvertently broke the runtime-rs / Cloud Hypervisor TDX handling. It also introduced unrecoverable failure scenarios. Hence, replace slow, fallible regex matching in logging fast path with single pass non-failing multi-string log level matching.
Also, added a unit test for `parse_ch_log_level()`.
Fixes: #8418.
> runtime-rs: ch: Fix TDX

- tests/common.bash
- tests/metrics/lib/common.bash
This PR makes the change to using the SIGKILL signal instead of SIGTERM to force stop each kata component before start running any metric test.
Fixes: #8336
> metrics: Fix function that completely stops kata containers before running a test

- utils/kata-manager.sh
Add a command-line option to list the installed and available versions
of Kata, containerd and Docker.
Also contains a few extra code improvements.
Fixes: #8355.
> utils: kata-manager: Add option to list versions

- .github/workflows/ci.yaml
> [!NOTE]  
> The latest main branch's `ci.yaml` rather than this patch's is used to perform the CI. Therefore, "kata-containers-ci-on-push/*" tests of this pull request still go failure.
Two workflows, run-nerdctl-tests-on-garm.yaml and
run-docker-tests-on-garm.yaml, are removed from commit b481d39. However,
they are referenced by CI workflow. It leads to the CI not working
properly. This patch is to remove those files from ci.yaml.
Fixes: #8433
> gha: Remove docker and nerdctl tests from ci.yaml

- src/dragonball/src/api/v1/virtio_net.rs
- src/dragonball/src/api/v1/vmm_action.rs
- src/dragonball/src/dbs_virtio_devices/Cargo.toml
- src/dragonball/src/dbs_virtio_devices/src/lib.rs
- src/dragonball/src/dbs_virtio_devices/src/net.rs
- src/dragonball/src/dbs_virtio_devices/src/vhost/vhost_kern/net.rs
This patch is to remove vhost-net dependency on virtio-net from
dbs-virtio-devices crate. Then, the feature of vhost-net is able to enable
without enabling virtio-net device, error, etc.
Fixes: #8423
> dragonball: Remove vhost-net dependency on virtio-net

- .github/workflows/ci-nightly-s390x.yaml
This is to add a workflow for internal nightly tests for s390x in Jenkins.
This will replace the following CI job in Jenkins:
- http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-20.04-s390x-VFIO-AP-daily/
Fixes: #7986
> tests|gha: add nightly tests for s390x

- .github/workflows/build-kata-static-tarball-amd64.yaml
- .github/workflows/build-kata-static-tarball-arm64.yaml
- .github/workflows/build-kata-static-tarball-s390x.yaml
these tarballs are useful for debugging and re-running jobs, keep them for 15 days.
Fixes: #8000
> gha: Keep kata tarballs for 15 days

- tests/metrics/network/README.md
This PR adds the iperf udp information to the network README for the kata metrics CI.
Fixes #8452
> metrics: Add iperf udp information to README

- .github/workflows/ci-nightly-s390x.yaml
- .github/workflows/ci.yaml
- .github/workflows/run-cri-containerd-tests-s390x.yaml
- .github/workflows/run-k8s-tests-on-zvsi.yaml
- tests/common.bash
- tests/integration/kubernetes/filter_k8s_test.sh
- tests/integration/kubernetes/gha-run.sh
As part of the CI migration, this PR is to add workflows for containerd and k8s for s390x.
This will replace the following CI jobs in Jenkins:
- http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-ubuntu-s390x-main-PR/
- http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-s390x-main-PR/
Fixes: #7930
> tests|gha: add containerd and k8s tests for s390x

- src/runtime-rs/crates/resource/src/volume/block_volume.rs
- src/runtime-rs/crates/resource/src/volume/mod.rs
- src/runtime-rs/crates/resource/src/volume/utils.rs
When multiple containers in a kata pod share one direct volume, it's important to make sure that the corresponding block device is only mounted once in the guest. This means that there should be only one mount entry for the device in the mount information.
Fixes: #8328
> runitme-rs/bugfix: kata pod with multi-containers sharing one direct volume

- tools/packaging/kata-deploy/scripts/kata-deploy.sh
As a follow-up PR for #8404 (specifically https://github.com/kata-containers/kata-containers/commit/023c4a17cff82b547426932f4bc53e89c7817d03), this is to set a default value for an environment variable `ALLOWED_HYPERVISOR_ANNOTATIONS`. This will prevent a pod launching without an explicit configuration for the variable from getting into a `CrashLoop` state.
Fixes: #8477
> kata-deploy: Set a default value for ALLOWED_HYPERVISOR_ANNOTATIONS

- src/dragonball/src/dbs_virtio_devices/src/block/device.rs
- src/dragonball/src/dbs_virtio_devices/src/fs/device.rs
- src/dragonball/src/dbs_virtio_devices/src/vsock/epoll_handler.rs
- src/dragonball/src/device_manager/balloon_dev_mgr.rs
- src/dragonball/src/device_manager/blk_dev_mgr.rs
- src/dragonball/src/device_manager/fs_dev_mgr.rs
- src/dragonball/src/device_manager/mem_dev_mgr.rs
- src/dragonball/src/device_manager/memory_region_handler.rs
- src/dragonball/src/error.rs
The changes are:
- VirtIoError -> VirtioError
- VirtIoResult -> VirtioResult
- VirtIoDevice -> VirtioDevice
Fixes: #8464
> dragonball: Uniform the spelling of Virtio

- src/dragonball/src/dbs_boot/src/x86_64/mptable.rs
- src/dragonball/src/dbs_virtio_devices/src/balloon.rs
- src/dragonball/src/vm/x86_64.rs
In order to support PCI VFIO functionality in Dragonball, we should first add PCI bus and PCI device Interrupt information in Dragonball mptable setup process.
This patch add :
1. pci_legacy_irqs transfered to setup_mptable function.
2. pci bus support in mptable mem
3. pci interrupt support in mptable mem
fixes: #8449
> Dragonball: add PCI bus and PCI interrupt support in mptable Spec

- src/runtime/virtcontainers/types/virtual_volume.go
- src/runtime/virtcontainers/types/virtual_volume_test.go
Introduce the `KataVirtualVolume` data structure into the go kata-runtime, as specified in the kata-types through PR kata-containers/kata-containers/pull/7698. That PR is forwarded port from https://github.com/kata-containers/kata-containers/pull/7688/commits/d788d4af2ffad0affb3f8860813bb42ec673091d 
Fixes: #8472
> runtime: Introduce `KataVirtualVolume` structure into go runtime

- src/runtime-rs/crates/hypervisor/src/ch/inner_device.rs
- src/runtime-rs/crates/hypervisor/src/ch/mod.rs
- src/runtime-rs/crates/hypervisor/src/device/device_manager.rs
- src/runtime-rs/crates/hypervisor/src/device/driver/mod.rs
- src/runtime-rs/crates/hypervisor/src/device/driver/vfio.rs
- src/runtime-rs/crates/hypervisor/src/device/driver/vhost_user_blk.rs
- src/runtime-rs/crates/hypervisor/src/device/driver/virtio_blk.rs
- src/runtime-rs/crates/hypervisor/src/device/driver/virtio_fs.rs
- src/runtime-rs/crates/hypervisor/src/device/driver/virtio_net.rs
- src/runtime-rs/crates/hypervisor/src/device/driver/virtio_vsock.rs
- src/runtime-rs/crates/hypervisor/src/device/mod.rs
- src/runtime-rs/crates/hypervisor/src/dragonball/inner_device.rs
- src/runtime-rs/crates/hypervisor/src/dragonball/mod.rs
- src/runtime-rs/crates/hypervisor/src/dragonball/vmm_instance.rs
- src/runtime-rs/crates/hypervisor/src/lib.rs
- src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
- src/runtime-rs/crates/hypervisor/src/qemu/mod.rs
- src/runtime-rs/crates/resource/src/manager_inner.rs
- src/runtime-rs/crates/resource/src/rootfs/mod.rs
- src/runtime-rs/crates/resource/src/rootfs/nydus_rootfs.rs
- src/runtime-rs/crates/resource/src/share_fs/mod.rs
- src/runtime-rs/crates/resource/src/share_fs/share_virtio_fs.rs
- src/runtime-rs/crates/resource/src/share_fs/share_virtio_fs_inline.rs
- src/runtime-rs/crates/resource/src/share_fs/share_virtio_fs_standalone.rs
Currently, virtio-fs is still outside of the device manager. This causes some management issues, such as the inability to unify PCI address management.
To do Enhancement of device manager, it will bring virtio-fs device in device-manager for unified management
Fixes: #7915
> runtime-rs: bringing virtio-fs device in device-manager

- .github/workflows/run-k8s-tests-on-aks.yaml
This will be used for selecting the correct runtimes and runtimeclasses to be deployed with kata-deploy.
Fixes: #8475
> tests: k8s: Allow passing rust-runtime env var to kata-deploy

- .github/workflows/build-kata-static-tarball-amd64.yaml
- .github/workflows/build-kata-static-tarball-arm64.yaml
- .github/workflows/build-kata-static-tarball-s390x.yaml
these tarballs are useful for debugging and re-running jobs, keep them for 15 days.
Fixes: #8000
Backport of: #8460
> stable-3.2 | gha: Keep kata tarballs for 15 days

- tests/metrics/machine_learning/tensorflow_resnet50_fp32.sh
This PR fixes the result finding for the general throughput for the tensorflow benchmark.
Fixes #8466
> metrics: Fix result finding in tensorflow benchmark

- src/agent/src/rpc.rs
- src/runtime/virtcontainers/fs_share_linux.go
This PR fixes k8's configmap/secrets etc update propagation when filesystem sharing is disabled.
The commit introduces below changes with some limitations:
- creates new timestamped directory in guest
- updates the '..data' symlink
- creates user visible symlinks to newly created secrets.
- Limitation: The older timestamped directory and stale user visible symlinks exist in guest due to missing DELETE api in agent.
Fixes: #7398
> runtime: Fix configmap/secrets updates with FS sharing disabled

- .github/workflows/build-kata-static-tarball-ppc64le.yaml
- .github/workflows/ci.yaml
- .github/workflows/payload-after-push.yaml
- .github/workflows/publish-kata-deploy-payload-ppc64le.yaml
- .github/workflows/release-ppc64le.yaml
- .github/workflows/release.yaml
- tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
- tools/packaging/kata-deploy/local-build/dockerbuild/install_oras.sh
- tools/packaging/static-build/qemu.blacklist
- tools/packaging/static-build/qemu/Dockerfile
- tools/packaging/static-build/shim-v2/build.sh
This is the first step of the migration of jobs from Jenkins to GHA. 
Fixes: #8458
> github: add workflows for building and publishing kata artefacts on ppc64le

- .github/workflows/ci.yaml
- .github/workflows/run-cri-containerd-tests-ppc64le.yaml
- tests/integration/cri-containerd/gha-run.sh
- tests/integration/cri-containerd/integration-tests.sh
This PR adds workflow to run containerd tests on Power as a part of CI migration.
Fixes: #8500
> gha: add cri-containerd workflow for ppc64le

- src/runtime/virtcontainers/hypervisor_config_linux.go
This reverts commit b0157ad73a41b7e23d3c3ca7a761e27eab29ae29.
```
commit b0157ad73a41b7e23d3c3ca7a761e27eab29ae29
Refs: 3.3.0-alpha0-124-gb0157ad73
Author:     Fabiano Fidêncio <fabiano.fidencio@intel.com>
AuthorDate: Fri Aug 11 14:55:11 2023 +0200
Commit:     Fabiano Fidêncio <fabiano.fidencio@intel.com>
CommitDate: Fri Nov 10 12:58:20 2023 +0100
runtime: confidential: Do not set the max_vcpu to cpu
We don't have to do this since we're relying on the
`static_sandbox_resource_mgmt` feature, which gives us the correct
amount of memory and CPUs to be allocated.
```
This commit was removing a requirement that was made previously, but due to the SMP issue we're facing with the QEMU used for TDX (see commit …
> Revert "runtime: confidential: Do not set the max_vcpu to cpu"

- .github/workflows/build-kata-static-tarball-amd64.yaml
- .github/workflows/static-checks.yaml
This is a commit that's a pre-req for #6826, as that PR will merge log-parser-rs into kata-ctl, but that will result in a CI breakage.
So, let's deal with the CI changes here, thanks to GHA and our favourite `pull_request_target` event, unblocking that PR to be merged.
Fixes: #6797 (not really, but related).
> tools: Stop building / shipping log-parser-rs

- .github/workflows/build-kata-static-tarball-ppc64le.yaml
- .github/workflows/publish-kata-deploy-payload-ppc64le.yaml
Add step in the right place to prepare the runner for the builds/tests.
Fixes: #8525
> gha: fix artefacts build on ppc64le

- tests/integration/kubernetes/k8s-exec-rejected.bats
- tests/integration/kubernetes/runtimeclass_workloads/k8s-policy-exec-rejected.yaml
Print more information useful for debugging. Also, use a separate YAML file for this test, instead of reusing someone else's file.
Fixes: #8270
> tests: more k8s-exec-rejected debug output

- tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
This PR fixes the iperf parallel bandwidth limit for the kata metrics CI.
Fixes #8530
> metrics: Fix iperf parallel bandwidth limit

- src/runtime-rs/crates/hypervisor/ch-config/src/ch_api.rs
- src/runtime-rs/crates/hypervisor/src/ch/inner_device.rs
Update cloud hypervisor implementation to allow hybrid vsock devices to be handled.
Fixes #6692
> runtime-rs: Add Hybrid VSOCK device handling for CH

- src/libs/logging/src/lib.rs
PR #8311 inadvertently broke the logging since no log messages below the `Info` level are logged now, regardless of the requested log level.
Resolve the issue by storing the requested log level in the `RuntimeComponentLevelFilter` and using that level in the `log()` function, rather than hard-coding `Info` as the default where no entry is found in the `FILTER_RULE` hashmap.
Fixes: #8546.
> libs:logging: Fix logger

- src/dragonball/.gitignore
- src/dragonball/README.md
- src/dragonball/src/dbs_pci/Cargo.toml
- src/dragonball/src/dbs_pci/README.md
- src/dragonball/src/dbs_pci/src/bus.rs
- src/dragonball/src/dbs_pci/src/configuration.rs
- src/dragonball/src/dbs_pci/src/device.rs
- src/dragonball/src/dbs_pci/src/lib.rs
This commit inits dbs-pci lib for Dragonball to use. It contains several implementation now:
1. PCI configuration space
2. PCI bus
More info of the design & behavior of those two features could be found in the README of dbs-cli.
fixes: #8479
> dragonball: init dbs-pci lib with pci bus & pci conf

- src/libs/kata-sys-util/src/protection.rs
- src/tools/kata-ctl/src/ops/env_ops.rs
It is no longer necessary to be `root` to query the guest protection
(TDX) on `x86_64` systems, so drop the requirement.
Also update `kata-ctl` to remove the duplicate, and now redundant, root check.
Fixes: #8548.
> libs: protection: x86_64: drop root requirement for querying

- .github/workflows/basic-ci-amd64.yaml
This PR adds the cloud runtime rs as part of the containerd stability tests.
Fixes #8462
> gha: Add cloud runtime rs as part of the stability tests

- docs/how-to/containerd-kata.md
This PR updates the cri installation url link for the containerd documentation.
Fixes #8539
> docs: Update cri installation url link

- src/libs/kata-types/src/config/mod.rs
- src/runtime-rs/crates/runtimes/src/manager.rs
- src/runtime-rs/crates/service/src/task_service.rs
PR #8483 changed the location of the rust runtime config files to
`/etc/kata-containers/runtime-rs/`. However, if you haven't updated your
system to create that directory, attempting to create a container using
the rust runtime was giving the following cryptic message
(formatted for easier reading):
```
failed to handler message try init runtime instance
Caused by:
0: load config
1: load toml config
2: entity not found
```
Now, the message is as follows (again, reformatted for easier reading):
```
failed to handle message try init runtime instance
Caused by:
0: load config
1: load TOML config failed (tried [
\"/etc/kata-containers/runtime-rs/configuration.toml\",
\"/usr/share/defaults/kata-containers/runtime-rs/configuration.toml\", …
```
> runtime-rs: Show config files attempted on config load failure

- src/runtime/virtcontainers/container.go
- src/runtime/virtcontainers/mount.go
- src/runtime/virtcontainers/mount_linux_test.go
Device mapper is the only supported block device driver so far, which seems limiting. Kata Containers can work well with other block devices. It is necessary to enhance supporting of multiple kinds of host block device.
Fixes #4714
Signed-off-by: yuchen.cc <yuchen.cc@alibaba-inc.com>
> mount: support checking multiple kinds of block device driver

- .github/workflows/basic-ci-amd64.yaml
- .github/workflows/run-k8s-tests-on-garm.yaml
- tests/integration/cri-containerd/gha-run.sh
- tests/integration/kubernetes/gha-run.sh
- tests/stability/gha-run.sh
@studychao poked me about having this enabled in the CI, but not fully running, so his team can have an easy way to test it in the CI in order to fully enable them.
> gha: dragonball: Enable, but do not run, cri-containerd, stability, and devmapper tests

- .github/workflows/basic-ci-amd64.yaml
This will ensure no job will be stuck forever, as we've noticed with a few jobs already.
Fixes: #8572
> gha: basic-ci: Add a timeout for the tests

- tools/osbuilder/image-builder/image_builder.sh
In the `image_builder.sh`, `part_start` of `image` and `dax_image` should exactly specify the same location, according to the parted documentation (https://www.gnu.org/software/parted/manual/parted.html#IEC-binary-units), to exactly specify the location, the units of partition start and end should use MiB.
Fixes: #8435
> image-builder: bugfix incorrect partition location

- docs/how-to/containerd-kata.md
This PR updates the config containerd url link in the containerd kata documentation.
Fixes #8577
> docs: Update config containerd url link

- tests/git-helper.sh
It is to remove a GITHUB_WORKSPACE directory for self-hosted runners when a workflow fails due to the merge conflict. This will prevent the subsequent workflows from getting stuck in the same situation.
Fixes: #8600
> GHA: remove GITHUB_WORKSPACE when workflow fails due to merge conflict

- tests/metrics/machine_learning/resnet50_fp32_dockerfile/Dockerfile
- tests/metrics/machine_learning/tensorflow_resnet50_fp32.sh
This PR updates the python version for the TensorFlow ResNet FP32 dockerfile so the benchmark can run without issues.
Fixes #8593
> metrics: Update TensorFlow ResNet FP32 dockerfile

- .github/workflows/basic-ci-amd64.yaml
- tests/integration/nerdctl/gha-run.sh
This PR enables the cloud hypervisor runtime-rs for the nerdctl gha CI.
Fixes #8603
> gha: nerdctl: Enable cloud hypervisor runtime-rs for nerdctl CI

- src/runtime-rs/crates/hypervisor/src/ch/inner_device.rs
Implement try_from trait function to convert runtime-rs BlockConfig to cloud-hypervisor DiskConfig. This can allow for code reuse in the future.
Fixes: #8581
> Implement and use try_from for DiskConfig

- src/libs/kata-types/src/annotations/mod.rs
If a wrong configuration.toml file is used by accidentally, runtime-rs binary could run into panic because of unwrap().
This fixes the panic by returning errors instead of unwrap().
Fixes: #8565
--
v3:
* Rebased to the latest main branch(9d38f01c2fe3c7b9cc63904f7c961948e56ca128).
v2: 
* Added fixes label in the commit log.
* Updated the error msg to "hypervisor name" instead.
> runtime-rs: fix panic when hypervisor mismatches with configuration

- tests/gha-run-k8s-common.sh
This is to fix a broken usage for `k3s kubectl version` by switching an option `--short` to `--client=true`.
Fixes: #8621
> GHA: Use --client=true for k3s kubectl version

- docs/install/azure-installation-guide.md
- tests/static-checks.sh
Make the URL checker cycle through a list of user agent values until we
hit one the remote server is happy with.
This is required since, unfortunately, we really, really want to check
these URLs, but some sites block clients based on their `User-Agent`
(UA) request header value. And of course, each site is different and can
change its behaviour at any time.
Our strategy therefore is to try various UA's until we find one the
server accepts:
- No explicit UA (use `curl`'s default)
- Explicitly no UA.
- A blank UA.
- Partial UA values for various CLI tools.
- Partial UA values for various console web browsers.
- Partial UA for Emacs's built-in browser.
- The existing UA which is used as a "last ditch" attempt where the UA implies multiple platforms and browser.
> **Notes:**
>
> - The …
> CI: static-checks: Try multiple user agents 

- tools/packaging/kata-deploy/runtimeclasses/kata-qemu-se.yaml
- tools/packaging/kata-deploy/runtimeclasses/kata-runtimeClasses.yaml
This is to fix an error on kata-deploy-runtime-classes-check for kata-qemu-se.
Fixes: #8623
> GHA: Fix kata-deploy-runtime-classes-check for kata-qemu-se

- tools/osbuilder/rootfs-builder/rootfs.sh
This PR is to build a binary for OPA from source code for ppc64le and s390x.
Fixes: #7616
> rootfs: build OPA binary from source for ppc64le and s390x

- src/dragonball/Makefile
- src/dragonball/src/dbs_pci/src/bus.rs
- src/dragonball/src/dbs_pci/src/lib.rs
- src/dragonball/src/dbs_virtio_devices/src/lib.rs
- src/dragonball/src/dbs_virtio_devices/src/vhost/vhost_kern/net.rs
- src/dragonball/src/dbs_virtio_devices/src/vhost/vhost_user/test_utils.rs
Right now, cargo fmt check in Dragonball only test with the default features but not all features. This will cause some code being untested by the fmt tool.
This PR adds --all option for the Dragonball CI and also fix some code that forgets to do cargo fmt --all.
fixes: #8598
> dragonball: add --all for fmt ci

- tests/common.bash
- tests/integration/nerdctl/gha-run.sh
This PR enables the nerdctl tests for cloud hypervisor runtime-rs.
Fixes #8616
> tests: nerdctl: Enable nerdctl tests for cloud hypervisor runtime-rs

- src/dragonball/src/dbs_virtio_devices/src/vhost/vhost_user/connection.rs
The layout of packed virtqueue isn't supported by `Endpoint::negotiate()`.
Communication between device and driver will be failed due to the failure
of parsing virtqueue if we don't disable the packed feature. This patch
fixes this issue.
Fixes: #8633
> dragonball: Disable packed virtqueue for vhost-user devices

- src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
Make the CH (Cloud Hypervisor) `stop_vm()` method check the VM state before attempting to stop the VM, and update the state once the VM has stopped.
This avoids the method failing if called multiple times which will happen if the workload exits before the container manager requests that the container stop.
This change ensures the CH driver finishes cleanly.
Fixes: #8629.
> runtime-rs: ch: Change state when VM stopped

- src/dragonball/src/dbs_pci/README.md
- src/dragonball/src/dbs_pci/src/device.rs
- src/dragonball/src/dbs_pci/src/lib.rs
- src/dragonball/src/dbs_pci/src/root_bus.rs
- src/dragonball/src/dbs_pci/src/root_device.rs
In order to follow up the PCI implementation in Dragonball, we need to add PCI root device and root bus support.
root device is a pseudo PCI root device to manage accessing to PCI configuration space.
root bus is mainly for emulating PCI root bridge and also create the PCI root bus with the given bus ID with the PCI root bridge.
fixes: #8563
Signed-off-by: Gerry Liu <gerry@linux.alibaba.com>
Signed-off-by: Zizheng Bian <zizheng.bian@linux.alibaba.com>
Signed-off-by: Shifang Feng <fengshifang@linux.alibaba.com>
Signed-off-by: Yang Su <yang.su@linux.alibaba.com>
Signed-off-by: Zha Bin <zhabin@linux.alibaba.com>
Signed-off-by: Xin Lin <jingshan@linux.alibaba.com>
> dragonball: add pci root bus and root device

- .github/workflows/build-kata-static-tarball-s390x.yaml
- .github/workflows/ci-nightly-s390x.yaml
- .github/workflows/publish-kata-deploy-payload-s390x.yaml
- .github/workflows/run-cri-containerd-tests-s390x.yaml
- .github/workflows/run-k8s-tests-on-zvsi.yaml
This is to introduce a pre-action to all the workflows for building artifacts. The action could take care of tasks such as cleaning up files and reinstalling packages, which prevents a workflow from getting affected by the environment.
This also includes the removal of the step `Adjust a permission for repo`, because it could be incorporated into the action.
Fixes: #8648
> GHA: Put all the preliminary steps into pre-action for s390x

- src/dragonball/src/api/v1/virtio_net.rs
- src/runtime-rs/crates/hypervisor/src/ch/inner_device.rs
- src/runtime-rs/crates/hypervisor/src/device/driver/mod.rs
- src/runtime-rs/crates/hypervisor/src/device/driver/virtio_net.rs
- src/runtime-rs/crates/hypervisor/src/dragonball/inner_device.rs
- src/runtime-rs/crates/hypervisor/src/dragonball/mod.rs
- src/runtime-rs/crates/resource/src/network/endpoint/ipvlan_endpoint.rs
- src/runtime-rs/crates/resource/src/network/endpoint/macvlan_endpoint.rs
- src/runtime-rs/crates/resource/src/network/endpoint/tap_endpoint.rs
- src/runtime-rs/crates/resource/src/network/endpoint/veth_endpoint.rs
- src/runtime-rs/crates/resource/src/network/endpoint/vlan_endpoint.rs
This patch set vhost-net as default backend of networking. It allows users
to set `disable_vhost_net` to `true` to reenable virtio-net backend.
Plus, which backend to use is a matter of hypervisor, runtime-rs will no
longer need to know that.
Fixes: #8608
> dragonball: Use vhost-net device by default

- src/libs/kata-types/src/mount.rs
- src/runtime-rs/crates/resource/src/volume/direct_volumes/mod.rs
(1) Enhancement of DirectVolume when using CSI.
We use a matching direct-volume path to determine whether an OCI mount
is a DirectVolume. However, we should handle the case where no match is
found appropriately.
This error will be defined as a non-DirectVolume type when judging the
OCI mount but not failed.
(2) Add attribe serde rename to each field of DirectVolume.
DirectVolume structure in runtime-rs is different from it in kata-runtime,
which causes they has no unified handling method for DirectVolumeMountInfo
and MountInfo.
We should align the two by simply adding the attribute #[serde(rename="x")
to each field in DirectVolumeMountInfo
Fixes: #8619
> runtime-rs: Enhancement of DirectVolume when using a dedicated CSI

- .github/workflows/run-cri-containerd-tests-ppc64le.yaml
This PR identifies and adds an action to cleanup the ppc64le self hosted runner.
Fixes: #8666
> gha: add a post cleanup script for cri-containerd ppc64le workflow

- utils/README.md
According to #6259 this warning is not needed anymore.
> Remove warning for cgroupsv2 only operating systems

- tests/metrics/machine_learning/resnet50_int8_dockerfile/Dockerfile
- tests/metrics/machine_learning/tensorflow_resnet50_int8.sh
This PR updates the TensorFlow ResNet50 Int8 Dockerfile to use the proper python version for kata metrics.
Fixes #8643
> metrics: Update TensorFlow ResNet50 Int8 Dockerfile

- tests/metrics/network/latency_kubernetes/latency-network.sh
This PR improves the latency network cleanup by removing the pods even if the test fails.
Fixes #8658
> metrics: Improve latency network cleanup

- .github/workflows/cargo-deny-runner.yaml
- .github/workflows/ci-on-push.yaml
- .github/workflows/darwin-tests.yaml
If a PR contains files from the ignore-paths, these actions do not run as intended. However, the actions are make as required. And there does not seem to be a way to mark these as non-required in that case. As a result a PR containing the files from the ignore-paths remains stalled.
Hence remove the ignore-paths until github provides a way to mark actions that are skipped due to ignore-paths as non-required/passed.
Fixes: #8663
> github-actions: Remove ignore paths for required CI checks

- src/tools/kata-ctl/src/args.rs
- src/tools/kata-ctl/src/main.rs
Add a `--show-default-config-paths` command line option for parity with `kata-runtime`.
Note that this requires the `KataCtlCli.command` to be optional so that the user can run simply:
```bash
$ kata-ctl --show-default-config-paths
```
... without also specifying a (sub-)command.
Fixes: #8640.
> kata-ctl: Add option to dump config files

- src/agent/rustjail/src/cgroups/systemd/subsystem/cpu.rs
If cgroup driver is systemd, CPUShares, for cgroup v1, should be at least 2 [1] and CPUWeight for cgroup v2, should be at least 1 [2].
Fixes: #8340
[1] https://github.com/systemd/systemd/blob/d19434fbf81db04d03c8cffa87821f754a86635b/src/basic/cgroup-util.h#L122
[2] https://github.com/systemd/systemd/blob/d19434fbf81db04d03c8cffa87821f754a86635b/src/basic/cgroup-util.h#L91
> agent: correct CPUShares and CPUWeight value

- ci/lib.sh
- docs/Licensing-strategy.md
- docs/presentations/unit-testing/kata-containers-unit-testing.md
Change the two functions in lib.sh to use the static checks script from
the kata containers repo instead of tests. Remove cloning the repo from
these functions since we don't need it anymore. Leave these two
functions because the document checking one may be used locally and the
static checks one is called from the virtcontainers Makefile.
Fixes #8681
> ci: Use static checks from kata repo for lib functions

- src/runtime-rs/crates/hypervisor/src/device/device_manager.rs
- src/runtime-rs/crates/hypervisor/src/device/driver/virtio_vsock.rs
As a follow-up for #8516, guest_cid and vhost_fd are not necessarily initialised via new(). Instead, the fields should be initialised later when they are really used to construct hypervisor's parameters.
This commit is to separate init_config() from new() to initialise guest_cid and vhost_fd and leave only the assignment of id for the existing function.
Fixes: #8671
> runtime-rs: Separate init_config() from new() for struct VsockDevice

- src/dragonball/Makefile
- src/dragonball/src/dbs_legacy_devices/src/i8042.rs
- src/dragonball/src/dbs_virtio_devices/src/device.rs
- src/dragonball/src/dbs_virtio_devices/src/vhost/vhost_user/fs.rs
`make SUPPORT_VIRTUALIZATION=1 test` iterates through all subcrates and
does test. 
Plus, this patch fixes some issues about unit tests:
- Feed too much parameters to `I8042Device::new()`.
- Virtqueue checks have been introduced since `virtio-queue v0.7.0`.
- GHA might have no access to `/var/tmp` dir on runner.
Fixes: #8690
> dragonball: Trigger unit tests of dbs_* subcrates by `make test`

- tests/integration/runk/runk-tests.sh
Add logging to run-runk, for debugging possible failures.
Fixes: #8696
> tests: additional run-runk logging

- src/agent/Cargo.lock
- src/agent/Cargo.toml
- src/agent/src/rpc.rs
- src/libs/Cargo.lock
- src/libs/protocols/Cargo.toml
- src/runtime/virtcontainers/kata_agent.go
fixes #8669 
The underlying issue in the dependency has been addressed, hence the revision bump of `image-rs` to use the fix in the agent. I think a fix to the CCv0 branch is warranted, since it makes all images with more than a single layer work unreliably.
cc @stevenhorsman @bpradipt
> Bump image-rs rev to include image-layer-ordering fix

- tests/integration/kubernetes/confidential_common.sh
This PR fixes the indentation of the confidential common script for kubernetes tests.
Fixes #8698
> tests: k8s: Fix indentation in confidential common script

- src/runtime-rs/README.md
Since cloud-hypervisor is no longer built as an optional feature, lets mention cloud-hypervisor in the list of hypervisors supported by runtime-rs.
Fixes: 8587
> runtime-rs: Update readme to indicate cloud-hypervisor support

- tests/functional/kata-deploy/kata-deploy.bats
- tools/packaging/kata-deploy/scripts/kata-deploy.sh
After kata-deploy has installed, check containerd is still in active state, to ensure that we didn't corrupt the containerd config during kata-deploy's edits
Fixes: #8678
> gha: kata-deploy: Revert containerd config break

- tools/packaging/kata-deploy/Dockerfile
- tools/packaging/kata-deploy/scripts/kata-deploy.sh
This is a follow-up from https://github.com/kata-containers/kata-containers/pull/8679#issuecomment-1864556280, where we've narrowed down the correct component that was causing the issue, and we can go ahead and unblock the snapshotter related work (and, consequently, the merge to main work).
> kata-deploy: Update `jq` as part of the kata-deploy daemonset

- tests/integration/kubernetes/k8s-confidential.bats
Retry because the SSH server might take some time to start up.
Fixes: #8687
> tests: retry connection to pod SSH server

- ci/lib.sh
Switch to use function from Kata repo in common.bash to reduce dependency on the tests repo.
Fixes #8713
> tests: Use function from Kata repo

- tests/common.bash
The default network backend of runtime-rs with Dragonball is vhost-net
after #8609 merged. The tests might be failed if vhost modules are not
loaded.
Fixes: #8717
> tests: Load vhost modules explicitly while Kata installing

- tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
- tools/packaging/kata-deploy/scripts/kata-deploy.sh
Since containerd 1.7.0 we can easily set a specific snapshotter to be used with a runtime handler, and we should take advantage of this, mostly as it'll help setting up any runtime using devmapper or nydus snapshotters.
This implementation here has a few caveats:
* The format expected for the SNAPSHOTTER_HANDLER_MAPPING is: `shim:snapshotter,shim:snapshotter,...`
* It only works with containerd 1.7 or newer
* We **never** change the default containerd snapshotter
* We don't do any check on our side to verify whether the snapshotter required is properly deployed
* Users will have to add an annotation to their pods, in order to use the snapshotter set up per runtime handler
* Example: ``` metadata: ... annotations: io.containerd.cri.runtime-handler: kata-fc ```
Fixes: #8615
**NOTE**: Due to …
> kata-deploy: Allow setting up snapshotters per runtime handler

- src/dragonball/src/dbs_interrupt/src/lib.rs
- src/dragonball/src/dbs_pci/Cargo.toml
- src/dragonball/src/dbs_pci/README.md
- src/dragonball/src/dbs_pci/src/lib.rs
- src/dragonball/src/dbs_pci/src/msi.rs
- src/dragonball/src/dbs_pci/src/msix.rs
introduce msi/msix mod to maintain information for PCI Message Signalled Interrupt Extended Capability. It will be initialized when parsing pci configuration space and used when getting interrupt capabilities.
fixes: #8661
Signed-off-by: Gerry Liu <gerry@linux.alibaba.com>
Signed-off-by: Zizheng Bian <zizheng.bian@linux.alibaba.com>
Signed-off-by: Shifang Feng <fengshifang@linux.alibaba.com>
Signed-off-by: Yang Su <yang.su@linux.alibaba.com>
Signed-off-by: Zha Bin <zhabin@linux.alibaba.com>
Signed-off-by: Xin Lin <jingshan@linux.alibaba.com>
---
v2
1. update vm-memory to 0.10.0 in order to keep consistent with other crates in Dragonball.
2. change according to @justxuewei comments
3. modify msix to reduce hard code and add comments.
> dragonball: introduce pci msi/msix interrupt

- src/dragonball/src/api/v1/mod.rs
- src/dragonball/src/api/v1/virtio_net.rs
- src/runtime-rs/Cargo.lock
- src/runtime-rs/crates/hypervisor/Cargo.toml
- src/runtime-rs/crates/hypervisor/src/device/device_manager.rs
- src/runtime-rs/crates/hypervisor/src/device/driver/mod.rs
- src/runtime-rs/crates/hypervisor/src/device/driver/vhost_user.rs
- src/runtime-rs/crates/hypervisor/src/device/driver/vhost_user_net.rs
- src/runtime-rs/crates/hypervisor/src/device/mod.rs
- src/runtime-rs/crates/hypervisor/src/dragonball/inner_device.rs
- src/runtime-rs/crates/resource/src/network/dan.rs
- src/runtime-rs/crates/resource/src/network/endpoint/endpoint_persist.rs
- src/runtime-rs/crates/resource/src/network/endpoint/mod.rs
- src/runtime-rs/crates/resource/src/network/endpoint/tap_endpoint.rs
- src/runtime-rs/crates/resource/src/network/endpoint/vhost_user_endpoint.rs
- src/runtime-rs/crates/resource/src/volume/direct_volumes/spdk_volume.rs
This commit introduces VhostUserEndpoint and supports relative to
vhost-user-net devices for device manager. For now, Dragonball is able to
attach vhost-user-net devices.
Fixes: #8625
> runtime-rs: Support vhost-user-net device

- tools/packaging/kata-monitor/Dockerfile
move `SKIP_GO_VERSION_CHECK` after `make` command to skip checking golang version.
And also upgrade golang to 1.19.
Fixes: #8728
> kata-monitor: fix Dockerfile to build image

- src/dragonball/Cargo.toml
- src/dragonball/src/api/v1/vmm_action.rs
- src/dragonball/src/dbs_virtio_devices/Cargo.toml
- src/dragonball/src/dbs_virtio_devices/src/lib.rs
- src/dragonball/src/dbs_virtio_devices/src/vhost/vhost_user/block.rs
- src/dragonball/src/dbs_virtio_devices/src/vhost/vhost_user/connection.rs
- src/dragonball/src/dbs_virtio_devices/src/vhost/vhost_user/mod.rs
- src/dragonball/src/dbs_virtio_devices/src/vhost/vhost_user/test_utils.rs
- src/dragonball/src/device_manager/blk_dev_mgr.rs
- src/dragonball/src/device_manager/mod.rs
- src/dragonball/src/error.rs
This patch introduces a feature of supporting vhost-user-blk device.
This device needs to be defined before the VM instance is started,
which can be done through the dbs-cli tool with --virblks option:
--virblks '{
"drive_id": "8623",
"device_type": "Spdk",
"path_on_host": "spdk:///var/tmp/vhost.sock",
"is_root_device": false,
"is_read_only": false,
"is_direct": false,
"no_drop": false,
"num_queues": 1,
"queue_size": 256
}'
Fixes: https://github.com/kata-containers/kata-containers/issues/8631
> dragonball: introduce vhost-user-blk device

- src/dragonball/src/dbs_pci/Cargo.toml
- src/dragonball/src/dbs_pci/README.md
- src/dragonball/src/dbs_pci/src/configuration.rs
- src/dragonball/src/dbs_pci/src/lib.rs
- src/dragonball/src/dbs_pci/src/msi.rs
- src/dragonball/src/dbs_pci/src/msix.rs
- src/dragonball/src/dbs_pci/src/vfio.rs
vfio mod collects lots of information related to the vfio operations, including VfioMsi and VfioMsix capability & state, vfio interrupt info, pci region infor and vfio pci device info & state.
fixes: #8722
> dragonball: introduce vfio support

- tools/packaging/kata-deploy/scripts/kata-deploy.sh
We want to check whether the shim is part of the "plain text" shims passed to the daemonset (meaning, checking against `$SHIMS`).  Before this fix we were checking against `$shims`, which is an array of shims instead of a string, resulting on a broken check.
Fixes: #8732
> kata-deploy: Fix shim check for snapshotter configuration

- src/agent/Cargo.lock
- src/agent/Cargo.toml
- src/libs/Cargo.lock
- src/libs/protocols/Cargo.toml
- src/runtime-rs/Cargo.lock
- src/runtime-rs/crates/agent/Cargo.toml
- src/runtime-rs/crates/runtimes/common/Cargo.toml
- src/runtime-rs/crates/runtimes/virt_container/Cargo.toml
- src/runtime-rs/crates/service/Cargo.toml
- src/runtime-rs/crates/shim/Cargo.toml
- src/tools/agent-ctl/Cargo.lock
- src/tools/agent-ctl/Cargo.toml
- src/tools/agent-ctl/src/client.rs
The affected crates in this repo are runtime-rs, agent, protocols and agent-ctl.
The crates that are upgraded are:
- `ttrpc` from `0.7.1` to `0.8`.
- `containerd-shim-protos` from `0.3.0` to `0.6.0`.
Fixes: #8756
> runtime-rs|agent|protocols|agent-ctl: Bump ttrpc and containerd-shim-protos versions

- src/dragonball/Cargo.lock
- src/dragonball/src/api/v1/mod.rs
- src/dragonball/src/dbs_virtio_devices/src/lib.rs
- src/dragonball/src/dbs_virtio_devices/src/net.rs
- src/dragonball/src/dbs_virtio_devices/src/net_common.rs
- src/dragonball/src/dbs_virtio_devices/src/vhost/vhost_kern/net.rs
- src/dragonball/src/dbs_virtio_devices/src/vhost/vhost_user/net.rs
Combinations of network features were tested:
- None
- virtio-net
- vhost-net
- vhost-user-net
- virtio-net,vhost-net
- vhost-net,vhost-user-net
- virtio-net,vhost-user-net
- virtio-net,vhost-net,vhost-user-net
Fixes: #8742
> dragonball: Fix compilation issue without all net features

- tests/metrics/network/iperf3_kubernetes/k8s-network-metrics-iperf3.sh
This PR improves the iperf3 cleanup to ensure all the components are being deleted properly to avoid the random failures of leaving the iperf3 clients on the kata metrics CI.
Fixes #8765
> metrics: Improve iperf3 cleanup

- docs/Developer-Guide.md
- docs/design/virtualization.md
- docs/hypervisors.md
- tests/cmd/check-spelling/data/projects.txt
- tests/cmd/check-spelling/kata-dictionary.dic
- tools/packaging/kata-deploy/README.md
As the StratoVirt VMM has been added, we can update the docs and make some intoduction to StratoVirt, thus users can know more about the hypervisor choices.
Fixes: #8645
> docs: Update docs for new StratoVirt VMM introduction

- tests/common.bash
This PR adds the qemu-experimental hypervisor in the function to kill kata components.
Fixes #8775
> tests: Add hypervisor component to kill kata components function

- src/agent/src/policy.rs
- src/agent/src/rpc.rs
Don't release the lock between is_allowed and set_policy calls, because the policy might change in between these calls.
Also, move more policy code into policy.rs.
Fixes: #8734
> agent: hold lock while setting new policy

- src/agent/rustjail/src/cgroups/notifier.rs
The agent registers an event fd in `memory.oom_control`. An OOM event is
forwarded to containerd when the event is emitted, regardless of the
content in that file.
I observed content indicating that events should not be forwarded, as shown
below. When `oom_kill` is set to 0, it means no OOM has occurred. Therefore,
it is important to check the content to avoid mistakenly forwarding OOM
events.
```
oom_kill_disable 0
under_oom 0
oom_kill 0
```
Fixes: #8715
> agent: Fix an issue reporting OOM events by mistake

- src/agent/src/network.rs
> agent: use method params instead of const params in functions

- tools/packaging/static-build/stratovirt/build-static-stratovirt.sh
This PR fixes the indentation of the build static stratovirt script for kata containers.
Fixes #8777
> packaging: Fix indentation of build static stratovirt

- tests/integration/kubernetes/run_kubernetes_tests.sh
Log the list of the current pods between tests because these pods might be related to cluster nodes occasionally running out of memory.
Fixes: #8769
> tests: list the current k8s pods

- src/runtime-rs/Cargo.lock
- src/runtime-rs/crates/runtimes/common/src/message.rs
- src/runtime-rs/crates/service/Cargo.toml
- src/runtime-rs/crates/service/src/event.rs
- src/runtime-rs/crates/service/src/lib.rs
- src/runtime-rs/crates/service/src/manager.rs
It is a little bit heavy for the runtime-rs to forward events via
containerd CLI, contrast to the ttrpc way. Plus, for runtimes that haven't
this mechanism, e.g. CRI-O, we can't get those events anywhere.
This patch introduces two types of forwarders:
- `ContainerdForwarder`: Acquire ttrpc address from environment variables
and forward events via ttrpc connection.
- `LogForwarder`: Write event info into logs.
Fixes: #7881
> runtime-rs: Forward events to containerd via ttrpc

- src/runtime/virtcontainers/hypervisor.go
- src/runtime/virtcontainers/qemu.go
- src/runtime/virtcontainers/types/asset.go
This is to reintroduce a configuration rule for IBM Z Secure Execution, where no initrd path should be configured. For the TEE of interest, only a kernel image should be specified with `confidential_guest=true`.
Fixes: #8692
Test result:
```
$ ps -ef | grep qemu | grep kernel
root      415937  415926  3 14:51 ?        00:00:02 /opt/kata/bin/qemu-system-s390x -name sandbox-217c61c958d255f517cacfe2cbb1cde84eb58a0f6af7f2a04ce98a1035c072c8 -uuid 3d1d57e4-48c4-436e-9350-2fcd2c1466d5 -machine s390-ccw-virtio,accel=kvm,confidential-guest-support=pv0 -cpu host, -qmp unix:fd=3,server=on,wait=off -m 2048M,slots=10,maxmem=15923M -device virtio-serial-ccw,id=serial0,devno=fe.0.0001 -device virtconsole,chardev=charconsole0,id=console0 -chardev …
```
> runtime: Allow no initrd path for IBM Z Secure Execution

- .github/workflows/run-metrics.yaml
- tests/common.bash
- tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-stratovirt-kata-metric8.toml
- tests/metrics/gha-run.sh
Update the metrics test baseline for StratoVirt and re-enable.
Fixes: #8656 
Related: #8496
> gha: Fix the failure of gha metrics for StratoVirt

- .github/workflows/add-backport-label.yaml
- ci/gh-util.sh
Add gh-util.sh script
- The hub tool is now deprecated, so introduce a new alternative to `hub-util.sh`
https://github.com/kata-containers/.github/blob/main/scripts/hub-util.sh
that works with it.
Initially I've only started with the couple of commands that we use regularly, but we can extend it in future.
- Expects jq to be installed and `gh` to be installed an setup (see https://docs.github.com/en/github-cli/github-cli/quickstart#prerequisites    workflows: Update backport-label to use gh-utils.sh)
- Now we don't have lots of repos, I've moved it into `kata-containers` rather than `.github`,
so it is more visible.
- Update workflow to use new script
Fixes: #8125
> Fix backport check hub

- src/runtime-rs/crates/hypervisor/src/ch/inner.rs
- src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
Unfortunately, PR #6876 broke running runtime-rs with Cloud Hypervisor so add minimal implementations of the new APIs to allow CH to be used with runtime-rs.
Full implementations will be added later on issues #8800, #8801, and #8802.
> runtime-rs: ch: Unbreak CH driver

- tests/common.bash
- tests/integration/cri-containerd/gha-run.sh
- tests/integration/cri-containerd/integration-tests.sh
- tests/stability/gha-run.sh
CI: make CI work for dragonball to test stability and cri-containerd
It needs to remove the skip setting, and make it work for dragonball.
bugfix when CI running cri-containerd
Fixes https://github.com/kata-containers/kata-containers/issues/8746
> ci: test dragonball stability and cri-containerd

- tests/metrics/machine_learning/tensorflow_nhwc_dockerfile/Dockerfile
This PR uses a specific python version to run tensorflow benchmark as it needs python 3.8 to run correctly and avoid failures.
Fixes #8791
> metrics: Use a specific python version to run tensorflow benchmark

- src/dragonball/src/dbs_virtio_devices/src/vhost/vhost_user/connection.rs
`EndpointProtocolFlags::ProtocolBackend` is removed due to no reference.
Fixes: #8745
> dragonball: Remove unused definition

- tests/integration/kubernetes/k8s-oom.bats
Disable k8s-oom.bats on cbl-mariner until it passes more often.
Fixes: #8824
> tests: cbl-mariner: disable k8s-oom.bats

- tests/metrics/network/iperf3_kubernetes/runtimeclass_workloads/iperf3-deployment.yaml
This PR removes the iperf3 server protocol as this server definition is also used for the UDP iperf3 benchmarks to avoid duplication of the same yaml files.
Fixes #8829
> metrics: Remove iperf3 server protocol

- src/tools/genpolicy/rules.rego
Temporarily disable the allow_storages() rules, because they are based on tarfs snapshotter + container image integrity information that are not available yet in the main branch - see #8833.
Fixes: #8834
> genpolicy: temporarily disable allow_storages()

- tests/metrics/density/memory_usage.sh
This PR removes the references to virtiofs from memory average calculation when the container uses a shared file system other than virtiofs.
Fixes: #8807
> tests: Ignore virtiofs contribution to memory usage when it is disabled.

- src/tools/genpolicy/genpolicy-settings.json
- src/tools/genpolicy/rules.rego
Adjust genpolicy-settings.json to match the container root path from the main branch + cbl-mariner Guest VMs.
This configuration might have to be adjusted again when other types of Guest VMs will be tested during CI using genpolicy, in the future.
Also, improve logging from allow_root_path(), to easier debug these issues in the future.
Fixes: #8835
> genpolicy: use root path from cbl-mariner Guest VM

- src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
Add implementations for the following `Hypervisor` trait methods which simply return the same details as the `get_vmm_master_tid()` method:
- `get_thread_ids()`
- `get_pids()`
Fixes: #6438.
> runtime-rs: ch: Implement minimal implementation for missing thread/pid APIs

- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Install the default genpolicy OPA rules and settings JSON files, in addition to the genpolicy binary.
Fixes: #8844
> tools: install genpolicy settings files

- .github/workflows/static-checks.yaml
- ci/install_yq.sh
- src/agent/rustjail/src/cgroups/fs/mod.rs
- src/agent/src/device.rs
- src/agent/src/netlink.rs
- src/agent/src/random.rs
- src/agent/src/rpc.rs
- src/agent/src/sandbox.rs
- src/dragonball/Makefile
- src/dragonball/src/dbs_virtio_devices/src/vhost/vhost_user/connection.rs
- src/dragonball/src/device_manager/mod.rs
- src/runtime-rs/Makefile
- src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
- src/runtime/cmd/kata-runtime/kata-env_ppc64le_test.go
- src/tools/agent-ctl/Makefile
- src/tools/kata-ctl/Makefile
- src/tools/kata-ctl/src/arch/s390x/mod.rs
- src/tools/runk/Makefile
- src/tools/runk/libcontainer/src/init_builder.rs
- src/tools/trace-forwarder/Makefile
This is to enable the static check (including a unit test) for s390x by incorporating it with the existing one for `x86_64`.
Once this PR is merged and the relevant workflows settle down, it will replace a Jenkins CI  http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-s390x-unit-PR/.
Fixes: #8482
Test result: https://github.com/BbolroC/kata-containers/actions/runs/6945353895/job/18894516175 (all failing tests are for `x86_64` and they have nothing to do with the change for this PR)
> GHA: Enable static check for s390x, aarch64 and ppc64le

- src/libs/kata-types/src/config/default.rs
- src/libs/kata-types/src/config/hypervisor/qemu.rs
- src/runtime-rs/crates/hypervisor/src/qemu/cmdline_generator.rs
- src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
- src/runtime-rs/crates/hypervisor/src/qemu/mod.rs
This PR adds a bare-bones functionality to the qemu driver.  At the moment, the VM can boot from an image or an initrd and not much more than a block device for rootfs, vsock connection for shim <-> agent communication and virtio-fs setup is handled.  This is however sufficient already to run a very simple kata container like busybox the proper way, with no hard-coded shortcuts - everything that works is set up based on hypervisor configuration and devices sent by the runtime-rs proper.  The proposed framework for qemu command line generation is heavily inspired by govmm so it shouldn't feel too foreign to anybody familiar with the golang shim qemu driver.
For the time being, the majority of `configuration.toml` is still not handled and there's no QMP support yet.  These will be addressed …
> Add qemu cmdline generation framework

- src/tools/genpolicy/src/pod.rs
Ignore pod DNS settings because policing the network traffic is currently outside the scope of the Agent Policy.
Example from Kata CI: pod-custom-dns.yaml
Fixes: #8832
> genpolicy: ignore pod DNS settings

- .github/workflows/ci.yaml
- .github/workflows/run-k8s-tests-on-aks.yaml
- tests/integration/kubernetes/gha-run.sh
The changes to install and test genpolicy must come later, after CI picks up these gha changes.
Fixes: #8856
> gha: get ready to install genpolicy

- src/runtime/pkg/govmm/qemu/qemu.go
SharedVersion fiel add a versiontable property that isn't supported by upstream QEMU. This is dead code since virtcontainers isn't setting SharedVersions to true.
Fixes: #7720
> runtime: remove SharedVersions field dead code

- docs/how-to/README.md
- docs/how-to/how-to-run-kata-containers-with-SE-VMs.md
This PR is to add a document for how to run kata containers under IBM Secure Execution environment.
Fixes: #7025
> docs: provide a guide for how to use IBM Secure Execution

- versions.yaml
This PR updates the libseccompt version to v2.5.5 which includes the following changes:
- Update the syscall table for Linux
- Fix minor issues with binary tree testing and with empty binary trees
Fixes #8883
> versions: Update libseccomp to version v2.5.5

- .github/workflows/build-kata-static-tarball-amd64.yaml
Lets remove the GHA target actions first so the the follow-up PR  https://github.com/kata-containers/kata-containers/pull/8874 tests are succeeding.
> gpu: remove GHA target first then remove the obsoleted Makefile targets

- tests/integration/kubernetes/run_kubernetes_tests.sh
Add --show-output-of-passing-tests to the k8s integration tests. The output of a passing test can be helpful when investigating a failure of the same test.
Fixes: #8885
> tests: k8s: bats --show-output-of-passing-tests

- tests/metrics/machine_learning/resnet50_fp32_dockerfile/Dockerfile
This PR updates the packages necessary to build the ResNet50 fp32 Dockerfile to run properly the benchmark.
Fixes #8875
> metrics: Update packages needed for ResNet50 FP32 Dockerfile

- tools/packaging/static-build/qemu/build-base-qemu.sh
This PR uses a variable that is already defined in the build base qemu script to have uniformity across the script as this variable is already used in the script.
Fixes #8903
> tools: Use defined variable in build base qemu script

- tools/packaging/scripts/configure-hypervisor.sh
Several use-cases need a vTPM lets enable it for QEMU, a follow up patch will introduce the runtime config.
Fixes: #8902
> qemu: enable TPM

- .gitignore
- tools/osbuilder/rootfs-builder/alpine/Dockerfile.in
- tools/osbuilder/rootfs-builder/cbl-mariner/Dockerfile.in
- tools/osbuilder/rootfs-builder/centos/Dockerfile.in
- tools/osbuilder/rootfs-builder/debian/Dockerfile.in
- tools/osbuilder/rootfs-builder/rootfs.sh
- tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in
- tools/packaging/guest-image/build_image.sh
- tools/packaging/kata-deploy/local-build/Makefile
- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
- tools/packaging/kata-deploy/local-build/kata-deploy-copy-libseccomp-installer.sh
- tools/packaging/scripts/lib.sh
- tools/packaging/static-build/agent/Dockerfile
- tools/packaging/static-build/agent/build-static-agent.sh
- tools/packaging/static-build/agent/build.sh
There's absolutely no need to always build the Kata Containers agent when building the rootfs. We already have the agent being built / packaged on every PR, and we can rely on that to simply be unpacked into the rootfs, unless there's a change in the agent.
Please, see each commit for more info.
> packaging:  Don't always build the kata-agent

- .github/workflows/ci-nightly-s390x.yaml
- tests/integration/kubernetes/confidential_common.sh
- tests/integration/kubernetes/k8s-confidential.bats
- tests/integration/kubernetes/k8s-cpu-ns.bats
- tests/integration/kubernetes/k8s-inotify.bats
The existing confidential basic test titled `Test unencrypted confidential container launch success and verify that we are running in a secure enclave` has been updated to incorporate IBM Secure Execution (`qemu-se`).
Previously, a secure image was absent from kata-deploy, hindering the inclusion of IBM SE in the test.
Thanks to the #6755 update, it is now possible to test the TEE.
This modification extends the existing test by introducing `qemu-se`. The specific changes are outlined below:
- Add an additional test `cc-se-e2e-tests` to s390x nightly
- Expansion of `REMOTE_COMMAND_PER_HYPERVISOR` for `qemu-se`
- Temporary exclusion of two test cases currently incompatible with IBM SE (`cpu-ns` is a common issue across all TEEs, while `inotify` will be addressed in a subsequent pull request …
> tests: Add IBM SE to the basic confidential test

- src/tools/genpolicy/rules.rego
- src/tools/genpolicy/src/config_map.rs
- src/tools/genpolicy/src/daemon_set.rs
- src/tools/genpolicy/src/deployment.rs
- src/tools/genpolicy/src/job.rs
- src/tools/genpolicy/src/list.rs
- src/tools/genpolicy/src/no_policy.rs
- src/tools/genpolicy/src/pod.rs
- src/tools/genpolicy/src/policy.rs
- src/tools/genpolicy/src/replica_set.rs
- src/tools/genpolicy/src/replication_controller.rs
- src/tools/genpolicy/src/secret.rs
- src/tools/genpolicy/src/stateful_set.rs
- src/tools/genpolicy/src/yaml.rs
Validate the sandbox_pidns field value for CreateSandbox and CreateContainer.
For a simple, sanity test, using a Kata CI YAML file:
genpolicy -u -y busybox-pod.yaml
k apply -f busybox-pod.yaml
k get pods | grep busybox
busybox                                                 2/2     Running   0          29s
Fixes: #8868
> genpolicy: add shareProcessNamespace support

- .github/workflows/build-kata-static-tarball-arm64.yaml
- .github/workflows/build-kata-static-tarball-ppc64le.yaml
- .github/workflows/build-kata-static-tarball-s390x.yaml
Those are not yet being cached for no reason, and they better be as it'll allow us to save a considerable amount of time building the rootfs.
Fixes: #8917
NOTE: The agent-opa is not in the scope for this, and I will leave it for the maintainers of each specific architecture to do so, and to also add the dependency to their specific rootfs as done for this one in a previous commit.
> gha: Cache the agent for non-x86_64 arches

- .github/workflows/run-k8s-tests-on-aks.yaml
- .github/workflows/run-kata-deploy-tests-on-aks.yaml
- tests/gha-run-k8s-common.sh
Due to the changes done in the CI, we need to set the correct subscription to be used with the account from now on, otherwise we'd end up using CoCo subscription.
> gha: azure: Set the correct subscription to the account

- tools/osbuilder/rootfs-builder/rootfs.sh
- versions.yaml
The versions.yaml has only a default amd64 binary configured extend the versions.yaml for aarch64 as well.
Fixes: #8373
> arm64: agent_policy build always pulls amd64 opa binary

- src/tools/genpolicy/src/pod.rs
Validating the node name is currently outside the scope of the CoCo policy.
This change unblocks testing using Kata CI's test-pod-file-volume.yaml and pv-pod.yaml.
Fixes: #8888
> genpolicy: ignore the nodeName field

- src/tools/genpolicy/src/daemon_set.rs
- src/tools/genpolicy/src/deployment.rs
- src/tools/genpolicy/src/job.rs
- src/tools/genpolicy/src/pod.rs
- src/tools/genpolicy/src/pod_template.rs
- src/tools/genpolicy/src/replica_set.rs
- src/tools/genpolicy/src/replication_controller.rs
- src/tools/genpolicy/src/stateful_set.rs
- src/tools/genpolicy/src/yaml.rs
Add metadata containing the Policy annotation if the user didn't provide any metadata in the input yaml file.
For a simple sanity test using a Kata CI YAML file:
genpolicy -u -y job.yaml
kubectl apply -f job.yaml
kubectl get pods | grep job
job-pi-test-64dxs 0/1     Completed   0          14s
Fixes: #8891
> genpolicy: optional PodTemplateSpec metadata field

- .github/workflows/run-k8s-tests-with-crio-on-garm.yaml
This will *not* solve the CRI-O CI breakage but will give us an environment where we could get it to run locally.
Fixes: #8935 -- part I
Thanks to Julien Ropé for trying to reproduce the issues I faced on https://github.com/kata-containers/kata-containers/issues/8935 in an Ubuntu 22.04 system.
> gha: cri-o: Bump runners to 22.04

- src/tools/genpolicy/genpolicy-settings.json
- src/tools/genpolicy/src/secret.rs
Allow Kata CI's pod-nested-configmap-secret.yaml to work with
genpolicy and current cbl-mariner images:
1. Ignore the optional type field of Secret input YAML files.
It's possible that CoCo will need a more sophisticated Policy
for Secrets, but this change at least unblocks CI testing for
already-existing genpolicy features.
2. Adapt the value of the settings field below to fit current CI
images for testing on cbl-mariner Hosts:
"kata_config": {
"confidential_guest": false
},
Switching this value from true to false instructs genpolicy to
expect ConfigMap volume mounts similar to:
"configMap": {
"mount_type": "bind",
"mount_source": "$(sfprefix)",
"mount_point": "^$(cpath)/watchable/$(bundle-id)-[a-z0-9]{16}-",
"driver": "watchable-bind",
"fstype": "bind",
"options": [
"rbind",
"rprivate", …
> genpolicy: fix ConfigMap volume mount paths

- src/dragonball/src/dbs_virtio_devices/src/block/handler.rs
The [`noop-method-call`](https://doc.rust-lang.org/rustc/lints/listing/warn-by-default.html#noop-method-call) is a rustc lint that has existed since [v1.52.0](https://github.com/rust-lang/rust/pull/80723).
This lint has been moved to the warn by default lint level since [v1.73.0](https://github.com/rust-lang/rust/pull/111916).
Therefore build is failing with this version and above.
This commit removes the unnecessary call to `<&T as Deref>::deref` on `T: !Deref`.
Fixes: #8586
Signed-off-by: Kvlil <kalil.pelissier@gmail.com>
> dragonball: fix noop-method-call warning

- src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
- src/runtime-rs/crates/hypervisor/src/qemu/mod.rs
Having a ready access to qemu's stderr is immensely helpful in debugging qemu's launch failures.  Qemu's stderr output is now included in regular shim's log (look for lines prepended with "qemu stderr: ").
An unrelated small fix promised in review of PR #8185 is also included in this PR's initial commit.
> runtime-rs: Log qemu's stderr in shim log

- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
- tools/packaging/scripts/lib.sh
- tools/packaging/static-build/agent/Dockerfile
This involves using Ubuntu 20.04 as a build environment for an agent to match with a runtime environment.
Fixes: #8955
> packaging: Use Ubuntu 20.04 for building an agent

- tools/packaging/kata-deploy/kata-cleanup/base/kustomization.yaml
- tools/packaging/kata-deploy/kata-cleanup/overlays/k3s/kustomization.yaml
- tools/packaging/kata-deploy/kata-cleanup/overlays/rke2/kustomization.yaml
- tools/packaging/kata-deploy/kata-deploy/base/kustomization.yaml
- tools/packaging/kata-deploy/kata-deploy/overlays/k0s/kustomization.yaml
- tools/packaging/kata-deploy/kata-deploy/overlays/k3s/kustomization.yaml
- tools/packaging/kata-deploy/kata-deploy/overlays/rke2/kustomization.yaml
- tools/packaging/kata-deploy/kata-deploy/overlays/stable/kustomization.yaml
- tools/packaging/kata-deploy/kata-rbac/base/kustomization.yaml
By running `kustomize edit fix` on those files they have changed deprecated instructions ('bases' and 'patchesStrategicMerge') as well as 'apiVersion' and 'kind' were added.
Fixes #8268
> kata-deploy: fix deprecations on kustomization files

- src/tools/genpolicy/src/volume.rs
The auto-generated Policy already allows these volumes to be mounted, regardless if they are:
- Present, or
- Missing and optional
Fixes: #8893
> genpolicy: ignore volume configMap optional field

- tests/integration/nerdctl/gha-run.sh
This PR re-arranged the nerdctl tests to avoid random failures. In this PR first will run the tests with RunC and then with the kata hypervisor. This PR tries to avoid the random failures that is happening with cloud-hypervisor.
Fixes #8963
> tests: Re-arranged nerdctl tests

- src/tools/genpolicy/genpolicy-advanced-command-line-parameters.md
- src/tools/genpolicy/src/policy.rs
- src/tools/genpolicy/src/settings.rs
- src/tools/genpolicy/src/utils.rs
Using custom input paths with -i is counter-intuitive. Simplify path handling with explicit flags for rules.rego and genpolicy-settings.json.
Fixes: #8568
I'm quite new here, but I think @danmihai1 might be a good person to review this.
<strike>Note: I couldn't come up with a good short flag for `--rules-file` (`--raw-out` is using `-r`). Suggestions are welcome.</strike>
> genpolicy: allow separate paths for rules and settings files

- src/libs/kata-types/src/annotations/mod.rs
Removed the setting of default values for runtime fields. Added explicit checks for missing or empty fields, reporting errors with clear messages.
Fixes: #8838
> runtime-rs: report error on missing or empty fields in configuration

- src/runtime/virtcontainers/sandbox.go
When creating a cgroup, add a SingleContainer when obtaining the OCI Spec to apply to ctr, podman, etc.
Fixes: #5240
> runtime: add SingleContainer when obtaining OCI Spec

- src/runtime/pkg/resourcecontrol/cgroups.go
- src/runtime/pkg/resourcecontrol/utils_linux.go
- src/runtime/pkg/resourcecontrol/utils_linux_test.go
Merged ValidCgroupPath method and modified unit tests.
Fixes: #8930
> runtime: merged ValidCgroupPath method

- src/tools/genpolicy/genpolicy-settings.json
- src/tools/genpolicy/src/config_map.rs
- src/tools/genpolicy/src/daemon_set.rs
- src/tools/genpolicy/src/deployment.rs
- src/tools/genpolicy/src/job.rs
- src/tools/genpolicy/src/list.rs
- src/tools/genpolicy/src/no_policy.rs
- src/tools/genpolicy/src/obj_meta.rs
- src/tools/genpolicy/src/pod.rs
- src/tools/genpolicy/src/policy.rs
- src/tools/genpolicy/src/replica_set.rs
- src/tools/genpolicy/src/replication_controller.rs
- src/tools/genpolicy/src/secret.rs
- src/tools/genpolicy/src/settings.rs
- src/tools/genpolicy/src/stateful_set.rs
- src/tools/genpolicy/src/yaml.rs
Allow users to specify in genpolicy-settings.json a default cluster namespace other than "default". For example, Kata CI uses as default namespace: "kata-containers-k8s-tests".
Fixes: #8976
> genpolicy: support non-default namespace name

- src/tools/genpolicy/src/policy.rs
Kata CI's pod-sandbox-vcpus-allocation.yaml ends with "---", so the empty YAML document following that line should be ignored.
To test this fix:
genpolicy -u -y pod-sandbox-vcpus-allocation.yaml
Fixes: #8895
> genpolicy: ignore empty YAML as input

- tests/gha-run-k8s-common.sh
This addresses an internal AKS issue that intermittently prevents clusters from getting created. The fix has been rolled out to eastus but not yet eastus2, so we unblock the CI by switching. No downsides in general.
This supersedes #8990.
Fixes: #8989
> ci: aks: switch from eastus2 to eastus region

- .github/workflows/ci.yaml
- .github/workflows/run-k8s-tests-on-ppc64le.yaml
- tests/integration/kubernetes/gha-run.sh
This PR adds workflow for running kubernetes test suite on ppc64le. It uses scripts to create and delete the cluster using kubeadm as none of the current cluster creation tools are supported on Power.
Fixes: #7950
> gha: add kubernetes tests workflow for ppc64le

- src/runtime-rs/Makefile
- src/runtime-rs/crates/hypervisor/Cargo.toml
- src/runtime-rs/crates/hypervisor/src/lib.rs
- src/runtime-rs/crates/runtimes/virt_container/src/lib.rs
- src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
This PR is to make `runtime-rs` compilable with QEMU on s390x. This is just a base work for the s390x enablement. There must be a few more steps (implementation for s390x-specific) to run a container with runtime-rs.
Fixes: #8446
> runtime-rs: make compilation for QEMU on s390x

- src/runtime/pkg/containerd-shim-v2/service.go
We notice a 100% CPU load `systemd` process in the `host` when deploying more than 400 Kata Containers Pods (using go runtime) through k8s in one node, as described in issue #8758 .
Inspired by rust runtime, we add the mount namespace isolation to go runtime, and it can prevent the `systemd` process from seeing more mounts, thereby reducing the burden on the `systemd`, making it faster to deploy more Pods.
Considering the runtime-rs VMMs are under heavy developments, adding such isolation is still useful for many user-cases.
Fixes: #8758
> runtime: Reduce the mount points with namespace isolation

- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
This issues was introduced due to a typo not caught during reviews on e5bca90274f39608ecaf369df9ea2438461af22d.
Fixes: #6415 -- part II
> packaging: Fix pushing artefacts to the registry

- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Those are fix ups to ensure that the work merged as part of #8987 works correctly.
Here are the local tests with these patches in:
```bash
⋊> kata-containers on topic/fix-cache-for-confidential-kernel-part-III ≡ make kernel-tarball
make kernel-tarball-build
make[1]: Entering directory '/home/ffidenci/src/upstream/kata-containers/kata-containers'
/home/ffidenci/src/upstream/kata-containers/kata-containers/tools/packaging/kata-deploy/local-build//kata-deploy-binaries-in-docker.sh  --build=kernel
sha256:17f85480ef404c1533f7fe4d1dc1ccf371df074f33e0894dfb5c8983e6feb268
Build kata version 3.3.0-alpha0: kernel
INFO: DESTDIR /home/ffidenci/src/upstream/kata-containers/kata-containers/tools/packaging/kata-deploy/local-build/build/kernel/destdir
Downloading 8f71e2b0fe63 kernel-builder-image-version …
```
> packaging: Don't build the confidential / sev kernel twice -- part III

- .github/workflows/run-k8s-tests-on-aks.yaml
This PR adds the Cloud Hypervisor driver, integrated with the runtime-rs, as part of the kubernetes tests different without devmapper.
Fixes #8995
> gha: k8s: Add cloud-hypervisor (runtime-rs) support

- .github/workflows/build-kata-static-tarball-amd64.yaml
- tools/packaging/kata-deploy/local-build/Makefile
- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
- versions.yaml
Let's use a single rootfs image / initrd for confidential workloads,
instead of having those split for different TEEs.
We can easily do this now as the soon-to-be-added guest-components can
be built in a generic way.
Fixes: #8982
NOTE: This is rebased atop of #8978
> packaging: Add confidential image / initrd

- tests/gha-run-k8s-common.sh
delete_cluster() has tried to delete the az resources group regardless if it exists. In some cases the result of that operation is ignored, i.e., fail to resource group not found, but the log messages get a little dirty. Let's delete the RG only if it exists then.
Fixes #8989
---
Split of https://github.com/kata-containers/kata-containers/pull/8990
> gha: delete azure RG only if it exists

- src/runtime/pkg/kata-monitor/monitor.go
It should be "/agent-url" here.
Fix: #9013
> kata-monitor: fix agentUrl from containerd shim

- src/runtime/pkg/containerd-shim-v2/shim_management.go
- src/runtime/pkg/kata-monitor/pprof.go
- src/runtime/pkg/utils/shimclient/shim_management_client.go
runtime: display accurate error msg to avoid misleading users.
The original handling method does not reach user expectations.
When the ClientSocketAddress method stats the corresponding
path of runtime-rs and has not found it yet, we should return
an error message here that includes the reason for the failure
(which should be an error display indicating that both runtime-go
and runtime-rs were not found). Instead of simply displaying the
corresponding path of runtime-rs as the final error message to
users.
It is also necessary to return the error promptly to the caller
for further error handling.
Fixes: #8999
> runtime: display accurate error msg to avoid misleading users.

- .github/workflows/static-checks.yaml
To test PR #8484, the compilation process for the kata-agent relies on clang. There have been encountered failures on ARM, s390x, and ppc64le architectures: 
- ppc64le: https://github.com/kata-containers/kata-containers/actions/runs/7754082828/job/21146689026?pr=8484 
- s390x: https://github.com/kata-containers/kata-containers/actions/runs/7754082828/job/21146689401?pr=8484 
- arm: https://github.com/kata-containers/kata-containers/actions/runs/7754082828/job/21146689026?pr=8484
Fixed: #9004
> static-checks: Install clang in the ci environments

- tools/osbuilder/rootfs-builder/rootfs.sh
- tools/packaging/kata-deploy/local-build/Makefile
- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
- tools/packaging/static-build/coco-guest-components/build-static-coco-guest-components.sh
- tools/packaging/static-build/coco-guest-components/build.sh
Let's install the coco-guest-components into the confidential rootfs image and initrd.
Fixes: #9021
> rootfs: confidential: Install coco-guest-components

- src/runtime/virtcontainers/physical_endpoint.go
Missing port type would cause error: port is not set.
https://github.com/kata-containers/kata-containers/blob/852021e4169df4d68d5e8b54894ee3c0585e6da3/src/runtime/pkg/device/drivers/vfio.go#L74-L78
Fix: #9014
> runtime: missing port type in the DeviceInfo

- .github/workflows/run-k8s-tests-on-ppc64le.yaml
The filtering of testing cases installs/uses yq and expects GOPATH to be present. Hence, add it to the workflow.
Fixes: #9018
> gha: add GOPATH env var to the ppc64le k8s workflow

- tests/integration/cri-containerd/integration-tests.sh
The loop that generate test cases for virtio-mem enabled/disabled doesn't return the integers '1' and '0' as expected. Instead it returns the strings '{1,' and '0}'.
Fixes #9024
> cri-containerd: fix loop in TestContainerMemoryUpdate()

- tests/integration/kubernetes/gha-run.sh
- tests/integration/kubernetes/k8s-cpu-ns.bats
- tests/integration/kubernetes/k8s-number-cpus.bats
- tests/integration/kubernetes/k8s-sandbox-vcpus-allocation.bats
- tests/integration/kubernetes/k8s-scale-nginx.bats
This PR enable the k8s tests for cloud hypervisor runtime-rs without devicemapper.
Fixes #8627
> tests: k8s: Enable tests for cloud hypervisor runtime-rs without devicemapper

- utils/kata-manager.sh
As already done for docker, let's also add support for installing nerdctl + kata containers.
For now, at least for now, we are explicitly not allowing the combination of installing both docker and nerdctl in the same installation in order to reduce the script complexity.
Also, nerdctl installation, for now, is limited to x86_64 and aarch64 as those are the only architectures that nerdctl releases a "full" package for.
Fixes: #8358
> kata-manager: Add support for nerdctl installation

- tests/common.bash
- versions.yaml
Bump nydus snapshotter version to v0.13.7.
The new release name of nydus snapshotter is `nydus-snapshotter-v0.13.7-linux-amd64.tar.gz`, which differs from the version used by kata (`nydus-snapshotter-v0.12.0-x86_64.tgz`). Therefore, we need to update the script to obtain the correct nydus snapshotter name.
Fixes: #9044
> nydus: Bump nydus snapshotter version to v0.13.7

- src/tools/genpolicy/genpolicy-settings.json
- src/tools/genpolicy/src/mount_and_storage.rs
- src/tools/genpolicy/src/settings.rs
The emergent Kata CI tests for Policy use confidential_guest = false in genpolicy-settings.json. That value is inconsistent with the following mount settings:
"emptyDir": {
"mount_type": "local",
"mount_source": "^$(cpath)/$(sandbox-id)/local/",
"mount_point": "^$(cpath)/$(sandbox-id)/local/",
"driver": "local",
"source": "local",
"fstype": "local",
"options": [
"mode=0777"
]
},
We need to keep those settings for confidential_guest = true, and change confidential_guest = false to use:
"emptyDir": {
"mount_type": "local",
"mount_source": "^$(cpath)/$(sandbox-id)/rootfs/local/",
"mount_point": "^$(cpath)/$(sandbox-id)/local/",
"driver": "local",
"source": "local",
"fstype": "local",
"options": [
"mode=0777"
]
},
The value of the mount_source field is different.
This change unblocks testing …
> genpolicy: mount source for non-confidential guest

- src/runtime-rs/crates/hypervisor/src/ch/inner.rs
Fix assert error:
```
error: used `assert_eq!` with a literal bool
--> crates/hypervisor/src/ch/inner.rs:218:9
|
218 |         assert_eq!(state.jailed, false);
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#bool_assert_comparison
= note: `-D clippy::bool-assert-comparison` implied by `-D warnings`
```
Fixes: #9042
> runtime-rs: fix assert error in `make check`

- src/runtime/virtcontainers/qemu_amd64.go
> runtime: fix creation of SEV confidential container on SNP enabled host.

- tests/integration/kubernetes/setup.sh
This PR replaces the add_kernel_initrd_annotations_to_yaml function more generic so later can be used for other components.
Fixes #9054
> tests:k8s: make add_kernel_initrd_anotations function generic

- tests/integration/kubernetes/gha-run.sh
Setup nydus snapshotter for CoCo tests.
Fixes #8584
> gha: Setup nydus snapshotter for CoCo tests

- tools/packaging/kernel/README.md
This PR removes the jenkins reference which is not longer being used in the kernel documentation.
Fixes #9046
> docs: Remove jenkins reference in kernel documentation

- src/tools/genpolicy/genpolicy-settings.json
- src/tools/genpolicy/rules.rego
- src/tools/genpolicy/src/policy.rs
- tests/integration/kubernetes/k8s-attach-handlers.bats
- tests/integration/kubernetes/k8s-copy-file.bats
- tests/integration/kubernetes/tests_common.sh
Auto-generate policy for k8s-copy-file.bats.
Fixes: #9050
> tests: k8s: k8s-copy-file auto-generated policy

- tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in
Avoid error when building for amd64 using:
USE_CACHE=no AGENT_POLICY=yes DEBUG=1 \
tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh \
--build=rootfs-image
Fixes: #9067
> tools: avoid rootfs-image build "ln -s" error

- tests/common.bash
- versions.yaml
CRI-O has moved, for a long time, towards pkgs.k8s.io, see:
https://kubernetes.io/blog/2023/10/10/cri-o-community-package-infrastructure/
With this the OBS repo won't be used anymore.
Fixes: #8935
> tests: cri-o: Use packages from pkgs.k8s.io

- tests/integration/kubernetes/tests_common.sh
Delete the debugger pod created during the test, rather than already existing debugger pods.
Fixes: #9069
> tests: k8s: avoid deleting unrelated pods

- .github/workflows/build-kata-static-tarball-amd64.yaml
- .github/workflows/build-kata-static-tarball-s390x.yaml
It doesn't make sense to ship the pause-image / coco-guest-components themselves as an release artefact.
The reason we build and cache those is in order to use them inside the rootfs, and that's it, there's not need to ship them as part of the release, at all.
Fixes: #9032 -- part II
> release: Don't ship the pause-image / coco-guest-components as part of the release artefacts

- .github/workflows/run-kata-coco-tests.yaml
- tests/integration/kubernetes/gha-run.sh
---
ci: Clean up kata-deploy ds before starting the tests
This will ensure no leftovers are in the node, which has been cause the
TDX CI to fail every now and then.
Fixes: #9081
---
gha: tdx: Stop running kata-deploy tests on TDX
We only have one TDX machine, let's not make it busier than needed.
---
> tests: Remove kata-deploy-tdx test and ensure kata-deploy is always cleaned up before starting the tests

- src/runtime/go.mod
- src/runtime/go.sum
- src/runtime/vendor/github.com/safchain/ethtool/ethtool.go
- src/runtime/vendor/modules.txt
Although we don't seem to be affected by
https://nvd.nist.gov/vuln/detail/CVE-2024-21626, we vendor and use the runc package in a few different places of our code, and we better update the package to its latest release.
Fixes: #9097
> runtime: Update runc to v1.1.12

- .github/workflows/build-kata-static-tarball-amd64.yaml
- tools/packaging/kata-deploy/local-build/Makefile
- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Add `kata-manager.sh` to the release packages.
Fixes: #9066.
> packaging: Add the kata manager script

- tests/integration/kubernetes/filter_out_per_arch/s390x.yaml
A test `vcpu allocation k8s test` exhibits different behavior on s390x For more details, please refer to issue #9093.
This commit is to make the test skipped until the issue is resolved on the platform.
Fixes: #9093
> CI|k8s: Skip vcpu allocation test for s390x

- tools/testing/kata-webhook/webhook-check.sh
When moving the webhook we skipped the common.bash as (close-enough) version is already in `/tests` but we forgot to update the source path, fixing it here.
> tools.kata-webhook: Fix lib path

- src/runtime/go.sum
- src/runtime/vendor/github.com/safchain/ethtool/ethtool.go
Fix checksum mismatch error in `make vendor`.
Fixes: #9111
> runtime: fix checksum mismatch error in `make vendor`

- tests/integration/kubernetes/k8s-confidential.bats
This has been introduced by 53bc4a432bc9782272fb7fd1fe3113e006172294, where the condition was changed.
The correct condition is:
* If the list of supported tees does not contain the kata hypervisor and the list of supported non tees does not contain the kata hypervisor.
The error is that we were checking whether kata-hypervisor would contain the list of supported tees, and that would almost always be false (unless in the case where the list had an one and only one element).
Fixes: #9055 -- part II
> ci: k8s: Fix checks used to skip confidential tests

- src/runtime/virtcontainers/api.go
- src/runtime/virtcontainers/network_linux.go
network: Move up defer block to cleanup network
Move the defer for cleaning up network before the call to add network.
This way if any change made by add network is reverted by in case of
failure. This is particulary important for physical network interfaces
as with this step we make sure that driver for the physical interface is
reverted back to the original host driver. Without this the physical
network iterface will remain bound to vfio.
Fixes: #8646
> Cleanup network to make sure physical interfaces are restores back to original host driver.

- README.md
This PR updates the CI link into the README as currently we are using GHA workflows and they are now part of the kata containers repository.
Fixes #9078
> docs: Update CI link into the README

- tests/integration/docker/gha-run.sh
This PR pulls the docker image needed for the test as part of the dependencies in order to avoid failures of timeouts mainly because the image was not properly download it and it is unable to find it.
Fixes #9089
> gha: docker: Pull docker image as part of the dependencies

- src/runtime-rs/crates/hypervisor/src/dragonball/inner.rs
runtime-rs: bugfix for GPU passthrough failed with InvalidOperation.
We need initailize the pci_hotplug_enabled with true before we do GPU
passthrough with runtime-rs/dragonball. Otherwise it fails with error
`InvalidOperation`.
Fixes: #9129
> runtime-rs: bugfix for GPU passthrough failed with InvalidOperation.

- versions.yaml
Bump nydus snapshotter version to v0.13.8 to fix the bug in v0.13.7 : https://github.com/containerd/nydus-snapshotter/pull/582
Fixes: #9131
> gha: bump nydus snapshotter version to v0.13.8

- src/agent/Cargo.lock
- src/agent/rustjail/src/container.rs
This adds some missing namespace isolation in cgroup v2 guests. Some linting is apparently needed in main. Do this as a preparatory patch avoid the noise in the actual fix.
Fixes #9124
> agent: Run container workload in its own cgroup namespace (cgroup v2 guest only)

- .github/workflows/build-checks.yaml
To test PR #8484, the compilation process for the kata-agent relies on protoc:
https://github.com/kata-containers/kata-containers/actions/runs/8016317290/job/21898040849?pr=8484 https://github.com/kata-containers/kata-containers/actions/runs/8016534530/job/21898654435?pr=8484 
Fixes: #9141
> build-checks: Install protoc in the ci environments

- tools/packaging/release/release-notes.sh
Add a link in the release notes to the Kata Container survey, to
advertise it, and hopefully encourage users to take the survey.
Add a "twistie" / arrow (`▶`) that the user can click on to see the full
list of commits _if they want to_.
This way, the release notes become easier to read and we can display
information below the shortlog which would (probably) normally not be
seen due to the huge long list of commits.
Fixes: #9075.
Fixes: #9074.
> packaging: release notes: Don't show shortlist by default, and add survey link

- src/runtime-rs/crates/runtimes/src/shim_metrics.rs
- src/runtime/pkg/containerd-shim-v2/shim_metrics.go
Following discussion on #5738 - I think the `kata_shim_netdev` metrics is unneeded.
It is not only using too much memory (causing Prometheus pods to be OOM-killed in some installations), but it also reports data from interfaces that are unrelated to kata (no namespace isolation allowing the reporting of host-wide metrics).
The shim network usage is not giving any useful insight anyway - we already have hypervisor and agent metrics for that.
So rather than trying to fix the memory/namespace question, I'm suggesting to just remove the shim netdev metrics.
I'm also doing it on the rust implementation, even if it's not impacted by the initial bug as far as I can tell: In the rutime-rs case, the metrics are isolated (not verified, but that's my understanding at this point). Also it seems we …
> runtime: remove kata_shim_netdev metric

- src/runtime/virtcontainers/clh.go
Relax the timeout for calling CLH's CreateVM + BootVM APIs. When hitting the older 1s timeout, killing a half-booted Guest and retrying the same boot sequence could have been wasteful and resulting in unstable CI testing on slower Hosts.
Fixes: #9152
> runtime: clh: minimum 10s timeout for CreateVM + BootVM

- src/agent/README.md
Add all agent configuration options to README so that users can more easily understand what these options do and how to configure them at runtime.
Fixes: #9109
> agent: Add all agent configuration options to README

- .github/workflows/run-k8s-tests-on-aks.yaml
- tests/integration/kubernetes/gha-run.sh
Changed the "run k8s tests on AKS" workflows to get the CoCo KBS installed so that we can run attestation tests.
The plan is to run attestation tests only on a subset of non-TEE jobs initially, so this commit restricts to install KBS only on kata-qemu configuration. Actually at this point it is added only stubs commands to tests/integration/kubernetes/gha-run.sh that should be implemented in a future commit.
Fixes #9058
---
This is a split of PR #9065. We merge this commit first to then allow to run CI on #9065.
@sprt @jodh-intel suggested on #9065 to move the logic about whether to install or not the KBS out of the workflow and into the shell script as this is easier for testing and future extending. However, talking with …
> gha: k8s: prepare AKS workflow to install the CoCo KBS

- .github/workflows/payload-after-push.yaml
Please, see each commit for more details.
It's not worth running CI for this one.
> releases: Second round of follow-up fixes

- docs/design/architecture/README.md
renew the stale link "https://github.com/containerd/containerd/tree/main/runtime/v2" to the latest "https://github.com/containerd/containerd/tree/main/core/runtime/v2".
Fixes: https://github.com/kata-containers/kata-containers/issues/9177
> docs: renew stale link

- tools/osbuilder/rootfs-builder/rootfs.sh
We were never passing the arguments to add the PAUSE_IMAGE to the rootfs, leading to it never being present in the confidential image / initrd.
Fixes: #9032 -- part II
> rootfs: Fix PAUSE_IMAGE_TARBALL addition to the rootfs

- .github/workflows/basic-ci-amd64.yaml
- tests/integration/cri-containerd/gha-run.sh
This PR adds the Cloud Hypervisor driver, integrated with the runtime-rs, as part of the cri-containerd tests.
Fixes #9181
> gha: Add cloud-hypervisor (runtime-rs) support to cri-containerd tests

- src/tools/genpolicy/src/mount_and_storage.rs
- src/tools/genpolicy/src/pod.rs
Make tool panic when we find a yaml that has a volume mount subpath defined.
Fixes: https://github.com/kata-containers/kata-containers/issues/9145
> genpolicy: panic when we see a volume mount subpath

- src/tools/csi-kata-directvolume/Dockerfile
> csi-kata-directvolume: add Dockerfile for building csi image

- tests/integration/kubernetes/k8s-sandbox-vcpus-allocation.bats
Kubernetes v1.29 introduced a new [PodReadyToStartContainers](https://kubernetes.io/blog/2023/12/19/pod-ready-to-start-containers-condition-now-in-beta/) condition that breaks assumptions in `k8s-sandbox-vcpus-allocation.bats`.
Pass a less fragile condition to `kubectl wait`.
Fixes #9178
> tests: k8s: Adapt k8s-sandbox-vcpus-allocation.bats to kubernetes v1.29

- ci/openshift-ci/run_smoke_test.sh
This backports the:
9060e930caf2d20f413df07778d3ab497493161c
ci.ocp: Add debug output on HTTP service failure
these logs are vital to analyze a setup failure.
a10a1e2c9cbc21afc1e80f22b0fb8634d27cbd8d
ci.ocp: Improve the service-up detection
waiting for the first response is not sufficient as OCP returns html
page without error even when the route is not yet established describing
the issue (why it doesn't reply with 500?). Waiting for the correct
output should do better.
commits from the kata-containers/tests repo.
Fixes: #8653
> ci.ocp: Backport service-up detection fixes

- .github/workflows/run-k8s-tests-on-aks.yaml
The step to deploy KBS on run-k8s-tests-on-aks workflow should be increased so that there is enough time for checking the service is healthy and exposed. Likewise the step that builds the kbs-client which requires enough time to build the executable.
Fixes #9058
> gha: increase timeout of KBS steps

- tests/integration/cri-containerd/gha-run.sh
This PR enables the cri-containerd tests for cloud hypervisor runtime-rs.
Fixes #9198
> gha: Enable cri-containerd tests for cloud hypervisor runtime-rs

- src/runtime/pkg/katautils/katatrace/tracing.go
This fixes a panic on tracing on container exit.
The root cause is that global var needs to be set by "=" instead of ":=".
Fixes: #9102
> katautils: fix panic on tracing.

- .github/workflows/run-k8s-tests-on-garm.yaml
- tests/integration/kubernetes/gha-run.sh
This PR helps to store the artifacts for different logs for k8s tests on garm. This includes changes in the workflow to install the dependencies required as well as saving the artifacts files, the introduction of the teardown script which will help to collect kata env details as well as logs from the different components.
Fixes #9103
> gha: Storing artifacts for logs of k8s tests garm

- README.md
- tests/README.md
This PR adds general README documentation for the tests section in the kata containers repository.
Fixes #9209
> docs: Add general README for tests section

- tests/gha-run-k8s-common.sh
- tests/integration/kubernetes/confidential_kbs.sh
- tests/integration/kubernetes/gha-run.sh
- versions.yaml
This introduces the building blocks to install the [CoCo KBS](https://github.com/confidential-containers/kbs) on Kubernetes to be used on the upcoming attestation tests (see https://github.com/kata-containers/kata-containers/issues/9058).
It is added the commands `deploy-coco-kbs` and `delete-coco-kbs` to the `tests/integration/kubernetes/gha.sh` script to install and uninstall the KBS on Kubernetes.
I tested those new commands on a kubeadm cluster as:
```
$ ./tests/integration/kubernetes/gha-run.sh deploy-coco-kbs
::group::Clone the kbs sources
Cloning into '/tmp/kbs'...
remote: Enumerating objects: 283, done.
remote: Counting objects: 100% (283/283), done.
remote: Compressing objects: 100% (256/256), done.
remote: Total 283 (delta 24), reused 185 (delta 8), pack-reused 0
Receiving …
```
> CI: Install KBS on k8s for attestation tests

- tests/functional/kata-deploy/kata-deploy.bats
- tests/integration/kubernetes/gha-run.sh
Currently, the checking for kata-deploy is running assume that the daemonset scheduled at least one pod, however it might not had and the kubectl wait command fails due to "error: no matching resources found".
On CI I've observed that fail intermittently. I suspect the service account kata-deploy-sa take a while to show up then no kata-deploy is scheduled in meanwhile.
Changed the checker logic to use waitForProcess() to keep testing if it is already running, or hit the timeout (still 10m).
Fixes #9183
> tests/kata-deploy: fix checker for kata-deploy running

- src/runtime/virtcontainers/clh.go
This patch fixes #9192. It adds dax in rootflags for clh.
> clh: Enable DAX for rootfs

- tests/common.bash
PR #8760 tentatively tried to have the shim to run in its own mount namespace for the sake of improving isolation between the sandbox and the host. Thus crio storage drivers shouldn't create a PRIVATE bind mount on their home directory. Otherwise, the container's rootfs mount wouldn't be propagated to kata runtime's mount namespace, and kata runtime couldn't access the container's rootfs files.
So, when kata cooperated with crio, crio should set skip_mount_home=true for its storage overlay.
Fixes: #9028
> CI: fix the issue of ci failure on crio

- docs/hypervisors.md
- utils/README.md
- utils/kata-manager.sh
kata-manager: Allow hypervisor to be changed
Add new options to allow the configured hypervisor to be changed:
- `-L`: List available _packaged_ hypervisor config names (filename fragments).
- `-e`: List available _local_ hypervisor config names (filename fragments).
- `-H <hypervisor>`: Install Kata then switch to the specified hypervisor (by filename fragment).
- `-S <hypervisor>`: Switch to the specified hypervisor (by filename fragment [Errors if Kata not installed]).
For example, to install Kata and configure it to use Cloud Hypervisor
with the golang Kata runtime:
```bash
$ kata-manager.sh -H clh
```
To switch back to the default hypervisor:
```bash
$ kata-manager.sh -S default
```
To show details of the available packaged configs:
```bash
$ kata-manager.sh -L
```
To show details of …
> kata-manager: Allow hypervisor to be changed

- versions.yaml
New qemu fork of AMDESE created in confidential-containers project. SNP qemu version now pointed to stable tag at:
https://github.com/confidential-containers/qemu/tree/amd-snp-202402240000
Fixes: #9173
Forks of AMDESE repositories have been created in the confidential-containers project:
[amdese-amdsev](https://github.com/confidential-containers/amdese-amdsev/tree/amd-snp)
[linux](https://github.com/confidential-containers/linux)
[qemu](https://github.com/confidential-containers/qemu)
[edk2](https://github.com/confidential-containers/edk2)
Pointing to the tagged version here will allow users to generate host kernels for stable SNP testing environments with the specified version of qemu above.
> versions: SNP qemu updated to stable coco tagged version

- tools/packaging/kernel/README.md
This PR removes stale kernel information at README documentation.
Fixes #9218
> docs: Remove stale kernel information at README documentation

- src/tools/genpolicy/rules.rego
- src/tools/genpolicy/src/registry.rs
Disable env variable verification to unblock CI, until container images that don't specify the Env variables will be handled correctly (see #9239).
Also, mark the image config Env field as optional, thus allowing policy generation for these container images.
Fixes: #9240
> genpolicy: disable env variable verification

- src/libs/Cargo.lock
- src/libs/shim-interface/Cargo.toml
- src/libs/shim-interface/src/lib.rs
- src/runtime-rs/Cargo.lock
> kata-ctl: Support using container short ID to enter guest.

- src/tools/genpolicy/src/pod.rs
This adds support for sidecar container introduced in Kubernetes 1.28.
Fixes: #9220
I tested this for our use-case and it worked well.
> genpolicy: add restartPolicy to container struct

- src/dragonball/src/device_manager/mod.rs
- src/dragonball/src/signal_handler.rs
fixes: #9207 
test_signal_handler: a) There is some unknown syscalls triggered in new github virt machine that would break the make test process with SIGSYS after applying SeccompFilter. In order to fix this, we change the allowlist in this unit test for seccompfileter into a blocklist to avoid meeting the unknown syscalls. b) lazy static METRICS is not fully initialize in the unit test and may lead to unstable result for this UT.
test_handler_insert_region: the mmap region start guest addr hard-code a value and later there would be check whether the mentioned addr is larger than or equal to mem_end (mem_end default to host_phy_mem >> 1) in order to satisfy the requirement for DaxMemory. Since github virt machine phy_mem is larger than previous CI machine we use, the hard-code value could …
> Dragonball: fix unit test problems when switching to new virt github machine

- .github/workflows/payload-after-push.yaml
- .github/workflows/release-amd64.yaml
- .github/workflows/release-arm64.yaml
- .github/workflows/release-ppc64le.yaml
- .github/workflows/release-s390x.yaml
- .github/workflows/release.yaml
- tools/packaging/release/release.sh
We need to ensure the release type is passed down to workflows, otherwise we'll fail to get the correct release version for tagging the daemonset images.
Fixes: #9064 - part III
> release: Ensure the release-type is passed to workflows

- src/runtime/virtcontainers/clh.go
The PID needs to be initialized before calling isClhRunning. waitVMM() uses isClhRunning and is called by launchClh() just before returning from function.
Fixes: #9230
> clh: initialize clh pid before using it

- docs/Developer-Guide.md
- docs/install/README.md
- tests/cmd/check-spelling/kata-spell-check.sh
Move the "build from source" and "manual installation" details to the
developer guide. This makes the installation landing page clearer for
users.
Fixes: #9234.
Also includes a fix for a `grep(1)` warning caused by the unnecessary escaping of the
hash/sharp symbol in the spell-checker.
Fixes: #9235.
> docs: install: Simplify instructions

- .github/workflows/build-kata-static-tarball-ppc64le.yaml
- .github/workflows/publish-kata-deploy-payload-ppc64le.yaml
- .github/workflows/release-ppc64le.yaml
- .github/workflows/run-cri-containerd-tests-ppc64le.yaml
- .github/workflows/run-k8s-tests-on-ppc64le.yaml
This PR adds a step to ensure that containerd is up and running before building the payload image on Power.
Fixes: #9262
> gha: ensure that the self hosted runner is in desired state before running the workflow 

- src/tools/genpolicy/rules.rego
- src/tools/genpolicy/src/containerd.rs
- src/tools/genpolicy/src/registry.rs
Use containerd's default environment for container images that don't specify the Env field.
Also, re-enable policy env variable verification, now that these uncommon images are supported too.
Fixes: #9239
> genpolicy: default env if image doesn't have env

- tests/integration/kubernetes/gha-run.sh
- tests/integration/nerdctl/gha-run.sh
Initialize $GITHUB_ENV to avoid nounset error when running the scripts locally out of Github Actions.
Fixed commit 9ba5e3d2a8aeab8d1d868a1b6f8f1b2836cbfd0a
Fixes #9217
> tests: fix nounset error with $GITHUB_ENV

- src/agent/rustjail/src/mount.rs
Fixes: #9269
From https://github.com/opencontainers/runtime-spec/blob/main/config.md#mounts type (string, OPTIONAL) The type of the filesystem to be mounted. bind may be only specified in the oci spec options -> flags update r#type The agent will ignore bind mounts if they are only specified in the OCI spec options and not in the flags.
> kata-agent: optional bind flag

- src/runtime-rs/crates/hypervisor/ch-config/src/lib.rs
The current default value of IP `0.0.0.0` with mask `0.0.0.0` will cause ioctl error when being used to create and configure TAP device, with newer version of Cloud Hypervisor [1]. This patch replaces them with valid value that are the same as the Go-lang runtime [2].
[1] https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5924
[2] https://github.com/kata-containers/kata-containers/blob/e3f78527388a22d0c1a4cfea66fe5c43ec041fea/src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_net_config.go#L40-L57
Fixes: #9254
> runtime-rs: ch: Provide valid default value for NetConfig

- .github/workflows/release-s390x.yaml
This is to place a pre-action step for the kata-deploy job in order to clean up the github workspace directory before checking out the repo.
Fixes: #9301
> gha: Place pre-action on s390x runner for kata-deploy during release

- utils/kata-manager.sh
Fix the Docker install by removing the second (erroneous) call to `containerd_installed()` in `handle_docker()`.
Without this fix, installing using Docker (`-D`) will work *iff* you already have containerd installed. However, if you do not have containerd installed, the `containerd_installed()` function returns 1, which exits the script as we're running with `set -e`, leaving a broken Docker installation.
> **Note:** containerd is installed via Docker's `get-docker.sh` script.
Fixes: #9292.
> kata-manager: Fix Docker install

- src/agent/Cargo.lock
- src/agent/src/features.rs
- src/agent/src/main.rs
- src/agent/src/rpc.rs
- src/libs/protocols/protos/agent.proto
- src/runtime-rs/Cargo.lock
- src/runtime-rs/crates/agent/src/kata/trans.rs
- src/runtime-rs/crates/agent/src/types.rs
The agent now has a number of optional build-time features that can be enabled.
Add details of these features to the following areas:
- Version output (`kata-agent --version`)
- Announce message (so that the details are always added to the journal at agent startup).
- The response message returned by the ttRPC `GetGuestDetails()` API.
Fixes: #9285.
> agent: Show features enabled at build time

- .github/workflows/run-k8s-tests-on-aks.yaml
Currently we're only running the small instance tests. This adds the normal instance tests as well.
Fixes: #9298
> ci: aks: also run tests in normal instance for Mariner

- tests/integration/kubernetes/filter_k8s_test.sh
This commit updates `filter_k8s_test.sh` to handle skipped tests that include comments. In addition to the existing parameter expansion, the following expansions have been added:
- Removal of a comment
- Stripping of trailing spaces
Fixes: #9304
> CI|k8s: Handle skipped tests with a comment for filter_out_per_arch

- tools/packaging/release/release.sh
This release is a special case, as we've slacked for 6 months and the release content is way too long ... long enough to exceed the allowed limit for the release notes.
With this in mind we'll just remove the `--generate-notes` for now, and then revert this commit as soon as the release is out, as releases should be happening every month and, ideally, we won't reach this situation never ever again.
Fixes: #9064 - part V
> release: Skip --generate-notes for this release

- tests/integration/kubernetes/gha-run.sh
This PR updates the journal log names for kubernetes artifacts in order to make sure that we have different names when we are running parallel GHA jobs.
Fixes #9308
> gha: Update journal log names for kubernetes artifacts

- tests/integration/kubernetes/gha-run.sh
This PR terminates the nydus namespace to avoid the error of that the flag needs an argument.
Fixes #9264
> gha: Fix nydus namespace clean up

- src/dragonball/src/dbs_arch/src/x86_64/regs.rs
MTRR, or Memory-Type Range Registers are a group of x86 MSRs providing a way to control acces s and cacheability of physical memory regions.
During our test in runtime-rs + Dragonball, we found out that this register support is a must for passthrough GPU running CUDA application, GPU needs that information to properly use GPU memory.
fixes: #9310
> Dragonballl: introduce MTRR regs support

- tests/static-checks.sh
Added an announcement message to the `static-checks.sh` script. It runs
platform / architecture specific code so it would be useful to display
details of the platform the checker is running on to help with
debugging.
Fixes: #9258.
> tests: static checker: Add announce message 

- src/agent/src/features.rs
Add `guest-pull` to the list of agent features in announce().
Fixes: #9225 -- part IV
> agent: Add guest-pull to the list of agent features in announce()

- tools/packaging/release/release.sh
This reverts commit 0fa59ff94bc405ea992e07ee5fda801caabb977b, as now we'll be able to use the `--generate-notes`, hopefully, without blowing the allowed limit.
Fixes: #9064 - part VI
> Revert "release: Skip --generate-notes for this release"

- versions.yaml
This version brings in a fix for cleaning up k3s/rke2 environments, which directly impacts the TDX machine that's part of our CI.
Fixes: #9318
> versions: Update nydus-snapshotter to v0.13.11

- src/agent/Cargo.lock
- src/agent/src/image.rs
- src/agent/src/rpc.rs
- src/agent/src/storage/image_pull_handler.rs
Currently, `.lock().await.clone()` results in `Option<ImageService>` being duplicated in memory with each call to `singleton()`. Consequently, if kata-agent receives numerous image pulling requests simultaneously, it will lead to the allocation of multiple `Option<ImageService>` instances in memory, thereby consuming additional memory resources.
In image.rs, we introduce two public functions: `merge_bundle_oci()` and `init_image_service()`. These functions will encapsulate the operations on `IMAGE_SERVICE`, ensuring that its internal details remain hidden from external modules such as `rpc.rs`.
Fixes: #9225 -- part II
> agent:image: Refactor code to improve memory efficiency of image service

- tests/integration/kubernetes/setup.sh
This PR fixes the unbound variables error when trying to run the setup script locally in order to avoid errors.
Fixes #9328
> scripts: Fix unbound variables in k8s setup script

- .github/workflows/build-kata-static-tarball-ppc64le.yaml
- .github/workflows/build-kata-static-tarball-s390x.yaml
Since https://github.com/kata-containers/kata-containers/pull/7769, we support building the OPA binary into the ppc64le and s390x arch versions of the rootfs, so build the policy enabled agent to match for those architectures too.
Fixes: #9355
> workflows: Build agent-opa for more archs

- tests/integration/kubernetes/runtimeclass_workloads/confidential/unencrypted/Dockerfile
Since v2.2.6 it can detect TDX guests on Azure, so let's bump it even if Azure peer-pods are not currently used as part of our CI.
Fixes: #9348
> k8s: confidential: Update cpuid to its latest release

- src/tools/genpolicy/rules.rego
Kata CI has full debug output enabled for the cbl-mariner k8s tests, and the test AKS node is relatively slow. So debug prints from policy are expensive during CI.
Fixes: #9296
> genpolicy: reduce policy debug prints

- src/runtime/pkg/containerd-shim-v2/stream.go
This reverts commit 1c5693be86be4dcfee83d2d5ff2ec68dcfd18df4.
Avoid apparent infinite loop when ReadStreamRequest is blocked by policy - for some of the pods.
When running the k8s-limit-range.bats test with Policy enabled, the Shim + VMM never get terminated on my cluster. Not sure why the sandbox clean-up works better for other tests, but the k8s-limit-range test pod gets stuck in an infinite loop:
```
stdout io stream copy error happens: error = %wrpc error: code =
PermissionDenied desc = \"ReadStreamRequest is blocked by policy
...
policy check: ReadStreamRequest
...
stdout io stream copy error happens: error = %wrpc error: code =
PermissionDenied desc = \"ReadStreamRequest is blocked by policy
...
policy check: ReadStreamRequest
...
```
Fixes: #9380
> runtime: remove stream copy infinite loop

- src/agent/rustjail/src/mount.rs
- src/agent/src/mount.rs
- src/agent/src/rpc.rs
- src/agent/src/signal.rs
Running `make check` in the `src/agent` directory shows a variety of lint-level errors, outlined in the three commits in this PR. With the proposed fixes, `make check` is clean (at least on my machine).
> agent: Fix errors in `make check`

- tests/integration/nerdctl/gha-run.sh
This PR updates the journal log name for nerdctl artifacts to make sure that we have different names in case we add a parallel GHA job.
Fixes #9357
> gha: Update journal log names for nerdctl artifacts

- src/agent/src/rpc.rs
The guest_hook_path item in configuration.toml allows OCI hook scripts to be executed within Kata's guest environment. Traditionally, these guest hook programs are pre-built and included in Kata's guest rootfs image at a fixed location.
While setting guest_hook_path = "/usr/share/oci/hooks" in configuration.toml works, it lacks flexibility. Not all guest hooks reside in the path /usr/share/oci/hooks, and users might have custom locations.
To address this, a more flexible and configurable approach is to be proposed that allows users to specify their desired path. This could include using a sandbox bind mount path for hooks specific to that particular container.
However, The current implementation of guest hooks and bind mounts in kata-agent has a reversed order of execution compared to the …
> kata-agent: Change order of guest hook and bind mount processing

- versions.yaml
This PR removes the runc version information as this is not longer being used in the kata containers scripts.
Fixes #9364
> versions: Remove runc version information

- versions.yaml
This PR removes conmon information from versions.yaml as this is not longer being used in kata containers repository.
Fixes #9396
> versions: Remove conmon information from versions.yaml

- tests/gha-run-k8s-common.sh
This PR defines the GH_PR_NUMBER variable in gha run k8s common script to avoid failures like unbound variable when running locally the scripts just like the GHA CI.
Fixes #9408
> gha: Define GH_PR_NUMBER variable in gha run k8s common script

- tests/integration/kubernetes/k8s-job.bats
Don't just verify SuccessfulCreate - wait for it if needed.
Fixes: #9138
> tests: k8s-job: wait for job successful create

- tests/gha-run-k8s-common.sh
There's an rg name duplication situation that got introduced by #9385 where 2 different test runs might have same rg name.
Add back uniqueness by including the first letter of GENPOLICY_PULL_METHOD to cluster name.
Fixes: #9412
> gha: ensure unique resource group name

- src/runtime-rs/crates/hypervisor/src/device/driver/vfio.rs
- src/runtime-rs/crates/hypervisor/src/device/driver/vhost_user_blk.rs
- src/runtime-rs/crates/hypervisor/src/device/driver/virtio_blk.rs
- src/runtime-rs/crates/hypervisor/src/device/util.rs
runtime-rs: bugfix incorrect use of refcount before vfio attach
When there's a pod with multiple containers, there may be case that
attach point more than 2, we should not return Err in that case when
we are doing attach ops, but just return Ok.
runtime-rs: introduce dedicated function do_increase_count/do_decrease_count
Since there are many implementations of reference counting in the
drivers, all of which have the same implementation, we should try
to reduce such duplicated code as much as possible. Therefore, a
new function is introduced to solve the problem of duplicated code.
runtime-rs: refactor increase_attach_count with do_increase_count/do_decrease_count
Try to reduce duplicated code in increase_attach_count with public
new function do_increase_count/do_decrease_count.
Fixes: …
> bugfix and refactor device increate count

- src/runtime/pkg/govmm/qemu/qemu.go
- src/runtime/pkg/govmm/qemu/qemu_test.go
- src/runtime/virtcontainers/hypervisor_linux_amd64.go
- src/runtime/virtcontainers/qemu.go
- tools/packaging/static-build/ovmf/build-ovmf.sh
- tools/packaging/static-build/qemu/Dockerfile
- versions.yaml
As host side patches of TDX are being shipped by distros like Ubuntu, CentOS Stream, and SuSE, let's take advantage of this and switch to using those, while on the guest side we rely on the upstream content (kernel 6.7, which has everything we need).
Please, take a look at each commit in the series for further details.
> tdx: Update TDX artefacts to be used with the Ubuntu 23.10 / CentOS 9 stream OSVs.
