- README.md
Add brief details of the new "ci" and "packaging" repositories.
Fixes #6.
> docs: Add references to "ci" and "packaging" repos

- README.md
PR #7 was merged inadvertently, so apply the Documentation Team's
review comments to `README.md`.
Fixes #10.
> docs: Apply doc team review comments to README

- src/agent/src/main.rs
When kata-agent run as init process in initrd, do the
init before pasring cmd line, thus it can read
/proc/cmdline.
Fixes: #85
Signed-off-by: lifupan <lifupan@gmail.com>
> agent: init agent as init before parsing cmd line

- src/agent/src/main.rs
Once parsed cmdline and set the config on AGENT_CONFIG,
release the write lock as soon as possible. In case other
thread would get read lock on it.
Fixes:#87
Signed-off-by: lifupan <lifupan@gmail.com>
> agent: fix the issue dead lock on AGENT_CONFIG

- src/agent/src/grpc.rs
Fix the issue of copy file failed from host to target
> Fix copy file

- src/agent/src/config.rs
It's should use string.eq() to match option's
key words exactly instead of using string.starts_with()
for single key options and for "key=value" options it's
bettet to match "key=" instead of "key" with string.starts_with()
which would match wrongly such as passed options "agent.log_vsock"
which would match "agent.log" with string.starts_with()
and trigger parsing issues.
Fixes: #96
Signed-off-by: lifupan <lifupan@gmail.com>
> config: fix the issue of parse cmdline options

- src/agent/src/config.rs
- src/agent/src/device.rs
- src/agent/src/grpc.rs
- src/agent/src/linux_abi.rs
- src/agent/src/logging.rs
- src/agent/src/main.rs
- src/agent/src/mount.rs
- src/agent/src/namespace.rs
- src/agent/src/random.rs
- src/agent/src/sandbox.rs
- src/agent/src/uevent.rs
- src/agent/src/version.rs
1. Refine code for maintenance.
2. Fix bug #98
> Fix bug #98 and improve code readability

- .github/workflows/main.yaml
Fix two issues identified in workflow:
1. Correctly pass output between jobs/steps
2. gathering of artifacts needs to depend on experimental build
> Fixup workflow 103

- src/agent/Cargo.toml
- src/agent/netlink/Cargo.toml
- src/agent/netlink/src/lib.rs
- src/agent/src/grpc.rs
- src/agent/src/main.rs
- src/agent/src/sandbox.rs
- src/agent/src/uevent.rs
Fixes: #111
Signed-off-by: Yang Bo <yb203166@antfin.com>
> netlink: pull out netlink as library crate.

- src/agent/src/sandbox.rs
These are the unit tests for the sandbox struct. This is the summary
of the most important changes:
- To test containers it was needed to create a `LinuxContainer` type
and this requires root privileges. So, some tests now requires root
user to be run.
- There was a bug in the `unset_sandbox_storage` method. The return
type was wrapped in a `Result` to avoid this problem.
Fixes: #50
> agent: Add unit tests for sandbox.rs

- src/agent/oci/src/lib.rs
Fixes: #118
Signed-off-by: quanweizhou <quanweiZhou@linux.alibaba.com>
> add oci compatibility test case

- src/agent/Cargo.toml
- src/agent/netlink/Cargo.toml
- src/agent/rustjail/Cargo.toml
- src/agent/rustjail/src/container.rs
- src/agent/src/config.rs
- src/agent/src/grpc.rs
- src/agent/src/main.rs
> vsock: support log_vport and debug_console_vport

- src/agent/Makefile
Based on @ericho's work on the bug
Fixes: #69
> Makefile: Fix rust agent build using "--release".

- src/agent/src/grpc.rs
It's better to catch the  error of couldn't find the process
in tty_win_resize service, other wise, an invalid process id
could crash the agent.
Fixes: #137
> grpc: fix the issue of crash agent when didn't find the process

- .github/workflows/gather-artifacts.sh
- .github/workflows/main.yaml
Add a logs to debug actions easily
Fixes: #157
Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>
> actions: Add verbose information

- src/agent/Cargo.toml
- src/agent/Makefile
Add a worksapce and run all of the tests in
under this workspace.
Fixes:#155
> add a workspace and run all the tests in the workspace

- src/agent/rustjail/src/process.rs
- src/agent/src/config.rs
- src/agent/src/grpc.rs
Adds a cmdline option to configure the stdout/stderr pipe sizes.
Uses `F_SETPIPE_SZ` to resize the write side of the pipe after
creation.
Example Cmdline option: `agent.container_pipe_size=2097152`
fixes #152
Signed-off-by: Alex Price <aprice@atlassian.com>
> agent: add configurable container pipe size cmdline option

- .travis.yml
Use build jobs to enable it.
Fixes: #209
> travis: enable linux-ppc64le

- .github/workflows/main.yaml
the actions upload/download-artifact moved to a new version
and master now is not comptible.
Fixes: #211
Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>
> release: actions: pin artifact to v1

- tools/osbuilder/scripts/lib.sh
> osbuilder: use newest golang

- src/agent/src/main.rs
Fix the issue  of debug  console couldn't work as expected.
Fix the issue of missing set hostname when run as init process.
> Fix issue of debug console

- src/runtime/virtcontainers/kata_agent.go
So that waiter gets notified when oom happens.
> virtcontainers: GetOOMEvent should have no timeout

- src/runtime/cli/kata-check_amd64.go
- src/runtime/cli/main.go
- src/runtime/virtcontainers/acrn.go
- src/runtime/virtcontainers/container.go
- src/runtime/virtcontainers/device/drivers/block.go
- src/runtime/virtcontainers/fc.go
- src/runtime/virtcontainers/kata_agent.go
- src/runtime/virtcontainers/pkg/rootless/rootless.go
- src/runtime/virtcontainers/proxy.go
- src/runtime/virtcontainers/qemu.go
- src/runtime/virtcontainers/qemu_amd64.go
- src/runtime/virtcontainers/qemu_s390x.go
- src/runtime/virtcontainers/utils/utils_linux_ppc64le.go
Fix issue links in source codes.
Fixes: #391
> runtime: fix wrong issue links

- src/runtime/virtcontainers/api.go
- src/runtime/virtcontainers/bridgedmacvlan_endpoint.go
- src/runtime/virtcontainers/device/config/config.go
- src/runtime/virtcontainers/device/drivers/generic.go
- src/runtime/virtcontainers/device/drivers/vfio.go
- src/runtime/virtcontainers/endpoint.go
- src/runtime/virtcontainers/ipvlan_endpoint.go
- src/runtime/virtcontainers/macvtap_endpoint.go
- src/runtime/virtcontainers/network.go
- src/runtime/virtcontainers/persist/api/device.go
- src/runtime/virtcontainers/physical_endpoint.go
- src/runtime/virtcontainers/qemu.go
- src/runtime/virtcontainers/sandbox.go
- src/runtime/virtcontainers/tap_endpoint.go
- src/runtime/virtcontainers/tuntap_endpoint.go
- src/runtime/virtcontainers/veth_endpoint.go
- src/runtime/virtcontainers/vhostuser_endpoint.go
- src/runtime/virtcontainers/vhostuser_endpoint_test.go
> [forwardport 2.0] create cgroup manager after creating the network 

- .github/workflows/PR-wip-checks.yaml
- .github/workflows/dco-check.yaml
33b1865e actions: Pin to a particular sha for actions
8564c99e actions: Add github actions to perform DCO check
c5081624 actions: Add action to perform WIP check for pull requests
> Backport actions from master

- src/runtime/virtcontainers/types/asset_test.go
Add additional test cases that cover more asset types and functions to
increase unit test coverage.
Fixes #424
> virtcontainers: Expand unit test coverage for asset

- src/runtime/containerd-shim-v2/create.go
- src/runtime/containerd-shim-v2/delete.go
- src/runtime/containerd-shim-v2/service.go
- src/runtime/containerd-shim-v2/shim_management.go
- src/runtime/containerd-shim-v2/utils.go
- src/runtime/containerd-shim-v2/wait.go
- src/runtime/virtcontainers/mount.go
Change some logger from directly calling logrus to use a
logrus instance to use structured log.
Fixes: #458
> runtime: change un-structured log to structured log

- src/agent/src/main.rs
It should setup the "lo" interface when agent run
as init porcess.
Fixes: #508
> agent: setup the "lo" interface run agent as init

- src/agent/rustjail/src/process.rs
Increase code coverage to 80.9%
fixes #285
> agent: add unit tests for rustjail/process.rs

- src/agent/rustjail/src/mount.rs
When do bind mount for container's volumes, the propagation
flags should be mount/set after bind mount.
Fixes: #530
> rustjail: fix the issue of missing set propagation for bind mount

- tools/osbuilder/scripts/install-yq.sh
- tools/osbuilder/scripts/lib.sh
This PR ports kata-containers/osbuilder#454 to kata 2.0
Fixes #576
> [forward port]: osbuilder: Update yq

- tools/packaging/kata-deploy/scripts/kata-deploy.sh
> Forward-port kata deploy conf

- src/runtime/virtcontainers/README.md
Add a guide on how to pass a VFIO-AP device, such as Crypto Express cards on IBM Z mainframes, to a Kata container.
Like the documentation for VFIO-PCI, this was put in the virtcontainers README.
/cc @alicefr
Fixes: #658
> docs: Add documentation for VFIO-AP passthrough

- versions.yaml
Update to the latest lts kernel in versions.yaml
Fixes: #654
> kernel: update to the latest LTS kernel 5.4.60

- .github/workflows/commit-message-check.yaml
> action: ignore 'fixes check' for subsystem 'release'

- tools/packaging/Makefile
Update the url of version file in Makefile.
Fixes: #756
> packaging: update version file url for kata 2.0 in Makefile

- .travis.yml
- src/agent/Cargo.lock
- src/agent/rustjail/Cargo.toml
- src/agent/rustjail/src/lib.rs
- src/agent/rustjail/src/mount.rs
> agent: Unit tests for rustjail/mount.rs

- tools/packaging/qemu/apply_patches.sh
- tools/packaging/static-build/qemu-virtiofs/Dockerfile
- tools/packaging/static-build/qemu/Dockerfile
This contain a fix to the qemu experimental which currently doesn't get some patches applied.
I took this opportunity to improve a little bit the build scripts for QEMU.
> Fix to qemu experimental and improvements

- src/agent/Makefile
Fixes: #812
Signed-off-by: Pradipta Kr. Banerjee <pradipta.banerjee@gmail.com>
> agent: Set LIBC=gnu for ppc64le arch by default

- docs/Developer-Guide.md
Include details on setting up rust.
Fixes: #851
> docs: update dev guide for agent build

- .github/workflows/snap.yaml
Add github action to test the snap
fixes #838
> ci: add github action to test the snap

- src/agent/rustjail/src/container.rs
On old kernels (like v4.9), kernel applies CLOECEC in wrong order w.r.t.
dumpable task flags. As a result, we might leak guest file descriptor to
containers. This is a former runc CVE-2016-9962 and still applies to
kata agent. Although Kata container is still valid at protecting the
host, we should not leak extra resources to user containers.
This sets the init processes that join and setup the container's
namespaces as non-dumpable before they setns to the container's pid (or
any other ) namespace.
This settings is automatically reset to the default after the Exec in
the container so that it does not change functionality for the
applications that are running inside, just our init processes.
This prevents parent processes, the pid 1 of the container, to ptrace
the init process before it …
> agent: set init process non-dumpable

- src/agent/rustjail/src/mount.rs
Attackers might use it to explore other containers in the same pod.
While it is still safe to allow it, we can just close the race window
like runc does.
Fixes: #885
ref: https://github.com/opencontainers/runc/pull/2207
> agent: do not follow link when mounting container proc and sysfs

- src/agent/Makefile
- tools/packaging/qemu/patches/5.1.x/0002-virtio-skip-legacy-support-check-on-machine-types-le.patch
- tools/packaging/qemu/patches/5.1.x/0003-vhost-vsock-pci-force-virtio-version-1.patch
- tools/packaging/qemu/patches/5.1.x/0004-vhost-user-vsock-pci-force-virtio-version-1.patch
- tools/packaging/qemu/patches/5.1.x/0005-vhost-vsock-ccw-force-virtio-version-1.patch
ARM CI is passing now http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-ARM-PR/409/console
Depends-on: github.com/kata-containers/tests#2945
> fix arm CI

- src/agent/rustjail/src/cgroups/fs/mod.rs
Somehow containerd is sending a malformed device with empty device type in update API. While it
should not happen, we should not panic either.
Fixes: #946
> agent: fix panic on malformed device resource in container update

- src/runtime/Makefile
- tools/packaging/qemu/patches/5.0.x/0003-virtiofsd-Used-glib-shared-thread-pool.patch
- tools/packaging/qemu/patches/5.1.x/0006-virtiofsd-Used-glib-shared-thread-pool.patch
This PR contains two patches mentioned by @dagrh during the Architecture Meeting Today that could help with performance.
Please, refer to:
https://github.com/kata-containers/kata-containers/issues/943 and https://github.com/kata-containers/kata-containers/issues/944
> VirtioFS: backports & default settings to improve performance

- src/agent/src/rpc.rs
> agent: simplify ttrpc error construction

- src/runtime/virtcontainers/qemu.go
- src/runtime/virtcontainers/qemu_arm64_test.go
port forward PR https://github.com/kata-containers/runtime/pull/3017
Fixes: #3016
@jodh-intel  @devimc @sameo
> arm64: correct bridge type for QEMUVIRT

- src/agent/rustjail/src/container.rs
Fix the permissions of PID 1's STDIO within the container to
the specified user.
The ownership needs to match because it is created outside of the
container and needs to be localized.
Fixes: #1022
> agent: fixes the permissions of PID 1's STDIO

- docs/Developer-Guide.md
- docs/Documentation-Requirements.md
- docs/Upgrading.md
- docs/install/container-manager/containerd/containerd-install.md
- docs/install/gce-installation-guide.md
- docs/install/minikube-installation-guide.md
- src/runtime/README.md
- src/runtime/cli/config-generated.go.in
- src/runtime/cli/kata-check.go
- src/runtime/cli/kata-env.go
- src/runtime/cli/main.go
- src/runtime/data/completions/bash/kata-runtime
- utils/kata-manager.sh
This PR solves some of the problems described in #1011. It's not perfect, but a start :)
> cli: Provide aliases for kata-* subcommands and options

- src/agent/src/sandbox.rs
Improve unit test coverage for src/sandbox.rs
fixes #293
> agent: Improve unit test coverage for src/sandbox.rs

- README.md
Rework the top-level README to reflect the current use of this
repository.
Fixes: #1064.
> docs: Update top-level README

- src/runtime/virtcontainers/clh.go
- src/runtime/virtcontainers/clh_test.go
Forward port PR kata-containers/runtime#3013 for issue kata-containers/runtime#3001.
Fixes: #1076
> clh: Consolidate the code path for device unplug

- src/runtime/virtcontainers/pkg/cloud-hypervisor/client/README.md
- src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
- src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/BalloonConfig.md
- src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/CpusConfig.md
- src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/MemoryConfig.md
- src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/VmConfig.md
- src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/VmInfo.md
- src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_balloon_config.go
- src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_cpus_config.go
- src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_memory_config.go
- src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_config.go
- src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_vm_resize.go
- src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
- versions.yaml
Forward port PR kata-containers/runtime#3013 for issue kata-containers/runtime#3001.
Fixes: #1089
> versions: Update cloud-hypervisor to release v0.11.0

- src/agent/README.md
README updates for agent build on ppc64le
Fix: https://github.com/kata-containers/kata-containers/issues/1069
Signed-off-by: Jing Wang <jing.wang4@ibm.com>
> Agent: README updates for build on ppc64le

- src/agent/Cargo.toml
- src/agent/src/linux_abi.rs
- src/agent/src/uevent.rs
port https://github.com/kata-containers/agent/pull/860 here.
Fixes: #1059
@jodh-intel @devimc
> agent: create pci root Bus Path for arm64

- src/agent/rustjail/src/container.rs
The main process do unshare pid namespace, the process
couldn't spawn new thread, in order to avoid this issue,
fork a new child process and do the pid namespace unshare
in the new temporary process.
Fixes: #1140
> rustjail: fork a new child process to change the pid ns

- src/runtime/virtcontainers/clh.go
We should always cleanup the vm directory when doing `stopSandbox`,
while we are skipping the cleanup process on some error code paths when
using cloud-hypervisor driver.
Fixes: #1098
> runtime: clh: Enforce to call 'cleanupVM' for 'stopSandbox'

- src/runtime/containerd-shim-v2/service.go
Sometimes shim process cannot be shutdown because of container list
is not empty. This container list is written in shim service, while
creating container. We find that if containerd cancel its Create
Container Request due to timeout, but runtime didn't handle it properly
and continue creating action, then this container cannot be deleted at
all. So we should make sure the ctx passed to Create Service rpc call
is effective.
Fixes #1088
Signed-off-by: Yves Chan <shanks.cyp@gmail.com>
> shimv2: handle ctx passed by containerd

- docs/install/snap-installation-guide.md
Improve snap documentation, document how to install
kata 1.x and 2.x, how to configure them and their integration
with container engines.
fixes #1138
> [forwardport] install: Improve snap documentation

- src/agent/src/random.rs
This PR wraps `fd` raw descriptor with `File`, so it'll be properly closed once exited.
> Don't leak fd when reseeding rng

- src/agent/Cargo.lock
- src/agent/Cargo.toml
- src/agent/oci/src/lib.rs
- src/agent/protocols/Cargo.toml
- src/agent/rustjail/src/cgroups/fs/mod.rs
- src/agent/rustjail/src/lib.rs
Fix #1211 
Also a minor improve to consume ttrpc from crates.io.
> oci: fix a typo in "addtionalGids"

- src/agent/rustjail/src/validator.rs
Several minor code improvements to rustjail/validator.
> improve rustjail validator

- src/agent/rustjail/src/mount.rs
In case the container rootfs's /dev was overrided
by binding mount from another directory, then there's
no need to create the default devices nodes and symlinks
in /dev.
Fixes: #692
> rustjail: fix the issue of bind mount /dev

- src/runtime/containerd-shim-v2/service.go
Add trace functions to shimv2. Tracing starts in New() which is called
twice, so the tracer is created twice. Stop tracing in Shutdown(),
Delete(), and StartShim() which is called after the initial New().
Load runtime config in New() since tracing cannot start without value
for Trace.
Fixes #903
> shimv2: Add tracing to shimv2

- .github/workflows/main.yaml
- .github/workflows/release.yaml
Still need pkg-sha
Fixes: #1273
> actions: fixup release/main workflow

- .github/workflows/main.yaml
set-env is no longer allowed. Updated to use the new recommended syntax.
Fixes: #1273
> actions: w/a deprecated set-env

- .github/workflows/main.yaml
- .github/workflows/release.yaml
- tools/packaging/release/tag_repos.sh
- tools/packaging/release/update-repository-version.sh
Backport of fixes from 2.0-dev:
- tag tests repo
- fix workflows
> Fix 2.0 stable release

- tools/osbuilder/README.md
- tools/osbuilder/image-builder/Dockerfile
- tools/osbuilder/image-builder/image_builder.sh
- tools/osbuilder/rootfs-builder/README.md
- tools/osbuilder/rootfs-builder/centos/Dockerfile.in
- tools/osbuilder/rootfs-builder/fedora/Dockerfile.in
- tools/osbuilder/rootfs-builder/rootfs.sh
This provides a small fix for urls from when the repositories were merged and some trivial improvements.
> osbuilder: miscelaneous fixes/improvements

- tools/osbuilder/README.md
> osbuilder: add description for how to use DISTRO variable

- .github/workflows/snap.yaml
- snap/snapcraft.yaml
> Fix Snap CI

- src/runtime/containerd-shim-v2/create.go
- src/runtime/containerd-shim-v2/service.go
Remove loading of configuration from New() so that it is not loaded more
than once. Start tracer in create() so that it is created after the
runtime config is loaded in its original location.
Fixes #1411
> runtime: Create tracer later in shimv2

- src/agent/Makefile
Add comments that allow self document variables and targets
Fixes: #1436
> makefile: agent: Add self documented help

- src/agent/Cargo.lock
- src/agent/Cargo.toml
- src/agent/protocols/Cargo.toml
- src/agent/protocols/build.rs
- src/agent/rustjail/Cargo.toml
- src/agent/rustjail/src/cgroups/notifier.rs
- src/agent/rustjail/src/pipestream.rs
- src/agent/rustjail/src/process.rs
- src/agent/src/device.rs
- src/agent/src/main.rs
- src/agent/src/netlink.rs
- src/agent/src/rpc.rs
- src/agent/src/sandbox.rs
- src/agent/src/uevent.rs
> agent: Upgrade tokio to 1.2.0

- src/agent/rustjail/src/cgroups/fs/mod.rs
- src/agent/rustjail/src/cgroups/notifier.rs
- src/agent/rustjail/src/container.rs
- src/agent/rustjail/src/validator.rs
- src/agent/src/device.rs
- src/agent/src/mount.rs
- src/agent/src/namespace.rs
- src/agent/src/netlink.rs
- src/agent/src/rpc.rs
- src/agent/src/sandbox.rs
- src/agent/src/uevent.rs
> agent: fix clippy for rustc 1.5

- src/agent/src/mount.rs
Port https://github.com/kata-containers/agent/pull/883 fix to the Rust Agent.
```
In the event that the virtiofs device is already mounted at the
requested destination, don't error out. We'll check before attempting to
mount to see if the destination is already a mount point. If so, skip
doing the mount in the agent.
This facilitates mounting the sharedfs automatically in the guest before
the agent service starts.
Signed-off-by: Eric Ernst eric.g.ernst@gmail.com
```
Fixes: #1398
cc: @egernst 
> agent: don't error of virtiofs share is already mounted

- src/agent/src/rpc.rs
- src/agent/src/sandbox.rs
Otherwise it would block the shutdown of ttrpc.
Fixes: #1524
> agent: disconnect rpc get_oom_event when destroy_sandbox.

- src/runtime/virtcontainers/pkg/cgroups/manager.go
- src/runtime/virtcontainers/pkg/cgroups/manager_test.go
- src/runtime/virtcontainers/pkg/cgroups/utils.go
- src/runtime/virtcontainers/pkg/cgroups/utils_test.go
Port to 2.0 stable branch https://github.com/kata-containers/kata-containers/pull/1514
> [backport] Fixup systemd cgroup handling

- src/agent/rustjail/src/container.rs
> rustjail: rework execute_hook

- src/agent/rustjail/src/cgroups/fs/mod.rs
It's better to get the online cpusets from
"/sys/devices/system/cpu/online" instead of from
cpuset cgroup, cause there would be an latency
between one cpu online and present in the root
cpuset cgroup.
Fixes: #1536
> cgroups: fix the issue of get wrong online cpus

- versions.yaml
Otherwise it breaks qemu release build.
> action: fix missing qemu tag

- docs/how-to/how-to-use-k8s-with-cri-containerd-and-kata.md
Update how-to-use-k8s-with-cri-containerd-and-kata.md to fit the latest
Kubernetes way.
And also changed CNI plugin from flannel to bridge, that will be easy to run.
Fixes: #1325
> docs: update how-to-use-k8s-with-cri-containerd-and-kata.md

- tools/agent-ctl/Cargo.lock
- tools/agent-ctl/Cargo.toml
> stable-2.0 | agent-ctl: update ttrpc version

- src/agent/src/console.rs
- src/agent/src/main.rs
- src/agent/src/util.rs
Rework the debug console with `tokio` + async and make it clear and easy to read.
> agent: Rework the debug console

- docs/Developer-Guide.md
- src/agent/rustjail/src/cgroups/fs/mod.rs
- src/agent/rustjail/src/cgroups/mock.rs
- src/agent/src/sandbox.rs
- tools/packaging/kata-deploy/k8s-1.18/kata-runtimeClasses.yaml
- tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml
- tools/packaging/release/update-repository-version.sh
The backports include fixes for:
#574, #1665, #580, #1156, and #1159
> stable-2.x | backports for 2.0.3

- src/runtime/virtcontainers/qemu.go
If the QEMU VMM fails to launch, we currently fail to kill virtiofsd,
resulting in leftover processes running on the host. Let's make sure we
kill these, and explicitly cleanup the virtiofs socket on the
filesystem.
Ideally we'll migrate QEMU to utilize the same virtiofsd interface that
CLH uses, but let's fix this bug as a first step.
Fixes: #1755
To reproduce / verify:
With non-static build of QEMU:
```
$ sudo mv /lib64/librbd.so.2 /lib64/librbd.so.1
$ sudo ctr run --rm  --runtime io.containerd.kata.v2 -t docker.io/library/busybox:latest sh
ctr: failed to launch qemu: exit status 127, error messages from qemu log: /usr/bin/qemu-kata-system-x86_64: error while loading shared libraries: librbd.so.1: cannot open shared object file: No such …
```
> qemu: kill virtiofsd if failure to start VMM

- src/runtime/virtcontainers/container.go
- src/runtime/virtcontainers/sandbox.go
Thanks help from @liubin when I was working on this issue.
> Fix the issue that sandbox size is not right after update

- ci/install_yq.sh
Check the yq version before return.
Fixes: #1776
Signed-off-by: Hui Zhu <teawater@antfin.com>
> ci/install_yq.sh: install_yq: Check version before return

- src/runtime/cli/kata-metrics.go
- src/runtime/cli/main.go
- src/runtime/pkg/kata-monitor/metrics.go
> stable-2.1 | Get sandbox metrics cli

- src/runtime/cli/config/configuration-acrn.toml.in
- src/runtime/cli/config/configuration-clh.toml.in
- src/runtime/cli/config/configuration-fc.toml.in
- src/runtime/cli/config/configuration-qemu.toml.in
- src/runtime/pkg/katautils/config.go
- src/runtime/virtcontainers/kata_agent.go
- src/runtime/virtcontainers/pkg/agent/protocols/client/client.go
> stable-2.1 | runtime: make dialing timeout configurable

- docs/how-to/how-to-use-virtio-mem-with-kata.md
Update this howto because the virtio-mem support of kata, qemu and Linux
was updated.
Fixes: #1845
Signed-off-by: Hui Zhu <teawater@antfin.com>
> how-to-use-virtio-mem-with-kata.md: Update doc to make it clear

- src/agent/src/main.rs
The Rust standard library had suppressed the default SIGPIPE
behavior, see https://github.com/rust-lang/rust/pull/13158.
Since the parent's signal handler would be inherited by it's child
process, thus we should re-enable the standard SIGPIPE behavior as a
workaround.
Fixes: #1887
> agent: re-enable the standard SIGPIPE behavior

- src/agent/rustjail/src/cgroups/fs/mod.rs
When update memory limit, we should adapt the write sequence
for memory and swap memory, so it won't fail because
the new value and the old value don't fit kernel's
validation.
Fixes: #1917
> cgroup: fix the issue of set mem.limit and mem.swap

- src/runtime/go.mod
- src/runtime/go.sum
- src/runtime/vendor/github.com/kata-containers/govmm/qemu/qemu.go
- src/runtime/vendor/modules.txt
- src/runtime/virtcontainers/hypervisor_ppc64le.go
- src/runtime/virtcontainers/qemu_ppc64le.go
Protected Execution Facility(PEF) is the confidential computing
technology on ppc64le. This PR adds the support for it in Kata.
Fixes: #1881
cc @bpradipt @clnperez
> runtime: Add support for PEF

- src/runtime/virtcontainers/kata_agent.go
- src/runtime/virtcontainers/network.go
- src/runtime/virtcontainers/network_test.go
- src/runtime/virtcontainers/sandbox.go
This commit fix some conments/logs.
And add some logs for debug.
Fixes: #1947
> runtime: fix some comments and logs

- src/agent/Cargo.lock
- src/agent/Cargo.toml
- src/agent/rustjail/Cargo.toml
- src/agent/rustjail/src/container.rs
- src/agent/src/console.rs
We need to fix some agent's code to conform to the latest nix crate
to be able to use new features of the nix.
Fixes: #1987
> agent: Conform to the latest nix version (0.21.0)

- src/runtime/virtcontainers/qemu_ppc64le_test.go
> ppc64le: Adding test for appendProtectionDevice

- docs/install/minikube-installation-guide.md
- src/runtime/README.md
6db24bbe docs: Update kata-deploy urls for installation document
2162422b docs: Update url for installation guides
> backport stable-2.1

- docs/use-cases/Intel-GPU-passthrough-and-Kata.md
- docs/use-cases/Nvidia-GPU-passthrough-and-Kata.md
- src/runtime/cli/config/configuration-fc.toml.in
- src/runtime/cli/config/configuration-qemu.toml.in
- src/runtime/go.mod
- src/runtime/go.sum
- src/runtime/pkg/katautils/config-settings.go.in
- src/runtime/vendor/github.com/kata-containers/govmm/qemu/qmp.go
- src/runtime/vendor/modules.txt
- src/runtime/virtcontainers/qemu.go
- src/runtime/virtcontainers/qemu_amd64.go
- src/runtime/virtcontainers/qemu_amd64_test.go
- src/runtime/virtcontainers/qemu_arch_base.go
- src/runtime/virtcontainers/qemu_arch_base_test.go
- src/runtime/virtcontainers/qemu_test.go
Fixes #1953
Depends-on: github.com/kata-containers/tests#3586
Signed-off-by: Marcel Apfelbaum <marcel@redhat.com>
> Remove the pc machine

- docs/Documentation-Requirements.md
This PR updates the proper urls for the Documentation Requirements document.
Fixes #2094
> docs: Update urls for Documentation Requirements document

- src/runtime/containerd-shim-v2/start.go
After create an container/exec successfully, containerd
would wait it immediately, and if start it failed, there
is no chance to send value to exitCh, thus the wait goroutine
would blocked for ever and had no chance to exit.
Fixes: #2087
> shimv2: fix the issue of leaking wait goroutines

- docs/Documentation-Requirements.md
This PR updates the proper urls for the Documentation Requirements document.
Fixes #2094
> stable-2.1 | docs: Update urls for Documentation Requirements document

- docs/use-cases/using-Intel-QAT-and-kata.md
- tools/osbuilder/dockerfiles/QAT/Dockerfile
- tools/osbuilder/dockerfiles/QAT/run.sh
The QAT driver version changed and needs updating in a few locations.
> Update qat version

- docs/how-to/how-to-use-virtio-fs-with-kata.md
This PR updates the url for virtiofs documentation.
Fixes #2134
> docs: Fix url in virtiofs documentation

- src/agent/src/rpc.rs
- src/agent/src/sandbox.rs
- src/agent/src/tracer.rs
- src/runtime/virtcontainers/agent.go
- src/runtime/virtcontainers/kata_agent.go
- src/runtime/virtcontainers/kata_agent_test.go
- src/runtime/virtcontainers/mock_agent.go
- src/runtime/virtcontainers/mount.go
- src/runtime/virtcontainers/pkg/agent/protocols/client/client.go
- src/runtime/virtcontainers/qemu.go
- src/runtime/virtcontainers/vm.go
Pass span context from runtime to agent to get a full trace #1968
Now WIP, but review is welcome. @jodh-intel @cmaf
> Pass span context from runtime to agent to get a full trace #1968

- src/agent/src/config.rs
This commit cleans up config parsing and testing code to make it a bit more easy to maintain.
- Adds `with_context` from `anyhow` to include the underlying error. This helps to understand what exactly went wrong.
- Uses `ensure!` and `bail!` as a shorter alternative for `if` checks.
- `TestData` in `test_parse_cmdline` is now implements `Default` trait to reduce boilerplate code.
- Remove `make_err` as it doesn’t make any sense.
Fixes: #2177
> agent: Cleanup config

- src/agent/rustjail/src/container.rs
Use which to find the full path of exe before run execute_hook
to avoid error: 'No such file or directory'
Fixes: #2172
> agent: enhance tests of execute_hook

- src/runtime/containerd-shim-v2/utils_test.go
- src/runtime/virtcontainers/pkg/agent/protocols/client/client.go
- src/runtime/virtcontainers/pkg/cpuset/cpuset.go
Apart from the work done on the tests repo to ignore the `govet` issues, let's fix the few others that are easily fixed as part of this PR.
Fixes: #2204
> runtime: Fix lint issues

- src/runtime/virtcontainers/clh.go
When checking clh's binary path if valid, return error even
though the error is not a IsNotExist error.
And add errors to log filed when errors occurred.
Fixes: #2208
> runtime: return error if clh's binary doesn't have a normal stat

- .github/workflows/static-checks.yaml
- ci/lib.sh
> ci: static checks: use defined target_branch

- src/runtime/virtcontainers/bridgedmacvlan_endpoint.go
- src/runtime/virtcontainers/device/config/pmem.go
- src/runtime/virtcontainers/device/drivers/utils.go
- src/runtime/virtcontainers/device/drivers/vfio.go
- src/runtime/virtcontainers/device/manager/manager.go
- src/runtime/virtcontainers/documentation/api/1.0/api.md
- src/runtime/virtcontainers/ipvlan_endpoint.go
- src/runtime/virtcontainers/sandbox.go
- src/runtime/virtcontainers/tuntap_endpoint.go
Some comments are old or copy miss, not suitable for the code.
And the API doc for virtcontainers is old.
Fixes: #2187
> Update outdated comments and do some minor reworks

- src/runtime/cli/config/configuration-acrn.toml.in
- src/runtime/cli/config/configuration-clh.toml.in
- src/runtime/cli/config/configuration-fc.toml.in
- src/runtime/cli/config/configuration-qemu.toml.in
- Update url for osbuilder
- Fix typo about poststart
Fixes: #2260
> config: Fix description for OCI hooks

- src/agent/src/mount.rs
It's better to check whether the destination file exists
before creating them, if it had been existed, then return
directly.
Fixes: #2247
> mount: fix the issue of missing check file exists

- docs/design/README.md
- docs/design/proposals/README.md
- docs/design/proposals/tracing-proposals.md
Create a document summarising the tracing design proposals from PR #1937.
Fixes: #2061.
> docs: Add tracing proposals doc

- src/runtime/virtcontainers/clh.go
When enabling tracing with Cloud Hypervisor, we end up establishing 2
connections to 2 different HTTP servers: The Cloud Hypervisor API one
that runs over a UNIX socket and the Jaeger endpoint running over UDP.
Both connections use the default HTTP golang client instance, and thus
share the same transport layer. As the Cloud Hypervisor implementation
sets it up to be over a Unix socket, the jaeger uploader ends up going
through that transport as well, and sending its spans to the Cloud
Hypervisor API server.
We fix that by giving the Cloud Hypervisor implementation its own HTTP
client instance and we avoid sharing it with anything else in the shim.
Fixes #2364
Signed-off-by: Samuel Ortiz <samuel.e.ortiz@protonmail.com>
> virtcontainers: clh: Do not use the default HTTP client

- src/agent/rustjail/src/cgroups/fs/mod.rs
- src/agent/rustjail/src/container.rs
- src/agent/rustjail/src/mount.rs
- src/agent/rustjail/src/validator.rs
- src/agent/src/config.rs
- src/agent/src/device.rs
- src/agent/src/main.rs
- src/agent/src/metrics.rs
- src/agent/src/mount.rs
- src/agent/src/namespace.rs
- src/agent/src/netlink.rs
- src/agent/src/network.rs
- src/agent/src/rpc.rs
- src/agent/src/sandbox.rs
- src/agent/src/uevent.rs
Mostly the needless borrow one, plus a few others that are now enforced.
Fixes #2408
> agent: Fix cargo 1.54 clippy warning

- src/runtime/virtcontainers/utils/utils_test.go
Simplify tests in utils_test.go by table-driven tests.
Fixes: #2281
Signed-off-by: Yujia Qiao <rapiz3142@gmail.com>
> virtcontainers: simplify tests

- src/runtime/virtcontainers/clh.go
- src/runtime/virtcontainers/qemu.go
Initialize and assign a value, reducing one append operation
Fixes: #2264
> runtime: Optimize the way slice created

- docs/how-to/what-is-vm-templating-and-how-do-I-use-it.md
- src/runtime/cli/main_test.go
- src/runtime/containerd-shim-v2/utils_test.go
- src/runtime/pkg/katautils/config-settings.go.in
- src/runtime/pkg/katautils/create_test.go
- src/runtime/virtcontainers/qemu_amd64.go
- src/runtime/virtcontainers/qemu_arch_base.go
- src/runtime/virtcontainers/qemu_arch_base_test.go
> runtime: drop qemu-lite support

- src/runtime/go.mod
- src/runtime/go.sum
- src/runtime/vendor/github.com/kata-containers/govmm/qemu/qemu.go
- src/runtime/vendor/github.com/kata-containers/govmm/qemu/qmp.go
- src/runtime/vendor/modules.txt
- src/runtime/virtcontainers/qemu.go
Use ExecuteBlockdevAddWithDriverCache with swap in hotplugAddBlockDevice to handle swap file cannot work OK with ExecuteBlockdevAddWithCache issue.
Fixes: #2548
> Fix swap fail insert fail issue

- src/runtime/virtcontainers/persist/manager.go
- src/runtime/virtcontainers/persist_test.go
remove NewStoreFeature
Fixes: #2296
> virtcontainers: Remove NewStoreFeature

- src/agent/protocols/protos/agent.proto
- src/agent/src/rpc.rs
- tools/agent-ctl/src/client.rs
- tools/osbuilder/rootfs-builder/fedora/Dockerfile.in
- tools/osbuilder/rootfs-builder/fedora/config.sh
This commit adds the PullImge endpoint to the agent
and the agent-ctl command to test it.
Fixes: #2509
Signed-off-by: Georgina Kinge <georgina.kinge@ibm.com>
> CCv0 | agent: Add PullImage endpoint

- .github/workflows/static-checks.yaml
- src/agent/Makefile
- src/agent/src/watcher.rs
- src/runtime/Makefile
- src/runtime/cli/kata-check.go
- src/runtime/cli/kata-check_amd64.go
- src/runtime/cli/kata-check_amd64_test.go
- src/runtime/cli/kata-check_test.go
- src/runtime/pkg/katatestutils/utils.go
- src/runtime/virtcontainers/factory/template/template_test.go
- src/runtime/virtcontainers/vm.go
- src/runtime/virtcontainers/vm_test.go
Add tests that run under root user to test special cases.
Fixes: #2446
> test: enable running tests under root user

- src/runtime/virtcontainers/sandbox.go
adds the default devices for unix such as /dev/null, /dev/urandom to
the container's resource cgroup spec
Fixes: #2539
> sandbox: Add device permissions such as /dev/null to cgroup

- docs/how-to/README.md
- docs/how-to/how-to-set-sandbox-config-kata.md
- docs/how-to/how-to-setup-swap-devices-in-guest-kernel.md
- src/runtime/README.md
Add doc for guest swap
Fixes: #2326
> Add doc for guest swap

- src/runtime/virtcontainers/container_test.go
> virtcontainers: add unit tests for container.go

- src/runtime/containerd-shim-v2/service.go
- src/runtime/virtcontainers/sandbox.go
Backport @snir911's fixes for #2527 to stable-2.2.
Fixes #2527
> shimv2: Backport fixes for #2527

- tools/packaging/scripts/configure-hypervisor.sh
Fixes: kata-containers/tests#3993
> packaging: fix qemu build on ppc64le

- src/runtime/virtcontainers/pkg/cgroups/cgroups.go
There are `DeviceToDeviceCgroup` and `deviceToDeviceCgroup` two functions,
creating a `specs.LinuxDeviceCgroup` object. We clear the new function `deviceToDeviceCgroup`.
Fixes: #2694
> runtime: clear virtcontainers cgroup duplicated function

- src/runtime/virtcontainers/Makefile
modify to the correct relative path
Fixes: #2515
> virtcontainers: Fix incorrect scripts path

- src/runtime/virtcontainers/utils/utils_linux.go
- src/runtime/virtcontainers/utils/utils_linux_generic.go
> virtcontainers: clean up useless code

- tools/packaging/scripts/configure-hypervisor.sh
We explicitely set the Postion Independant Executlable (PIE) options
in the extra CFLAGS and LDFLAGS that are passed to the QEMU configure
script for all archs. This means that these options are used pretty
much everywhere, including when building the sample plugins under the
test directory. These cannot be linked with -pie and break the build,
as experienced recently on ARM (see PR #2732).
This only broke on ARM because other archs are configured with
--disable-tcg : this disables plugins which are built by default
otherwise.
The --enable-pie option is all that is needed. The QEMU build system
knows which binaries should be created as PIE, e.g. the important
bits like QEMU and virtiofsd, and which ones should not, e.g. the
sample plugins that aren't used in production.
Rely on …
> packaging: Configure QEMU with --enable-pie

- tools/packaging/kernel/build-kernel.sh
> package: assign proper value to redefined_string  in build-kernel.sh

- docs/how-to/how-to-use-kata-containers-with-acrn.md
fix outdated links which were checked out by workflow/docs-url-alive-check
Fixes #2630
> docs: Fix outdated links

- src/agent/rustjail/src/process.rs
- src/agent/src/rpc.rs
Move closing IO into process.rs and use macro
to reduce codes.
Fixes: #2944
> agent: refactor process IO processing

- src/agent/rustjail/src/container.rs
Invalid environment variable key/value will cause set_env panic.
Refer: https://doc.rust-lang.org/std/env/fn.set_var.html#panics
Fixes: #3006
> agent: check environment variables if empty or invalid

- src/agent/README.md
Update the agent README by removing the historical details about the
conversion from golang to rust which (occurred at the start of Kata 2.x
development) and replacing it with information that developers and
testers should find more useful.
Fixes: #3056.
> agent: Update README

- src/agent/src/watcher.rs
The current implementation just copies the file, dereferencing any
simlinks in the process. This results in symlinks no being preserved,
and a change in layout relative to the mount that we are making
watchable.
What we want is something like "cp -d"
This isn't available in a crate, so let's go ahead and introduce a copy
function which will create a symlink with same relative path if the
source file is a symlink. Regular files are handled with the standard
fs::copy.
Introduce a unit test to verify symlinks are now handled 
Fixes: #2950
> watchers: don't dereference symlinks when copying files

- src/agent/src/watcher.rs
Backport of https://github.com/kata-containers/kata-containers/pull/2998
```
The current implementation just copies the file, dereferencing any
simlinks in the process. This results in symlinks no being preserved,
and a change in layout relative to the mount that we are making
watchable.
What we want is something like "cp -d"
This isn't available in a crate, so let's go ahead and introduce a copy
function which will create a symlink with same relative path if the
source file is a symlink. Regular files are handled with the standard
fs::copy.
Introduce a unit test to verify symlinks are now handled
```
> backport: fix symlink handling in agent watcher

- docs/use-cases/using-SPDK-vhostuser-and-kata.md
Use `ctr` instead of `Docker`.
Fixes: #3054
> docs: update using-SPDK-vhostuser-and-kata.md

- docs/README.md
- docs/Unit-Test-Advice.md
- docs/code-pr-advice.md
Add a document giving advice to code PR authors.
Fixes: #3099.
> docs: Add a code PR advice document

- src/agent/src/rpc.rs
- src/agent/src/sandbox.rs
Delete redundant parameter init in find_process function and
add test case for it.
Fixes: #3117
> agent: refactor find_process function and add test cases

- src/agent/src/mount.rs
- src/agent/src/rpc.rs
Using sandbox ID as the key will cause the failed containers' storage
leak.
Fixes: #3172
> agent: user container ID as watchable storage key for hashmap

- docs/code-pr-advice.md
- snap/snapcraft.yaml
- src/runtime/virtcontainers/factory/factory.go
- src/runtime/virtcontainers/factory/template/template.go
- src/runtime/virtcontainers/kata_agent.go
- src/runtime/virtcontainers/qemu.go
- tools/osbuilder/image-builder/image_builder.sh
- tools/osbuilder/rootfs-builder/alpine/Dockerfile.in
- tools/osbuilder/rootfs-builder/alpine/config.sh
- tools/osbuilder/rootfs-builder/alpine/rootfs_lib.sh
- tools/osbuilder/rootfs-builder/rootfs.sh
- versions.yaml
Weekly merge of new commits in main into CCv0
Fixes: #3259
> CCv0: Merge main into CCv0 branch

- docs/design/architecture.md
Refresh the content and formatting of the architecture document.
Out of scope of these changes:
- Diagram updates.
- Updates to the Networking section.
Fixes: #3190.
> docs: Update architecture document

- src/agent/src/config.rs
- src/agent/src/main.rs
- Add option to pass in config with -c/--config
Fixes: #3252
> agent: Add config file option to cli

- docs/how-to/README.md
- docs/how-to/how-to-run-docker-with-kata.md
Fixes: #2474
Signed-off-by: vados <vados@vadosware.io>
> docs: add how-to on DinD in Kata

- src/agent/src/rpc.rs
For calls from shim to agent, the return error will be processed like this:
```rust
match self.do_start_container(req).await {
Err(e) => Err(ttrpc_error(ttrpc::Code::INTERNAL, e.to_string())),
Ok(_) => Ok(Empty::new()),
}
```
The `e.to_string()` return only a part of the error(for example set by `context()` on a `nix` Error),
this may lead lack of information.
The `format!("{:?}", err)` will return more info.
Logs before and after this patch:
Before:
> "rpc error: code = Internal desc = failed to umount \"/run/kata-containers/sandbox/ephemeral/hugepage\""
After:
> "rpc error: code = Internal desc = failed to umount \"/run/kata-containers/sandbox/ephemeral/hugepage\"\n\nCaused by:\n    EINVAL: Invalid argument"
Fixes: #3353
> agent: return detail error message for RPC calls from shim

- docs/Upgrading.md
This PR removes a word duplication in the Upgrading documentation.
Fixes #3381
> docs: Remove word duplication

- tools/packaging/kata-deploy/action/Dockerfile
tar params are passed wrongly
Fixes: #3394
> kata-deploy: fix tar command in dockerfile

- tools/packaging/kata-deploy/action/Dockerfile
backports https://github.com/kata-containers/kata-containers/pull/3395
> stable-2.3 | kata-deploy: fix tar command in dockerfile

- src/runtime/virtcontainers/sandbox.go
When Sandbox AddInterface() is called, it may fail after endpoint.HotAttach,
we'd better rollback and call save() in the end.
Fixes: #3419 
Signed-off-by: yangfeiyu <yangfeiyu20102011@163.com>
> runtime: it should rollback when failed in Sandbox AddInterface

- tools/packaging/qemu/patches/6.1.x/0001-arm-cpuhp-Add-QMP-vcpu-params-validation-support.patch
- tools/packaging/qemu/patches/6.1.x/0002-arm-cpuhp-Add-new-ARMCPU-core-id-property.patch
- tools/packaging/qemu/patches/6.1.x/0003-arm-cpuhp-Add-common-cpu-utility-for-possible-vcpus.patch
- tools/packaging/qemu/patches/6.1.x/0004-arm-cpuhp-Machine-init-time-change-common-to-vcpu-co.patch
- tools/packaging/qemu/patches/6.1.x/0005-arm-cpuhp-Pre-create-disabled-possible-vcpus-machine.patch
- tools/packaging/qemu/patches/6.1.x/0006-arm-cpuhp-Changes-to-pre-size-GIC-with-possible-vcpu.patch
- tools/packaging/qemu/patches/6.1.x/0007-arm-cpuhp-Init-PMU-at-host-for-all-possible-vcpus.patch
- tools/packaging/qemu/patches/6.1.x/0008-arm-cpuhp-Enable-ACPI-support-for-vcpu-hotplug.patch
- tools/packaging/qemu/patches/6.1.x/0009-arm-cpuhp-Init-GED-framework-with-cpu-hotplug-events.patch
- tools/packaging/qemu/patches/6.1.x/0010-arm-cpuhp-Update-CPUs-AML-with-cpu-ctrl-dev-change.patch
- tools/packaging/qemu/patches/6.1.x/0011-arm-cpuhp-Update-GED-_EVT-method-AML-with-cpu-scan.patch
- tools/packaging/qemu/patches/6.1.x/0012-arm-cpuhp-MADT-Tbl-change-to-size-the-guest-with-pos.patch
- tools/packaging/qemu/patches/6.1.x/0013-arm-cpuhp-Add-ACPI-_MAT-entry-for-Processor-object.patch
- tools/packaging/qemu/patches/6.1.x/0014-arm-cpuhp-Release-objects-for-disabled-possible-vcpu.patch
- tools/packaging/qemu/patches/6.1.x/0015-arm-cpuhp-Update-ACPI-GED-framework-to-support-vcpu-.patch
- tools/packaging/qemu/patches/6.1.x/0016-arm-cpuhp-Add-update-basic-hot-un-plug-framework.patch
- tools/packaging/qemu/patches/6.1.x/0017-arm-cpuhp-Changes-to-un-wire-GICC-VCPU-IRQs-during-h.patch
- tools/packaging/qemu/patches/6.1.x/0018-arm-cpuhp-Changes-to-update-GIC-with-vcpu-hot-plug-n.patch
- tools/packaging/qemu/patches/6.1.x/0019-arm-cpuhp-Changes-required-to-re-init-the-vcpu-regis.patch
- tools/packaging/qemu/patches/6.1.x/0020-arm-cpuhp-Update-the-guest-via-GED-about-cpu-hot-un-.patch
- tools/packaging/qemu/patches/6.1.x/0021-arm-cpuhp-Changes-required-for-reset-and-to-support-.patch
- tools/packaging/qemu/patches/6.1.x/0022-arm-cpuhp-Add-support-of-unrealize-ARMCPU-during-vcp.patch
- tools/packaging/qemu/patches/6.1.x/0023-armcpuhp-initial-pvtime-and-pmu-for-all-possible-cpu.patch
- tools/packaging/qemu/patches/6.1.x/0024-armcpuhp-add-cpu-hotunplug-frame-work-in-acpi-device.patch
- tools/packaging/qemu/patches/6.1.x/0025-cleanup-code-of-arm-cpu-hotplug-support.patch
- tools/packaging/qemu/patches/6.1.x/0026-armcpuhp-set-cpu-disabled-to-true-when-initialize-cp.patch
- tools/packaging/qemu/patches/6.1.x/0027-armcpuhp-clean-acpi-ged-call-back.patch
- tools/packaging/qemu/patches/6.1.x/0028-armcpuhp-fix-bug-when-maxvcpu-number-larger-than-8.patch
Enable the vcpu-hotplug with the patches (most patch are from Salil Mehta).
Signed-off-by: Huang Shijie <shijie8@gmail.com>
> experimentally enable the vcpu-hotplug for arm in qemu side

- src/agent/rustjail/src/mount.rs
- src/agent/src/util.rs
A few tests have unused or unread variables. Let's clean these up...
Fixes: #3530
> agent: resolve unused variables in tests

- src/agent/rustjail/src/mount.rs
- src/agent/src/network.rs
- src/agent/src/uevent.rs
- src/agent/src/util.rs
These result in build failures when using recent toolchain - let's ensure these fixes are on stable branch as well.
> stable-2.3: backport lint fixes from main

- docs/design/architecture/networking.md
Updated the doc to clarify certain networking details and add
external links to some of the networking terms used.
Fixes #3308
> docs: Update networking details in the architecture doc

- docs/how-to/ccv0.sh
- docs/how-to/how-to-build-and-test-ccv0.md
- Add scripts and documentation to build, configure and test
created a Kata CC unencrypted container using Kubernetes
- Switch test images to quay.io as image_rpc.rs has some
problems with docker.io?
- Update documentation to better fit the kata documentation
requirements and fix typos
- Fixes: #3511
> CCv0 | doc: Add k8s e2e doc and scripts 

- docs/Release-Process.md
- tools/packaging/scripts/lib.sh
> Release process related fixes

- src/runtime/virtcontainers/qemu_amd64.go
Enable SGX in QEMU when `sgx.intel.com/epc` annotation is defined
fixes #3436
> runtime: support QEMU SGX

- docs/how-to/how-to-import-kata-logs-with-fluentd.md
See
https://github.com/kubernetes/kubernetes/commit/5d9b7ae9e5174f898d3b06c21cb2355e759bd94a#diff-ada96bec4aba13195248d6dd21ee67e333bead2bd898b81a1b089d53bd06b4d8R2820
Fixes #3616
> docs: Update link to EFK stack docs

- src/agent/src/device.rs
- src/agent/src/mount.rs
- src/runtime/go.mod
- src/runtime/vendor/modules.txt
- src/runtime/virtcontainers/container.go
- src/runtime/virtcontainers/device/config/pmem.go
- src/runtime/virtcontainers/kata_agent.go
- src/runtime/virtcontainers/kata_agent_test.go
- src/runtime/virtcontainers/mount.go
- src/runtime/virtcontainers/sandbox.go
- src/runtime/virtcontainers/sandbox_test.go
- src/runtime/virtcontainers/utils/utils_linux.go
- src/runtime/virtcontainers/utils/utils_linux_test.go
Porting of:
- kata-containers/agent#872
- kata-containers/runtime#3109
Fixes: #3342
> feature: hugepages support

- src/runtime/virtcontainers/container.go
- src/runtime/virtcontainers/device/manager/utils.go
- src/runtime/virtcontainers/device/manager/utils_test.go
- src/runtime/virtcontainers/sandbox_test.go
With the recently added VFIO fixes and support, we should not need that
anymore.
Fixes #3108
> container: Remove VFIO lazy attach handling

- docs/how-to/ccv0.sh
- docs/how-to/how-to-build-and-test-ccv0.md
- Add scripts and documentation to build, configure and test
the ssh-demo encrypted image sample in Kubernetes
Fixes: #3637
> doc: Add doc and script for ssh-demo sample

- src/runtime/virtcontainers/network_linux.go
As the container runtime, we're never inspecting, adding or configuring
host networking endpoints.
Make sure we're always do that by wrapping addSingleEndpoint calls into
the pod network namespace.
Fixes #3661
> runtime: Always add network endpoints from the pod netns

- src/agent/rustjail/src/container.rs
Backport of:
- https://github.com/kata-containers/kata-containers/pull/3007
- 57bb7ffae356241c6216f27fcef5fbe293b86c0b
- https://github.com/kata-containers/kata-containers/pull/3351
- 4fc4c76b874782aaa8003639d723444d5993b0bd
- https://github.com/kata-containers/kata-containers/pull/3668
- c37447520ab44fc613559673f0c251edbca71936
- 5e7dcac18313903d147f27c7fb77fdefa49fbc43
> stable-2.3 | agent: fix invalid hooks env issues

- src/runtime/config/configuration-clh.toml.in
- src/runtime/config/configuration-qemu.toml.in
- src/runtime/pkg/katautils/config.go
- src/runtime/virtcontainers/clh.go
- src/runtime/virtcontainers/hypervisor.go
- src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml
- src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/DefaultApi.md
- src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/DeviceNode.md
- src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/ReceiveMigrationData.md
- src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/SendMigrationData.md
- src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_device_node.go
- src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_receive_migration_data.go
- src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_send_migration_data.go
- src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml
- src/runtime/virtcontainers/qemu_amd64.go
- src/runtime/virtcontainers/qemu_arch_base.go
- src/runtime/virtcontainers/qemu_ppc64le.go
- src/runtime/virtcontainers/qemu_s390x.go
- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
- tools/packaging/static-build/cloud-hypervisor/build-static-clh.sh
- versions.yaml
TDX support using td-shim has been added to cloud-hypervisor not so long ago, and in this series I'm bringing that functionality to the cloud-hypervisor driver.
Fixes: #3632
> clh: Add TDX support

- tools/packaging/scripts/configure-hypervisor.sh
> Update QEMU >= 6.1.0 in configure-hypervisor.sh

- src/runtime/virtcontainers/clh.go
If, for some reason, we're able to launch cloud hypervisor but not able
to boot the VM up, the virtiofsd process would be left behind.
Let's ensure, via defer, that we stop virtiofsd in case of errors.
Fixes: #3819
Backports: #3823
> stable-2.3 | clh: stop virtofsd if clh fails to boot up the vm

- src/runtime/README.md
This PR updates the contact link in the runtime README document.
Fixes #3854
> docs: Update contact link in runtime README

- src/runtime-rs/Cargo.lock
- src/runtime-rs/crates/shim/Cargo.toml
- src/runtime-rs/crates/shim/src/bin/main.rs
- src/runtime-rs/crates/shim/src/shim.rs
- src/runtime-rs/crates/shim/src/shim_start.rs
1. runtime-rs: update containerd-shim-protos to 0.2.0
Fixes: #3866
2. runtime-rs: modify the review suggestion
Fixes: #3876
> runtime-rs: modify the review suggestion for shim-part

- docs/how-to/run-kata-with-k8s.md
Update documentation with missing step to untaint node to enable
scheduling and update the example to run a pod using the kata runtime
class instead of untrusted workloads, which applies to versions of CRI-O
prior to v1.12.
Fixes #3863
The example for running a pod comes from the [doc](https://github.com/kata-containers/kata-containers/blob/main/docs/how-to/how-to-use-k8s-with-cri-containerd-and-kata.md#allow-pods-to-run-in-the-master-node) for configuring with CRI containerd.
> docs: Update k8s documentation

- tools/packaging/static-build/cloud-hypervisor/build-static-clh.sh
Right now it doesn't do much for us, as we're always building from a
specific version.  However, this opens the possibility for us to add a
CI, similar to the one we have for CRI-O, for testing against each
cloud-hypervisor PR, on the cloud-hypervisor branch.
Fixes: #3908
> static-build,clh: Add the ability to build from a PR

- src/libs/kata-types/src/config/agent.rs
- src/libs/kata-types/src/config/mod.rs
- src/runtime-rs/Cargo.lock
- src/runtime-rs/Cargo.toml
- src/runtime-rs/crates/agent/Cargo.toml
- src/runtime-rs/crates/agent/src/kata/agent.rs
- src/runtime-rs/crates/agent/src/kata/mod.rs
- src/runtime-rs/crates/agent/src/kata/trans.rs
- src/runtime-rs/crates/agent/src/lib.rs
- src/runtime-rs/crates/agent/src/log_forwarder.rs
- src/runtime-rs/crates/agent/src/sock/hybrid_vsock.rs
- src/runtime-rs/crates/agent/src/sock/mod.rs
- src/runtime-rs/crates/agent/src/sock/vsock.rs
- src/runtime-rs/crates/agent/src/types.rs
Responsible for communicating with the agent, such as kata-agent in the VM
Fixes: #3785
> runtime-rs: agent implements:

- docs/how-to/run-kata-with-k8s.md
Update documentation with missing step to untaint node to enable
scheduling and update the example to run a pod using the kata runtime
class instead of untrusted workloads, which applies to versions of CRI-O
prior to v1.12.
Fixes #3863
(cherry picked from commit 5c434270d14734455aad133624a7ab5379cf7be8)
Backport of https://github.com/kata-containers/kata-containers/pull/3868
> stable-2.4 | docs: Update k8s documentation

- tools/osbuilder/dockerfiles/QAT/run.sh
don't pull kata sources if they already exist under GOPATH
fixes #3965
> osbuilder/qat: don't pull kata sources if exist

- src/agent/src/rpc.rs
- src/runtime/pkg/containerd-shim-v2/service.go
- src/runtime/pkg/containerd-shim-v2/start.go
- src/runtime/pkg/containerd-shim-v2/stream.go
- src/runtime/pkg/containerd-shim-v2/stream_test.go
- src/runtime/pkg/containerd-shim-v2/wait.go
backport #3955
/cc @fengwang666
> agent: Signal the whole process group

- tools/packaging/release/update-repository-version.sh
In such a case, we should bump from the "latest" tag rather than from
current_version.
Fixes: #3986
> kata-deploy: fix version bump from -rc to stable

- src/runtime/pkg/containerd-shim-v2/wait.go
- src/runtime/virtcontainers/monitor.go
Stop getting OOM events from agent for "ttrpc closed" error
Fixes: #3815
> Stop getting OOM events from agent for "ttrpc closed" error

- src/agent/rustjail/src/process.rs
- src/agent/src/rpc.rs
The nix::sys::signal::Signal package api cannot deal with SIGRTMIN+3,
directly use libc function to send the signal.
Fixes: #3990
Signed-off-by: Wang Xingxing <stellarwxx@163.com>
(cherry picked from commit 0d765bd08248887ad3084df0c5483e551295e91a)
Signed-off-by: Wang Xingxing <stellarwxx@163.com>
> stable-2.4 | agent: fix container stop error with signal SIGRTMIN+3

- docs/how-to/README.md
- docs/how-to/how-to-use-kata-containers-with-firecracker.md
Add info on setting up kata with firecracker.
Fixes: #3555
Signed-off-by: George Ntoutsos <gntouts@nubificus.co.uk>
> docs: Add a firecracker installation guide

- src/agent/src/rpc.rs
Add test coverage for update_container_namespaces function
in src/rpc.rs. Includes minor refactor to make function easier
to test.
Fixes #4034
> agent: add tests for update_container_namespaces

- src/agent/src/mount.rs
Add test coverage for mount_to_rootfs function in src/mount.rs.
Includes minor refactoring to make function more easily testable.
Fixes #4073
> agent: add tests for mount_to_rootfs function

- src/agent/rustjail/src/mount.rs
Add tests for the mount_from function in rustjail mount.rs file.
Fixes: #4121
> rustjail: add tests for mount_from function

- src/agent/src/random.rs
Expands MR #1677 with the suggestions from @jodh-intel.
Fixes #291
cc @wainersm @fidencio
> Agent: Unit tests for random.rs

- docs/design/README.md
- docs/design/direct-blk-device-assignment.md
> docs: repropose direct-assigned volume

- src/runtime/virtcontainers/qemu.go
The vhost-user-blk can be hotplugged on the PCI bridge succesfullly on
X86, but failed on Arm. However, hotplugging it on Root Port as a PCIe
device can work well on ARM.
Open the "pcie_root_port" in configuration.toml is needed.
Fixes: #4019
Signed-off-by: Jaylyn Ren <jaylyn.ren@arm.com>
> Virtcontainers: Enable hot plugging vhost-user-blk device on ARM

- src/agent/src/watcher.rs
Today in agent watchers, when we copy files/symlinks
or create directories, the ownership of the source path
is not preserved which can lead to permission issues.
In copy, ensure that we do a chown of the source path
uid/gid to the destination file/symlink after copy to
ensure that ownership matches the source ownership.
fs::copy() takes care of setting the permissions.
For directory creation, ensure that we set the permissions
of the created directory to the source directory permissions
and also perform a chown of the source path uid/gid to
ensure directory ownership and permissions matches to the source.
Fixes: #4188
Signed-off-by: Yibo Zhuang <yibzhuang@gmail.com>
> agent watchers: ensure uid/gid is preserved on copy/mkdir

- src/agent/src/watcher.rs
- src/runtime/virtcontainers/clh.go
- src/runtime/virtcontainers/clh_test.go
This round iocludes fixes for the following issues:
* #4196
* #4188
> stable-2.4 | Second round of backports for the 2.4.1 release

- versions.yaml
> stable-2.4 | versions: Upgrade to Cloud Hypervisor v23.1

- docs/how-to/ccv0.sh
Change all the tests repo interactions to be done as sudo
Fixes: #4241
> doc: Allow ccv0 to run as non-root user

- docs/how-to/ccv0.sh
Refactoring ccv0.sh to use integration/confidential/lib.sh
Fixes: #4132
Depends-on: https://github.com/kata-containers/tests/pull/4729
Signed-off-by: Georgina Kinge <georgina.kinge@ibm.com>
Co-authored-by: Megan Wright <Megan.Wright@ibm.com>
> CCv0: Refactored ccv0.sh to use new shared library

- src/runtime/virtcontainers/acrn.go
- src/runtime/virtcontainers/agent.go
- src/runtime/virtcontainers/clh.go
- src/runtime/virtcontainers/container.go
- src/runtime/virtcontainers/kata_agent.go
- src/runtime/virtcontainers/kata_agent_test.go
- src/runtime/virtcontainers/mock_agent.go
- src/runtime/virtcontainers/qemu.go
- src/runtime/virtcontainers/sandbox.go
Fallout of 09f7962ff
Signed-off-by: Rafael Fonseca <r4f4rfs@gmail.com>
> runtime: remove duplicate 'types' import

- src/agent/Cargo.toml
- src/agent/rustjail/src/container.rs
- src/tools/runk/Makefile
- src/tools/runk/README.md
- src/tools/runk/src/main.rs
> runk: merge oci-kata-agent into runk 

- docs/how-to/containerd-kata.md
Containerd usage docs with Kata need to be update for Kata 2.x.i
Fixes #3870
> Update containerd docs

- src/agent/src/config.rs
- src/agent/src/rpc.rs
- src/agent/src/sandbox.rs
- src/agent/src/test_utils.rs
Backport signal handling fix, as well as agent test improvements.
> stable-2.4: backport agent fixes

- src/agent/rustjail/src/process.rs
The `kata-agent` passes its standard I/O file descriptors
through to the container process that will be launched
by `runk` without manipulation or modification in order to
allow the container process can handle its I/O operations.
Fixes: #4327
> agent: Pass standard I/O to container launched by runk

- src/tools/runk/libcontainer/src/builder.rs
runk always launches containers with detached mode,
so users have to use a console socket with `run` and
`create` operations when a terminal is used.
If users set `terminal` to `true` in `config.json` and
try to launch a container without specifying a console
socket, runk returns an error with a message early.
Fixes: #4324
> runk: Return error when tty is used without console socket

- src/runtime-rs/crates/hypervisor/src/device/vfio.rs
- src/runtime-rs/crates/resource/src/network/endpoint/physical_endpoint.rs
- src/runtime-rs/crates/resource/src/network/network_model/route_model.rs
- src/runtime-rs/crates/resource/src/network/utils/netns.rs
- src/runtime-rs/crates/resource/src/share_fs/utils.rs
- src/runtime-rs/crates/resource/src/volume/mod.rs
- versions.yaml
> for rust context with_context is better, because it is evaluated lazily. 

- .github/workflows/kata-deploy-test.yaml
- docs/Release-Process.md
Backport-of: https://github.com/kata-containers/kata-containers/pull/4350
> backport-2.4 | workflows: add workflow_dispatch triggering to test-kata-deploy

- docs/use-cases/NVIDIA-GPU-passthrough-and-Kata.md
Now that #4213 is merged we need updated documentation for vGPU time-sliced or vGPU MIG-backed.
Fixes: #4343
> docs: Update vGPU use-case

- .github/workflows/add-pr-sizing-label.yaml
- .github/workflows/snap-release.yaml
> workflow: Removing man-db, workflow kept failing

- tools/packaging/kernel/README.md
- tools/packaging/scripts/apply_patches.sh
- versions.yaml
This brings in a few security fixes.
Fixes #4438
> versions: Update kernel to latest LTS version 5.15.48

- docs/how-to/ccv0.sh
Refactored ccv0.sh to utilise new automated tests for pulling encrypted images and creating a pod.
Fixes: #4512
Depends-on: github.com/kata-containers/tests#4866
Signed-off-by: Georgina Kinge <georgina.kinge@ibm.com>
Co-authored-by: Megan Wright <Megan.Wright@ibm.com>
> CCv0: Refactor ccv0.sh to use bats test

- docs/how-to/ccv0.sh
- docs/how-to/how-to-build-and-test-ccv0.md
Refactored ccv0.sh to remove rootfs code now in lib.sh
Fixes: #4512
Co-authored-by: Megan Wright Megan.Wright@ibm.com
Signed-off-by: Georgina Kinge <georgina.kinge@ibm.com>
> CCv0: Refactor ccv0.sh to remove duplicate code

- src/agent/src/rpc.rs
Get handled signal include SigBlk, SigIgn and SigCgt.
Fixes: #4478
Signed-off-by: quanweiZhou <quanweiZhou@linux.alibaba.com>
> agent: enhance get handled signal

- src/runtime-rs/crates/resource/src/network/endpoint/endpoints_test.rs
- src/runtime-rs/crates/resource/src/network/endpoint/ipvlan_endpoint.rs
- src/runtime-rs/crates/resource/src/network/endpoint/mod.rs
- src/runtime-rs/crates/resource/src/network/network_model/mod.rs
- src/runtime-rs/crates/resource/src/network/network_pair.rs
- src/runtime-rs/crates/resource/src/network/network_with_netns.rs
- src/runtime/virtcontainers/ipvlan_endpoint.go
Add support for ipvlan endpoint
Fixes: #4655
> runtime-rs: support functionalities of ipvlan endpoint

- docs/install/README.md
- docs/install/kata-containers-3.0-rust-runtime-installation-guide.md
add installation guide for kata 3.0
Fixes:#4661
> docs: add installation guide for kata 3.0

- src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container_inner.rs
fix ctr exit failed.
Fixes: #4683
> runtime-rs: fix ctr exit failed

- docs/how-to/data/kata-monitor-daemonset.yml
fix can't monitor /run/vc/sbs.
Fixes: #4685
> kata-monitor: fix can't monitor /run/vc/sbs

- src/runtime-rs/crates/resource/src/manager.rs
- src/runtime-rs/crates/resource/src/manager_inner.rs
- src/runtime-rs/crates/runtimes/common/src/runtime_handler.rs
- src/runtime-rs/crates/runtimes/common/src/sandbox.rs
- src/runtime-rs/crates/runtimes/linux_container/src/lib.rs
- src/runtime-rs/crates/runtimes/src/manager.rs
- src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs
- src/runtime-rs/crates/runtimes/virt_container/src/lib.rs
- src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
- src/runtime-rs/crates/runtimes/wasm_container/src/lib.rs
runtime-rs: support disable_guest_seccomp
support disable_guest_seccomp
Fixes: #4691
> support disable_guest_seccomp

- src/agent/rustjail/src/mount.rs
- src/agent/src/main.rs
- src/agent/src/netlink.rs
check the result to let it return early if there are some errors
Fixes: #4708
> rustjail: check result to let it return early

- docs/install/kata-containers-3.0-rust-runtime-installation-guide.md
add more details for rust set up in kata 3.0 install guide
Fixes: #4720
> Docs: add rust environment setup for kata 3.0

- src/libs/README.md
Fixes: https://github.com/kata-containers/kata-containers/issues/4725
> Docs: fix tables format error

- src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs
Set the share sandbox pid namepsace from spec
Fixes:#4680
> runtime-rs: fix set share sandbox pid namespace

- tools/packaging/static-build/ovmf/Dockerfile
- tools/packaging/static-build/ovmf/build-ovmf.sh
- tools/packaging/static-build/ovmf/build.sh
- versions.yaml
Fixes: #4169
Signed-off-by: Alex Carter <alex.carter@ibm.com>
Introduces a build script for AmdSev build of OVMF, which will be needed for SEV measured direct boot.
> Add support AmdSev build of OVMF

- src/runtime-rs/crates/resource/src/cgroups/mod.rs
- src/runtime-rs/crates/runtimes/virt_container/src/container_manager/io/shim_io.rs
- src/runtime-rs/crates/runtimes/virt_container/src/container_manager/process.rs
- src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
Fix the stop failed in azure.
Fixes: #4740
> runtime-rs: fix stop failed in azure

- src/agent/rustjail/src/mount.rs
- src/agent/src/main.rs
- src/libs/kata-sys-util/src/mount.rs
- src/libs/logging/src/lib.rs
- src/runtime-rs/crates/shim/src/logger.rs
- src/tools/agent-ctl/src/main.rs
- src/tools/agent-ctl/src/utils.rs
- src/tools/runk/src/commands/delete.rs
- src/tools/runk/src/commands/list.rs
- tools/packaging/static-build/td-shim/Dockerfile
- tools/packaging/static-build/td-shim/build-td-shim.sh
- tools/packaging/static-build/td-shim/build.sh
- versions.yaml
To keep runtime-rs up to date, we will merge main into runtime-rs every
week.
Fixes: #4790
> runtime-rs: merge main to runtime-rs

- src/runtime-rs/Cargo.lock
Update Cargo.lock
Fixes: #4875
> runtime-rs: update Cargo.lock

- src/tools/runk/libcontainer/src/container.rs
- src/tools/runk/src/commands/delete.rs
Move delete logic to `libcontainer` crate to make the code clean
like other commands.
Fixes: #4975
> runk: Move delete logic to libcontainer

- src/dragonball/src/config_manager.rs
This pull request introduces more unit tests for Dragonball.
Since `runtime-rs` has been merged into the `main` branch, so reopen this pr.  The previous pr #4604.
> Built-in Sandbox: add more unit tests for dragonball.

- docs/Developer-Guide.md
This PR updates the url for containerd in the Developer Guide.
Fixes #5075
> docs: Update url in the Developer Guide

- src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs
amend_spec do two works:
- modify the spec
- check if the pid namespace is enabled
This make it confusable. So split it into two functions.
Fixes: #5062
> runtime-rs: split amend_spec function

- docs/design/architecture_3.0/README.md
Update the status and plan for the Rust runtime developement
Fixes: #4884
> runtime-rs: update rust runtime roadmap

- src/dragonball/src/device_manager/console_manager.rs
- src/dragonball/src/device_manager/mod.rs
Fixes: #5083
Signed-off-by: qiliangfan <fanqiliang@mail.nankai.edu.cn>
> dragonball: Fix problem that stdio console cannot connect to stdout

- src/dragonball/Cargo.toml
- src/dragonball/Makefile
- src/dragonball/src/address_space_manager.rs
- src/dragonball/src/device_manager/mod.rs
- src/runtime-rs/Cargo.lock
- src/runtime-rs/Cargo.toml
- src/runtime-rs/crates/hypervisor/Cargo.toml
Updated vmm-sys-util to 0.10.0
Updated virtio-queue to 0.4.0
Updated vm-memory to 0.9.0
Fixes: #5194
> Build-in Sandbox: update dragonball-sandbox dependencies

- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
- Remove skopeo and umoci from the CC image
Fixes: #4889
> packaging: Remove skopeo & umoci

- src/runtime-rs/crates/resource/src/volume/share_fs_volume.rs
In src/runtime-rs/crates/resource/src/volume/share_fs_volume.rs, there are two ways used to check if a file is a regular file:
- one is using `stat` and its' mode
- one is using [`Path`'s `is_file()`](https://doc.rust-lang.org/std/path/struct.PathBuf.html#method.is_file)
The `Path`'s `is_file()` is enough to check if a file is a regular file.
> runtime-rs: use Path.is_file to check regular files

- src/runtime-rs/Makefile
- src/runtime-rs/crates/runtimes/common/src/types/mod.rs
- src/runtime-rs/crates/runtimes/common/src/types/trans_from_shim.rs
- src/runtime-rs/crates/runtimes/src/manager.rs
- tools/packaging/kata-deploy/README.md
- tools/packaging/kata-deploy/action/test-kata.sh
- tools/packaging/kata-deploy/examples/nginx-deployment-dragonball.yaml
- tools/packaging/kata-deploy/examples/test-deploy-kata-dragonball.yaml
- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
- tools/packaging/kata-deploy/runtimeclasses/kata-runtimeClasses.yaml
- tools/packaging/kata-deploy/scripts/kata-deploy.sh
- tools/packaging/static-build/shim-v2/Dockerfile
- tools/packaging/static-build/shim-v2/build.sh
- tools/packaging/static-build/shim-v2/install_go_rust.sh
support kata-deploy for runtime-rs
Fixes:#5000
> kata-deploy: ship the rustified runtime binary

- src/agent/src/watcher.rs
- src/libs/Cargo.lock
- src/libs/kata-types/Cargo.toml
- src/libs/kata-types/src/k8s.rs
- src/runtime-rs/Cargo.lock
- src/runtime-rs/crates/resource/src/share_fs/mod.rs
- src/runtime-rs/crates/resource/src/share_fs/utils.rs
- src/runtime-rs/crates/resource/src/share_fs/virtio_fs_share_mount.rs
- src/runtime-rs/crates/resource/src/volume/share_fs_volume.rs
Use watchable mount to support inotify for virtio-fs.
Fixes: #5184 
> runtime-rs: support watchable mount

- src/tools/runk/README.md
This PR updates the urls that we have in the runk documentation.
Fixes #5259
> docs: Update urls in runk documentation

- src/runtime-rs/Makefile
- src/runtime-rs/crates/runtimes/common/src/types/mod.rs
- src/runtime-rs/crates/runtimes/common/src/types/trans_from_shim.rs
- src/runtime-rs/crates/runtimes/src/manager.rs
- tools/packaging/kata-deploy/README.md
- tools/packaging/kata-deploy/action/test-kata.sh
- tools/packaging/kata-deploy/examples/nginx-deployment-dragonball.yaml
- tools/packaging/kata-deploy/examples/test-deploy-kata-dragonball.yaml
- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
- tools/packaging/kata-deploy/runtimeclasses/kata-runtimeClasses.yaml
- tools/packaging/kata-deploy/scripts/kata-deploy.sh
- tools/packaging/static-build/shim-v2/Dockerfile
- tools/packaging/static-build/shim-v2/build.sh
- tools/packaging/static-build/shim-v2/install_go_rust.sh
support runtime-rs for kata deploy
Fixes:#5264
> kata-deploy: support runtime-rs for kata deploy

- src/runtime-rs/crates/resource/src/share_fs/utils.rs
add comments for runtime-rs shared directory
Fixes:#5197
> runtime-rs: add comments for runtime-rs shared directory

- src/agent/src/mount.rs
The kata agent adds a reference for each storage object before mount and skip mount again if the storage object is known. We need to remove the object reference if mount fails.
Fixes: #5364
> agent: reduce reference count for failed mount

- src/libs/kata-types/src/config/hypervisor/mod.rs
With default_maxvcpus = 0 and default_vcpus = 1 settings, the
default_vcpus will be set to 0 and leads to starting failure.
The default_maxvcpus is not set correctly when it is set to 0,
and the default_vcpus will be set to 0.
The correct action is setting default_maxvcpus to the max number
of CPUs or MAX_DRAGONBALL_VCPUS, and the default_vcpus should be
set to the desired value if the valuse is between 0 and
default_maxvcpus.
Fixes: #5110
> libs/kata-types: adjust default_vcpus correctly

- .github/workflows/static-checks.yaml
- Makefile
- src/dragonball/Cargo.toml
- src/dragonball/Makefile
- src/dragonball/src/address_space_manager.rs
- src/dragonball/src/api/v1/boot_source.rs
- src/dragonball/src/api/v1/instance_info.rs
- src/dragonball/src/api/v1/machine_config.rs
- src/dragonball/src/api/v1/vmm_action.rs
- src/dragonball/src/config_manager.rs
- src/dragonball/src/device_manager/blk_dev_mgr.rs
- src/dragonball/src/device_manager/fs_dev_mgr.rs
- src/dragonball/src/device_manager/mod.rs
- src/dragonball/src/device_manager/virtio_net_dev_mgr.rs
- src/dragonball/src/device_manager/vsock_dev_mgr.rs
- src/dragonball/src/kvm_context.rs
- src/dragonball/src/resource_manager.rs
- src/dragonball/src/vcpu/vcpu_impl.rs
- src/dragonball/src/vm/mod.rs
- src/dragonball/src/vmm.rs
Added more unit test for vmm actions.
Added dragonball components to Makefile.
Fixed clippy warning.
> Built-in Sandbox: add more unit tests for dragonball

- src/agent/src/image_rpc.rs
Without this, a failure in `init_attestion_agent` would lead to a panic.
Fixes #5406
Signed-off-by: Wedson Almeida Filho <walmeida@microsoft.com>
> image_rpc: Make `init_attestation_agent` fail gracefully

- src/agent/src/image_rpc.rs
Prior to this patch, we were missing a call to `verify_cid` when the cid was derived from the image path, which meant that the host could specify something like "prefix/..", and we would use ".." as the cid. Paths derived from this (e.g., `bundle_path`) would not be at the intended tree.
This patch factors the code out of `pull_image` so that it can be more easily tested. Tests are added for a number of cases.
Fixes #5421
Signed-off-by: Wedson Almeida Filho <walmeida@microsoft.com>
> image_rpc: always call `verify_cid` after determining the cid

- src/agent/rustjail/src/cgroups/fs/mod.rs
before setting a limit, otherwise paths may not be found. guest supporting different hugepage size is more likely with peer-pods where podvm may use different flavor.
Forward-port-from: https://github.com/kata-containers/kata-containers/pull/5192
Fixes: #5191
> agent: validate hugepage size is supported

- src/agent/rustjail/src/cgroups/fs/mod.rs
before setting a limit, otherwise paths may not be found. guest supporting different hugepage size is more likely with peer-pods where podvm may use different flavor.
(sent only against CCv0 however, it may make sense to port also to main)
Fixes: #5191
> CCv0: agent: validate hugepage size is supported

- tools/packaging/static-build/cloud-hypervisor/build-static-clh.sh
This Pr removes single spaces and fix the indentation of the script.
Fixes #5528
> tools: Fix indentation of build static clh script

- src/agent/src/config.rs
I think this is all we need to allow the cmdline to overwrite the agent config. This means we can update config parameters without having to rebuilt the rootfs. Does not change trust model since the command line is measured.
@stevenhorsman  @sameo  @arronwy
Fixes: #5173
Signed-off-by: Tobin Feldman-Fitzthum <tobin@ibm.com>
> CC | Agent: Allow agent config to be overwritten

- src/agent/src/config.rs
- src/agent/src/image_rpc.rs
- src/runtime/Makefile
Add `enable_signature_verification` config support
> Sig ver param

- src/runtime-rs/crates/resource/src/share_fs/share_virtio_fs_standalone.rs
The 'config' argument to ShareVirtioFsStandalone::new() is now actually used, taking care of an explicit TODO.
If a shared path doesn't exist in ShareVirtioFsStandalone::virtiofsd_args() it is now created instead of returning an error, thus following ShareVirtioFsInline's suit.
The '-o vhost_user_socket=...' command line argument doesn't seem to be supported by newer versions of virtiofsd so we replace it with '--socket-path' which should be functionally equivalent according to docs.
Fixes #5572
Signed-off-by: Pavel Mores <pmores@redhat.com>
> runtime-rs: blanks filled & fixes made to virtiofsd launch

- src/dragonball/src/device_manager/mod.rs
- src/dragonball/src/lib.rs
- src/dragonball/src/test_utils.rs
- src/dragonball/src/vm/mod.rs
Added more unit tests for device manager.
Fixes: #4899 
> Built-in Sandbox: add more unit tests for dragonball. Part 3

- src/runtime-rs/crates/agent/src/kata/agent.rs
- src/runtime-rs/crates/agent/src/kata/trans.rs
- src/runtime-rs/crates/agent/src/lib.rs
- src/runtime-rs/crates/agent/src/types.rs
- src/runtime-rs/crates/runtimes/common/src/sandbox.rs
- src/runtime-rs/crates/runtimes/src/shim_mgmt/client.rs
- src/runtime-rs/crates/runtimes/src/shim_mgmt/handlers.rs
- src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
Support kata-ctl iptables series of commands in runtime.
Fixes: #5370
> feat(shim-mgmt): iptables handler

- tools/packaging/static-build/virtiofsd/build-static-virtiofsd.sh
This Pr removes single spaces and fix the indentation of the script.
Fixes #5630
> tools: Fix indentation of build static virtiofsd script

- src/runtime/virtcontainers/nydusd.go
- src/runtime/virtcontainers/nydusd_test.go
- versions.yaml
> versions: update nydusd version

- .github/workflows/kata-deploy-push.yaml
- .github/workflows/kata-deploy-test.yaml
- .github/workflows/release.yaml
- tools/packaging/kata-deploy/local-build/Makefile
- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
- tools/packaging/static-build/nydus/build.sh
Install nydus related binaries under /opt/kata/libexec/
Fixes: #5726
> package: add nydus to release artifacts

- src/runtime-rs/crates/runtimes/src/manager.rs
- src/runtime-rs/crates/runtimes/virt_container/src/lib.rs
- src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
- src/runtime-rs/crates/runtimes/virt_container/src/sandbox_persist.rs
code refactoring, add conditional compile for virt-sandbox persist
Fixes: #5706
> Refactor(runtime-rs): add conditional compile for virt-sandbox persist

- tools/packaging/static-build/cache_components.sh
This PR improves the cached artifacts for qemu components.
Fixes #5670
> tools: Improve cached artifacts for qemu

- tools/packaging/static-build/initramfs/Dockerfile
- tools/packaging/static-build/shim-v2/build.sh
This is to fix errors on building cc-builders images on s390x. Please check out the details in the issue below.
Fixes: #5677
> CC: Fix errors on building cc-builders on s390x

- tools/packaging/static-build/cache_components.sh
- tools/packaging/static-build/kernel/build.sh
This PR enables the use for the cached kernel.
Fixes #5355
> CCv0: Use cached kernel

- src/agent/src/rpc.rs
agent: Update the merge_oci_process to properly manage the env variables
Loop through the images enviroment variables, checking if it exists inside the target. If it does then do not append it. Add unit tests for correctly merging the env variables of the pod yaml and image itself in the container and image process
Signed-off-by: Jordan Jackson <jordan.jackson@ibm.com>
> CC | agent: Update the merge_oci_process to properly manage the env variables

- .github/workflows/darwin-tests.yaml
- .github/workflows/docs-url-alive-check.yaml
- .github/workflows/static-checks.yaml
- versions.yaml
This Go release fixes golang/go#56309
Fixes #5773
> build: update golang version to 1.19.3

- src/agent/src/rpc.rs
agent: Update the merge_oci_process function to change cwd
Change the if statement to check if the CWD is set to / Add unit tests for the correct merging of working directory in the container and image process
Note: there is an outstanding question about one test case
Fixes: #5721
Co-authored-by: stevenhorsman <steven@uk.ibm.com>
Signed-off-by: jordan9500 <jordan.jackson@ibm.com>
> CC | agent: Update the merge_oci_process function to change cwd

- tools/packaging/kata-deploy/local-build/Makefile
- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
- tools/packaging/static-build/cache_components.sh
Let's simplify the Cloud Hypervisor cached logic, see each commit for more details.
Fixes: #5816
> CC | packaging: Fix the cloud hypervisor cached logic

- src/agent/src/rpc.rs
- src/runtime-rs/crates/runtimes/src/manager.rs
- src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs
- src/runtime-rs/crates/runtimes/virt_container/src/container_manager/manager.rs
- src/runtime-rs/crates/service/src/manager.rs
- src/runtime-rs/crates/service/src/task_service.rs
Fix some not correct variable name and typos.
Fixes: #5820
> runtime-rs: fix some variable names and typos

- src/agent/Cargo.lock
- src/agent/Cargo.toml
Fixes: #5843
Signed-off-by: James Tumber <james.tumber@ibm.com>
> agent: remove `sysinfo` dependency

- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
- tools/packaging/static-build/cache_components.sh
- tools/packaging/static-build/shim-v2/build.sh
As done for different components, let's cache and use the rootfs whenever it's possible.
> CC | Cache and use rootfs whenever it's possible

- src/tools/kata-ctl/Cargo.lock
- src/tools/kata-ctl/Cargo.toml
- src/tools/kata-ctl/src/arch/mod.rs
- src/tools/kata-ctl/src/arch/x86_64/mod.rs
- src/tools/kata-ctl/src/args.rs
- src/tools/kata-ctl/src/check.rs
- src/tools/kata-ctl/src/main.rs
- src/tools/kata-ctl/src/ops/check_ops.rs
- src/tools/kata-ctl/src/types.rs
Implement the kata-runtime check --list command with unit tests
Fixes #5344
Signed-off-by: David Esparza <david.esparza.borquez@intel.com>
> kata-ctl: Add --list option

- src/runtime/pkg/containerd-shim-v2/service.go
update outdated code comments
Fixes: #3234
> shim: return hypervisor's pid not shim's pid

- .gitignore
- tools/osbuilder/.gitignore
- tools/packaging/.gitignore
Add some new ignore items to avoid local builds that cause git to track a lot of files
Fixes: #5900
> tools: Add some new gitignore items

- docs/use-cases/using-SPDK-vhostuser-and-kata.md
Fixes: https://github.com/kata-containers/kata-containers/issues/5926
Signed-off-by: Xin Yang <xinydev@gmail.com>
> docs: Remove duplicate sentences

- versions.yaml
Add space before start of comment
Fixes: #5928
> version: Fix formatting

- src/dragonball/src/vm/mod.rs
- src/dragonball/src/vmm.rs
- src/runtime-rs/Cargo.lock
- src/runtime-rs/crates/hypervisor/Cargo.toml
add dbs-upcall feature to dragonball
Fixes:#5949
> runtime-rs: add dbs-upcall feature

- src/dragonball/src/kvm_context.rs
- src/dragonball/src/vcpu/vcpu_impl.rs
- src/dragonball/src/vcpu/vcpu_manager.rs
Added more unit tests for Vcpu Manager.
Fixes: #4899 
> Built-in Sandbox: add more unit tests for dragonball. Part 4

- src/runtime/virtcontainers/hypervisor.go
- src/runtime/virtcontainers/hypervisor_darwin.go
- src/runtime/virtcontainers/hypervisor_linux.go
Fixes: #5995
Placeholder skeleton at this point - implementation will be added after basic build refactoring lands.
> virtcontainers: Introduce hypervisor_darwin

- src/runtime/virtcontainers/virtframework.go
Fixes: #6004
A Virtualization.framework based Hypervisor implementation. This is just stubs for now to eventually get this building.
> virtcontainers: Add a Virtualization.framework skeleton

- tools/packaging/kata-deploy/action/setup-aks.sh
This PR fixes the indentation for setup aks script being used in tools.
Fixes #6013
> tools: Fix indentation for setup aks script

- docs/Developer-Guide.md
> docs: add hint of probing loop module

- src/runtime/pkg/resourcecontrol/cgroups_darwin.go
- src/runtime/pkg/resourcecontrol/controller.go
- src/runtime/pkg/resourcecontrol/utils.go
- src/runtime/pkg/resourcecontrol/utils_linux.go
- src/runtime/virtcontainers/network_darwin.go
Add initial stubs for darwin specific handling for network and resource control.
> Add darwin skeletons

- src/runtime/pkg/oci/utils.go
Fixes: #6073
Signed-off-by: zhaojizhuang <571130360@qq.com>
> runtime: paas enablevhostuserstore annotation to hypervisor config

- versions.yaml
This PR updates the conmon version that we are using in our versions.yaml
Fixes #6084
> versions: Update conmon version

- src/tools/kata-ctl/Cargo.lock
- src/tools/kata-ctl/src/arch/aarch64/mod.rs
- src/tools/kata-ctl/src/arch/powerpc64le/mod.rs
- src/tools/kata-ctl/src/arch/s390x/mod.rs
- src/tools/kata-ctl/src/arch/x86_64/mod.rs
- src/tools/kata-ctl/src/check.rs
- src/tools/kata-ctl/src/utils.rs
Add functions to get distro and cpu details
> Utility functions for kata-env

- src/agent/src/metrics.rs
DEFAULT_REGISTRY pre-registers many metrics that we don't need or have duplicated. This PR uses a custom register for metrics without interference and ensures that the registration process is executed only once when the program is running.
Fixes: #5255
> agent: Eliminate unnecessary metrics

- src/agent/src/image_rpc.rs
- Add agent log if pull image fails
> agent: Improve logging of pull image

- docs/how-to/how-to-build-and-test-ccv0.md
- src/agent/src/config.rs
- src/agent/src/image_rpc.rs
- tools/osbuilder/rootfs-builder/README.md
- tools/osbuilder/rootfs-builder/rootfs.sh
- tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in
- tools/osbuilder/rootfs-builder/ubuntu/config.sh
- tools/osbuilder/scripts/lib.sh
- tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
- tools/packaging/static-build/cache_components.sh
- versions.yaml
- Remove skopeo and umoci code from the agent
- Remove associated agent configuration
- Remove the options to install the skopeo and umoci binaries into the rootfs
> CC: Remove skopeo umoci

- src/dragonball/README.md
- src/dragonball/docs/images/upcall-architecture.svg
- src/dragonball/docs/upcall.md
In order for users to get better understand of upcall feature, we add this document for upcall to illustrate what is upcall and how to enable upcall.
fixes: #6054
> upcall: add document for upcall

- src/runtime/config/configuration-qemu.toml.in
- src/runtime/pkg/govmm/qemu/qemu.go
- src/runtime/virtcontainers/hypervisor.go
- src/runtime/virtcontainers/qemu.go
Fixes: #6092
Signed-off-by: zhaojizhuang <571130360@qq.com>
> runtime: Add hmp for qemu

- src/dragonball/src/address_space_manager.rs
- src/dragonball/src/api/v1/vmm_action.rs
- src/dragonball/src/device_manager/mod.rs
- src/dragonball/src/vm/mod.rs
- src/dragonball/src/vmm.rs
Added more unit tests for vm module.
Fixes: #4899
> Built-in Sandbox: add more unit tests for dragonball. Part 5

- src/runtime/virtcontainers/pkg/annotations/annotations.go
Fixes: #6150
Signed-off-by: yahaa <1477765176@qq.com>
> Typo: change tabs in comment to spaces

- src/agent/rustjail/src/cgroups/fs/mod.rs
- src/runtime/pkg/containerd-shim-v2/metrics.go
- src/runtime/pkg/containerd-shim-v2/metrics_test.go
- src/runtime/pkg/resourcecontrol/utils.go
- src/runtime/pkg/resourcecontrol/utils_linux.go
Support to use cgroup v2 metrics marshal guest metrics.
Fixes: #5998
Signed-off-by: yaoyinnan <yaoyinnan@foxmail.com>
> runtime: support cgroup v2 metrics marshal guest metrics

- src/tools/kata-ctl/src/check.rs
Change unit tests for CPU check to table-driven tests and expand test cases including temp files for cpuinfo.
Fixes #5919
> kata-ctl: Expand unit tests for CPU check

- src/agent/Cargo.lock
- src/agent/Cargo.toml
- src/agent/src/rpc.rs
- src/libs/kata-types/src/config/hypervisor/mod.rs
- src/runtime/pkg/containerd-shim-v2/wait.go
- src/runtime/virtcontainers/clh.go
- src/runtime/virtcontainers/qemu_amd64.go
- src/runtime/virtcontainers/qemu_amd64_test.go
- tools/packaging/static-build/virtiofsd/build-static-virtiofsd.sh
This PR adds backports for the stable 3.0 branch
> stable-3.0: Stable 3.0 backports

- src/dragonball/Cargo.lock
- src/dragonball/Cargo.toml
- src/dragonball/src/api/v1/vmm_action.rs
- src/runtime-rs/Cargo.lock
- src/runtime-rs/crates/agent/src/sock/hybrid_vsock.rs
- src/runtime-rs/crates/agent/src/sock/vsock.rs
- src/runtime-rs/crates/hypervisor/Cargo.toml
- src/runtime-rs/crates/hypervisor/src/ch/inner.rs
- src/runtime-rs/crates/hypervisor/src/ch/mod.rs
- src/runtime-rs/crates/hypervisor/src/dragonball/inner.rs
- src/runtime-rs/crates/hypervisor/src/dragonball/vmm_instance.rs
- src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
- src/runtime-rs/crates/runtimes/common/src/message.rs
> Remove all remaining unsafe impl

- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
- tools/packaging/static-build/cache_components.sh
Cache initrd and kernel in one job and reuse whenever possible.
Fixes: #6176
Signed-off-by: Unmesh Deodhar <udeodhar@amd.com>
> Adding caching capability for SEV kernel and initrd

- src/libs/kata-types/src/config/runtime.rs
- src/runtime-rs/config/configuration-dragonball.toml.in
- src/runtime-rs/crates/runtimes/src/manager.rs
* add doc in the configuration
* make entry consistent with 2.0
Fixes: #6313
> feat(runtime): make static resource management consistent with 2.0

- src/agent/Cargo.lock
- src/agent/Cargo.toml
- versions.yaml
- attestation-agent: c6cdff6dcd4f4ca45fa0fb7df439057d2dba15ea
- image-rs: ~48bb221d8e76cb35549f2ffa626d2f687f959bd2~ 948db858579be538724266a650e840e75e7e824d
- td-shim: latest HEAD (5fa81efa1e43c8005d6d8099b5c099125c17b4b0)
Fixes: #6366
> CCv0: update deps for 0.4.0

- src/agent/src/rpc.rs
This patch fixes the issue that do_copy_file changes the directory permission of the parent directory of a target file, even when the parent directory already exists.
Fixes #6367
> agent: don't set permission of existing directory in copy_file

- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Fixing initrd build by providing correct suffix.
Fixes: #6388
> packaging: fix initrd build

- src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs
Currently, we only create the new exec process in runtime, this will cause error when the following requests needing to be handled:
- Task: exec process
- Task: resize process pty
- ...
The agent do not do_exec_process when we handle ExecProcess, thus we can not find any process information in the guest when we handle ResizeProcessPty. This will report an error.
In this commit, the handling process is modified to the:
* Modify process tty_win information in runtime
* If the exec process is not running, we just return. And the truly pty_resize will happen when start_process
Fixes: #6248
> bugfix: modify tty_win info in runtime when handling ResizePtyRequest

- src/dragonball/src/device_manager/blk_dev_mgr.rs
Added more unit tests for virtio-blk device.
Fixes: #4899
> Built-in Sandbox: add more unit tests for dragonball. Part 6

- tools/packaging/static-build/cache_components.sh
Check if tarball exists. If yes, skip the tarball create command.
Fixes: #6473
> packaging: fix sev kernel caching

- .github/workflows/payload-after-push-amd64.yaml
- .github/workflows/payload-after-push-arm64.yaml
- .github/workflows/payload-after-push-s390x.yaml
- tools/packaging/kata-deploy/scripts/kata-deploy.sh
While trying to use kata-deploy on openshift-ci (#6492) I noticed some problems that I hope are fixed by the commits on this PR.
> A couple of kata-deploy fixes

- .github/workflows/static-checks.yaml
- tools/osbuilder/tests/test_images.sh
Cherry-pick of:
- #6406 
so that we can get the same fix for out-of-space errors in the CI.
Depends on:
- kata-containers/tests#5532
> CC | static checks workflow improvements

- tools/packaging/kata-deploy-cc/scripts/kata-deploy.sh
Add support for cri-o into kata-deploy and merge in CAA features
Fixes: #6351
> kata-deploy: Add cri-o support

- .github/workflows/kata-deploy-push.yaml
- .github/workflows/kata-deploy-test.yaml
- .github/workflows/release.yaml
- src/agent/rustjail/src/cgroups/fs/mod.rs
- src/agent/rustjail/src/cgroups/mock.rs
- src/agent/rustjail/src/cgroups/mod.rs
- src/agent/rustjail/src/cgroups/systemd/manager.rs
- src/agent/rustjail/src/container.rs
- src/agent/src/main.rs
- src/agent/src/rpc.rs
- src/runtime-rs/arch/powerpc64le-options.mk
- src/runtime/virtcontainers/mount.go
- src/runtime/virtcontainers/mount_linux_test.go
- src/runtime/virtcontainers/mount_test.go
- tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in
- tools/osbuilder/rootfs-builder/ubuntu/rootfs_lib.sh
- tools/packaging/static-build/firecracker/build-static-firecracker.sh
- tools/packaging/static-build/shim-v2/install_go_rust.sh
These are the backports for the upcoming 3.1 release.
> Backports for 3.1

- src/runtime/virtcontainers/nydusd.go
- src/runtime/virtcontainers/nydusd_test.go
- versions.yaml
upgrad nydus version to v2.2.0 thus it can pass the test on arm64
> nydus: upgrad to v2.2.0

- src/agent/src/image_rpc.rs
If cid is empty, we will use image name as default cid, and `image-rs` will use `cid` as bundle directory name for each container, to support multiple containers with same image, we need append unique id to the image name.
Fixes: #6456
> image_rpc: Add container_count for containers without cid

- .github/workflows/cc-payload-after-push-s390x.yaml
- tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
This is a preliminary work to establish an e2e test for a new runtime class `kata-qemu-se` (IBM secure execution).
Fixes: #6544
> CC: Introduce secure image in payload image

- src/agent/Cargo.lock
- src/agent/Cargo.toml
- src/agent/src/image_rpc.rs
- tools/osbuilder/rootfs-builder/rootfs.sh
- tools/osbuilder/rootfs-builder/ubuntu/config.sh
- tools/osbuilder/rootfs-builder/ubuntu/rootfs_lib.sh
- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
- tools/packaging/static-build/cache_components.sh
- versions.yaml
Ignore this, this is an attempt to run CI on
- #6404
- #6520 
combined with the following tests pr:
- ~kata-containers/tests#5577~ kata-containers/tests#5579
> CC | agent: add support for ttrpc + dependency on test PR

- docs/install/kata-containers-3.0-rust-runtime-installation-guide.md
> docs: update the rust version from version.yaml

- src/runtime/pkg/containerd-shim-v2/shim_management.go
- src/runtime/pkg/kata-monitor/pprof.go
- src/runtime/pkg/utils/shimclient/shim_management_client.go
> backport: Don't create socket file in /run/kata to 3.1

- src/runtime/pkg/device/drivers/vfio.go
On some systems a GPU is in a IOMMU group with a PCI Bridge and PCI Host Bridge. Per default no PCI Bridge needs to be passed-through. When scanning the IOMMU group, ignore devices with a 0x60 class ID prefix.
Fixes: #6663
> gpu: Do not pass-through PCI (Host) Bridges

- src/runtime/Makefile
- src/runtime/config/configuration-qemu-gpu.toml.in
- tools/packaging/kata-deploy/runtimeclasses/kata-runtimeClasses.yaml
- tools/packaging/kata-deploy/scripts/kata-deploy.sh
With every kata release make sure we have a default configuration and runtime working with GPUs
Fixes: https://github.com/kata-containers/kata-containers/issues/6675
> gpu: Add GPU enabled confguration and runtime 

- .gitignore
- src/libs/kata-types/src/config/agent.rs
- src/libs/kata-types/src/config/default.rs
- src/libs/kata-types/src/config/mod.rs
- src/tools/kata-ctl/Cargo.lock
- src/tools/kata-ctl/Cargo.toml
- src/tools/kata-ctl/Makefile
- src/tools/kata-ctl/src/arch/aarch64/mod.rs
- src/tools/kata-ctl/src/arch/powerpc64le/mod.rs
- src/tools/kata-ctl/src/arch/s390x/mod.rs
- src/tools/kata-ctl/src/arch/x86_64/mod.rs
- src/tools/kata-ctl/src/args.rs
- src/tools/kata-ctl/src/check.rs
- src/tools/kata-ctl/src/main.rs
- src/tools/kata-ctl/src/ops.rs
- src/tools/kata-ctl/src/ops/check_ops.rs
- src/tools/kata-ctl/src/ops/env_ops.rs
- src/tools/kata-ctl/src/ops/version.rs.in
- src/tools/kata-ctl/src/utils.rs
Command implements functionality to get user environment settings.
Fixes: #5339
> Implement the "kata-ctl env" command

- .github/workflows/ci-on-push.yaml
- .github/workflows/run-k8s-tests-on-sev.yaml
- tests/integration/kubernetes/run_kubernetes_tests.sh
Adding the k8s tests for qemu-sev
Fixes: #6711
> gha: Also run k8s tests on qemu-sev

- .github/workflows/ci-on-push.yaml
- .github/workflows/run-k8s-tests-on-snp.yaml
- tests/integration/kubernetes/run_kubernetes_tests.sh
Adding the k8s tests for qemu-snp
Fixes: #6722
> gha: Also run k8s tests on qemu-snp

- src/runtime/virtcontainers/remote.go
Add configurable context timeout for StopVM similar to StartVM
Fixes: #6730
> CC | runtime: Add configurable context timeout for StopVM

- src/runtime/virtcontainers/persist/manager_test.go
Expanded tests on manager_test.go to cover more lines of code.
Fixes: #259
> virtcontainers/persist: Improved test coverage 65% to 87.5%

- src/runtime/pkg/signals/signals_test.go
Expanded tests on signals_test.go to cover more lines of code. 'go test' won't show 100% coverage (only 66.7%), because one test need to spawn a new process (since it is testing a function that calls os.Exit(1)).
Fixes: #256
> pkg/signals: Improved test coverage 60% to 100%

- src/libs/kata-types/src/annotations/mod.rs
- src/runtime-rs/crates/agent/src/types.rs
- src/runtime-rs/crates/hypervisor/src/ch/inner_device.rs
- src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
- src/runtime-rs/crates/resource/src/network/utils/address.rs
- src/runtime-rs/crates/resource/src/network/utils/mod.rs
- src/runtime-rs/crates/resource/src/rootfs/mod.rs
- src/runtime-rs/crates/runtimes/src/manager.rs
- src/runtime-rs/crates/runtimes/virt_container/src/container_manager/process.rs
- src/runtime-rs/crates/runtimes/virt_container/src/health_check.rs
- src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
- src/tools/agent-ctl/src/main.rs
- src/tools/kata-ctl/src/arch/x86_64/mod.rs
- src/tools/kata-ctl/src/ops/exec_ops.rs
- src/tools/kata-ctl/src/ops/volume_ops.rs
- src/tools/kata-ctl/src/utils.rs
- src/tools/runk/Cargo.lock
- src/tools/runk/libcontainer/src/cgroup.rs
- src/tools/runk/src/main.rs
- versions.yaml
> warning_fix: fix warnings when build with cargo-1.68.0

- src/dragonball/src/vm/x86_64.rs
Use linux_loader::configurator::linux::LinuxBootConfigurator::write_bootparams to simplify code.
> Dragonball: use LinuxBootConfigurator::write_bootparams

- src/runtime/virtcontainers/pkg/compatoci/utils.go
- src/runtime/virtcontainers/pkg/compatoci/utils_test.go
In this PR, I add some test to expand test coverage. Now the coverage of compatoci is 91.5%
Credit PR to Hackathon Team3
Fixes: #258
> virtcontainers/pkg/compatoci/: Improved coverage for  for Kata 2.0

- tools/packaging/kata-deploy/local-build/kata-deploy-build-and-upload-payload.sh
- Remove local introduced by bad copy-paste
Fixes: #6814
> deploy: fix shell script error

- src/runtime/Makefile
- tests/integration/kubernetes/k8s-cpu-ns.bats
- tests/integration/kubernetes/run_kubernetes_tests.sh
- tools/packaging/kata-deploy/scripts/kata-deploy.sh
Enable SNP tests. Skip the CPU constraints tests due to hotplug limitations.
> gha: Enable SEV-SNP tests on main

- tools/osbuilder/dockerfiles/QAT/Dockerfile
- tools/osbuilder/image-builder/Dockerfile
- tools/packaging/kata-deploy/Dockerfile
- tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
- tools/packaging/kata-deploy/local-build/kata-deploy-build-and-upload-payload.sh
- tools/packaging/kata-deploy/local-build/kata-deploy-copy-yq-installer.sh
- tools/packaging/kata-deploy/local-build/kata-deploy-merge-builds.sh
Cherry pick in ae24dc73c13124835bc9805b097a7c747d8d13e5 and 636539bf0cc6eafa8db40af3fb5f1608db219f8b to get the CC deployment working. Builds upon https://github.com/kata-containers/kata-containers/pull/6927
> Ccv0 cherry pick build script

- tools/packaging/kata-deploy/scripts/kata-deploy.sh
We're currently backing up and restoring all the possible shim files, but the default one ("containerd-shim-kata-v2").
Let's ensure this is also backed up and restored.
Fixes: #6957
> kata-deploy: Improve shim backup / restore

- tools/packaging/kata-deploy-cc/Dockerfile
- tools/packaging/kata-deploy-cc/scripts/kata-deploy.sh
Port over fixes from `kata-deploy` into `kata-deploy-cc`
- https://github.com/kata-containers/kata-containers/pull/6829
- https://github.com/kata-containers/kata-containers/pull/6913
- https://github.com/kata-containers/kata-containers/pull/6648
Fixes: #6955
> kata-deploy-cc: Port fixes

- src/agent/src/netlink.rs
When updating an interface, there's maybe an existed interface whose name would be the same with the updated required name, thus it would update failed with interface name existed error. Thus we should rename the existed interface with an temporary name and swap it with the previouse interface name last.
Fixes: #6842
> netlink: Fix the issue of update_interface

- tests/integration/kubernetes/runtimeclass_workloads/pod-empty-dir-fsgroup.yaml
- tests/integration/kubernetes/runtimeclass_workloads/pod-http-liveness.yaml
- tests/integration/kubernetes/runtimeclass_workloads/pod-tcp-liveness.yaml
> kubernetes: add agnhost command in pod yaml

- versions.yaml
td-shim:  9e9a045b08b04756ccbbd5c9477f34fe366f054c
attestation-agent: 1fc89c144089d6faa77f7e92b6733dbfbeadc070
> CCv0: update dependencies for CoCo release 0.6.0

- .github/workflows/run-k8s-tests-on-aks.yaml
- tests/integration/gha-run.sh
Fixes: https://github.com/kata-containers/kata-containers/issues/7047
> gha: Fix gha-run.sh and unbreak CI

- docs/Developer-Guide.md
This PR updates the developer guide at the connect to the debug console section.
Fixes #7094
> docs: Update Developer Guide

- tests/metrics/lib/common.bash
This PR adds the test lib common script that is going to be used for kata containers metrics.
Fixes #7113
> tests: Add tests lib common script

- tests/common.bash
- tests/metrics/gha-run.sh
The common.sh script includes helper functions used in our metrics tests, so we are gradually adding more metrics used in kata.
Fixes: #7108
> tests: Move tests helper script to this repo

- .github/workflows/run-metrics.yaml
This PR removes an unrecognized value located in one of the yamls for the gha in order to make it work the CI again.
Fixes #7149
> gha: Fix gha actions

- tests/metrics/gha-run.sh
- tests/metrics/lib/common.bash
- tests/metrics/time/launch_times.sh
This PR enables launch-times test on gha metrics workflow.
Fixes: #7049
> metrics: enable launch-times test on gha-run metrics script

- src/dragonball/src/device_manager/console_manager.rs
> dragonball: avoid obtaining lock twice in create_stdio_console

- src/runtime/pkg/katautils/config.go
- src/runtime/virtcontainers/remote.go
> runtime: Add support for key annotations to remote hyp

- src/runtime-rs/crates/hypervisor/src/device/driver/vfio.rs
Vfio support introduce build error on AArch64. Remove arch related annotation can avoid this error.
Fixes: #7187
> runtime-rs: fix build error on AArch64

- src/runtime-rs/crates/hypervisor/src/device/device_manager.rs
- src/runtime-rs/crates/hypervisor/src/device/mod.rs
- src/runtime-rs/crates/hypervisor/src/dragonball/inner.rs
- src/runtime-rs/crates/hypervisor/src/dragonball/mod.rs
- src/runtime-rs/crates/hypervisor/src/dragonball/vmm_instance.rs
- src/runtime-rs/crates/hypervisor/src/lib.rs
- src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
- src/runtime-rs/crates/hypervisor/src/qemu/mod.rs
- src/runtime-rs/crates/resource/src/manager_inner.rs
- src/runtime-rs/crates/resource/src/network/endpoint/physical_endpoint.rs
- src/runtime-rs/crates/resource/src/network/mod.rs
- src/runtime-rs/crates/resource/src/network/network_with_netns.rs
use the device manager to attach the physical endpoint
Fixes: #7103
> runtime-rs:  support physical endpoint using device manager

- .github/workflows/cc-payload-after-push-amd64.yaml
- .github/workflows/cc-payload-after-push-s390x.yaml
- .github/workflows/cc-payload-amd64.yaml
- .github/workflows/cc-payload-s390x.yaml
TIL that when using "include" for a matrix we must duplicate the value we're overriding for each element we want that to happen.
Fixes: #7235
> cc: gha: Matrix "include" cannot be a list

- .github/workflows/run-metrics.yaml
- tests/metrics/gha-run.sh
- tests/metrics/storage/blogbench.sh
- tests/metrics/storage/blogbench_dockerfile/Dockerfile
- tests/metrics/storage/web-tooling-dockerfile/Dockerfile.in
- tests/metrics/storage/webtooling.sh
This PR adds blogbench and webtooling metrics checks to this repo.
Fixes: #7069
> metrics: Adds blogbench and webtool metrics tests

- .github/workflows/run-metrics.yaml
- tests/common.bash
- tests/metrics/gha-run.sh
- tests/metrics/lib/common.bash
This PR enables storing metrics workflow artifacts in two separated flavours: clh and qemu.
Fixes: #7239
> metrics: storing metrics workflow artifacts

- tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
- tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
- tests/metrics/density/memory_usage.sh
- tests/metrics/gha-run.sh
This PR enables the memory usage metrics tests for kata CI.
Fixes #7229
> tests: Enable memory usage metrics tests

- .github/workflows/ci-nightly.yaml
- .github/workflows/ci-on-push.yaml
- .github/workflows/ci.yaml
- .github/workflows/payload-after-push.yaml
Please, take a look at each individual commit message for more details.
> gha: ci: Follow up fixes for the nightly jobs

- .github/workflows/ci-nightly.yaml
- .github/workflows/ci-on-push.yaml
- .github/workflows/ci.yaml
Please, take a look at each commit message for more details.
> gha: ci: More follow up fixes after adding a nightly CI

- tests/integration/gha-run.sh
This is a very simple addition, that should be expanded by
https://github.com/kata-containers/kata-containers/pull/7295, and it's
targetting gathering more info that will help us to debug CI failures.
Fixes: #7296
> gha: ci: Gather info about the node / pods

- tests/metrics/README.md
- tests/metrics/machine_learning/README.md
- tests/metrics/machine_learning/pytorch.sh
- tests/metrics/machine_learning/pytorch_dockerfile/Dockerfile
- tests/metrics/machine_learning/tensorflow.sh
- tests/metrics/machine_learning/tensorflow_dockerfile/Dockerfile
This PR adds machine learning performance tests like Tensorflow and Pytorch scripts as well as general documentation.
> tests: Add machine learning performance tests

- tests/metrics/machine_learning/README.md
- tests/metrics/machine_learning/tensorflow_mobilenet_benchmark.sh
- tests/metrics/machine_learning/tensorflow_mobilenet_dockerfile/Dockerfile
This PR adds the MobileNet Tensorflow perfomance script as well as its proper Dockerfile and finally we are adding its proper documentation as part of the machine learning documentation.
> tests: Add MobileNet Tensorflow performance benchmark

- .github/workflows/run-cri-containerd-tests.yaml
KATA_HYPERVSIOR should be KATA_HYPERVISOR
Fixes: #6543
> gha: ci: cri-containerd: Fix KATA_HYPERVSIOR typo

- tests/metrics/machine_learning/README.md
This PR updates the machine learning documentation related with Tensorflow and Pytorch benchmarks.
Fixes #7359
> metrics: Update machine learning documentation

- tests/integration/kubernetes/gha-run.sh
This is a follow up of 2ee2cd307b001f8eab4d8192271cf0e3fec4c595, which changed the location of gha-run.sh
Fixes: #7373
> ci: k8s: Adapt "source ..." to the new location of gha-run.sh

- src/agent/Cargo.lock
- src/agent/Cargo.toml
- tests/integration/kubernetes/tests_common.sh
- tools/packaging/kata-deploy/examples/test-deploy-kata-clh.yaml
- tools/packaging/kata-deploy/examples/test-deploy-kata-dragonball.yaml
- tools/packaging/kata-deploy/examples/test-deploy-kata-fc.yaml
- tools/packaging/kata-deploy/examples/test-deploy-kata-qemu.yaml
- tools/packaging/kata-deploy/examples/test-deploy-runc.yaml
- versions.yaml
This update the CC dependencies to the 0.7.0-rc commits.
Step 4. on https://github.com/confidential-containers/confidential-containers/issues/111.
> CC | Update deps 0.7.0 (rc)

- src/agent/Cargo.lock
- src/agent/Cargo.toml
- versions.yaml
Fixes: #7400 
Step 16 of https://github.com/confidential-containers/confidential-containers/issues/111
> CC | Update to v0.7.0 tags 

- .github/workflows/ci.yaml
- .github/workflows/run-vfio-tests.yaml
- tests/functional/vfio/gha-run.sh
This job will run on a nested virt capable Azure VM (improving test concurrency). This is just a placeholder while we adapt the test to GHA.
> gha: ci: Add skeleton of vfio job

- tests/metrics/lib/json.bash
This PR adds general improvements like putting function before function name and consistency in how we declare variables and so on to have uniformity across the metrics scripts.
Fixes #7429
> metrics: General improvements to json.bash script

- .github/workflows/run-k8s-tests-on-aks.yaml
- .github/workflows/run-k8s-tests-on-sev.yaml
- .github/workflows/run-k8s-tests-on-snp.yaml
- .github/workflows/run-k8s-tests-on-tdx.yaml
- tests/.gitignore
- tests/integration/kubernetes/gha-run.sh
- tests/integration/kubernetes/run_kubernetes_tests.sh
- tests/integration/kubernetes/setup.sh
- tests/integration/kubernetes/tests_common.sh
This is a series of patches to make running tests outside of GHA more pleasant.
Fixes: #7454
> tests: QoL improvements for running tests locally

- tests/metrics/storage/fio-k8s/cmd/fiotest/Makefile
- tests/metrics/storage/fio-k8s/cmd/fiotest/main.go
- tests/metrics/storage/fio-k8s/pkg/env/Makefile
- tests/metrics/storage/fio-k8s/pkg/env/env.go
- tests/metrics/storage/fio-k8s/pkg/exec/Exec.go
- tests/metrics/storage/fio-k8s/pkg/k8s/Makefile
- tests/metrics/storage/fio-k8s/pkg/k8s/exec.go
- tests/metrics/storage/fio-k8s/pkg/k8s/k8s.go
- tests/metrics/storage/fio-k8s/scripts/Makefile
- tests/metrics/storage/fio-k8s/scripts/compare-virtiofsd-dax.sh
- tests/metrics/storage/fio-k8s/scripts/dax-compare-test/report/fio.ipynb
- tests/metrics/storage/fio-k8s/scripts/dax-compare-test/report/fio.py
- tests/metrics/storage/fio-k8s/scripts/dax-compare-test/report/gen-html-fio-report.sh
- tests/metrics/storage/fio-k8s/scripts/dax-compare-test/report/run-docker-jupyter-server.sh
This PR adds FIO report files for kata metrics.
Fixes #7472
> metrics: Add FIO report files for kata metrics

- src/runtime-rs/crates/runtimes/src/manager.rs
- src/runtime-rs/crates/service/src/manager.rs
- src/runtime-rs/crates/service/src/task_service.rs
- src/runtime-rs/crates/shim-ctl/src/main.rs
- src/runtime-rs/crates/shim/src/shim_run.rs
Simplify implementation of runtime-rs/service.
Fixes: https://github.com/kata-containers/kata-containers/issues/7479
> Simplify implementation of runtime-rs/service

- tests/metrics/density/README.md
- tests/metrics/density/k8s-sysbench.sh
- tests/metrics/density/runtimeclass_workloads/sysbench-pod.yaml
- tests/metrics/density/sysbench-dockerfile/Dockerfile
This PR adds the sysbench performance test for kata CI.
Fixes #7485
> metrics: Add sysbench performance test

- tests/metrics/README.md
- tests/metrics/network/README.md
- tests/metrics/network/iperf3_kubernetes/k8s-network-metrics-iperf3.sh
- tests/metrics/network/iperf3_kubernetes/runtimeclass_workloads/iperf3-daemonset.yaml
- tests/metrics/network/iperf3_kubernetes/runtimeclass_workloads/iperf3-deployment.yaml
- tests/metrics/network/iperf3_kubernetes/runtimeclass_workloads/iperf3-service.yaml
This PR adds the iperf3 benchmark test for kata metrics.
Fixes #7515
> metrics: Add iperf3 network test

- tests/common.bash
- tests/metrics/lib/common.bash
- tests/metrics/time/launch_times.sh
This PR kills all kata components before start a new metric test.
> metrics: stop kata components before start a metric test.

- src/runtime-rs/crates/hypervisor/src/dragonball/inner_device.rs
Looks like a copy/paste error...
> fix number of queues handling in dragonball share fs device

- src/agent/src/mount.rs
- src/agent/src/rpc.rs
- src/agent/src/sandbox.rs
Fix mimor bugs and improve coding stype of agent rpc/sandbox/mount, it's a preparation to enhance the agent/mount subsystem.
> Fix mimor bugs and improve coding stype of agent rpc/sandbox/mount

- .github/workflows/ci.yaml
- .github/workflows/run-k8s-tests-on-sev.yaml
- .github/workflows/run-k8s-tests-on-snp.yaml
- .github/workflows/run-k8s-tests-on-tdx.yaml
Please, take a look at each one of the commit messages.
> Follow up fixes for https://github.com/kata-containers/kata-containers/pull/7596

- tests/metrics/machine_learning/tensorflow.sh
This PR computes average results for TF bench.
Additionally, it improves the data parsing from
all running containers.
Fixes: #7603
> metrics: compute tensorflow statistics

- src/agent/src/rpc.rs
- src/runtime/config/configuration-clh.toml.in
- src/runtime/config/configuration-qemu-nvidia-gpu.toml.in
- src/runtime/config/configuration-qemu-sev.toml.in
- src/runtime/config/configuration-qemu-snp.toml.in
- src/runtime/config/configuration-qemu-tdx.toml.in
- src/runtime/config/configuration-qemu.toml.in
- src/runtime/virtcontainers/fs_share.go
- src/runtime/virtcontainers/fs_share_darwin.go
- src/runtime/virtcontainers/fs_share_linux.go
- src/runtime/virtcontainers/kata_agent.go
- src/runtime/virtcontainers/kata_agent_test.go
- src/runtime/virtcontainers/sandbox.go
> Propogate secrets, config maps etc into guest if sharedFS not available

- tests/metrics/lib/common.bash
- tests/metrics/machine_learning/tensorflow.sh
- tests/metrics/machine_learning/tensorflow_mobilenet_v1_bfloat16_fp32.sh
This PR adds the collect results function to the common metrics script.
Fixes #7617
> metrics: Add common functions to the common script

- src/agent/rustjail/src/container.rs
- https://github.com/kata-containers/kata-containers/issues/7168
- runk fails to launch OCI container when no PID ns is given in spec (`config.json`)
- This PR fixes runk to launch container when no pid ns is given
```
[
{
"type": "ipc"
},
{
"type": "uts"
},
{
"type": "cgroup"
},
{
"type": "network"
},
{
"type": "mount"
}
]
Hello from runk
```
> runk: Support without pid ns

- tests/metrics/machine_learning/tensorflow_mobilenet_v1_bfloat16_fp32.sh
This PR fixes MobileNet help me description in the tensorflow script.
Fixes #7661
> metrics: Fix MobileNet help me description

- src/agent/src/rpc.rs
We extend the `Result` and `Option` types with associated types that allows converting a `Result<T, E>` and `Option<T>` into `ttrpc::Result<T>`.
This allows the elimination of many `match` statements in favor of calling the map function plus the `?` operator. This transformation simplifies the code.
Fixes: #7624
> agent: simplify error handling

- tests/metrics/machine_learning/README.md
- tests/metrics/machine_learning/resnet50_int8_dockerfile/Dockerfile
- tests/metrics/machine_learning/tensorflow_resnet50_int8.sh
This PR adds the Tensorflow ResNet50 int8 script for kata metrics.
Fixes #7652
> metrics: Add Tensorflow ResNet50 int8 benchmark

- tests/metrics/machine_learning/pytorch.sh
This PR uses a common function into the pytorch script.
Fixes #7709
> metrics: Use function from metrics common in pytorch script

- tests/metrics/storage/fio-k8s/fio-test-ci.sh
This PR fixes the FIO path for the FIO files.
Fixes #7711
> metrics: Fix FIO path

- src/libs/kata-types/src/mount.rs
Introduce a common structure KataVirtualVolume to support Nydus, direct volume and image pulling for Coco, so we can build a common infrastructure for them later.
> kata-types: introduce KataVirtualVolume to support nydus, direct volume and image pull

- .github/workflows/static-checks.yaml
- src/agent/Cargo.lock
- src/agent/Cargo.toml
- tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in
- versions.yaml
- image-rs & AA: 917984103e1029d8ff93d91df3c973761910508c
- td-shim: 4ecf76ab8bc57c2e857937487d1923961c2b6769
> **Note**: This PR is for reducing delta to reduce work during release and find problems early on.
> Update AA, image-rs td-shim

- src/libs/kata-types/src/mount.rs
cherry-pick PR #7698 into CCv0, there's no any conflicts during cherry-pick.
> CC | cherry-pick PR #7698 into CCv0

- tests/metrics/machine_learning/resnet50_fp32_dockerfile/Dockerfile
- tests/metrics/machine_learning/tensorflow_resnet50_fp32.sh
This PR adds TensorFlow ResNet50 FP32 benchmark for kata metrics.
Fixes #7735
> metrics: Add TensorFlow ResNet50 FP32 benchmark

- tests/integration/kubernetes/confidential_common.sh
- tests/integration/kubernetes/k8s-confidential.bats
- tests/integration/kubernetes/run_kubernetes_tests.sh
- tests/integration/kubernetes/runtimeclass_workloads/pod-confidential-unencrypted.yaml
Add a test case for the launch of unencrypted confidential container.
Fixes: #7184
> tests: Add confidential test

- tests/metrics/density/memory_usage.sh
This PR fixes an issues in the parsing results stage, by collecting just the n-results from the n-running containers, discarding irrelevant data.
Fixes: #7774
> metrics: fix parsing issue on memory-usage test

- tests/metrics/report/makereport.sh
- tests/metrics/report/report_dockerfile/Dockerfile
- tests/metrics/report/report_dockerfile/dut-details.R
- tests/metrics/report/report_dockerfile/fio-reads.R
- tests/metrics/report/report_dockerfile/fio-writes.R
- tests/metrics/report/report_dockerfile/footprint-density.R
- tests/metrics/report/report_dockerfile/genreport.sh
- tests/metrics/report/report_dockerfile/html.Rmd
- tests/metrics/report/report_dockerfile/lifecycle-time.R
- tests/metrics/report/report_dockerfile/mem-in-cont.R
- tests/metrics/report/report_dockerfile/memory-footprint.R
- tests/metrics/report/report_dockerfile/metrics_report.Rmd
- tests/metrics/report/report_dockerfile/network-cpu.R
This PR adds metrics report script for kata metrics.
Fixes #7782
> metrics: Add metrics report script

- src/runtime/cmd/kata-runtime/kata-check_amd64_test.go
- src/runtime/cmd/kata-runtime/kata-env_amd64_test.go
Some tests are failing when running on AMD machines. I suspect GH CI is not running on amd and is not failing there. Vide individual commits for details.
> Fixes tests on AMD machines

- src/libs/kata-sys-util/src/protection.rs
Update the protection checking code to detect newer versions of Intel TDX (whose userland interface has now stabilised).
> **Note:** that we don't need to retain the existing behaviour since:
>
> - We haven't yet landed the TDX feature (#6448).
> - Systems wishing to use TDX will need to use the latest available
>   system components (such as firmware and host kernel).
Also added an explicit TDX unit test.
Fixes: #7384.
> kata-sys-util: protection: Update TDX checks

- src/agent/src/sandbox.rs
- src/agent/src/storage/mod.rs
- src/libs/kata-types/src/mount.rs
cherry-pick #7819 and #7821 from main branch.
> CC | cherry-pick #7819 and #7821 from main branch

- tests/metrics/README.md
- tests/metrics/report/README.md
This PR adds the README for kata metrics report.
Fixes #7802
> metrics: Add README for kata metrics report

- .github/workflows/run-k8s-tests-on-garm.yaml
integrations -> integration
integrtion -> integration
Fixes: #6542
> ci: k8s: Fix typo in run-k8s-tests-on-garm.yaml

- .github/workflows/run-k8s-tests-on-aks.yaml
- .github/workflows/run-k8s-tests-on-garm.yaml
- .github/workflows/run-k8s-tests-on-sev.yaml
- .github/workflows/run-k8s-tests-on-snp.yaml
- .github/workflows/run-k8s-tests-on-tdx.yaml
- tests/integration/kubernetes/gha-run.sh
This time we'll actually be able to run the tests, hopefully, and this PR will include all the needed fixes to get them green.
> ci: k8s: Second round of fix-ups with the devmapper CI

- tests/integration/kubernetes/gha-run.sh
- tests/integration/kubernetes/k8s-cpu-ns.bats
- tests/integration/kubernetes/k8s-credentials-secrets.bats
- tests/integration/kubernetes/k8s-file-volume.bats
- tests/integration/kubernetes/k8s-inotify.bats
- tests/integration/kubernetes/k8s-nested-configmap-secret.bats
- tests/integration/kubernetes/k8s-pod-quota.bats
- tests/integration/kubernetes/k8s-projected-volume.bats
- tests/integration/kubernetes/k8s-volume.bats
The tests are failing to finish as the argument is invalid.
Fixes: #6542
> ci: k8s: Add clean-up-garm argument for gha-run.sh

- src/agent/src/config.rs
- src/dragonball/src/dbs_utils/src/net/net_gen/mod.rs
- src/dragonball/src/vcpu/vcpu_manager.rs
- src/libs/safe-path/src/scoped_path_resolver.rs
- src/runtime-rs/crates/resource/src/network/utils/address.rs
- src/runtime-rs/crates/resource/src/volume/block_volume.rs
- src/runtime-rs/crates/resource/src/volume/shm_volume.rs
- src/runtime-rs/crates/resource/src/volume/spdk_volume.rs
- src/tools/agent-ctl/src/client.rs
- src/tools/kata-ctl/src/check.rs
- src/tools/kata-ctl/src/ops/exec_ops.rs
- src/tools/kata-ctl/src/utils.rs
- src/tools/runk/libcontainer/src/utils.rs
- versions.yaml
Bump rust to 1.72.0 to test what extra warnings/issues we get
Fixes: #7902
> versions: Bump rust version

- src/agent/src/config.rs
- src/dragonball/src/dbs_utils/src/net/net_gen/mod.rs
- src/dragonball/src/vcpu/vcpu_manager.rs
- src/libs/safe-path/src/scoped_path_resolver.rs
- src/runtime-rs/crates/resource/src/network/utils/address.rs
- src/runtime-rs/crates/resource/src/volume/block_volume.rs
- src/runtime-rs/crates/resource/src/volume/shm_volume.rs
- src/runtime-rs/crates/resource/src/volume/spdk_volume.rs
- src/tools/agent-ctl/src/client.rs
- src/tools/kata-ctl/src/check.rs
- src/tools/kata-ctl/src/ops/exec_ops.rs
- src/tools/kata-ctl/src/utils.rs
- src/tools/runk/libcontainer/src/utils.rs
- versions.yaml
Bump rust to 1.72 - cherry-picked from https://github.com/kata-containers/kata-containers/pull/7811
> CCv0 bump to rust 1.72

- src/runtime/virtcontainers/network_linux.go
When creating a new endpoint, we check existing endpoint names and automatically adjust the naming of the new endpoint to ensure uniqueness.
Fixes: #7876
> runtime: Naming conflict of network devices

- tests/metrics/disk/README.md
This PR adds the Cassandra Metrics documentation for kata metrics.
Fixes #7922
> metrics: Add Cassandra Metrics documentation

- .github/workflows/ci.yaml
- .github/workflows/run-kata-deploy-tests-on-aks.yaml
- .github/workflows/run-kata-deploy-tests-on-garm.yaml
- .github/workflows/run-kata-deploy-tests-on-tdx.yaml
- tests/functional/kata-deploy/gha-run.sh
- tests/functional/kata-deploy/kata-deploy.bats
- tests/gha-run-k8s-common.sh
- tests/integration/kubernetes/gha-run.sh
Basically, let's also test on rke2 and k0s as well.
> ci: kata-deploy: Enable all k8s flavours that we support

- .github/workflows/payload-after-push.yaml
This will allow us to easily test failures and fixes on that workflows.
Fixes: #8031
> ci: Trigger payload-after-push on workflow_dispatch

- tests/metrics/cpu/README.md
This PR fixes the C-Ray documentation for kata metrics.
Fixes #8052
> metrics: Fix C-Ray documentation

- tests/metrics/network/latency_kubernetes/latency-network.sh
This PR fixes the latency yamls path for the latency test for kata metrics.
Fixes #8055
> metrics: Fix latency yamls path

- docs/design/kata-vra.md
This PR updates the url in kata vra document.
Fixes #8065
> docs: Update url in kata vra document

- tests/stability/agent_stability_test.sh
- tests/stability/cassandra_stress.sh
- tests/stability/scability_test.sh
- tests/stability/stressng.sh
- tests/stability/stressng_dockerfile/Dockerfile
This PR adds the stability test for kata containers repository.
Fixes #8084
> tests: Add stability test for kata CI

- .github/workflows/ci.yaml
- .github/workflows/run-containerd-stability-tests.yaml
- tests/stability/gha-run.sh
This PR adds the stability test workflow for gha for the kata CI.
Fixes #8107
> gha: Add stability tests workflow for gha

- tests/metrics/network/iperf3_kubernetes/k8s-network-metrics-iperf3.sh
This PR adds a trap whenever the script exits, it deletes the iperf k8s deployment and k8s services, and deletes the kata components.
This way, when the script finishes, it verifies that there are indeed no kata components still running.
Fixes: #8126
> metrics: removes kata components and k8s deployment when test finishes

- .github/workflows/basic-ci-amd64.yaml
- tests/stability/gha-run.sh
- tests/stability/soak_parallel_rm.sh
- versions.yaml
This PR enables the soak parallel stability test for the kata GHA CI.
> tests: Enable soak parallel stability test

- src/runtime-rs/crates/hypervisor/ch-config/src/ch_api.rs
- src/runtime-rs/crates/hypervisor/src/ch/inner.rs
- src/runtime-rs/crates/hypervisor/src/ch/inner_device.rs
This change adds support for adding vfio devices for cloud-hypervisor.
Fixes: #6691
> runtime-rs: Add support for adding vfio device for cloud-hypervisor

- tests/stability/gha-run.sh
- tests/stability/scability_test.sh
- tests/stability/soak_parallel_rm.sh
This PR enables the scability test for stability CI gha.
Fixes #8196
> tests: Enable scability test for stability CI

- versions.yaml
- Bump guest components to pick up fix to issue in https://github.com/confidential-containers/guest-components/pull/374
Fixes: #8223
> versions: Bump guest-components

- tests/integration/kubernetes/k8s-policy-set-keys.bats
- tests/integration/kubernetes/run_kubernetes_tests.sh
- tests/integration/kubernetes/runtimeclass_workloads/k8s-policy-set-keys.rego
- tests/integration/kubernetes/runtimeclass_workloads/k8s-policy-set-keys.yaml
Add example for querying json data from the OPA service.
> tests: query data from the OPA service

- tests/stability/agent_stability_test.sh
- tests/stability/gha-run.sh
This PR enables the agent stability test for stability gha CI.
Fixes #8240
> tests: Enable agent stability test

- tests/metrics/network/iperf3_kubernetes/k8s-network-metrics-iperf3-udp.sh
This PR adds the iperf udp benchmark for bandwdith measurement for network metrics.
Fixes #8246
> metrics: Add iperf udp benchmark

- src/agent/src/config.rs
- src/agent/src/rpc.rs
Remove the ability to block access to kata agent endpoints by using agent-config.toml. That functionality is now implemented using the Agent Policy feature (#7573).
The CCv0 branch relied on blocking endpoints using agent-config.toml but will set-up an equivalent default policy file instead (#8219).
Fixes: #8228
> agent: no endpoint blocking from agent-config.toml

- tests/metrics/network/iperf3_kubernetes/k8s-network-metrics-iperf3-udp.sh
This PR adds the parallel udp iperf3 benchmark for network metrics.
Fixes #8277
> metrics: Add parallel udp iperf3 benchmark

- .github/workflows/add-backport-label.yaml
- .github/workflows/add-issues-to-project.yaml
- .github/workflows/add-pr-sizing-label.yaml
- .github/workflows/basic-ci-amd64.yaml
- .github/workflows/build-kata-static-tarball-amd64.yaml
- .github/workflows/build-kata-static-tarball-arm64.yaml
- .github/workflows/build-kata-static-tarball-s390x.yaml
- .github/workflows/cargo-deny-runner.yaml
- .github/workflows/ci.yaml
- .github/workflows/darwin-tests.yaml
- .github/workflows/docs-url-alive-check.yaml
- .github/workflows/kata-runtime-classes-sync.yaml
- .github/workflows/move-issues-to-in-progress.yaml
- .github/workflows/payload-after-push.yaml
- .github/workflows/publish-kata-deploy-payload-amd64.yaml
- .github/workflows/publish-kata-deploy-payload-arm64.yaml
- .github/workflows/publish-kata-deploy-payload-s390x.yaml
- .github/workflows/release-amd64.yaml
- .github/workflows/release-arm64.yaml
- .github/workflows/release-s390x.yaml
- .github/workflows/release.yaml
- .github/workflows/require-pr-porting-labels.yaml
- .github/workflows/run-docker-tests-on-garm.yaml
- .github/workflows/run-k8s-tests-on-aks.yaml
- .github/workflows/run-k8s-tests-on-garm.yaml
- .github/workflows/run-kata-coco-tests.yaml
- .github/workflows/run-kata-deploy-tests-on-aks.yaml
- .github/workflows/run-metrics.yaml
- .github/workflows/run-nerdctl-tests-on-garm.yaml
Latest and hopefully ultimate fixes to be able to release 3.2.0 :
- #8287
- #8292
> Fix 3.2 release

- src/runtime-rs/crates/hypervisor/src/device/device_manager.rs
> runtime-rs: fix a typo in device manager

- src/runtime/virtcontainers/ipvlan_endpoint.go
- src/runtime/virtcontainers/macvlan_endpoint.go
We used the approach of cold-plugging network interface for pre-shimv2 support for docker.Since the hotplug approach was not required, we never really got to implementing hotplug support for certain network endpoints, ipvlan and macvlan being among them.
Since moving to shimv2 interface as the default for runtime, we switched to hotplugging the network interface for supporting docker and nerdctl. This was done for veth endpoints only.
Implement the hot-attach apis for ipvlan and macvlan as well to support ipvlan and macvlan networks with docker and nerdctl.
Fixes: #8333
> network: Fix network attach for ipvlan and macvlan

- src/agent/Cargo.lock
- src/agent/Cargo.toml
- versions.yaml
- image-rs & AA: e5e6e69ae0ea01393a125cde8e2772ad98aba39c
- td-shim: 3f18d9f3f51c9428c034cf01b45ab94bcd0d1622
> CCv0: Update image-rs, AA and td-shim

- utils/kata-manager.sh
This patch could fix the error encountered when attempting to deploy containerd on an arm machine(https://github.com/kata-containers/kata-containers/issues/7071), 
the error message : 
_ERROR: Cannot determine download URL for version v1.7.2 (https://api.github.com/repos/containerd/containerd/releases)_
This patch has been verified on both arm and x86 machines, the logs are as followed:
```
./kata-manager.sh  -k 3.2.0-alpha3 -c v1.7.2
INFO: Checking dependencies
INFO: Running pre-checks
INFO: Downloading Kata Containers release (version 3.2.0-alpha3)
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  130M  100  130M    0     0  12.9M …
```
> kata-manager: Fix deployment of containerd on architectures other than amd64.

- .github/workflows/stale.yaml
See the commits for more details.
> gha: stale: Fix typo and allow manually triggering it

- src/agent/src/image_rpc.rs
The pullimage handler behaves differently for the sandbox and container, and it uses the annotations to differentiate between the two. The annotation name used by crio for container-type being different than the containerd one, we need to check both.
Fixes: #8399
> CC | agent: fix annotation name to allow cri-o support of CoCo pullimage in guest

- src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs
Pause and resume task do not currently update the status of the container to paused or running, so fix this. This is for specifically pausing the task and not the VM.
Fixes #6434
> runtime-rs: Update status for pause and resume

- docs/how-to/README.md
- docs/how-to/how-to-use-the-kata-agent-policy.md
Add initial agent policy documentation.
Fixes: #7671
> docs: add agent policy documentation

- tests/stability/gha-run.sh
- tests/stability/stressng.sh
This PR enables the stressng scalability test for kata CI.
Fixes #8420
> tests: Enable stressng scalability test

- src/libs/kata-sys-util/src/protection.rs
- src/libs/kata-types/src/config/shared_mount.rs
Compiler is giving us two errors when running make check.
> Fixes make check errors

- .github/workflows/run-metrics.yaml
This PR disables the stratovirt for gha metrics.
Fixes #8496
> gha: Disable stratovirt for gha metrics

- tools/osbuilder/rootfs-builder/alpine/config.sh
> osbuilder: add pkg bash for alpine

- src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
Launch cloud-hypervisor binary in the netns provided at the prepare_vm
stage.
Fixes: #6441
> runtime-rs: Launch cloud-hypervisor in given netns

- tools/packaging/kata-deploy/kata-deploy/overlays/stable/env_stable_conf.yaml
- tools/packaging/kata-deploy/kata-deploy/overlays/stable/kustomization.yaml
> deployment: Add stable overlay for kata-deploy.yaml

- tools/packaging/kata-deploy/Dockerfile
- tools/packaging/kata-deploy/scripts/kata-deploy.sh
Please, see each commit description for better understanding of what we're doing.
> kata-deploy: Use `tomlq` to configure containerd

- .github/workflows/static-checks.yaml
As described in the [issue](https://github.com/kata-containers/kata-containers/issues/8673), we need to install some dependencies to fix issues in static checks. 
Fixes #8673
> static-checks: Add some dependencies to static checks for CoCo features

- tests/integration/kubernetes/setup.sh
This PR fixes the indentation of the kubernetes setup script.
Fixes #8675
> tests: k8s: Fix indentation in setup script

- tools/packaging/kata-deploy/scripts/kata-deploy.sh
- Add spaces so that the if statements are valid
Fixes: #8720
> kata-deploy: snapshotter typo fixes

- src/libs/kata-types/src/config/hypervisor/mod.rs
- src/runtime-rs/crates/hypervisor/src/device/device_manager.rs
- src/runtime-rs/crates/hypervisor/src/device/driver/vfio.rs
- src/runtime-rs/crates/hypervisor/src/device/driver/vhost_user_blk.rs
- src/runtime-rs/crates/hypervisor/src/device/driver/vhost_user_net.rs
- src/runtime-rs/crates/hypervisor/src/device/driver/virtio_blk.rs
- src/runtime-rs/crates/hypervisor/src/device/driver/virtio_fs.rs
- src/runtime-rs/crates/hypervisor/src/device/driver/virtio_net.rs
- src/runtime-rs/crates/hypervisor/src/device/driver/virtio_vsock.rs
- src/runtime-rs/crates/hypervisor/src/device/mod.rs
- src/runtime-rs/crates/hypervisor/src/device/topology.rs
- src/runtime-rs/crates/resource/src/manager_inner.rs
- src/runtime-rs/crates/resource/src/network/endpoint/endpoints_test.rs
It's for kinds of pci devices which will be attached on the pci/pcie bus.
Fixes: #7218
> runtime-rs: add pci topology for pci devices

- src/tools/genpolicy/Cargo.lock
- src/tools/genpolicy/src/policy.rs
- src/tools/genpolicy/src/volume.rs
Also, update Cargo.lock
Fixes: #8816
> genpolicy: "cargo fmt -- --check" clean-up

- src/runtime-rs/crates/resource/src/volume/utils.rs
DirectVolume/Rawblock doesn't work well when device's block driver is virtio-blk-pci and the storage handler is DRIVER_BLK_PCI_TYPE.
Fixes: #8707
> runtime-rs: bugfix for DirectVolume/rawblock when driver is blk

- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
This tool can be useful for any users.
Fixes: #8907
> tools: allow all users to execute genpolicy

- tests/metrics/machine_learning/resnet50_int8_dockerfile/Dockerfile
This PR updates the required packages for the TensorFlow ResNet50 Int8 Dockerfile.
Fixes #8950
> metrics: Update packages for TensorFlow ResNet Int8 Dockerfile

- tools/packaging/scripts/configure-hypervisor.sh
- tools/packaging/static-build/qemu/Dockerfile
- versions.yaml
This is required to allow creation of SNP coco on host kernel (e.g. https://github.com/AMDESE/linux ,branch:snp-host-latest) supporting guest private memory for SNP using gmem.
> packaging: qemu-snp-experimental: support host kernel with gmem

- src/tools/genpolicy/rules.rego
- tests/integration/kubernetes/k8s-caps.bats
- tests/integration/kubernetes/k8s-configmap.bats
- tests/integration/kubernetes/k8s-copy-file.bats
- tests/integration/kubernetes/k8s-cpu-ns.bats
- tests/integration/kubernetes/k8s-credentials-secrets.bats
- tests/integration/kubernetes/k8s-custom-dns.bats
- tests/integration/kubernetes/k8s-env.bats
- tests/integration/kubernetes/k8s-file-volume.bats
- tests/integration/kubernetes/k8s-job.bats
- tests/integration/kubernetes/k8s-kill-all-process-in-container.bats
- tests/integration/kubernetes/k8s-limit-range.bats
- tests/integration/kubernetes/k8s-memory.bats
- tests/integration/kubernetes/k8s-number-cpus.bats
- tests/integration/kubernetes/k8s-oom.bats
- tests/integration/kubernetes/k8s-optional-empty-configmap.bats
- tests/integration/kubernetes/tests_common.sh
Auto-generate Policy for ~15 additional tests.
Fixes: #9072
> tests: k8s: generated policy for additional tests

- tests/integration/kubernetes/gha-run.sh
CI failed to deploy nydus snapshotter because it was not cleaned up last time. So we can try to cleanup nydus snapshotter before deploying it.
Fixes: #9121
> gha: try to cleanup nydus snapshotter before deploying it

- tests/common.bash
- tests/error.sh
This PR adds an enhanced die function in order to dump more information in a yaml format that will help with the debugging.
Fixes #9105
> scripts: Add an enhanced die function

- tests/integration/kubernetes/gha-run.sh
~~This reverts commit 7299dbdb43b62a4a23783e6eeda714d4d465e782.~~
~~The collect artifacts step on garm jobs are failing due to the unset `start_time` variable.~~
Reverting didn't work.
---
The jobs running on garm will collect journal information. The data gathered
is based on the time the tests started running. The $start_time is
exported on run_tests() and used in collect_artifacts(). It happens that
run_tests() and collect_artifacts() are called on different steps of the
workflow and the environment variables aren't preserved between them,
i.e, $start_time exported on the first step is not available on the
subsequents.
To solve that issue, let's save $start_time in the file pointed out by
$GITHUB_ENV that Github actions uses to export variables. In case $GITHUB_ENV is
empty then …
> gha: export start_time to collect artifacts properly 

- tests/integration/kubernetes/gha-run.sh
The k3s distribution of k8s uses an embedded version of containerd and configures it to log to a file, not the journal. Hence, although we collect the journal as a test artifact, we also need to collect the actual log files for containerd.
Also collect the k3s containerd config files to help with debugging.
Fixes: #9104.
> tests: Add k3s artifacts

- tests/integration/kubernetes/k8s-parallel.bats
- tests/integration/kubernetes/k8s-qos-pods.bats
- tests/integration/kubernetes/k8s-replication.bats
- tests/integration/kubernetes/k8s-scale-nginx.bats
- tests/integration/kubernetes/k8s-shared-volume.bats
Auto-generate Policy for more K8s tests.
Fixes: #9096
> tests: k8s: auto-generated policy

- .github/workflows/basic-ci-amd64.yaml
- tests/integration/nerdctl/gha-run.sh
This PR adds the collect artifacts step to nerdctl workflow.
Fixes #9241
> gha: Add collect artifacts step to nerdctl workflow

- tests/integration/kubernetes/k8s-exec.bats
Auto-generate policy for k8s-exec.bats.
Fixes: #9247
> tests: k8s: k8s-exec.bats auto-generated policy

- tests/integration/kubernetes/k8s-pid-ns.bats
Auto-generate policy for k8s-pid-ns.bats.
Fixes: #9249
> tests: k8s: k8s-pid-ns.bats auto-generated policy

- src/runtime-rs/Cargo.lock
- src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
Small improvement on the passed file descriptors.
Fixes #9281
> runtime-rs: Consolidate the handling of fds passed to QEMU

- ci/openshift-ci/cleanup.sh
- ci/openshift-ci/cluster/deployments/relabel_selinux.yaml
- ci/openshift-ci/cluster/deployments/workaround-9206-crio-ds.yaml
- ci/openshift-ci/cluster/deployments/workaround-9206-crio.yaml
- ci/openshift-ci/cluster/install_kata.sh
Please see the individual commits for details.
Fixes:  #9228
Related to: #9206
> ocp.ci: Various fixes and improvements to the OCP pipeline

- docs/Documentation-Requirements.md
This PR updates the url links in the Documentation Requirements document.
Fixes #9306
> docs: Update links in the Documentation Requirements document

- src/runtime-rs/Cargo.lock
- src/runtime-rs/crates/hypervisor/Cargo.toml
- src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
Add in the full details once cloud-hypervisor/cloud-hypervisor#6103 has been implemented, and the feature is available in a Cloud Hypervisor release.
Fixes: #8799
> runtime-rs: ch: Implement full thread/tid/pid handling

- src/agent/src/namespace.rs
- src/agent/src/util.rs
Refactor unit tests to leverage rstest for parameterization. 
Fixes: #9314
> agent: Refactor unit tests to leverage rstest for parameterization

- docs/code-pr-advice.md
- src/runtime/Makefile
- src/runtime/pkg/katautils/katatrace/tracing.go
- tools/osbuilder/dockerfiles/QAT/run.sh
- tools/packaging/scripts/lib.sh
Remove links and references to files/scripts in tests repo when they can be replaced by ones from the kata containers repo.
> Remove additional links to tests directory

- src/agent/Cargo.lock
- src/agent/Cargo.toml
- src/agent/README.md
- src/agent/src/config.rs
- src/agent/src/main.rs
- tests/gha-run-k8s-common.sh
- tests/integration/kubernetes/confidential_kbs.sh
- tests/integration/kubernetes/filter_out_per_arch/aarch64.yaml
- tests/integration/kubernetes/filter_out_per_arch/ppc64le.yaml
- tests/integration/kubernetes/gha-run.sh
- tests/integration/kubernetes/k8s-confidential-attestation.bats
- tests/integration/kubernetes/run_kubernetes_tests.sh
- tests/integration/kubernetes/runtimeclass_workloads/pod-attestable.yaml
- tools/packaging/static-build/coco-guest-components/Dockerfile
- tools/packaging/static-build/coco-guest-components/build.sh
- versions.yaml
build attestation-agent, confidential-data-hub, api-server-rest for rootfs image.
and launch them by kata-agent in guest
> port attestation agent from CCv0 branch to main branch

- tests/integration/kubernetes/gha-run.sh
This PR fixes an identation in gha run script.
Fixes #9449
> gha: Fix indentation in gha run script

- .github/workflows/commit-message-check.yaml
- .github/workflows/move-issues-to-in-progress.yaml
We've discussed this over and over. Let's try to get to an agreement here. I will use this issue to remove the mandatory Issue - PR dependency.
Fixes: #9500
> kata: Remove check for "Fixes" in PR

- src/agent/rustjail/src/container.rs
- src/agent/rustjail/src/process.rs
- src/agent/src/rpc.rs
- src/dragonball/src/dbs_virtio_devices/src/vsock/csm/connection.rs
- src/runtime-rs/crates/runtimes/virt_container/src/container_manager/io/passfd_io.rs
- src/runtime-rs/crates/runtimes/virt_container/src/container_manager/io/shim_io.rs
- src/runtime-rs/crates/runtimes/virt_container/src/container_manager/process.rs
- dragonball: fix EPOLLHUP/EPOLLERR events handling in vsock
- agent: Fix close_stdin for passfd-io
- runtime-rs: fix FIFO handling
Fixes: #9334
Run a normal container with `-t` and a simple command.
<details>
```sh
$ sudo ctr run --runtime io.containerd.run.kata.v2 --rm -t docker.io/library/busybox:latest hello id
uid=0(root) gid=0(root) groups=0(root),10(wheel)
$ sudo ctr run --runtime io.containerd.run.kata.v2 --rm -t docker.io/library/ubuntu:latest hello id
uid=0(root) gid=0(root) groups=0(root)
$ sudo ctr run --runtime io.containerd.run.kata.v2 --rm -t docker.io/library/ubuntu:latest hello sh
uid=0(root) gid=0(root) groups=0(root)
```
</details>
Run a normal container with a simple command, not using a terminal.
<details>
```sh
$ sudo ctr run --runtime io.containerd.run.kata.v2 --rm …
```
> passfd-io: fix FIFO opening and vsock handling

- tests/integration/kubernetes/gha-run.sh
Enable the k8s tests for cloud hypervisor with devicemapper.
Fixes: #9221.
Co-authored-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>
> gha: Enable k8s tests for cloud hypervisor with devicemapper

- src/runtime-rs/crates/hypervisor/src/qemu/cmdline_generator.rs
WiP, still missing implementation on the QemuCmdLine struct
Signed-off-by: Emanuel Lima <emlima@redhat.com>
> runtime-rs: Add RTC to QEMU cmdline

- src/dragonball/src/device_manager/vfio_dev_mgr/pci_vfio.rs
dragonball reserves 2048G of mmio space for the pci root bus by default on physical addresses greater than 4G. However, for some machines with smaller physical address widths, such as 39-bit wide physical addresses, dragonball reserves the mmio space when initializing the memory. It is less than 2048G, so this commit dynamically calculates and allocates the mmio size of each pci root bus.
Fixes: #9509
> db: fix the issue of failed to init pci root bus

- tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml
- tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
- tools/packaging/kata-deploy/runtimeclasses/kata-qemu-nvidia-gpu-snp.yaml
- tools/packaging/kata-deploy/runtimeclasses/kata-qemu-nvidia-gpu-tdx.yaml
- tools/packaging/kata-deploy/runtimeclasses/kata-runtimeClasses.yaml
Fixes: #9483
For the added configurations we need to provide runtimeClasses.
> deploy: Add runtimeClasses relating to the NVIDIA GPU

- tests/gha-run-k8s-common.sh
This PR fixes the indentation in gha run k8s common script to have uniformity across the script.
> gha: Fix indentation in gha run k8s common

- tests/metrics/time/launch_times.sh
This PR updates the launch times scripts by improving the variable definition as well as trying to use the same format across all the script.
> metrics: Update launch times script

- tests/integration/kubernetes/confidential_common.sh
This PR fixes the indentation in the confidential common script.
> tests: Fix indentation in confidential common script

- tests/integration/kubernetes/run_kubernetes_tests.sh
The k8s test suite halts on the first failure, i.e., failing-fast. This isn't the behavior that we used to see when running tests on Jenkins and it seems that running the entire test suite is still the most productive way. So this disable fail-fast by default.
However, if you still wish to run on fail-fast mode then just export K8S_TEST_FAIL_FAST=yes in your environment.
Fixes: #9697
> tests/k8s: disable "fail-fast" behavior by default

- src/agent/src/device.rs
The `update_env_pci()` function need the PCI address mapping to translate the host PCI address to guest PCI address in below environment variables:
- `PCIDEVICE_<prefix>_<resource-name>_INFO`
- `PCIDEVICE_<prefix>_<resource-name>`
Fixes https://github.com/kata-containers/kata-containers/issues/9614
> agent: collect PCI address mapping for both vfio-pci-gk and vfio-pci device

- src/agent/rustjail/src/container.rs
Fixes: #9267
The doc states we have support for all lifecycle hooks. There are still some missing. This is the first issue regarding the CreateContainer hook which is run before pivot_root but after prestart and createruntime
> kata-agent: CreateContainer Hook

- tests/functional/kata-deploy/kata-deploy.bats
- tests/functional/kata-deploy/run-kata-deploy-tests.sh
- tests/integration/kubernetes/gha-run.sh
- tests/integration/kubernetes/run_kubernetes_tests.sh
- tools/packaging/kata-deploy/kata-cleanup/overlays/k0s/kustomization.yaml
- tools/packaging/kata-deploy/kata-cleanup/overlays/k0s/mount_k0s_conf.yaml
- tools/packaging/kata-deploy/scripts/kata-deploy.sh
Please, see each commit for more details.
> kata-deploy / kata-cleanup / ci: Fixes and improvements to kata-deploy / kata-cleanup and its usage in the CI

- tools/packaging/static-build/coco-guest-components/Dockerfile
- tools/packaging/static-build/coco-guest-components/build-static-coco-guest-components.sh
- tools/packaging/static-build/coco-guest-components/build.sh
Build guest-components without sudo docker this is not needed. This is part 2 of N
> ci: guest-components without sudo

- tests/metrics/density/memory_usage.sh
This PR improves general format like variable definition to have uniformity across the memory usage script.
> metrics: Improve variable definition in memory usage script

- tools/packaging/static-build/tools/Dockerfile
- tools/packaging/static-build/tools/build-static-tools.sh
- tools/packaging/static-build/tools/build.sh
Build tools without sudo docker this is not needed. This is part 7 of N
> ci: tools no sudo

- tools/packaging/static-build/agent/Dockerfile
- tools/packaging/static-build/agent/build-static-agent.sh
- tools/packaging/static-build/agent/build.sh
Build agent without sudo docker this is not needed. This is part 3 of N
> ci: build agent without sudo

- tools/packaging/static-build/virtiofsd/build-static-virtiofsd.sh
- tools/packaging/static-build/virtiofsd/build.sh
- tools/packaging/static-build/virtiofsd/gnu/Dockerfile
- tools/packaging/static-build/virtiofsd/musl/Dockerfile
build virtiofsd without sudo docker this is not needed. This is part 8 of N
> ci: virtiofsd no sudo

- tools/packaging/static-build/pause-image/build-static-pause-image.sh
- tools/packaging/static-build/pause-image/build.sh
Build pause-image without sudo docker this is not needed. This is part 5 of N
> ci: pause-image no sudo

- ci/lib.sh
- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
- tools/packaging/scripts/lib.sh
- tools/packaging/static-build/cloud-hypervisor/build-static-clh.sh
Now with the sudo less build we should be good
to remove those hacks.
> ci: Remove all git config safe.directory

- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
- tools/packaging/kata-deploy/local-build/kata-deploy-build-and-upload-payload.sh
build/push/manage aritfacts without sudo
> ci: kata-deploy no sudo

- docs/threat-model/threat-model.md
We're missing several topics in the current threat model lets update.
Fixes: #8943
> threat-model: Add VFIO, ACPI and KVM/VMM threat-model descriptions

- tools/osbuilder/image-builder/image_builder.sh
- tools/osbuilder/initrd-builder/initrd_builder.sh
- tools/packaging/guest-image/build_image.sh
The image build needs special handling since we're doing a lot of privileged operations.
> ci: remove sudo and make sure artifacts is owned by user

- tests/integration/kubernetes/confidential_kbs.sh
- tests/integration/kubernetes/k8s-confidential-attestation.bats
Let's enable the CDH tests for TDX.
> ci: kbs: Enable CDH tests for TDX

- tests/common.bash
This PR fixes the indentation in common script.
> tests: Fix indentation in common script

- src/libs/kata-types/src/capabilities.rs
- src/libs/kata-types/tests/texture/configuration-anno-0.toml
- src/libs/kata-types/tests/texture/configuration-anno-1.toml
> kata-types: fix bug in kata-types several test cases

- tests/integration/kubernetes/setup.sh
This PR makes general improvements like definition of variables and the use of them to improve the general setup script for kubernetes tests.
> tests: setup: Improve setup script for kubernetes tests

- tests/integration/kubernetes/confidential_kbs.sh
This PR uses the nodeport deployment from upstream trustee.
To ensure our deployment is as close to upstream trustee replace
the custom nodeport handling and replace it with nodeport
kustomized flavour from the trustee project.
> tests: kbs: Use nodeport deployment from upstream trustee

- src/dragonball/src/address_space_manager.rs
- src/dragonball/src/device_manager/mod.rs
- versions.yaml
- Bump the rust version to 1.75.0 as agreed on in the AC meeting
> versions: Bump rust toolchain

- src/tools/genpolicy/src/registry.rs
registries
Adding back changes from
77540503f9b38ac75ead13e4bde6c07ff75ba311.
Fixes: #9008
> genpolicy: add back support for insecure

- .github/workflows/build-kata-static-tarball-ppc64le.yaml
Now lets clean up the ppc64 build, do not use sudo.
> ci: gha no sudo ppc64

- src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
This is mostly just a small batch of logging and consistency improvements.
> runtime-rs: adjust qemu vm shutdown behaviour

- src/runtime/virtcontainers/kata_agent.go
Move the `sandbox.agent.setPolicy` call out of the remoteHypervisor if, block, so we can use the policy implementation on peer pods
> runtime: Support policy in remote hypervisor

- src/tools/genpolicy/rules.rego
Reject CreateContainerRequest field values that are not tested by Kata CI and that might impact the confidentiality of CoCo Guests.
This change uses a "better safe than sorry" approach to untested fields. It is very possible that in the future we'll encounter
reasonable use cases that will either:
- Show that some of these fields are benign and don't have to be verified by Policy, or
- Show that Policy should verify legitimate values of these fields
These are the new CreateContainerRequest Policy rules:
count(input.shared_mounts) == 0
is_null(input.string_user)
i_oci := input.OCI
is_null(i_oci.Hooks)
is_null(i_oci.Linux.Seccomp)
is_null(i_oci.Solaris)
is_null(i_oci.Windows)
i_linux := i_oci.Linux
count(i_linux.GIDMappings) == 0
count(i_linux.MountLabel) == 0 …
> genpolicy: reject untested CreateContainer field values

- .github/workflows/build-kata-static-tarball-arm64.yaml
Now lets clean up the arm64 build, do not use sudo.
> ci: gha no sudo arm64

- tests/functional/kata-monitor/kata-monitor-tests.sh
This PR increases the timeout to crictl calls on kata monitor tests to avoid to hit issues every now and avoid random failures. This PR is very similar to PR #7640.
> tests: Increase timeout to crictl calls on kata monitor tests

- src/runtime/config/configuration-qemu-nvidia-gpu-snp.toml.in
Add the correct separator for replacement
> gpu: Missing separator

- tests/metrics/density/memory_usage.sh
This PR removes the common_init function call from the memory usage script to eliminate duplicate checking that is also done from the init_env function.
It also eliminates duplicaction of nested conditionals.
Fixes: #9984
> metrics: Remove duplicate check of processes from memory test.

- docs/how-to/how-to-run-kata-containers-with-SNP-VMs.md
- tests/cmd/check-spelling/data/projects.txt
- tests/cmd/check-spelling/kata-dictionary.dic
- tests/integration/kubernetes/k8s-confidential-attestation.bats
This tests the attestation of SNP guest. It depends upon the PR #9806.
> gha: enable SNP attestation

- src/agent/README.md
- src/agent/src/config.rs
- src/agent/src/image.rs
- tests/integration/kubernetes/k8s-confidential-attestation.bats
- tests/integration/kubernetes/k8s-guest-pull-image-authenticated.bats
- tests/integration/kubernetes/k8s-guest-pull-image-encrypted.bats
- tests/integration/kubernetes/k8s-liveness-probes.bats
- tests/integration/kubernetes/k8s-sealed-secret.bats
- tests/integration/kubernetes/run_kubernetes_tests.sh
Add authenticated registry support for guest-pull
Fixes: #8122
> Support for registry authentication in guest pull

- tests/integration/kubernetes/gha-run.sh
- tests/integration/kubernetes/k8s-policy-pvc.bats
- tests/integration/kubernetes/tests_common.sh
Enable autogenerated policy testing on SEV and SEV-SNP
> gha: enable autogenerated policy testing on SEV and SEV-SNP

- src/kata-opa/allow-all-except-exec-process.rego
- src/kata-opa/allow-all.rego
- src/kata-opa/allow-set-policy.rego
- tests/integration/kubernetes/setup.sh
- tools/osbuilder/rootfs-builder/rootfs.sh
environment variable
* Set policy file via env var
* Add restrictive policy file to kata-opa folder
* Change restrictive policy file name
* Change relative default path location
Upstreaming from https://github.com/microsoft/kata-containers/pull/123
> tools: Allow setting policy rego file via

- docs/design/kata-nydus-design.md
This PR updates the url links in the kata nydus document.
> docs: Update url links in kata nydus document

- src/libs/kata-types/src/config/hypervisor/dragonball.rs
- src/runtime-rs/config/configuration-dragonball.toml.in
- src/runtime-rs/crates/hypervisor/src/dragonball/inner.rs
- src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
enable the dragonball support initrd.
Fixes: #10023
> runtime-rs: enable dragonball hypervisor support initrd

- src/agent/src/policy.rs
- tests/integration/kubernetes/k8s-policy-hard-coded.bats
1. Use the new value of AllowRequestsFailingPolicy after setting up a new Policy. Before this change, the only way to enable AllowRequestsFailingPolicy was to change the default Policy file, built into the Guest rootfs image.
2. Ignore errors returned by regorus while evaluating Policy rules, if AllowRequestsFailingPolicy was enabled. For example, trying to evaluate the UpdateInterfaceRequest rules using a policy that didn't define any UpdateInterfaceRequest rules results in a "not found" error from regorus. Allow AllowRequestsFailingPolicy := true to bypass that error.
3. Add simple CI test for AllowRequestsFailingPolicy.
These changes are restoring functionality that was broken recently by commmit df23eb09a6b7a229f5c099d8a04b799a97ced141.
> agent: fix the AllowRequestsFailingPolicy functionality

- src/tools/genpolicy/rules.rego
Cherry pick from https://github.com/microsoft/kata-containers/pull/140
> genpolicy: reject create custom hook settings

- tests/stability/kubernetes_stability.sh
- tests/stability/runtimeclass_workloads/stability-test.yaml
This PR adds a k8s stability test that will be part of the CoCo Kata stability tests that will run weekly.
> tests: Add kubernetes stability test

- src/tools/genpolicy/src/cronjob.rs
- src/tools/genpolicy/src/main.rs
- src/tools/genpolicy/src/yaml.rs
- tests/integration/kubernetes/k8s-cron-job.bats
- tests/integration/kubernetes/run_kubernetes_tests.sh
- tests/integration/kubernetes/runtimeclass_workloads/cron-job.yaml
- tests/integration/kubernetes/setup.sh
* Add support for cron jobs
* Add simple test for cron job support
> genpolicy: Add support for cron jobs

- docs/how-to/how-to-pull-images-in-guest-with-kata.md
- src/agent/Cargo.lock
- src/agent/Cargo.toml
- src/agent/README.md
- src/agent/src/cdh.rs
- src/agent/src/config.rs
- src/agent/src/image.rs
- src/agent/src/rpc.rs
- src/libs/protocols/build.rs
- src/libs/protocols/protos/confidential_data_hub.proto
- src/libs/protocols/src/lib.rs
- tests/integration/kubernetes/confidential_common.sh
- tests/integration/kubernetes/k8s-guest-pull-image-encrypted.bats
- tests/integration/kubernetes/k8s-guest-pull-image.bats
- tests/integration/kubernetes/runtimeclass_workloads/confidential/trusted-storage.yaml.in
- tests/integration/kubernetes/runtimeclass_workloads/pod-guest-pull-in-trusted-storage.yaml.in
- tools/osbuilder/rootfs-builder/rootfs.sh
- tools/osbuilder/rootfs-builder/scripts/init_trusted_storage.sh
- versions.yaml
Mostly cherry-pick https://github.com/kata-containers/kata-containers/pull/4885 from CCv0
Fixes: #8142
> Trusted image storage

- src/tools/genpolicy/src/yaml.rs
> genpolicy: ignore Role resource

- tests/integration/kubernetes/runtimeclass_workloads/k8s-policy-rc.yaml
- tests/integration/kubernetes/runtimeclass_workloads/lifecycle-events.yaml
- tests/integration/kubernetes/runtimeclass_workloads/nginx-deployment.yaml
- tests/integration/kubernetes/runtimeclass_workloads/replication-controller.yaml
The previous ones are gone, so let's switch to our own multi arch one.
> ci: k8s: Replace nginx alpine images

- src/runtime/virtcontainers/fs_share_linux.go
Fix https://github.com/kata-containers/kata-containers/issues/9986
This PR resolves the default kubelet root dir symbolic link and uses it as the absolute path for the fs watcher
> runtime: Files are not synced between host and guest VMs

- tests/integration/kubernetes/confidential_kbs.sh
Otherwise we may have tests failing due to the resource not being created yet.
> ci: Ensure the KBS resources are created

- .github/workflows/ci-coco-stability.yaml
- .github/workflows/run-kata-coco-stability-tests.yaml
- tests/stability/gha-stability-run.sh
This PR adds the k8s stability Kata CoCo GHA workflow to run weekly the k8s stability tests.
> gha: Add k8s stability Kata CoCo GHA workflow

- tests/common.bash
- tests/integration/kubernetes/gha-run.sh
- versions.yaml
We're doing this as we're taking a safer path, and working on the fixes without the need to block the CI.
Those 2 commits will be re-reverted as soon as the release is out, and will come in a series including fixes from @wainersm and myself.
> ci: Let's temporarily revert the helm charts usage in our CI

- .github/workflows/commit-message-check.yaml
`Reapply "` should be taken into sonsideration as well.
> ci: commit-message-check: Take re-revert into consideration

- src/agent/src/console.rs
when use debug console, the shell run in child process may not be exited, in some scenes.
eg. directly Ctrl-C in the host to terminate the kata-runtime process, that will block the task handling the console connection，while waiting for the child to exit.
as shown in the figure below, there are two kata-agent child processes(217, 1094) whose top stacks are blocked in the do_wait call.
There is another problem here. 
compared with the normal situation, there should be a thread on the top of the stack that is blocked in the ep_poll call, waiting for new requests to come in.
As you can see from the abnormal  kata-agent threads' stack, none of the threads is ep_poll, causing all vsocks of kata-agent to be unable to respond to new requests.
Kill those two child processes, and the kata-agent …
> agent: kill child process when console socket closed

- src/runtime/virtcontainers/network_linux.go
PhysicalEndpoint unbinds its VF interface and rebinds it as a VFIO device, then cold-plugs the VFIO device into the guest kernel.
When `cold_plug_vfio` is set to "no-port", cold-plugging the VFIO device will fail.
This change checks if `cold_plug_vfio` is enabled before creating PhysicalEndpoint to avoid unnecessary VFIO rebind operations.
Fixes: #10162
> runtime: check if  cold_plug_vfio is enabled before create PhysicalEndpoint

- .github/workflows/PR-wip-checks.yaml
- .github/workflows/add-issues-to-project.yaml
- .github/workflows/add-pr-sizing-label.yaml
- .github/workflows/build-kata-static-tarball-amd64.yaml
- .github/workflows/cargo-deny-runner.yaml
- .github/workflows/ci.yaml
- .github/workflows/cleanup-resources.yaml
- .github/workflows/commit-message-check.yaml
- .github/workflows/kata-runtime-classes-sync.yaml
- .github/workflows/move-issues-to-in-progress.yaml
- .github/workflows/payload-after-push.yaml
- .github/workflows/publish-kata-deploy-payload-amd64.yaml
- .github/workflows/release-amd64.yaml
- .github/workflows/release.yaml
- .github/workflows/run-k8s-tests-on-aks.yaml
- .github/workflows/run-kata-coco-tests.yaml
- .github/workflows/run-kata-deploy-tests-on-aks.yaml
- .github/workflows/run-kata-monitor-tests.yaml
- .github/workflows/run-runk-tests.yaml
- .github/workflows/stale.yaml
- .github/workflows/static-checks.yaml
Follow up to #9960 and #10007.
Tracked in #9940.
> ci: Transition GARM tests to free runners, pt. III

- src/agent/Cargo.lock
- src/agent/Cargo.toml
As this brings in proper support to handle gzip whiteouts.
> agent: Update image-rs to 02af65abc

- src/runtime/pkg/katautils/config.go
> runtime: fix bad default machine_type for remote hypervisor

- src/tools/genpolicy/src/mount_and_storage.rs
- tests/integration/kubernetes/runtimeclass_workloads/k8s-policy-rc.yaml
Support readonly hostpath and readonly  emptyDir mount
> genpolicy: support readonly hostpath

- src/tools/genpolicy/src/yaml.rs
> genpolicy: add support for PodDisruptionBudget yaml

- src/runtime/pkg/govmm/qemu/qemu.go
This is a simple and basic pre-req for the initData work that @Xynnn007 is doing, and it'll simplify his life a little bit.
> runtime: qemu: tdx: Add support for setting mrconfigid / mrowner / mrownerconfig

- src/agent/Cargo.lock
- src/agent/Cargo.toml
- tests/integration/kubernetes/k8s-guest-pull-image-encrypted.bats
- versions.yaml
Please, see each commit for a better explanation.
> Bump guest-components / trustee to a version that supports ITA

- tests/stability/gha-stability-run.sh
- tests/stability/kubernetes_soak_test.sh
This PR enables the stressng k8s stability test for Kata CoCo CI.
> tests: Enable stressng k8s stability test for Kata CoCo CI

- tests/integration/kubernetes/gha-run.sh
Kata-deploy often fails due to a transiently unreachable k8s cluster for the qemu-coco-dev test on s390x.
```
Final kata-deploy manifests used in the test
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/ansible/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/ansible/.kube/config
install.go:222: [debug] Original chart version: ""
install.go:239: [debug] CHART PATH: /home/ansible/gha-runner/_layout/_work/kata-containers/kata-containers/tools/packaging/kata-deploy/helm-chart/kata-deploy
Error: INSTALLATION FAILED: Kubernetes cluster unreachable: Get "https://127.0.0.1:6443/version": dial tcp 127.0.0.1:6443: connect: connection refused
helm.go:84: [debug] Get "https://127.0.0.1:6443/version": …
```
> tests: Introduce retry mechanism for helm install

- tests/integration/cri-containerd/integration-tests.sh
This PR fixes the indentation in the cri containerd tests as we have in several places a misalignment in the script.
> tests: Fix indentation in the cri containerd tests

- src/agent/Makefile
- src/agent/README.md
- src/agent/src/config.rs
- src/agent/src/image.rs
- tests/integration/kubernetes/confidential_common.sh
- tests/integration/kubernetes/k8s-confidential-attestation.bats
- tests/integration/kubernetes/k8s-guest-pull-image-authenticated.bats
- tests/integration/kubernetes/k8s-guest-pull-image-encrypted.bats
- tests/integration/kubernetes/k8s-guest-pull-image-signature.bats
- tests/integration/kubernetes/k8s-guest-pull-image.bats
- tests/integration/kubernetes/k8s-sealed-secret.bats
- tests/integration/kubernetes/run_kubernetes_tests.sh
- tests/integration/kubernetes/tests_common.sh
Close #8120.
The test commit has not been testsed and I just followed what was coded in https://github.com/kata-containers/kata-containers/pull/9904.
On top of #9904.
Let's continue this after #9904 is merged.
cc @stevenhorsman
> Merge to main: supporting pull cosign signed images

- ci/install_libseccomp.sh
This PR fixes the indentation of the install libseccomp script.
> ci: Fix indentation of install libseccomp script

- src/tools/genpolicy/src/daemon_set.rs
- src/tools/genpolicy/src/deployment.rs
- src/tools/genpolicy/src/job.rs
- src/tools/genpolicy/src/pod.rs
- src/tools/genpolicy/src/replica_set.rs
- src/tools/genpolicy/src/replication_controller.rs
- src/tools/genpolicy/src/stateful_set.rs
- src/tools/genpolicy/src/yaml.rs
- tests/integration/kubernetes/k8s-policy-deployment.bats
- tests/integration/kubernetes/k8s-policy-job.bats
- tests/integration/kubernetes/k8s-policy-rc.bats
- tests/integration/kubernetes/runtimeclass_workloads/k8s-policy-deployment.yaml
- tests/integration/kubernetes/runtimeclass_workloads/k8s-policy-rc.yaml
Get the UID value from PodSecurityContext for other k8s resource types too, not just for Pods.
> genpolicy: get UID from PodSecurityContext

- src/agent/rustjail/src/cgroups/fs/mod.rs
kata-agent incorrectly reports CPU time for cgroup v2, causing 1000x underreporting.
For cgroup v2, kata-agent reads the cpu.stat file, which reports the time consumed by the processes in the cgroup in µs.
However, there was a bug in kata-agent where it returned this value in µs without converting it to ns.
This commit adds the necessary µs to ns conversion for cgroup v2, aligning it with v1 behavior and kata-shim's expectations.
This fixes https://github.com/kata-containers/kata-containers/issues/10278
Signed-off-by: Alex Man <alexman@stripe.com>
> agent: Fix CPU usage reporting for cgroup v2 in kata-agent

- docs/Release-Process.md
- Reflect the need to update the versions in the Helm Chart
- Add the lock branch instruction
- Add clarity about the permissions needed to complete tasks
> doc: Update the release process

- ci/openshift-ci/cluster/deploy_webhook.sh
in b9d88f74edc463dc14ef52135c592fbb6bd5c792 the `runtime_class` CM was added which overrides the one we previously set. Let's reorder our logic to first deploy webhook and then override the default CM in order to use the one we really want.
Since we need to change dirs we also have to use realpath to ensure the files are located well.
Related to: https://github.com/kata-containers/kata-containers/pull/10329
> ci: Reorder webhook deployment

- tests/integration/kubernetes/run_kubernetes_tests.sh
It was observed that the custom node debugger pod is not cleaned up when a test times out.
https://github.com/kata-containers/kata-containers/actions/runs/11037706754/job/30659802220
This PR ensures the pod is cleaned up by triggering the cleanup on EXIT, preventing any debugger pods from being left behind.
> tests: Delete custom node debugger pod on EXIT

- src/runtime-rs/crates/hypervisor/src/ch/inner.rs
- src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
- src/runtime-rs/crates/hypervisor/src/ch/mod.rs
- src/runtime-rs/crates/hypervisor/src/firecracker/inner.rs
- src/runtime-rs/crates/hypervisor/src/firecracker/inner_hypervisor.rs
- src/runtime-rs/crates/hypervisor/src/firecracker/mod.rs
- src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
- src/runtime-rs/crates/hypervisor/src/qemu/mod.rs
- src/runtime-rs/crates/runtimes/common/src/error.rs
- src/runtime-rs/crates/runtimes/common/src/types/mod.rs
- src/runtime-rs/crates/runtimes/common/src/types/trans_from_shim.rs
- src/runtime-rs/crates/runtimes/common/src/types/trans_into_shim.rs
- src/runtime-rs/crates/runtimes/src/manager.rs
- src/runtime-rs/crates/service/src/manager.rs
- src/runtime-rs/crates/service/src/task_service.rs
- src/runtime-rs/crates/shim-ctl/src/main.rs
Some prepared work for incoming sandbox api support, such as:
sandbox: fix the issue of hypervisor's wait_vm
runtime-rs: rename the Request/Response to TaskRequest/TaskResponse
sandbox: rename the task_service to service
> Some prepared work for sandbox api support

- ci/openshift-ci/bisect-range.sh
The quay.io registry returns the tags sorted alphabetically and doesn't seem to provide a way to sort it by age. Let's use not really efficient but functional way to sort it by going through all merge commits (as we only publish images for them) of the current git listing those that are present in the quay repo.
> ci.ocp: Sort images according to git

- tests/integration/kubernetes/tests_common.sh
The behavior of **Kata CI** doesn't change.
For **local testing** using kubernetes/gha-run.sh and AUTO_GENERATE_POLICY=yes:
1. Before these changes users were forced to use:
- SEV, SNP, or TDX guests, or
- KATA_HOST_OS=cbl-mariner
2. After these changes users can also use other platforms that are configured with "shared_fs = virtio-fs" - e.g.,
- KATA_HOST_OS=ubuntu + KATA_HYPERVISOR=qemu
> tests: k8s: AUTO_GENERATE_POLICY=yes for local testing

- src/agent/src/cdh.rs
- src/agent/src/main.rs
- src/agent/src/rpc.rs
- tests/integration/kubernetes/k8s-sealed-secret.bats
- tests/integration/kubernetes/runtimeclass_workloads/pod-sealed-secret-as-file.yaml
This PR brings sealed secret functionality as volume to main.  This functionality was originally implemented by @LindaYu17
Please see the individual commits for details. 
Fixes: #8123
> Support Confidential Sealed Secrets (as volume) 

- src/agent/src/cdh.rs
The root cause is that the CDH client is a global variable, and unit tests `test_unseal_env` and `test_unseal_file` share this lock-free global variable, leading to resource contention and destruction. Merging the two unit tests into one `test_sealed_secret` will resolve this issue. Original commit: https://github.com/kata-containers/kata-containers/commit/31e09058af68a2f7e9c9685f505c7cad53148c8d
Fixes: #10403
> agent:cdh: fix unit tests about sealed secret

- src/agent/src/config.rs
Use rstest for unit test rather than TestData arrays where possible to make the code more compact, easier to read and open the possibility to enhance test cases with a description more easily.
> agent: config: Use rstest for unit tests

- ci/README.md
This PR updates the CI documentation referring to the several tests and in which kind of instances is running them.
> docs: Update CI documentation

- src/runtime-rs/crates/hypervisor/src/qemu/cmdline_generator.rs
Semantics are lifted straight out of the go runtime for compatibility. We introduce DeviceVirtioScsi to represent a virtio-scsi device and instantiate it if block device driver in the configuration file is set to virtio-scsi.  We also introduce ObjectIoThread which is instantiated if the configuration file additionally enables iothreads.
> runtime-rs: support virtio-scsi device in qemu-rs

- tests/kata-doc-to-script.sh
This reverts commit 093a6fd54218ae17ff1531e8e18fff96b6c17f13. as it is breaking the static checks
> Revert "tests: Add trap statement in kata doc script"

- src/agent/src/image.rs
- src/agent/src/rpc.rs
The PR replaces the OCI process spec of the pause container with the spec of
the guest provided pause bundle.
Fixes: https://github.com/kata-containers/kata-containers/issues/10537
> agent: overwrite OCI process spec when overwriting pause image

- .github/workflows/run-kata-coco-tests.yaml
- tests/integration/kubernetes/k8s-confidential-attestation.bats
- tests/integration/kubernetes/k8s-guest-pull-image-authenticated.bats
- tests/integration/kubernetes/k8s-guest-pull-image-encrypted.bats
- tests/integration/kubernetes/k8s-guest-pull-image-signature.bats
We've debugged the SNP Node and we
wish to test the fixes on GHA.
This PR will undo [PR#10539](https://github.com/kata-containers/kata-containers/pull/10539)
> ci: Re-enable SNP CI

- tools/testing/gatekeeper/required-tests.yaml
Synchronize the required jobs with the current GH setting. Note due to way it's executed we should actually see the result directly in this PR...
> ci: Required jobs

- tools/osbuilder/rootfs-builder/nvidia/nvidia_chroot.sh
- tools/osbuilder/rootfs-builder/nvidia/nvidia_rootfs.sh
- tools/osbuilder/rootfs-builder/rootfs.sh
- tools/packaging/kata-deploy/local-build/Makefile
- tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
- tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh
- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
With each release make sure we ship a GPU enabled rootfs/initrd
Fixes: #6554
Depends: ~~#9480~~, ~~#9584~~
> gpu: NVIDIA GPU initrd/image build

- src/runtime-rs/crates/hypervisor/src/device/driver/vfio.rs
> runtime-rs: fix vfio device name combination issue

- .github/workflows/build-kata-static-tarball-amd64.yaml
- .github/workflows/build-kata-static-tarball-arm64.yaml
- .github/workflows/build-kata-static-tarball-ppc64le.yaml
- .github/workflows/build-kata-static-tarball-s390x.yaml
- tools/packaging/kata-deploy/local-build/Makefile
- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
See commits for more information.
> Unbreak the CI, 3rd attempt

- src/runtime-rs/crates/hypervisor/src/qemu/cmdline_generator.rs
To explicitly specify a device number on the QEMU command line (e.g. `devno=fe.0.0000`) for the following devices using the CCW transport on s390x:
- SerialDevice
- BlockDevice
- VhostUserDevice
- SCSIController
- VSOCKDevice
this PR introduces a new structure `CcwSubChannel` and leverages it to construct a required QEMU command line.
This resolves the 1st part of #10573. For details, please check out the issue.
> Add subchannel support to qemu-runtime-rs for s390x

- src/runtime/virtcontainers/pkg/agent/protocols/client/client.go
With full debug logging enabled there might be around 1,500 redials so log just ~15 of these redials to avoid flooding the log.
> runtime: skip logging some of the dial errors

- src/runtime/virtcontainers/clh.go
This commit sets memory config `shared` to false in cloud hypervisor when creating vm with shared_fs=None && hugePages = false.
Fixes #10547
> runtime: Set memory config shared=false when shared_fs=None in CLH.

- tests/integration/kubernetes/k8s-confidential-attestation.bats
- tests/integration/kubernetes/k8s-guest-pull-image-authenticated.bats
- tests/integration/kubernetes/k8s-guest-pull-image-encrypted.bats
- tests/integration/kubernetes/k8s-guest-pull-image-signature.bats
This reverts commit 2242aee099765340024ee2411a07826539835e26.
Add the skipped tests back for the SNP CI.
> Revert "ci: Skip the failing tests in SNP"

- tools/packaging/scripts/configure-hypervisor.sh
- tools/packaging/static-build/qemu/Dockerfile
- tools/packaging/static-build/qemu/build-base-qemu.sh
- tools/packaging/static-build/qemu/build-qemu.sh
- versions.yaml
New features added in the major release have been disabled for now.
Deprecated features related to live-block-migration and avx512f have been removed.
Plan is to test the newly added features for performance and add them as
required in the future.
The major release includes quite a few bug fixes and improvments related
to storage and memory:
Block improvements:
The block layer is now thread safe and multiple I/O threads can send I/O
requests to the same disk image. virtio-blk can be configured to make use
of this and improve scalability
Fixed I/O errors in the libblkio based block drivers caused by incorrect
memory alignment of bounce buffers
In 'blklogwrites', potential log corruption bugs were fixed related to
concurrent requests and to write zeroes operations
Memory improments:
Memory …
> qemu: Upgrade qemu 9.1.2

- ci/README.md
- tests/cmd/check-spelling/kata-dictionary.dic
Add information about what required jobs are and
our initial guidelines for how jobs are eligible for being made required, or non-required
> doc: Add required jobs info

- tools/packaging/static-build/coco-guest-components/build-static-coco-guest-components.sh
- versions.yaml
We still have one change to get into Trustee, but let's see if bumping things will work
> Update Trustee and Guest Components

- tests/gha-run-k8s-common.sh
Because az client restricts the name to be less than 64 characters. In
some cases (e.g. KATA_HYPERVISOR=qemu-runtime-rs) the generated name
will exceed the limit. This changed the function to shorten the name:
* SHA1 is computed from metadata then compound the cluster's name
* metadata as plain-text are passed as --tags
Fixes: #9850
> tests/gha-run-k8s-common: shorten AKS cluster name

- .github/workflows/build-kata-static-tarball-amd64.yaml
- .github/workflows/build-kata-static-tarball-arm64.yaml
Reverts kata-containers/kata-containers#10764
> Revert "gpu: Add rootfs target amd64/arm64"

- .github/workflows/gatekeeper.yaml
- .github/workflows/run-k8s-tests-on-amd64.yaml
- .github/workflows/run-k8s-tests-on-ppc64le.yaml
- .github/workflows/run-k8s-tests-on-zvsi.yaml
- .github/workflows/run-kata-coco-tests.yaml
- .github/workflows/run-kata-deploy-tests-on-garm.yaml
- tests/integration/kubernetes/confidential_common.sh
- tools/testing/gatekeeper/jobs.py
> ci: Unify on `$GH_PR_NUMBER` environment variable

- src/agent/Cargo.lock
- src/agent/Cargo.toml
- src/libs/Cargo.lock
- src/libs/protocols/Cargo.toml
- src/runtime-rs/Cargo.lock
- src/runtime-rs/crates/agent/Cargo.toml
- src/runtime-rs/crates/hypervisor/Cargo.toml
- src/runtime-rs/crates/runtimes/common/Cargo.toml
- src/runtime-rs/crates/service/Cargo.toml
- src/tools/agent-ctl/Cargo.lock
- src/tools/agent-ctl/Cargo.toml
- src/tools/genpolicy/Cargo.lock
- src/tools/kata-ctl/Cargo.lock
- src/tools/kata-ctl/Cargo.toml
This PR updates the ttrpc crate to include the fix from @msanft (who was the one who did the hard work here ;-)), and also bumps the kernel version (so we can easily test it on our side).
> agent: Update ttrpc to include the fix for connectivity issues

- tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in
- tools/osbuilder/rootfs-builder/ubuntu/config.sh
- tools/osbuilder/rootfs-builder/ubuntu/rootfs_lib.sh
- tools/packaging/guest-image/build_image.sh
- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
- versions.yaml
All the commits before that one were needed in order to do the bump.
Every single day, a new yak to shave.
> versions: Bump Ubuntu base image & initrd

- tools/osbuilder/rootfs-builder/nvidia/nvidia_chroot.sh
- tools/osbuilder/rootfs-builder/nvidia/nvidia_rootfs.sh
- tools/osbuilder/rootfs-builder/rootfs.sh
- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Besides latest and lts options add an option to specify the exact driver version.
> gpu: Add driver version selection

- .github/workflows/darwin-tests.yaml
- .github/workflows/docs-url-alive-check.yaml
- versions.yaml
Bump golang versions so we are more up-to-date and have the extra security fixes
> versions: Bump golang version

- tools/osbuilder/rootfs-builder/nvidia/nvidia_chroot.sh
- tools/osbuilder/rootfs-builder/nvidia/nvidia_rootfs.sh
- tools/osbuilder/rootfs-builder/rootfs.sh
Various fixes to make the rootfs build on aarch64 and x86_64
> gpu: Fix arm64 build

- .github/workflows/shellcheck.yaml
We need to start to fix our scripts. Lets run shellcheck and see what needs to be reworked.
> gha: Add shellcheck

- .github/workflows/build-kata-static-tarball-amd64.yaml
Start bulding the confidential initrd.
> gpu: enable confidential initrd build

- tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
- tools/packaging/static-build/agent/Dockerfile
- tools/packaging/static-build/coco-guest-components/Dockerfile
- tools/packaging/static-build/initramfs/Dockerfile
- tools/packaging/static-build/ovmf/Dockerfile
- tools/packaging/static-build/shim-v2/Dockerfile
- tools/packaging/static-build/tools/Dockerfile
As Ubuntu 20.04 will reach its EOL in April.
> packaging: Move builds to Ubuntu 22.04

- tests/integration/kubernetes/k8s-block-volume.bats
The block volume test has failed on 10/10 nightlies and all the PRs I've seen, so skip it until it can be assessed.
See #10873
> tests: Skip block volume test on fc, stratovirt

- .github/workflows/build-kata-static-tarball-arm64.yaml
We need to make sure the release does not have any residual binaries left for the release payload
> release: Remove artifacts for release

- .github/workflows/build-kata-static-tarball-amd64.yaml
> QEMU TDX experimental workflow

- tests/gha-run-k8s-common.sh
- versions.yaml
k0s to see if that resolves the crio issues
> ci: k8s: Pin k0s version to get cri-o tests back working

- tests/integration/kubernetes/k8s-guest-pull-image.bats
- tools/osbuilder/initrd-builder/initrd_builder.sh
- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
- versions.yaml
20.04 will be EOL this year.
Fixes: #10802
> versions: update confidential initrd to 22.04

- shellcheckrc
Let's have common rules over all shell files.
> ci: Add shellcheckrc

- .github/workflows/ci.yaml
- .github/workflows/run-metrics.yaml
- tests/common.bash
- tests/integration/kubernetes/gha-run.sh
- tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
- tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
- tests/metrics/gha-run.sh
- tests/metrics/lib/common.bash
- tests/metrics/network/iperf3_kubernetes/k8s-network-metrics-iperf3.sh
- tests/metrics/network/iperf3_kubernetes/runtimeclass_workloads/iperf3-daemonset.yaml
- tests/metrics/network/iperf3_kubernetes/runtimeclass_workloads/iperf3-deployment.yaml
- tests/metrics/network/latency_kubernetes/latency-network.sh
Various fixes to the metrics test and re-working the job to make more sense and work properly
> Rework and fix metrics issues

- src/runtime-rs/config/configuration-cloud-hypervisor.toml.in
- src/runtime-rs/config/configuration-qemu-runtime-rs.toml.in
Add mem-agent config to clh and qemu config file.
Fixes: #10996
> runtime-rs: Add mem-agent config to clh and qemu config file

- tests/integration/kubernetes/runtimeclass_workloads/confidential/unencrypted/Dockerfile
Need to set correct permissions for ssh directories and files
Fixes: #11005
> tests: fix confidential ssh Dockerfile

- tests/integration/kubernetes/tests_common.sh
Retry "kubectl exec" a few times if it unexpectedly produced an empty output string.
This is an attempt to work around test failures similar to:
https://github.com/kata-containers/kata-containers/actions/runs/13840930994/job/38730153687?pr=10983
not ok 1 Environment variables
(from function `grep_pod_exec_output' in file tests_common.sh, line 394,
in test file k8s-env.bats, line 36)
`grep_pod_exec_output "${pod_name}" "HOST_IP=\([0-9]\+\(\.\|$\)\)\{4\}" "${exec_command[@]}"' failed
That test obtained correct ouput from "sh -c printenv" one time, but the second execution of the same command returned an empty output string.
> tests: k8s: retry "kubectl exec" on empty output

- tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
- tests/metrics/gha-run.sh
- tests/metrics/network/iperf3_kubernetes/k8s-network-metrics-iperf3.sh
A few different improvements including
- Fix the expected data of one test
- Fix the timeout of the iperf apply
> metrics: Test improvements

- ci/darwin-test.sh
- ci/gh-util.sh
- ci/install_libseccomp.sh
- ci/install_yq.sh
- ci/openshift-ci/bisect-range.sh
- ci/openshift-ci/cleanup.sh
- ci/openshift-ci/cluster/deploy_webhook.sh
- ci/openshift-ci/cluster/install_kata.sh
- ci/openshift-ci/lib.sh
- ci/openshift-ci/run_smoke_test.sh
- ci/openshift-ci/sample-test-reproducer.sh
- ci/openshift-ci/test.sh
Various shellcheck fixes, the SCXXXX were auto-generated but thoroughly reviewed, the rest was manually created.
Related to: https://github.com/kata-containers/kata-containers/issues/10951
> ci: shellcheck fixes

- src/runtime-rs/crates/hypervisor/src/device/driver/vfio.rs
Just get base name from iommu group symlink is enough. As the validation will be handled in subsequent steps when constructing the full path /sys/kernel/iommu_groups/$iommu_group.
In this PR, it will remove dupicalted validation of iommu_group.
> runtime-rs: Simplify iommu group base name extraction from symlink

- src/libs/Cargo.lock
- src/libs/kata-sys-util/Cargo.toml
- src/libs/kata-sys-util/src/lib.rs
- src/libs/kata-sys-util/src/pcilibs/devices.rs
- src/libs/kata-sys-util/src/pcilibs/mod.rs
- src/libs/kata-sys-util/src/pcilibs/pci_manager.rs
> kata-sys-utils: Introduce pcilibs for getting pci devices info

- ci/openshift-ci/README.md
- ci/openshift-ci/peer-pods-azure.sh
this script will be used in a new OCP integration pipeline to monitor basic workflows of OCP+peer-pods.
Testing version of this pipeline can be found here: https://github.com/openshift/release/pull/61457 using this file provided as gist https://gist.github.com/ldoktor/a7a3c797a53304ef91c58ed8cee416af. Once this is merged I'll switch that to this file instead and propose it for merging.
> ci.ocp: Add peer-pods setup script

- src/agent/src/netlink.rs
When running Kata Containers on CSPs, the CSPs may enforce their clusters to be IPv4-only.
Checking the OCI spec passed down to container, on a GKE cluster, we can see:
```
"sysctl": {
...
"net.ipv6.conf.all.disable_ipv6": "1",
"net.ipv6.conf.default.disable_ipv6": "1",
...
},
```
Even with ipv6 being explicitly disabled (behind our back ;-)), we've noticed that IPv6 addresses would be received, but then as IPv6 was disabled we'd break on CreatePodSandbox with the following error:
```
Warning  FailedCreatePodSandBox  4s    kubelet            Failed to
create pod sandbox: rpc error: code = Unknown desc = failed to create
containerd task: failed to create shim task: "update interface: Failed
to add address fe80::c44c:1cff:fe84:f6b7: NetlinkError(ErrorMessage {
code: Some(-13), header: [64, …
```
> agent: netlink: Only add an ipv6 address if ipv6 is enabled

- src/agent/src/storage/fs_handler.rs
- src/libs/kata-types/src/mount.rs
- src/runtime/pkg/containerd-shim-v2/create.go
- src/runtime/pkg/katautils/create.go
- src/runtime/virtcontainers/container.go
- src/runtime/virtcontainers/fs_share_linux.go
- src/runtime/virtcontainers/kata_agent.go
> EROFS Snapshotter Support in Kata

- src/agent/Cargo.lock
- src/agent/Cargo.toml
- src/libs/Cargo.lock
- src/libs/kata-sys-util/Cargo.toml
- src/libs/kata-types/Cargo.toml
- src/libs/logging/Cargo.toml
- src/libs/safe-path/Cargo.toml
- src/libs/shim-interface/Cargo.toml
- src/runtime-rs/Cargo.lock
- src/runtime-rs/Cargo.toml
- src/tools/genpolicy/Cargo.lock
- src/tools/genpolicy/Cargo.toml
- src/tools/kata-ctl/Cargo.lock
- src/tools/kata-ctl/Cargo.toml
- src/tools/runk/Cargo.lock
- src/tools/runk/Cargo.toml
- src/tools/runk/libcontainer/Cargo.toml
- src/tools/trace-forwarder/Cargo.lock
- src/tools/trace-forwarder/Cargo.toml
Update the tempfile crate to resolve security
issue CVE-2025-1744
> versions: Update tempfile crate

- src/runtime/virtcontainers/remote.go
Need to use hvLogger
Fixes: #11286
> runtime: Fix logging for remote hypervisor

- src/runtime/config/configuration-fc.toml.in
- src/runtime/config/configuration-qemu-coco-dev.toml.in
- src/runtime/config/configuration-qemu-nvidia-gpu-snp.toml.in
- src/runtime/config/configuration-qemu-nvidia-gpu-tdx.toml.in
- src/runtime/config/configuration-qemu-nvidia-gpu.toml.in
- src/runtime/config/configuration-qemu-se.toml.in
- src/runtime/config/configuration-qemu-sev.toml.in
- src/runtime/config/configuration-qemu-snp.toml.in
- src/runtime/config/configuration-qemu-tdx.toml.in
- src/runtime/config/configuration-qemu.toml.in
- src/runtime/config/configuration-stratovirt.toml.in
> config: Fix typos

- src/runtime/virtcontainers/container.go
Fixes: #11288
This PR appends hotplug devices (e.g., persistent volume) to deviceInfos when `vfio_mod` is `vfio` and `cold_plug_vfio` is set to one except `no-port`. For details, please visit the issue.
> runtime: Preserve hotplug devices for vfio-coldplug mode

- tools/osbuilder/scripts/lib.sh
> osbuilder: lib.sh: Fix indent

- src/runtime-rs/crates/hypervisor/src/device/driver/vfio.rs
Some nvidia gpu pci address domain with 0001,
current runtime default deal with 0000:bdf,
which cause address errors during device initialization and address conflicts during device registration
> runtime-rs: fix vfio pci address domain 0001 problem

- .github/workflows/static-checks.yaml
- src/tools/genpolicy/rules.rego
- tests/install_opa.sh
- tests/install_regorus.sh
- tests/static-checks.sh
- versions.yaml
> genpolicy: fix rules syntax issues, rego v1 compatibility; ci: checks for rego parsing

- .github/workflows/ci-weekly.yaml
- .github/workflows/release-amd64.yaml
- .github/workflows/release-arm64.yaml
- .github/workflows/release-ppc64le.yaml
- .github/workflows/release-s390x.yaml
Add extra permissions for reusable workflow calls
that need them later on
> workflows: Fix permissions

- src/runtime-rs/crates/resource/src/cpu_mem/initial_size.rs
An odd memory size leads to the runtime breaking during its startup, as shown below:
```
Warning  FailedCreatePodSandBox  34s   kubelet            Failed to
create pod sandbox: rpc error: code = Unknown desc = failed to start
sandbox
"708c81910f4e67e53b4170b6615083339b220154cb9a0c521b3232cdb40d50f9":
failed to create containerd task: failed to create shim task:
Others("failed to handle message start sandbox in task handler\n\nCaused
by:\n    0: start vm\n    1: set vm base config\n    2: set vm
configuration\n    3: Failed to set vm configuration VmConfigInfo {
vcpu_count: 2, max_vcpu_count: 16, cpu_pm: \"on\", cpu_topology:
CpuTopology { threads_per_core: 1, cores_per_die: 1, dies_per_socket: 1,
sockets: 1 }, vpmu_feature: 0, mem_type: \"shmem\", mem_file_path: \"\",
mem_size_mib: 4513, …
```
> runtime-rs: Fix calculation of odd memory sizes

- .github/workflows/PR-wip-checks.yaml
- .github/workflows/cargo-deny-runner.yaml
- .github/workflows/commit-message-check.yaml
> gha: Eliminate use of force-skip-ci label

- tools/osbuilder/rootfs-builder/nvidia/nvidia_chroot.sh
- tools/osbuilder/rootfs-builder/nvidia/nvidia_rootfs.sh
Remove gpu admin tools and pin toolkit version.
> Remove gpu admin tools

- src/runtime-rs/crates/hypervisor/src/qemu/qmp.rs
Although Previous implementation of hotplugging block device via QMP can successfully hot-plug the regular file based block device, but it fails when the backend is /dev/xxx(e.g. /dev/loop0). With analysis about it, we can know that it lacks the ablility to hotplug host block devices.
This commit will fill the gap, and make it work well for host block devices.
> runtime-rs: Support hotplugging host block devices within qemu-rs

- src/runtime-rs/Cargo.lock
- src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
- src/runtime-rs/crates/hypervisor/src/qemu/mod.rs
- src/runtime-rs/crates/hypervisor/src/qemu/qmp.rs
- src/runtime-rs/crates/resource/Cargo.toml
- src/runtime-rs/crates/resource/src/cgroups/mod.rs
- src/runtime-rs/crates/resource/src/cgroups/resource.rs
- src/runtime-rs/crates/resource/src/cgroups/resource_inner.rs
- src/runtime-rs/crates/resource/src/cgroups/utils.rs
- src/runtime-rs/crates/resource/src/manager_inner.rs
- src/runtime-rs/crates/shim/src/bin/main.rs
- tests/integration/kubernetes/k8s-oom.bats
- tests/integration/kubernetes/runtimeclass_workloads/pod-oom.yaml
The first commit is to implement `get_thread_ids()` for QEMU to return the
real vCPU thread ids. It is a required feature, since our tests are using
QEMU.
The second commit is to ignore SIGTERM signal. When enabling systemd cgroup
driver and sandbox cgroup only, the shim is under a systemd unit. When the
unit is stopping, systemd sends SIGTERM to the shim. The shim can't exit
immediately, as there are some cleanups to do. Therefore, ignoring SIGTERM
is required here. The shim should complete the work within a period (Kata
sets it to 300s by default). Once a timeout occurs, systemd will send
SIGKILL.
The third one is to add full cgroups support on host.
Cgroups are managed by `FsManager` and `SystemdManager`. As the names
impies, the `FsManager` manages cgroups through cgroupfs, while the …
> runtime-rs: Add full cgroups support on host

- tools/osbuilder/rootfs-builder/nvidia/nvidia_rootfs.sh
Make sure stage two gets the coco guest components
> gpu: guest components

- .github/workflows/run-kata-coco-stability-tests.yaml
- .github/workflows/run-kata-coco-tests.yaml
- .github/workflows/run-kata-deploy-tests-on-aks.yaml
- tests/functional/kata-deploy/gha-run.sh
- tests/gha-run-k8s-common.sh
- tests/integration/kubernetes/gha-run.sh
- tests/stability/gha-stability-run.sh
az cli is already installed by the azure/login action.
Test run: https://github.com/kata-containers/kata-containers/actions/runs/16627263899
> gha: Remove unnecessary install-azure-cli step

- tests/integration/kubernetes/k8s-nvidia-nim.bats
- tests/integration/kubernetes/runtimeclass_workloads/nvidia-nim-llama-3-1-8b-instruct.yaml.in
- tests/integration/kubernetes/runtimeclass_workloads/nvidia-nim-llama-3-2-nv-embedqa-1b-v2.yaml.in
Add langchain and embedding service
> gpu: AMD64 NVIDIA GPU CI/CD Part 2

- src/runtime/virtcontainers/qemu.go
- src/runtime/virtcontainers/qemu_arch_base.go
- src/runtime/virtcontainers/qemu_arm64.go
- src/runtime/virtcontainers/qemu_ppc64le.go
- src/runtime/virtcontainers/qemu_s390x.go
- src/runtime/virtcontainers/qemu_s390x_test.go
- tests/integration/kubernetes/k8s-initdata.bats
Opening this PR for enabling support for initdata in s390x [Issue : 11628](https://github.com/kata-containers/kata-containers/issues/11628)
> Feat | Implement initdata for bare-metal/qemu for s390x

- src/agent/src/confidential_data_hub/mod.rs
This PR optimizes the sealed secret scanning logic to avoid unnecessary full file reads, which can cause performance and reliability issues in certain environments.
Instead of reading the entire file, we now:
- Open the file and read only the first `N` bytes (`N = SEALED_SECRET_PREFIX.len()`).
- Compare the read bytes with the prefix.
- Only perform a full read if the prefix matches.
This avoids expensive I/O and reduces memory usage, while still preserving the intended functionality.
> Optimize sealed secret scanning to avoid full file reads

- .github/workflows/darwin-tests.yaml
- .github/workflows/docs-url-alive-check.yaml
- src/runtime/go.mod
- src/runtime/pkg/containerd-shim-v2/errors.go
- src/runtime/virtcontainers/remote.go
- src/tools/csi-kata-directvolume/go.mod
- src/tools/csi-kata-directvolume/pkg/utils/safe_formater.go
- src/tools/csi-kata-directvolume/pkg/utils/utils.go
- tests/common.bash
- tests/install_go.sh
- tools/testing/kata-webhook/go.mod
- versions.yaml
Bump to golang 1.24.6 now that go 1.23.x is EoL
> Golang 1.24.6 bump

- tests/common.bash
This is to investigate #11755.
> ci: cri-containerd-amd64: add logging for curl failures

- src/tools/log-parser/go.mod
- tests/go.mod
- tests/metrics/cmd/checkmetrics/go.mod
Update go 1.23 references to go 1.24.6 to match
versions.yaml
> versions: Tidy up go.mod versions

- src/libs/kata-types/src/container.rs
- src/runtime-rs/crates/runtimes/src/manager.rs
- src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs
It's related to https://github.com/kata-containers/kata-containers/issues/11697
> runtime-rs: Fix annotations within runtime-rs to pass the agent policy check

- ci/openshift-ci/peer-pods-azure.sh
we noticed we are quite blind on failure, add some extra output and allow to override parameters to allow bisection/reproduction with specified versions.
> ci.ocp: More debug output and tweaks

- tests/gha-run-k8s-common.sh
- tests/integration/kubernetes/setup.sh
- tests/integration/kubernetes/tests_common.sh
This reverts commit e8405590c1aadea21d510b25a2612fe93191fc10.
> Revert "ci: temporarily avoid using the Mariner Host image"

- src/libs/kata-sys-util/src/mount.rs
PR #11849 was merged before fixing a formatting issue.
> kata-sys-util: format mount.rs

- src/agent/rustjail/src/mount.rs
The previous code only checked the result of with_nix_path(), not statfs(), thus leading to an uninitialized memory read if statfs() failed.
No functional change otherwise.
> agent/rustjail: Fix potentially uninitialized memory read in unsafe code

- tools/osbuilder/rootfs-builder/nvidia/nvidia_chroot.sh
- tools/osbuilder/rootfs-builder/nvidia/nvidia_rootfs.sh
- tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Switch to noble for the guest and use NVIDIA CUDA repos with priority. Also use packages were possible and remove repo clone and build steps.
> gpu Switch to Noble and CUDA repos
