kata-containers/kata-containers

tests/integration/kubernetes/confidential_kbs.sh
this adds a support for `kcli` to `tests/integration/kubernetes/gha-run.sh deploy-coco-kbs`. It uses nodeport feature to expose the service from localhost as well as between the nodes, one can test it by:
```
cd tests/integration/kubernetes
CLUSTER_DISK_SIZE=40 ./gha-run.sh create-cluster-kcli
./gha-run.sh deploy-kata-kcli
KBS_INGRESS=nodeport KBS=true AKS_NAME=ldoktor bash -x ./gha-run.sh deploy-coco-kbs
```
=> tests: Support for kbs setup on kcli

tests/metrics/network/latency_kubernetes/latency-network.sh
This PR improves the latency test cleanup in order to avoid random failures of leaving the pods.
Fixes #9418
=> metrics: Improve latency test cleanup

.github/workflows/build-checks.yaml
Occasionally, the removal of GITHUB_WORKSPACE fails for self-hosted runners because one of the subdirectories is not empty. This is likely due to another process occupying the directory at the time.
Implementing a secondary cleanup resolves this issue. This commit focuses on the implementation for the secondary cleanup.
Fixes: #9317
=> GHA: Implement secondary GITHUB_WORKSPACE cleanup on 1st failure

utils/README.md
Now that v3.3.0 has been released, simplify
the `kata-manager` documentation.
Fixes: #9227.
=> docs: kata-manager: Update with latest details

src/agent/src/image.rs
Support different pause images in the guest for guest-pull, such as k8s pause image (registry.k8s.io/pause) and openshift pause image (quay.io/bpradipt/okd-pause).
The primary distinction between the k8s pause image and the OKD pause image lies in the arguments specified in the `config.json` file:
For the k8s pause image, the arguments are set as follows:
```json
"args": [
"/pause"
],
```
Conversely, for the OKD pause image, the arguments are different:
```json
"args": [
"/usr/bin/pod"
],
```
Fixes: #9225 -- part III
=> agent:image: Support different pause image in the guest for guest pull

.github/workflows/basic-ci-amd64.yaml, .github/workflows/build-kata-static-tarball-amd64.yaml, .github/workflows/build-kata-static-tarball-arm64.yaml, .github/workflows/build-kata-static-tarball-ppc64le.yaml, .github/workflows/build-kata-static-tarball-s390x.yaml, .github/workflows/ci.yaml, .github/workflows/payload-after-push.yaml, .github/workflows/publish-kata-deploy-payload-amd64.yaml, .github/workflows/publish-kata-deploy-payload-arm64.yaml, .github/workflows/publish-kata-deploy-payload-ppc64le.yaml, .github/workflows/publish-kata-deploy-payload-s390x.yaml, .github/workflows/release-amd64.yaml, .github/workflows/release-arm64.yaml, .github/workflows/release-ppc64le.yaml, .github/workflows/release-s390x.yaml, .github/workflows/release.yaml, .github/workflows/run-cri-containerd-tests-ppc64le.yaml, .github/workflows/run-cri-containerd-tests-s390x.yaml, .github/workflows/run-k8s-tests-on-aks.yaml, .github/workflows/run-k8s-tests-on-garm.yaml, .github/workflows/run-kata-monitor-tests.yaml, .github/workflows/run-metrics.yaml, .github/workflows/run-runk-tests.yaml
`Node.js 19` is deprecated. Bump to all impacted actions to new versions based on `Node.js 20`.
Fixes #9245
=> gha: Bump various actions to use Node.js 20

ci/README.md, docs/README.md, tests/cmd/check-spelling/kata-dictionary.dic
This is actually a first attempt to document our CI, and all this content was based on the document created by @fidencio (kudos to him). We are just moving the content and discussion from Google Docs to here.
I used the "poetic license" to add some notes on what I believe our CI will look like in the future.
TIP: I suggest viewing the file in preview mode and also enabling the TOC feature in Github for better navigation.
=> docs: adding an initial CI documentation

.github/workflows/build-checks.yaml, src/tools/genpolicy/Cargo.lock, src/tools/genpolicy/Cargo.toml, src/tools/genpolicy/genpolicy-advanced-command-line-parameters.md, src/tools/genpolicy/src/config_map.rs, src/tools/genpolicy/src/daemon_set.rs, src/tools/genpolicy/src/deployment.rs, src/tools/genpolicy/src/job.rs, src/tools/genpolicy/src/list.rs, src/tools/genpolicy/src/main.rs, src/tools/genpolicy/src/no_policy.rs, src/tools/genpolicy/src/pod.rs, src/tools/genpolicy/src/policy.rs, src/tools/genpolicy/src/registry.rs, src/tools/genpolicy/src/registry_containerd.rs, src/tools/genpolicy/src/replica_set.rs, src/tools/genpolicy/src/replication_controller.rs, src/tools/genpolicy/src/secret.rs, src/tools/genpolicy/src/stateful_set.rs, src/tools/genpolicy/src/utils.rs, src/tools/genpolicy/src/yaml.rs, tests/integration/kubernetes/filter_out_per_arch/aarch64.yaml, tests/integration/kubernetes/filter_out_per_arch/ppc64le.yaml, tests/integration/kubernetes/filter_out_per_arch/s390x.yaml, tests/integration/kubernetes/gha-run.sh, tests/integration/kubernetes/k8s-pod-manifest-v1.bats, tests/integration/kubernetes/run_kubernetes_tests.sh, tests/integration/kubernetes/runtimeclass_workloads/pod-manifest-v1.yaml, tests/integration/kubernetes/tests_common.sh
Fixes: https://github.com/kata-containers/kata-containers/issues/9144
Add an optional flag that allows you to use existing containerd installation to pull and manage images.
This improvement will:
- Add support to images with v1 [manifest](https://github.com/opencontainers/image-spec/blob/main/manifest.md), such as `bprashanth/nginxhttps:1.0`
- Support images with any layer media type that is supported by containerd, such as `application/vnd.docker.distribution.manifest.v1+prettyjws` from image `registry.k8s.io/galera-install:0.1`
- Fix issue with current method where sometimes you get API throttled when pulling layers individually
=> genpolicy: Add optional toggle to pull images using containerd

tests/integration/kubernetes/confidential_kbs.sh
This PR improves the kbs_k8s_delete function to verify that the resources were properly deleted for baremetal environments.
Fixes #9379
=> tests: Improve the kbs_k8s_delete function

tests/integration/kubernetes/k8s-policy-job.bats, tests/integration/kubernetes/run_kubernetes_tests.sh, tests/integration/kubernetes/runtimeclass_workloads/k8s-policy-job.yaml, tests/integration/kubernetes/tests_common.sh
Auto-generate the policy and then simulate attacks from the K8s control plane by modifying the test yaml files. The policy then detects and blocks those changes.
These test cases are using K8s Jobs. Additional policy failures will be injected using other types of K8s resources - e.g., using Pods and/or Replication Controllers - in future PRs.
Fixes: #9406
=> tests: k8s: inject agent policy failures

.github/workflows/run-kata-coco-tests.yaml, tests/gha-run-k8s-common.sh, tests/integration/kubernetes/k8s-guest-pull-image.bats
This is for running the existing guest-pull tests on non-TEE environment for the CoCo 0.9.0 release.
I could have introduced a new column to the current k8s jobs matrix (`.github/workflows/run-k8s-tests-on-aks.yaml`) but this would have created some issues as I described in https://github.com/kata-containers/kata-containers/issues/9410. So instead this is going to create a new matrix of jobs (`run-k8s-tests-coco-nontee`) alongside the TEE jobs in `.github/workflows/run-kata-coco-tests.yaml` for running the CoCo tests on non-TEE.
Initially it is going to run only the guest-pull tests but in the future I envision it being used for all CoCo's non-TEE tests, that's why I made it generic.
Talking about the guest-pull tests, because I  they are now running on non-CoCo runtimeclasses, i.e., when …
=> CC: run guest-pull tests on non-TEE jobs

src/agent/src/main.rs
Linux kernel generates a panic when the init process exits. The kernel is booted with panic=1, hence this leads to a vm reboot.
When used as a service the kata-agent service has an ExecStop option which does a full sync and shuts down the vm. This patch mimicks this behavior when kata-agent is used as the init process.
Fixes: #9429
=> agent: shutdown vm on exit when agent is used as init process

ci/openshift-ci/cluster/install_kata.sh
updating the machine config takes even longer than 1200s, use 60m to be sure everything is updated.
Fixes: #9338
=> ci.ocp: Increase the MCP update time

versions.yaml
In order to build a coco {image,initrd}, it is required to specify its name and version in versions.yaml. This commit is to add the configuration for them, respectively.
Fixes: #9470
=> version: Add coco name and version for {image,initrd} for s390x

.github/workflows/ci.yaml
The new CoCo non-tee job introduced on commit 0d5399ba923a17f need to read secrets like AZ_TENANT_ID, so run-kata-coco-tests workflow should inherit the secrets from the caller workflow.
Fixes #9477
=> gha: make run-kata-coco-tests inherit secrets

tests/integration/kubernetes/k8s-policy-rc.bats, tests/integration/kubernetes/run_kubernetes_tests.sh, tests/integration/kubernetes/runtimeclass_workloads/k8s-policy-rc.yaml
Auto-generate the policy and then simulate attacks from the K8s control plane by modifying the test yaml files. The policy then detects and blocks those changes.
These test cases are using K8s Replication Controllers. Additional policy failures will be injected using other types of K8s resources
, e.g., using Pods and/or Jobs, in separate PRs.
Fixes: #9463
=> tests: k8s: inject agent policy failures (part2)

src/tools/genpolicy/genpolicy-settings.json, src/tools/genpolicy/src/pod.rs, src/tools/genpolicy/src/policy.rs, src/tools/genpolicy/src/registry.rs, src/tools/genpolicy/src/settings.rs, src/tools/genpolicy/src/utils.rs
This PR adds support for a few registry options that allow running genpolicy in hermetic environments (e.g. build systems). Instead of adding more arguments to the individual function calls, I decided to pass around an options struct that holds the currently required options: `use_cache`, `pause_container_image` and `insecure_registries`. 
I think the right place to obtain the pause container image from is the settings file, because this is where other implementation details of the CRI currently live (such as default env vars, capabilities, etc.). The `cluster_config` section seemed like a good idea, but I'm open to alternatives. Although there already is a `pause_container` section, that one is parsed as a `KataSpec`, where putting an image reference does not make sense. 
Insecure …
=> genpolicy: support insecure registries and custom pause containers

docs/hypervisors.md, docs/use-cases/GPU-passthrough-and-Kata.md, docs/use-cases/Intel-Discrete-GPU-passthrough-and-Kata.md, tests/cmd/check-spelling/data/acronyms.txt, tests/cmd/check-spelling/data/main.txt, tests/cmd/check-spelling/kata-dictionary.dic
Document describes the steps needed to pass an entire Intel Discrete GPU as well a GPU SR-IOV interface to a Kata Container.
Fixes: #9083
=> docs: Document Intel Discrete GPUs usage with Kata

versions.yaml
Fixes: #9472
For initrd and image, the related NVIDIA will not use the default targets and we will pin them to a specific release.
=> version: add initrd, image NVIDIA sections

tests/integration/kubernetes/k8s-policy-pod.bats, tests/integration/kubernetes/run_kubernetes_tests.sh, tests/integration/kubernetes/runtimeclass_workloads/k8s-policy-configmap.yaml, tests/integration/kubernetes/runtimeclass_workloads/k8s-policy-pod.yaml
Auto-generate the policy and then simulate attacks from the K8s control plane by modifying the test yaml files. The policy then detects and blocks those changes.
These test cases are using K8s Pods. Additional policy failures are injected during CI using other types of K8s resources - e.g., using Jobs and Replication Controllers - from separate PRs.
Fixes: #9491
=> tests: k8s: inject agent policy failures (part 3)

.github/workflows/ci-nightly-s390x.yaml
This commit is simply to remove a CI workflow `k8s-cri-containerd-rhel9-e2e-tests`.
Fixes: #9504
=> gha: Remove k8s-cri-containerd-rhel9-e2e-tests for s390x

.github/workflows/stale.yaml
As documented in https://github.com/actions/stale?tab=readme-ov-file#start-date
> The start date is used to ignore the issues and pull requests created before the start date.
> Particularly useful when you wish to add this stale workflow on an existing repository
> and only wish to stale the new issues and pull requests.
As we don't want need to treat PRs older than May 2023 as a special case, then remove this option.
Fixes: #9502
=> gha: stale: Remove the start-date

.github/workflows/run-cri-containerd-tests-s390x.yaml, .github/workflows/run-k8s-tests-on-zvsi.yaml
This is to make a workflow `run-k8s-tests` and `run-cri-containerd` (s390x and zvsi) run only on the runners labeled by `s390x-large`.
FYI: here are the registered runners for s390x:
Fixes: #9507
=> gha: Make integration tests for s390x run on s390x-large runners

.github/workflows/stale.yaml
- Bump the stalebot action version to v9 as that fixes the
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/stale@v8.
```
warning.
Fixes: #9512
=> gha: stale: Bump stalebot version

.github/workflows/run-k8s-tests-on-ppc64le.yaml
This PR aims at running the k8s tests to one runner on ppc64le.
Fixes: #9520
=> gha: tag k8s tests on ppc64le to ppc64le-runner-01

.github/workflows/run-k8s-tests-on-aks.yaml, .github/workflows/run-kata-coco-tests.yaml
The new run-k8s-tests-coco-nontee job should be the home of attestation tests.
Changed run-k8s-tests-coco-nontee to get KBS installed and by the time the KBS variable is exported in the environment then the attestation tests will kick in (likewise they will skip in run-k8s-tests-on-aks).
Fixes #9455
=> gha: move attestation tests to run-k8s-tests-coco-nontee

src/agent/Cargo.lock
Update Kata Agent's Cargo.lock after the recent changes to Cargo.toml.
=> agent: update cargo.lock

src/libs/kata-types/src/config/hypervisor/mod.rs, src/runtime-rs/crates/resource/src/rootfs/block_rootfs.rs
In case of block devices using virtio-block, we need to pass the pci-path as the storage source field to the agent. Current the virt-path is being passed which works just for mmio block devices.
In the future when support is added for scsi, block-ccw and pmem devices, the storage source would need to be handled accordingly.
Fixes: #9034
=> runtime-rs: Update storage source for pci block devices

.github/workflows/build-kata-static-tarball-s390x.yaml, .github/workflows/run-k8s-tests-on-zvsi.yaml, docs/how-to/how-to-run-kata-containers-with-SE-VMs.md, tools/packaging/guest-image/build_se_image.sh, tools/packaging/kata-deploy/local-build/Makefile
This commit is to add a new CI job to run-k8s-tests-on-zvsi.yaml.
Why the job is not configured in run-kata-coco-tests.yaml by having it integrated with `run-k8s-tests-coco-nontee` is:
- It uses k3s instead of AKS
- It runs on a self-hosted runner
These differences make the integrated job not easy to read and maintain when it comes to incorporating other platforms in the near future.
The verification for non-TEE has been done via a private self-hosted runner at https://github.com/BbolroC/kata-containers/actions/runs/8782763328
This PR also includes an adjustment of the build procedure for `boot-image-se` and updates the document accordingly. The verification for TEE (Secure Execution) from the internal test is at https://github.com/kata-containers/kata-containers/actions/runs/8795055047/jo …
=> CC: Enable guest-pull tests on non-TEE for s390x

src/runtime/virtcontainers/clh.go
isClhRunning uses signal 0 to test whether the process is still alive or not. This doesn't work because the process is a direct child of the shim. Once it is dead the process becomes zombie.
Since no one waits for it the process lingers until its parent dies and init reaps it. Hence sending signal 0 in isClhRunning will always return success whether the process is dead or not.
This patch calls wait to remove the zombie from the process table before trying to send signal 0.
Fixes: #9431
=> clh: isClhRunning waits for full timeout when clh exits

tools/packaging/kata-deploy/scripts/kata-deploy.sh
This should only be done once, and if CRI-O restarts, there's a big chance kata-deploy will also restart and the user would end up with a file that looks like:
```
[crio]
log_level = "debug"
[crio]
log_level = "debug"
[crio]
log_level = "debug"
...
```
And that would simply cause CRI-O to not start.
=> kata-deploy: Stop append `log_level = "debug"` for CRI-O

src/tools/genpolicy/src/config_map.rs, src/tools/genpolicy/src/list.rs, src/tools/genpolicy/src/no_policy.rs, src/tools/genpolicy/src/secret.rs, src/tools/genpolicy/src/yaml.rs
This PR adds default implementations for the following methods of K8sResource trait:
- generate_policy
- serialize
- use_sandbox_pidns
- use_host_network
- get_containers
- get_container_mounts_and_storages
- get_sandbox_name
- get_annotations
Fixes: #8960
=> genpolicy: implement default methods for K8sResource trait

tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
When docker is installed on the host system using script from https://get.docker.com/ it automatically creates a docker group with _gid=999_. 
Then during docker build process of tarball, eg. **make qemu-tdx-experimental-tarball** docker is also installed inside the image with the same script, which also automatically adds docker group with _gid=999_.
Then, the build tries to add a new group _docker_on_host_ with _gid=999_, which already exists, which breaks the build.
=> build: Fix tarball not building correctly in docker

src/tools/genpolicy/Cargo.lock, src/tools/genpolicy/Cargo.toml, src/tools/genpolicy/src/registry.rs, src/tools/genpolicy/src/registry_containerd.rs
Based on 3a1461b0a5186a92afedaaea33ff2bd120d1cea0
Previously the tool would use the layers_cache folder for all instances and hence delete the cache when it was done, interfereing with other instances. This change makes it so that each instance of the tool will have its own temp folder to use.
=> genpolicy: changing caching so the tool can run concurrently with itself

docs/install/README.md
Document section `hardware-requirements` locates to `/README.md`.
=> doc: fix missing document link

.github/workflows/darwin-tests.yaml, .github/workflows/docs-url-alive-check.yaml, tests/.golangci.yml, versions.yaml
As we have the following issue with a golang version for `run-cri-containerd`, it is required to bump the language:
```
go build  -gcflags=-trimpath=/home/runner/actions-runner/_work/kata-containers/kata-containers/src -buildmode=pie  -o bin/containerd -ldflags '-X github.com/containerd/containerd/version.Version=v1.7.16 -X github.com/containerd/containerd/version.Revision=83031836b2cf55637d7abf847b17134c51b38e53 -X github.com/containerd/containerd/version.Package=github.com/containerd/containerd -s -w ' -tags "no_btrfs"  ./cmd/containerd
vendor/tags.cncf.io/container-device-interface/internal/validation/k8s/objectmeta.go:43:16: undefined: errors.Join
note: module requires Go 1.20
```
CI example: https://github.com/kata-containers/kata-containers/actions/runs/8844120756/job/24285892891
=> build: Update golang version to 1.22.2

src/runtime-rs/crates/hypervisor/src/qemu/cmdline_generator.rs
This PR adds support for the IOMMU device and `iommu_platforms` device param to runtime-rs qemu driver.  It can be also viewed as implementing support for `configuration.toml`'s `enable_iommu` and `enable_iommu_platform` settings.
=> runtime-rs: support IOMMU in qemu VMs

.github/workflows/commit-message-check.yaml
Dependabot doesn't follow all our commit format guidelines, so add a check and skip these if the author is `dependabot[bot]`
=> workflow: static-checks: Skip commit checks for dependabout

tools/packaging/kata-deploy/scripts/kata-deploy.sh
Fix the configuration for crio's log_level
Fixes: #9556
=> kata-deploy: configure debugging for crio

.github/workflows/build-kata-static-tarball-amd64.yaml, .github/workflows/build-kata-static-tarball-ppc64le.yaml, .github/workflows/build-kata-static-tarball-s390x.yaml, docs/how-to/how-to-run-kata-containers-with-SE-VMs.md, tools/packaging/kata-deploy/local-build/Makefile, tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Now that the OPA binary is not required anymore, let's start shipping
the agent with the policy enabled by default.
The agent *without* policy enabled has 30MB, while it's 34MB *with* the
policy enabled.
This 4MB (~10%) increase is, IMHO, worth it in order to reduce the
amount of components we have to maintain and test, including the
possibility to also reduce the amount of possible rootfs / initrd
images.
Whoever wants to use the agent without policy enabled can simply do that
by building their own agent. :-)
/cc @stevenhorsman @danmihai1
=> build: Build the shipped agent with policy enabled

src/tools/genpolicy/rules.rego, tests/gha-run-k8s-common.sh, tests/integration/kubernetes/setup.sh
```
The CH v39 upgrade in #9575 is currently blocked because of a bug in the
Mariner host kernel. To address this, we temporarily tweak the Mariner
CI to use an Ubuntu host and the Kata guest kernel, while retaining the
Mariner initrd. This is tracked in #9594.
Importantly, this allows us to preserve CI for genpolicy. We had to
tweak the default rules.rego however, as the OCI version is now
different in the Ubuntu host. This is tracked in #9593.
This change has been tested together with CH v39 in #9588.
```
=> tests: adapt Mariner CI to unblock CH v39 upgrade

versions.yaml
This PR removes oci information from versions file as this is not longer being used in kata containers repository.
Fixes #9599
=> versions: Remove oci information from versions file

src/runtime/golang.mk
The build message shows that yq was not found when I tried to build runtime binaries, but I've actually installed yq by yum install.
=> build: fix the confusing build message if yq doesn't exist in GOPATH/bin

src/runtime-rs/crates/runtimes/src/manager.rs
We should init and asign the runtime instance to runtime handler, otherwise, if the pause container failed to start, which means the runtime instance failed to start, then the following delete & shutdown request wouldn't be run, thus the dead shim would be left.
Fixes: #9597
=> runtime-rs: fix the issue of the leak of dead shim

src/runtime/virtcontainers/qemu_arm64.go
Everytime I create contianer on arm64 machine, containerd/kata logs a redundant warning as follows:
``` shell
time="2024-05-07" level=warning msg="<nil>" arch=arm64 name=containerd-shim-v2 pid=xxx sandbox=fdd1f05 source=virtcontainers/hypervisor
```
I added an error statement so that the error would be logged when it occurs.
=> qemu: the error is logged only when it occurs

.github/workflows/build-kata-static-tarball-amd64.yaml
This is the first step of the work to start relying on the artefacts coming from the distros (CentOS 9 Stream, and Ubuntu) themselves.
Let's have this first one merged, as this will not run the CI due to the changes being on the yaml itself, and then follow-up with the changes needed on other parts of the project (kata-deploy, runtime, etc).
Fixes: #9590 -- part I
=> ci: Stop building TDX specific QEMU and OVMF

tests/integration/kubernetes/k8s-guest-pull-image.bats
Let's skip those tests on TEEs as we've been facing a reasonable amount of issues, most likely on the containerd side, related to pulling the image on the guest.
Once we're able to fix the issues on containerd, we can get back and re-enable those by reverting this commit.
The decision of disabling the tests for TEEs is because the machines may end up in a state where human intervention is necessary to get them back to a functional state, and that's really not optimal for our CI.
=> tests: pull-image: Don't run on TEEs

src/runtime-rs/crates/hypervisor/src/qemu/cmdline_generator.rs
RTC was being built in a wrong fashion on PR 9519
=> runtime-rs: Fix constructing the RTC struct

docs/Debug-shim-guide.md, docs/Developer-Guide.md, tools/containerd-shim-katadbg-v2
This PR provides some developer's documentation and a helper script that makes it easier to use a debugger on the go shim.
NOTE: This PR doesn't address runtime-rs, it will come with a future commit.
Now the script provided here will probably be useful for runtime-rs too, as most of it is related to the shim's behavior, dictated by the shimv2 interface.
My expectation at this point is that the same script should be usable for both shims.
=> debugging: adding a script and instructions for debugging the GO shim

tools/packaging/kata-deploy/scripts/kata-deploy.sh
the `tdx_not_supported_warning` function does not exists, the `tdx_not_supported` should be called instead.
Fixes: #9628
=> kata-deploy: Fix tdx_not_supported call

tools/osbuilder/rootfs-builder/rootfs.sh, tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
We have a runtime error for agent with `AGENT_POLICY`.
This commit is to ensure if the default rootfs is built with AGENT_POLICY=yes.
Fixes: #9630 
=> local-build: Ensure the default rootfs is built with AGENT_POLICY=yes

tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Preparation for complete GPU rootfs build step num 1 of N
=> gpu: Add build targets for GPU rootfs initrd/image

tests/integration/kubernetes/k8s-confidential-attestation.bats
This PR adds a k8s negative policy test to the confidential attestation bats test.
Fixes #9437
=> tests: Add k8s negative policy test

tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh, tools/packaging/scripts/lib.sh
A length of the result of `git log -1 --pretty=format:%h` could vary over different CI systems, highly likely messing up their caching mechanisms.
This commit is to use an option `--abbrev=9` to standardize the length to 9 characters for CI.
=> CI: Use `--abbrev=9` explicitly for abbreviated commit hash

tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml, tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
This PR fixes the random write value for FIO for qemu and clh by decreasing it to avoid the random failures of the GHA CI.
=> metrics: Fix random write value for FIO

versions.yaml
Bump nydus snapshotter to v0.13.13 to fix the gap when switching different snapshotters in guest pull.
Fixes: #8407
=> version: Bump nydus snapshotter to v0.13.13

.github/workflows/build-kata-static-tarball-amd64.yaml, .github/workflows/build-kata-static-tarball-arm64.yaml, .github/workflows/build-kata-static-tarball-ppc64le.yaml, .github/workflows/build-kata-static-tarball-s390x.yaml, .github/workflows/release-amd64.yaml, .github/workflows/release-arm64.yaml, .github/workflows/release-ppc64le.yaml, .github/workflows/release-s390x.yaml, tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Add the ability to tag certain components in our ghcr cache, rather than just storing them all by digest. In particular the cloud-api-adaptor implementation of the remote-hypervisor wants to use the agent, agent-opa and guest-components
=> Tag component caches

.github/workflows/build-kata-static-tarball-amd64.yaml, .github/workflows/build-kata-static-tarball-arm64.yaml, .github/workflows/build-kata-static-tarball-ppc64le.yaml, .github/workflows/build-kata-static-tarball-s390x.yaml
- It appears like the `if` isn't required when setting env as a conditional :( Sorry!
=> workflow: Remove if from env conditional

tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Now we have the workflow updated and can test the changes in caching we've hit an error:
```
line 1180: artefact_tag: unbound variable
```
so we need to fix that up. Sorry for missing this before.
=> ci: cache: Fix unbound variable

tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
- Merge oras push logic together
- Container image tags can only contain alphanumeric, period,
hyphen and underscore characters, so convert characters outside
of these to be underscores, to avoid having invalid tag failures
=> Caching tagging update part iii

tests/gha-run-k8s-common.sh, tests/integration/kubernetes/confidential_common.sh, tests/integration/kubernetes/k8s-confidential-attestation.bats, tests/integration/kubernetes/k8s-confidential.bats, tests/integration/kubernetes/k8s-guest-pull-image.bats, tests/integration/kubernetes/lib.sh
On 142342012c01debcd8b4c8812e6cc2b62daf698e, I've mistakenly disabled the tests entirely, for both non-TEEs and TEEs.
This happened as I didn't realise that `confidential_setup` would take non-TEEs into consideration. :-/
Now, let me follow-up on that and make sure that the tests will be running on non-TEEs.
=> tests: pull-image: Only skip tests for TEEs

tools/packaging/static-build/initramfs/build.sh
This PR is to append an arch type to the initramfs-cryptsetup image to prevent a wrong arch image from being pulled on a different arch host.
Fixes: #9654
=> CI: Append arch type to initramfs-cryptsetup image

tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
- The tags have a trailing non-printable character, which results in our cache tags having a trailing underscore e.g. `ghcr.io/kata-containers/cached-artefacts/agent:ce24e9835_` For ease of use of these cached components, we should strip off the trailing underscore.
=> ci: cache: Filter out non-printable characters from tag

tests/gha-run-k8s-common.sh
This reverts commit 5ff53e4d1cb94cef04477e36135b932edd28e077, as the script was fixed by MSFT, at least according to:
https://github.com/Azure/azure-cli/issues/28984
=> Revert "ci: azure: Workaround azure cli installation script"

tools/packaging/kata-deploy/scripts/kata-deploy.sh
fixes #9670
VERSION_ID is not guaranteed to be specified in os-release, this makes kaka-deploy breaks in rolling distros like arch linux and void linux.
> Note that operating system vendors may choose not to provide version information, for example to accommodate for rolling releases. In this case, VERSION and **VERSION_ID may be unset. Applications should not rely on these fields to be set.**
=> fix: kata-deploy.sh VERSION_ID unbound-variable

.github/workflows/release-amd64.yaml, .github/workflows/release-arm64.yaml, .github/workflows/release-ppc64le.yaml
Now we have updated the release builds to push artefacts to
our registry for the release, so we can cache the images, we need to set
`secrets: inherit` for all architecture's tarball builds so that we can log into quay.io and ghcr in those steps
This change was tested on release workflow https://github.com/kata-containers/kata-containers/actions/runs/9158766910/job/25179503476 which was green
=> gha: release: Set inherit secrets on tarball builds

src/tools/genpolicy/src/policy.rs
In Kubernetes, the following values for namespace are equivalent and all refer to the default namespace:
- ` ` (namespace field missing)
- `namespace: ""` (namespace field is the empty string)
- `namespace: "default"`(namespace field has the explicit value `default`)
Genpolicy currently does not handle the empty string case correctly.
=> genpolicy: detect empty string in ns as default

.github/workflows/run-kata-coco-tests.yaml, tests/integration/kubernetes/confidential_kbs.sh, tests/integration/kubernetes/gha-run.sh
This PR adds support to install KBS to k8s TDX GHA workflow in order to run confidential attestation tests.
Fixes #9451
=> gha: Add support to install KBS to k8s TDX GHA workflow

tests/functional/vfio-ap/Dockerfile, tests/functional/vfio-ap/run.sh
An e2e test for `vfio-ap` has been conducted internally in IBM due to the lack of publicly available test machines equipped with a required crypto device.
The test is performed by the `tests` repository:
(i.e. https://github.com/kata-containers/tests/blob/772105b5606432f7c59e04aad1978b622e357586/Makefile#L144)
The community is working to integrate all tests into the `kata-containers` repository, so the `vfio-ap` test should be part of that effort.
This PR moves a test script and Dockerfile for a test image from the `tests` repository (i.e. https://github.com/kata-containers/tests/tree/main/functional/vfio-ap). We do not rename the script to `gha-run.sh` because it is not executed by Github Actions' workflow.
You can check the test results from the s390x nightly test with the migrated …
=> CI: Migrate vfio-ap test files from tests repo

src/runtime/pkg/oci/utils.go, src/runtime/pkg/oci/utils_test.go
Currently for remote-hypervisor, the verification of hypervisor annotations like default_memory, default_cpu, machine_type etc. is using the Kata/Qemu processing framework. This is limiting the capabilities of remote hypervisor. This PR disables the check for number of cpu comparison on a remote hypervisor scenario.
Fixes https://github.com/kata-containers/kata-containers/issues/9238
=> runtime: Disable number of cpu comparison on remote hypervisor scenario 

src/runtime/virtcontainers/kata_agent.go, src/runtime/virtcontainers/kata_agent_test.go
By default, when a container is created with the `--privileged` flag, all devices in `/dev` from the host are mounted into the guest. If there is a block device(e.g. `/dev/dm`) followed by a generic device(e.g. `/dev/null`)，two identical block devices(`/dev/dm`) would be requested to the kata agent causing the agent to exit with error:
> Conflicting device updates for /dev/dm-2
As the generic device type does not hit any cases defined in `switch`， the variable `kataDevice` which is defined outside of the loop is still the value of the previous block device rather than `nil`. Defining `kataDevice` in the loop fixes this bug.
=> runtime: fix duplicated devices requested to the agent

src/runtime/virtcontainers/clh.go
ResizeMemory for Cloud Hypervisor is missing a check for the new requested memory being greater than the max hotplug size after alignment. Add the check, and since an earlier check for this setsrequested memory to the max hotplug size, do the same in the post-alignment check.
Fixes #9640
=> runtime: Add missing check in ResizeMemory for CH

src/runtime-rs/crates/hypervisor/src/qemu/cmdline_generator.rs
All these settings are hardcoded as `false` and result in no extra options on the QEMU command line, like the go runtime does. There actually not needed :
- we're never going to ask QEMU to survive a guest shutdown
- we're never going to run QEMU daemonized since it prevents log collection
- we're never going to ask QEMU to start with the guest stopped
No need to keep this code around then.
=> runtime-rs: Drop some useless QEMU arguments

tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
As we have multi-arch builds for nearly all components, we want to ensure that all the cache tags we set have the architecture suffix, not just the `TARGET_BRANCH` one.
=> ci: cache: Add arch suffix to all cache tags

tests/integration/kubernetes/confidential_kbs.sh, tests/integration/kubernetes/gha-run.sh, tests/integration/kubernetes/k8s-confidential-attestation.bats, versions.yaml
This PR enables the installation and unistallation of the kbs client as well as general coco components needed for the TDX GHA CI.
=> gha: Enable install kbs and coco components for TDX, but still skip the CDH test

tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
This PR fixes the minvalue for boot time to avoid the random failures of the GHA CI.
=> metrics: Fix minvalue for boot time

tests/integration/kubernetes/k8s-custom-dns.bats
This test has failed in confidential runtime jobs. Skip it until we don't have a fix.
Fixes: #9663
=> tests/k8s: skip custom DNS tests on confidential jobs

src/agent/src/device.rs
The new version of sriov-network-device-plugin adds an env `PCIDEVICE_<prefix>_<resource-name>_INFO`, which has a json value; kata-agent can't parse it as env `PCIDEVICE_<prefix>_<resource-name>` which has value in format "DDDD:BB:SS.F".
This change updates env `PCIDEVICE_<prefix>_<resource-name>_INFO`.
=> kata-agent: update env PCIDEVICE_<prefix>_<resource-name>_INFO

src/libs/Cargo.lock, src/runtime-rs/config/configuration-cloud-hypervisor.toml.in, src/runtime-rs/config/configuration-dragonball.toml.in, src/runtime-rs/config/configuration-qemu-runtime-rs.toml.in
The `dial_timeout` works fine for Runtime-go, but is obsoleted in
Runtime-rs.
When the pod cannot connect to the Agent upon starting, we need to adjust
the `reconnect_timeout_ms` to increase the number of connection attempts to
the Agent.
Fixes: #9688
=> runtime-rs: Remove obsoleted dial_timeout config

src/runtime/cmd/kata-runtime/kata-check.go
If device /dev/kvm does not exist, kata-runtime check would fail with an ambiguous error messae 'no such file or directory'. I added a little more details to make it understandable and it will belike:
```
ERRO[0000] cannot open kvm device: no such file or directory  arch=arm64 check-type=full device=/dev/kvm name=kata-runtime pid=2849085 source=runtime
ERRO[0000] no such file or directory                          arch=arm64 name=kata-runtime pid=2849085 source=runtime
no such file or directory
```
=> runtime: make kata-runtime check error more understandable when /dev/kvm doesn't exist

src/libs/kata-types/src/config/hypervisor/mod.rs, src/runtime-rs/config/configuration-qemu-runtime-rs.toml.in, src/runtime-rs/crates/hypervisor/src/qemu/cmdline_generator.rs
add support QMP socket in cmdline
Fixes: #9603
=> runtime-rs: add QMP support for Qemu(part I)

src/runtime-rs/Makefile
Replace tab indentation with spaces for the three lines within the ifneq statements, aligning them with the surrounding code.
Fixes: #9692.
Signed-off-by: sidneychang <2190206983@qq.com>
=> Adjust indentation in ifneq statements within Makefile in runtime-rs 

src/runtime/cmd/kata-runtime/kata-env.go, src/runtime/cmd/kata-runtime/kata-env_test.go, src/runtime/pkg/containerd-shim-v2/create.go, src/runtime/pkg/containerd-shim-v2/create_test.go, src/runtime/pkg/device/config/config.go, src/runtime/pkg/device/drivers/utils.go, src/runtime/pkg/device/drivers/vfio.go, src/runtime/pkg/device/manager/manager.go, src/runtime/pkg/hypervisors/hypervisor_state.go, src/runtime/pkg/katatestutils/utils.go, src/runtime/pkg/katautils/config-settings.go.in, src/runtime/pkg/katautils/config.go, src/runtime/pkg/katautils/config_test.go, src/runtime/pkg/oci/utils.go, src/runtime/pkg/oci/utils_test.go, src/runtime/virtcontainers/container.go, src/runtime/virtcontainers/hypervisor.go, src/runtime/virtcontainers/persist.go, src/runtime/virtcontainers/persist/api/config.go, src/runtime/virtcontainers/pkg/annotations/annotations.go, src/runtime/virtcontainers/qemu.go, src/runtime/virtcontainers/sandbox.go
In Kubernetes we still do not have proper VM sizing at sandbox creation level. This KEP tries to mitigates that: kubernetes/enhancements#4113 but this can take some time until Kube and containerd or other runtimes have those changes rolled out.
Before we used a static config of VFIO ports, and we introduced CDI support which needs a patched containerd. We want to eliminate the patched containerd in the GPU case as well.
Fixes: #8860
=> gpu: reintroduce pcie_root_port and add pcie_switch_port

tools/packaging/static-build/ovmf/build.sh
Build ovmf without sudo docker this is not needed. This is part 1 of N
=> ci: ovmf without sudo

tools/packaging/static-build/qemu/build-base-qemu.sh
Build qemu without sudo docker this is not needed. This is part 9 of N
=> ci: qemu no sudo

utils/kata-manager.sh
nerdctl requires cni plugins to be installed in /opt/cni/bin
Without bridge plugin installed, it is not possible to run a
container with nerdctl.
The downloaded nerdctl tarball contains cni plugin files, but are
extracted under /usr/local/libexec.
Copy extracted tarball cni files under /usr/local/libexec
to /opt/cni/bin
=> kata-manager: Copy cni files under /opt/cni

tools/packaging/static-build/initramfs/Dockerfile, tools/packaging/static-build/initramfs/build.sh
Build initramfs  without sudo docker this is not needed. This is part 10 of N
=> ci: initramfs no sudo

tools/packaging/scripts/lib.sh
We weren't considering changes of the tools script dir adding a fourth hash to accomodate this
=> ci: Fix tools builder images

src/runtime-rs/crates/hypervisor/src/qemu/cmdline_generator.rs
It creates this line, as the Golang runtime does:
-object rng-random,id=rng0,filename=/dev/urandom -device virtio-rng-pci,rng=rng0,max-bytes=1024,period=1000
=> runtime-rs: Add RNG to QEMU cmdline

tests/integration/kubernetes/gha-run.sh
It's cloning the nydus-snapshotter repo from the version specified in versions.yaml, however, the deployment files are set to pull in the latest version of the snapshotter image. With this version we are pinning the image version too.
This is a temporary fix as it should be better worked out at nydus-snapshotter project side.
Fixes: #9742
=> ci: pin the nydus-snapshotter image version

tests/integration/kubernetes/k8s-empty-dirs.bats, tests/integration/kubernetes/k8s-file-volume.bats, tests/integration/kubernetes/k8s-kill-all-process-in-container.bats, tests/integration/kubernetes/k8s-seccomp.bats, tests/integration/kubernetes/k8s-shared-volume.bats, tests/integration/kubernetes/k8s-sysctls.bats, tests/integration/kubernetes/setup.sh
Currently the `kata-qemu-coco-dev` configuration run one and only one guest-pull pull type test, which is the [k8s-guest-pull-image.bats](https://github.com/kata-containers/kata-containers/blob/main/tests/integration/kubernetes/k8s-guest-pull-image.bats). This PR is for enabling the runtime handler annotation (`io.containerd.cri.runtime-handler`) on all deployments used on k8s tests, as a result, k8s tests will be leveraging the guest-pull from now on.
The `tests/k8s: skip custom DNS tests for qemu-coco-dev` commit on this PR isn't related with the change I'm proposing here. However, I had to disable that test to run the test suite (currently configured for "fail-fast"), as it started failing last week for all TEE jobs (see https://github.com/kata-containers/kata-containers/issues/9663) . …
=> tests: enable guest-pull on all k8s tests for the qemu-coco-dev configuration

tests/integration/kubernetes/k8s-empty-dirs.bats
Wainer noticed this is failing for the coco-qemu-dev case, and decided to skip it, notifying me that he didn't fully understand why it was not failing on TDX.
Turns out, though, this is also failing on TDX, and we need to skip it there as well.
=> ci: k8s: Skip empty dir tests also for TDX

tests/integration/kubernetes/k8s-confidential-attestation.bats
Use the variable BATS_TEST_COMPLETED which is defined by the bats framework when the test finishes. `BATS_TEST_COMPLETED=` (empty) means the test failed, so the node syslogs will be printed only at that condition.
Fixes: #9750
---
First I created a function `has_test_failed()` (see below) that would be called from `teardown()`. It didn't work because `BATS_TEST_COMPLETED` is a local variable not visible from `has_test_failed()`, and I still don't know why. Any bash guru could help here? Then I decided to implement like in this PR.
```
--- a/tests/integration/kubernetes/tests_common.sh
+++ b/tests/integration/kubernetes/tests_common.sh
@@ -118,6 +118,16 @@ exec_host() {
return ${exit_code}
}
+# Return true if current test failed.
+# Use in teardown() to conditionally take actions. …
```
=> tests/k8s: print logs on fail only (k8s-confidential-attestation.bats)

src/agent/README.md, src/agent/src/config.rs, src/agent/src/main.rs
fixes #9748
A configuration option `guest_component_procs` has been introduced that indicates which guest component processes are supposed to be spawned by the agent. The default behaviour remains that all of those processes are actively spawned by the agent. At the moment this is based on presence of binaries in the rootfs and the guest_component_api_rest option.
The new option is incremental:
none -> attestation-agent -> confidential-data-hub -> api-server-rest
e.g. api-server-rest implies attestation-agent and confidential-data-hub
the `none` option has been removed from guest_component_api_rest, since this is addresses by the introduced option.
=> CoCo: introduce config for guest-components procs

.github/actionlint.yaml, .github/workflows/basic-ci-amd64.yaml, .github/workflows/run-kata-monitor-tests.yaml
I've made a python script to collect some statistics of the nightly CI jobs. This PR disables the **test** jobs that failed > 50% on the last 10 nights.
While I think that this script has bugs (e.g. I notice the filter regex isn't correct), I do believe that for the jobs I'm disabling here, the numbers are correct. I've observed those jobs for a while now and I only wanted an excuse :)
See the script and results here: https://github.com/kata-containers/kata-containers/issues/9506#issuecomment-2142990502
=> CI: disable jobs that failed > 50% on nightly CI recently - part 1

.github/workflows/run-k8s-tests-on-zvsi.yaml, tests/integration/kubernetes/tests_common.sh
In line with the changes for x86_64, the k8s nydus test for s390x should also use `qemu-coco-dev` for `KATA_HYPERVISOR`.
Additionally, it was observed that the `node_start_time` value is sometimes empty, leading to a test failure.
This PR includes to make `setup_common()` retry fetching the value up to 3 times.
The changes have been tested 5 times internally, and all tests passed. 
=> GHA: Use qemu-coco-dev for k8s nydus test on s390x

src/tools/genpolicy/src/daemon_set.rs, src/tools/genpolicy/src/deployment.rs, src/tools/genpolicy/src/pod.rs, src/tools/genpolicy/src/policy.rs, src/tools/genpolicy/src/stateful_set.rs, src/tools/genpolicy/src/utils.rs, src/tools/genpolicy/src/yaml.rs, tests/integration/kubernetes/k8s-policy-pod.bats, tests/integration/kubernetes/tests_common.sh
Add a command line flag to the genpolicy tool. 
The given value ("kata-cc" by default) must match the `runtimeClassName` of K8s resources which have this field defined (even if not explicitly set) like Deployment, DaemonSet, ReplicaSet,...
This is useful when the policies for a more complex deployment should be generated. Before, a policy would be attached on e.g. every pod even if it wasn't supposed to run as a confidential container. Additionally, to be able to generate that policy, the container needed to be downloaded which, depending on the size, might take some time. 
I choose using the given parameter value as a prefix, because in Contrast we have our own runtimeClassName `contrast-cc-<sha265sum indicating the version>` for which we don't want to carry around the full value all the …
=> genpolicy: add ability to filter for runtimeClassName

tests/integration/kubernetes/confidential_kbs.sh
This PR replaces the name to use a variable that is already defined to have a better uniformity across the general script.
=> tests: Use variable definition for better uniformity

tools/packaging/kata-deploy/local-build/dockerbuild/install_oras.sh
We are currently building Oras from source on ppc64le. Now that they offically release the artefacts for power, consume them to install Oras.
This PR also updates oras version to `1.2.0`
Fixes: #9213
=> kata-deploy: install oras using release artefacts on ppc64le

docs/Blog-Post-Submission-Guide.md, docs/README.md
The Kata blog was recently moved to the project's website. The content of the blog is stored together with the rest of the website source on GitHub.
This patch adds a short guide that describes how to submit a new blog post as a PR, to appear on the project's website.
=> docs: Adding blog submission guidelines

utils/kata-manager.sh
For nerdctl install, add symlinks for runc and slirp4netns in the binary install path.
runc link comes in handy for running runc containers with nerdctl fir quick tests.
slirp4netns allows for running containers with user mode networking useful in case of rootless containers.
=> kata-manager: Add symlinks for runc and slirp4netns

ci/openshift-ci/images/Dockerfile.buildroot
Centos8 is EOL and repos are not available anymore https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/52655/rehearse-52655-pull-ci-kata-containers-kata-containers-main-images/1798289476254961664 Centos9 contains the same packages and should do well as a base for testing.
=> ci.ocp: Switch base to centos-9

tests/integration/kubernetes/k8s-credentials-secrets.bats, tests/integration/kubernetes/k8s-inotify.bats, tests/integration/kubernetes/k8s-nested-configmap-secret.bats, tests/integration/kubernetes/k8s-projected-volume.bats, tests/integration/kubernetes/k8s-volume.bats
It seems I was very lose on disabling some of the tests, and the issues I faced could be related to other instabilities in the CI.
Let's re-enable the tests, following what was done for the SEV, SNP, and coco-qemu-dev.
Thanks @AdithyaKrishnan, @ryansavino, and @wainersm for double-checking which tests could be re-enabled.
=> ci: tdx: Re-enable a bunch of volume related tests

tests/common.bash, tests/integration/kubernetes/gha-run.sh
Frequent errors have been observed during k8s e2e tests:
- The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?
- Error from server (ServiceUnavailable): the server is currently unable to handle the request
- Error from server (NotFound): the server could not find the requested resource
These errors can be resolved by retrying the kubectl command.
This commit introduces a wrapper function in common.sh that runs kubectl up to 3 times with a 5-second interval. Initially, this change only covers gha-run.sh for Kubernetes.
=> CI: Introduce retry mechanism for kubectl in gha-run.sh

tests/integration/kubernetes/k8s-policy-pod.bats
Fix the recent collision between:
- https://github.com/kata-containers/kata-containers/pull/9377
- https://github.com/kata-containers/kata-containers/pull/9725
One enabled a newer yq command line format and the other used the older format. Both passed CI because they were not tested together.
Fixes: #9789
=> tests: k8s: use newer yq command line format

src/agent/src/config.rs
fixes #9810
Add an annotation to the enum values in the agent config that will deserialize them using a kebab-case conversion, aligning the behaviour to parsing of params specified via kernel cmdline.
drive-by fix: add config override for guest_component_procs variable
=> agent: convert enum vals to kebab-case in cfg file

src/tools/genpolicy/genpolicy-settings.json, src/tools/genpolicy/rules.rego, src/tools/genpolicy/src/policy.rs, src/tools/genpolicy/src/settings.rs
Load OCI version from genpolicy-settings.json and validate it in rules.rego
Fixes: #9593
=> genpolicy: load OCI version from settings

src/agent/src/config.rs
- Update the config parsing logic so that when reading from the agent-config.toml file any envs are still processed
- Add units tests to formalise that the envs take precedence over values from the command line and the config file
=> agent: config: Ensure envs take precedence

tests/metrics/time/launch_times.sh
This PR uses the function definition to have uniformity across all the launch times script.
=> metrics: Use function definition to have uniformity

tests/integration/kubernetes/gha-run.sh, tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml, tools/packaging/kata-deploy/scripts/kata-deploy.sh
This introduces a handler for PULL_TYPE variable to allow configuring CRI-O for guest-pull image pulling.
kata-deploy is going to append `runtime_pull_image = true` to each kata runtimeClass configuration created at `/etc/crio/crio.conf.d/99-kata-deploy` , when `PULL_TYPE=guest-pull`. For example:
```toml
[crio.runtime.runtimes.kata-qemu]
runtime_path = "/usr/local/bin/containerd-shim-kata-qemu-v2"
runtime_type = "vm"
runtime_root = "/run/vc"
runtime_config_path = "/opt/kata/share/defaults/kata-containers//configuration-qemu.toml"
privileged_without_host_devices = true
runtime_pull_image = true
```
Currently there aren't any CI jobs exercising this feature. I tested it in a fresh Ubuntu 22.04 VM by running the following script and checking  was as expected:
```bash
#!/bin/bash
set -o …
```
=> kata-deploy: configuring CRI-O for guest-pull image pulling

src/tools/genpolicy/rules.rego, src/tools/genpolicy/src/containerd.rs, src/tools/genpolicy/src/persistent_volume_claim.rs, src/tools/genpolicy/src/pod.rs, src/tools/genpolicy/src/policy.rs, tests/integration/kubernetes/k8s-policy-pvc.bats, tests/integration/kubernetes/run_kubernetes_tests.sh, tests/integration/kubernetes/runtimeclass_workloads/k8s-policy-pod-pvc.yaml, tests/integration/kubernetes/runtimeclass_workloads/k8s-policy-pvc.yaml
This PR allows `genpolicy` to parse Kubernetes objects using [raw block volumes](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#raw-block-volume-support), and derives rules for creating these volumes in the guest VM container.
Fixes #9651.
cc @danmihai1
=> genpolicy: add support for devices

src/runtime/pkg/govmm/qemu/qemu.go, src/runtime/pkg/govmm/qemu/qemu_test.go, src/runtime/virtcontainers/qemu.go
As said in https://github.com/kata-containers/kata-containers/pull/9642#issuecomment-2122399707, this is back-porting a code simplification from the rust shim : remove the code for the options that are not to be ever passed to QEMU.
=> Kill some dead runtime code

tests/integration/kubernetes/k8s-policy-pvc.bats
Fix the collision between:
- https://github.com/kata-containers/kata-containers/pull/9377
- https://github.com/kata-containers/kata-containers/pull/9706
One enabled a newer yq command line format and the other used the older format. Both passed CI because they were not tested together.
=> tests: fix yq command line in k8s-policy-pvc

ci/install_yq.sh
I get:
~/gopath/bin/yq --version
yq (https://github.com/mikefarah/yq/) version v4.40.7
Also add support for set -o xtrace to install_yq.sh.
=> ci: fix the expected yq version string

src/runtime/virtcontainers/remote.go
While running with a remote hypervisor, whenever kata-monitor tries to access metrics from the shim, the shim does a "panic" and no metric can be gathered.
The function GetVirtioFsPid() is called on metrics gathering, and had a call to "panic()". Since there is no virtiofs process for remote hypervisor, the right implementation is to return nil. The caller expects that, and will skip metrics gathering for virtiofs.
Fixes: #9826
=> runtime: avoid panic on metrics gathering

src/runtime/pkg/govmm/qemu/qmp.go
Fixes minor spelling issues in runtime.
=> runtime: fix minor spelling issues

src/runtime-rs/crates/runtimes/src/manager.rs
It shouldn't call the initial_size_manager's setup_config in the load_config since it had been called in the sandbox's try_init function.
Fixes: #9778
=> sandbox: fix the issue of double initial_size_manager config

.github/workflows/build-kata-static-tarball-amd64.yaml
Now that all artifacts are owned by $USER we can start to remove sudo from our GHA
=> CI: remove sudo from GHA

src/tools/genpolicy/src/settings.rs
This corrects the warning to point to the `-j` flag,
which is the correct flag for the JSON settings file.
Previously, the warning was confusing, as it pointed to
the `-p` flag, which specifies to the path for the Rego ruleset.
=> genpolicy: fix settings path flag name

.github/workflows/run-k8s-tests-on-aks.yaml, tests/integration/kubernetes/k8s-cpu-ns.bats, tests/integration/kubernetes/k8s-number-cpus.bats, tests/integration/kubernetes/k8s-sandbox-vcpus-allocation.bats
The following tests are disabled because they fail (alike with dragonball):
- k8s-cpu-ns.bats
- k8s-number-cpus.bats
- k8s-sandbox-vcpus-allocation.bats
Fixes #9804
=> tests/k8s: run for qemu-runtime-rs on AKS

tests/integration/kubernetes/gha-run.sh
Since #9785 was introduced, the following error was observed during the deployment of nydus snapshotter:
```
Error from server (NotFound):
the server could not find the requested resource ( pods/log nydus-snapshotter-5v82v)
'kubectl logs nydus-snapshotter-5v82v -n nydus-system' failed after 3 tries
Error: Process completed with exit code 1.
```
This error can occur when a pod is re-created by a daemonset during the retry interval.
This commit addresses the issue by using `--selector` rather than the pod name
for `kubectl logs/describe`.
=> tests: Use selector rather than pod name for kubectl logs/describe

src/agent/Cargo.lock, src/agent/Cargo.toml, src/agent/rustjail/Cargo.toml, src/libs/Cargo.lock, src/libs/shim-interface/Cargo.toml, src/runtime-rs/Cargo.lock, src/runtime-rs/crates/agent/Cargo.toml, src/runtime-rs/crates/hypervisor/Cargo.toml, src/runtime-rs/crates/hypervisor/ch-config/Cargo.toml, src/runtime-rs/crates/resource/Cargo.toml, src/runtime-rs/crates/runtimes/Cargo.toml, src/runtime-rs/crates/runtimes/common/Cargo.toml, src/runtime-rs/crates/runtimes/linux_container/Cargo.toml, src/runtime-rs/crates/runtimes/virt_container/Cargo.toml, src/runtime-rs/crates/runtimes/wasm_container/Cargo.toml, src/runtime-rs/crates/service/Cargo.toml, src/runtime-rs/crates/shim-ctl/Cargo.toml, src/runtime-rs/crates/shim/Cargo.toml, src/tools/agent-ctl/Cargo.lock, src/tools/genpolicy/Cargo.lock, src/tools/genpolicy/Cargo.toml, src/tools/runk/Cargo.lock, src/tools/runk/Cargo.toml
Update tokio dependency in various crates to address the
high severity security vulnerability https://rustsec.org/advisories/RUSTSEC-2024-0019
=> Tokio vulnerability bump

src/runtime-rs/crates/runtimes/virt_container/src/container_manager/manager.rs
For kata container, the container's pid is meaning less to containerd/crio since the container's pid is belonged to VM, and containerd/crio couldn't use it. Thus we just return any tid of kata shim or hypervisor. But since the hypervisor had been stopped before deleting the container, and it wouldn't get the hypervisor's tid for some supported hypervisor, thus we'd better to return the kata shim's pid instead of hypervisor's tid.
Fixes: #9777
Fixes: #9374
=> sandbox: fix the issue of failed to get the vmm master tid

src/runtime-rs/Cargo.lock, src/runtime-rs/crates/hypervisor/Cargo.toml, src/runtime-rs/crates/hypervisor/src/qemu/cmdline_generator.rs, src/runtime-rs/crates/hypervisor/src/qemu/inner.rs, src/runtime-rs/crates/hypervisor/src/qemu/mod.rs, src/runtime-rs/crates/hypervisor/src/qemu/qmp.rs
This PR creates a base framework for QMP functionality.  The idea of the new `Qmp` object is similar to the one of `QemuCmdLine` - encapsulate implementation details of QMP handling while offering `QemuInner` an interface that matches its needs.
The `qapi-rs` library is used to handle the QMP low-level details.  Its documentation isn't great but the library itself is close enough to QMP to be actually quite easy to use (so far at least ;-)).
We also add support for hotplugging vCPUs, basically as a test case for the newly added infrastructure. :-)
=> runtime-rs: add base qmp framework

.github/workflows/run-kata-coco-tests.yaml
TDX CI has been having some issues with the Nydus snapshotter cleanup, which has been stuck for hours depending every now and then.
With this in mind, let's disable the TDX CI, so we avoid it blocking the progress of Kata Containers project, and we re-enable it as soon as we have it solved on Intel's side.
=> ci: tdx: Disable TDX CI

.github/workflows/run-kata-coco-tests.yaml
We've noticed a bunch of issues related to deploying and deleting the nydus-snapshotter.  As we don't see the same issues on other machines using vanilla kubernetes, let's avoid using k3s for now follow the flow.
NOTE: This test should **NOT** run as the TDX CI is not enabled right now.
=> ci: tdx: Use vanilla k8s instead of k3s

tools/packaging/scripts/configure-hypervisor.sh, versions.yaml
There is a known issue in qemu 7.2.0 that causes kernel-hashes to fail the verification of the launch binaries for the SEV legacy use case.
Fixes: #9148
=> qemu: upgrade to 8.2.4

tests/integration/nerdctl/gha-run.sh
This PR fixes the variables names for the network that was created as well removes the network that were created for the tests to ensure a clean environment when running all the tests and avoid failures specially on baremental environments that network already exists.
=> tests: nerdctl: Fix variables names and remove network

.github/workflows/run-kata-coco-tests.yaml
Now, using vanilla kubernetes, let's re-enable the TDX CI and hope it becomes more stable than it used to be.
The cleanup-snapshotter is now taking ~4 minutes, and that matches with the other platforms, mainly considering there's a sum of 210 seconds sleep in the process.
=> ci: tdx: Re-enable TDX CI

.github/workflows/build-kata-static-tarball-s390x.yaml
We can now do the same for s390x that we did for amd64 and remove the sudo cp.
=> ci: remove sudo from s390x build

src/tools/genpolicy/src/pod.rs, tests/integration/kubernetes/runtimeclass_workloads/k8s-policy-pod.yaml
Ignore SeccompProfile in PodSpec. rules.rego already verifies is_null(i_linux.Seccomp).
=> genpolicy: ignore SeccompProfile in PodSpec

tests/metrics/density/memory_usage_inside_container.sh
This PR improves the variable definition in memory inside the container script for metrics. This change declares and assigns the variables separately to avoid masking return values.
=> metrics: Improve variable definition in memory inside containers script

src/libs/kata-types/src/k8s.rs
When the total number of files observed is greater than limit, return -1 directly. runtime has fixed this bug, it should b ported to runtime-rs.
Fixes:#9829
=> runtime-rs: fix the bug of func count_files

.github/workflows/run-kata-coco-tests.yaml
- Add the `AUTHENTICATED_IMAGE_USER` and `AUTHENTICATED_IMAGE_PASSWORD` repository secrets as env vars to the coco tests, so we can use them to pull an images from and authenticated registry for testing
=> workflow: coco: Add auth registry secret

src/tools/genpolicy/src/registry.rs, src/tools/genpolicy/src/registry_containerd.rs, src/tools/genpolicy/src/utils.rs, tests/integration/kubernetes/k8s-policy-pod.bats
Add --layers-cache-file-path flag to allow the user to specify where the cache file for the container layers is saved. This allows e.g. to have one cache file independent of the user's working directory.
In the actual logic, this replaces the `use_cached_files` variable. Note that the `use_cached_files` flag can still be used and the CLI retains the same behavior.
Current error behavior when specifying a path that does not exists:
```
[2024-06-17T20:34:25Z INFO  genpolicy::registry] ============================================
[2024-06-17T20:34:25Z INFO  genpolicy::registry] Pulling manifest and config for "ghcr.io/3u13r/contrast/openssl@sha256:2b75075a8c1273607fa9acbf30792b5d59c2a4b8519ceb8327226ac31d52633f"
[2024-06-17T20:34:26Z INFO  genpolicy::registry] read_verity_from_store: failed …
```
=> genpolicy: allow specifying layer cache file

tests/integration/kubernetes/k8s-confidential-attestation.bats
- We only want to enable the sample verifier in the KBS for non-TEE tests, so prevent an edge case where the TEE platform isn't set up correctly and we might fall back to the sample and get false positives. To prevent this we add guards around the sample policy enablement and only run it for non confidential hardware
=> tests: attestation: Restrict sample policy use

ci/openshift-ci/run_smoke_test.sh, ci/openshift-ci/smoke/http-server.yaml.in, ci/openshift-ci/test.sh
we do encourage people to set the KATA_RUNTIME, but it is only used by the webhook. Let's define it in the main `test.sh` and use it in the smoke test to ensure the user-defined runtime is smoke-tested rather than hard-coded kata-qemu one.
Related to: #9804
=> ci.ocp: Ensure we smoke-test with the right runtime class

src/tools/kata-ctl/Cargo.lock
A previous change missed to refresh Cargo.lock.
=> kata-ctl: Update Cargo.lock

tests/common.bash
Observed instability in the API server after deploying kata-deploy caused test failures. (see: https://github.com/kata-containers/kata-containers/actions/runs/9681494440/job/26743286861) Specifically, `kubectl_retry logs` failed before the API server could respond properly.
This commit increases the interval and max_tries for kubectl_retry(), allowing sufficient time to handle this situation.
=> tests: Increase interval and max_tries for kubectl_retry

tools/osbuilder/rootfs-builder/ubuntu/rootfs_lib.sh
In some occassions multistrap is not able to find the ubuntu-keyring  package, e.g. CI system, DMZ'ed server etc. Run `apt pdate`  to have all repos up to date.
=> rootfs: Fix spurious error

tests/integration/kubernetes/runtimeclass_workloads/pod-attestable.yaml
A multi-arch image for `alpine-bash-curl` has been pushed to and available at `quay.io/kata-containers`.
This PR switches the test image to `quay.io/kata-containers/alpine-bash-curl`.
Fixes: #9935
=> CI: Use multi-arch image for alpine-bash-curl

src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/CpusConfig.md, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/RngConfig.md, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_cpus_config.go, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_rng_config.go, src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml, versions.yaml
v40.0. The following user visible changes have been made:
It is now possible to pass file descriptors over the HTTP API (and using
`ch-remote`) when restoring to update the file descriptors for network devices.
This enables snapshot & restore functionality for guests using `macvtap` or
other file descriptor backed network devices. 
* Default values have been removed from required fields in the OpenAPI metadata
* The help syntax of `ch-remote remove-device` has been improved
* A double close of file descriptors has been fixed when using `--serial`
* To prevent loops a limit on the nesting level for QCOW2 backing files has
been introduced
* Boot time performance has been …
=> Upgrade to Cloud Hypervisor v40.0

tests/metrics/machine_learning/openvino.sh
Test reports that it is a onednn test when it is openvino; update description.
Fixes: #9948
=> tests: Update help section in openvino test

src/runtime/virtcontainers/qemu_ppc64le.go, tools/packaging/static-build/qemu/Dockerfile
Do not install the packages librados-dev and librbd-dev as they are not needed for building static qemu.
Fixes: #9893
=> kata-deploy: fix qemu static build on ppc64le

.github/workflows/basic-ci-amd64.yaml, .github/workflows/ci.yaml, .github/workflows/run-kata-deploy-tests-on-garm.yaml, .github/workflows/run-kata-monitor-tests.yaml, .github/workflows/run-runk-tests.yaml, .github/workflows/static-checks.yaml
```
Per the decision taken in the 6/27 AC meeting, this PR temporarily
disables kata-deploy and GARM tests until we secure further Azure CI
funding.
In the meantime, I'll transition the GARM tests to free runners and
reenable them to regain that coverage without affecting spending (see
#9940). If it turns out the free runners are too slow, we'll switch back
to GARM.
After funding is secured, we'll reenable the kata-deploy tests (see
#9939).
```
=> ci: Temporarily disable kata-deploy and GARM tests

src/tools/genpolicy/src/pod.rs, tests/integration/kubernetes/runtimeclass_workloads/k8s-policy-pod.yaml
Allow genpolicy to process Pod YAML files including topologySpreadConstraints.
=> genpolicy: add topologySpreadConstraints support

.github/workflows/cleanup-resources.yaml, tests/cleanup_resources.py
```
Follow-up to #9898 and final PR of this set. This implements the actual
deletion logic.
```
Tested here as a dry run (nothing was actually deleted): https://github.com/kata-containers/kata-containers/actions/runs/9670071327/job/26678039258 Interestingly, that shows 12 dangling clusters.
=> ci: Add scheduled job to cleanup resources, pt. II 

src/agent/Makefile, src/runtime-rs/Makefile, src/tools/kata-ctl/Makefile, src/tools/log-parser/Makefile, tools/osbuilder/Makefile, tools/osbuilder/rootfs-builder/rootfs.sh, tools/osbuilder/scripts/lib.sh
This allows to call tooling like the rootfs builder outside of a git environment. Calculating the VERSION_COMMIT field without warnings/errors depends on the presence of a VERSION file and on a git environment. We set the VERSION_COMMIT field to 'unknown' if the version cannot be properly calculated. This not only prevents errors in the Makefile but also prevents from rootfs.sh being called with an empty -o parameter, thus the distro parameter from being parsed incorrectly.
The change also makes a rust version check optional for cases where we want to build the rootfs w/o building the agent and thus w/o the rust dependency
Fixes: 9824
=> osbuilder: allow rootfs builds w/o git or version file deps

docs/presentations/unit-testing/kata-containers-unit-testing.md
This PR removes the jenkins reference from unit testing presentation as this is not longer supported on the kata containers project.
=> docs: Remove jenkins reference from unit testing presentation

tests/metrics/density/k8s-sysbench.sh
This PR removes the CI_JOB variable which previously was used but not longer being supported of the metrics sysbench test.
=> metrics: Remove variable in sysbench that is not being used

tests/integration/kubernetes/gha-run.sh
tests: remove unnecessary sleeps that slow down tests
The modifications to kubectl_retry from #9923 in combination with extensive sleep times in the nydus cleanup is causing various TEE environment timeouts and test failures.
Fixes: #9942
tests: delete the nydus directory at the end of cleanup
The nydus cleanup is skipped if the directory does not exist.
The directory was not being deleted.
Signed-Off-By: Adithya Krishnan Kannan <AdithyaKrishnan.Kannan@amd.com>
=> tests: Fixes TEE timeout issue

.github/workflows/basic-ci-amd64.yaml, tests/integration/docker/gha-run.sh, tests/stability/gha-run.sh
Transitioning the first batch of tests in `basic-ci-amd64.yaml`.
This is tracked in #9940.
=> ci: Transition GARM tests to free runners, pt. I

src/agent/src/image.rs, src/agent/src/rpc.rs, src/agent/src/storage/image_pull_handler.rs, tests/integration/kubernetes/k8s-file-volume.bats, tests/integration/kubernetes/k8s-kill-all-process-in-container.bats, tests/integration/kubernetes/k8s-liveness-probes.bats, tests/integration/kubernetes/k8s-shared-volume.bats, tests/integration/kubernetes/k8s-sysctls.bats
Let me explain why:
In our previous approach, we implemented guest pull by passing PullImageRequest to the guest. However, this method  resulted in the loss of specifications essential for running the container, such as commands specified in YAML, during the CreateContainer stage. To address this, it is necessary to integrate the OCI specifications and process information from the image’s configuration with the container in guest pull.
The snapshotter method does not care this issue. Nevertheless, a problem arises when two containers in the same pod attempt to pull the same image, like InitContainer. This is because the image service searches for the existing configuration, which resides in the guest. The configuration, associated with <image name, cid>, is stored in the directory …
=> Fix issues on CI about guest-pull

tests/integration/nerdctl/gha-run.sh
This PR fixes the pip installation for nerdctl by removing a flag which is not longer supported and avoid the failure of no such option: --break-system-packages.
=> gha: Fix pip installation for nerdctl GHA

src/agent/Cargo.lock, src/agent/Cargo.toml, tests/integration/kubernetes/k8s-liveness-probes.bats
- Try bumping image-rs to latest main to pull in the latest security fixes and updates
=> Image rs bump to latest main

tests/stability/agent_stability_test.sh, tests/stability/scability_test.sh, tests/stability/soak_parallel_rm.sh, tests/stability/stressng.sh
This PR is for the use of the variable CTR_EXE which is already defined in the metrics common script and which is being used in the stabilty tests to have better uniformity.
=> tests: Use variable already defined in metrics common script for stability tests

src/agent/Cargo.lock, src/agent/Cargo.toml, src/agent/src/cdh.rs, src/agent/src/main.rs, src/agent/src/rpc.rs, src/libs/protocols/build.rs, src/libs/protocols/protos/sealed_secret.proto, src/libs/protocols/src/lib.rs, tests/integration/kubernetes/k8s-sealed-secret.bats, tests/integration/kubernetes/run_kubernetes_tests.sh, tests/integration/kubernetes/runtimeclass_workloads/pod-sealed-secret.yaml
This PR brings sealed secret functionality to main. This functionality was originally implemented by @LindaYu17 and @Lu-Biao.
I have made some improvements and converted the [old sealed secrets test](https://github.com/kata-containers/tests/blob/CCv0/integration/kubernetes/confidential/sealed_secret.bats) from the defunct CCv0 branch of the tests repo into a test that is similar to the existing CoCo attestation test.
There are still refinements to be made (especially in the last PR). I have done some local testing, but let's see what the CI makes of it.
=> Support Confidential Sealed Secrets (as env vars)

ci/openshift-ci/run_smoke_test.sh
This replays https://github.com/ldoktor/kata-containers/pull/6 on top of https://github.com/kata-containers/kata-containers/tree/selective-ci which contains the changes from https://github.com/kata-containers/kata-containers/pull/9637 .
Previous tentative to test at https://github.com/kata-containers/kata-containers/pull/9961 got auto-merged. Likely a mistake from my side : I forgot to commit the test patch after rebasing and I force-pushed to the PR an exact copy of the target branch.
=> Test https://github.com/kata-containers/kata-containers/pull/9637 (take 2)

src/agent/src/device.rs, src/agent/src/linux_abi.rs, tests/functional/vfio-ap/Dockerfile, tests/functional/vfio-ap/container-config.json.in, tests/functional/vfio-ap/run.sh, tests/functional/vfio-ap/sandbox-config.json
So far, the `vfio-ap` test has only been verifying the attachment of the device to a VM guest for a {hot,cold}-plug via `lszcrypt` from `s390-tools` (https://github.com/ibm-s390-linux/s390-tools). This PR introduces a functional test for the device for a hot-plug via a new tool `zcrypttest`.  The following steps are required to achieve this goal:
- Instantiate/pass vfio-ap device to ociSpec
- Add zcrypttest tool to test image Dockerfile
- Extend vfio-ap hotplug test to use zcrypttest
Each step corresponds to a single commit. You can find a detailed description in each commit.
The extended test has already run in the s390x nightly test (e.g. https://github.com/kata-containers/kata-containers/actions/runs/9542189133/job/26296583157) since the 14th of June and no test failure has been …
=> tests: Extend vfio-ap hotplug test to use a zcrypttest tool

tests/integration/cri-containerd/gha-run.sh
```
Following #9960 that transitioned this test to a free runner, we need to
ensure Docker isn't installed on the system as that will conflict with
the installation of Podman.
Example error:
https://github.com/kata-containers/kata-containers/actions/runs/9818218975/job/27177785716
```
Addresses #9940
=> tests: cri-containerd: Ensure Docker isn't present

tests/integration/cri-containerd/integration-tests.sh
This PR removes the use_devmapper variable which was part of the jenkins environment flags which is not longer support it or available for the cri-containerd tests.
=> cri-containerd: Remove use_devmapper variable for cri-containerd tests

.github/workflows/ci.yaml
run-k8s-tests-on-zvsi runs the coco tests and we've added new secrets to provide credentials for the authenticated image testing, so we need to let the zvsi job inherit these from the caller workflow like the rest of the coco tests (in https://github.com/kata-containers/kata-containers/pull/9479)
=> gha: make run-k8s-tests-on-zvsi inherit secrets

.github/workflows/run-kata-coco-tests.yaml
This PR increases the timeout to run the CoCo TDX tests in order to avoid the random failures on TDX saying that
The action 'Run tests' has timed out after 30 minutes and making the GHA job fail.
=> gha: Increase timeout to run CoCo TDX tests

tests/common.bash, tests/metrics/lib/json.bash
```
GH-9973 introduced:
* New function get_kata_memory_and_vcpus() in
tests/metrics/lib/common.bash.
* A call to get_kata_memory_and_vcpus() from extract_kata_env(), which
is defined in tests/common.bash.
Because the nydus test only sources tests/common.bash, it can't find
get_kata_memory_and_vcpus() and errors out.
So we fix this by moving get_kata_memory_and_vcpus() to
tests/common.bash.
```
Related: #9940
=> ci: fix run-nydus tests

tests/metrics/storage/blogbench.sh
This PR updates the container name to put a random name instead of using a hard coded name.
=> metrics: Update container name in blogbench test

tests/integration/kubernetes/k8s-empty-dirs.bats, tests/integration/kubernetes/k8s-shared-volume.bats
Currently, it is not viable to share a writable volume (e.g., emptyDir) between containers in a single pod for IBM SE.
The following tests are relevant:
- pod-shared-volume.bats
- k8s-empty-dirs.bats
(See: https://github.com/kata-containers/kata-containers/issues/10002)
This PR skips the tests until the issue is resolved.
=> k8s: Skip shared-volume relevant tests for IBM SE

tests/integration/kubernetes/confidential_kbs.sh, tests/integration/kubernetes/k8s-confidential-attestation.bats, tools/packaging/guest-image/build_se_image.sh, tools/packaging/guest-image/lib_se.sh, tools/packaging/static-build/coco-guest-components/build.sh, versions.yaml
This PR enables [k8s-confidential-attestation.bats](https://github.com/kata-containers/kata-containers/blob/main/tests/integration/kubernetes/k8s-confidential-attestation.bats) for s390x. Detailed explanation can be found in each commit message.
Fixes: #9933
For reviewers: the tests have been passing since the 27th of June at https://github.com/kata-containers/kata-containers/actions/workflows/ci-nightly-s390x.yaml
=> tests: Enable attestation e2e tests for IBM SE

tests/common.bash
This PR adds the share fs information for dragonball using kata-ctl to avoid the failures in runk tests saying that shared_fs is an unbound variable.
=> common: Add share fs information for dragonball

.github/workflows/basic-ci-amd64.yaml, src/agent/rustjail/src/process.rs, src/agent/src/rpc.rs, src/runtime-rs/crates/runtimes/virt_container/src/container_manager/io/container_io.rs, src/runtime-rs/crates/runtimes/virt_container/src/container_manager/process.rs, tests/integration/stdio/gha-run.sh, tests/integration/stdio/stdio-tests.sh
agent: 
- Close stdin when write_stdin receives data of length 0.
- Stop call notify_term_close() in close_stdin, because it could discard stdout unexpectedly.
runtime-rs:
- Instead of call agent.close_stdin in close_io, we call agent.write_stdin with 0 len data when the stdin pipe ends.
=> Fix ctr exec stuck problem

tools/packaging/kata-deploy/scripts/kata-deploy.sh
Make sure that the "skip_mount_home" flag is set in cri-o config.
Fixes: #9878
=> kata-deploy: add storage configuration for cri-o

src/agent/Cargo.lock, src/agent/Cargo.toml, src/agent/Makefile, src/agent/src/main.rs, tests/integration/kubernetes/confidential_kbs.sh, tests/integration/kubernetes/k8s-guest-pull-image-encrypted.bats, tests/integration/kubernetes/k8s-measured-rootfs.bats, tests/integration/kubernetes/lib.sh, tests/integration/kubernetes/run_kubernetes_tests.sh, tools/packaging/static-build/agent/Dockerfile
This PR mainly fixes #8111. Le's temporarily make it draft as it depends the following PRs
- #8870.  Which brings CDH, the component inside guest to decrypt image layer
- https://github.com/confidential-containers/guest-components/pull/524 and https://github.com/confidential-containers/guest-components/pull/523: let kata-agent get rid of reading aa_kbc_params from kernel cmdline
- https://github.com/confidential-containers/guest-components/pull/522 makes kata-agent built-able
Much thanks to @ChengyuZhu6 .
hi @wainersm , I use the following yaml on tdx and it succeed
```yaml
apiVersion: v1
kind: Pod
metadata:
name: busybox
annotations:
io.containerd.cri.runtime-handler: kata-qemu-tdx
spec:
runtimeClassName: kata-qemu-tdx
containers:
- name: busybox
image: …
```
=> Merge to main: supporting pull encrypted images

tests/integration/kubernetes/gha-run.sh, tests/integration/kubernetes/run_kubernetes_tests.sh, tests/integration/kubernetes/tests_common.sh
1. Avoid changing containerd settings in two different places.
2. Use GENPOLICY_PULL_METHOD=oci-distribution in gha-run.sh too, for consistency with other test files.
3. Add comment explaining why there are two different methods for pulling container images in genpolicy.
=> tests: k8s: GENPOLICY_PULL_METHOD clean-up

src/tools/genpolicy/rules.rego, src/tools/genpolicy/src/containerd.rs, src/tools/genpolicy/src/pod.rs, src/tools/genpolicy/src/policy.rs, src/tools/genpolicy/src/yaml.rs, tests/integration/kubernetes/k8s-policy-pod.bats, tests/integration/kubernetes/k8s-security-context.bats, tests/integration/kubernetes/runtimeclass_workloads/k8s-policy-pod.yaml
1. Explain better the reason for already-existing workaround in rules.rego.
2. Add genpolicy ability to create policy based on the SecurityContext.runAsUser and PodSecurityContext.runAsUser fields.
3. Add basic tests for genpolicy + these two fields.
Fixes: #8879
=> genpolicy: add support for runAsUser fields

docs/how-to/containerd-kata.md
This PR updates the cri installation guide url link in the containerd documentation guide as the previous url link does not exists.
=> docs: Update cri installion guide url in containerd documentation

.github/workflows/run-k8s-tests-on-zvsi.yaml
We missed to apply the changes of commit d8961cbd4a in the IBM SE workflow and then getting https://github.com/kata-containers/kata-containers/pull/9904 not passing CI. As this is a required change on the workflow we need to have it in a separated PR.
While here, I delinted the run-k8s-tests-on-zvsi.yaml and ran `actionlint` to ensure I'm not introducing any (obvious) bug.
=> workflows: setup environment to run auth registry tests on s390x

tests/integration/kubernetes/k8s-security-context.bats, tests/integration/kubernetes/runtimeclass_workloads/pod-security-context.yaml
1. Use a container image that supports "ps --user 1000 -f".
2. Execute that command using:
sh -c "ps --user 1000 -f"
instead of passing additional arguments to sh:
sh -c ps --user 1000 -f
Fixes: #10019
=> tests: fix ps command in k8s-security-context

src/tools/genpolicy/genpolicy-settings.json, src/tools/genpolicy/rules.rego, src/tools/genpolicy/src/policy.rs, tests/integration/kubernetes/gha-run.sh, tests/integration/kubernetes/k8s-policy-pvc.bats, tests/integration/kubernetes/tests_common.sh
=> gha: enable policy testing on TDX

docs/design/architecture/storage.md
This PR updates the devmapper docs by updating the url link for the current containerd devmapper information.
=> docs: Update devmapper docs

tests/integration/kubernetes/k8s-guest-pull-image-authenticated.bats
Since #9904 was merged, newly introduced tests for `k8s-guest-pull-image-authenticated.bats` have been failing on IBM SE (s390x). The agent fails to start because a kernel parameter cannot pass to the guest VM via annotation. To fix this, the boot image must be rebuilt with updated parameters.
This PR adds the rebuilding step in `create_pod_yaml_with_private_image()` for `qemu-se`.
=> tests: Rebuild secure boot image for guest-pull-image-authenticated for IBM SE

tests/metrics/storage/blogbench_dockerfile/Dockerfile
Move to blogbench 1.2 version from 1.1.
This version includes an important fix for the read_score test which was reported to be broken in the previous version. It essentially fixes this issue here:
https://github.com/jedisct1/Blogbench/issues/4
=> metric: Upgrade blogbench to 1.2

.github/workflows/cleanup-resources.yaml, tests/cleanup_resources.py
```
Some resource names seem to be lingering in Azure limbo but do not map
to any actual resources, so we ignore those.
```
=> ci: cleanup: Ignore nonexisting resources

src/tools/genpolicy/rules.rego, src/tools/genpolicy/src/pod.rs, src/tools/genpolicy/src/policy.rs, tests/integration/kubernetes/k8s-policy-pod.bats, tests/integration/kubernetes/runtimeclass_workloads/k8s-policy-pod.yaml, tests/integration/kubernetes/tests_common.sh
Keep track of individual exec args instead of joining them in the policy text. Verifying each arg results in a more precise policy,
because some of the args might include space characters.
This improved validation applies to commands specified in K8s YAML files using:
- livenessProbe
- readinessProbe
- startupProbe
- lifecycle.postStart
- lifecycle.preStop
=> genpolicy: container.exec_commands args validation

tests/integration/kubernetes/k8s-confidential-attestation.bats, tests/integration/kubernetes/k8s-guest-pull-image-authenticated.bats, tests/integration/kubernetes/lib.sh
It is not good practice to call repack_secure_image() from a bats file because the test code might not consider cases where `qemu-se` is used as `KATA_HYPERVISOR`.
This PR moves the function call to set_metadata_annotation() if a key includes `kernel_params` and `KATA_HYPERVISOR` is set to `qemu-se`, allowing developers to focus on the test scenario itself.
=> tests: Call repack_secure_image() in set_metadata_annotation()

src/runtime/pkg/device/api/interface.go, src/runtime/pkg/device/drivers/vfio.go, src/runtime/pkg/device/manager/manager.go, src/runtime/virtcontainers/endpoint.go, src/runtime/virtcontainers/ipvlan_endpoint.go, src/runtime/virtcontainers/macvlan_endpoint.go, src/runtime/virtcontainers/macvtap_endpoint.go, src/runtime/virtcontainers/network_linux.go, src/runtime/virtcontainers/physical_endpoint.go, src/runtime/virtcontainers/physical_endpoint_test.go, src/runtime/virtcontainers/tap_endpoint.go, src/runtime/virtcontainers/tuntap_endpoint.go, src/runtime/virtcontainers/veth_endpoint.go, src/runtime/virtcontainers/vhostuser_endpoint.go, src/runtime/virtcontainers/vhostuser_endpoint_test.go
network: Implement hotplug for physical endpoints
Enable physical network interfaces to be hotplugged.
For this, we need to change the signature of the HotAttach method
to make use of Sandbox instead of Hypervisor. Similar approach was
followed for Attach method, but this change was overlooked for
HotAttach.
The signature change is required in order to make use of
device manager and receiver for physical network
enpoints.
Fixes: #8405
=> Implement hotplug support for physical endpoints

src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs, src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container_inner.rs, src/runtime-rs/crates/runtimes/virt_container/src/container_manager/manager.rs
When create container failed, it should cleanup the container thus there's no device/resource left.
Fixes: #10044
=> runtime-rs: container: fix the issue of missing cleanup container

tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml, tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
This PR updates the Blogbench reference values for read and write operations used in the CI check metrics job.
This is due to the update to version 1.2 of blobench.
Fixes: #10039
=> metrics: update avg reference values for blogbench.

tests/integration/kubernetes/k8s-credentials-secrets.bats
Add policy to pod-secret-env.yaml from k8s-credentials-secrets.bats.
Policy was already auto-generated for the other pod used by the same test (pod-secret.yaml). pod-secret-env.yaml was inconsistent, because it was taking advantage of the "allow all" policy built into the Guest image. Sooner or later, CI Guests for CoCo will not get the "allow all" policy built in anymore and pod-secret-env.yaml would have stopped working then.
Note that pod-secret-env.yaml continues to use an "allow all" policy after these changes. #10033 must be solved before a more restrictive policy will be generated for pod-secret-env.yaml.
=> tests: k8s-credentials-secrets: policy for second pod

tests/integration/kubernetes/k8s-guest-pull-image-authenticated.bats, tests/integration/kubernetes/lib.sh
Currently, we have found that `assert_logs_contain` does not work on TDX. We manually located the specific log, but it fails to get the log using `kubectl debug`. The error found in CI is:
```
warning: couldn't attach to pod/node-debugger-984fee00bd70.jf.intel.com-pdgsj,
falling back to streaming logs: error stream protocol error: unknown error
```
Upon debugging the TDX CI machine, we found an error in containerd:
```
Attach container from runtime service failed" err="rpc error: code = InvalidArgument desc = tty and stderr cannot both be true"
containerID="abc8c7a546c5fede4aae53a6ff2f4382ff35da331bfc5fd3843b0c8b231728bf"
```
We believe this is the root cause of the test failures in TDX CI. Therefore, we need to ensure that tty and stderr are not set to true at same time.
Fixes: #10011
=> tests: Fix missing log on TDX

tools/packaging/kata-deploy/local-build/Makefile, tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
Build a GPU flavoured dragonball kernel
Depends on: ~~#9967~~
=> dragonball: kernel gpu dragonball 6.1.x

tools/osbuilder/initrd-builder/initrd_builder.sh
Initramfs expects /init, create symlink only if ${ROOTFS}/init does not exist Init may be provided by other packages, e.g. systemd or GPU initrd/rootfs
=> gpu: rootfs/initrd build init

tests/metrics/time/launch_times.sh
This PR updates the metrics launch times to use grep -F instead of fgrep as this command has been deprecated.
=> metrics: Update launch times to use grep -F

tools/osbuilder/rootfs-builder/rootfs.sh, tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in
For the GPU build we need go/rust and some other helpers to build the rootfs.
=> gpu: rootfs ubuntu build expansion

src/runtime-rs/crates/hypervisor/ch-config/src/convert.rs, src/runtime-rs/crates/hypervisor/src/qemu/inner.rs, src/runtime-rs/crates/hypervisor/src/qemu/mod.rs, src/runtime-rs/crates/hypervisor/src/qemu/qmp.rs
A rather standard memory hotplugging implementation, the only slightly unusual thing about it is that it makes a best-effort attempt at hotunplugging, too.  While hotunplugging memory seems to fail generally I'd like to have it in the code base at least for a while for observation.  It does no harm either.
=> runtime-rs: add memory hotplugging support to qemu-rs

.github/workflows/run-kata-coco-tests.yaml
This PR increases the timeout for running the CoCo tests to avoid random failures. These failures occur when the action `Run tests` times out after 30 minutes, causing the CI to fail.
Fixes: #10062
=> gha: Increase timeout to run CoCo tests

src/tools/genpolicy/src/config_map.rs, src/tools/genpolicy/src/pod.rs, src/tools/genpolicy/src/secret.rs, tests/integration/kubernetes/k8s-policy-pod.bats, tests/integration/kubernetes/runtimeclass_workloads/k8s-policy-configmap.yaml, tests/integration/kubernetes/runtimeclass_workloads/k8s-policy-pod.yaml
This change adds support for the `envFrom` field in the `Pod` resource
=> genpolicy: Add support for envFrom

tests/integration/kubernetes/k8s-attach-handlers.bats, tests/integration/kubernetes/k8s-caps.bats, tests/integration/kubernetes/k8s-configmap.bats, tests/integration/kubernetes/k8s-copy-file.bats, tests/integration/kubernetes/k8s-cpu-ns.bats, tests/integration/kubernetes/k8s-credentials-secrets.bats, tests/integration/kubernetes/k8s-custom-dns.bats, tests/integration/kubernetes/k8s-env.bats, tests/integration/kubernetes/k8s-file-volume.bats, tests/integration/kubernetes/k8s-number-cpus.bats, tests/integration/kubernetes/k8s-optional-empty-configmap.bats, tests/integration/kubernetes/k8s-security-context.bats, tests/integration/kubernetes/k8s-shared-volume.bats, tests/integration/kubernetes/tests_common.sh
Share a single test script variable for both:
- Allowing a command to be executed using Policy settings.
- Executing that command using "kubectl exec".
Fixes: #10014
=> tests: k8s: reuse policy exec variable

src/runtime-rs/crates/agent/src/kata/mod.rs, src/runtime-rs/crates/agent/src/sock/vsock.rs, src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
we need more friendly logs for debugging agent conntion cases when kata pods fail.
Fixes #10057
=> runtime-rs: enhance debug info for agent connect.

src/agent/src/device.rs, src/agent/src/linux_abi.rs, src/agent/src/netlink.rs, src/agent/src/rpc.rs, tests/integration/nerdctl/gha-run.sh
agent: Bring interface down before renaming it.
In case we are dealing with multiple interfaces and there exists a
network interface with a conflicting name, we temporarily rename it to
avoid name conflicts.
Before doing this, we need to rename bring the interface down.
Failure to do so results in netlink returning Resource busy errors.
The resource needs to be down for subsequent operation when the name is
swapped back as well.
This solves the issue of passing multiple networks in case of nerdctl
as:
nerdctl run --rm  --net foo --net bar docker.io/library/busybox:latest ip a
Fixes: #9900    
=> Fix issue while adding multiple networks with nerdctl

tools/osbuilder/rootfs-builder/rootfs.sh
Let's ensure at least 50% of the memory is used for /run, as systemd by default forces it to be 10%, which is way too small even for very small workloads.
This is only done for the rootfs-confidential image.
This is built atop of https://github.com/kata-containers/kata-containers/pull/7016, thus I'm keeping Alex's Signed-off-by, and also Chengyu's and Arron's as the approach taken is closer to what we have downstream.
=> tee: osbuilder: Set /run to use 50% of the image with systemd

src/tools/genpolicy/genpolicy-settings.json, src/tools/genpolicy/rules.rego, src/tools/genpolicy/src/policy.rs, src/tools/genpolicy/src/settings.rs, tests/integration/kubernetes/k8s-exec.bats, tests/integration/kubernetes/k8s-policy-pod.bats, tests/integration/kubernetes/tests_common.sh
Generate policy that validates each exec command line argument, instead of joining those args and validating the resulting string. Joining the args ignored the fact that some of the args might include space characters.
The older format from genpolicy-settings.json was similar to:
"ExecProcessRequest": {
"commands": [
"sh -c cat /proc/self/status"
],
"regex": []
},
That format will not be supported anymore. genpolicy will detect if its users are trying to use the older "commands" field and will exit with a relevant error message in that case.
The new settings format is:
"ExecProcessRequest": {
"allowed_commands": [
[
"sh",
"-c",
"cat /proc/self/status"
]
],
"regex": []
},
=> genpolicy: validate each exec command line arg

tests/integration/kubernetes/k8s-exec-rejected.bats, tests/integration/kubernetes/k8s-policy-hard-coded.bats, tests/integration/kubernetes/k8s-policy-pod.bats, tests/integration/kubernetes/run_kubernetes_tests.sh, tests/integration/kubernetes/runtimeclass_workloads/k8s-policy-hard-coded.yaml, tests/integration/kubernetes/tests_common.sh
1. Avoid potential word splitting in k8s-policy-pod.bats.
2. Allow the users of AUTO_GENERATE_POLICY=yes to easily execute the hard-coded policy tests on any platform.
3. Rename k8s-exec-rejected.bats to k8s-policy-hard-coded.bats, thus getting ready to test in the future additional types of hard-coded policies by using the same test script.
=> tests: k8s: minor policy tests clean-up

src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container_inner.rs, src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
Since stop sandbox would be called in multi path,
thus it's better to set and check the sandbox's state.
=> runtime-rs : fix the issue of stop sandbox

.github/workflows/build-kata-static-tarball-s390x.yaml, .github/workflows/publish-kata-deploy-payload-s390x.yaml, .github/workflows/release-s390x.yaml, .github/workflows/run-cri-containerd-tests-s390x.yaml, .github/workflows/run-k8s-tests-on-zvsi.yaml
As suggested in #9934, the following hooks have been introduced for s390x runners:
- ACTIONS_RUNNER_HOOK_JOB_STARTED
- ACTIONS_RUNNER_HOOK_JOB_COMPLETED
These hooks will perfectly replace the existing {pre,post}-action scripts. This commit wipes out all GHA steps for s390x where the actions are triggered.
Verification result: https://github.com/BbolroC/kata-containers/actions/runs/10163515657
=> gha: Eradicate {pre,post}-action steps for s390x runners

tests/integration/kubernetes/k8s-nginx-connectivity.bats
Fixes Issue https://github.com/kata-containers/kata-containers/issues/10100
Changing the busybox_image from docker to quay to fix rate limit errors on k8s-nginx-connectivity.bats
=> ci: Fix rate limit error by migrating busybox_image

.github/workflows/run-k8s-tests-on-zvsi.yaml
In #10096, a cleanup step for kata-deploy is removed by mistake. This leads to a cleanup error in the following `Complete job` step.
This PR restores the removed step to resolve the current CI failure on s390x.
FYI: The error is being handled by a script triggered by ACTIONS_RUNNER_HOOK_JOB_COMPLETED.
=> gha: Restore cleanup-zvsi for s390x

tests/integration/kubernetes/gha-run.sh, versions.yaml
Currently, there are some issues with pulling images in CI, such as : https://github.com/kata-containers/kata-containers/actions/runs/10109747602/job/27959198585
This issue is caused by switching between different snapshotters for the same image in some scenarios. To resolve it, we can check existing images to ensure all content is available locally before running tests.
We also have some patches (https://github.com/containerd/nydus-snapshotter/pull/605, https://github.com/containerd/nydus-snapshotter/pull/609) in the nydus snapshotter to stabilize our CI. 
Fixes: #10029
=> tests: add image check before running coco tests

.github/workflows/run-k8s-tests-on-zvsi.yaml
This PR adds a new CI job for qemu-runtime-rs to the existing zvsi Kubernetes test matrix.
But it should be merged if the current regression for qemu-runtime-rs on x86_64 is resolved by https://github.com/kata-containers/kata-containers/pull/10052.
It was verified that the new CI job passes on the self-hosted runner: https://github.com/BbolroC/kata-containers/actions/runs/10081693643/job/27880051619
=> GHA: Run k8s e2e tests for qemu-runtime-rs on s390x

versions.yaml
Bump trustee to the latest to fix error with pulling busybox from dockerhub.
related PR in trustee: https://github.com/confidential-containers/trustee/pull/452
Fixes: #10109
=> version: bump trustee version

.github/workflows/payload-after-push.yaml, tools/packaging/release/release.sh
It's been a reasonable time that we're not able to even build arm64 artefacts.
For now I am removing the builds as it doesn't make sense to keep running failing builds, and those can be re-enabled once we have arm64 machines plugged in that can be used for building the stuff, and maintainers for those machines.
The `arm-jetson-xavier-nx-01` is also being removed from the runners.
Looped in @ananos  and @zvonkok  to make them aware of the situation.
=> ci: Temporarily remove arm64 builds

tests/metrics/density/fast_footprint.sh, tests/metrics/density/footprint_data.sh
This PR updates the memory tests like fast footprint to use grep -F instead of fgrep as this command has been deprecated.
=> metrics: Update memory tests to use grep -F

tools/packaging/release/release.sh
Let's remove what we commented out, as publish manifest complains:
```
Created manifest list quay.io/kata-containers/kata-deploy-ci:kata-containers-latest
./tools/packaging/release/release.sh: line 146: --amend: command not found
```
=> ci: Temporarily remove arm64 builds -- part II

utils/kata-manager.sh
We've done something quite similar for kata-deploy, but I've noticed we forgot about the kata-manager counterpart.
Here you can find results (and how to test) without the patch and with the patch:
* without: https://gist.github.com/fidencio/b95fa4ea34e8f10e18dde4eabf18327d
* with: https://gist.github.com/fidencio/368211840813afe6ae41df60264e4f07
@GabyCT, @cmaf, @dborquez, could you give it a try on your TDX machines?
=> kata-manager: Ensure distro specific TDX config is set

tests/integration/kubernetes/gha-run.sh
This will help to avoid huge logs, and allow us to debug issues in a better way.
I've requested the review of the ones who have baremetal machines which will be affected by this.
=> tests: k8s: Rotate & cleanup journal for every run

tests/integration/kubernetes/confidential_kbs.sh
This PR adds missing packages depenencies to install kbs cli in a fresh new baremetal environment. This will avoid to have a failure when trying to run install-kbs-client.
=> tests: kbs: Add missing dependencies to install kbs cli

tests/integration/kubernetes/tests_common.sh
The issue is similar to #10011.
The root cause is that tty and stderr are set to true at same time in containerd: #10031.
Fixes: #10081
=> tests: Fix error with `kubectl debug`

.github/workflows/ci.yaml, .github/workflows/payload-after-push.yaml, tools/packaging/release/release.sh
We're basically reverting c5dad991cecdeb3a3fe404694c636fc1ce1a282e and e9710332e74bca35a28f432bd4c9af1c353d5eb1, and enabling the builders to run on `pull_request_event`, avoiding then future breakages as those would be caught before content gets merged.
Right now 2 VMs have been added to the CI as builders (with 2 more to be added), and I'm assuming @ananos and @zvonkok will be the maintainers of those.
=> ci: re-enable arm CI

.github/workflows/ci.yaml
When re-enabling those we'll need a smart way to do so, as this limit of 20 workflows referenced is just ... weird.
However, for now, it's more important to add the jobs related to the new platforms than keep the ones that are actively disabled.
=> ci: Remove jobs that are not running

tests/integration/kubernetes/k8s-guest-pull-image-encrypted.bats
After experimenting a little bit with those tests, they seem to be passing on all the available TEE machines.
With this in mind, let's just enable them for those machines.
=> ci: Enable encrypted image tests for TEEs

src/tools/genpolicy/.gitignore, src/tools/genpolicy/Cargo.toml, src/tools/genpolicy/Makefile, src/tools/genpolicy/src/main.rs, src/tools/genpolicy/src/utils.rs, src/tools/genpolicy/src/version.rs.in
- Add --version flag to the genpolicy tool that prints the current version
- Add version.rs.in template to store the version information
- Update makefile to autogenerate version.rs from version.rs.in
- Add license to Cargo.toml
This follows a [similar patter used in the agent](https://github.com/kata-containers/kata-containers/blob/main/src/agent/src/main.rs#L332)
Cherry pick from https://github.com/microsoft/kata-containers/pull/176
=> genpolicy: add --version flag

tests/common.bash, tests/integration/kubernetes/gha-run.sh, tools/packaging/kata-deploy/helm-chart/Makefile, tools/packaging/kata-deploy/helm-chart/kata-deploy/.helmignore, tools/packaging/kata-deploy/helm-chart/kata-deploy/Chart.yaml, tools/packaging/kata-deploy/helm-chart/kata-deploy/templates/_helpers.tpl, tools/packaging/kata-deploy/helm-chart/kata-deploy/templates/kata-deploy.yaml, tools/packaging/kata-deploy/helm-chart/kata-deploy/templates/kata-rbac.yaml, tools/packaging/kata-deploy/helm-chart/kata-deploy/values.yaml, tools/packaging/kata-deploy/scripts/kata-deploy.sh, versions.yaml
For easier handling of kata-deploy we can leverage a Helm chart to get rid of all the base and overlays for the various components
=> kata-deploy: Add Helm Chart

docs/design/kata-guest-image-management-design.md, src/runtime/virtcontainers/kata_agent.go
Our code for handling images being pulled inside the guest relies on a containerType ("sandbox" or "container") being set as part of the container annotations, which is done by the CRI Engine being used, and depending on the used CRI Engine we check for a specfic annotation related to the image-name, which is then passed to the agent.
However, when running kata-containers without kubernetes, specifically when using `nerdctl`, none of those annotations are set at all.
One thing that we can do to allow folks to use `nerdctl`, however, is to take advantage of  the  `--label` flag, and document on our side that users must pass `io.kubernetes.cri.image-name=$image_name` as part of the labels.
By doing this, and changing our "fallback" so we can always look for such annotation, we ensure that …
=> runtime: image-pull: Make it work with nerdctl

src/tools/genpolicy/Cargo.lock, src/tools/genpolicy/Cargo.toml, src/tools/genpolicy/Makefile, src/tools/genpolicy/src/mount_and_storage.rs, src/tools/genpolicy/src/policy.rs, src/tools/genpolicy/src/registry.rs, src/tools/genpolicy/tests/main.rs, src/tools/genpolicy/tests/testdata/copyfile/pod.yaml, src/tools/genpolicy/tests/testdata/copyfile/testcases.json, src/tools/genpolicy/tests/testdata/createsandbox/pod.yaml, src/tools/genpolicy/tests/testdata/createsandbox/testcases.json, tools/packaging/static-build/tools/Dockerfile
Provides a test runner that generates a policy and validates it with canned requests. The initial set of test cases is mostly for illustration and will be expanded incrementally.
Fixes: #10061
---
cc @danmihai1 & @Redent0r 
Please let me know how I should integrate this into the larger testing strategy of Kata:
* How should this be added to the Makefile? I'm just using `cargo test` and don't quite understand the relationships of the Makefile.
* Should this be added to a GitHub Action?
=> genpolicy: add crate-scoped integration test

tools/packaging/scripts/configure-hypervisor.sh, tools/packaging/static-build/qemu/Dockerfile
The kata containers hypervisior qemu configuration supports setting `block_device_aio="native"`, but the kata static build of qemu does not add the linux aio feature.
The `libaio-dev` library is a necessary dependency for building qemu with linux aio.
Fixes: #10130
=> tools: Support for building qemu with linux aio

tests/integration/kubernetes/tests_common.sh
This PR updates the image that we are using in the kubectl debug command as part of the exec host function, as the current alpine image does not allow to create a temporary file for example and creates random kubernetes failures.
=> tests:k8s: Update image in kubectl debug for the exec host function

src/runtime-rs/crates/hypervisor/src/qemu/cmdline_generator.rs, src/runtime/pkg/govmm/qemu/qemu.go, src/runtime/pkg/govmm/qemu/qemu_arch_base_test.go, src/runtime/pkg/govmm/qemu/qemu_s390x_test.go, src/runtime/pkg/govmm/qemu/qemu_test.go
This parameter has been deprecated for a long time and QEMU 9.1.0 finally removes it.
Fixes: #10112
=> qemu: don't emit scsi parameter

tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
- At the moment we aren't factoring in the kata version on our caches, so it means that when we bump this just before release, we don't rebuilt components that pull in the VERSION content, so the release build ends up with incorrect versions in it's binaries
Fixes: #10092
=> ci: cache: Include kata version in artefact versions

tests/integration/kubernetes/runtimeclass_workloads/stress/Dockerfile
This PR updates the ubuntu image for stress Dockerfile. The main purpose is to have a more updated image compared with the one that is in libpod which has not been updated in a while.
=> tests: Update ubuntu image for stress Dockerfile

tests/stability/kubernetes_stressng.sh, tests/stability/runtimeclass_workloads/stress-test.yaml
This PR adds kubernetes stress-ng tests as part of the stability testing for kata.
=> tests: Add kubernetes stress-ng tests

tests/integration/kubernetes/k8s-file-volume.bats
This PR disables the k8s file volume test as we are having random failures in multiple GHA CIs mainly because the exec_host function sometimes does it not work properly.
=> tests: Disable k8s file volume test

src/runtime-rs/crates/hypervisor/src/ch/inner.rs, src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs, src/runtime-rs/crates/hypervisor/src/ch/mod.rs, src/runtime-rs/crates/hypervisor/src/dragonball/inner.rs, src/runtime-rs/crates/hypervisor/src/dragonball/inner_device.rs, src/runtime-rs/crates/hypervisor/src/dragonball/mod.rs, src/runtime-rs/crates/hypervisor/src/dragonball/vmm_instance.rs, src/runtime-rs/crates/hypervisor/src/firecracker/inner.rs, src/runtime-rs/crates/hypervisor/src/firecracker/inner_hypervisor.rs, src/runtime-rs/crates/hypervisor/src/firecracker/mod.rs, src/runtime-rs/crates/hypervisor/src/lib.rs, src/runtime-rs/crates/hypervisor/src/qemu/inner.rs, src/runtime-rs/crates/hypervisor/src/qemu/mod.rs
Add the wait_vm method for hypervisors. This is a
prerequisite for sandbox api support.
Fixes: #7043
=> runtime-rs: Add the wait_vm support for hypervisors

src/tools/genpolicy/genpolicy-settings.json, src/tools/genpolicy/rules.rego, src/tools/genpolicy/tests/testdata/copyfile/testcases.json, src/tools/genpolicy/tests/testdata/createsandbox/testcases.json
This PR backports the commits mentioned in #10046, except for the symlink source (which I don't quite understand yet) and the sandbox storage checks (which are likely blocked by #8833). The commit messages each have a rationale for why this hardening makes sense.
cc @danmihai1
=> genpolicy: hardening some agent requests

tools/osbuilder/dracut/Dockerfile.in, tools/packaging/static-build/qemu/Dockerfile
docker prints warning when building QEMU builder image.
```
1 warning found (use docker --debug to expand):
- ConsistentInstructionCasing: Command 'from' should match the case of the command majority (uppercase) (line 5)
```
All commands within the Dockerfile should use the same casing (either upper or lower).
Docker build checks doc: https://docs.docker.com/reference/build-checks/consistent-instruction-casing/
=> tools: Fix container image build warning

tests/integration/kubernetes/k8s-file-volume.bats, tests/integration/kubernetes/tests_common.sh
The `exec_host()` function often fails to capture the output of a given command because the node debugger pod is prematurely terminated. To address this issue, the function has been refactored to ensure consistent output capture by adjusting the `kubectl debug` process as follows:
- Keep the node debugger pod running
- Wait until the pod is fully ready
- Execute the command using `kubectl exec`
- Capture the output and terminate the pod
This PR refactors `exec_host()` to implement the above steps, improving its reliability. And it reverts #10156 as well.
Fixes: #10081
=> tests: Ensure exec_host() consistently captures command output

tools/packaging/kata-deploy/scripts/kata-deploy.sh
This reverts commit 8d9bec2e015f20126a84bc474e35ecf748f53d98, as it causes issues in the operator and kata-deploy itself, leading to the node to be NotReady.
=> Revert "ci: add reset_runtime to cleanup"

tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in
Remove the duplicate package "xz-utils".
=> osbuilder: fix typo in ubuntu rootfs depends

tests/integration/kubernetes/gha-run.sh
Instead of deploying and removing the snapshotter on every single run, let's make sure the snapshotter is always deploy on the TDX case.
We're doing this as an experiment, in order to see if we'll be able to reduce the failures we've been facing with the nydus snapshotter.
=> ci: nydus: Treat the snapshotter as a dependency

tools/packaging/kata-deploy/scripts/kata-deploy.sh
For the cases where containerd_conf_file does not exist, cp will fail and let the pod in Error state.
=> kata-deploy: fix kata-deploy reset

versions.yaml
This reverts commit d35320472c9db9e706979289d36e53fcbc60e8d8.
Although the commit in question does solve an issue related to the usage of busybox from docker.io, as it's reasonably easy to hit the rate limit, the commit also brings in functionalities that are causing issues in, at least, the TDX CI, such as:
```sh
[2024-08-16T16:03:52Z INFO  actix_web::middleware::logger] 10.244.0.1 "POST /kbs/v0/attest HTTP/1.1" 401 259 "-" "attestation-agent-kbs-client/0.1.0" 0.065266
[2024-08-16T16:03:53Z INFO  kbs::http::attest] Auth API called.
[2024-08-16T16:03:53Z INFO  actix_web::middleware::logger] 10.244.0.1 "POST /kbs/v0/auth HTTP/1.1" 200 74 "-" "attestation-agent-kbs-client/0.1.0" 0.000169
[2024-08-16T16:03:54Z INFO  kbs::http::attest] Attest API called.
[2024-08-16T16:03:54Z INFO …
```
=> Revert "version: bump trustee version"

src/runtime/virtcontainers/kata_agent.go, tests/integration/kubernetes/k8s-guest-pull-image.bats
Improved error handling to provide clearer feedback on request failures.
Fixes: #10173 -- part II
=> runtime: Add specific error message for gRPC request timeouts

src/tools/genpolicy/genpolicy-settings.json, src/tools/genpolicy/src/cronjob.rs, src/tools/genpolicy/src/daemon_set.rs, src/tools/genpolicy/src/deployment.rs, src/tools/genpolicy/src/job.rs, src/tools/genpolicy/src/mount_and_storage.rs, src/tools/genpolicy/src/pod.rs, src/tools/genpolicy/src/registry.rs, src/tools/genpolicy/src/registry_containerd.rs, src/tools/genpolicy/src/replica_set.rs, src/tools/genpolicy/src/replication_controller.rs, src/tools/genpolicy/src/settings.rs, src/tools/genpolicy/src/stateful_set.rs, src/tools/genpolicy/src/yaml.rs, tests/integration/kubernetes/k8s-policy-deployment.bats, tests/integration/kubernetes/run_kubernetes_tests.sh, tests/integration/kubernetes/runtimeclass_workloads/k8s-policy-deployment.yaml
Add bind mounts for volumes defined by docker container images, unless those mounts have been defined in the input K8s YAML file too.
For example, quay.io/opstree/redis defines two mounts:
/data
/node-conf
Before these changes, if these mounts were not defined in the YAML file too, the auto-generated policy did not allow this container image to start.
=> genpolicy: add bind mounts for image volumes

src/agent/rustjail/src/container.rs
Container/Sandbox clean up should not fail if root FS is not mounted for some reason.
Fixes: https://github.com/kata-containers/kata-containers/issues/10166
When running the remote hypervisor, the sandbox is not properly stopped since there are errors destroying the pause container. These errors happen because pause container root fs is not mounted (see [line](https://github.com/kata-containers/kata-containers/blob/3.7.0/src/agent/src/image.rs#L146)).  This PR handles EINVAL errors when umount2 is called.
```
024/08/13 17:54:54 [adaptor/proxy] StartContainer: containerID:3f363c9b05624badc5eb1adbf8b79d2125acb5b80dd93063f5bec942d69db139
2024/08/13 17:56:36 [adaptor/proxy] RemoveContainer: containerID:3f363c9b05624badc5eb1adbf8b79d2125acb5b80dd93063f5bec942d69db139
2024/08/13 17:56:36 …
```
=> agent: Handle EINVAL error when umounting container rootfs

.github/workflows/basic-ci-amd64.yaml, tests/integration/stdio/gha-run.sh
I assume the PR that introduced this was based on an older version of yq, and as the test couldn't run before it got merged we never noticed the error.
However, this test has been failing for a reasonable amount of time, which makes me think that we either need a maintainer for it, or just remove it completely, but that's a discussion for another day.
For now, let's make it, at least, run.
=> ci: stdio: Fix typo on getting the containerd version

tools/packaging/kata-deploy/helm-chart/kata-deploy/templates/kata-deploy.yaml, tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml, tools/packaging/kata-deploy/scripts/kata-deploy.sh
All the supported versions of containerd and CRI-O do support setting the full runtime path via the `runtime_path` field.  Let's take advantage of that and avoid having to access `/usr/local/bin` and create symlinks there.
=> kata-deploy: Stop symlinking into /usr/local/bin

tests/integration/kubernetes/confidential_kbs.sh
The deploy-kbs.sh script generates the kbs.key that's used to install KBS. This same file is used lately by kbs-client to authenticate. This ensures that the file was created, otherwise fail.
Another problem solved here is that on bare-metal machines the key doesn't survive a reboot as it is created in a temporary directory (/tmp/trustee). So let's save the file to a non-temporary location.
=> tests/k8s: check and save kbs.key

src/tools/genpolicy/genpolicy-settings.json, src/tools/genpolicy/rules.rego, src/tools/genpolicy/src/policy.rs, tests/integration/kubernetes/tests_common.sh
* genpolicy: deny UpdateEphemeralMountsRequest
Deny UpdateEphemeralMountsRequest by default, because paths to critical Guest components can be redirected using such request.
Upstreaming from https://github.com/microsoft/kata-containers/pull/126
=> genpolicy: deny UpdateEphemeralMountsRequest

tests/metrics/machine_learning/openvino.sh
This PR removes an unused variable in the openvino script for kata metrics.
=> metrics: Remove unused variable in openvino script

tools/packaging/kata-deploy/scripts/kata-deploy.sh
In order to ensure that the cleanup action won't cause any harm or lead to a misconfiguration, let's re-work the "common to the actions" part of the script so file creations are only done during the specific actions.
=> kata-deploy: Rework the logic a little bit

tests/integration/kubernetes/gha-run.sh
This reverts commit 41b7577f08da85a7507d106de7068121019c42e2.
We were seeing a lot of issues in the TDX CI of the nature:
"Error: failed to create containerd container: create instance
470: object with key "470" already exists: unknown"
With the TDX CI, we moved to having the nydus snapsotter pre-installed. Essentially the `deploy-snapshotter` step was performed once before any actual CI runs.
We were seeing failures related to the error message above.
On reverting this change, we are no longer seeing errors related to "key exists" with the TDX CI passing now.
The change reverted here is related to downloading incomplete images, but this seems to be messing up TDX CI.
It is possible to pass --snapshotter to `ctr image check` but that does not seem to have any effect on the data set …
=> Revert "tests: add image check before running coco tests"

tests/integration/kubernetes/k8s-guest-pull-image.bats, tests/integration/kubernetes/lib.sh
While resolving an issue for IBM SE after #9999 was merged, some test setups required patching.
This PR includes the following changes:
- Load confidential_kbs.sh in k8s-guest-pull-iamge.bats
- Introduce wait_time to k8s_create_pod()
Each commit message provides a detailed explanation for these changes.
=> tests: Fix k8s test issues on s390x

docs/how-to/how-to-set-sandbox-config-kata.md, src/agent/README.md, src/agent/src/cdh.rs, src/agent/src/config.rs, src/runtime-rs/config/configuration-rs-fc.toml.in, src/runtime/config/configuration-acrn.toml.in, src/runtime/config/configuration-clh.toml.in, src/runtime/config/configuration-fc.toml.in, src/runtime/config/configuration-qemu-coco-dev.toml.in, src/runtime/config/configuration-qemu.toml.in, src/runtime/config/configuration-stratovirt.toml.in, src/runtime/pkg/katautils/config.go, src/runtime/virtcontainers/kata_agent.go, src/runtime/virtcontainers/pkg/annotations/annotations.go
In `k8s-guest-pull-image.bats`, a container sometimes fails to start due to the following error:
```
Message:   failed to create containerd task: failed to create shim task: ttrpc err: Receive packet timeout Elapsed(())
```
This issue occurs when fulfilling volume mounts for a large image (https://github.com/kata-containers/kata-containers/actions/runs/10465537902/job/28980940906). 
It was identified that CDH_API_TIMEOUT (default: 50s) influences this situation. 
This PR makes the variable configurable so that the timeout can be adjusted on the fly via annotations.
=> agent/config: Make CDH_API_TIMEOUT configurable

utils/kata-manager.sh
To do so, use a test image from quay.io instead of docker.io.
=> kata-manager: Avoid docker rate-limit

tests/metrics/machine_learning/README.md
This PR adds the OpenVINO benchmark general information into the machine learning README metrics information.
=> metrics: Add OpenVINO general information into README

tests/stability/kubernetes_soak_test.sh, tests/stability/runtimeclass_workloads/pod-deployment.yaml
This PR adds a kubernetes parallel test that will launch multiple replicas from a kubernetes deployment and we will iterate this multiple times to verify that we are able to do this using CoCo Kata. This test will be part of the CoCo Kata stability CI.
=> stability: Add kubernetes parallel test

src/runtime/pkg/katautils/config.go
=> runtime: Allow machine_type in kata config for remote hypervisors

tests/gha-run-k8s-common.sh, tests/integration/kubernetes/setup.sh, tests/integration/kubernetes/tests_common.sh
GH-9592 addressed a bug in a previous version of the AKS Mariner host kernel that blocked the CH v39 upgrade. This bug has now been fixed so we undo that PR.
Fixes: #9594
=> ci: reinstate Mariner host and guest kernel

.github/workflows/ci-coco-stability.yaml, .github/workflows/ci-weekly.yaml
This PR adds a GHA workflow to run Kata CoCo weekly stablity tests.
=> gha: Add GHA workflow to run Kata CoCo stability tests

tests/metrics/machine_learning/README.md
This PR adds the oneDNN benchmark information to the machine learning metrics README.
=> docs: Add oneDNN benchmark information to metrics README

src/tools/genpolicy/src/pod.rs, tests/integration/kubernetes/k8s-policy-pod.bats, tests/integration/kubernetes/runtimeclass_workloads/k8s-policy-pod.yaml, tests/integration/kubernetes/runtimeclass_workloads/k8s-priority-class.yaml, tests/integration/kubernetes/setup.sh
This allows generation of policy for pods specifying priority classes.
Cherry pick from https://github.com/microsoft/kata-containers/pull/145
=> genpolicy: add priorityClassName as a field in PodSpec interface

src/agent/Cargo.toml
This commit includes a fix for pulling an image on platforms that do not support xattr.
Some platforms/file-systems do not support xattrs, this would make the image pull fail because of failing to set xattr. This commit will check whether the target path supports xattr. If yes, the unpacking will maintain xattrs; if not, it will not set xattrs.
=> agent: image-rs: check xattrs for image unpacking

tests/metrics/machine_learning/onednn.sh
This PR removes an unused variable in oneDNN metrics benchmark.
=> metrics: Remove unused variable in oneDNN benchmark

src/agent/src/policy.rs
slog's is_enabled() is documented as:
- "Best effort", and
- Sometime resulting in false positives.
Use AGENT_CONFIG.log_level.as_usize() instead, to avoid those false positives.
=> agent: avoid policy.txt log without debug enabled

tools/packaging/kata-deploy/helm-chart/kata-deploy/templates/kata-deploy.yaml, tools/packaging/kata-deploy/helm-chart/kata-deploy/values.yaml, tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml, tools/packaging/kata-deploy/scripts/kata-deploy.sh
Although we keep building Kata Containers using `PREFIX=/opt/kata`, this option allows the user to use any `INSTALLATION_PREFIX`, which will result in Kata Containers being deployed under `${INSTALLATION_PREFIX}/opt/kata`.
There's some "magic" done with qemu in order to make it work, so, please, carefully check each commit and its commit log / commit message.
`quay.io/fidencio/kata-deploy:installation_prefix` is an image that can be used for testing.
=> kata-deploy: helm: Add INSTALLATION_PREFIX

src/agent/src/cdh.rs, src/agent/src/main.rs, src/agent/src/rpc.rs
- Introduced a global `CDH_CLIENT` instance to hold the cdh client and implemented `init_cdh_client` function to initialize the cdh client if not already set.
- Move `unseal_env` and `secure_mount` functions on the global `CDH_CLIENT` instance to access the CDH client.
- Decouple the cdh client from AgentService and refactor cdh client usage and initialization in kata-agent.
Fixes: #10231
=> agent:cdh: Refactor CDHClient usage and initialization

tests/common.bash, tests/integration/kubernetes/gha-run.sh, tools/packaging/kata-deploy/helm-chart/kata-deploy/templates/post-delete-job.yaml, tools/packaging/kata-deploy/scripts/kata-deploy.sh, versions.yaml
**DO NOT ADD THE `ok-to-test` LABEL**
Folks,
This PR brings in several changes that will solve the issues we've been facing with helm, and this one has to be **extensively** tested, unfortunaly also manually tested, before adding the `ok-to-test` label.
The uninstall issue, which is the one I've spent some time working on, basically happens because `helm` does not wait for one operation to finish before calling the second operation. But what does it really mean? :-)
Let's take a look at the installation flow with `helm`, **before this PR**.
* `helm install` is called
* `kata-rbac` is deployed
* `kata-deploy` daemonset is deployed
* `helm uninstall` is called
* `kata-deploy` daemonset is deleted
* this daemonset has a `lifecycle.preStop`  hook, which calls the `kata-deploy.sh` script …
=> helm: Several fixes, including some reasonable re-work on kata-deploy.sh script

src/runtime/pkg/katautils/config.go
This error is specific to SNP platforms, so let's make sure we only error this out when an SNP platform is used.
=> runtime: Don't error out about SNP cert path on non SNP platforms

.github/workflows/run-k8s-tests-on-zvsi.yaml, tests/integration/kubernetes/confidential_kbs.sh
`KBS` deployment has been missed for `qemu-coco-dev` on s390x. Let's enable it!
=> gha: Turn on KBS for qemu-coco-dev on s390x

versions.yaml
This PR updates the firecracker version to 1.8.0 which includes the following changes:
- Added ACPI support to Firecracker for x86_64 microVMs. Currently, we pass ACPI tables with information about the available vCPUs, interrupt controllers, VirtIO and legacy x86 devices to the guest. This allows booting kernels without MPTable support. Please see our kernel policy documentation for more information regarding relevant kernel configurations.
- Added support for the Virtual Machine Generation Identifier (VMGenID) device on x86_64 platforms. VMGenID is a virtual device that allows VMMs to notify guests when they are resumed from a snapshot. Linux includes VMGenID support since version 5.18. It uses notifications from the device to reseed its internal CSPRNG. Please refer to snapshot support …
=> versions: Update firecracker version to 1.8.0

.github/workflows/run-kata-coco-stability-tests.yaml, tests/stability/gha-stability-run.sh
This PR enables the k8s soak stability test to run on the weekly Kata CoCo stability CI.
=> tests: Enable k8s soak stability test for Kata CoCo CI

.github/workflows/basic-ci-amd64.yaml, tests/functional/kata-agent-apis/gha-run.sh, tests/functional/kata-agent-apis/run-agent-api-tests.sh, tests/functional/kata-agent-apis/setup_common.sh
enable CI to add test cases for testing kata-agent APIs. This commit introduces:
- a workflow to run tests
- setup scripts to prepare the test environment
Fixes #10262
=> ci: Add workflow to run kata-agent api tests using kata-agent-ctl

tests/common.bash
metrics tests sometimes fail with kata components still running. sending SIGKILL and waiting for the processes to reap.
Fixes #8651
=> ci: send SIGKILL to kill kata components

.github/workflows/basic-ci-amd64.yaml, tests/functional/kata-agent-apis/api-tests/dummy.bats, tests/functional/kata-agent-apis/gha-run.sh, tests/functional/kata-agent-apis/run-agent-api-tests.sh
This commit enables running tests for kata agent apis. The 'api-tests' directory will contain bats test files for individual APIs.
Fixes #10269
=> ci: Enable kata agent API tests

tests/metrics/machine_learning/onednn.sh, tests/metrics/machine_learning/openvino.sh
This PR updates the machine learning tests references or urls for the openVINO and oneDNN scripts as currently they are refering to a different performance benchmark.
=> metrics: Update openVINO and oneDNN tests references

src/agent/src/storage/bind_watcher_handler.rs, src/agent/src/storage/block_handler.rs, src/agent/src/storage/ephemeral_handler.rs, src/agent/src/storage/fs_handler.rs, src/agent/src/storage/image_pull_handler.rs, src/agent/src/storage/local_handler.rs, src/agent/src/storage/mod.rs, src/libs/kata-types/src/mount.rs
Support registering multiple IDs to a single handler and Refactor storage handler registration. That's the pre-PR for the trusted data storage feature in CoCo.
Fixes: https://github.com/kata-containers/kata-containers/issues/10242
=> agent: Refactor storage handler registration

tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml
As kata-cleanup will only call `reset_runtime()`, there's absolutely no need to export the other set of environment variables in its yaml file.
=> kata-deploy: Remove kata-cleanup unneeded vars

tests/stability/kubernetes_soak_test.sh
This PR increases the timeout to wait that the deployment for the soak stability test is ready in order to avoid random failures saying that the deployment is not ready yet.
=> tests: Increase timeout to wait for soak stability test deployment

src/runtime-rs/config/configuration-dragonball.toml.in
Remove duplicated description of enable_balloon_f_reporting from configuration-dragonball.toml.in.
Fixes: #10281
=> runtime-rs: configuration-dragonball.toml.in: Remove duplication

src/runtime/virtcontainers/container.go
It will panic when users do GPU vfio passthrough with cdi in runtime. The root cause is that CustomSpec.Annotations is nil when new element added.
To address this issue, initialization is introduced when it's nil.
Fixes #10266
=> runtime: Fix runtime/cdi panic with assignment to entry in nil map

tests/integration/kubernetes/confidential_kbs.sh
In the process of switching the TDX CI machine we've noticed that `hostname -i` in one of the machines returns an one and only IP address, while in another machine it returns a full list of IPs.
As we're only interested in the first one, let's adapt the code to always return the first one.
=> ci: tdx: Adapt how we get the host IP

tests/metrics/lib/common.bash
This PR removes the remove_img variable in the metrics common script as it is not being used.
=> metrics: Remove unused remove img var in common script

src/tools/genpolicy/Cargo.lock, src/tools/genpolicy/Cargo.toml, src/tools/genpolicy/rules.rego, src/tools/genpolicy/src/registry.rs, src/tools/genpolicy/src/registry_containerd.rs, tests/integration/kubernetes/k8s-policy-pod.bats, tests/integration/kubernetes/runtimeclass_workloads/k8s-policy-pod.yaml
1. Add ability to pull UID:GID values from /etc/passwd, from container images.
2. Add genpolicy test for a container image that specifies a user name that must be converted to a UID value.
3. Re-enable CreateContainerRequest UID verification, now that the behavior from #9928 has been addressed by this PR.
Most of these changes have been cherry-picked from #9955 - thanks @HernanGatta !
Also, thanks to @burgerdev for #9928, for reviewing these changes, and for the additional ideas for possible future improvements tracked by #10290 !
=> genpolicy: fix and re-enable create container UID verification

tests/integration/kubernetes/k8s-inotify.bats
Poll/wait for pod termination instead of sleeping 2 minutes. This change typically saves ~90 seconds in my test cluster.
=> tests: k8s-inotify: pod termination polling

docs/how-to/how-to-run-kata-containers-with-SE-VMs.md, tools/packaging/guest-image/build_se_image.sh, tools/packaging/guest-image/lib_se.sh
This PR updates the documentation `how-to-run-kata-containers-with-SE-VMs.md` with the following changes:
- Update secure boot image verification for IBM SE
- Remove unnecessary `sudo`
- Add an error message where an incorrect host key document is used
- Add a missing artifact `kernel-confidential-modules`
- Make a variable `kernel_version` and replace it with relevant hits
=> doc: Update how-to-run-kata-containers-with-SE-VMs.md

.github/workflows/build-kata-static-tarball-s390x.yaml, tools/packaging/guest-image/lib_se.sh
As #10315 introduced an `unbound variable` error, this PR is a hot-fix for it.
The job `build-asset-boot-image-se` https://github.com/kata-containers/kata-containers/blob/03cd02a00643ec4468e91cf59a34662b6aac68a5/.github/workflows/build-kata-static-tarball-s390x.yaml#L87 does not rebase itself atop of the latest target branch. It is why we let the error code sneak in the main. 
=> local-build: Fix unbound variable issue for lib_se.sh

src/agent/src/config.rs, src/agent/src/main.rs, src/agent/src/policy.rs, tests/functional/kata-agent-apis/setup_common.sh
agent built with policy feature initializes the policy engine using a
policy document from a default path, which is installed & linked during
UVM rootfs build. This commit adds support to provide a default agent
policy as environment variable.
This targets development/testing scenarios where kata-agent
is wanted to be started as a local process.
Fixes #10301
=> agent: add support to provide default agent policy via env

tests/gha-run-k8s-common.sh, tools/packaging/kata-deploy/Dockerfile, tools/packaging/kata-deploy/action/Dockerfile
The payload build is failing with:
```
ERROR: failed to solve: process "/bin/sh -c apk --no-cache add bash curl && \tARCH=$(uname -m) && \tif [ \"${ARCH}\" = \"x86_64\" ]; then ARCH=amd64; fi && \tif [ \"${ARCH}\" = \"aarch64\" ]; then ARCH=arm64; fi && \tDEBIAN_ARCH=${ARCH} && \tif [ \"${DEBIAN_ARCH}\" = \"ppc64le\" ]; then DEBIAN_ARCH=ppc64el; fi && \tcurl -fL --progress-bar -o /usr/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/${ARCH}/kubectl && \tchmod +x /usr/bin/kubectl && \tcurl -fL --progress-bar -o /usr/bin/jq https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-linux-${DEBIAN_ARCH} && \tchmod +x /usr/bin/jq && \tmkdir -p ${DESTINATION} && \ttar xvf ${WORKDIR}/${KATA_ARTIFACTS} -C …
```
=> kata-deploy: Switch Kubernetes URL

src/tools/agent-ctl/src/client.rs, src/tools/agent-ctl/src/types.rs, src/tools/agent-ctl/src/utils.rs, tests/functional/kata-agent-apis/api-tests/test_set_policy.bats, tests/functional/kata-agent-apis/setup_common.sh
This patch adds support to call kata agents SetPolicy API. Also adds tests for SetPolicy API using agent-ctl.
Fixes #9711
=> agent-ctl: Add SetPolicy support

src/runtime/pkg/containerd-shim-v2/create.go, src/runtime/pkg/katautils/create.go, src/runtime/virtcontainers/container.go, src/runtime/virtcontainers/fs_share_linux.go, src/runtime/virtcontainers/kata_agent.go, src/runtime/virtcontainers/kata_agent_test.go, src/runtime/virtcontainers/mount_linux.go
...or by using a binary with additional suffix.
This allows having multiple verisons of nydus-overlayfs installed on the host, telling nydus-snapshotter which one to use while still detecting Nydus is used.
=> virtcontainers: allow specifying nydus-overlayfs binary by path

src/runtime/pkg/containerd-shim-v2/metrics.go
kata-shim was not reporting inactive_file in memory stat.
This memory is deducted by containerd when calculating the size of container working set, as it can be paged out by the operating system under memory pressure.
Without reporting `inactive_file`, containerd will over report container memory usage.
[Here](https://github.com/containerd/containerd/blob/v1.7.22/pkg/cri/server/container_stats_list_linux.go#L117) 
is where containerd deducts `inactive_file` from memory usage.
Note that kata-shim correctly reports `total_inactive_file` for cgroup v1, but this was not implemented for cgroup v2.
This commit:
- Adds code in kata-shim to report "inactive_file" memory for cgroup v2
- Implements reporting of all available cgroup v2 memory stats to containerd
- Uses defensive coding to avoid …
=> shim: Fix memory usage reporting for cgroup v2

src/runtime/config/configuration-remote.toml.in, src/runtime/virtcontainers/remote.go, src/runtime/virtcontainers/sandbox.go, src/runtime/virtcontainers/sandbox_test.go
Enables Image annotation to support multiple PodVM images in remote hypervisor scenario.
Fixes https://github.com/kata-containers/kata-containers/issues/10240
While enabling `image` annotation for remote hypervisor it should be added as,
```
annotations:
io.katacontainers.config.hypervisor.image: "rhel9-podvm-image"
```
As because the `image` is considered as `imagePath` internally, a `/` was required at the end or at the beginning, to bypass this check for `remote` hypervisor scenario, an if condition is added while on `createAssets()` method
=> runtime: Enable Image annotation for remote hypervisor

.github/workflows/run-kata-coco-tests.yaml
This PR increases the timeout to run k8s tests for Kata CoCo TDX to avoid the random failures of timeout.
=> gha: Increase timeout to run k8s tests on TDX

tools/packaging/kata-deploy/README.md
```
* Clarifies instructions for k0s.
* Adds kata-deploy step for each cluster type.
* Removes the old kata-deploy-stable step for vanilla k8s.
```
=> kata-deploy: clean up and fix docs for k0s

src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs, src/runtime-rs/crates/hypervisor/src/ch/mod.rs
Since the block_on would block on the current thread which would prevent other async tasks to be run on this worker thread, thus change it to use the async task for this task.
=> runtime-rs: fix the issue of using block_on

tests/integration/kubernetes/confidential_common.sh, tests/integration/kubernetes/k8s-file-volume.bats, tests/integration/kubernetes/k8s-guest-pull-image.bats, tests/integration/kubernetes/k8s-volume.bats, tests/integration/kubernetes/run_kubernetes_tests.sh, tests/integration/kubernetes/runtimeclass_workloads/custom-node-debugger.yaml, tests/integration/kubernetes/tests_common.sh
This PR resolves an issue with `exec_host()` handling loop devices by:
- Mimicking a node debugger with full privileges
- Creating and deleting the node debugger pod only once
- Re-enabling guest-pull-image tests for `qemu-coco-dev`
- Increase timeouts for `qemu-coco-dev` in trusted image storage tests
Detailed explanation can be found in the commit messages.
Fixes: #10133
=> tests: Fix loop device handling for exec_host()

tools/testing/kata-webhook/deploy/webhook.yaml, tools/testing/kata-webhook/webhook-check.sh
The kata webhook requires a configmap to define what runtime class it should set for the newly created pods. Additionally, the configmap allows others to modify the default runtime class name we wish to set (in case the handler is kata but the name of the runtimeclass is different). 
Finally, this PR changes the webhook-check to compare the runtime of the newly created pod against the specific runtime class in the configmap, if said confimap doesn't exist, then it will default to "kata".
=> tools.kata-webhook: Specify runtime class using configMap

src/runtime/virtcontainers/endpoint.go, src/runtime/virtcontainers/endpoint_test.go, src/runtime/virtcontainers/kata_agent.go, src/runtime/virtcontainers/network.go, src/runtime/virtcontainers/network_linux.go, src/runtime/virtcontainers/network_linux_test.go, src/runtime/virtcontainers/persist/api/network.go, src/runtime/virtcontainers/sandbox.go, src/runtime/virtcontainers/types/dan.go, src/runtime/virtcontainers/vfio_endpoint.go
When using network adapters that support SR-IOV, a VFIO device can be
plugged into a guest VM and claimed as a network interface. This can
significantly enhance network performance.
Fixes: #9758
=> runtime: add DAN support for VFIO network device in Go kata-runtime

tests/integration/kubernetes/k8s-confidential-attestation.bats, tests/integration/kubernetes/k8s-file-volume.bats, tests/integration/kubernetes/k8s-guest-pull-image-authenticated.bats, tests/integration/kubernetes/k8s-guest-pull-image-encrypted.bats, tests/integration/kubernetes/k8s-guest-pull-image-signature.bats, tests/integration/kubernetes/k8s-liveness-probes.bats, tests/integration/kubernetes/k8s-sealed-secret.bats, tests/integration/kubernetes/k8s-volume.bats, tests/integration/kubernetes/lib.sh, tests/integration/kubernetes/tests_common.sh
This PR improves the k8s negative tests by:
- Making the `kubectl` commands in `print_node_journal()` synchronous, similar to the fix for `exec_host()`, to prevent missing journal logs due to premature termination of the node debugger pod.
- Completing the tests as soon as a specified log message is captured, rather than waiting for the default 2 minutes to confirm that the test pod is not running.
For a detailed explanation, please refer to the commit messages.
=> tests: Improve k8s negative tests

src/runtime-rs/crates/runtimes/common/src/message.rs, src/runtime-rs/crates/runtimes/common/src/sandbox.rs, src/runtime-rs/crates/runtimes/common/src/types/mod.rs, src/runtime-rs/crates/runtimes/common/src/types/trans_into_shim.rs, src/runtime-rs/crates/runtimes/common/src/types/utils.rs, src/runtime-rs/crates/runtimes/src/manager.rs, src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
Docker cannot exit normally after the container process exits when used with runtime-rs since it doesn't receive the exit event. This commit enable runtime-rs to send TaskExit to containerd after process exits.
Also, it moves "system_time_into" and "option_system_time_into" from crates/runtimes/common/src/types/trans_into_shim.rs to a new utility mod.
Fixes #10288 
Signed-off-by: Sicheng Liu <lsc2001@outlook.com>
=> runtime-rs: Notify containerd when process exits

src/agent/src/rpc.rs
When the sandbox api was enabled, the pasue container wouldn't be created, thus the shared sandbox pidns should be fallbacked to the first container's init process, instead of return any error here.
=> agent: fix the issue of setup sandbox pidns

src/runtime-rs/crates/resource/src/cpu_mem/initial_size.rs, src/runtime-rs/crates/runtimes/common/src/runtime_handler.rs, src/runtime-rs/crates/runtimes/common/src/sandbox.rs, src/runtime-rs/crates/runtimes/common/src/types/mod.rs, src/runtime-rs/crates/runtimes/linux_container/src/lib.rs, src/runtime-rs/crates/runtimes/src/manager.rs, src/runtime-rs/crates/runtimes/virt_container/src/lib.rs, src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs, src/runtime-rs/crates/runtimes/wasm_container/src/lib.rs
Inorder to support sandbox api, intorduce the sandbox_config struct and split the sandbox start stage from init process.
=> sandbox: refactor the sandbox init process

src/runtime-rs/crates/hypervisor/Cargo.toml, src/runtime-rs/crates/hypervisor/src/device/mod.rs, src/runtime-rs/crates/hypervisor/src/device/tap.rs, src/runtime-rs/crates/hypervisor/src/utils.rs
It's a prerequisite PR to make built-in vmm dragonball compilation options configurable.
Ported TAP device management code from dragonball's dbs_utils to runtime-rs's hypervisor module. Replaced bidegen-generated C code with an implementation using the libc crate and the ifreq structure. Removed dependency on dragonball to simplify runtime-rs and reduce unnecessary complexity. Ensured that the TAP device creation and management functionality remains unchanged.
Signed-off-by: sidney chang <2190206983@qq.com>
Fixes #10182
=> runtime-rs: Port TAP implementation from dragonball

.github/workflows/run-kata-coco-tests.yaml
This PR adds ita_key as a github secret at the kata coco tests yaml workflow.
This PR is not mine, it comes from Gaby! :-)
The reason I'm splitting this one as a different PR is because we need it to be merged to actually test the ITA changes.
There's no need to run CI on it.
=> gha: Add ita_key as a github secret

docs/Developer-Guide.md
This PR removes some qemu information which is not longer valid as this is referring to the tests repository and to kata 1.x.
=> docs: Remove qemu information not longer valid

tests/integration/kubernetes/confidential_kbs.sh, tests/integration/kubernetes/gha-run.sh
This PR replaces the use of DCAP to use an ITA key for Kata CoCoTDX CI.
=> ci:tdx: Use an ITA key for TDX

docs/install/kata-containers-3.0-rust-runtime-installation-guide.md, src/runtime-rs/Makefile, src/runtime-rs/crates/hypervisor/Cargo.toml, src/runtime-rs/crates/hypervisor/src/lib.rs, src/runtime-rs/crates/runtimes/virt_container/Cargo.toml, src/runtime-rs/crates/runtimes/virt_container/src/lib.rs, src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
This PR introduces support for selectively compiling Dragonball in runtime-rs. By default, Dragonball will continue to be compiled into the containerd-shim-kata-v2 executable, but users now have the option to disable Dragonball compilation. When Dragonball is not compiled, the default runtime will switch to Qemu.
Fixes #10310
Signed-off-by: sidney chang <2190206983@qq.com>
=> runtime-rs: Add Configurable Compilation for Dragonball in Runtime-rs

src/tools/genpolicy/genpolicy-settings.json, src/tools/genpolicy/rules.rego, src/tools/genpolicy/src/policy.rs, src/tools/genpolicy/src/settings.rs, tests/integration/kubernetes/tests_common.sh
Reject any unexpected values from the CreateSandboxRequest storages field.
Cherry-picked from https://github.com/microsoft/kata-containers/commit/e4465090e693807d6ccc044344ad44789acda3e2#diff-5c63caeeb90fbc2a1ea4b7795dfc044d80576727968da21f555045e8bdd684b1
=> genpolicy: validate create sandbox storages

tests/integration/kubernetes/k8s-block-volume.bats
Currently, `qemu-runtime-rs` does not support `virtio-scsi`, which causes the `k8s-block-volume.bats` test to fail (for details, please check out #10373).
This PR skips the test until `virtio-scsi` is supported by the runtime.
FYI: @sprt
=> tests: Skip k8s-block-volume.bats for qemu-runtime-rs

tests/metrics/density/fast_footprint.sh
This PR updates the fast footprint script to remove the use of egrep as this command has been deprecated and change it to use grep command.
=> metrics: Update fast footprint script to use grep

tests/integration/kubernetes/k8s-empty-dirs.bats
For now, this is only in order to debug and then try to understand why it's been disabled and why it's passing on SEV / SNP.
=> k8s: tests: Re-enable empty-dirs tests for TDX / coco-qemu-dev

src/runtime-rs/crates/hypervisor/src/qemu/cmdline_generator.rs, src/runtime-rs/crates/hypervisor/src/qemu/inner.rs, src/runtime-rs/crates/hypervisor/src/qemu/qmp.rs
This PR add a capability to hotplug network devices into QEMU kata VMs.
This functionality seems kind of hard to trigger with tools like `ctr` and `crictl` which tend to coldplug under most scenarios but one way to test this is using a `nerdctl` compose with multiple networks defined.
The initial four commits of this series are preparatory steps and refactors not directly related to the main topic but necessary to set the stage for it, the final three commits then implement the actual hotplugging.
=> runtime-rs: add network device hotplugging to qemu-rs

tests/integration/kubernetes/confidential_kbs.sh
This PR adds the trap statement in the confidential kbs script to clean up temporary files and ensure we are leaving them.
=> k8s:kbs: Add trap statement to clean up tmp files

tools/osbuilder/rootfs-builder/rootfs.sh
This PR removes duplicated arch variable definition in the rootfs script as this variable and its value is already defined at the top of the script.
=> osbuilder: Remove duplicated arch variable definition

.github/workflows/ci-on-push.yaml, .github/workflows/ci.yaml, .github/workflows/gatekeeper-skipper.yaml, .github/workflows/gatekeeper.yaml, .github/workflows/static-checks-self-hosted.yaml, .github/workflows/static-checks.yaml, tools/testing/gatekeeper/jobs.py, tools/testing/gatekeeper/required-tests.yaml, tools/testing/gatekeeper/skips.py
This PR adds 2 workflows:
* gatekeeper-skipper
* gatekeeper
The skipper can be used in workflows to detect changes and output set of tests to be executed (or skipped), the gatekeeper watches all the running jobs and checks the status of expected jobs to pass (based on changed files), which should replace the "required" feature of GH (once we make this workflow required).
Note this solution should be quite scalable so things like advanced heuristic or GH comments/labels overrides should be possible.
Example PRs (with slightly outdated gatekeeper but mainly similar):
* https://github.com/ldoktor/kata-containers/pull/6
* https://github.com/ldoktor/kata-containers/pull/5
Note you can get gatekeeper output of any existing PR (yours or kata-containers) by running something like `GITHUB_TOKEN="" …
=> CI: Select jobs by touched code

.github/workflows/run-k8s-tests-on-aks.yaml, .github/workflows/run-kata-coco-tests.yaml, tests/integration/kubernetes/gha-run.sh
The behavior of **Kata CI** doesn't change.
For **local testing** using kubernetes/gha-run.sh:
1. Before these changes:
- AUTO_GENERATE_POLICY=yes was always used by the users of SEV, SNP, TDX, or KATA_HOST_OS=cbl-mariner.
2. After these changes:
- Users of SEV, SNP, TDX, or KATA_HOST_OS=cbl-mariner must specify AUTO_GENERATE_POLICY=yes if they still want to auto-generate policy.
- These users have the option to test just using hard-coded policies (e.g., using the default policy built into the Guest rootfs) by using AUTO_GENERATE_POLICY=no. AUTO_GENERATE_POLICY=no is the default value of this env variable.
=> gha: enable AUTO_GENERATE_POLICY where needed

tools/osbuilder/rootfs-builder/rootfs.sh
By checking for AGENT_POLICY we ensure we only try to read allow-all.rego if AGENT_POLICY is set to "yes"
=> build: Fix RPM build fail due to AGENT_POLICY

tools/osbuilder/image-builder/image_builder.sh
This PR removes an unused variable in the image builder script.
=> image-builder: Remove unused variable

.github/workflows/build-kata-static-tarball-amd64.yaml, tools/packaging/kata-deploy/local-build/Makefile, tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh, versions.yaml
Kata CI will start building and testing the new rootfs-image-mariner instead of the older rootfs-initrd-mariner image.
The "official" AKS images are moving from a rootfs-initrd-mariner image to the rootfs-image-mariner format. Making the same change in Kata CI is useful to keep this testing in sync with the AKS settings.
=> local-build: add ability to build rootfs-image-mariner

tools/osbuilder/tests/test_images.sh
This PR adds the trap statement in the test images script to clean up tmp files.
=> tools/osbuilder/tests: Add trap statement in test images script

src/agent/src/cdh.rs
This reverts commit 31e09058af68a2f7e9c9685f505c7cad53148c8d, as it's breaking the agent unit tests CI.
This is a stop gap till Chengyu Zhu finds the time to properly address the issue, avoiding the CI to be blocked for now.
=> Revert "agent:cdh: unittest for sealed secret as file"

tools/packaging/kata-deploy/local-build/Makefile, tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh, versions.yaml
As mariner has switched to using an image instead of an initrd, let's just drop the abiliy to build the initrd and avoid keeping something in the tree that won't be used.
--- 
This one depends on https://github.com/kata-containers/kata-containers/pull/10396 and will be kept as a draft till that one gets merged.
=> build: mariner: Remove the ability to build the marine initrd

tests/integration/kubernetes/confidential_kbs.sh, versions.yaml
In https://github.com/confidential-containers/trustee/pull/521
the overlays logic was modified to add sample
s390x support and simplify non-ibm-se platforms.
We need to update the logic in `kbs_k8s_deploy`
to match and can remove the dummying of `IBM_SE_CREDS_DIR`
for non-SE flows now.
=> Kbs deploy overlays update

tests/integration/kubernetes/confidential_kbs.sh, versions.yaml
When dealing with a specific release, it was easier to just do some adjustments on the image that has to be used for ITA without actually adding a new entry in the versions.yaml.
However, it's been proven to be more complicated than that when it comes to dealing with staged images, and we better explicitly add (and update) those versions altogether to avoid CI issues.
=> kbs: ita: Ensure the proper image / image_tag is used for ITA

tools/osbuilder/tests/test_images.sh
This PR removes egrep command as it has been deprecated and it replaces by grep in the test images script.
=> tools/osbuilder/tests: Remove egrep in test images script

.github/workflows/build-checks.yaml, tools/packaging/static-build/tools/Dockerfile
Adds dependencies of 'clang' & 'protobuf' to be installed in runners when building agent-ctl sources having image pull support.
Fixes #10400
=> ci: Install build dependencies for building agent-ctl with image pull.

src/tools/genpolicy/src/config_map.rs, tests/integration/kubernetes/runtimeclass_workloads/k8s-policy-configmap.yaml
While Kubernetes defines `binaryData` as `[]byte`, when defined in a YAML file the raw bytes are
base64 encoded. Therefore, we need to read the YAML value as `String` and not as `Vec<u8>`.
Fixes: #10410
=> genpolicy: read binaryData value as String

tools/packaging/kata-deploy/scripts/kata-deploy.sh
Use the configuration used by AKS (static_sandbox_resource_mgmt=true) for CI testing on Mariner hosts.
Hopefully pod startup will become more predictable on these hosts - e.g., by avoiding the occasional hotplug timeouts described by #10413.
=> ci: static_sandbox_resource_mgmt for cbl-mariner

tests/integration/kubernetes/k8s-inotify.bats
- Don't leak configmap if the test fails.
- Wait for pod termination up to a longer time (180 sec) than the timeout specified in the pod yaml (120 sec). Before these changes, the 90 sec wait might have timed out before the pod got a chance to finish its work.
=>  tests: k8s-inotify.bats improvements

src/runtime-rs/crates/hypervisor/src/firecracker/fc_api.rs
Use values from the config for the setup of the microVM.
Fixes: #10434
=> runtime-rs: Use vCPU and memory values from config

.github/workflows/build-kata-static-tarball-amd64.yaml, .github/workflows/build-kata-static-tarball-s390x.yaml, tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
This adds provenance attestation logic for agent binaries that are published to an oci registry via ORAS.
As a downstream consumer of the kata-agent binary the Peerpod project needs to verify that the artifact has been built on kata's CI. So far the provenance creation has been only enabled for agent builds on amd64 and xs390x.
To create an attestation we need to know the exact digest of the oci artifact, at the point when the artifact was pushed.
Therefore we record the full oci image as returned by oras push. The pushing and tagging logic have been slightly reworked to make this task less repetitive.
The oras cli accepts multiple tags separated by comma on pushes, so a push can be performed atomically instead of iterating through tags and pushing each individually. This removes the risk …
=> ci: add provenance attestation for agent artifact

.github/workflows/build-kata-static-tarball-amd64.yaml, .github/workflows/build-kata-static-tarball-s390x.yaml
Moved the parsing of the oci image marker into its own step, since we only need to perform that for attestation purposes and some cached images might not have that file in the tarball.
=> ci: don't parse oci image for cached artifacts

src/agent/src/rpc.rs, tests/integration/kubernetes/k8s-hostname.bats, tests/integration/kubernetes/run_kubernetes_tests.sh, tests/integration/kubernetes/runtimeclass_workloads/pod-hostname.yaml
When do update_container_namespaces updating namespaces, setting all UTS(and IPC) namespace paths to None resulted in hostnames set prior to the update becoming ineffective. This was primarily due to an error made while aligning with the oci spec: in an attempt to match empty strings with None values in oci-spec-rs, all paths were incorrectly set to None.
Fixes #10325
Related PR #10423
=> kata-agent: fixing bug of unable setting hostname correctly.

tools/osbuilder/rootfs-builder/cbl-mariner/config.sh
Outline: Change the PACKAGES variable for the cbl-mariner rootfs-builder to use the kata-packages-uvm meta package from packages.microsoft.com to define the set of packages to be contained in the UVM.
This aligns the UVM build for the Azure Linux distribution with the UVM build done for the Kata Containers offering on Azure Kubernetes Services (AKS).
The reasoning behind this change is to get to a more tailored selection of packages than before (e.g. a selection from core-packages-base-image) and to get more immediate control on the set of packages being included (for instance, this achieves a faster turnover when a third party has a use case for which a package is missing. In this case, no new fork/upstream release has to be cut in order to add the package to the UVM).
The …
=> tools: Change PACKAGES var for cbl-mariner

.github/workflows/build-kata-static-tarball-amd64.yaml, .github/workflows/build-kata-static-tarball-arm64.yaml, .github/workflows/build-kata-static-tarball-ppc64le.yaml, .github/workflows/build-kata-static-tarball-s390x.yaml
By doing this we can ensure that whenever the rootfs changes, we'll be able to get the new root_hash.txt and use it.
This is the very first step to bring the measured rootfs tests back.
=> workflows: Ensure shim-v2 is built as the last asset

src/runtime/virtcontainers/qemu.go
When QEMU is terminated by signal 15, it deletes the PidFile. Upon detecting that QEMU has exited, the shim executes the stopVM function. If the PidFile is not found, the PID is set to 0. Subsequently, the shim executes kill -9 0, which terminates the current process group. This prevents any further logic from being executed, resulting in resources not being cleaned up.
=> runtime: Failed to clean up resources when QEMU is terminated 

.github/workflows/ci-devel.yaml, .github/workflows/ci-nightly.yaml
```
workflows: Add a manually trigger "devel" workflow for the CI
This workflow is intended to replace the `workflow_dispatch` trigger
currently present as part of the `ci-nightly.yaml`.
The reasoning behind having this done in this way is because of our good
and old GHA behaviour for `pull_request_target`, which requires a PR to
be merged in order to check the changes in the workflow itself, which
leads to:
* when a change in a workflow is done, developers (should) do:
* push their branch to the kata-containers repo
* manually trigger the "nightly" CI in order to ensure the changes
don't break anything
* this can result in the "nightly" CI weather being polluted
* we don't have the guarantee / assurance about the last n nightly
runs anymore
```
---
```
workflows: Remove the possibility …
```
=> Add a specific workflow for testing the CI, without messing up with the "nightly" weather

ci/README.md
This PR fixes a misspelling in CI documentation readme.
=> docs: Fix misspelling in CI documentation

tests/kata-doc-to-script.sh
This PR adds the trap statement into the kata doc
script to clean up properly the temporary files.
=> tests: Add trap statement in kata doc script

.github/workflows/ci-devel.yaml
Stop using "manually-triggered" as it's too long to create AKS clusters, and use "dev" instead.
Also, let's allow this to run in parallel in case two or more developers want to test things at the same time.
=> workflows: devel: Follow-up on the manually triggered jobs

.github/workflows/build-kata-static-tarball-amd64.yaml, .github/workflows/build-kata-static-tarball-arm64.yaml, .github/workflows/build-kata-static-tarball-ppc64le.yaml, .github/workflows/build-kata-static-tarball-s390x.yaml
The only reason we had this one passing for amd64 is because the check was done using the wrong variable (`matrix.stage`, while in the other workflows the variable used is `inputs.stage`).
The commit that broke the release process is 67a8665f51d78e1138c, which blindly copy & pasted the logic from the matrix assets.
=> workflows: Possibly fix the release workflow

tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
All the oras push logic happens from inside `${workdir}`, while the root_hash.txt extraction and renaming was not taking this into consideration.
This was not caught during the manually triggered runs as those do not perform the oras push.
=> build: cache: Ensure shim-v2-root_hash.txt is in "${workdir}"

src/runtime/virtcontainers/sandbox.go
Return of proper error to the initiator is not guaranteed.
Method StopVM could kill shim process together with VM pieces.
Signed-off-by: Konstantin Khlebnikov <koct9i@gmail.com>
=> runtime: log vm start error before cleanup

tests/stability/kubernetes_stressng.sh
This PR increase the time to run the stressng k8s tests for the CoCo stability CI.
=> tests: Increase time to run stressng k8s tests

.github/workflows/run-k8s-tests-on-zvsi.yaml, tests/integration/kubernetes/gha-run.sh
Last November, SUSE discontinued support for s390x, leaving `k3s` on this platform stuck at k8s version 1.28, while upstream k8s has since reached 1.31. Fortunately, `kubeadm` allows us to create a 1.30 Kubernetes cluster on s390x.
This PR switches the `KUBERNETES` option from `k3s` to `kubeadm` for s390x and removes a dedicated cluster creation step. It also includes a configuration option `kubeadm` for devmapper setup.
Now, cluster setup and teardown occur in `ACTIONS_RUNNER_HOOK_JOB_{STARTED,COMPLETED}` on the self-hosted runners.
For reviewers, the affected workflows are as follows:
- run-k8s-tests-on-zvsi / run-k8s-tests (devmapper, qemu, k3s)
- run-k8s-tests-on-zvsi / run-k8s-tests (overlayfs, qemu-runtime-rs, k3s)
- run-k8s-tests-on-zvsi / run-k8s-tests (nydus, qemu-coco-dev, k3s) …
=> gha: Switch KUBERNETES from k3s to kubeadm on s390x

src/agent/Cargo.lock, src/libs/Cargo.lock, src/libs/kata-sys-util/Cargo.toml, src/libs/kata-sys-util/README.md, src/libs/kata-sys-util/src/spec.rs, src/libs/protocols/Cargo.toml, src/libs/protocols/src/trans.rs, src/runtime-rs/Cargo.lock, src/tools/agent-ctl/Cargo.lock, src/tools/genpolicy/Cargo.lock, src/tools/kata-ctl/Cargo.lock, src/tools/runk/Cargo.lock
This PR allows building the genpolicy binary on darwin and adds a CI step to ensure it keeps building in the future.
Background: #10424. The individual commits have more detailed descriptions, too.
cc @Apokleos @Redent0r @danmihai1
=> genpolicy: support darwin target 

tools/packaging/kata-deploy/local-build/Makefile, tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh, tools/packaging/kata-deploy/local-build/kata-deploy-copy-libseccomp-installer.sh, tools/packaging/static-build/tools/Dockerfile, tools/packaging/static-build/tools/build-static-tools.sh, tools/packaging/static-build/tools/build.sh
This commit introduces changes to use ubuntu for statically building kata tools. In the existing CI setup, the tools currently build only for x86_64 architecture.
It also fixes the build error seen for agent-ctl PR#10395.
Fixes #10441
=> ci: Use ubuntu for static building of kata tools.

docs/how-to/how-to-set-sandbox-config-kata.md, src/runtime/config/configuration-remote.toml.in, src/runtime/pkg/oci/utils.go, src/runtime/pkg/oci/utils_test.go, src/runtime/virtcontainers/hypervisor.go, src/runtime/virtcontainers/pkg/annotations/annotations.go, src/runtime/virtcontainers/remote.go
Add GPU annotations for remote hypervisor to help
with the right instance selection based on number of GPUs and model
=> runtime: Add GPU annotations for remote hypervisor

src/agent/src/main.rs
This change is motivated by a problem in peerpod's podvms. In this setup the lifecycle of guest components is managed by systemd. The current code skips over init steps like setting the ocicrypt-rs env and initialization of a CDH client in this case.
To address this the launch of the processes has been isolated into its own fn.
=> agent: perform attestation init w/o process launch

tests/stability/gha-stability-run.sh
This PR fixes the source to avoid duplication specially in the common.sh script and avoid failures saying that certain script is not in the directory.
=> gha: Fix source for gha stability run script

src/tools/agent-ctl/Cargo.lock, src/tools/agent-ctl/Cargo.toml, src/tools/agent-ctl/src/client.rs, src/tools/agent-ctl/src/image.rs, src/tools/agent-ctl/src/main.rs, src/tools/agent-ctl/src/types.rs, src/tools/agent-ctl/src/utils.rs, src/tools/agent-ctl/template/oci_config.json, tests/functional/kata-agent-apis/api-tests/test_create_container.bats, tests/functional/kata-agent-apis/setup_common.sh, tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
This commit introduces changes to enable testing kata-agent's container APIs of CreateContainer/StartContainer/RemoveContainer. The changeset include:
- using confidential-containers image-rs crate to pull/unpack/mount a container image. Currently supports only un-authenicated registry pull
- re-factor api handlers to reduce cmdline complexity and handle request generation logic in tool
- introduce an OCI config template for container creation
- add test case
Fixes #9707
=> agent-ctl: Add support to test kata-agent's container creation APIs.

tests/gha-run-k8s-common.sh, tests/integration/kubernetes/confidential_kbs.sh, tests/integration/kubernetes/k8s-guest-pull-image-authenticated.bats, tests/integration/kubernetes/k8s-guest-pull-image-encrypted.bats, tests/integration/kubernetes/k8s-guest-pull-image-signature.bats, tests/integration/kubernetes/k8s-guest-pull-image.bats, tests/integration/kubernetes/k8s-liveness-probes.bats, tests/integration/kubernetes/k8s-measured-rootfs.bats, tests/integration/kubernetes/k8s-sealed-secret.bats, tests/integration/kubernetes/run_kubernetes_tests.sh
We've seen some issues with tests not being run in some of the Coco CI jobs (Issue #10451) and in the envrionments that are more stable we noticed that
they had a newer version of bats installed.
Try updating the version to 1.10+ and print out
the version for debug purposes
=> tests: k8s: Update bats

tools/packaging/static-build/ovmf/build-ovmf.sh
Let's just do a simple `sed` and **not** use the repo that became private.
This is not a backport of https://github.com/tianocore/edk2/pull/6402, but it's a similar approach that allows us to proceed without the need to pick up a newer version of edk2.
=> builds: ovmf: Workaround Zeex repo becoming private

tools/packaging/guest-image/build_image.sh
Add suffix to image or initrd depending on the NVIDIA driver version 
Fixes: #9478
We want to keep track of the driver versions build during initrd/image build so update the artifact_name after the fact.
=> image: Add suffix to image or initrd depending on the NVIDIA driver version

src/agent/src/storage/ephemeral_handler.rs
Most likely this was overlooked during the development / review, but we're actually interested on the size rather than on the pagesize of the hugepages.
cc @liubin @bpradipt, as this as introduced as part of 36c3fc12ce6813763538ada66334a3d8a28845f0
Please, let me know if this is not actually a typo, and why it's not a typo. as I came across this one while debugging something completely unrelated.
=> agent: fix typo on getting EphemeralHandler size option

tests/integration/kubernetes/k8s-nginx-connectivity.bats
We have an error with service name resolution with this test when using qemu/crio. This error could not be reproduced outside of the CI for now. Skipping it to keep the CI job running until we find a solution.
See: https://github.com/kata-containers/kata-containers/issues/10414
=> ci: skip nginx connectivity test with qemu/crio

.github/workflows/ci.yaml, .github/workflows/run-kata-coco-tests.yaml, src/runtime/config/configuration-qemu-coco-dev.toml.in, tests/integration/kubernetes/tests_common.sh
By the moment we're testing it also with qemu-coco-dev, it becomes easier for a developer without access to TEE to also test it locally.
=> workflows: Use AUTO_GENERATE_POLICY for qemu-coco-dev

.github/workflows/run-kata-coco-stability-tests.yaml, tests/stability/gha-stability-run.sh
This PR adds the install kata tools step as part of the k8s stability workflow.
=> gha: Add install kata tools as part of the stability workflow

src/runtime/virtcontainers/fs_share_linux.go
This PR makes the root dir absolute after resolving the default root dir symlink.
Fixes: https://github.com/kata-containers/kata-containers/issues/10499
=> runtime: Files are not synced between host and guest VMs

src/agent/Cargo.lock, src/agent/Cargo.toml, src/agent/src/device/mod.rs, src/agent/src/rpc.rs
For proper device handling add CDI support
Depends on: ~~https://github.com/kata-containers/kata-containers/pull/9944~~ ~~https://github.com/kata-containers/kata-containers/issues/10059~~
=> kata-agent: Add CDI support

.github/workflows/run-metrics.yaml
As discussed on the AC call, we are lacking maintainers for the metrics tests. As a starting point for potentially phasing them out, we discussed starting with removing the test for stratovirt as a non-core hypervisor and a job that is problematic in leaving behind resources that need cleaning up.
=> metrics: Skip metrics on stratovirt

.github/workflows/basic-ci-amd64.yaml, .github/workflows/build-checks.yaml, .github/workflows/build-kata-static-tarball-amd64.yaml, .github/workflows/run-runk-tests.yaml
As discussed in the AC meeting, we don't have a maintainer, (or users?) of runk, and the CI is unstable, so giving we can't support it, we shouldn't waste CI cycles on it.
=> workflow: Remove/skip runk CI

tests/integration/kubernetes/k8s-guest-pull-image.bats
Currently the error we are checking for is
`CreateContainerRequest timed out`, but this message doesn't always seem to be printed to our pod log e.g. https://github.com/kata-containers/kata-containers/actions/runs/11694675764/job/32569257632
Try using a more general message that should be present more reliably.
=> tests: k8s: Update image pull timeout error

tests/integration/kubernetes/confidential_kbs.sh
Trustee's deployment must set the correct https_proxy as env var on the container that will talk to the ITA / ITTS server, otherwise the kbs service won't be able to start, causing then issues in our CI.
=> ci: tdx: kbs: Ensure https_proxy is taken in consideration

.github/workflows/ci-weekly.yaml, .github/workflows/gatekeeper-skipper.yaml, .github/workflows/gatekeeper.yaml, .github/workflows/run-kata-coco-stability-tests.yaml, src/runtime/pkg/govmm/.github/workflows/main.yml
GHA is migrating ubuntu-latest to Ubuntu 24 so let's hardcode the current 22.04 LTS.
https://github.blog/changelog/2024-11-05-notice-of-breaking-changes-for-github-actions/
=> gha: Hardcode ubuntu-22.04 instead of latest

.github/workflows/run-kata-coco-stability-tests.yaml, tests/stability/gha-stability-run.sh
This PR adds the get artifacts which are needed when installing kata tools in stability workflow to avoid failures saying that artifacts are missing.
=> gha: Get artifacts when installing kata tools in stability workflow

.github/workflows/run-kata-coco-tests.yaml
As discussed in the CI working group,
we are temporarily skipping the SNP CI
to unblock the remaining workflow.
Will revert after fixing the SNP runner.
=> ci: Temporarily skip SNP CI

tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in
Remove unneeded second declaration of `GO_HOME` in rootfs-builder.
=> osbuilder: remove redundant env variable 

src/agent/Cargo.lock, src/agent/Cargo.toml, src/agent/src/policy.rs, src/tools/genpolicy/rules.rego
Fixes https://github.com/kata-containers/kata-containers/issues/10087
This PR adds the ability for the policy to save and load data to a state kept in the regorus engine, and also validates one field (sandbox name) to show capabilities.
=> genpolicy: add state to policy

src/runtime/pkg/oci/utils.go
This patch sets maxvcpus equal to vcpus for the static sandbox resources management case. The value can safely be set to the actual number of vCPUs that the VM will use since CPU hotplugging will be no op when static_sandbox_resources_mgmt is set to true. The value gets passed down to the kernel when using clh/qemu. Booting with a high number of max vCPUs is a bit slower compared to a lower number.
Fixes: #9194
=> runtime: Set maxvcpus equal to vcpus for the static resources case

src/runtime/virtcontainers/clh.go
Per the comment in clh.go pertaining to logging verbosity for CLH, we should only be getting 'WARN' messages from CLH when we configure clh.Config.Debug = true. This is not the case; we instead filter for messages up to an including the 'INFO' level. This appears to be due to the CLH implementation for logging verbosity getting out of sync with the comment/verbosity logic in clh.go.
clh.go comment: https://github.com/microsoft/kata-containers/blob/msft-main/src/runtime/virtcontainers/clh.go#L1437 
clh implementation logic: https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/src/main.rs#L556 
For a system configured with enable_debug=true for kata runtime, kernel, I expected only messages from CLH up to 'WARN'.
```
cat journal.txt | grep "cloud-hypervisor.*WARN" …
```
=> runtime: fix comment to accurately reflect clh behavior

docs/how-to/how-to-run-kata-containers-with-SNP-VMs.md
Fix several build failures  when I tried the procedures in [Kata Containers with AMD SEV-SNP VMs](https://github.com/kata-containers/kata-containers/blob/main/docs/how-to/how-to-run-kata-containers-with-SNP-VMs.md).
Fixes: #10378
=> docs: Fix several build failures  when I tried the procedures in "Kata Containers with AMD SEV-SNP VMs"

src/agent/src/device/mod.rs
We need to clean-up any created files/dirs otherwise we cause problems on self-hosted runners. Using tempdir which will be removed automatically.
=> ci: Fix error on self-hosted machines

src/tools/genpolicy/rules.rego
Avoid adding to the Guest console warnings about "agent_policy:10:8".
"import input" is unnecessary.
=> genpolicy: avoid regorus warning

tools/packaging/kata-deploy/kata-deploy/overlays/k0s/mount_k0s_conf.yaml, tools/packaging/kata-deploy/scripts/kata-deploy.sh
As Ubuntu seems to already be shipping a containerd version that uses version 3 as its default version.
=> kata-deploy: Support containerd configuration version 3

.github/workflows/build-kata-static-tarball-amd64.yaml, .github/workflows/build-kata-static-tarball-arm64.yaml, .github/workflows/build-kata-static-tarball-ppc64le.yaml, .github/workflows/build-kata-static-tarball-s390x.yaml
We need the publish certain artefacts for the rootfs, like the agent, guest-components, pause bundle etc as they are consumed in the `build-asset-rootfs` step. However after this point they aren't needed and probably shouldn't be included in the overall kata tarball, so delete them once they aren't needed any more to avoid them being included.
Fixes: #10575
=> workflows: Remove rootfs binary artifacts

.github/workflows/build-kata-static-tarball-amd64.yaml, .github/workflows/ci.yaml, .github/workflows/publish-csi-driver-amd64.yaml, .github/workflows/run-kata-coco-tests.yaml, tests/integration/kubernetes/gha-run.sh, tools/packaging/kata-deploy/local-build/Makefile
This is the first step in implementing confidential ephemeral storage for CoCo. Because we'll need to use a CSI driver to properly test this (see #10560), we start by building and publishing this driver in the CI. We also add initial no-op steps to deploy and clean up the driver in the test cluster.
Please see the development plan for all the steps: #10560
=> coco: ci: Lay groundwork for compiling and publishing CSI driver image [1/x]

src/runtime/virtcontainers/clh.go
Avoid logging the same endpoint fields twice from addNet().
=> runtime: clh: addNet() logging clean-up

.github/workflows/build-kata-static-tarball-amd64.yaml, .github/workflows/build-kata-static-tarball-arm64.yaml, .github/workflows/build-kata-static-tarball-ppc64le.yaml, .github/workflows/build-kata-static-tarball-s390x.yaml
#9838 previously modified the static build so as not to repeatedly copy the same assets on each matrix iteration:
https://github.com/kata-containers/kata-containers/pull/9838#issuecomment-2169299202
However, that implementation breaks specifiying no-op/WIP build targets such as done in e43c59a. Such no-op builds have been a historical of the project requirement because of a GHA limitation. The breakage is due to no-op builds not generating a tar file corresponding to the asset:
https://github.com/kata-containers/kata-containers/actions/runs/12059743390/job/33628926474?pr=10592
To address this breakage, we revert to the `cp -r` implementation and add the `--no-clobber` flag to still preserve the current behavior. Note that `-r` will also create the destination directory if it doesn't …
=> ci: unbreak: Reallow no-op builds

tools/testing/gatekeeper/required-tests.yaml
As the following CI job has been marked as required:
- kata-containers-ci-on-push / run-k8s-tests-on-zvsi / run-k8s-tests (devmapper, qemu, kubeadm)
we need to add it to the gatekeeper's required job list.
=> gatekeeper: add run-k8s-tests-on-zvsi(devmapper) to required jobs

tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
The default initrd confidential target will have a variant=confidential we need to accomodate this
and make sure we also accomodate aaa-xxx-confidential targets.
=> ci: Fix variant for confidential targets

.github/workflows/ci.yaml
The compilation succeeds, however Docker can't find the binary because we specify an absolute path. In Docker world, an absolute path is absolute to the Docker build context (here:
src/tools/csi-kata-directvolume).
To fix this, we link the binary into the build context, where the Dockerfile expects it.
Failure mode:
https://github.com/kata-containers/kata-containers/actions/runs/12068202642/job/33693101962?pr=10563#step:8:213
Note this does NOT affect any required jobs.
Part of: #10560
=> ci: Fix Docker publishing for CSI driver

src/tools/genpolicy/rules.rego
Reuse constants where applicable. This avoids repetition and makes the code easier to maintain.
=> policy: add constants to rules.rego

src/tools/genpolicy/src/obj_meta.rs, tests/integration/kubernetes/runtimeclass_workloads/k8s-policy-pod.yaml
This prevents a deserialization error when uid is specified
More context on uid: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids
=> policy: ignore optional metadata uid field

.github/workflows/ci.yaml
Follow-up to #10609 as it seems GHA doesn't allow hard links:
https://github.com/kata-containers/kata-containers/actions/runs/12144941404/job/33868901896?pr=10563#step:6:8
Note that I also updated the `needs` directive as we don't need the Kata payload container, just the tarball artifact.
Part of: #10560
=> ci: Fix Docker publishing for CSI driver, 2nd try

src/tools/genpolicy/rules.rego
Before this patch there was a mismatch between the JSON path under which the state of the rule evaluation is set in comparison to under which it is retrieved.
This resulted in the behavior that each time the policy was evaluated, it thought it was the _first_ time the policy was evaluated.
This also means that the consistency check for the `sandbox_name` was ineffective.
Also use `sprintf` instead of concat since it is more straightforward to understand.
Note (not included in commit message):
I found this when implementing https://github.com/kata-containers/kata-containers/issues/10529. This necessitates larger refactoring of rust code though. I hope I can a create a draft PR for those changes tomorrow, we can then discuss with concrete proposal in that PR.
=> genpolicy: align state path getter and setter

tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml, tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
We've seen a couple of instances recently where the metrics tests are failing due to the results being below the minimum value by ~2%.
For tests like latency I'm not sure why values being too low would be an issue, but I've updated the minpercent range of the failing tests to try and get them passing.
Updates specifically to address the failure in: https://github.com/kata-containers/kata-containers/actions/runs/11903546209/job/33212069238
```
time="2024-11-19T16:02:07Z" level=debug msg="Compare check for [network-iperf3]"
time="2024-11-19T16:02:07Z" level=debug msg="Checking value [mean]"
time="2024-11-19T16:02:07Z" level=debug msg=" Check minval (0.022000 < 0.021000)"
time="2024-11-19T16:02:07Z" level=warning msg="Failed Minval (0.022000 > 0.021000) for [network-iperf3]"
```
and …
=> metrics: Increase minval range for failing tests

tests/integration/kubernetes/k8s-job.bats
The tests is unstable on this platform, so skip it for now to prevent the regular known failures covering up other issues. See #10616
=> tests: Skip k8s job test on qemu-coco-dev

tools/testing/gatekeeper/jobs.py
In https://github.com/kata-containers/kata-containers/pull/10447 we stumbled across the situation where previously recorded "running" job was never reported as "finished" because they had the same run_id (which makes sense). While on it also improve the message and remove unused variable.
=> ci.gatekeeper: Update existing results

tools/packaging/kata-deploy/helm-chart/kata-deploy/templates/kata-deploy.yaml, tools/packaging/kata-deploy/helm-chart/kata-deploy/templates/kata-rbac.yaml, tools/packaging/kata-deploy/helm-chart/kata-deploy/templates/post-delete-job.yaml, tools/packaging/kata-deploy/helm-chart/kata-deploy/values.yaml, tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml, tools/packaging/kata-deploy/kata-rbac/base/kata-rbac.yaml, tools/packaging/kata-deploy/scripts/kata-deploy.sh
kata-deploy: Add support to multi-installation
This is super useful for development / debugging scenarios, mainly when
dealing with limited hardware availability, as this change allows
multiple people to develop into one single machine, while still using
kata-deploy.
Fixes: #10546
=> kata-deploy: Add support to multi-installation

.github/workflows/release.yaml, tools/packaging/release/release.sh
So users can simply download the chart and use it accordingly without the need to download the full repo.
=> release: helm: Add the chart as part of the release

src/tools/genpolicy/genpolicy-settings.json, src/tools/genpolicy/rules.rego, src/tools/genpolicy/src/policy.rs, tests/integration/kubernetes/k8s-limit-range.bats, tests/integration/kubernetes/tests_common.sh
- Remove the need for specifying `default_namespace` from settings
- Ensure container namespaces in a pod match each other in case no namespace is specified in the YAML
=> policy: improve pod namespace validation

src/runtime-rs/crates/runtimes/virt_container/src/container_manager/process.rs
When tty is enabled, stderr fifo should never be opened.
Fixes: #10637
=> runtime-rs: Fix the issues with stderr fifo

src/runtime-rs/Makefile
This patch fixes that by adding `--release` only if `BUILD_TYPE=release`.
Fixes: #10640
=> runtime-rs: Ignore BUILD_TYPE if it is not release

src/agent/rustjail/src/mount.rs, src/libs/kata-sys-util/src/mount.rs, src/runtime-rs/crates/resource/src/share_fs/virtio_fs_share_mount.rs, src/runtime-rs/crates/resource/src/volume/direct_volume.rs, src/runtime-rs/crates/resource/src/volume/direct_volumes/spdk_volume.rs, src/runtime-rs/crates/resource/src/volume/direct_volumes/vfio_volume.rs, src/runtime-rs/crates/resource/src/volume/share_fs_volume.rs, src/runtime-rs/crates/resource/src/volume/shm_volume.rs
This path fixes the logic of getting the type of volume: when the type of
OCI mount is `Some("none")` and the options have "bind" or "rbind", the
type will be considered as "bind".
Fixes: #10642
=> runtime-rs & agent: Fix the issues with bind volumes

tests/functional/vfio-ap/run.sh
The current script logic assigns an empty string to APID and APQI when APQN consists entirely of zeros (e.g., "00.0000"). However, this behavior is incorrect, as "00" and "0000" are valid values and should be represented as "0".
This PR ensures that the script assigns the default string “0” to APID and APQI if their computed values are empty.
=> vfio-ap: Assign default string "0" for empty APID and APQI

src/tools/kata-ctl/src/ops/exec_ops.rs
MgmnClient can also tolerate short sandbox id.
Signed-off-by: Liu Bo <liub.liubo@gmail.com>
=> kata-ctl: fix outdated comments

tools/packaging/scripts/configure-hypervisor.sh
Building static binaries for aarch64 requires disabling PIE We get an GOT overflow and the OS libraries are only build with fpic and not with fPIC which enables unlimited sized GOT tables.
=> qemu: Fix aarch64 build

.github/workflows/build-kata-static-tarball-amd64.yaml, .github/workflows/build-kata-static-tarball-arm64.yaml, .github/workflows/build-kata-static-tarball-ppc64le.yaml, .github/workflows/build-kata-static-tarball-s390x.yaml
With the code I originally did I think there is potentially a case where we can get a failure due to timing of steps. Before this change the `build-asset-shim-v2`
job could start the `get-artifacts` step and concurrently `remove-rootfs-binary-artifacts` could run and delete the artifact during the download and result in the error. In this commit, I try to resolve this by making sure that the shim build waits for the artifact deletes to complete before starting.
=> workflows: Remove potential timing issues with artifacts

tools/packaging/release/release.sh
In order to check that we don't accidentally overwrite release artifacts, we should add a check if the release name already exists and bail if it does.
=> release: Abort if release version exists

docs/Release-Process.md
Add a step to wait for the payload publish to complete before running the release action.
=> doc: Update the release process

tools/packaging/guest-image/build_image.sh, tools/packaging/guest-image/build_se_image.sh
Fix typos in usage and move the logic of valid check after usage help print.
Fixes: #9386
=> packaging: fix the broken usage help

tests/integration/kubernetes/k8s-job.bats
Fix the logic to make the test skipped on qemu-coco-dev, rather than the opposite and update the syntax to make it clearer as it incorrectly got written and reviewed by three different people in it's prior form.
=> tests: Fix qemu-coc-dev skip

.github/workflows/run-cri-containerd-tests-ppc64le.yaml
In some runs e.g. https://github.com/kata-containers/kata-containers/actions/runs/12426384186/job/34697095588 and https://github.com/kata-containers/kata-containers/actions/runs/12422958889/job/34697016842 we've seen the Prepare the self-hosted runner
and Install dependencies steps get stuck for 5hours+. If they are working then it should take a few minutes, so let's add timeouts and not hold up whole the CI if they are stuck
=> workflows: Add timeout to some ppc64le steps

.github/workflows/build-kata-static-tarball-ppc64le.yaml, .github/workflows/publish-kata-deploy-payload-ppc64le.yaml, .github/workflows/release-ppc64le.yaml, .github/workflows/run-k8s-tests-on-ppc64le.yaml
Unsurprisingly now we've got passed the containerd test hangs on the ppc64le, we are hitting others  in the "Prepare the self-hosted runner" stage, so add timeouts to all of them to avoid CI blockages.
=> workflows: Add more ppc64le timeouts

src/runtime-rs/crates/hypervisor/src/ch/mod.rs, src/runtime-rs/crates/hypervisor/src/device/device_manager.rs, src/runtime-rs/crates/hypervisor/src/dragonball/mod.rs, src/runtime-rs/crates/hypervisor/src/firecracker/mod.rs, src/runtime-rs/crates/hypervisor/src/qemu/mod.rs, src/runtime-rs/crates/hypervisor/src/remote/mod.rs, src/runtime-rs/crates/resource/src/network/endpoint/endpoints_test.rs, src/runtime-rs/crates/runtimes/virt_container/src/lib.rs
`set_hypervisor_config()` and `set_passfd_listener_port()` acquire inner
lock, so that `mut` for `hypervisor` is unneeded.
Fixes: #10682
=> runtime-rs: Remove unneeded `mut` from `new_hypervisor()`

src/tools/kata-ctl/src/ops/volume_ops.rs
Got following issue:
kata-ctl direct-volume add /kubelet/kata-direct-vol-002/directvol002 "{\"device\": \"/home/t4/teawater/coco/t.img\", \"volume-type\": \"directvol\", \"fstype\": \"\", \"metadata\":"{}", \"options\": []}" subsystem: kata-ctl_main
Dec 30 09:43:41.150 ERRO Os {
code: 2,
kind: NotFound,
message: "No such file or directory",
}
The reason is KATA_DIRECT_VOLUME_ROOT_PATH is not exist.
This commit create_dir_all KATA_DIRECT_VOLUME_ROOT_PATH before join_path to handle this issue.
Fixes: #10695
=> kata-ctl: direct-volume: Auto create KATA_DIRECT_VOLUME_ROOT_PATH

tests/common.bash, tests/functional/kata-monitor/gha-run.sh, tests/integration/cri-containerd/gha-run.sh, tests/integration/nydus/gha-run.sh, tests/integration/runk/gha-run.sh, tests/integration/stdio/gha-run.sh, versions.yaml
Since from https://github.com/containerd/containerd/pull/9096 containerd removed cri-containerd-*.tar.gz release bundles, thus we'd better change the tarball name to "containerd".
BTW, the containerd tarball containerd the follow files:
bin/
bin/containerd-shim
bin/ctr
bin/containerd-shim-runc-v1
bin/containerd-stress
bin/containerd
bin/containerd-shim-runc-v2
thus we should untar containerd into /usr/local directory instead of "/" to keep align with the cri-containerd.
In addition, there's no containerd.service file,runc binary and cni-plugin included, thus we should add a specific containerd.service file and install the runc binary and cni-plugin specifically.
=> CI: change the containerd tarball name from cri-containerd-cni to containerd

tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
The bump to kernel 6.12 seems to have reduced the latency in the metrics test, so increase the range for the minimal value, to account for this.
=> metrics: Increase latency minimum range

tests/integration/kubernetes/k8s-oom.bats
Since we bumped to the 6.12.x LTS kernel, we've also adjusted the aggressivity of the OOM test, which may be enough to allow us to re-enable it for mariner.
Fixes: #8821
=> tests: Re-enable oom tests for mariner

tests/integration/kubernetes/k8s-empty-dirs.bats, tools/packaging/static-build/virtiofsd/build-static-virtiofsd.sh, tools/packaging/static-build/virtiofsd/build.sh, versions.yaml
Together with the bump, let's also bump the rust version needed to build the package, with the caveat that virtiofsd doesn't actually use a pinned version as part of their CI, so we're bumping to whatever is the version on `alpine:rust` (which is used in their CI).
=> virtiofsd: Update to its v1.13.0 ( + one patch) release :-)

tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml, tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-qemu-kata-metric8.toml
After the kernel version bump, in the latest nightly run https://github.com/kata-containers/kata-containers/actions/runs/12681309963/job/35345228400 The sequential read throughput result was 79.7% of the expected (so failed) and the sequential write was 84% of the expected, so was fairly close, so increase their minimum ranges to make them more robust.
=> metrics: Increase latency test range

src/runtime/pkg/govmm/qemu/qmp.go
Since https://github.com/qemu/qemu/commit/be93fd53723cbdca675bd9ed112dae5cabbe1e91, which is included in QEMU starting from version 9.2.0, the options for the `device_add` QMP command need to be typed correctly.
This makes it so that instead of `"on"`, the value is set to `true`, matching QEMU's expectations.
This has been tested on QEMU 9.2.0 and QEMU 9.1.2, so before and after the change.
The compatibility with incorrectly typed options  for the `device_add` command is deprecated since version 6.2.0 [^1].
[^1]:  https://qemu-project.gitlab.io/qemu/about/deprecated.html#incorrectly-typed-device-add-arguments-since-6-2
=> runtime: use actual booleans for QMP `device_add` boolean options

versions.yaml
This update addresses an issue with token verification for SE and SNP introduced in the last update by #10541.
Bumping the project to the latest commit resolves the issue.
=> versions: Bump trustee to latest

tools/osbuilder/rootfs-builder/nvidia/nvidia_rootfs.sh
Use "set -x" only when the user specified DEBUG=1.
=> rootfs: reduced console output by default

tools/osbuilder/rootfs-builder/cbl-mariner/Dockerfile.in, tools/osbuilder/rootfs-builder/cbl-mariner/config.sh, versions.yaml
Use Mariner 3.0 (a.k.a., Azure Linux 3.0) as the Guest CI image.
=> image: bump mariner guest version to 3.0

tests/integration/kubernetes/k8s-guest-pull-image.bats, tests/integration/kubernetes/lib.sh
On s390x, some tests for trusted storage occasionally failed due to:
```bash
etcdserver: request timed out
```
or
```bash
Internal error occurred: resource quota evaluation timed out
```
These timeouts were not observed previously on k3s but occur sporadically on kubeadm. Importantly, they appear to be temporary and transient, which means they can be ignored in most cases.
To address this, we introduced a new wrapper function, `retry_kubectl_apply()`, for `kubectl create`. This function retries applying a given manifest up to 5 times if it fails due to a timeout. However, it will still catch and handle any other errors during pod creation.
Fixes: #10651
=> tests: Introduce retry_kubectl_apply() for trusted storage

src/runtime/virtcontainers/sandbox.go
Skip logging empty lines of text from the Guest console output, if there are any such lines.
Without this change, the Guest console log from CLH + /dev/pts/0 has twice as many lines of text. Half of these lines are empty.
Fixes: #10737
=> runtime: skip empty Guest console output lines

tools/packaging/static-build/virtiofsd/gnu/Dockerfile
With ubuntu 20.04 image, `virtiofsd` gnu target couldn't be built due to "unsupported ISA subset z" reported by "cc".
Updating to ubuntu 24.04 image addresses this problem.
Relates: #10739
=> virtiofsd: Update ubuntu to 22.04 for gnu target

tools/osbuilder/rootfs-builder/nvidia/nvidia_rootfs.sh
The pyinstaller is located per default under /usr/local/bin some prior versions were installing it to ${HOME}.
=> gpu: Fix rootfs build

.github/workflows/build-kata-static-tarball-amd64.yaml, .github/workflows/build-kata-static-tarball-arm64.yaml
Adding the initrd build first to get the rootfs on amd64. With that we can start to add tests.
=> gpu: Add rootfs target amd64/arm64

tools/packaging/kata-deploy/local-build/Makefile
Add the kernel dependency to the non coco use-case so that a rootfs build can be executed via GHA.
=> gpu: Add kernel dep for the non coco use-case

.github/workflows/run-k8s-tests-on-aks.yaml, .github/workflows/run-kata-coco-stability-tests.yaml, .github/workflows/run-kata-coco-tests.yaml, .github/workflows/run-kata-deploy-tests-on-aks.yaml
The `Create AKS cluster` step in `run-k8s-tests-on-aks.yaml` is likely
to fail fail since we are trying to issue `PUT` to `aks` in a relatively
high frequency, while the `aks` end has it's limit on `bucket-size` and
`refill-rate`, documented here [1].
Use `nick-fields/retry@v3` to retry in 10 seconds after request fail,
based on observations that AKS were request 7, or 8 second delays
before retry as part of their 429 response
[1] https://learn.microsoft.com/en-us/azure/aks/quotas-skus-regions#throttling-limits-on-aks-resource-provider-apis
Fixes: #10772
=> ci: Retry on failure of Create AKS cluster

.github/actionlint.yaml, .github/workflows/build-kata-static-tarball-arm64.yaml, .github/workflows/publish-kata-deploy-payload-arm64.yaml, .github/workflows/release-arm64.yaml
Now that gituhb have hosted arm runners
https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/ we should try and switch our arm64 builder jobs to run on these.
=> workflows: Switch to github-hosted arm runners

tools/osbuilder/image-builder/image_builder.sh, tools/osbuilder/rootfs-builder/rootfs.sh
1. Move the deletion of systemd units and files from image_builder.sh into rootfs.sh. 
- This allows other image file formats to benefit from the deletion of unnecessary systemd units and files, not just the rootfs-image format created by image_builder.sh.
- Also, image_builder.sh was deleting these files *after* it calculated the size of the rootfs files, thus missing out on the opportunity to possibly create a smaller image file.
2. Delete symbolic links to files being deleted.
=> rootfs: minor systemd file deletion cleanup

.github/workflows/static-checks-self-hosted.yaml, tools/testing/gatekeeper/required-tests.yaml
Now we have the build-assets running on the gh-hosted runners, try the same approach for the static-checks
=> workflows: Move arm static checks runner

tools/packaging/scripts/lib.sh, tools/packaging/static-build/virtiofsd/build.sh, tools/packaging/static-build/virtiofsd/gnu/Dockerfile
With this change, `virtiofsd` (gnu target) could be built and then to be used with other components.
Depends: #10741
Fixes: #10739
=> virtiofsd: Enable build for RISC-V

src/runtime/data/completions/bash/kata-runtime
Raised during package review [1] by rpmlint
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1590425#c8
=> Remove shebang in non-executable completion script

tests/metrics/cmd/checkmetrics/ci_worker/checkmetrics-json-clh-kata-metric8.toml
In the last couple of days I've seen the blogbench metrics write latency test on clh fail a few times e.g. https://github.com/kata-containers/kata-containers/actions/runs/12931225043/job/36067164331?pr=10779 because the latency was too low, so adjust the minimum range to tolerate quicker finishes.
=> metrics: Increase minval range for blogbench test

tools/packaging/static-build/virtiofsd/build-static-virtiofsd.sh
#10714 added support for building a specific commit, but due to the clone only having `--depth=1`, we can only reset to a commit if it's the latest on the `main` branch, otherwise we will get:
```
+ git clone --depth 1 --branch main https://gitlab.com/virtio-fs/virtiofsd virtiofsd
Cloning into 'virtiofsd'...
warning: redirecting to https://gitlab.com/virtio-fs/virtiofsd.git/
+ pushd virtiofsd
+ git reset --hard cecc61bca981ab42aae6ec490dfd59965e79025e
...
fatal: Could not parse object 'cecc61bca981ab42aae6ec490dfd59965e79025e'.
```
=>  packaging: virtiofsd: Allow building a specific commit

versions.yaml
The static_checks_versions test uses yamllint which fails with:
```
[comments] too few spaces before comment
```
many times and so makes code reviews more annoying with all these extra messages. Other it's probably not the worse issues, I checked the
[yaml spec](https://yaml.org/spec/1.2.2/#66-comments) and it does say
> Comments must be separated from other tokens by white space character**s**
so it's easiest to fix it and move on.
=> versions: Fix formatting

.github/workflows/run-k8s-tests-on-amd64.yaml
I've seen cases for the qemu, crio, k0s tests where Delete kata-deploy is still running for this test after 2 hours, and had to be manually cancelled, so let's try adding a 5m timeout to the kata-deploy delete to stop CI jobs hanging.
=> workflows: Add delete kata-deploy timeouts for crio tests

src/runtime/config/configuration-clh.toml.in, src/runtime/pkg/katautils/config-settings.go.in, src/runtime/pkg/katautils/config.go, src/runtime/pkg/katautils/config_test.go, src/runtime/virtcontainers/clh.go, src/runtime/virtcontainers/hypervisor.go
Introduce new config, hypervisor_loglevel, which allows the user to specify the verbosity of the hypervisor.
=> CLH: config: add hypervisor_loglevel

tests/integration/kubernetes/k8s-guest-pull-image.bats, tests/integration/kubernetes/k8s-measured-rootfs.bats, tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
IBM SE has encountered a boot failure issue since the guest OS was upgraded to Ubuntu 22.04. We identified that the issue is caused by the initramfs, which is built for the measured rootfs scenario. IBM SE ensures that the initrd is measured by genprotimg and verified by the ultravisor. To address this, let’s skip building the measured rootfs on s390x. This PR also skips end-to-end tests for trusted storage for IBM SE.
For reviewers: the changes are already verified at https://github.com/kata-containers/kata-containers/actions/runs/13150558902/job/36740406368
FYI: @hbrueckner
=> local-build: Do not build measured rootfs on s390x

tests/integration/kubernetes/k8s-policy-job.bats
k8s-policy-job is modeled after the older k8s-job, and it appears that both of them fail occasionally on coco-dev.
=> tests: disable k8s-policy-job.bats on coco-dev

.github/workflows/build-kata-static-tarball-amd64.yaml, .github/workflows/build-kata-static-tarball-arm64.yaml
We introduced extratarballs with a make target. The CI  currently only uploads tarballs that are listed in the matrix. The NV kernel builds a headers package which needs to be uploaded  as well. The get-artifacts has a glob to download all artifacts hence we should be good.
Depends on: ~~https://github.com/kata-containers/kata-containers/pull/10749~~  ~~https://github.com/kata-containers/kata-containers/pull/10785~~
=> gpu: Add first target and fix extratarballs 

.github/actionlint.yaml, .github/workflows/run-kata-coco-tests.yaml
We've been hitting issues with the CentOS 9 Stream machine, which Intel doesn't have cycles to debug.
After raising this up in the Confidential Containers community meeting we got the green light from Red Hat (Ariel Adam) to just disable the CI based on CentOS 9 Stream for now.
=> ci: Only use the Ubuntu TDX machine in the CI

.github/workflows/build-kata-static-tarball-amd64.yaml
Otherwise we may end up simply unpacking kata-containers specific
binaries into the same location that system ones are needed, leading to
a broken system (most likely what happened with the metrics CI, and also
what's happening with the GHA runners).
=> workflows: build: Do not store unnecessary content on the tarball

src/runtime-rs/config/configuration-cloud-hypervisor.toml.in, src/runtime-rs/config/configuration-dragonball.toml.in, src/runtime-rs/config/configuration-rs-fc.toml.in, src/runtime-rs/crates/hypervisor/src/ch/inner.rs, src/runtime-rs/crates/hypervisor/src/ch/inner_device.rs, src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs, src/runtime-rs/crates/hypervisor/src/qemu/cmdline_generator.rs, src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
The config block_device_cache_direct of runtime-rs is messy.
qemu and ch can support this config but doesn't have code for it.
db has this config support but its config file doesn't have this config.
fc cannot support this config but its config file has it.
This PR fixes the issues.
=> Clean the config block_device_cache_direct of runtime-rs

tests/integration/kubernetes/gha-run.sh
Skipping SNP and SEV from deploying and deleting Snapshotter from the gha-run.sh script similar to how Intel is skipping TDX. This may be a temporary fix, to first check if the AMD node becomes more stable with this change. If it does, will repoen [10792](https://github.com/kata-containers/kata-containers/pull/10792) and [10793](https://github.com/kata-containers/kata-containers/pull/10793).
=> Skipping SNP and SEV from deploying and deleting Snapshotter

tests/gha-run-k8s-common.sh
When trying to deploy nydus on kcli locally we get the following failure:
```
root@sh-kata-ci1:~# kubectl get pods -n nydus-system
NAMESPACE                   NAME                                          READY   STATUS              RESTARTS      AGE
nydus-system                nydus-snapshotter-5kdqs                       0/1     CrashLoopBackOff    4 (84s ago)   7m29s
```
Digging into this I found that the nydus-snapshotter service is failing with:
```
ubuntu@kata-k8s-worker-0:~$ journalctl -u nydus-snapshotter.service
-- Logs begin at Wed 2025-02-12 15:06:08 UTC, end at Wed 2025-02-12 15:20:27 UTC. --
Feb 12 15:10:39 kata-k8s-worker-0 systemd[1]: Started nydus snapshotter.
Feb 12 15:10:39 kata-k8s-worker-0 containerd-nydus-grpc[6349]: /usr/local/bin/containerd-nydus-grpc: …
```
=> ci: k8s: Bump kcli image version

ci/install_yq.sh
In v4.44.5 of `yq`, artifacts for riscv64 are released. Update the version used for `yq` and enable `install_yq.sh` to work on riscv64.
=> ci: Update yq to v4.44.5 to support riscv64

.github/workflows/run-kata-coco-tests.yaml
Phase 1 of Issue #10840
AMD has deprecated SEV support on
Kata Containers, and going forward,
SNP will be the only AMD feature
supported. As a first step in this
deprecation process, we are removing
the SEV CI workflow from the test suite
to unblock the CI.
Will be adding future commits to
remove redundant SEV code paths.
=> CI: Deprecate SEV

tools/packaging/kata-deploy/local-build/kata-deploy-merge-builds.sh
The tags created automatically for published Github releases are probably not annotated, so by simply running `git describe` we are not getting the correct tag. Use a `git describe --tags` to allow git to look at all tags, not just annotated ones.
=> packaging(release): Properly handle version tag for the release bundle

src/agent/rustjail/src/cgroups/fs/mod.rs, src/agent/rustjail/src/cgroups/systemd/dbus_client.rs, src/agent/rustjail/src/cgroups/systemd/manager.rs
This is a fix for issue https://github.com/kata-containers/kata-containers/issues/10733
=> Add process to init subcgroup when we're using dind with cgroups v2

src/agent/Cargo.lock, src/agent/Cargo.toml, src/agent/src/image.rs, src/agent/src/rpc.rs, tests/integration/kubernetes/k8s-guest-pull-image-signature.bats
As this brings in the commit bumping ttrpc to 0.8.4, which fixes connection issues with kernel 6.12.9+.
As image-rs has a new builder pattern and several of the values in the image client config have been renamed, let's change the agent to account for this.
=> agent: Bump image-rs to 514c561d93

src/agent/Cargo.lock
Manually bump some dependencies we bring in to resolve the agent's main CVEs
=> agent: Bump agent crates to resolve CVEs

src/agent/src/config.rs, src/agent/src/device/mod.rs, src/agent/src/rpc.rs
Some systems like a DGX where we have 8 H100 or 8 H800 GPUs
need some extended time to be initialized. We need to make
sure we can configure CDI timeout, to enable even systems with 16 GPUs.
=> gpu: agent cdi timeout

src/tools/genpolicy/Cargo.lock, src/tools/genpolicy/Cargo.toml, src/tools/genpolicy/src/registry.rs, src/tools/genpolicy/src/registry_containerd.rs
This picks up a security fix for confidential pulling of unsigned images.
The crate moved permanently to oci-client, which required a few import changes.
=> genpolicy: bump oci-distribution to v0.12.0

tools/packaging/kata-deploy/examples/test-deploy-kata-qemu.yaml
An image `registry.k8s.io/hpa-example` used in the kata-deploy [example](https://github.com/kata-containers/kata-containers/blob/main/tools/packaging/kata-deploy/README.md#run-a-sample-workload) and the minikube [installation](https://github.com/kata-containers/kata-containers/blob/main/docs/install/minikube-installation-guide.md#testing-kata-containers) only supports amd64. Let's use a multi-arch image `quay.io/prometheus/prometheus` for the QEMU example instead.
=> example: Use multi-arch image for test-deploy-kata-qemu.yaml

tests/cmd/check-spelling/data/main.txt, tests/cmd/check-spelling/kata-dictionary.dic, tests/static-checks.sh
- spell: Add missing entries for kata-spell-check:
`kata-dictionary.dic` changes after running `kata-spell-check.sh make-dict`. This is due to someone forgot to first update entries in data and run `make-dict`, but directly updated `kata-dictionary.dic` instead.
Add mssing entries to data and re-run `make-dict` to generate correct `kata-dictionary.dic`.
- header_check: Check header for changed text files:
We are running `header_check` for non-text files like binary files, symbolic link files, image files (pictures) and etc., which does not make sense.
Filter out non-text files and run `header_check` only for text files changed.
=> ci: Fix spell_check and improve header_check

tools/packaging/kata-deploy/local-build/Makefile, tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh, versions.yaml
Since SNP moved to upstream QEMU we're repurposing the experimental target for the GPU builds. The GPU related PRs are not yet fully upstream and merged in mainline QEMU. 
I am taking care of the branches on confidential-containers/qemu for SNP and TDX for the GPU work.
=> gpu: QEMU SNP+TDX experimental updates

tests/common.bash
On Ubuntu 24.04, due to the `/usr` merge, system-provided unit files now reside in `/usr/lib/systemd/system/` instead of `/lib/systemd/system/`. For example, the command below now returns a different path:
```
$ systemctl show containerd.service -p FragmentPath
/usr/lib/systemd/system/containerd.service
```
Previously, on Ubuntu 22.04 and earlier, it returned:
```
/lib/systemd/system/containerd.service
```
The current pattern `if [[ $unit_file == /lib* ]]` fails to match the new path. To ensure compatibility across versions, we update the pattern to match both `/lib` and `/usr/lib` like:
```
if [[ $unit_file =~ ^/(usr/)?lib/ ]]
```
=> tests: Support systemd unit files in /usr/lib as well as /lib

src/agent/src/rpc.rs, tests/integration/kubernetes/k8s-policy-logs.bats, tests/integration/kubernetes/run_kubernetes_tests.sh
Container logs are forwarded to the agent through a unix pipe. These pipes have limited capacity and block the writer when full. If reading logs is blocked by policy, a common setup for confidential containers, the pipes fill up and eventually block the container.
This commit changes the implementation of `ReadStream` such that it returns empty log messages instead of a policy failure (in case reading log messages is forbidden by policy). As long as the runtime does not encounter a failure, it keeps pulling logs periodically. In turn, this triggers the agent to flush the pipes.
Fixes: #10680
---
* The agent could unconditionally pull from the pipe but still return a policy error, and the runtime could keep pulling in case of policy errors. This would arguably make the agent service …
=> agent: clear log pipes if denied by policy

.github/workflows/build-kata-static-tarball-s390x.yaml
This is the first attempt to remove the following code:
```
if [ "${ARCH}" == "s390x" ]; then
export MEASURED_ROOTFS=no
fi
```
from install_shimv2() in kata-deploy-binaries.sh.
=> GHA: Turn off MEASURED_ROOTFS in build-kata-static-tarball-s390x

tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
As a follow-up for #10904, we do not need to set MEASURED_ROOTFS to no on s390x explicitly. The GHA workflow already exports this variable. This commit removes the redundant assignment.
=> shim-v2: Remove MEASURED_ROOTFS assignment for s390x

src/runtime/config/configuration-qemu-snp.toml.in
Adding disable nesting_checks for SNP config file upstream. This check isn't needed for majority of SNP deployments. Was brought up in a conversation by @jepio.
=> Disabling Nesting Check for SNP upstream

.github/actionlint.yaml, .github/workflows/ci.yaml, .github/workflows/run-k8s-tests-on-arm64.yaml, tests/integration/kubernetes/k8s-memory.bats, tests/integration/kubernetes/k8s-pod-quota.bats, tests/integration/kubernetes/k8s-sandbox-vcpus-allocation.bats
As one has a problem to fully disconnect, I've taken my first day off to take a look at what was needed to get the ARM CI back up, and I did it together with @kevinzs2048.
This PR brings the CI back up, the CI will be maintained by @kevinzs2048 himself, and it's running on the self-hosted runner that was not being utilised for anything anymore since we switched to using the GitHub hosted runners to do the ARM builds.
I've disabled 3 tests, which @kevinzs2048 will be working on to re-enable them in sooner than later.
The disabled tests are:
* https://github.com/kata-containers/kata-containers/issues/10926
* https://github.com/kata-containers/kata-containers/issues/10927
* https://github.com/kata-containers/kata-containers/issues/10928
Here is a manually triggered run with this PR:
* …
=> arm: ci: k8s: Enable CI

src/agent/Makefile, src/runtime-rs/Makefile, src/tools/agent-ctl/Makefile, src/tools/genpolicy/Makefile, src/tools/runk/Makefile, src/tools/trace-forwarder/Makefile
There are many `override ARCH = powerpc64le` after where `utils.mk` is included, which are redundant.
Drop those redundant `override`s.
=> build: Drop redundant ARCH override

src/runtime/pkg/device/drivers/utils.go
We need a proper ID otherwise QEMU sometimes fails with invalid ID.  Use the same pattern as with the old VFIO implementation.
=> gpu: IOMMUFD fix

src/libs/kata-sys-util/src/protection.rs, src/libs/kata-types/src/config/hypervisor/mod.rs, src/runtime-rs/crates/hypervisor/ch-config/src/convert.rs, src/runtime-rs/crates/hypervisor/ch-config/src/lib.rs, src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs, src/runtime-rs/crates/hypervisor/src/device/device_manager.rs, src/runtime-rs/crates/hypervisor/src/device/driver/mod.rs, src/runtime-rs/crates/hypervisor/src/device/driver/protection_device.rs, src/runtime-rs/crates/hypervisor/src/device/mod.rs, src/runtime-rs/crates/hypervisor/src/dragonball/inner_device.rs, src/runtime-rs/crates/hypervisor/src/qemu/cmdline_generator.rs, src/runtime-rs/crates/hypervisor/src/qemu/inner.rs, src/runtime-rs/crates/resource/src/lib.rs, src/runtime-rs/crates/resource/src/manager_inner.rs, src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
This PR adds `ProtectionDevice`, a new `DeviceType` to represent protection devices.
The implementation and handling of `ProtectionDevice` aims to be as similar as possible to other devices and to fit well into runtime-rs's device handling architecture.  I'd really appreciate review from @lifupan , @studychao or @Apokleos to verify that.
The PR might look like it also adds support for AMD's SEV/SEV-SNP TEEs but that's actually not a goal.  While a bulk of SEV/SEV-SNP support _is_ added parts are still missing and this work requires careful review and testing (@ryansavino ).  SEV/SEV-SNP was only used as a test case to make sure that the support framework I was creating made some sense, and I could obviously do no real testing (apart from faking detection of SEV or SEV-SNP and making sure …
=> runtime-rs: TEE support framework

src/agent/src/cdh.rs, src/agent/src/rpc.rs
As the guest-pull is a very Confidental Containers specific feature, let's make sure we, at least, don't break folks who decide to build Kata Containers' agent without having this feature enabled (for instance, for the sake of the agent size).
This was tested by building the agent with the following patch:
```sh
diff --git a/src/agent/Cargo.toml b/src/agent/Cargo.toml
index 34a39b561..d746ad492 100644
--- a/src/agent/Cargo.toml
+++ b/src/agent/Cargo.toml
@@ -99,7 +99,7 @@ lto = true
[features]
-default-pull = ["guest-pull"]
+default-pull = []
seccomp = ["rustjail/seccomp"]
standard-oci-runtime = ["rustjail/standard-oci-runtime"]
agent-policy = [ "kata-agent-policy" ]
```
=> agent: Fix non-guest-pull build

src/runtime/pkg/containerd-shim-v2/create.go, src/runtime/virtcontainers/sandbox.go
Adding devices by CDI annotation can fail for a variety of reasons. If that happens, it's helpful to know the root cause of the issue (CDI spec missing, malformatted, requested device not present, etc.).
This commit adds the root cause of the CDI device addition to the errors reported back to the caller. Since this error is bubbled up all the way back to the shimv2 task.Create handler, it will be visible in Kubernetes logs and enable fixing the root cause.
cc @zvonkok
=> runtime: add cause to CDI errors

src/tools/genpolicy/src/cronjob.rs
This function was accidentally left unimplemented for `CronJob`, resulting in `runAsUser` not being supported there.
Fixes: #10653
---
cc @Redent0r
=> genpolicy: add get_process_fields to CronJob

src/tools/genpolicy/src/registry.rs, src/tools/genpolicy/src/registry_containerd.rs
Currently, if a layer can't be processed, we log this a warning and continue execution, finally exit with a zero exit code. This can lead to the generation of invalid policies. One reason a layer might not be processed is that the pull of that layer fails.
We need all layers to be processed successfully to generate a valid policy, as otherwise we will miss the verity hash for that layer or we might miss the USER information from a passwd stored in that layer. This will cause our VM to not get through the agent's policy validation.
Returning an error instead of printing a warning will cause genpolicy to fail in such cases.
=> genpolicy: fail when layer can't be processed

src/tools/genpolicy/genpolicy-settings.json, src/tools/genpolicy/rules.rego, src/tools/genpolicy/src/containerd.rs, src/tools/genpolicy/src/cronjob.rs, src/tools/genpolicy/src/daemon_set.rs, src/tools/genpolicy/src/deployment.rs, src/tools/genpolicy/src/job.rs, src/tools/genpolicy/src/pod.rs, src/tools/genpolicy/src/policy.rs, src/tools/genpolicy/src/replica_set.rs, src/tools/genpolicy/src/replication_controller.rs, src/tools/genpolicy/src/stateful_set.rs, src/tools/genpolicy/src/yaml.rs, src/tools/genpolicy/tests/main.rs, src/tools/genpolicy/tests/testdata/createcontainer/sysctls/pod.yaml, src/tools/genpolicy/tests/testdata/createcontainer/sysctls/testcases.json
Sysctls may be added to a container by the Kubernetes pod definition or by containerd configuration. The main commit adds support for the corresponding PodSecurityContext field and an option to specify environment-dependent sysctls in the settings file.
The sysctls requested in a `CreateContainerRequest` are checked against the sysctls in the pod definition, or if not defined there in the defaults in genpolicy-settings.json. There is no check for the presence of expected sysctls, though, because Kubernetes might legitimately omit unsafe syscalls itself and because default sysctls might not apply to all containers.
---
Notes to reviewers (@Redent0r, @danmihai1) : 
1. I'm leaving this as draft until #10613 is merged and I can test with that. Feel free to ignore the test cases for now.
2. We …
=> genpolicy: support sysctls from PodSpec and environment defaults

.github/workflows/codeql.yml
I noticed that CodeQl using the default config hasn't scanned since May 2024, so figured it would be worth trying an explicit configuration to see if that gets better results. It's mostly the template, but updated to be more relevant:
- Only scan PRs and pushes to the `main` branch
- Set a pinned runner version rather than latest (with mac support)
- Edit the list of languages to be scanned to be more relevant for kata-containers
=> workflows: Add codeql config

tools/packaging/kata-deploy/helm-chart/kata-deploy/templates/_helpers.tpl, tools/packaging/kata-deploy/kata-cleanup/overlays/k0s/mount_k0s_conf.yaml
The drop-in path should be /etc/containerd (from the containers' perspective), which mounts to the host path /etc/k0s/containerd.d.
With what we had we ended up dropping the file under the /etc/k0s/containerd.d/containerd.d/, which is wrong.
This is a regression introduce by: 94b3348d3c
=> kata-deploy: k0s: Fix drop-in path

src/agent/src/ccw.rs, src/agent/src/device/network_device_handler.rs, src/agent/src/rpc.rs, src/libs/protocols/protos/types.proto, src/runtime-rs/crates/agent/src/kata/trans.rs, src/runtime-rs/crates/agent/src/types.rs, src/runtime-rs/crates/resource/src/network/network_info/network_info_from_dan.rs, src/runtime-rs/crates/resource/src/network/network_info/network_info_from_link.rs, src/runtime/virtcontainers/endpoint.go, src/runtime/virtcontainers/ipvlan_endpoint.go, src/runtime/virtcontainers/macvlan_endpoint.go, src/runtime/virtcontainers/macvtap_endpoint.go, src/runtime/virtcontainers/network.go, src/runtime/virtcontainers/physical_endpoint.go, src/runtime/virtcontainers/pkg/agent/protocols/types.pb.go, src/runtime/virtcontainers/qemu.go, src/runtime/virtcontainers/qemu_arch_base.go, src/runtime/virtcontainers/qemu_s390x.go, src/runtime/virtcontainers/sandbox.go, src/runtime/virtcontainers/tap_endpoint.go, src/runtime/virtcontainers/tuntap_endpoint.go, src/runtime/virtcontainers/types/ccw.go, src/runtime/virtcontainers/types/ccw_test.go, src/runtime/virtcontainers/veth_endpoint.go, src/runtime/virtcontainers/vfio_endpoint.go, src/runtime/virtcontainers/vhostuser_endpoint.go
The s390x architecture uses `virtio-net-ccw` instead of `virtio-net-pci`.
- Device number was formatted wrong in virtcontainers. Fix, and implement device structure like for PCI.
- Find device (by uevent or already existing) in agent, using the appropriate path for PCI or CCW.
This re-enables e.g.
```
$ docker run --runtime io.containerd.run.kata.v2 --rm busybox ping -c1 katacontainers.io
PING katacontainers.io (75.2.60.5): 56 data bytes
64 bytes from 75.2.60.5: seq=0 ttl=229 time=9.398 ms
--- katacontainers.io ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 9.398/9.398/9.398 ms
```
on s390x :)
cc @BbolroC @hbrueckner 
e: this definitely requires forward porting to runtime-rs, but from my first glance, the virtio-net implementation …
=> Fix virtio-net-ccw

tools/osbuilder/rootfs-builder/nvidia/nvidia_rootfs.sh
With the recent changes we need to make sure NVRC is symlinked for init and sbin/init
=> gpu: fix init symlinks

src/runtime/pkg/katautils/config.go, src/runtime/pkg/katautils/config_test.go
The documented behavior was that the clh loglevel was set to 1 if unspecified. This was in actuality 0; properly fix the default logic to reflect the documented/expected result.
=> runtime: Properly set default hyp loglevel to 1

src/agent/src/device/mod.rs, src/agent/src/rpc.rs, src/agent/src/sandbox.rs
We had a static mapping of host guest PCI addresses, which prevented to use VFIO devices in initContainers. We're tracking now the host-guest mapping per container and removing this mapping if a container is removed.
We do not properly support VFIO with initContainers or containers in a Pod with different life-cycles (with pass-through devices), In the outer runtime we allocate a root-port slot and deallocate a root-port slot when  creating a container and stopping deleting a container. The kata-agent only does a sb.pcimap.insert(host, guest) but never deallocates the mapping, which needs to be done during stop/delete container to free up the mapping.
```
create initContainer - bind GPU -> alloc: root-port slot 0000:02.0 - agent.pcimap.insert (host, guest)
stop   initContainer - unbind …
```
=> agent: Enable VFIO and initContainers

src/agent/rustjail/src/mount.rs
The previous PR mistakenly set all perms to 0o666 we should follow what runc does and fetch the permission from the guest aka host if the file_mode == 0. If we do not find the device on the guest aka host fallback to 0.
=> agent: fix permisssion according to runc

src/runtime/virtcontainers/qemu_s390x.go
After the introduction of the following kernel parameters on s390x (see #6163):
```
CONFIG_SCLP_VT220_TTY=y
CONFIG_SCLP_VT220_CONSOLE=y
```
the system log for Kata components (e.g., the agent) no longer appeared on the SCLP console (i.e., /dev/ttysclp0).
Let's switch to the default fallback console (likely /dev/console) for logging on the platform.
=> runtime: Remove console=ttysclp0 for s390x

src/libs/kata-types/tests/test_config.rs
It will address two issuses:
(1) expected `,`:
-->
/root/kata-containers/src/libs/kata-types/tests/test_config.rs:15:9
|
14 |         KATA_ANNO_CFG_HYPERVISOR_ENABLE_IO_THREADS
|                                                   -
|                                                   |
|                                                   expected one of
`,`, `::`, `as`, or `}`
|                                                   help: missing `,`
15 |         KATA_ANNO_CFG_HYPERVISOR_FILE_BACKED_MEM_ROOT_DIR,
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
unexpected token
(2) remove useless annotation `KATA_ANNO_CFG_HYPERVISOR_CTLPATH`.
Fixes #10936
=> kata-types: Fix bugs related to annotations in kata-types

src/runtime-rs/config/configuration-dragonball.toml.in
Add double quotes to fix log_level's comments in
configuration-dragonball.toml.in.
Fixes: #10974
=> runtime-rs: Fix log_level's comments in configuration-dragonball.toml.in

.github/workflows/basic-ci-amd64.yaml, tests/integration/cri-containerd/integration-tests.sh, versions.yaml
As we're testing against the LTS and the Active versions of containers, let's upgrade the lts version from 1.6 to 1.7 and active version from 1.7 to 2.0 to cover the sandboxapi tests.
=> ci: cri-containerd: upgrade the LTS / Active versions for containerd

src/libs/kata-types/src/config/hypervisor/mod.rs, src/runtime-rs/crates/hypervisor/src/device/driver/protection_device.rs, src/runtime-rs/crates/hypervisor/src/qemu/cmdline_generator.rs, src/runtime-rs/crates/hypervisor/src/qemu/inner.rs, src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
An almost trivial PR to remove support of the obsolete `snp_certs_path` setting.
=> runtime-rs: remove snp certs path support from qemu-rs

src/runtime-rs/crates/hypervisor/Cargo.toml, src/runtime-rs/crates/hypervisor/src/kernel_param.rs, src/runtime-rs/crates/hypervisor/src/lib.rs, src/runtime-rs/crates/runtimes/virt_container/src/lib.rs, src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
- runtime-rs: Drop s390x target predicates: Drop `target_arch = "s390x"` all over `runtime-rs` since `dragonball` feature is not enabled.
- runtime-rs: Restrict cloud-hypervisor feature: Cloud-Hypervisor currently only supports `x86_64` and `aarch64`, this features should not be avaiable even if other architectures explicitly requires it.
Restrict `cloud-hypervisor` feature to only `x86_64` and `aarch64`.
=> runtime-rs: Remove s390x conditional compilation

tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile
Switch to `docker.io` provided by Ubuntu sources. It is not necessary for us to install docker through `get-docker.sh`.
=> kata-deploy: Use docker.io for all architectures

tests/git-helper.sh
The workplace was already being deleted on non-x86_64 platforms, but x86_64 can be affected by the same problem too. That might have been the case with the SNP and TDX test runs from:
https://github.com/kata-containers/kata-containers/actions/runs/13687511270/job/38313758751?pr=10973
https://github.com/kata-containers/kata-containers/actions/runs/13687511270/job/38313760086?pr=10973
Rebase worked fine for the same PR #10973 on other platforms - but not on these two x86_64 platforms.
TDX might have recovered successfully using this git-helper.sh change - here:
https://github.com/kata-containers/kata-containers/actions/runs/13705989000/job/38332494333?pr=10973
```
Adding user name and email to the local git repo
Rebasing atop of the latest main
fatal: It seems that there is already a …
```
=> gha: always delete workspace on rebase error

tests/integration/kubernetes/k8s-configmap.bats, tests/integration/kubernetes/k8s-env.bats, tests/integration/kubernetes/tests_common.sh
Log the "kubectl exec" ouput, just in case it helps investigate sporadic test errors like:
https://github.com/kata-containers/kata-containers/actions/runs/13724022494/job/38387329268?pr=10973
```not ok 1 ConfigMap for a pod
(in test file k8s-configmap.bats, line 44)
`kubectl exec $pod_name -- "${exec_command[@]}" | grep "KUBE_CONFIG_2=value-2"' failed
```
https://github.com/kata-containers/kata-containers/actions/runs/13724022494/job/38387329321?pr=10973
```not ok 1 Environment variables
(in test file k8s-env.bats, line 37)
`grep "HOST_IP=\([0-9]\+\(\.\|$\)\)\{4\}"' failed
```
=> tests: k8s: log kubectl exec ouput

.github/workflows/build-checks-preview-riscv64.yaml, .github/workflows/build-checks.yaml
- ci: Drop install-libseccomp matrix variant
`install-libseccomp` is applied only for `agent` component, and we are already combining matrix with `if`s in steps, drop `install-libseccomp` in matrix to reduce complexity.
- ci: Refactor build-checks workflow
Refator matrix setup and according dependencies installation logic in`build-checks.yaml` and `build-checks-preview-riscv64.yaml` to provide better readability and maintainability.
- ci: Move musl-tools installation into Setup rust
`musl-tools` is only needed when a component needs `rust`, and the `instance` running is of `x86_64` or `aarch64`.
=> ci: Refactor matrix for `build-checks`

tests/gha-run-k8s-common.sh, tests/integration/kubernetes/setup.sh, tests/integration/kubernetes/tests_common.sh
Disable the Mariner host during CI, while investigating test failures with new Cloud Hypervisor v43.0.
=> ci: temporarily avoid using the Mariner Host image

tests/integration/kubernetes/k8s-guest-pull-image.bats
follow other TEEs to skip trusted storage tests due to #10838.
=> tests: k8s: skip trusted storage tests for qemu-tdx

src/agent/src/rpc.rs, src/libs/kata-types/src/config/hypervisor/dragonball.rs, src/libs/kata-types/src/config/hypervisor/mod.rs, src/libs/kata-types/src/config/hypervisor/qemu.rs, src/libs/protocols/protos/agent.proto, src/runtime-rs/config/configuration-cloud-hypervisor.toml.in, src/runtime-rs/config/configuration-dragonball.toml.in, src/runtime-rs/config/configuration-qemu-runtime-rs.toml.in, src/runtime-rs/crates/agent/src/kata/agent.rs, src/runtime-rs/crates/agent/src/kata/trans.rs, src/runtime-rs/crates/agent/src/lib.rs, src/runtime-rs/crates/agent/src/types.rs, src/runtime-rs/crates/hypervisor/src/ch/inner_device.rs, src/runtime-rs/crates/hypervisor/src/device/driver/virtio_blk.rs, src/runtime-rs/crates/hypervisor/src/dragonball/inner_device.rs, src/runtime-rs/crates/hypervisor/src/qemu/inner.rs, src/runtime-rs/crates/resource/src/cpu_mem/mem.rs, src/runtime-rs/crates/resource/src/cpu_mem/mod.rs, src/runtime-rs/crates/resource/src/cpu_mem/swap.rs, src/runtime-rs/crates/resource/src/manager_inner.rs
This PR add guest swap support to runtime-rs.
When configuration enable_guest_swap is enabled, runtime-rs will start a swap task.
When the VM start or update the guest memory, the swap task will be waked up to create and insert a swap file.
Before this job, swap task will sleep some seconds (set by configuration guest_swap_create_threshold_secs) to reduce the impact on guest kernel boot performance and prevent the insertion of multiple swap files due to frequent memory elasticity within a short period.
The size of swap file is set by configuration guest_swap_size_percent.
The percentage of the total memory to be used as swap device.
Remove swap configuration from qemu config file because runtime-rs qemu support code doesn't support hotplug block device.
Fixes: #10988
=> runtime-rs: Add guest swap support

.github/workflows/shellcheck.yaml, .github/workflows/shellcheck_required.yaml
- In the previous PR I only skipped the runtime/vendor directory, but errors are showing up in other vendor packages, so try a wildcard skip
- Also update the job step was we can distinguish between the required and non-required versions
=> workflows: shellcheck: Expand vendor ignore

tools/testing/gatekeeper/required-tests.yaml
As shown by the dashboard: https://kata-containers.github.io/coco both the zvsi and non-tee coco tests have had ten passing nightly runs and maintainers of good standing in the community (and me). Admittedly for non-tee this does include some re-runs I believe (which we have discussed labeling in some way on the dashboard), but based on popular opinion I think we probably want to go ahead and make these both required now.
=> ci: Add coco required tests

tests/integration/kubernetes/k8s-policy-pod.bats
Test using the host path /tmp/k8s-policy-pod-test instead of /var/lib/kubelet/pods.
/var/lib/kubelet/pods might happen to contain files that CopyFileRequest would try to send to the Guest before CreateContainerRequest. Such CopyFileRequest was an unintended side effect of this test.
=> tests: k8s-policy-pod: safer host path volume source

src/tools/genpolicy/Cargo.lock, src/tools/genpolicy/Cargo.toml, src/tools/genpolicy/rules.rego, src/tools/genpolicy/src/obj_meta.rs, src/tools/genpolicy/tests/main.rs, src/tools/genpolicy/tests/testdata/createcontainer/generate_name/pod.yaml, src/tools/genpolicy/tests/testdata/createcontainer/generate_name/testcases.json
Validate sandbox name using a regex. If the YAML specifies metadata.name, use a regex that exact matches.
If the YAML specifies metadata.generateName, use a regex that matches the prefix of the generated name.
Context: see generateName in https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#objectmeta-v1-meta
=> policy: validate pod generated name

src/tools/genpolicy/genpolicy-settings.json, src/tools/genpolicy/rules.rego, src/tools/genpolicy/src/policy.rs, src/tools/genpolicy/tests/main.rs, src/tools/genpolicy/tests/testdata/updateinterface/pod.yaml, src/tools/genpolicy/tests/testdata/updateinterface/testcases.json
Introduce rules for UpdateInterfaceRequest and genpolicy tests for them.
goal is to:
- have strong promises about loopback traffic; local traffic has no tls
- prevent loopback traffic from being routed to network devices controlled by the hypervisor
- prevent hypervisor network devices from spoofing loopback
=> genpolicy: Introduce UpdateInterfaceRequest rules in genpolicy-settings

src/runtime/config/configuration-qemu-nvidia-gpu-snp.toml.in, src/runtime/config/configuration-qemu-snp.toml.in, src/runtime/pkg/govmm/qemu/qemu.go, src/runtime/pkg/katautils/config.go, src/runtime/virtcontainers/hypervisor.go, src/runtime/virtcontainers/qemu_amd64.go
For a use case, we want to set the SNP IDBlock, which allows configuring the AMD ASP to enforce parameters like expected launch digest at launch. The struct with the config that should be enforced (IDBlock) is signed. The public key is placed in the auth block and the signature is verified by the ASP before launch. The digest of the public key is also part of the attestation report (ID_KEY_DIGESTS).
=> runtime: make SNP IDBlock configurable

tools/testing/gatekeeper/required-tests.yaml
The SNP CI has been consistently passing and we request the @kata-containers/architecture-committee to mark this test as a required test.
CC: @wainersm @fitzthum @stevenhorsman @ryansavino
=> CI: Mark SNP as a Required test

.github/workflows/build-checks-preview-riscv64.yaml, src/libs/kata-sys-util/src/protection.rs, src/runtime-rs/arch/riscv64gc-options.mk
- kata-sys-util: Set NoProtection for riscv64: `available_guets_protection` is required for `runtime-rs` to infer while building it on riscv64 platforms. Set it to `NoProtection` as riscv64 does not support guest protection for now.
- runtime-rs: Enable RISC-V build: Define `riscv64gc-options.mk` to enable `runtime-rs` to be built on RISC-V platforms.
- ci: Enable runtime-rs component build-check on riscv64: `runtime-rs` is now buildable and testable on riscv64 platforms, enable `build-check` on `runtime-rs`.
=> runtime-rs: Support and enable build on riscv64

.github/cargo-deny-composite-action/cargo-deny-skeleton.yaml.in, .github/workflows/PR-wip-checks.yaml, .github/workflows/build-kata-static-tarball-amd64.yaml, .github/workflows/build-kata-static-tarball-arm64.yaml, .github/workflows/build-kata-static-tarball-ppc64le.yaml, .github/workflows/build-kata-static-tarball-riscv64.yaml, .github/workflows/build-kata-static-tarball-s390x.yaml, .github/workflows/ci-weekly.yaml, .github/workflows/ci.yaml, .github/workflows/commit-message-check.yaml, .github/workflows/payload-after-push.yaml, .github/workflows/publish-kata-deploy-payload.yaml, .github/workflows/release-amd64.yaml, .github/workflows/release-arm64.yaml, .github/workflows/release-ppc64le.yaml, .github/workflows/release-s390x.yaml, .github/workflows/release.yaml, .github/workflows/run-k8s-tests-on-aks.yaml, .github/workflows/run-kata-coco-stability-tests.yaml, .github/workflows/run-kata-coco-tests.yaml, .github/workflows/run-kata-deploy-tests-on-aks.yaml, .github/workflows/shellcheck.yaml, .github/workflows/shellcheck_required.yaml, src/runtime/pkg/govmm/.github/workflows/main.yml
A popular third-party action has recently been compromised [1][2] and the attacker managed to point multiple git version tags to a malicious commit containing code to exfiltrate secrets.
This PR follows GitHub's recommendation [3] to pin third-party actions to a full-length commit hash, to mitigate such attacks.
Hopefully actionlint starts warning about this soon [4].
[1] https://www.cve.org/CVERecord?id=CVE-2025-30066
[2] https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised
[3] https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
[4] https://github.com/rhysd/actionlint/pull/436
=> security: ci: Pin third-party actions to commit hashes

tools/osbuilder/rootfs-builder/ubuntu/rootfs_lib.sh, tools/packaging/static-build/coco-guest-components/Dockerfile
with the latest CoCo guest-components, tdx-attester no longer depends on libtdx attest. Stop installing it to the rootfs.
=> build: drop libtdx-attest

.github/workflows/build-checks.yaml, src/runtime/cmd/kata-runtime/kata-check_arm64_test.go, src/runtime/cmd/kata-runtime/kata-env_arm64_test.go, src/runtime/cmd/kata-runtime/kata-env_test.go
`GITHUB_RUNNER_CI_ARM64` is turned on for self hosted runners without virtualization to skipped those tests depend on virtualization. This may happen to other archs/runners as well, let's generalize it to `GITHUB_RUNNER_CI_NON_VIRT` so we can reuse it on other archs.
=> ci: Generalize `GITHUB_RUNNER_CI_ARM64`

tools/packaging/kata-deploy/scripts/kata-deploy.sh
It hangs when invalid arguments are specified.
```bash
kata-deploy-6sr2p:/# /opt/kata-artifacts/scripts/kata-deploy.sh xxx
Action:
* xxx
...
Usage: /opt/kata-artifacts/scripts/kata-deploy.sh [install/cleanup/reset]
ERROR: invalid arguments
...
^C <- hang
```
I changed it to behave the same as when there are no arguments.
```bash
kata-deploy-6sr2p:/# /opt/kata-artifacts/scripts/kata-deploy.sh
Usage: /opt/kata-artifacts/scripts/kata-deploy.sh [install/cleanup/reset]
ERROR: invalid arguments
kata-deploy-6sr2p:/# echo $?
1
```
Fixes: #11068
=> kata-deploy: return exit code for invalid argument

src/tools/genpolicy/Makefile
Use "cargo build --release" when BUILD_TYPE was not specified, or when BUILD_TYPE=release. The default "cargo build" behavior is to build in debug mode.
=> genpolicy: add support for BUILD_TYPE=debug

src/tools/genpolicy/tests/main.rs, src/tools/genpolicy/tests/testdata/copyfile/testcases.json, src/tools/genpolicy/tests/testdata/createcontainer/generate_name/testcases.json, src/tools/genpolicy/tests/testdata/createcontainer/network_namespace/testcases.json, src/tools/genpolicy/tests/testdata/createcontainer/sysctls/testcases.json, src/tools/genpolicy/tests/testdata/createsandbox/testcases.json, src/tools/genpolicy/tests/testdata/updateinterface/testcases.json, src/tools/genpolicy/tests/testdata/updateroutes/testcases.json
This commit introduces changes to add test data for multiple request type in a single testcases.json file. This allows for stateful testing, for ex: enable testing ExecProcessRequest using policy state set after testing a CreateContainerRequest.
Fixes #11073.
=> genpolicy: Refactor tests to allow different request types in a testcases json.

tests/common.bash
We get the following error while writing containerd config if a base dir `/etc/containerd` does not exist like:
```
sudo tee /etc/containerd/config.toml << EOF
...
EOF
tee: /etc/containerd/config.toml: No such file or directory
```
The PR makes sure a base directory for containerd before writing config and drops the config file deletion because a default behaviour of `tee` is overwriting.
=> tests: Make sure /etc/containerd before writing config

tests/integration/kubernetes/tests_common.sh
Clean-up shellcheck warnings:
note: Prefer [[ ]] over [ ] for tests in Bash/Ksh. [SC2292]
warning: timeout appears unused. Verify use (or export if used externally). [SC2034]
note: Prefer putting braces around variable references even when not strictly required. [SC2250]
note: Prefer double quoting even when variables don't contain special characters. [SC2248]
note: Use -n instead of ! -z. [SC2236]
note: Double quote to prevent globbing and word splitting. [SC2086]
warning: This assignment is only seen by the forked process. [SC2097]
warning: This expansion will not see the mentioned assignment. [SC2098]
warning: AUTO_GENERATE_POLICY is referenced but not assigned. [SC2154]
warning: Declare and assign separately to avoid masking return values. [SC2155]
warning: policy_settings_dir is …
=> tests: k8s: clean-up shellcheck warnings in tests_common.sh

.github/workflows/build-checks-preview-riscv64.yaml, src/runtime/Makefile, src/runtime/arch/riscv64-options.mk, src/runtime/cmd/kata-runtime/kata-check_data_riscv64_test.go, src/runtime/cmd/kata-runtime/kata-check_generic_test.go, src/runtime/cmd/kata-runtime/kata-check_riscv64.go, src/runtime/cmd/kata-runtime/kata-check_riscv64_test.go, src/runtime/cmd/kata-runtime/kata-env_riscv64_test.go, src/runtime/go-test.sh, src/runtime/pkg/govmm/vmm_riscv64.go, src/runtime/virtcontainers/factory/template/template_riscv64.go, src/runtime/virtcontainers/hypervisor_linux_riscv64.go, src/runtime/virtcontainers/qemu_riscv64.go
- runtime: Introduce riscv64 template for vm factory
- runtime: Define availableGuestProtection for riscv64
- runtime: Introduce riscv64 to govmm pkg
- runtime: Define default values for QEMU riscv
- runtime: Enable runtime check for riscv64
- runtime: Enable runtime to build on riscv64
- runtime: Disable race flag for riscv64
- runtime: Enable testSetCPUTypeGeneric for riscv64
- runtime: Add mock data for kata-check
- runtime: Add getExpectedHostDetails for riscv64
- runtime: Enable kata-check test on riscv64
- ci: Enable build-check for runtime on riscv64
Thanks @YutingN from my team for completing the unit tests
=> runtime: Support and enable build on riscv64

tools/packaging/kata-deploy/scripts/kata-deploy.sh
Since kata-deploy.sh references an undefined variable, kata-cleanup.yaml enters a CrashLoopBackOff state.
```
$ kubectl apply -f https://raw.githubusercontent.com/kata-containers/kata-containers/main/tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml
daemonset.apps/kubelet-kata-cleanup created
$ kubectl get pods -n kube-system
kubelet-kata-cleanup-zzbd2        0/1     CrashLoopBackOff   3 (33s ago)     80s
$ kubectl logs -n kube-system daemonsets/kubelet-kata-cleanup
/opt/kata-artifacts/scripts/kata-deploy.sh: line 19: SHIMS: unbound variable
```
Therefore, set an initial value for the environment variables.
Fixes: #11083
=> kata-deploy: Fix kata-cleanup's CrashLoopBackOff

src/agent/src/rpc.rs, tests/integration/kubernetes/confidential_kbs.sh, tests/integration/kubernetes/k8s-sealed-secret.bats
This PR allows all TEEs to run the sealed secret test. In order to make it happen, the followings are made:
- Call `cdh_handler()` for sealed secrets after `add_storage()` in kata agent
- Introduce `kbs_set_default_policy()` and add it to `setup()` in `k8s-sealed-secrets.bats` for CoCo
Please check out each commit message for details.
The tests pass for IBM SE: https://github.com/kata-containers/kata-containers/actions/runs/14075853927/job/39418620980#step:3:18102
Fixes: #11011 
=> tests: Enable sealed secrets for all TEEs

tools/packaging/kata-deploy/scripts/kata-deploy.sh
Currently, ConfigPath in containerd.toml is a double "/" as follows.
```
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-clh.options]
ConfigPath = "/opt/kata/share/defaults/kata-containers//configuration-clh.toml"
...
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata-cloud-hypervisor.options]
ConfigPath = "/opt/kata/share/defaults/kata-containers//runtime-rs/configuration-cloud-hypervisor.toml"
...
```
So, removed the double "/".
Fixes: #11099
=> kata-deploy: remove the double "/"

tools/packaging/kata-deploy/scripts/kata-deploy.sh
INSTALLATION_PREFIX needs to start with a "/"
because it is being concatenated with /host.
If there is no /, it will be added, making it more robust.
Fixes: #11096
=> kata-deploy: add INSTALLATION_PREFIX validation

.github/workflows/ci.yaml
Previously we introduced `build-kata-static-tarball-riscv64.yaml`, enable that workflow in `ci.yaml`.
=> ci: Enable `build-kata-static-tarball-riscv64.yaml`

src/tools/genpolicy/rules.rego, src/tools/genpolicy/tests/main.rs, src/tools/genpolicy/tests/testdata/execprocess/pod.yaml, src/tools/genpolicy/tests/testdata/execprocess/testcases.json
This PR introduces validation for additional input fields in ExecProcessRequest. for hardening the security policy. Here are the enforcements - 
-  `string_user` : Enforced to be null to disallow any root privileges using this field
- `selinuxLabel`: Disallowed for any custom label
- `ApparmorProfile` : Disallowed for any custom profiles
- Update rules.rego to add null/empty field enforcements for String_user, SelinuxLabel and ApparmorProfile
- Introduce unit tests for ExecProcessRequest for each of the validations
- Local testing using `cargo tests`
Fixes #11108
=> policy: Add missing input validations for ExecProcessRequest

src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/PayloadConfig.md, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/PlatformConfig.md, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_payload_config.go, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_platform_config.go, src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml, versions.yaml
Cloud Hypervisor now has experimental `riscv64` architecture
support. Details can be found from the [riscv
documentation](docs/riscv.md).
To improve the readability of CLI options, the output of the `--help`
now is alphabetically sorted. 
The downtime of VM live migration is reduced via delaying some of the
tearing down process of the source VM after the destination VM is up and
running. 
* Fix seccomp filters related to http-api thread
* Handle cross-page access in the emulator for mshv 
This release has been tracked in [v44.0
group](https://github.com/orgs/cloud-hypervisor/projects/6/views/4?filterQuery=release%3A%22Release+v44.0%22)
of our [roadmap project](https://github.com/orgs/cloud-hypervisor/projects/6/).
The `iommu_address_width` option has been added to `--platform` to allow …
=> versions: Upgrade to Cloud Hypervisor v45.0

.github/workflows/ci.yaml
The metrics runner is broken, so skip the metrics
jobs to stop the CI being stuck waiting.
=> ci: Remove metric jobs

src/runtime-rs/Cargo.toml, src/runtime-rs/crates/agent/Cargo.toml, src/runtime-rs/crates/hypervisor/Cargo.toml, src/runtime-rs/crates/hypervisor/ch-config/Cargo.toml, src/runtime-rs/crates/persist/Cargo.toml, src/runtime-rs/crates/resource/Cargo.toml, src/runtime-rs/crates/runtimes/Cargo.toml, src/runtime-rs/crates/runtimes/common/Cargo.toml, src/runtime-rs/crates/runtimes/linux_container/Cargo.toml, src/runtime-rs/crates/runtimes/virt_container/Cargo.toml, src/runtime-rs/crates/runtimes/wasm_container/Cargo.toml, src/runtime-rs/crates/service/Cargo.toml, src/runtime-rs/crates/shim-ctl/Cargo.toml, src/runtime-rs/crates/shim/Cargo.toml, src/runtime-rs/tests/utils/Cargo.toml
- runtime-rs: Extend workspace to cover all crates
- runtime-rs: Group local dependencies
- runtime-rs: Put local dependencies into workspace
=> runtime-rs: Extend runtime-rs workspace and centralize local dependencies

tools/testing/gatekeeper/required-tests.yaml
- Update some truncation typos of job names
- Add shellcheck-required
- Remove the ok-to-test as a required label on the build test as it isn't needed as a trigger
- Make updates to the required-tests file not need the whole CI to run
=> ci: required-tests fixes/updates

tools/testing/gatekeeper/required-tests.yaml
Update the required-tests.yaml so that .md files only trigger the static tests, not the build, or CI tests
=> ci: Update gatekeeper tests for md files

rust-toolchain.toml, versions.yaml
Add a top-level rust-toolchain.toml with the version that matches version.yaml to ensure that we stay in sync
=> rust: Add rust-toolchain.toml

ci/openshift-ci/test.sh
some of the e2e tests spawn a lot of workers which are mainly idle, but the scheduler fails to schedule them due to cpu resource overcommit. For our testing we are more focused on having actual pods running than the speed of the scheduled pods so let's increase the amount of schedulable pods by decreasing the default cpu requests.
=> ci.ocp: Override default runtimeclass CPU resources

tools/osbuilder/rootfs-builder/nvidia/nvidia_rootfs.sh
We need to make sure the device files are created correctly in the rootfs otherwise kata-agent will apply permission 0o000.
=> gpu: Update creation permissions

tools/testing/gatekeeper/required-tests.yaml
The CoCo non-TEE job has failed due the removal of an add-on from AKS, causing KBS to not get installed (see #11156).
The fix should be done in this repo as well as in trustee, which can take some time. We don't want to hold kata-containers PRs from getting merged anylonger, so removing the job from required list.
=> ci: demote CoCo non-TEE to non-required from gatekeeper

src/runtime-rs/crates/resource/src/network/network_info/network_info_from_link.rs, src/runtime-rs/crates/resource/src/network/utils/address.rs, src/runtime-rs/crates/resource/src/network/utils/link/manager.rs
Use `|=` instead of `+=` while iterating through a vector of flags, which makes more sense and prevents situations like duplicated flags in vector would cause problems.
=> runtime-rs: Use bitwise or assign for bitflags

versions.yaml
Every so often the main gnu site has an outage, so we can't download gperf. GNU providesthe generic URL https://ftpmirror.gnu.org to automatically choose a nearby and up-to-date mirror, so switch to this to help avoid this problem
=> versions: Switch gperf mirror

src/runtime/pkg/containerd-shim-v2/create.go, src/runtime/pkg/device/config/config.go, src/runtime/virtcontainers/container.go, src/runtime/virtcontainers/sandbox.go
This is some work to enable cold-plugging until we have the https://github.com/kubernetes/enhancements/pull/4113. 
This enables the provision of a Pod annotation to cold-plug a VFIO device into the VM. 
Fixes: #11125
=> gpu: Fix CDI annotations

tests/integration/kubernetes/tests_common.sh
`genpolicy` is sending more HTTPS requests than other components during CI so it's more likely to be affected by transient network errors similar to:
`ConnectError(
"dns error",
Custom {
kind: Uncategorized,
error: "failed to lookup address information: Try again",
},
)`
Note that `genpolicy` is not the only component hitting network errors during CI. Recent example from a different component:
`"Message:  failed to create containerd task: failed to create shim task:
failed to async pull blob stream HTTP status server error (502 Bad Gateway)"`
This CI change might help work around the `genpolicy` errors but not with the similar errors hit by other CI components.
Fixes: #11182
=> ci: retry genpolicy execution

tests/gha-run-k8s-common.sh
The AKS CLI recently introduced a regression that prevents using aks-preview extensions (Azure/azure-cli#31345), and hence create CI clusters.
To address this, we temporarily hardcode the last known good version of aks-preview.
Note that I removed the comment about this being a Mariner requirement, as aks-preview is also a requirement of AKS App Routing, which will be introduced soon in #11164.
=> temp: ci: Fix AKS cluster creation

tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh, tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh, tools/packaging/static-build/shim-v2/build.sh
Let's add a RUNTIME_CHOICE env var that can be passed to be build scripts, which allows the user to select whether they bulld the go runtime, the rust runtime, or both.
=> build: Allow users to build the go, rust, or both runtimes

src/libs/kata-types/Cargo.toml, src/libs/kata-types/src/config/hypervisor/mod.rs, src/libs/kata-types/src/config/hypervisor/qemu.rs, src/libs/kata-types/src/config/hypervisor/remote.rs, src/libs/kata-types/src/device.rs, src/libs/kata-types/src/handler.rs
The Coniguration initialization was observed to be significantly slow
due to the extensive system information gathering performed by
`sysinfo::System::new_all()`. This function collects data on CPU,
memory, disks, and network, most of which is unnecessary for Kata's
memory adjusting config phase, where only the total system memory is
required.
This commit optimizes the initialization process by implementing a more
targeted approach to retrieve only the total system memory. This avoids
the overhead of collecting a large amount of irrelevant data, resulting
in a noticeable performance improvement.
Fixes #11165
=> kata-types: Optimize memory adjuesting by only gathering memory info

src/runtime/config/configuration-clh.toml.in, src/runtime/pkg/katautils/config-settings.go.in, src/runtime/pkg/katautils/config.go, src/runtime/pkg/oci/utils.go, src/runtime/virtcontainers/clh.go, src/runtime/virtcontainers/hypervisor.go, src/runtime/virtcontainers/pkg/annotations/annotations.go
We're bringing to *Cloud Hypervisor only* the reclaim_guest_freed_memory option already present in the runtime-rs.
This allows us to use virtio-balloon for the hypervisor to reclaim memory freed by the guest.
The reason we're not touching other hypervisors is because we're very much aware of avoiding to clutter the go code at this point, so we'll leave it for whoever really needs this on other hypervisor (and trust me, we really do need it for Cloud Hypervisor right now ;-)).
=> runtime: clh: Add reclaim_guest_freed_memory [BACKPORT]

.github/workflows/darwin-tests.yaml, .github/workflows/docs-url-alive-check.yaml, src/runtime/go.mod, src/tools/csi-kata-directvolume/go.mod, src/tools/log-parser/go.mod, tests/go.mod, tests/integration/cri-containerd/gha-run.sh, tests/metrics/cmd/checkmetrics/go.mod, tools/testing/kata-webhook/go.mod, versions.yaml
Bump golang version to the latest minor 1.23.x release now that 1.24 has been released and 1.22.x is no longer stable and receiving security fixes
=> versions: Bump golang version

tests/integration/kubernetes/confidential_common.sh, tests/integration/kubernetes/confidential_kbs.sh, tests/integration/kubernetes/k8s-confidential-attestation.bats, tests/integration/kubernetes/k8s-guest-pull-image-authenticated.bats, tests/integration/kubernetes/k8s-guest-pull-image-encrypted.bats, tests/integration/kubernetes/k8s-sealed-secret.bats
For help with debugging, add logging of the KBS,
like the container system logs if the confidential test fails
=> tests: confidential: Add KBS logging

.github/workflows/ci-nightly-s390x.yaml
As #11076 introduces VFIO-AP bind/associate funtions for IBM Secure Execution (SEL), a new internal nightly test has been established. 
This PR adds a new entry `cc-vfio-ap-e2e-tests` to the existing matrix to share the test result.
=> GHA: Add VFIO-AP to s390x nightly tests for CoCo

.github/workflows/run-kata-coco-tests.yaml, tests/gha-run-k8s-common.sh, tests/integration/kubernetes/confidential_kbs.sh
The Azure AKS addon-http-application-routing add-on is deprecated and cannot be enabled on new clusters which has caused some CI jobs to fail.
Migrated our code to use approuting instead. Unlike addon-http-application-routing, this add-on doesn't configure a managed cluster DNS zone, but the created ingress has a public IP. To avoid having to deal with DNS setup, we will be using that address from now on. Thus, some functions no longer used are deleted.
Fixes #11156
---
This is how I tested it locally:
```
$ export KBS_INGRESS=aks
$ ./tests/integration/kubernetes/gha-run.sh create-cluster
<output omitted>
$ ./tests/integration/kubernetes/gha-run.sh get-cluster-credentials
<output omitted>
$ …
```
=> tests/k8s: fix kbs installation on Azure AKS

src/tools/genpolicy/genpolicy-settings.json, src/tools/genpolicy/rules.rego, src/tools/genpolicy/src/cronjob.rs, src/tools/genpolicy/src/daemon_set.rs, src/tools/genpolicy/src/deployment.rs, src/tools/genpolicy/src/job.rs, src/tools/genpolicy/src/pod.rs, src/tools/genpolicy/src/policy.rs, src/tools/genpolicy/src/registry.rs, src/tools/genpolicy/src/registry_containerd.rs, src/tools/genpolicy/src/replica_set.rs, src/tools/genpolicy/src/replication_controller.rs, src/tools/genpolicy/src/stateful_set.rs, src/tools/genpolicy/src/yaml.rs, src/tools/genpolicy/tests/main.rs, src/tools/genpolicy/tests/testdata/createcontainer/generate_name/testcases.json, src/tools/genpolicy/tests/testdata/createcontainer/network_namespace/testcases.json, src/tools/genpolicy/tests/testdata/createcontainer/security_context/pod.yaml, src/tools/genpolicy/tests/testdata/createcontainer/security_context/testcases.json, src/tools/genpolicy/tests/testdata/createcontainer/sysctls/testcases.json, src/tools/genpolicy/tests/testdata/state/createcontainer/testcases.json, tests/integration/kubernetes/k8s-policy-deployment-sc.bats, tests/integration/kubernetes/run_kubernetes_tests.sh, tests/integration/kubernetes/runtimeclass_workloads/k8s-layered-sc-deployment.yaml, tests/integration/kubernetes/runtimeclass_workloads/k8s-pod-sc-deployment.yaml, tests/integration/kubernetes/runtimeclass_workloads/k8s-pod-sc-nobodyupdate-deployment.yaml, tests/integration/kubernetes/tests_common.sh
The genpolicy implementation currently misaligns with how containerd handles GIDs/securityContexts. In the container runtime, the actual group ID of the running process is determined by a number of factors in order of priority:
1. The securityContext.runAsGroup specified in the yaml for a given container
2. The securityContext.runAsGroup specified in a pod yaml
3. The UID:GID mapping in /etc/passwd, if present in the container image layers
4. Otherwise it is 0, even if the image_user specifies a GID.
Make our policy engine align with this behavior by:
1. At the registry level, always obtain the GID from the /etc/passwd file if present. Ignore GIDs specified in the image_user field.
2. After an update to UID due to securityContexts, perform another check against the /etc/passwd file if …
=> genpolicy: Align GID behavior with CRI and enable GID policy checks. 

tests/gha-run-k8s-common.sh
This reverts commit 1de466fe848c04a8d3a71465e2318f964c3fb9d2.
The latest release of the az aks extension fixes the issue https://github.com/Azure/azure-cli-extensions/blob/main/src/aks-preview/HISTORY.rst#1400b5
=> ci: revert temp: ci: Fix AKS cluster creation

src/runtime-rs/crates/hypervisor/src/kernel_param.rs, src/runtime/virtcontainers/hypervisor.go, src/runtime/virtcontainers/hypervisor_test.go
"data=ordered" and "errors=remount-ro" are wrong options in xfs.
(they are ext4 options)
<https://manpages.ubuntu.com/manpages/focal/man5/xfs.5.html>
Fixes: #11205
=> runtime: remove wrong xfs options

.github/workflows/build-checks-preview-riscv64.yaml, .github/workflows/build-checks.yaml, .github/workflows/static-checks.yaml, src/runtime-rs/Cargo.lock, src/runtime-rs/Cargo.toml, src/runtime-rs/crates/agent/Cargo.toml, src/runtime-rs/crates/hypervisor/Cargo.toml, src/runtime-rs/crates/hypervisor/ch-config/Cargo.toml, src/runtime-rs/crates/persist/Cargo.toml, src/runtime-rs/crates/resource/Cargo.toml, src/runtime-rs/crates/runtimes/Cargo.toml, src/runtime-rs/crates/runtimes/common/Cargo.toml, src/runtime-rs/crates/runtimes/linux_container/Cargo.toml, src/runtime-rs/crates/runtimes/virt_container/Cargo.toml, src/runtime-rs/crates/runtimes/wasm_container/Cargo.toml, src/runtime-rs/crates/service/Cargo.toml, src/runtime-rs/crates/shim-ctl/Cargo.toml, src/runtime-rs/crates/shim/Cargo.toml, src/runtime-rs/tests/utils/Cargo.toml
Update the runtime-rs workspace packages to
use workspace package versions where applicable
to centralise the config and reduce maintenance
when updating these
=> Runtime rs centralise workspace config

src/dragonball/Cargo.toml, src/dragonball/dbs_boot/Cargo.toml, src/dragonball/dbs_interrupt/Cargo.toml, src/dragonball/dbs_legacy_devices/Cargo.toml, src/dragonball/dbs_pci/Cargo.toml, src/dragonball/dbs_upcall/Cargo.toml, src/dragonball/dbs_virtio_devices/Cargo.toml
Put local dependencies (mostly `dbs` crates) into workspace to avoid complex path dependencies all over the workspace. Simplify path dependency referencing.
=> dragonball: Put local dependencies into workspace

tools/osbuilder/rootfs-builder/nvidia/nvidia_chroot.sh
Kernel Makefiles changed how to deduce the right arch lets set it explicilty to enable arm and amd builds.
=> gpu: Set the ARCH explicilty for driver builds

src/runtime/virtcontainers/qemu_amd64.go, src/runtime/virtcontainers/qemu_arch_base.go
qemu-system-x86_64 does not support "-machine virt". (this is only supported by arm,aarch64)
<https://people.redhat.com/~cohuck/2022/01/05/qemu-machine-types.html>
no virt
```
$ /opt/kata/bin/qemu-system-x86_64 --machine help
Supported machines are:
microvm              microvm (i386)
pc                   Standard PC (i440FX + PIIX, 1996) (alias of pc-i440fx-9.1)
pc-i440fx-9.1        Standard PC (i440FX + PIIX, 1996) (default)
pc-i440fx-9.0        Standard PC (i440FX + PIIX, 1996)
pc-i440fx-8.2        Standard PC (i440FX + PIIX, 1996)
pc-i440fx-8.1        Standard PC (i440FX + PIIX, 1996)
pc-i440fx-8.0        Standard PC (i440FX + PIIX, 1996)
pc-i440fx-7.2        Standard PC (i440FX + PIIX, 1996)
pc-i440fx-7.1        Standard PC (i440FX + PIIX, 1996)
pc-i440fx-7.0        Standard PC …
```
=> runtime: remove wrong qemu-system-x86_64 option

src/runtime-rs/crates/shim/src/logger.rs
It's better to open the log pipe file with read & write option, otherwise, once the containerd reboot and closed the read endpoint, kata shim would write the log pipe with broken pipe error.
Fixes: #11207
=> shimv2: fix the issue logger write failed

src/runtime-rs/Cargo.lock, src/runtime-rs/crates/resource/Cargo.toml, src/runtime-rs/crates/resource/src/network/endpoint/endpoints_test.rs, src/runtime-rs/crates/resource/src/network/network_info/network_info_from_dan.rs, src/runtime-rs/crates/resource/src/network/network_info/network_info_from_link.rs, src/runtime-rs/crates/resource/src/network/network_model/test_network_model.rs, src/runtime-rs/crates/resource/src/network/network_pair.rs, src/runtime-rs/crates/resource/src/network/utils/address.rs, src/runtime-rs/crates/resource/src/network/utils/link/manager.rs
Bump `netlink-sys` to v0.8, `netlink-packet-route` to v0.22 and
`rtnetlink` to v0.16 to reach a consistent state of `rust-netlink`
dependencies in `runtime-rs`
=> runtime-rs: Upgrade `rust-netlink` crates

src/agent/src/netlink.rs, src/libs/protocols/protos/types.proto, src/runtime-rs/crates/agent/src/kata/trans.rs, src/runtime-rs/crates/agent/src/types.rs, src/runtime-rs/crates/resource/src/network/dan.rs, src/runtime-rs/crates/resource/src/network/network_info/network_info_from_dan.rs, src/runtime-rs/crates/resource/src/network/network_info/network_info_from_link.rs, src/runtime/virtcontainers/network.go, src/runtime/virtcontainers/pkg/agent/protocols/types.pb.go
Some cni plugins will set the MTU of some routes, such as cilium will modify the MTU of the default route. If the mtu of the route is not set correctly, it may cause excessive fragmentation or even packet loss of network packets. Therefore, this PR adds the setting of the MTU of the route. First, when obtaining the route, if the MTU is set, the MTU will also be obtained and set to the route in the guest.
Fixes:https://github.com/kata-containers/kata-containers/pull/11135
=> runtime: add the mtu support for updating routes

tools/packaging/kata-debug/kata-debug-build-and-upload-payload.sh
Enabled to run from other scripts as source, etc.
Fixes: #11115
=> kata-debug: Make path resolution more robust

src/runtime/data/kata-collect-data.sh.in
When installing with kata-deploy,  usually `/opt/kata/bin` is not in the PATH.
Therefore, it will fail to execute. so add it to the PATH.
The reason we don't use fixed values is because installation directory is customizable.(INSTALLATION_PREFIX etc)
Fixes: #11122
=> runtime: Add Path for kata-deploy

src/tools/genpolicy/rules.rego, src/tools/genpolicy/tests/main.rs, src/tools/genpolicy/tests/testdata/createcontainer/volumes/emptydir/pod.yaml, src/tools/genpolicy/tests/testdata/createcontainer/volumes/emptydir/testcases.json
This PR is a starting point for extending genpolicy test suite for validating and hardening volume and volumeMounts.
This PR contains
- Update in `rules.rego` file to check for unique mount destinations inside a container
- Adds following test cases:
- A valid container that checks different emptydir volume mount configurations
- An invalid container containing source path not generated by policy 
- An invalid container having duplicate destinations' mount
- An invalid container having options different from what is generated by policy
- An invalid container with invalid fstype
=> genpolicy: improve validation for mounts

docs/README.md, docs/use-cases/CEX-passthrough-and-coco.md, src/agent/Cargo.lock, src/agent/Cargo.toml, src/agent/src/cdh.rs, src/agent/src/device/vfio_device_handler.rs, src/libs/protocols/protos/confidential_data_hub.proto
Kata Containers has support for both the IBM Secure Execution trusted execution environment and the IBM Crypto Express hardware security module (used via the Adjunct Processor bus), but using them together requires specific steps. When using Enterprise PKCS11 with Crypto Express, the adapter domain must be associated with a guest secret. This guest secret must be submitted from within the guest, which induces use of the `s390_pv_core` crate.
The guest secret is to be provisioned based on the master key verification pattern of the adapter domain, via [Trustee](https://github.com/confidential-containers/trustee). In order to make such data available in the guest, [api-server-rest](https://github.com/confidential-containers/guest-components/tree/main/api-server-rest)'s `GetResourceService` …
=> Bind/associate for VFIO-AP

tools/packaging/kata-deploy/scripts/kata-deploy.sh
Once the multiInstallSuffix has been taken into account, we should not keep appending it on every re-run/restart, as that would lead to a path that does not exist.
Fixes: #11187
=> helm: Avoid appending the multiInstallSuffix several times

.github/workflows/release.yaml
Let's take advantage that helm take and OCI registry as the charts, and upload our charts to the OCI registries we've been using so far.
**NOTE**: I'd like to ask someone from the @kata-containers/architecture-committee on what's the best way to try this out before the release, before it gets merged.. :-)
=> helm: release: Publish our helm charts to the OCI registries

tools/osbuilder/rootfs-builder/rootfs.sh, tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in, tools/osbuilder/rootfs-builder/ubuntu/rootfs_lib.sh
Multistrap requires usrmerge package which was dropped in Ubuntu 24.04 (Noble). Based on details from [0], the rootfs build process was switched to mmdebstrap.
Some additional minor tweaks were needed around chrony as the version from Noble has very strict systemd sandboxing configured and it doesn't work with readonly root by default.
[0] https://lists.debian.org/debian-dpkg/2023/05/msg00080.html
Fixes: #11245
=> osbuilder: ubuntu: Switch from multistrap to mmdebstrap

src/dragonball/Cargo.lock, src/runtime-rs/Cargo.lock
update libz-sys crate to remediate CVE-2025-1744
=> Bump: libz-sys crate to address CVE

.github/workflows/build-kata-static-tarball-arm64.yaml, src/runtime/Makefile, src/runtime/arch/arm64-options.mk, tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh, tools/packaging/static-build/ovmf/build-ovmf.sh, tools/packaging/static-build/ovmf/build.sh, versions.yaml
This change enables building edk2 for arm64. The edk2 is required for memory hot plug on qemu for arm64. This is created as a smaller PR for only edk2 for arm64 changes from https://github.com/kata-containers/kata-containers/pull/11019.
=> Enable edk2 for arm64

tests/integration/kubernetes/k8s-memory.bats, tests/integration/kubernetes/k8s-pod-quota.bats
Now that memory hotplug should work, as we're using a firmware that supports that, let's re-enable the tests that rely on hotplug.
Fixes: #10926, #10927, #10928
=> ci: k8s: arm: Enable skipped tests

src/libs/kata-types/src/annotations/mod.rs, src/libs/kata-types/src/config/hypervisor/dragonball.rs, src/libs/kata-types/src/config/hypervisor/mod.rs, src/runtime-rs/config/configuration-qemu-runtime-rs.toml.in, src/runtime-rs/crates/hypervisor/src/device/device_manager.rs, src/runtime-rs/crates/hypervisor/src/device/driver/mod.rs, src/runtime-rs/crates/hypervisor/src/device/driver/port_device.rs, src/runtime-rs/crates/hypervisor/src/device/mod.rs, src/runtime-rs/crates/hypervisor/src/device/topology.rs, src/runtime-rs/crates/hypervisor/src/dragonball/inner_device.rs, src/runtime-rs/crates/hypervisor/src/qemu/cmdline_generator.rs, src/runtime-rs/crates/hypervisor/src/qemu/inner.rs, src/runtime-rs/crates/resource/src/lib.rs, src/runtime-rs/crates/resource/src/manager_inner.rs, src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
To well support vfio devices in PCIe root ports or switch ports in case of qemu-rs, we instroduce port devices containing RootPort and SwitchPort mostly aligned with the implementations of kata-runtime.
=> runtime-rs: Introduce PCIe Port devices in runtime-rs for qemu-rs

tools/testing/gatekeeper/required-tests.yaml
The github rest api truncated job names that are >100 characters (which doesn't seem to be documented).
There doesn't seem to be a way to easily make gatekeeper handle this automatically, so lets update the required-tests to expect the truncated job names
Fixes: #11176
=> ci: gatekeeper: Require names update

src/runtime/arch/amd64-options.mk
Drop '-vmx-rdseed-exit' from '-cpu host' QEMU options. The history of it is unknown but it's likely related to early TDX enablement.
TD pods start up fine without it (tested by manually editing the configuration file) and it's also not used elsewhere.
Keep TDXCPUFEATURES for now in case a need for it shows up later.
=> config: update QEMU TDX configuration

src/tools/genpolicy/genpolicy-settings.json, src/tools/genpolicy/rules.rego, src/tools/genpolicy/src/pod.rs, src/tools/genpolicy/tests/policy/testdata/state/execprocess/testcases.json
Validate more process fields for ExecProcessRequest and add test cases for each of those validations for input fields. These validations also hold true for k8s probe commands - e.g., livenessProbe, readinessProbe, etc.
Cherry-picked from:
- https://github.com/microsoft/kata-containers/commit/167e46577f24b856f6fc6957bcd7724e831adccb
- https://github.com/microsoft/kata-containers/commit/b78982693925f2cffc5a77102463d5307baa73f7
- https://github.com/microsoft/kata-containers/commit/12e16102de39cd7b1ed8d590ca98cc84095159d6
- https://github.com/microsoft/kata-containers/commit/577b154c0d7629a040f5155da5b74f27ae8e3aad
Fixes #11108
=> genpolicy: validate input process fields for ExecProcessRequest

src/runtime-rs/crates/hypervisor/src/qemu/inner.rs, src/runtime-rs/crates/hypervisor/src/qemu/qmp.rs
runtime-rs: Add hotplug block device type with QMP
There's several cases that block device plays very import roles:
1. Direct Volume:
In Kata cases, to achieve high-performance I/O, raw files on the host
are typically passed directly to the Guest via virtio-blk, and then
bond/mounted within the Guest for container usage.
2. Trusted Storage
In CoCo scenarios, particularly in Guest image pull mode, images are
typically pulled directly from the registry within the Guest. However,
due to constrained memory resources (prioritized for containers), CoCo
leverages externally attached encrypted storage to store images,
requiring hot-plug capability for block devices.
and as other vmms, like dragonball and cloud-hypervisor in runtime-rs or
qemu in kata-runtime have already supported such …
=> Support hot-plug block device in qemu-rs with QMP

tests/integration/kubernetes/confidential_kbs.sh
kbs_k8s_svc_host() returns the ingress IP when the KBS service is exposed via an ingress. In Azure AKS the ingress can time a while to be fully ready and recently we have noticed on CI that kbs_k8s_svc_host() has returned empty value. Maybe the problem is on current timeout being too low, so let's increase it to 50 seconds to see if the situation improves.
=> tests/k8s: increase wait time of KBS service ingress

.github/workflows/run-kata-coco-tests.yaml, tests/integration/kubernetes/.gitignore, tests/integration/kubernetes/gha-run.sh, tests/integration/kubernetes/run_kubernetes_tests.sh
This is a spin off of https://github.com/kata-containers/kata-containers/pull/10901 where I removed the mechanism to re-trigger tests, leaving only the improvements for better reporting tests results in CI.
I changed the test runner to send the output of the bats executions to stdout and individual files too; and added a command to gha.sh where a report with a summary and detailed sections is printed. I hope it helps to speed up time to spot a bad test.
=>  tests/k8s: better tests reporting for CI

tests/integration/kubernetes/confidential_kbs.sh
Addressed the following shellcheck advices:
SC2046 (warning): Quote this to prevent word splitting.
SC2248 (style): Prefer double quoting even when variables don't contain special characters
SC2250 (style): Prefer putting braces around variable references even when not strictly required.
SC2292 (style): Prefer [[ ]] over [ ] for tests in Bash/Ksh
Resulting in a free of warning/info/style file.
---
I have fixed some stuffs on that file recently and seeing the shellcheck advices was making me sick, hence this PR that I hope doesn't introduce unintentional bugs (always are a risk).
=> tests/k8s: delint confidential_kbs.sh

tools/testing/gatekeeper/jobs.py
Playing around with gatekeeper might be tedious with all the GH requests, let's add a way to record/provide some files instead.
=> tools.testing: Add methods to simplify gatekeeper development

.github/workflows/gatekeeper.yaml
Restrict the permissions of gatekeeper flow to read contents only for better security
=> workflows: gatekeeper: Update permissions

.github/workflows/build-kata-static-tarball-ppc64le.yaml, .github/workflows/ci-coco-stability.yaml, .github/workflows/ci-devel.yaml, .github/workflows/ci-nightly.yaml, .github/workflows/ci-on-push.yaml, .github/workflows/payload-after-push.yaml, .github/workflows/release.yaml
We have a number of jobs that nest the build-static-tarball workflows later on. Due to these doing attest build provenance, and pushing to ghcr.io, t hey need write permissions on `packages`, `id-token` and `attestations`, so we need to set these permissions on the top-level jobs (along with `contents: read`), so they are not blocked.
=> workflows: Add explicit permissions for attestation

src/agent/Cargo.lock, src/agent/Cargo.toml, src/runtime-rs/Cargo.lock, src/runtime-rs/crates/resource/Cargo.toml, src/tools/runk/Cargo.lock, src/tools/runk/libcontainer/Cargo.toml
We're switching to using a rev as it may take some time for the package to be updated on crates.io.
=> rust: Update cgroups-rs to its v0.3.5 release

src/runtime/pkg/govmm/qemu/qemu.go, tests/integration/kubernetes/k8s-initdata.bats
This patch fixes the initdata support for SNP, and also turn on initdata test for CI.
Fixes #11300
=> Fix | Support initdata for SNP

docs/install/README.md, tools/packaging/kata-deploy/helm-chart/README.md
Since 3.12 we're shipping the helm-chart per default with each release. Update the documentation to use helm rather then the kata-deploy manifests.
=> doc: Add Helm Chart entry

.github/workflows/release-amd64.yaml, .github/workflows/release-arm64.yaml, .github/workflows/release-ppc64le.yaml, .github/workflows/release-s390x.yaml, .github/workflows/release.yaml
workflows: Remove docker hub registry publishing
As docker hub has rate limiting issues, inside mirror
quay.io to ghcr.io instead
=> Switch docker hub mirroring to ghcr.io

.github/workflows/build-kata-static-tarball-amd64.yaml, .github/workflows/build-kata-static-tarball-arm64.yaml, .github/workflows/build-kata-static-tarball-ppc64le.yaml, .github/workflows/build-kata-static-tarball-riscv64.yaml, .github/workflows/build-kata-static-tarball-s390x.yaml, .github/workflows/ci-coco-stability.yaml, .github/workflows/ci-devel.yaml, .github/workflows/ci-nightly.yaml, .github/workflows/ci-on-push.yaml, .github/workflows/ci-weekly.yaml, .github/workflows/ci.yaml, .github/workflows/payload-after-push.yaml, .github/workflows/publish-kata-deploy-payload.yaml, .github/workflows/release-amd64.yaml, .github/workflows/release-arm64.yaml, .github/workflows/release-ppc64le.yaml, .github/workflows/release-s390x.yaml, .github/workflows/release.yaml, .github/workflows/run-k8s-tests-on-aks.yaml, .github/workflows/run-k8s-tests-on-zvsi.yaml, .github/workflows/run-kata-coco-stability-tests.yaml, .github/workflows/run-kata-coco-tests.yaml, .github/workflows/run-kata-deploy-tests-on-aks.yaml
Having secrets unconditionally being inherited is
bad practice, so update the workflows to only pass through the minimal secrets that are needed
=> workflows: Replace secrets: inherit

src/dragonball/dbs_virtio_devices/src/vhost/vhost_user/connection.rs
The vhost-user-fs has been added to Dragonball, so we can remove
`update_memory`'s dead_code attribute.
Fixes: #8691
=> dragonball: Remove a useless dead_code attribute

src/runtime-rs/crates/resource/src/share_fs/sandbox_bind_mounts.rs
Log on error condition when `umount` operation fail instead of `format!` error message.
=> runtime-rs: Log error instead of format

tools/osbuilder/rootfs-builder/cbl-mariner/Dockerfile.in
This implements a workaround for microsoft/azurelinux#13971 to unblock the CI.
=> ci: Fix Mariner rootfs build failure

src/runtime-rs/crates/agent/src/kata/mod.rs, src/runtime-rs/crates/agent/src/log_forwarder.rs, src/runtime-rs/crates/agent/src/sock/hybrid_vsock.rs, src/runtime-rs/crates/agent/src/sock/mod.rs, src/runtime-rs/crates/agent/src/sock/remote.rs, src/runtime-rs/crates/agent/src/sock/vsock.rs
When connecting to guest through vsock, a log is printed for each failure.
The failure comes from two main reasons: (1) the guest is not ready or (2)
some real errors happen. Printing logs for the first case leads to log
clutter, and your logs will like this:
```
Feb 07 02:47:24 ubuntu containerd[520]: {"msg":"connect uds \"/run/kata/...
Feb 07 02:47:24 ubuntu containerd[520]: {"msg":"connect uds \"/run/kata/...
Feb 07 02:47:24 ubuntu containerd[520]: {"msg":"connect uds \"/run/kata/...
Feb 07 02:47:24 ubuntu containerd[520]: {"msg":"connect uds \"/run/kata/...
Feb 07 02:47:24 ubuntu containerd[520]: {"msg":"connect uds \"/run/kata/...
```
To avoid this, the sock implmentations save the last error and return it
after all retries are exhausted. Users are able to check all errors by
setting …
=> runtime-rs: Reduce the number of duplicate log entries being printed

src/runtime-rs/Makefile
Full set test on RISC-V architecture is not yet supported, skip it for now.
=> runtime-rs: Skip test on RISC-V architecture

tools/osbuilder/rootfs-builder/cbl-mariner/Dockerfile.in
This reverts commit dfa25a42ff956190387ae04764d1811d6f906d4d.
The original issue was fixed:
https://github.com/microsoft/azurelinux/issues/13971#issuecomment-2956384627
=> Revert "ci: Fix Mariner rootfs build failure"

src/libs/protocols/src/lib.rs, src/libs/protocols/src/trans.rs
We always encount such noising warnings which makes us not happy. I think it's time to wipe it out
```
-            decoded.strip_prefix("CAP_").unwrap_or(decoded)
+            decoded
+                .strip_prefix("CAP_")
+                .unwrap_or(decoded)
.parse::<oci::Capability>()
.unwrap_or_else(|_| panic!("Failed to parse {:?} to
Enum Capability", cap))
})
@@ -1318,8 +1320,6 @@ mod tests {
#[test]
#[should_panic]
fn test_cap_vec2hashset_bad() {
-        cap_vec2hashset(vec![
-            "CAP_DOES_NOT_EXIST".to_string(),
-        ]);
+        cap_vec2hashset(vec!["CAP_DOES_NOT_EXIST".to_string()]);
```
=> protocols: Fix the noise caused by non-formatted codes in protocols

src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
- Support cold plug of block devices via virtio-blk for Qemu
- Enables block device and disable virtio-fs via capabilities
Fixes #11341
=> Enables block device and disable virtio-fs

tools/osbuilder/rootfs-builder/nvidia/nvidia_rootfs.sh
In the nvidia rootfs build, only copy in `kata-opa` if `AGENT_POLICY` is enabled. This fixes builds when `AGENT_POLICY` is disabled and opa is not built.
=> nvidia-rootfs: only copy `kata-opa` if `AGENT_POLICY` is enabled

src/tools/runk/Cargo.lock, src/tools/runk/Cargo.toml
The users@0.11.0 has a high severity CVE-2025-5791 and doesn't seem to be maintained, so switch to
uzers which forked it.
=> runk: Switch users crate

src/agent/src/cdh.rs
This method is not used when guest-pull is not used. Add a flag that prevents a compile error when building with rust version > 1.84.0 and not using guest-pull.
Related to https://github.com/kata-containers/kata-containers/pull/10934
=> agent: add feature flag to secure_mount method

src/runtime/virtcontainers/clh.go
Fixes a confusing log message shown when Virtio-FS is disabled.
Currently, we log “The virtiofsd had stopped” regardless of whether Virtio-FS was actually enabled or not.
=> Fix logging on virtiofs shutdown

src/libs/kata-types/src/mount.rs, src/runtime-rs/crates/resource/src/manager.rs, src/runtime-rs/crates/resource/src/manager_inner.rs, src/runtime-rs/crates/resource/src/rootfs/mod.rs, src/runtime-rs/crates/resource/src/rootfs/virtual_volume.rs, src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs
runtime-rs: Support Pull Image in Guest with Kata Volume for CoCo
In CoCo scenarios, there's no image pulling on host side, and it will
disable such operations, that's to say, there's no files sharing between
host and guest, especially for container rootfs.
As It's designed and implemented in runtime-go, we just follow related
docs Kata Containers Guest Image Management Design and Kata Containers
with Guest Image Management.
Fixes #10690
=> runtime-rs: Support Pull Image in Guest with Kata Volume for CoCo

tools/packaging/kata-deploy/scripts/kata-deploy.sh
the latest Canonical TDX release supports 25.04 / Plucky as well. Users experimenting with the latest goodies in the 25.04 TDX enablement won't get Kata deployed properly.
This change accepts 25.04 as supported distro for TDX.
=> kata-deploy: accept 25.04 as supported distro for TDX

tools/osbuilder/rootfs-builder/ubuntu/config.sh, versions.yaml
Since #11197 was merged, all confidential k8s e2e tests for s390x have been failing with the following errors:
```
attestation-agent: error while loading shared libraries:
libcurl.so.4: cannot open shared object file
libnghttp2.so.14: cannot open shared object file
```
In line with the update on x86_64, we need to upgrade the OS used in rootfs-{image,initrd} on s390x.
This PR also bumps all 22.04 to 24.04 for all architectures.
For s390x, this ensures the  missing packages listed above are installed.
=> rootfs: Bump rootfs-{image,initrd} to 24.04

.github/workflows/govulncheck.yaml, .github/workflows/static-checks.yaml, tests/govulncheck-runner.sh
This adds [govulncheck](https://pkg.go.dev/golang.org/x/vuln@v1.1.4/cmd/govulncheck) (binary mode) vulnerability scanning as a non-blocking check in the static checks workflow. 
Govulncheck is Go's official security scanner that detects known vulnerabilities in Go binaries by analyzing their compiled code and matching against the Go vulnerability database. Unlike source-based scanners, binary mode scanning ensures we only detect vulnerabilities that are present in the final compiled binaries.
The check scans all runtime Go binaries (kata-runtime, containerd-shim-kata-v2, kata-monitor) for security vulnerabilities while filtering out verified false positives in golvuncheck (for details, see limitation section in https://pkg.go.dev/golang.org/x/vuln@v1.1.4/cmd/govulncheck). 
This should …
=> ci: Add optional govulncheck security scanning to static checks

.github/workflows/darwin-tests.yaml, .github/workflows/docs-url-alive-check.yaml, versions.yaml
Bump golang to fix CVEs GO-2025-3751
and GO-2025-3563
=> versions: Bump golang to 1.23.10

.github/workflows/ci.yaml
At the moment if any of the tests in the matric fails then the rest of the jobs are cancelled, so we have to re-run everything. Add `fail-fast: false` to stop this behaviour.
=> workflows: Add fail-fast: false to cri-containerd tests

.github/workflows/release.yaml
Add more permissions to the release workflow
in order to enable `gh release` commands to run
=> workflows: Release permissions

.github/workflows/release.yaml
In theory `github.actor` could be used for code injection, so swap it out.
=> workflow: Remove code injection in helm login

src/tools/genpolicy/src/layers_cache.rs, src/tools/genpolicy/src/lib.rs, src/tools/genpolicy/src/main.rs, src/tools/genpolicy/src/registry.rs, src/tools/genpolicy/src/registry_containerd.rs, src/tools/genpolicy/src/utils.rs, src/tools/genpolicy/tests/policy/main.rs
We have been experiencing sporadic corruption of the layer cache file. Applying `genpolicy --use-cached-files` to this `deployment.yaml` and initial state of the layer cache `layers-cache.json`:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
name: whatever
spec:
template:
spec:
runtimeClassName: contrast-cc
containers:
- name: secret-service
image: 'ghcr.io/edgelesssys/privatemode/secret-service:v1.17.0@sha256:e36c9f13932f46e2fd460c5469dd4ee22bcdbaefd4b576d985f9e9a435413d3b'
```
```json
[
{
"diff_id": "sha256:fa6a52ec54152fea01d1e53fa5b2447fcc2004d56414f23830fe4536b8b3f823",
"verity_hash": "e25c3d85b5ef4fb029b338b0eef3c4d5f29ffabb7d0aa27a2a8130e06fdd8190",
"passwd": "root:x:0:0:root:/root:/bin/ash\nbin:x:1:1:bin:/bin:/sbin/nologin\ndaemon:x:2:2:daemon:/sbin:/sbin/nologin\nadm:x:3:4 …
```
=> genpolicy: prevent corruption of the layer cache file

src/runtime-rs/crates/resource/src/rootfs/block_rootfs.rs, src/runtime-rs/crates/resource/src/rootfs/mod.rs
For containerd's Blockfile Snapshotter, it will pass a rootfs mounts with a rawfile as a mount source
and mount options with "loop" embeded.
To support this type of rootfs, it is necessary to identify this as a blockfile rootfs through the "loop" flag, and then use the volume source of the rootfs as the source of the block device to hot-insert it into the guest.
Fixes:https://github.com/kata-containers/kata-containers/issues/11464
=> runtime-rs: add the blockfile based rootfs support

src/runtime-rs/crates/resource/src/rootfs/block_rootfs.rs
In the pre commit:74eccc54e7b31cc4c9abd8b6e4007c3a4c1d4dd4, it missed return the right rootfs volume.
In the is_block_rootfs fn, if the rootfs is based on a block device such as devicemapper, it should clear the volume's source and let the device_manager to use the dev_id to get the device's host path.
=> runtime-rs: fix the issue return the wrong volume

src/runtime-rs/crates/hypervisor/src/qemu/inner.rs
This commit introduces the ability to run Pods without shared fs mechanism in Kata.
The default shared fs can lead to unnecessary resource consumption and security risks for certain use cases. Specifically, scenarios where files only need to be copied into the VM once at Pod creation (e.g., non-tee envs) and don't require dynamic updates make the shared fs redundant and inefficient.
By explicitly disabling shared fs functionality, we reduce resource overhead and shrink the attack surface. Users will need to employ alternative methods(e.g. guest-pull) to ensure container images are shared into the guest VM for these specific scenarios.
=> runtime-rs: Support shared fs with "none" on non-tee platforms

src/runtime-rs/crates/hypervisor/ch-config/src/ch_api.rs, src/runtime-rs/crates/hypervisor/ch-config/src/lib.rs, src/runtime-rs/crates/hypervisor/ch-config/src/net_util.rs, src/runtime-rs/crates/hypervisor/src/ch/inner.rs, src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs, src/runtime-rs/crates/hypervisor/src/ch/mod.rs, src/runtime-rs/crates/hypervisor/src/qemu/inner.rs, src/runtime-rs/crates/hypervisor/src/utils.rs
Add the memory and vcpu hotplug for the cloud-hypervisor.
For cloud-hypervisor, currently only hot plugging of memory is
supported, but hot unplugging of memory is not supported. In addition,
by default, cloud-hypervisor uses ACPI-based memory hot-plugging instead
of virtio-mem based memory hot-plugging.
For vcpu, it can support both of hotplug and hot unplug.
=>  runtime-rs: Add the memory and vcpu hotplug for cloud-hypervisor

.github/workflows/zizmor.yaml
This runs the zizmor security lint [1] on our GH Actions.
The initial workflow uses [2] as a base.
[1] https://docs.zizmor.sh/
[2] https://docs.zizmor.sh/usage/#use-in-github-actions
=> ci: Run zizmor for GHA security analysis

src/libs/kata-types/src/annotations/mod.rs, src/libs/kata-types/src/config/hypervisor/mod.rs, src/runtime-rs/config/configuration-remote.toml.in, src/runtime-rs/crates/hypervisor/src/remote/inner.rs
We're introducing `default_gpus` and `default_gpu_model` as GPU annotations for kata VM configurations to improve instance selection on remote hypervisors.
By adding these annotations:
- default_gpus: Allows us to specify the minimum number of GPUs a VM requires. This ensures that the remote hypervisor selects an instance with at least that many GPUs, preventing resource under-provisioning.
- default_gpu_model: Lets us define the specific GPU model needed for the VM. This is crucial for workloads that depend on particular GPU architectures or features, ensuring compatibility and optimal performance.
Essentially, these new fields provide the remote hypervisor with the necessary intelligence to select the most appropriate instance for a given GPU VM.
Signed-off-by: alex.lyn …
=> runtime-rs: Add GPU annotations for remote hypervisor

versions.yaml
Bump to version v0.15.2 to pick up fix to mount source in https://github.com/containerd/nydus-snapshotter/pull/636
=> version: Bump nydus-snapshotter

src/tools/genpolicy/.gitignore, src/tools/genpolicy/genpolicy-settings.json, src/tools/genpolicy/rules.rego, src/tools/genpolicy/src/mount_and_storage.rs, src/tools/genpolicy/src/policy.rs, src/tools/genpolicy/src/yaml.rs, src/tools/genpolicy/tests/policy/main.rs, src/tools/genpolicy/tests/policy/testdata/createcontainer/volumes/config_map/config_map.yaml, src/tools/genpolicy/tests/policy/testdata/createcontainer/volumes/config_map/pod.yaml, src/tools/genpolicy/tests/policy/testdata/createcontainer/volumes/config_map/testcases.json, src/tools/genpolicy/tests/policy/testdata/createcontainer/volumes/container_image/pod.yaml, src/tools/genpolicy/tests/policy/testdata/createcontainer/volumes/container_image/testcases.json, src/tools/genpolicy/tests/policy/testdata/createcontainer/volumes/emptydir/testcases.json, src/tools/genpolicy/tests/policy/testdata/state/execprocess/testcases.json, tests/integration/kubernetes/tests_common.sh
**Description**
This PR adds validation for storages in the genpolicy tool.
Test cases are added for: config map, and container images containing volumes
Test cases are improved for: empty_dir
=> genpolicy: add validation for storages

src/dragonball/src/api/v1/vmm_action.rs, src/dragonball/src/device_manager/vfio_dev_mgr/mod.rs, src/dragonball/src/vcpu/vcpu_manager.rs, src/dragonball/src/vm/mod.rs, src/runtime-rs/crates/hypervisor/src/dragonball/inner.rs, src/runtime-rs/crates/hypervisor/src/dragonball/vmm_instance.rs
This PR contains two patch:
This PR mainly consists of two parts, one is to add support for resize_vcpu synchronization capabilities to dragonball; the other is to support the synchronization capabilities of calling dragonball's resize_vcpu interface on runtime-rs.
When hot plugging vcpu in dragonball hypervisor, use the synchronization
interface and wait until the hot plug cpu is executed in the guest
before returning. This ensures that the subsequent device hot plug will
not conflict with the previous call.
=> runtime-rs: make the resize_vcpu api support sync

src/libs/kata-types/src/mount.rs, src/runtime-rs/crates/resource/src/rootfs/virtual_volume.rs
When we do force guest pull with the setting in configuration.toml:
```
...
disable_guest_empty_dir=false
experimental=["force_guest_pull"] # add experimental feature here
...
```
(1) Refactor its implementation by adding public constant values; 
(2) Fix force guest pull implementation
- add default value for source to pass the validation.
- Initialize image_pull with Some(xxx) to prevent skipping when serializing.
=> runtime-rs:  refactor and fix the implementation of guest-pull

tools/osbuilder/rootfs-builder/nvidia/nvidia_rootfs.sh
We had the proper config.toml configuration for static builds but were building the glibc  target and not the musl target.
=> gpu: NVRC static build

.github/dependabot.yml, src/dragonball/Cargo.lock, src/libs/Cargo.lock, src/libs/logging/Cargo.toml, src/mem-agent/example/Cargo.lock, src/mem-agent/example/Cargo.toml, src/mem-agent/example/ctl.rs, src/mem-agent/example/share/option.rs, src/mem-agent/example/srv.rs, src/runtime-rs/Cargo.lock, src/tools/agent-ctl/Cargo.lock, src/tools/kata-ctl/Cargo.lock, src/tools/trace-forwarder/Cargo.lock
Update dependencies to remove the unmaintained `atty` crate being used which has a security advisory GHSA-g98v-hv3f-hcfr
=> Remove atty dependency

tools/packaging/kata-deploy/runtimeclasses/kata-qemu-nvidia-gpu-snp.yaml, tools/packaging/kata-deploy/runtimeclasses/kata-qemu-nvidia-gpu-tdx.yaml, tools/packaging/kata-deploy/runtimeclasses/kata-qemu-nvidia-gpu.yaml
We cannot only rely only on default_cpu and default_memory in the config, default is 1 and 2Gi but we need some overhead for QEMU and the other related binaries running as the pod overhead. Especially when QEMU is hot-plugging GPUs, CPUs, and memory it can consume more memory.
=> gpu: Update runtimeClasses for correct podoverhead

tools/packaging/kata-deploy/runtimeclasses/kata-runtimeClasses.yaml
679cc9d47c55dc77fc1e0a00cab370de1122eafc was merged and bumped the podoverhead for the gpu related runtimeclasses. However, the bump on the `kata-runtimeClasses.yaml` as overlooked, making our tests fail due to that discrepancy.
Let's just adjust the values here and move on.
=> tests: runtimeclasses: Adjust gpu runtimeclasses

.github/workflows/run-k8s-tests-on-amd64.yaml, tests/functional/kata-deploy/kata-deploy.bats, tests/gha-run-k8s-common.sh, versions.yaml
We've been pinning a specific version of k0s for CRI-O tests, which may make sense for CRI-O, but doesn't make sense at all when it comes to testing that we can install kata-deploy on latest k0s (and currently our test for that is broken).
Let's bump to the latest, and from this point we start debugging, instead of debugging on an ancient version of the project.
=> tests: k0s: Always use latest version, apart from CRI-O tests

src/runtime-rs/Cargo.lock, src/runtime-rs/crates/hypervisor/Cargo.toml, src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs
tempdir hasn't been updated for seven years and pulls in remove_dir_all@0.5.3 which has security advisory
GHSA-mc8h-8q98-g5hr, so replace this with using tempfile, which the crate got merged into and we use elsewhere in the project
=> runtime-rs: Switch tempdir to tempfile

.github/workflows/build-kata-static-tarball-amd64.yaml, .github/workflows/build-kata-static-tarball-arm64.yaml, .github/workflows/build-kata-static-tarball-ppc64le.yaml, .github/workflows/build-kata-static-tarball-s390x.yaml
The `/opt/kata/VERSION` file, which is created using `git describe --tags`, requires the newly released tag to be updated in order to be accurate.
To do so, let's add a `fetch-tags: true` to the checkout action used during the `create-kata-tarball` job.
=> gh: Fix released VERSION file

src/runtime-rs/Makefile, src/runtime-rs/config/configuration-cloud-hypervisor.toml.in, src/runtime-rs/config/configuration-dragonball.toml.in, src/runtime-rs/config/configuration-qemu-runtime-rs.toml.in, src/runtime-rs/config/configuration-qemu-se-runtime-rs.toml.in, src/runtime-rs/config/configuration-rs-fc.toml.in
runtime-rs: Change block device driver defualt with virtio-blk-* and update docs
When we run a kata pod with runtime-rs/qemu and with a default configuration toml,
it will fail with error "unsupported driver type virtio-scsi". 
As virtio-scsi within runtime-rs is not so popular, we set default block device driver with `virtio-blk-*`.
And as the previous description for the `block_device_driver` was inaccurate or
outdated. To make it clear for users, This PR also updates the documentation to
provide a more precise explanation of its function.
Fixes #11488
=> runtime-rs: Change default block device driver from virtio-scsi to virtio-blk-*

src/runtime-rs/Cargo.lock, src/tools/trace-forwarder/Cargo.lock
Bump chrono version to drop time@0.1.45 and remediate vulnerability CVE-2020-26235
=> runtime-rs | trace-forwarder: Bump chrono crate version

src/agent/Cargo.lock, src/agent/Cargo.toml, src/libs/kata-sys-util/Cargo.toml, src/libs/kata-types/Cargo.toml, src/libs/protocols/Cargo.toml, src/runtime-rs/Cargo.lock, src/runtime-rs/Cargo.toml, src/tools/agent-ctl/Cargo.toml, src/tools/genpolicy/Cargo.toml, src/tools/runk/Cargo.toml, src/tools/runk/libcontainer/Cargo.toml
Bumps of tracing components, oci-spec and cdi to see if they are still stable and fix various security advisories
=> Rust advisory fixes pre 3.19.0

.github/workflows/build-kata-static-tarball-amd64.yaml, .github/workflows/build-kata-static-tarball-arm64.yaml, tools/packaging/kata-deploy/local-build/Makefile, tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
The files cached follow the convention of rootfs-nvidia-gpu-initrd-*, while we were checking for rootfs-initrd-nvidia-gpu-*, leading to trying to check the current values with a non-existent cache file and, consequently, doing a new build every single time.
Although not used yet, we're also fixing the same logic for images.
=> build: Fix cache for nvidia-gpu-initrd builds

src/agent/rustjail/src/container.rs, src/agent/rustjail/src/process.rs, src/agent/src/rpc.rs
Sometimes, containers or execs do not use stdin, so there is no chance to add parent stdin to the process's writer hashmap, resulting in the parent stdin's fd not being closed when the process is cleaned up later.
Therefore, when creating a process, first explicitly add parent stdin to the wirter hashmap. Make sure that the parent stdin's fd can be closed when the process is cleaned up later.
Fixes: #11503
=> agent: fix the issue of parent writer pipe fd leak

versions.yaml
This new version of gc fixes s390x attestation, also introduces registry configuration setting directly via initdata.
cc @Apokleos @BbolroC
=> deps(chore): bump guest-components to candidate v0.14.0

src/runtime/pkg/README.md, tests/integration/kubernetes/gha-run.sh, tests/integration/kubernetes/k8s-cpu-ns.bats, tools/packaging/kata-deploy/helm-chart/README.md, tools/packaging/kata-deploy/helm-chart/kata-deploy/templates/kata-deploy.yaml, tools/packaging/kata-deploy/helm-chart/kata-deploy/values.yaml
Solves issue https://github.com/kata-containers/kata-containers/issues/11518
- Add nodeSelector configuration to values.yaml with empty default
- Update DaemonSet template to conditionally include nodeSelector
- Add documentation and examples for nodeSelector usage in README
- Allows users to restrict kata-containers deployment to specific nodes by labeling them
=> helm: add nodeSelector support to kata-deploy chart

.github/workflows/build-kata-static-tarball-amd64.yaml, .github/workflows/build-kata-static-tarball-arm64.yaml, .github/workflows/build-kata-static-tarball-ppc64le.yaml, .github/workflows/build-kata-static-tarball-s390x.yaml, tools/packaging/kata-deploy/local-build/kata-deploy-merge-builds.sh
For the release itself, let's use the release version in the VERSION file.
To do so, we had to change the logic that merges the build, as at that point the tag is not yet pushed to the repo.
=> release: Copy the VERSION file to the tarball

src/runtime/virtcontainers/clh.go, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/api/openapi.yaml, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/DefaultApi.md, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/DiskConfig.md, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/docs/NetConfig.md, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_disk_config.go, src/runtime/virtcontainers/pkg/cloud-hypervisor/client/model_net_config.go, src/runtime/virtcontainers/pkg/cloud-hypervisor/cloud-hypervisor.yaml, versions.yaml
Instead of exiting on I/O errors, the `virtio-block` device now reports
errors to the guest using `VIRTIO_BLK_S_IOERR`. It improves the user
experience particularly when the guest rootfs is not backed by the
affected block device.
We now have the chain of errors being reported and printed nicely, when
Cloud Hypervisor or ch-remote exits on errors.
To improve readability, ch-remote now prints help information in
alphabetical order.
* Error out early when block device serial is too long
* Fix partial commands being discarded for `virtio-vsock`
* Disable the broken interrupt support for the `rtc_pl031` device to
prevent spurious guest interrupts
* A default IP (`192.168.249.1`) and mask (`255.255.255.0`) are
currently assigned  to the `virtio-net` device if no value is specified
by users. …
=> versions: Upgrade to Cloud Hypervisor v47.0

src/dragonball/dbs_utils/src/net/mac.rs, src/dragonball/dbs_virtio_devices/src/vsock/mod.rs, src/dragonball/src/api/v1/vmm_action.rs, src/dragonball/src/device_manager/mod.rs
We always compile dragonball with `make` command, which enables `all-features` by default in our makefile. This leave some warning in default `cargo build` unnoticed.
=> dragonball: Fix warnings in default build

.github/workflows/basic-ci-amd64.yaml, .github/workflows/basic-ci-s390x.yaml, .github/workflows/run-cri-containerd-tests.yaml, .github/workflows/run-kata-monitor-tests.yaml, .github/workflows/run-runk-tests.yaml, tests/common.bash
Our CI keeps on getting
```
jq: error (at <stdin>:1): Cannot index string with string "tag_name"
```
during the install dependencies phase, which I suspect might be due to github rate limits being reduced, so try to pass through the `GH_TOKEN` env and use it in the auth header.
=> ci: Try passing api token into githubh api call

tools/testing/gatekeeper/required-tests.yaml
The CoCo non-TEE job (run-k8s-tests-coco-nontee) used to be required but we had to withdraw it to fix a problem (#11156). Now the job is back running and stable, so time to make it required again.
=> ci/gatekeeper: make run-k8s-tests-coco-nontee job required

versions.yaml
This PR updates the Firecracker version bundled with Kata Containers from **v1.8.0** to the latest stable **v1.12.1**.
---
-  Updated `versions.yaml` to point to Firecracker **v1.12.1**
---
```bash
/opt/kata/bin/firecracker --version
Firecracker v1.12.1
/opt/kata/bin/jailer --version
jailer v1.12.1
````
* Deployed **5 pods** using `kata-fc` runtime class and `gitpod/openvscode-server:latest` container.
* All pods launched successfully and were in `Running` state.
* Verified container access, resource allocation, and proper Firecracker usage.
```bash
kubectl get pods
kubectl exec -it vscode-kata-1 -- uname -a
ps aux | grep firecracker
```
* RuntimeClass: `kata-fc`
* Container image: `gitpod/openvscode-server:latest`
* Memory limit: `1Gi`, CPU: `1`
* Kernel: `Linux 6.12.36` inside microVM
* …
=> Updated Firecracker Version to 1.12.1

src/runtime/pkg/govmm/qemu/qmp.go, src/runtime/pkg/govmm/qemu/qmp_test.go, src/runtime/virtcontainers/qemu.go
When hot-plugging CPUs on QEMU, we send a QMP command with JSON arguments. QEMU 9.2 recently became more strict[1] enforcing the JSON schema for QMP parameters. As a result, running Kata Containers with QEMU 9.2 results in a message complaining that the core-id parameter is expected to be an integer:
```
qmp hotplug cpu, cpuID=cpu-0 socketID=1, error:
QMP command failed:
Invalid parameter type for 'core-id', expected: integer
```
Fix that by changing the core-id, socket-id and thread-id to be integer values.
[1]: https://github.com/qemu/qemu/commit/be93fd53723cbdca675bd9ed112dae5cabbe1e91
Fixes: #11633
=> qemu: Respect the JSON schema for hot plug

src/runtime/config/configuration-clh.toml.in, src/runtime/config/configuration-qemu-coco-dev.toml.in, src/runtime/config/configuration-qemu-nvidia-gpu-snp.toml.in, src/runtime/config/configuration-qemu-nvidia-gpu-tdx.toml.in, src/runtime/config/configuration-qemu-nvidia-gpu.toml.in, src/runtime/config/configuration-qemu-se.toml.in, src/runtime/config/configuration-qemu-snp.toml.in, src/runtime/config/configuration-qemu-tdx.toml.in, src/runtime/config/configuration-qemu.toml.in, src/runtime/config/configuration-stratovirt.toml.in, src/runtime/virtcontainers/kata_agent.go, src/runtime/virtcontainers/virtiofsd.go, src/runtime/virtcontainers/virtiofsd_test.go
The Rust virtiofsd supports a "metadata" cache mode [1] that wasn't present in the C version [2], so this PR adds support for that.
[1] https://gitlab.com/virtio-fs/virtiofsd
[2] https://qemu.weilnetz.de/doc/5.1/tools/virtiofsd.html#cmdoption-virtiofsd-cache
=> runtime: virtio-fs: Support "metadata" cache mode

tests/integration/cri-containerd/integration-tests.sh
After moving Arm64 CI nodes to new `not powerful` one, we do faced an interesting issue for timeout when it executes the command with `crictl runp`,  the error is usally: code = DeadlineExceeded 
Closes: #11662
=> ci: cri-containerd: add 5s timeout for creating sanbox with crictl

src/agent/Cargo.lock, src/libs/logging/Cargo.toml, src/libs/logging/src/lib.rs, src/runtime-rs/Cargo.lock, src/runtime-rs/crates/shim/src/logger.rs
Route kata-shim logs directly to systemd-journald under 'kata' identifier
This refactoring enables `kata-shim` logs to be properly attributed to 'kata' in systemd-journald, instead of inheriting the 'containerd' identifier.
Previously, `kata-shim` logs were challenging to filter and debug as they appeared under the `containerd.service` unit.
This commit resolves this by:
1.  Introducing a `LogDestination` enum to explicitly define logging targets (File or Journal).
2.  Modifying logger creation to set `SYSLOG_IDENTIFIER=kata` when logging to Journald.
3.  Ensuring type safety and correct ownership handling for different logging backends.
This significantly enhances the observability and debuggability of Kata Containers, making it easier to monitor and troubleshoot Kata-specific events. …
=> runtime-rs: Label system journal log with kata

src/libs/kata-types/src/config/hypervisor/mod.rs, src/runtime-rs/crates/hypervisor/src/qemu/cmdline_generator.rs
This commit support the seccomp_sandbox option from the configuration.toml file and add the logic for appending command-line arguments based on this new configuration parameter.
Fixes: #11524
=> runtime-rs: add seccomp support for qemu

tests/common.bash
This would cause weird issues for downstreams which default branch is not "main".
Tested downstream here: https://github.com/microsoft/kata-containers/actions/runs/16950865795/job/48043166346?pr=403
=> ci: static-checks: Don't hardcode default repo branch

src/runtime/go.mod, src/tools/csi-kata-directvolume/go.mod, tools/testing/kata-webhook/go.mod, versions.yaml
OSV-Scanner highlights go.mod references to go stdlib 1.23.0 contrary to intention in versions.yaml, so synchronize them.
Fixes: #11700
=> versions: sync go.mod with versions.yaml for go 1.23.12

src/libs/kata-types/src/config/hypervisor/mod.rs
To make it aligned with the setting of runtime-go, we should keep it as empty when users doesn't enable and set its specified path.
=> kata-types: remove default setting of guest_hook_path

src/libs/kata-types/src/initdata.rs, src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs, tests/integration/kubernetes/k8s-initdata.bats
This PR enables initdata for IBM SEL (s390x) and makes the relevant test for a new runtimeclass `qemu-se-runtime-rs`. 
For details, please look into each commit message.
=> runtime-rs Enable initdata IBM SEL

src/runtime-rs/config/configuration-qemu-se-runtime-rs.toml.in
The default `reconnect_timeout` (3 seconds) was found to be insufficient for IBM SEL when using VSOCK, which led to the following:
```
: connect to address \"vsock://2057012271\"\n    1: connect agent server\n    2: connect\n    3: cannot connect vsock to agent ttrpc server ConnectConfig { dial_timeout_ms: 30, reconnect_timeout_ms: 3000 }\n\nStack backtrace:\n   0: <agent::sock::vsock::Vsock as agent::
sock::Sock>::connect::{{closure}}\n   1: agent::kata::agent::<impl agent::AgentManager for agent::kata::KataAgent>::start::{{closure}}\n   2: <virt_container::sandbox::VirtSandbox as common::sandbox::Sandbox>::start::{{closure}}::{{closure}}\n   3: <virt_container::sand
box::VirtSandbox as common::sandbox::Sandbox>::start::{{closure}}\n   4: …
```
=> runtime-rs: Adjust VSOCK timeouts for IBM SEL

src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
we also need support initdat within nonprotection even though the platform is detected as NonProtection or usually is called nontee host. Within these cases, there's no need to validate the item of `confidential_guest=true`, we believe the result of the method `available_guest_protection()?`.
Fixes #11697
=> runtime-rs: Support initdata within NonProtection scenarios

src/runtime/config/configuration-qemu-coco-dev.toml.in, src/runtime/config/configuration-qemu-nvidia-gpu-snp.toml.in, src/runtime/config/configuration-qemu-nvidia-gpu-tdx.toml.in, src/runtime/config/configuration-qemu-nvidia-gpu.toml.in, src/runtime/config/configuration-qemu-se.toml.in, src/runtime/config/configuration-qemu-snp.toml.in, src/runtime/config/configuration-qemu-tdx.toml.in, src/runtime/config/configuration-qemu.toml.in, src/runtime/pkg/device/config/config.go, src/runtime/pkg/govmm/qemu/qemu.go, src/runtime/pkg/govmm/qemu/qemu_arch_base_test.go, src/runtime/pkg/govmm/qemu/qemu_s390x_test.go, src/runtime/pkg/katautils/config.go, src/runtime/virtcontainers/qemu.go, src/runtime/virtcontainers/qemu_arch_base.go
Similar to what we've done for Cloud Hypervisor in the commit 9f76467cb77bbefbe04017d3ff1fbd52b6f3c7dd, we're backporting a runtime-rs feature that would be benificial to have as part of the go runtime.
This allows users to use virito-balloon for the hypervisor to reclaim memory freed by the guest.
=> runtime: qemu: Add reclaim_guest_freed_memory [BACKPORT]

src/runtime/pkg/resourcecontrol/cgroups.go, src/runtime/virtcontainers/sandbox.go
ef642fe8900fb1ee1daae6501bbd6bae3aa50d3a added a special case to avoid
moving cgroups that are on the "default" slice in case of deletion.
However, this special check should be done in the Parent() method
instead, which ensures that the default resource controller ID is
returned, instead of ".".
Fixes: #11599
=> cgroups: Fix "." parent cgroup special case

src/libs/kata-types/src/fs.rs, src/libs/kata-types/src/lib.rs, src/runtime-rs/crates/hypervisor/src/kernel_param.rs, src/runtime-rs/crates/hypervisor/src/lib.rs, src/runtime-rs/crates/resource/src/rootfs/block_rootfs.rs
- Set guest Storage.options for block rootfs to empty (do not propagate host mount options).
- Align behavior with Go runtime: only add xfs "nouuid" when needed.
Fixes #11688
=> runtime-rs: Empty block-rootfs Storage.options and align with Go runtime

src/tools/genpolicy/rules.rego
Print the Storage data structures, to help with debugging.
=> genpolicy: print Input and Policy storages

src/runtime-rs/crates/runtimes/virt_container/src/container_manager/container.rs
In certain scenarios, particularly under CoCo/Agent Policy enforcement, the default initial value of `Linux.Resources.Devices` is considered non-compliant, leading to container creation failures. 
To address this issue and ensure consistency with the behavior in `runtime-go`, this commit removes the default value of `Linux.Resources.Devices` from the OCI Spec. 
This cleanup ensures that the OCI Spec aligns with runtime expectations and prevents policy violations during container creation.
And we also need ensure the setting of hooks when OCI Hooks is existing. Only the StartContainer hook needs to be reserved for execution in the guest, but we also make sure that the setting happens only when the OCI Hooks does exist, otherwise we do nothing.
Signed-off-by: Alex Lyn …
=> runtime-rs: Remove default value of Linux.Resources.Devices and correctly set Hooks in OCI Spec to meet with Agent Policy requirements

.github/workflows/zizmor.yaml
These are all the issues found in this PR with this mode:
https://github.com/kata-containers/kata-containers/security/code-scanning?page=1&query=is%3Aopen+tool%3Azizmor+pr%3A11615
I will fix those existing issues in separate PRs. In the meantime, any PR that introduces more such issues will be blocked and will have to be fixed.
=> security: gha: Run Zizmor in auditor mode

src/tools/agent-ctl/Cargo.lock
Bump the version of runtime-rs' hypervisor crate
to upgrade (indirectly) protobug and remediate vulnerability RUSTSEC-2024-0437
=> agent-ctl: version: bump hypervisor

tests/go.mod, tests/go.sum, tests/vendor/gopkg.in/yaml.v3/parserc.go, tests/vendor/modules.txt
Bump gopkg.in/yaml.v3 from 3.0.0 to 3.0.1 to remediate CVE-2022-28948
=> versions: Bump gopkg.in/yaml.v3

src/libs/kata-types/src/config/agent.rs, src/runtime-rs/config/configuration-cloud-hypervisor.toml.in, src/runtime-rs/config/configuration-dragonball.toml.in, src/runtime-rs/config/configuration-qemu-runtime-rs.toml.in, src/runtime-rs/config/configuration-qemu-se-runtime-rs.toml.in, src/runtime-rs/config/configuration-remote.toml.in, src/runtime-rs/config/configuration-rs-fc.toml.in
Since it aligns with the create_container_timeout definition in runtime-go, we need to set the value in configuration.toml in seconds, not milliseconds. We must also convert it to milliseconds when the configuration is loaded for request_timeout_ms.
Signed-off-by: Alex Lyn [alex.lyn@antgroup.com](mailto:alex.lyn@antgroup.com)
=> kata-types: Support create_container_timeout set within configuration

src/runtime-rs/crates/resource/src/rootfs/virtual_volume.rs
As prvious configure with overlayfs is incorrect, which causes the agent policy validation failure. And it's also different with runtime-go's configuration. In this patch, we'll correct its fstype with overlay and align with runtime on this matter.
=> runtime-rs: Bugfix for kata virtual volume overlay fstype

src/runtime-rs/crates/hypervisor/src/qemu/qmp.rs
Support for the share-rw=true parameter has been added. While this parameter is essential for maintaining data consistency across multiple QEMU instances sharing a backend disk image, its implementation also serves to standardize parameters with the block device hotplug functionality in kata-runtime/qemu.
It mainly address such issue when we run nontee CI, which described as below:
```
failed to create containerd task: failed to create shim task: Others("failed to handle message create container\n\nCaused by:\n    0: do handle device\n    1: failed to add deivce\n    2: hotplug block device\n    3: blockdev-add backend Qapi(Error { class: GenericError, desc: \"Duplicate nodes with node-name='drive-1'\", id: None })\n\nStack backtrace:\n   0: anyhow::error::<impl anyhow::Error>::msg\n   1: …
```
=> runtime-rs: Enable share-rw=true when hotplug block device within qemu

src/libs/kata-sys-util/src/k8s.rs, src/libs/kata-types/src/mount.rs, src/runtime-rs/crates/resource/src/manager.rs, src/runtime-rs/crates/resource/src/manager_inner.rs, src/runtime-rs/crates/resource/src/share_fs/mod.rs, src/runtime-rs/crates/resource/src/volume/ephemeral_volume.rs, src/runtime-rs/crates/resource/src/volume/mod.rs, src/runtime-rs/crates/resource/src/volume/shm_volume.rs, src/runtime-rs/crates/runtimes/common/src/types/mod.rs, src/runtime-rs/crates/runtimes/common/src/types/trans_from_shim.rs, src/runtime-rs/crates/runtimes/src/manager.rs, src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
Docker containers support specifying the shm size using the --shm-size option and support sandbox-level shm volumes, so we've added support for shm volumes. Since Kubernetes doesn't support specifying the shm size, it typically uses a memory-based emptydir as the container's shm, and its size can be specified.
=> runtime-rs: add the sandbox's shm volume support

src/tools/agent-ctl/Cargo.toml, src/tools/agent-ctl/src/vm/vm_ops.rs
agent-ctl's make check has been failing with:
```
Checking kata-agent-ctl v0.0.1 (/home/ubuntu/runner/_layout/_work/kata-containers/kata-containers/src/tools/agent-ctl)
error[E0432]: unresolved import `hypervisor::ch`
--> src/vm/vm_ops.rs:10:5
|
10 |     ch::CloudHypervisor,
|     ^^ could not find `ch` in `hypervisor`
|
note: found an item that was configured out
--> /home/ubuntu/runner/_layout/_work/kata-containers/kata-containers/src/runtime-rs/crates/hypervisor/src/lib.rs:30:9
|
30 | pub mod ch;
|         ^^
note: the item is gated here
--> /home/ubuntu/runner/_layout/_work/kata-containers/kata-containers/src/runtime-rs/crates/hypervisor/src/lib.rs:26:1
|
26 | / #[cfg(all(
27 | |     feature = "cloud-hypervisor",
28 | |     any(target_arch = "x86_64", target_arch = "aarch64")
29 | | …
```
=> tools: agent-ctl: Fix unresolved ch import

utils/kata-manager.sh
On 63f6dcdeb9d5542fc6bf0c5a9461999ee13b30ff we added the support to download either a .xz or a .zst tarball file. However, we missed adding the code to properly unpack a .zst tarball file.
=> kata-manager: Handle zst unpacking

src/runtime/virtcontainers/qemu_s390x.go, src/runtime/virtcontainers/qemu_s390x_test.go
On s390x, QEMU fails if maxmem is set to 0 (#11681):
```
invalid value of maxmem: maximum memory size (0x0) must be at least the initial memory size
```
This PR sets maxmem to the initial memory size for s390x when hotplug is disabled, resolving the error while still ensuring that memory hotplug remains off.
=> runtime: Set maxmem to initialmem on s390x when memory hotplug is disabled

tools/osbuilder/rootfs-builder/nvidia/nvidia_chroot.sh
Lets make sure that we use the real latest for the CI and releases. There was a sort missing. We picked up the driver that `apt-cache` delivered rather than the latest. Added `sort` to the parsing when `latest` is specified.
=> gpu: Add correct latest driver per default

src/libs/kata-types/src/config/hypervisor/mod.rs, src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs, src/runtime-rs/crates/hypervisor/src/ch/mod.rs, src/runtime-rs/crates/hypervisor/src/dragonball/inner_hypervisor.rs, src/runtime-rs/crates/hypervisor/src/dragonball/mod.rs, src/runtime-rs/crates/hypervisor/src/firecracker/inner.rs, src/runtime-rs/crates/hypervisor/src/firecracker/inner_hypervisor.rs, src/runtime-rs/crates/hypervisor/src/firecracker/mod.rs, src/runtime-rs/crates/hypervisor/src/lib.rs, src/runtime-rs/crates/hypervisor/src/qemu/inner.rs, src/runtime-rs/crates/hypervisor/src/qemu/mod.rs, src/runtime-rs/crates/hypervisor/src/remote/inner.rs, src/runtime-rs/crates/hypervisor/src/remote/mod.rs, src/runtime-rs/crates/hypervisor/src/selinux.rs, src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs, src/tools/agent-ctl/src/vm/vm_ops.rs
Add SELinux label support for QEMU process in Kata Containers
This PR implements SELinux label support with the following changes:
1. Add SELinux configuration fields to hypervisor config:
- Add `disable_selinux` flag
2. Set SELinux label for QEMU process:
- Check if SELinux is enabled and enforcing
- Apply the SELinux label to QEMU process before launching
- Handle cases where SELinux is not enabled gracefully
3. Read SELinux label from OCI spec:
- Extract SELinux label from container's OCI spec process configuration
- Handle cases where spec or label is not available
update: my latest results
```yaml
metadata:
attempt: 1
name: test-pod1
namespace: default
uid: hdishd83djaidwnduwk28bcsb
log_directory: /tmp
linux:
security_context:
selinux_options:  
user: "system_u"
role: "system_r" …
```
=> runtime-rs: align SELinux feature with runtime-go (#9866)

src/runtime-rs/crates/hypervisor/src/device/device_manager.rs, src/runtime-rs/crates/hypervisor/src/device/driver/mod.rs, src/runtime-rs/crates/resource/src/cpu_mem/swap.rs, src/runtime-rs/crates/resource/src/manager_inner.rs, src/runtime-rs/crates/resource/src/rootfs/block_rootfs.rs, src/runtime-rs/crates/resource/src/volume/block_volume.rs, src/runtime-rs/crates/resource/src/volume/direct_volumes/rawblock_volume.rs, src/runtime-rs/crates/resource/src/volume/direct_volumes/spdk_volume.rs, src/runtime-rs/crates/runtimes/virt_container/src/sandbox.rs
The commits introduce a new configuration option that allows users to specify the block device I/O mode on a per-device basis.
Previously, all block devices were configured to use a single, unified AIO mode (defaulting to `io_uring`). This change provides more granular control, enabling users to explicitly configure the AIO mode for each device through the configuration file.
This new feature improves flexibility and allows for more tailored performance tuning based on specific workload requirements.
=> Enhance block device AIO mode

src/runtime-rs/Makefile
Change the default block driver to virtio-scsi.
Since the latest qemu's commit:
https://gitlab.com/qemu-project/qemu/-/commit/
984a32f17e8dab0dc3d2328c46cb3e0c0a472a73
brings a bug for virtio-blk-pci with io_uring mode at line: https://gitlab.com/qemu-project/qemu/-/commit/984a32f17e8dab0dc3d2328c46cb3e0c0a472a73#ce8eeb01f8b84f8cb8d3c35684d473fe1ee670f9_345_352
In order to avoid this issue, change the default block driver to virtio-scsi.
=> runtime-rs: set the default block driver as virtio-scsi for qemu

tests/functional/kata-agent-apis/api-tests/test_vm_GuestDetails.bats
This change fixes clean up logic when running tests in a vm booted with qemu wrt to qmp.sock & console.sock files, and no longer assumes any path for them.
=> tests: agent-ctl: Fix cleanup for testing with qemu

tests/integration/kubernetes/runtimeclass_workloads/confidential/unencrypted/Dockerfile
We recently hit the following error during build:
```
RUN ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -P ""
OpenSSL version mismatch. Built against 3050003f, you have 30500010
```
This happened because `alpine:latest` moved forward and the `ssh-keygen` binary in the base image was compiled against a newer OpenSSL version that is not available at runtime.
Pinning the base image to the stable release (3.20) avoids the mismatch and ensures consistent builds.
=> GHA: Pin Alpine to 3.20 for tee-unencrypted image

src/tools/csi-kata-directvolume/README.md, src/tools/csi-kata-directvolume/cmd/directvolplugin/main.go, src/tools/csi-kata-directvolume/deploy/kata-directvolume/csi-directvol-plugin.yaml, src/tools/csi-kata-directvolume/docs/spdk-usage.md, src/tools/csi-kata-directvolume/examples/pod-with-spdkvol/csi-app.yaml, src/tools/csi-kata-directvolume/examples/pod-with-spdkvol/csi-pvc.yaml, src/tools/csi-kata-directvolume/examples/pod-with-spdkvol/csi-storageclass.yaml, src/tools/csi-kata-directvolume/pkg/directvolume/controllerserver.go, src/tools/csi-kata-directvolume/pkg/directvolume/controllerserver_test.go, src/tools/csi-kata-directvolume/pkg/directvolume/directvolume.go, src/tools/csi-kata-directvolume/pkg/directvolume/nodeserver.go, src/tools/csi-kata-directvolume/pkg/directvolume/nodeserver_test.go, src/tools/csi-kata-directvolume/pkg/spdkrpc/jsonrpc.go, src/tools/csi-kata-directvolume/pkg/state/state.go, src/tools/csi-kata-directvolume/pkg/utils/utils.go
Introduce initial implementation for SPDK-backed CSI volumes, allowing basic create and delete operations with vhost-user-blk integration.
Fixes: #9704
=> csi-kata-directvolume: Add basic SPDK volume support

tests/integration/kubernetes/runtimeclass_workloads/confidential/unencrypted/Dockerfile
The Hadolint warning DL3007 (pin the version explicitly) is no longer applicable.
We have updated the base image to use a specific version digest, which satisfies the linter's requirement for reproducible builds. This PR removes the corresponding inline ignore comment.
=> ci: Remove DL3007 ignore comment for base image

.github/workflows/zizmor.yaml, tools/testing/gatekeeper/required-tests.yaml
```
gha: Run Zizmor without Advanced Security
This does not change the security of the analysis, this is just to work
around zizmorcore/zizmor-action#43.
```
```
gha: Set Zizmor check as non-required
As a consequence of moving away from Advanced Security for Zizmor, it now
checks the entire codebase and will error out on this PR and future.
To be reverted once we address all Zizmor findings in a future PR.
```
=> gha: Run Zizmor without Advanced Security

tests/integration/kubernetes/k8s-parallel.bats, tests/integration/kubernetes/lib.sh, tests/integration/kubernetes/tests_common.sh
```
-o pipefail in particular ensures that exec_host() returns the right exit
code.
-u is also added for good measure. Note that $BATS_TEST_DIRNAME is set by
bats so we move its usage inside the function.
```
=> tests/k8s: Add set -euo pipefail to lib.sh

tools/osbuilder/rootfs-builder/nvidia/nvidia_rootfs.sh
Since we cannot build all components with libc=musl and
static RUSTFLAG we still need to ship libcc for AA or other guest
components.
=> gpu: Add libgcc for RUST libc=gnu builds

src/libs/kata-sys-util/src/mount.rs
- Test was failing on ppc64le due to larger system page size (e.g., 65536 bytes)
- Original test used a hardcoded 4097-byte string assuming 4KB page size
- Replaced with *MAX_MOUNT_PARAM_SIZE + 1 to reflect actual system limit
- Ensures test fails correctly across all architectures
Fixes: #11852
Signed-off-by: shwetha-s-poojary <shwetha.s-poojary@ibm.com>
=> libs: Fix the test_parse_mount_options failure on ppc64le

tests/integration/kubernetes/k8s-credentials-secrets.bats, tests/integration/kubernetes/k8s-liveness-probes.bats, tests/integration/kubernetes/k8s-nginx-connectivity.bats
Add auto-generated agent policy for:
k8s-credentials-secrets.bats
k8s-liveness-probes.bats
k8s-nginx-connectivity.bats
Most other k8s tests are already using auto-generated policy, for CoCo and cbl-mariner tests.
=> tests: k8s: auto-generate policy for additional tests

.github/workflows/darwin-tests.yaml, ci/darwin-test.sh, src/agent/Cargo.toml, src/libs/kata-types/Cargo.toml, src/libs/kata-types/src/mount.rs, src/runtime-rs/Cargo.toml, src/tools/genpolicy/Cargo.lock, src/tools/kata-ctl/Cargo.toml, tests/common.bash, tests/install_rust.sh
Overall, the goal is to build the genpolicy package in CI (eventually as required job), such that we learn of darwin support regressions in the tool. This PR adds the build to the existing, non-required darwin CI job, so that we can monitor its stability.  
Prerequisite: allow using `kata-types` on non-Linux
Drive-by: fix shellcheck issues in install_rust.sh
Fixes: #11635
=> ci: add genpolicy build for Darwin

src/runtime/pkg/katautils/config-settings.go.in, src/runtime/pkg/katautils/config.go, src/runtime/pkg/katautils/config_test.go
85f3391bc added the support for TDX QGS port=0 but missed defaultQgsPort in the default config. defaultQgsPort overrides user provided tdx_quote_generation_service_socket_port=0.
After this change, defaultQgsPort is not needed anymore since there's no default: any positive integer is OK and negative or unset value becomes a parse error.
QEMUTDXQUOTEGENERATIONSERVICESOCKETPORT in the Makefile is used to provide a sane default when tdx_quote_generation_service_socket_port gets set in the configuration.
=> runtime: config: allow TDX QGS port=0

.github/workflows/nydus-snapshotter-version-in-sync.yaml, .github/workflows/run-kata-coco-tests.yaml, tests/common.bash, tests/gha-run-k8s-common.sh, tests/integration/kubernetes/gha-run.sh, tools/packaging/kata-deploy/Dockerfile, tools/packaging/kata-deploy/helm-chart/kata-deploy/templates/kata-deploy.yaml, tools/packaging/kata-deploy/helm-chart/kata-deploy/templates/post-delete-job.yaml, tools/packaging/kata-deploy/helm-chart/kata-deploy/values.yaml, tools/packaging/kata-deploy/nydus-snapshotter/config-guest-pulling.toml, tools/packaging/kata-deploy/nydus-snapshotter/nydus-snapshotter.service, tools/packaging/kata-deploy/scripts/kata-deploy.sh, versions.yaml
Please, see each commit message for a better explanation of what each commit does.
=> kata-deploy: Add the ability to set up different snapshotters (nydus & erofs)

src/tools/genpolicy/rules.rego, src/tools/genpolicy/src/mount_and_storage.rs, tests/integration/kubernetes/k8s-volume.bats
Mount paths ending in '/' were not parsed correctly.
Also, auto-generate policy from k8s-volume.bats - the test that exposed this genpolicy bug by using the "/mnt/" path.
=> genpolicy: better parsing of mount path

tools/packaging/kata-deploy/scripts/kata-deploy.sh
Canonical TDX release is not needed for vanilla Ubuntu 25.10 but GRUB_CMDLINE_LINUX_DEFAULT needs to contain `nohibernate` and `kvm_intel.tdx=1`
=> kata-deploy: accept 25.10 as supported distro for TDX

tests/integration/kubernetes/k8s-privileged.bats, tests/integration/kubernetes/run_kubernetes_tests.sh, tests/integration/kubernetes/runtimeclass_workloads/pod-privileged.yaml
This adds an integration test to verify that privileged containers work properly when deploying Kata with kata-deploy.
This is a follow-up to #11878.
=> tests/k8s: Add test for privileged containers
